### ISSUE TITLE
Add git hooks for validation of notebooks before commit

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#10]

**Comment by gipster** [comment]
I think it should work as explained here http://timstaley.co.uk/posts/making-git-and-jupyter-notebooks-play-nice/
It says to create a .gitattribute file the repository and add

[filter "nbstrip_full"]
clean = "jq --indent 1 \
        '(.cells[] | select(has(\"outputs\")) | .outputs) = []  \
        | (.cells[] | select(has(\"execution_count\")) | .execution_count) = null  \
        | .metadata = {\"language_info\": {\"name\": \"python\", \"pygments_lexer\": \"ipython3\"}} \
        | .cells[].metadata = {} \
        '"
smudge = cat
required = true

*.ipynb filter=nbstrip_full

**Comment by cliveseldon** [comment]
Let's decide if this is still useful.
