### ISSUE TITLE
Empty Children array on a Seldon Deployment causes ArgoCD sync issues

### ISSUE THREAD

**Issue by gsunner** [SeldonIO/seldon-core#1009]
When an empty Children array (in the graph) is part of a Seldon Deployment, ArgoCD will see this as out of syc with whats in the cluster.

The reason is this array is omitted if empty.
In the operator code
```
type PredictiveUnit struct {
	Name               string                        `json:"name" protobuf:"string,1,opt,name=name"`
	Children           []PredictiveUnit              `json:"children,omitempty" protobuf:"bytes,2,opt,name=children"`
        ...
}
```

The operator does add other data to the deployment, but ArgoCd is able to deal with those differences, but not the difference in the omitted Children array.

**Comment by cliveseldon** [comment]
could not replicate.
