### ISSUE TITLE
switching between application/x-www-form-urlencoded and application/json

### ISSUE THREAD

**Issue by blublinsky** [SeldonIO/seldon-core#1013]
When implementing Seldon component models, I would like my components to be invoked using application/json not application/x-www-form-urlencoded.
Is there a flag that tells Seldon Core to use application/json for interacting with components?
Is it documentation or implementation issue?

**Comment by cliveseldon** [comment]
I think we should as this by default if its not in the engine right now. Is there any reason we need a flag?

**Comment by blublinsky** [comment]
There should be some way to configure it, whether this is a flag or not - you decide

**Comment by cliveseldon** [comment]
Will be fixed by #1016
