### ISSUE TITLE
Splitting and routing requests

### ISSUE THREAD

**Issue by rickymyl-karhoo** [SeldonIO/seldon-core#1037]
Currently we can use a router to determine which child branch to use for each prediction requests we make. However there is no splitting mechanism. E.g. I have 10 rows of data in my prediction request, it is not possible to route the first 5 rows to child A  and the later 5 rows into child B. This is not very convenient as it often requires splitting of requests on the client side.

**Comment by axsaucedo** [comment]
This would be a different use-case to the one routing was initially designed for. Sounds like it qould be interesting as it would enable distrbuted processing, however as it currently stands, this would not be something that would be processed in the routing functionality, as the static nature of it makes it sub-optimal. Other solutions like Ray are better suited for distributed processing of data.

We will be exploring a workstream on batch processing, but even in this workstream we're only exploring async processing, but we're still not looking to enable for distributed data processing.

**Comment by PouyaKrew** [comment]
We are interested in such functionality too. I wonder if you have such a feature in your backlog?

**Comment by cliveseldon** [comment]
I think we should consider these options further in how we can achieve routing that is more powerful that we have at present. @PouyaKrew and @rickymyl-karhoo would you be interested in helping here?

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
[Tempo](https://github.com/SeldonIO/tempo) would be a solution for this. Please try if still an issue.
