### ISSUE TITLE
Create documentation to help debugging

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1038]
Most times, issues with Seldon Core can be fixed (or at least idenfitied) with the same set of tools/steps. For example: 

- Check if the pod is receiving the request
- Check if all services inside the pods are up
- Check the pod events to see why some service is not up
- Check the logs for each of the services inside the pod
- etc.

It would be good to create a page in the docs explaining how to perform each of these to help troubleshooting problems.

**Comment by adriangonz** [comment]
This can be added to the [Troubleshooting Guide](https://docs.seldon.io/projects/seldon-core/en/latest/workflow/troubleshooting.html).

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Closing with new docs now available.
