### ISSUE TITLE
How to Deploy our custom models on seldon-core

### ISSUE THREAD

**Issue by irrationaldomain** [SeldonIO/seldon-core#104]
hi,
I am able to get seldon core up and running on kubernetes cluster  and tried deploying your example models , got successful . Now my aim is to deploy our custom model on seldon-core, so what is the procedure/requirements in order to deploy our model plus are there any conventions we have to follow .  FYI I have simple  model which uses tensorflow and flask framework, so what are the things need to consider before wrapping model.
One more thing I want to know that is it necessary that model we are deploying will have to be a saved model only?
thanks in advance

**Comment by cliveseldon** [comment]
Wrapping your tensorflow python model is very easy.

There are detailed instructions [here](https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/readme.md)
On our kubeflow end-to-end example you can see an example [tensorflow runtime component](https://github.com/kubeflow/example-seldon/blob/master/models/tf_mnist/runtime/DeepMnist.py) and the [script to wrap it using our docker image for python]( https://github.com/kubeflow/example-seldon/blob/master/models/tf_mnist/runtime/wrap.sh)

To answer your last question if I understand it, you can get your model parameters and weights from any file system that can be attached to kubernetes. Again [see this deployment file](https://github.com/kubeflow/example-seldon/blob/master/k8s_serving/serving_model.json) which uses a volume which contains the saved model weights which the runtime will load on startup.

**Comment by irrationaldomain** [comment]
After python wrapping got **ImportError**  pointing to microservice.py
showing as follows

 **Traceback (most recent call last):
  File "microservice.py", line 154, in <module>
    interface_file = importlib.import_module(args.interface_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)  
ImportError: No module named demo-model** 
here demo-model is my docker image name

**Comment by cliveseldon** [comment]
This looks like an issue in the wrapping process. In the example in the docs we have

```
docker run -v /path/to/model/dir:/my_model seldonio/core-python-wrapper:0.7 /my_model MnistClassifier 0.1 seldonio
```

which refers to a class: 
```
class MnistClassifier(object): # The file is called MnistClassifier.py
```

Note the class name and file match. Is this the case in your test?

**Comment by irrationaldomain** [comment]
I have Deploy custom model which has simple request( for eg. [2000] ). which is running fine on local but I am not able to get response when i am running it on seldon. So Is there any specific format to send request ??

**Comment by cliveseldon** [comment]
Please reopen if still an issue.
