### ISSUE TITLE
Broken imports on 0.5.0.2 release

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1040]
## What's failing?

On the latest release, there are some missing files. In particular, the pre-compiled `tensorflow` protobuffs introduced in #942 are not included. This breaks some import paths **when `tensorflow` is not present**.

For instance,

```python
>>> from seldon_core import utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/agm/.virtualenvs/fresh/lib/python3.6/site-packages/seldon_core/utils.py", line 10, in <module>
    from seldon_core.proto import prediction_pb2
  File "/home/agm/.virtualenvs/fresh/lib/python3.6/site-packages/seldon_core/proto/prediction_pb2.py", line 17, in <module>
    from seldon_core.proto.tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
ModuleNotFoundError: No module named 'seldon_core.proto.tensorflow'
```

## Suggested fix

We need to add the missing files to the `MANIFEST.in` file, so that they get included in the `sdist` release. To avoid this happening again in the future, we can introduce [`tox`](https://github.com/tox-dev/tox), which will wrap our tests and then run them in a fresh new environment each time (created from the `setup.py` manifest).

**Comment by gsunner** [comment]
0.5.0.3 release should now fix this
