### ISSUE TITLE
Multiple helm seldon-core installs on separate namespaces fails

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#106]
helm install ../helm-charts/seldon-core --name seldon-core-graphs \
        --set cluster_manager.rbac=true \
        --set cluster_manager_service_type=LoadBalancer \
        --set apife_service_type=LoadBalancer \
        --namespace graphs

Error: release seldon-core-graphs failed: clusterrolebindings.rbac.authorization.k8s.io "seldon" already exists

**Comment by gsunner** [comment]
added PR #146
