### ISSUE TITLE
Explore creation of a "batching" transformer

### ISSUE THREAD

**Issue by Maximophone** [SeldonIO/seldon-core#107]
The unit would receive requests and aggregate them in a certain batch size.

The behaviour would be something like this:

Input transformation:
When receiving new request, store it in memory and wait (needs multithreading)
When enough requests have been received, returns a batch in one of them, nothing in the others

Output transformation:
Wait until all outputs have arrived
split the one containing the batch into all the others
return all

**Comment by erandagan** [comment]
It's worth mentioning that TFServing has a [pretty flexible batching configuration](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/batching)
which can be used for inspiration.

**Comment by cliveseldon** [comment]
More likely to be part of core model servers such as tfserving or tensorrt inference server.
