### ISSUE TITLE
following tutorial  got 503

### ISSUE THREAD

**Issue by whitelilis** [SeldonIO/seldon-core#1073]
I followed https://docs.seldon.io/projects/seldon-core/en/latest/examples/ambassador_canary.html , 
it seems deploys ok.

![image](https://user-images.githubusercontent.com/1090230/68459296-f08a1d80-023f-11ea-84f7-003e4862a080.png)

and when  using `kubectl exec -it `  into the pod,  the classifier seems work too.
![image](https://user-images.githubusercontent.com/1090230/68459394-41017b00-0240-11ea-917b-145ebb1bbfae.png)

but when access from the outside, got 503
![image](https://user-images.githubusercontent.com/1090230/68459434-642c2a80-0240-11ea-9606-3d73020dbdf4.png)
![image](https://user-images.githubusercontent.com/1090230/68459448-6bebcf00-0240-11ea-83dc-e6db6079b9c3.png)
![image](https://user-images.githubusercontent.com/1090230/68459484-84f48000-0240-11ea-8738-f1d0c5dca8ef.png)

it seems that  the microservice not got the request

**Comment by whitelilis** [comment]
![image](https://user-images.githubusercontent.com/1090230/68459862-6b076d00-0241-11ea-8762-fd61b9bc7f85.png)

![image](https://user-images.githubusercontent.com/1090230/68459875-765a9880-0241-11ea-93bf-e0763c99b3d2.png)

**Comment by cliveseldon** [comment]
That is strange. Can you check the Ambassador diagnostics: https://docs.seldon.io/projects/seldon-core/en/latest/workflow/troubleshooting.html#i-get-404s-when-calling-the-ambassador-endpoint

And maybe also run the basic examples notebook to check they work: https://github.com/SeldonIO/seldon-core/blob/master/notebooks/helm_examples.ipynb

**Comment by cliveseldon** [comment]
Closing this but please reopen if still an issue and the above tests still fail for you.
