### ISSUE TITLE
Grafana Dashboard 

### ISSUE THREAD

**Issue by irrationaldomain** [SeldonIO/seldon-core#109]
Hi,
I have deployed seldon-core on kubernetes cluster. Now i want to know how can we access grafana dashboard in order to monitor our deployed models on seldon-core.

**Comment by cliveseldon** [comment]
You need to install via helm seldon-core-analytics and then port forward the grafana dashboard. You can login via admin with the password you set in helm. An example is given in the [minikube worked example notebook](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/kubectl_demo_minikube.ipynb).

**Comment by anneqzou** [comment]
Hi,
I have the same situation - deployed seldon-core on kubernetes cluster and deployed example model in the repo. After that I  followed instructions shared in above notebook, but I am not able to see anything in Seldon Deploy Prediction API Dashboard. Did I miss something for setup? 

Thanks,
Anne

**Comment by cliveseldon** [comment]
Have you done the port forward to grafana?
```
kubectl port-forward $(kubectl get pods -n seldon -l app=grafana-prom-server -o jsonpath='{.items[0].metadata.name}') -n seldon 3000:3000
```
If you did above - are you using the same namespace as in the example? Above its "seldon". You would need to change this if you started seldon-core in a different namespace.

If so are you saying you can see the dashboard but no stats in it? If this is what you man then have you run some prediction requests?

**Comment by cliveseldon** [comment]
@irrationaldomain  Did this work?

**Comment by anneqzou** [comment]
Thanks for looking at this problem, I missed this mail.

Above command didn't work as I used it when I set up the dashboard.

The root cause is permission, I worked around by assigning admin role to
account running the service.
