### ISSUE TITLE
Upgrade Maven and JDK on CI image

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1094]
Our CI image `seldonio/core-builder:0.4` currently uses version `v3.3.9` of Maven, which is dated from 2015. Likewise, the base `openjdk:8u141-jdk` Docker image we are using is also 2 years old. It would be good to update both so that it matches local development environments.

**Comment by ryandawsonuk** [comment]
For the PR builds it now seems to be on `seldonio/core-builder:0.6`

**Comment by ryandawsonuk** [comment]
It seems 3.3.9 is the latest available for that debian distro. May be able to override it though.

**Comment by gsunner** [comment]
Added PR #1231 to address the core builder changes
The new versions will be
