### ISSUE TITLE
Move CRD to v1

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1100]
* Will need to investigate Kubebuilder multi-version support.

**Comment by adriangonz** [comment]
Ideally, we want to to rename the current `operator/pkg/apis/v1alpha2` package to `operator/pkg/apis/v1`. On top of this, we also want to list versions `v1alpha2` **and `v1alpha3`** (see #890).

**Comment by adriangonz** [comment]
It seems that the recommended way by `kubebuilder` to expose multiple versions is to have multiple packages, one per version. This is the approach taken by a few projects, including `knative` (https://github.com/knative/serving/tree/master/pkg/apis/serving).

In our case, to follow this pattern we would need to duplicate the `apis/v1alpha2` folder into `apis/v1alpha3` and `apis/v1`. 

Note that these versions refer only to the `SeldonDeployment` CRD. Therefore, as new versions of Seldon Core come out, we could phase these deprecated packages/versions out. For example,

- `v1.0` would have the three folders: `v1alpha2`, `v1alpha3` and `v1` (marking `v1` for storage).
- `v1.1` would phase out `v1alpha2` and `v1alpha3`. Everyone on `v1.0` would get encouraged to update to update their `SeldonDeployment` resources to `v1` before upgrading to Seldon Core `v1.1.`.

This seems to be the most straightforward solution, even though it involves duplicating code temporarily.
