### ISSUE TITLE
tfjob problem in seldon example in latest kubeflow pipelines

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1111]
Seems to be broken by recent kubeflow changes - see https://github.com/kubeflow/pipelines/issues/2615 and https://github.com/kubeflow/example-seldon/issues/43

In the pipeline example even after changing the version I found the training step went into a loop logging:
```
time="2019-11-15T15:23:59Z" level=warning msg="Command for kubectl get -w for TFJob.kubeflow.org/mnist-train-2c70cb81-7eae-4000-b0f1-9a37230cefe6 exited. Getting return value using Wait"
time="2019-11-15T15:23:59Z" level=warning msg="cmd.Wait for kubectl get -w command for resource TFJob.kubeflow.org/mnist-train-2c70cb81-7eae-4000-b0f1-9a37230cefe6 returned error exit status 1"
time="2019-11-15T15:23:59Z" level=info msg="Waiting for resource TFJob.kubeflow.org/mnist-train-2c70cb81-7eae-4000-b0f1-9a37230cefe6 resulted in retryable error exit status 1"
time="2019-11-15T15:24:04Z" level=info msg="kubectl get TFJob.kubeflow.org/mnist-train-2c70cb81-7eae-4000-b0f1-9a37230cefe6 -w -o json -n kubeflow"
time="2019-11-15T15:24:04Z" level=warning msg="Json reader returned error EOF. Calling kill (usually superfluous)"
```
Submitting the TFJob directly by kubectl did work though so not sure if that issue is related to TFJob or my pipelines setup. I think I need update my pipelines SDK version and rebuild.

**Comment by ryandawsonuk** [comment]
Have updated SDK but same problem. Seems like the root problem is that the pipeline [never actually submits the TFJob resource](https://github.com/kubeflow/pipelines/issues/2624)

**Comment by cliveseldon** [comment]
Closing as Kubeflow example deprecated.
