### ISSUE TITLE
how to define MyModel for PyTorch model which has more than one arguments?

### ISSUE THREAD

**Issue by whitelilis** [SeldonIO/seldon-core#1115]
as https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html  said, I can handle one argument models.
but my scientist has the following model:
```
model = torch.load( 'deepfm_baseline_v0')
predict_result = model(batch_xi, batch_xv)
```
how can I wrap it?

**Comment by axsaucedo** [comment]
For this you would be able to take multiple approaches. The first one is to just use the data ndarray format, as you can send n-dimensional numpy arrays. If that doesn't work you can use the jsonData format to send anything you want, or the strata/binData if your data is quite custom (using pickle or stringifying)
