### ISSUE TITLE
Explore alternatives to protobufs's Struct and Value

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1119]
## Context

On the [`prediction.proto`](https://github.com/SeldonIO/seldon-core/blob/master/proto/prediction.proto) definition, we use type `google.protobuf.Value` to encode for "any" object that gets passed as `jsonData` (through `google.protobuf.Struct`) or `data.ndarray` (through `google.protobuf.ListValue`). 

One of the problems of this type, is that [it doesn't support integers](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#value). Therefore, every number that gets passed either through REST (as JSON) or through gRPC (as protobuf) will get parsed as a protobuf `double`.

On PR #1098 we patched this so that, when we use REST to communicate with the downstream inference graph, we serialise any `double` with an empty decimal part as an integer (e.g. `2.0` will get serialised as `2` on the resulting JSON). However, this workaround has its own [caveats](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#integer-numbers) and it still doesn't work for gRPC.

## Potential solutions

Potential solutions may involve using a protobuf data type different than `google.protobuf.Value` like `google.protobuf.Any` for the `jsonData` field. I believe this could allow people to use their custom `proto` descriptors? 

For the `data.ndarray` field, we could try to keep using `google.protobuf.Value` but adding a new `dtype` field, specifying what should be the actual type.

Each of these has its own set of problems though, so any other thoughts and ideas are welcome.

**Comment by cliveseldon** [comment]
Should be solved by executor

**Comment by siddarthjha** [comment]
Hi I want to send json data what would be the data type in .proto file?  

```command
grpcurl -vv -d '{"data":{"ndarray":{"TxnId": "b8d66a10af56477fb74aa4bd8e05bcdd", "TransactionDateTime": "2022-10-21T00:25:50.000+05:30", "txnPurpose": "21", "payer": "873122814577", "txnAmount": "7384", "mid": "SBU1020041", "issuerOrgId": "HDU", "acquirerOrgId": "SBU", "RRN": "6464564"}}}' -rpc-header seldon:sklearn-aeps -rpc-header namespace:seldon-system -plaintext -proto ./seldon.proto  <ip>:31463 seldon.protos.Seldon/Predict
```
  What would be type of ndarray in proto file. I am new to grpc so not sure on this. Please can you help me on this

**Comment by adriangonz** [comment]
Hey @siddarthjha ,

I can see you've sent this question to the community Slack, so we'll follow up there.
