### ISSUE TITLE
strData requests are not printed by seldon request logger

### ISSUE THREAD

**Issue by SachinVarghese** [SeldonIO/seldon-core#1121]
The seldon request logger prints only default data converted to ndarray format and not any other type like strData or jsonData maybe all request/response pairs should be printed in raw format.

**Comment by ryandawsonuk** [comment]
This is actually [already being done](https://github.com/SeldonIO/seldon-core/blob/master/seldon-request-logger/app/app.py#L68).

**Comment by ryandawsonuk** [comment]
Problem seems to be that dataType wasn't being set for strData requests so adding that.
