### ISSUE TITLE
[Improvement] Obscure service name when deploy my yaml

### ISSUE THREAD

**Issue by bestksw** [SeldonIO/seldon-core#1128]
Hi, seldon-core team.
When I deploy my yaml of  kind of SeldonDeployment, Service name (especially transformer) is obscure like seldon-[sha256].
ArgoCD alwalys display service name, so It's hard to understand what service is related to in-transformer, out-transformer or something.

I really appeciate if you improve service name to have more clear.
Thx.

**Comment by axsaucedo** [comment]
@bestksw it's necessary to hash the service name if it's longer that the kubernetes allowed limit, but we've added functionality in #950 (via PR #953) which allows you to override the service name with an annotation - that should solve your issue (but you will need to make if you add names that you don't end up with duplicate service names)
