### ISSUE TITLE
Support Traefik Ingress

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1129]
Look at supportting Traefik.

https://traefik.io/

@phsiao

**Comment by ryandawsonuk** [comment]
Hopefully we can support nginx too as the structure of the Ingress resources for both is similar

**Comment by ryandawsonuk** [comment]
I guess we'll need to support passing hosts to be set on Ingress resources in addition to the seldon-generated paths. We'll also probably need to support setting custom annotations on the Ingress resources.

**Comment by nickdgriffin** [comment]
We've created our own Helm chart that turns out a SeldonDeployment and our own Ingress (based on a pattern we use across all applications) and that works just fine. Is it really necessary for Seldon to support (and therefore maintain support) every permutation of Ingress rather than leaving it in the hands of the user?

**Comment by ryandawsonuk** [comment]
There's quite a lot to manage around the ingress and it's pretty common to do canaries, A/B tests and shadow deployments. Not all users would want to manage these configurations themselves.

**Comment by dtpryce** [comment]
@cliveseldon what are the chances of this happening or is there some inter-operability with Ambassador/Istio and Traefik that we could leverage?

**Comment by nickdgriffin** [comment]
> @nickdgriffin Any chance you can share how you got Seldon running without the Ambassador or Istio requirements?

I don't have access to that project any more, I'm afraid, so I can't. We were using the Nginx Ingress Controller, and if I remember correctly just looked at what Seldon was doing with Ambassador (or if there were "generic" docs, I honestly can't remember) and mapped it to the equivalent. At the time it wasn't doing anything exotic and was just routing to the point of entry for the Seldon Deployment I think.

**Comment by cliveseldon** [comment]
supported in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/)
