### ISSUE TITLE
Can not control retry_policy from SeldonDeployment yaml file

### ISSUE THREAD

**Issue by yufengshan** [SeldonIO/seldon-core#1137]
I am trying to control the ambassador retry_policy from SeldonDeployment using the ```seldon.io/ambassador-config:``` at spec section. 

I want to change the num_retries and retry_on for different services and then created customize annotation to test the ambassador config. Seems the operator can not pick up the retry_policy config, I looked into the code, it looks like the operator code only process the top level (retry_policy level) , but can not go inside retry_policy (num_retries and retry_on). Can you please take a look? Either the document I am following is missing something or the code may need more function to process the num_retries.  Thanks. 

The doc I used : https://docs.seldon.io/projects/seldon-core/en/latest/ingress/ambassador.html#custom-amabassador-configuration

**Comment by cliveseldon** [comment]
Have you tried https://docs.seldon.io/projects/seldon-core/en/latest/examples/ambassador_custom.html ?
Can you post the deployment yaml you are using?

**Comment by cliveseldon** [comment]
reopen if still an issue
