### ISSUE TITLE
Investigate OpenShift Service Catalog and Brokers

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#114]
https://blog.openshift.com/whats-new-in-openshift-3-7-service-catalog-and-brokers/

Would allow easy install for customers of OpenShift for seldon-core.

**Comment by ryandawsonuk** [comment]
It seems this requires providing images that use the[ official RedHat base images](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/using_red_hat_base_container_images_standard_and_minimal).

The [python](https://access.redhat.com/containers/?tab=security#/registry.access.redhat.com/rhscl/python-35-rhel7/images/3.5-51) and [java](https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift) base [builder images](https://access.redhat.com/containers/?count=10&start=20#/category/Builder%20Image) are most relevant. Currently I only see an openjdk8 image and not any higher java versions but I don't think anything higher is currently used in seldon-core.

It might be that the [RH openjdk 8 image ](https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift) could [become the base image](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/using_red_hat_base_container_images_standard_and_minimal#building_container_images_with_standard_base_images) for the [seldon core operator](https://github.com/SeldonIO/seldon-core/blob/master/core-builder/Dockerfile#L1). I think we'd have to [setup authentication to pull from the RH registry.](https://access.redhat.com/articles/3560571) when the image. 

It's not clear to me whether any of the image references in the [wrappers in the seldon-core repo](https://github.com/SeldonIO/seldon-core/search?l=Dockerfile&q=from) would also need changing. Presumably it only applies to components that would be part of the service catalog itself and [not all seldon docker images](https://hub.docker.com/u/seldonio).

**Comment by cliveseldon** [comment]
I think the RedHat images needed would be just for the core (Helm) installable components.

**Comment by ryandawsonuk** [comment]
Yeah so current understanding is that the images for the core helm installable components would need to be RH images. It's not yet clear to me whether they would have to be published to a RH registry - I'm waiting for access to the container zone section of connect.redhat.com (can access that site but not that zone). I should then be able to see the official certification process docs.

**Comment by ryandawsonuk** [comment]
Have pushed https://github.com/SeldonIO/seldon-core/commit/9fcb8b0191fe669f30d75dc511e33bbcb36ac58d as a test to branch redhat-cert-114 - this is based on [a redhat guide](https://github.com/RHC4TP/documentation/blob/master/Red%20Hat%20OpenShift%20-%20Container%20Zone/How%20to%20Guide-Red%20Hat%20OpenShift%20%26%20Container%20Zone-preliminary%20release-20180918.pdf) and [accompanying example](https://github.com/RHC4TP/starter/blob/master/Container%20Zone/Examples/WebServer_Dockerfile_RHEL). So need to check whether these work, whether we'd be ok with switching to these images or would need to provide than one version and whether they pass cert checks when uploaded to RH registry.

**Comment by ryandawsonuk** [comment]
I've noticed that `RUN apk add curl` in the engine Dockerfile results in `/bin/sh: apk: command not found` with the RH openjdk base image. Will have to check further but looks like it might not be used. If so we can maybe remove it.

**Comment by cliveseldon** [comment]
I think curl is used in the default preStop check: 
https://github.com/SeldonIO/seldon-core/blob/e73cf37d33ea1a57d598a86efec36484ba71538a/cluster-manager/src/main/java/io/seldon/clustermanager/k8s/SeldonDeploymentOperatorImpl.java#L158

**Comment by ryandawsonuk** [comment]
Will try to find a way to get curl. This could be why there were a [couple of failures in E2E ](https://gist.github.com/ryandawsonuk/1df86bcd7a850264153377b2cd54fc1f) when I removed curl.

**Comment by ryandawsonuk** [comment]
Actually I did an [exec into the RH-based engine container](https://medium.com/the-code-review/run-bash-or-any-command-in-a-docker-container-9a1e7f0ec204) and found it already has curl in there from the base image anyway. So the failures I saw are presumably related to something else.

**Comment by ryandawsonuk** [comment]
When I ran test_rolling_updates.py in isolation then those tests actually passed. I guess they were actually non-deterministic failures as both were in the `rest_request_api_gateway("oauth-key","oauth-secret",None)` call rather than our code. Presumably will be resolved by the retries proposed in https://github.com/SeldonIO/seldon-core/pull/480

**Comment by ryandawsonuk** [comment]
The tech preview images we submitted to redhat container registry were accepted. Next steps on this are to look at getting the operator published. The [sample operatorhub memcached operator ](https://github.com/operator-framework/operator-sdk-samples/tree/master/memcached-operator)looks very similar to the [one we're building with kubebuilder](https://github.com/SeldonIO/seldon-operator). Most obvious difference is we're just missing the build and deploy directories. I guess these will be needed to [pass the scorecard checks](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/scorecard.md). I guess the next steps for us are to [work through the operator-framework getting started guide](https://github.com/operator-framework/getting-started) using our kubebuilder-based operator and see if we can add everything we need to get to passing the checks.

**Comment by axsauze** [comment]
The PR for this WIP can be found at https://github.com/SeldonIO/seldon-operator/pull/2

**Comment by cliveseldon** [comment]
RedHat work already in progress.
