### ISSUE TITLE
Engine failing to access /tmp folder when restricted Pod Policies in place.

### ISSUE THREAD

**Issue by hjarraya** [SeldonIO/seldon-core#1143]
When deploying a SeldonModel in a cluster with restricted pod policies, the engine fails to access `tmp` folder. In this situation, the solution is to add the volume emptyDir and mount the /tmp folder as follow

```json
"volumeMounts":[
    {
        "mountPath": "/tmp",
        "name": "tmp"
    }
]
```

```json
"volumes": [
    {
        "name": "tmp",
        "emptyDir": {}
    }]
```

here is snapshot from the `seldon-container-engine` logs,  failing to read /tmp folder due to our restrictive pod policy

```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to create tempDir. java.io.tmpdir is set to /tmp
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.17.RELEASE.jar!/:1.5.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.3.20.RELEASE.jar!/:4.3.20.RELEASE]
	at org.springframework.b
```

**Comment by cliveseldon** [comment]
The engine is added to the first PodSpec by default. Are you saying the above fix is a solution and we can close this? Or would be want to allow the engine PodSpec to be customized more fully by the user in the spec when you want it to be a separate PodSpec?

**Comment by hjarraya** [comment]
The above is not a fix, as we are not able to modify the engine PodSpec. We would like to allow the engine PodSpec to be customized more fully by the user, either in the spec or in a separate PodSpec.

**Comment by phsiao** [comment]
Instead of using emptyDir on hostPath, I would suggest using

```
"volumes": [
    {
        "name": "tmp",
        "emptyDir": {
          "medium": "Memory"
        }
    }]
```

If what goes into /tmp is small and the volume is not something outside of the pod can influence (or becomes a DoS mechanism).  With that said, hostPath can be a DoS mechanism too and it is worth than pod reaching its memory limit and evicted.

@hjarraya does your environment allows read/write root filesystem if the pod/container securityContext is set correctly?

**Comment by cliveseldon** [comment]
Is this still an issue? @hjarraya Will close
