### ISSUE TITLE
tf.Session() deprecated for Tensorflow > 2.0

### ISSUE THREAD

**Issue by JoelH96** [SeldonIO/seldon-core#1155]
The deep_mnist image in the example below throws an error when ran. This is due to the requirements.txt file installing tensorflow >=1.12 (i.e. installs version 2.0). The error is due to tf.Session() being removed in tf 2.0.

Either the tensorflow version needs to be fixed in the requirements file, or the python script needs to be fixed for the latest version.

https://github.com/SeldonIO/seldon-core/tree/master/examples/models/aws_eks_deep_mnist

**Comment by OrthoDex** [comment]
Hello! First time contributor to Seldon here. Can I pick this up?

**Comment by cliveseldon** [comment]
Hi @OrthoDex yes We'd love some help improving this example for TF2

**Comment by OrthoDex** [comment]
Great! I'll setup an initial PR sometime by this weekend.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Closing this a should be fix. Please reopen if still an issue.
