### ISSUE TITLE
Analytics charts broken in K8s v1.16

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1176]
It seems that the `seldon-core-analytics` charts are broken in Kubernetes v1.16.

I tried installing them with:

```bash
$ helm install seldon-core-analytics --name seldon-core-analytics --repo https://storage.googleapis.com/seldon-charts --set grafana_prom_admin_password=password --set persistence.enabled=false
```

and the error I got back was:

```bash
Error: validation failed: [unable to recognize no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize no matches for kind "DaemonSet" in version "extensions/v1beta1"]
```

Installation in Kubernetes v1.15 seems to work fine.

**Comment by gsunner** [comment]
The reason for the issue some "Deprecated APIs Removed In 1.16" like "extensions/v1beta1"
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by ryandawsonuk** [comment]
fixed by https://github.com/SeldonIO/seldon-core/commit/1d662a0c418bb12dfc1ec3bc6b7584429d2ff485
