### ISSUE TITLE
Benchmarking notebook fails with "Deployment not found" error

### ISSUE THREAD

**Issue by glindsell** [SeldonIO/seldon-core#1177]
https://github.com/SeldonIO/seldon-core/blob/master/notebooks/benchmark_simple_model.ipynb

![deployment-not-found](https://user-images.githubusercontent.com/19472951/69982695-ff0ce180-152c-11ea-99cb-ee2fff5439ee.png)

**Comment by cliveseldon** [comment]
We should update benchmarking notebook and more comprehensive benchmarks.

**Comment by cliveseldon** [comment]
This notebook has been removed. We need to create a new benchmarking framework.
