### ISSUE TITLE
cat.json missing from Explainer notebook

### ISSUE THREAD

**Issue by glindsell** [SeldonIO/seldon-core#1178]
https://github.com/SeldonIO/seldon-core/blob/master/notebooks/explainer_examples.ipynb

![lost-cat](https://user-images.githubusercontent.com/19472951/69982943-7e021a00-152d-11ea-9c32-5cfad604f8e5.png)

**Comment by cliveseldon** [comment]
Fixed https://github.com/SeldonIO/seldon-core/commit/5f49e54a45b8b6c0e5d5669d0b2943ca2fc12630
