### ISSUE TITLE
Shadow example fails in Istio notebook

### ISSUE THREAD

**Issue by glindsell** [SeldonIO/seldon-core#1179]
https://github.com/SeldonIO/seldon-core/blob/master/notebooks/istio_example.ipynb

![shadow](https://user-images.githubusercontent.com/19472951/69983130-ddf8c080-152d-11ea-81ad-4dea682e9006.png)

**Comment by ryandawsonuk** [comment]
Am confused by this as @smv and I have seen the grafana dashboards go up on the shadow predictor when running a load test with a shadow. And the load test does use the external endpoint. Tried to check this in the notebook using kind but then realised that it assumes an external LoadBalancer. I tried port-forwarding with `kubectl port-forward -n istio-system svc/istio-ingressgateway 8080:80` but struggling to get the seldon_client to work with that.

**Comment by SMV** [comment]
@ryandawsonuk, I am also confused by this, as I haven't worked on this a day in my life. Think you tagged the wrong github account. Good luck.

**Comment by ryandawsonuk** [comment]
Yes wrong account, sorry I meant @SachinVarghese

**Comment by cliveseldon** [comment]
Reopen if still an issue.
