### ISSUE TITLE
resources for integration tests

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1194]
https://github.com/SeldonIO/seldon-core/blob/1d6c461c1917d4b45b9526e75c99b0b2372324f7/jenkins-x-integration.yml#L29 seems [problematic for the cluster](https://github.com/SeldonIO/seldon-core/pull/1183#issuecomment-562055555)

`kubectl describe nodes` while the tests are running reveals there isn't enough cpu available:
![image](https://user-images.githubusercontent.com/22754674/70226457-c9dcdb00-1748-11ea-810b-8779c83dc016.png)

I think it's overcommitted because some deployments are not setting any requests or limits. But the failures suggest that the tests actually need more than what they're requesting so it can sometimes fail when the resource is allocated to something else instead.

**Comment by ryandawsonuk** [comment]
Now we have PRs stuck waiting on pending tests:
![image](https://user-images.githubusercontent.com/22754674/70228351-1ece2080-174c-11ea-9907-66d407a50fc6.png)

**Comment by axsaucedo** [comment]
@ryandawsonuk is this still an issue?

**Comment by cliveseldon** [comment]
Reopen if we hit it on latest CI cluster we run.
