### ISSUE TITLE
snapshot helm chart not being published?

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1203]
I tried installing with the 0.5.1-SNAPSHOT version and when I submitted the iris sklearn resource I got
```
2019-12-05T17:17:14.195Z        ERROR   controller-runtime.controller   Reconciler error        {"controller": "seldondeployment", "request": "seldon/sklearn", "error": "quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:218
```
Then I realised 0.5.1-SNAPSHOT is behind. We're [publishing 0.5.2-SNAPSHOT](https://hub.docker.com/r/seldonio/seldon-core-operator/tags). But if I run
```
helm install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --set usageMetrics.enabled=true --namespace seldon-system --version 0.5.2-SNAPSHOT
```
Then I get
```
Error: chart "seldon-core-operator" version "0.5.2-SNAPSHOT" not found in https://storage.googleapis.com/seldon-charts repository
```

**Comment by ryandawsonuk** [comment]
Also right now there were recent changes in master (17 hrs ago):

![image](https://user-images.githubusercontent.com/22754674/70613666-f1c4b680-1c00-11ea-8335-5e5484929ed5.png)

But engine and operator have not been published:

![image](https://user-images.githubusercontent.com/22754674/70613708-0903a400-1c01-11ea-8748-6cfdc2f40853.png)

**Comment by ryandawsonuk** [comment]
There are also a [couple](https://github.com/SeldonIO/seldon-core/blob/master/doc/source/workflow/install.md#install-with-cert-manager) of [references](https://github.com/SeldonIO/seldon-core/blob/master/doc/source/reference/aws-mp-install.md#install-seldon-core-on-eks-via-aws-marketplace) in the docs to 0.5.0 when I think this should be 0.5.1

**Comment by axsaucedo** [comment]
@ryandawsonuk I see there's a merge PR referencing the issue, would this be fixed?

**Comment by cliveseldon** [comment]
Image publishing is in the CI now.
