### ISSUE TITLE
google storage slowness - initializer hangs in PodInitializing

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1204]
Hit [this the other day](https://github.com/SeldonIO/seldon-core/pull/1183#issuecomment-561220641) and saw that it had been [reported recently also for kfserving](https://github.com/kubeflow/kfserving/issues/562). 

Hit it again just now running the sklearn iris example from the server_examples notebook against kind using the 0.5.1 release version:
![image](https://user-images.githubusercontent.com/22754674/70259537-43df8500-1786-11ea-95d6-3875eea52332.png)
It eventually initialized after about 8 minutes. Again the logs show problems with GS metadata:
```
INFO:root:Initializing, args: src_uri [gs://seldon-models/sklearn/iris] dest_path[ [/mnt/models]
INFO:root:Copying contents of gs://seldon-models/sklearn/iris to local
INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 1 of 3
INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 2 of 3
INFO:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable onattempt 3 of 3
INFO:root:Downloading: /mnt/models/model.joblib
INFO:root:Successfully copied gs://seldon-models/sklearn/iris to /mnt/models
```

**Comment by cliveseldon** [comment]
Not a Seldon Core issue - see links above to further tracking.
