### ISSUE TITLE
Seldon core analytics should scrape resource metrics

### ISSUE THREAD

**Issue by SachinVarghese** [SeldonIO/seldon-core#1206]
Seldon core analytics should also scrape resource metrics like
- Pod count for each deployment
- CPU/ memory resource stats

**Comment by cliveseldon** [comment]
Yes. I think we might need to join these Analytics issues together for 1 person to completely update the Analytics Chart.

**Comment by axsaucedo** [comment]
@cliveseldon is this issue duplicate or should we keep it open ?

**Comment by SachinVarghese** [comment]
@axsaucedo  This a done in @glindsell analytics update PR https://github.com/SeldonIO/seldon-core/pull/1331. Hence, closing.
