### ISSUE TITLE
request logging for shadows

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1207]
Not clear if traffic to a shadow goes through a request logger. Need a way to log request-response pairs for the shadow and distinguish them from the main predictor.

Would be nice to log an ID that is common to the request that goes through the main predictor and shadow so that you could pull out each and compare the responses.

**Comment by ryandawsonuk** [comment]
This is actually rather tricky as it stands. The logging is [initiated from the engine](https://github.com/SeldonIO/seldon-core/blob/master/engine/src/main/java/io/seldon/engine/service/PredictionService.java#L134) as it has access to [both the request and the response](https://github.com/SeldonIO/seldon-core/blob/master/engine/src/main/java/io/seldon/engine/service/PredictionService.java#L117). But shadowing is implemented at gateway level by [telling the gateway/istio to send the requests to additional services](https://github.com/SeldonIO/seldon-core/blob/master/operator/controllers/seldondeployment_controller.go#L223). This means the engine doesn't currently even look at what the shadows are or have any way to get access to responses from shadows.

Need to discuss with @cliveseldon about how response logging will work with the [future executor implementation](https://github.com/SeldonIO/seldon-core/pull/1016) so we can [tie this in with kfserving logging](https://github.com/SeldonIO/seldon-core/issues/1293) which [uses per-predictor sidecars](https://github.com/kubeflow/kfserving/pull/467). 

If we moved to the per-predictor sidecar pattern then we'd be able to log request-response pairs for shadows and explainers. A key knock-on effect of this is that we'll have to be able to connect up all the request-response pairs in a way that we can efficiently search for them and display them. To do that we could either:

1) Change the [logger code](https://github.com/SeldonIO/seldon-core/tree/master/seldon-request-logger) so that if it's logging a response then it first looks for a request and updates the existing elasticsearch document (so stop using fluentd). Would have to match by an ID and be predictor-specific (the 'response' for a shadow needs to be joined to a shadow request and not overwrite the response for the main predictor)
or
2) Logs the request and responses separately and just record a common ID against them.

I am leaning towards 1 as 2 would make things awkward for any search page based on the elasticsearch data. Such a page would have to first query just for do an additional lookup for every record returned. (Elasticsearch does have a [kind of join concept](https://www.elastic.co/guide/en/elasticsearch/reference/current/joining-queries.html) but as far as I can see it would still require either [knowing the linkage at insert time](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html) or taking the [multiple-lookup performance hit](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html).)

**Comment by ryandawsonuk** [comment]
Need to check what happens in the current engine implementation. From discussion with @cliveseldon , there should be an engine inside the shadow predictor so it should currently be that everything is logged once for main predictor and once for shadow. But we need to check what IDs are recorded against these records.

**Comment by ryandawsonuk** [comment]
I tried this by creating the anchor tabular sdep and adding a shadow and then making a request. Only one request logger is created and it logs just one record. 

I also cleared out elasticsearch indexes before making the request and found I got only one:
![image](https://user-images.githubusercontent.com/22754674/71736113-1c90dc00-2e48-11ea-9837-790eb0324539.png)

**Comment by ryandawsonuk** [comment]
Hmm, comparing the logs for the two, the main predictor shows a `"POST /predict HTTP/1.1" 200 -` line and the shadow does not. Looks like the shadow is not receiving the traffic.

**Comment by ryandawsonuk** [comment]
Ok now it works. I sent in two requests and both got logged once for the main predictor and once for the shadow (so four in total). The `request.tabular.meta.puid` is distinct for the main request and the shadow. The only thing I can see to tie them together is that they have the exact same timestamps, right down to the millisecond.

![image](https://user-images.githubusercontent.com/22754674/71810694-d8c9ec80-306a-11ea-9244-325f39e0d7d2.png)

**Comment by cliveseldon** [comment]
Check how will work in Go executor

**Comment by ryandawsonuk** [comment]
Need to look at this in the light of https://github.com/SeldonIO/seldon-core/pull/1369
