### ISSUE TITLE
canary flag like shadow flag

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1210]
Add a `canary: true` option on a predictor on the SeldonDeployment. It would effectively just be an optional label with no functional impact. But it would distinguish a canary use-case from an A/B test use-case and it would make it clear which predictor were the canary and which the default in the case where the traffic split is 50/50 or even more to the canary.

**Comment by SachinVarghese** [comment]
@ryandawsonuk Is it a good idea to have a similar default flag for normal predictors without any functional impact?

**Comment by ryandawsonuk** [comment]
We spoke and decided an annotation on the predictor would be a better way to record this  e.g. `"seldon.io/canary": "true"`

**Comment by cliveseldon** [comment]
@SachinVarghese can we close this and do the work in Deploy
