### ISSUE TITLE
duplication of seldon_core_setup notebook

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1232]
When going through seldon-core docs I noticed that `seldon_core_setup.ipynb` is duplicated both in [seldon-core/examples](https://github.com/SeldonIO/seldon-core/blob/master/examples/seldon_core_setup.ipynb) and [seldon-core/notebooks](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/seldon_core_setup.ipynb).

~~The one linked from first tutorial [notebook](https://docs.seldon.io/projects/seldon-core/en/latest/examples/server_examples.html) one hit when going through docs leads you to latter one that does not include info about ambassador port forwarding which may be confusing to new users.~~

We could remove duplication by creating a symlink and keeping around only one version of this notebook.

**Comment by ryandawsonuk** [comment]
I agree it would be nice to do something about this. FWIW it looks to me like the port-forward is in both:

![image](https://user-images.githubusercontent.com/22754674/70526744-31789900-1b42-11ea-9039-425ac05e4a79.png)

**Comment by RafalSkolasinski** [comment]
oh, my bad, it's there but as a markdown cell whereas in other one it is executed directly from notebook, 
editing issue to only mark duplication

**Comment by ryandawsonuk** [comment]
The notebooks version is only reference by a few notebooks so we could shift them to point to `.../notebooks/seldon_core_setup.ipynb`

![image](https://user-images.githubusercontent.com/22754674/70526988-b8c60c80-1b42-11ea-9284-9036bbd0edda.png)

I think the seldon_core_setup.html references need to stay as-is as they are just for the web version that refer to the readthedocs page generated from the [nblink](https://github.com/SeldonIO/seldon-core/blob/master/doc/source/examples/seldon_core_setup.nblink) and the paths on those are different.

**Comment by ryandawsonuk** [comment]
Actually we shouldn't do what I just suggested. When you open a jupyter server with `jupyter notebook` then you can only refer as high as the base path from which you started it. So the it would be fine to remove the notebooks version if we were sure users were going to run the `jupyter notebook` command from the base `seldon-core` directory. But it's likely people will run this from the `notebooks` directory unless we tell them otherwise. Perhaps the symlink is a better idea.
