### ISSUE TITLE
provide a docker image ready to run example notebooks?

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1235]
This is a suggestion to provide a docker image that could serve a jupyter notebook and has all dependencies required to execute example notebooks (seldon-core, kubectl, helm, etc...). 

It could be accompanied by a comprehensive instructions how to make it work with Kubernetes cluster spawned with DigitalOcean, Minikube, Kind, etc...

**Comment by RafalSkolasinski** [comment]
My initial idea was to just provide image that could work as a client for kubernetes cluster, it is the cluster would have to run somewhere else and `kubectl` from inside the image could just be pointed to it.

@axsaucedo took this idea one step further and suggested to make the image with self-contained cluster (something like kind) - this would be more complete solution but more complex and slightly harder to achieve

**Comment by axsaucedo** [comment]
@RafalSkolasinski closing this one for now as today we discussed we'll want to do a cleanup of examples so we can bring this up on that discussion and reopen if we decide to move forward with a docker image with examples
