### ISSUE TITLE
Include seldon proto compilation in GO

### ISSUE THREAD

**Issue by hemantkashniyal** [SeldonIO/seldon-core#1245]
As per discussion on #1156 for any go application to use use seldon's HTTP/GRPC inference call, it will be helpful if Seldon protos are compiled in GO as part of CI BUILD.

Raising issue for creation of go package for seldon.

**Comment by adriangonz** [comment]
Thanks @hemantkashniyal for raising this issue and for the work you've contributed in #1246! This is great to hear and it's also linked to issue #1198.
