### ISSUE TITLE
Tox tests fail if py37 is not present

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1247]
`tox` is configured to run the tests on a `py37` environment. However, if Python 3.7 is not present the tests fail. 

https://github.com/SeldonIO/seldon-core/blob/1ae79570dfd9307902ec0784cae6943eb31d3250/python/setup.cfg#L6

It seems that `tox` doesn't do anything besides checking if there is a `python3.7` interpreter present. We should either change `tox`'s config to run the tests on whatever environment is present or add some way for `tox` to fetch the relevant versions if they are not present.

**Comment by axsaucedo** [comment]
@adriangonz is this something we want for 1.1 or push for later?

**Comment by adriangonz** [comment]
@adriangonz I think it would be good to have a look for 1.1. I can have a look into it and while I'm there I can also add tests for Python 3.8.
