### ISSUE TITLE
broken links to image descriptions

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1249]
In [Latest Seldon Images](https://github.com/SeldonIO/seldon-core/blob/master/doc/source/reference/images.md) table all links in `Description` column are broken.

- [x] fix links
- [x] document workaround to reference md files outside of `doc/source`

**Comment by axsaucedo** [comment]
@RafalSkolasinski is this still something that needs to be done?

**Comment by RafalSkolasinski** [comment]
Yes, gonna fix it.
