### ISSUE TITLE
Migrate tutorials to use kind instead of Minikube

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1256]
Kubernetes in Docker ([kind](https://kind.sigs.k8s.io/)) seems to be much more user friendly than Minikube. It does not require spinning a VM and therefore better share resources with a host machine.

Migrating all examples to `kind` is however a considerable investment of effort so we should carefully consider all pros and cons.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by axsaucedo** [comment]
@RafalSkolasinski i think this was done, should we close?

**Comment by RafalSkolasinski** [comment]
Most of examples I have seen in last few months were in `kind` so I guess we're good to close.
