### ISSUE TITLE
Existing resource conflict with Helm 3.x

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1289]
When Seldon Core is already installed on the cluster, if the user tries to upgrade to a more recent version using Helm 3.x it will receive the following error:

```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Secret, namespace: seldon-system, name: seldon-webhook-server-cert
```

For the sake of reference, the command used to upgrade is:

```bash
$ helm upgrade -n seldon-system seldon seldon/seldon-core-operator --version x.x.x
```

This seems to be a behaviour introduced in Helm 3.0, where Helm stops an upgrade if there is an existing resource with the same name already there. The issue has already been reported in the Helm repo (https://github.com/helm/helm/issues/6646, https://github.com/helm/helm/issues/6850) and there is a proposal for a fix in https://github.com/helm/helm/issues/7082.

## Suggested workaround

There is a suggested workaround of removing the existing duplicated resources (in our case, the `seldon-webhook-server-cert` secret) before the install. We need to first try this workaround and then consider any potential impact in downtime, etc.

**Comment by cliveseldon** [comment]
But all resources will be already existing in the cluster. How was the original install done?

**Comment by adriangonz** [comment]
If I understand correctly, on Helm 2.x if there was an existing resource with changes coming from the `helm upgrade` it would just patch the existing one with the changes.

However, on Helm 3.x, if the same happens it will just stop the update.

The proposal that it's being discussed in https://github.com/helm/helm/issues/7082 suggests adding a `--recreate` flag which would handle the above scenario.

**Comment by adriangonz** [comment]
After looking further into this, it seems that the first attempt to upgrade Seldon Core fails with:

```
Error: UPGRADE FAILED: failed to create patch: merging an object in json but data type is not struct, instead is: map
```

After trying a second time is when we get the error message we reported originally:

```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Secret, namespace: seldon-system, name: seldon-webhook-server-cert
```

The first error message (which seems to be the root cause) should have been fixed in https://github.com/helm/helm/issues/5853 but there are some reports of a regression error in Helm 3.x at the end of that thread.

**Comment by jason-liew** [comment]
[helm/helm#7238](https://github.com/helm/helm/pull/7238) may be helpful

**Comment by adriangonz** [comment]
Thanks for the suggestion @jason-liew!

I just tried but unfortunately the exact same thing seems to happen. I think that, despite of showing similar error messages, the https://github.com/helm/helm/pull/7238 PR probably tackles a different root cause.

**Comment by adriangonz** [comment]
It seems that the fix which was originally introduced for https://github.com/helm/helm/issues/5853 is still needed. I've submitted PR https://github.com/helm/helm/pull/7269 to add it back, which seems to solve the issue.
