### ISSUE TITLE
Update Analytics Helm Chart

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1297]
* Needs to use official helm chart dependencies for Grafana and Prometheus.
 * Ensure resource metrics are available (should happen automatically when we use upstream chart)
 * Separate out grafana dashboards for existing outlier detection examples - causing issues with present due to size of annotations

**Comment by arun-muthy** [comment]
Separating out grafana dashboards will help installation of seldon-core-analytics using Kustomize
