### ISSUE TITLE
Seldon Core Operator fails to install on EKS

### ISSUE THREAD

**Issue by conorcurlett** [SeldonIO/seldon-core#1320]
In an EKS cluster, version 1.14, running `helm3 install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --set usageMetrics.enabled=true --namespace seldon-system --set ambassador.enabled=true` results in `Error: failed to download "https://storage.googleapis.com/seldon-charts/seldon-core-operator-1.0.0.tgz" (hint: running `helm repo update` may help)`. 

There is no further debug information logged by increasing the verbosity level in Helm. 

Helm is version 3.0.2.

**Comment by cliveseldon** [comment]
Strange. The URL is public and available. Is there a firewall issue? Have you tried from a different source location machine or your local laptop to check the differences?

**Comment by conorcurlett** [comment]
I don't believe so:

- I can `wget` the file from the same host
- I have been using helm2 and helm3 without other issues, using a variety of repositories, including installing ambassador successfully prior to Seldon Core using the same configuration
- I've tested with helm 3.0.0, 3.0.1, 3.0.2 with the same result

I also tried installing v0.5.1 with the same result.
Using helm2 downloads the chart successfully, but fails due to the fixed issue in master https://github.com/SeldonIO/seldon-core/pull/1300

I was able to successfully install by downloading and using the chart directly, however.

**Comment by cliveseldon** [comment]
Very strange. Can you run the helm install with debug like in this "similar" issue: https://github.com/helm/helm/issues/7311

**Comment by conorcurlett** [comment]
I get 

```
$ helm3 install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts/ --set usageMetrics.enabled=true --namespace seldon-system --set ambassador.enabled=true --debug
install.go:149: [debug] Original chart version: ""
Error: no cached repo found. (try 'helm repo update'): open /home/user/.cache/helm/repository/local-index.yaml: no such file or directory
helm.go:76: [debug] open /home/user/.cache/helm/repository/local-index.yaml: no such file or directory
no cached repo found. (try 'helm repo update')
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).scanReposForURL
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:345
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:169
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:87
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/home/circleci/helm.sh/helm/pkg/action/install.go:669
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:161
main.newInstallCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/install.go:116
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_386.s:1325
```
... which looks like the `.helm` and `cache` are in the wrong places in the directory definition

```
/home/user/.helm/repository/cache/local-index.yaml
```
would be the standard location AFAIK.

**Comment by cliveseldon** [comment]
Could it be related to https://github.com/helm/helm/issues/4659

**Comment by cliveseldon** [comment]
I'll remove bug for now as this looks like a general helm configuration issue. But it would be great for the docs to understand more why you are hitting this.

**Comment by cliveseldon** [comment]
Please reopen if more info
