### ISSUE TITLE
send_feedback() got an unexpected keyword argument 'routing'

### ISSUE THREAD

**Issue by zjorgensenbits** [SeldonIO/seldon-core#1321]
When sending a request to the feedback endpoint of my deployed model, I get a Microservice Error and I see the following in the container log: send_feedback() got an unexpected keyword argument 'routing'.

This is the data payload I'm sending: '{"reward": 1.0, "truth": {"data":{"names":["a","b"],"tensor":{"shape":[2,1],"values":[0,1]}}}, "response": {"data":{"names":["a","b"],"tensor":{"shape":[2,1],"values":[0,1]}}},"request": {"data":{"names":["a","b"],"tensor":{"shape":[2,1],"values":[0,1]}}}}'

**Comment by cliveseldon** [comment]
It looks like it is adding routing to the call to your microservice. 

https://github.com/SeldonIO/seldon-core/blob/f89347d420d9b228415add09b04ce632d8a9bb25/python/seldon_core/user_model.py#L366-L368

Do you have this defined in your signature for the method?

Can you explain more how you created the example? Maybe one of our docs/examples is out of date?

**Comment by zjorgensenbits** [comment]
Ahh, yes, I was using an image created from the example here: seldon-core/wrappers/s2i/python/test/model-template-app/MyModel.py 
which is out of date.  I fixed the send_feedback function signature and it seems to work now.  I'm not getting an error, at least.  Should I see any kind of response?

**Comment by cliveseldon** [comment]
Send feedback does not give a payload response at present - so a 200 http code would be all.
