### ISSUE TITLE
Internal build issue: PR builds intermittently fail with no space left on device

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1322]
Seen for example at https://github.com/SeldonIO/seldon-core/pull/1298#issuecomment-567972993
and https://github.com/SeldonIO/seldon-core/pull/1315#issuecomment-571623827

Happens when you run multiple builds in quick succession. If you delete the old build jobs then the next one works. Seems to be the ephemeral storage that is being used for logging. Istio logs quite a lot and we log a lot anyway in our E2E tests, which we run multiple times within kind for different platforms.

Looks like a fairly common one to hit with JX anyway - https://github.com/jenkins-x/jx/issues/3243 and https://github.com/jenkins-x/jx/issues/5622

**Comment by ryandawsonuk** [comment]
Could also be that https://github.com/SeldonIO/seldon-core/blob/master/jenkins-x-integration.yml#L49 means the images are being stored on ephemeral storage

**Comment by ryandawsonuk** [comment]
I was listing and deleting completed pipeline jobs one by one but possibly [`jx gc`](https://jenkins-x.io/commands/jx_gc/) would do it. Didn't actually try that before.

**Comment by ryandawsonuk** [comment]
Also hitting this on https://github.com/SeldonIO/seldon-core/pull/1316 Happening even after cleaning up old jobs.

**Comment by ryandawsonuk** [comment]
This seems to have worked as tests passed on https://github.com/SeldonIO/seldon-core/pull/1323. Didn't do any cleanup prior to that so the changes in that PR seem to be what has fixed it.

Re cleanup, we may occasionally want to run `jx gc` and **also** `jx get build pods` followed by `kubectl delete pod <pod>` for any completed ones. Unfortunately the `jx gc` command alone doesn't do this. Old pods do get automatically cleaned up but typically not fast enough.

**Comment by ryandawsonuk** [comment]
Separate issue - the gh-pages branch seems to somehow be tracking master.

**Comment by axsaucedo** [comment]
@ryandawsonuk should we close this issue?
