### ISSUE TITLE
update redhat operator

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1327]
Follow-up to https://github.com/SeldonIO/seldon-core/issues/845 and https://github.com/SeldonIO/seldon-core/issues/791

Update https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/seldon-operator to new operator. Make sure we continue to respect https://github.com/zachncst/om-env-example/blob/master/README.md

**Comment by ryandawsonuk** [comment]
Turns out we don't currently respect the om-env-var convention adequately. We've now been told:
```
We need the environment variables to follow the RELATED_IMAGE_<identifier> format because there is code being written around it to make changes easier for users who need to customize the repository. If you can change the variable names, I think you'll be good to go.
```

**Comment by axsaucedo** [comment]
Closing issue (we can reopen if request comes in as compulsory)

**Comment by ryandawsonuk** [comment]
Now being tracked at https://github.com/SeldonIO/seldon-core/issues/1482
