### ISSUE TITLE
Namespaced operator duplicates Seldon deployments

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1339]
## Context

It is now possible to deploy a namespace-scoped Seldon Core operator which only pays attention to the `SeldonDeployment` resources present in its own namespace. For this to work, the namespace needs to be labeled with `seldon.io/controller-id=<namespaceName>`.

## Problem

If the namespace is **unlabeled** and there is also a **cluster-wide operator**, it seems that there are two sets of pods deployed: one coming from the namespace-scoped operator and the other from the cluster-wide one. One of them keeps being deleted and then re-created and the other remains stable.

## What should happen?

If the namespace is unlabeled the namespace-scoped operator should ignore its resources (and perhaps trigger some kind of warning).

**Comment by cliveseldon** [comment]
I don't think this is a bug. If you launch a namespaced operator it will try to reconcile anything launched into that namespace. If you also have a cluster-wide operator and you fail to label that namespace it will also try to reconcile it. The instructions in the docs say you need to label the namespace first.
