### ISSUE TITLE
Seldon Java Wrapper Roadmap towards incubation graduation

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1344]
There has been some requirements gathered around features relevant to the Java Wrapper. These include “required” and “nice-to-have”s, some which would lead towards the incubation graduation of the Java wrapper. This github issue is focused on discussion and scoping and should result in a set of more specific github issues that target single tasks.

Overview of high level requirements identified (which still need to be expanded):

    Further documentation on the Java Wrapper usage

        Overview of the variables available for override

    Integration tests

        Test for simple deployment of the Java Wrapper

    Improve Java dependencies

        Migrate to newer versions of Java (currently only working with JAva 1.8 (currently some fail with jdk 11)

        Switch over to Spring Boot 2

        Upgrade current Java 1st level dependencies to the latest

    Workflow of logic

        The seldon-java-wrapper currently lives in a different repo, we may want to have it all on the single mono-repo (so it benefits from dependabot updates, jenkins-x builds, etc)

    Extra enhancements

        Currently the whole SeldonMessage is passed without any pre-processing (unlike python wrapper which passes it as numpy array - this may require more understanding on usage of libraries in Java)

        Potentially it would be useful to have a prepackaged model server for H2O mojos, but then the question that followed was whether there was a possibility to abstract the inputs and outputs that come into those models in the same way that you have fr the python numpy arrays in python

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Closing as will need to address a new Java wrapper with MLServer
