### ISSUE TITLE
better test coverage: s2i functionality

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1356]
It does not seem that we have tests that would cover s2i functionality we provide:
- install pip packages from requirements.txt
- install conda packages from (to be merged) environment.yaml or conda.yml
etc...

It would be good to add those at least as unit tests.

**Comment by cliveseldon** [comment]
We do have e2e tests for s2i.

**Comment by cliveseldon** [comment]
closing - can be addressed in testing review
