### ISSUE TITLE
better test coverage: test both python 3.6 and 3.7 wrappers

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1357]
As we provide s2i wrappers for both Python 3.6 and Python 3.7 it may be good idea to test both of these in our e2e integration tests. 

Right now we only test a default one (python 3.7).

To be precise we only test `seldonio/seldon-core-s2i-python37` tagged as `seldonio/seldon-core-s2i-python3`.

**Comment by axsaucedo** [comment]
This is a good suggestion. It may be a heavy overhead to run it automatically on each default integration test, but we could make it a requirement on each main release (before releasing the changelog). We were also thinking about testing with multiple Kubernetes versions, so we could have a similar approach as well

**Comment by cliveseldon** [comment]
Closing. Can reopen for wider testing PR.
