### ISSUE TITLE
azure-storage-blob package update to 12.1.0

### ISSUE THREAD

**Issue by pymia** [SeldonIO/seldon-core#1371]
the latest azure-storage-blob is 12.1.0, Seldon is using `azure-storage-blob >= 2.0.1, < 3.0.0`, which is the legacy version. It will be great to update to the latest package.

**Comment by cliveseldon** [comment]
Lets put fix in kfserving project as that is where the code is.

**Comment by anggao** [comment]
Would be great to have this fixed in v1.3, as mlflow 1.10.0 has requirement azure-storage-blob>=12.0

**Comment by anggao** [comment]
@axsaucedo  If this can be included in the patch release would be great, thank you!

**Comment by axsaucedo** [comment]
It seems we just got flagged a (medium) vulnerability from azure storage, so we'll have to prioritise. Report: https://snyk.io/vuln/SNYK-PYTHON-IPADDRESS-590065

**Comment by axsaucedo** [comment]
Currently the storage.py dependency is linked to the kfserving dependencies, so we'll have to update it there https://github.com/kubeflow/kfserving/blob/master/python/kfserving/requirements.txt

**Comment by axsaucedo** [comment]
Just to follow-up on this one, it seems that the vulnerability is still TBC on resolve timeline. We'll have to confirm it gets resolved with the iptables library first. There is an open issue that is looking at it https://github.com/phihag/ipaddress/issues/55

**Comment by anggao** [comment]
There is a ticket in kfserving to upgrade it: https://github.com/kubeflow/kfserving/issues/923

**Comment by cliveseldon** [comment]
We plan to remove storage.py to reduce dependencies in the python module.
