### ISSUE TITLE
replace print with logging in tests

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1372]
Some tests, e.g. `python/tests/test_router_microservice.py`, are using `print` statements to ease debugging on failure.

It may be a good idea to replace them with proper logging.

(Though, personally I am not sure if there is much benefit from doing that for tests).

**Comment by cliveseldon** [comment]
Maybe just remove the print statements to make the tests cleaner. The error when the test fails with the name of the test should be enough in production.

**Comment by RafalSkolasinski** [comment]
Print statements will be removed via https://github.com/SeldonIO/seldon-core/pull/1424 which will close this issue once merged.

**Comment by RafalSkolasinski** [comment]
Adjusted to replacement with `logger.info`.
