### ISSUE TITLE
Updated Seldon Data Plane

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1389]
Update Seldon Data plane for REST and gRPC:

Some things to include:

 * Health
    * Server Ready
    * Server Live
    * Model ready
 * Server Metadata
 * Model Metadata
 * Server metrics 

Look at NVIDIA TRTIS data plane to align.

Linked issues:

 #1387 
 #1362

**Comment by lennon310** [comment]
Could you elaborate a bit on `Status` since it is related to error handling in old Java Engine?

**Comment by cliveseldon** [comment]
@lennon310 I have updated the initial description to make more clear the areas to cover. Feel free to add your own requirements in this issue to help with planning.

**Comment by gaocegege** [comment]
Will we migrate to KFServing community standard inference? TRTIS is planning to migrate to it.

**Comment by cliveseldon** [comment]
Yes - we will fully support it. Will close this to open new ones focused on particular data planes.
