### ISSUE TITLE
GPU Sharing

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1390]
Allow different Seldon Deployments to share the same GPU.

Initially this may be focused on some particular GPU serving technology such as TRTIS from NVIDIA.

**Comment by sreddybr3** [comment]
[https://github.com/Deepomatic/shared-gpu-nvidia-k8s-device-plugin](https://github.com/Deepomatic/shared-gpu-nvidia-k8s-device-plugin) might help

**Comment by cliveseldon** [comment]
We did some early work in https://github.com/SeldonIO/trtis-k8s-scheduler

**Comment by cliveseldon** [comment]
supported in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/)
