### ISSUE TITLE
Support for Xgboost 0.9

### ISSUE THREAD

**Issue by indranilr** [SeldonIO/seldon-core#1394]
Current release of Seldon [Xgboost server](https://docs.seldon.io/projects/seldon-core/en/latest/servers/xgboost.html#xgboost-server) supports XgBoost 0.82 release. Requesting support for [Xgboost 0.9](https://github.com/dmlc/xgboost/tree/v0.90) as it has several performance improvements.

**Comment by adriangonz** [comment]
Thanks for the ping @indranilr. Upgrading sounds like a good idea. Are there any breaking changes we should be aware of?

**Comment by indranilr** [comment]
There are couple of breaking changes as per [Release Notes ](https://github.com/dmlc/xgboost/blob/master/NEWS.md). 
1. XGBoost Python package drops support for Python 2.7 
2. XGBoost4J-Spark now requires Spark 2.4.x 

More information at [ https://github.com/dmlc/xgboost/issues/4389](url).

Please note that a new release 1.0.0 is in the offing : [https://github.com/dmlc/xgboost/issues/5253 ](url). Roadmap 1.0.0 : [https://github.com/dmlc/xgboost/issues/4680](url)
