### ISSUE TITLE
Support for xgboost4j-spark 0.9

### ISSUE THREAD

**Issue by indranilr** [SeldonIO/seldon-core#1395]
It should be possible to [persist a XGBoost4j-Spark 0.9](https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#model-persistence) model and serve the same using Seldon. 

The only available option today seems to be to save it to [another binding of Xgboost](https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#interact-with-other-bindings-of-xgboost) (e.g Python) and load using compatible Seldon Xgboost server.

Would it be possible to  have the spark pipeline saved using below snippet be served using Seldon ?

`val xgbClassificationModelPath = "/tmp/xgbClassificationModel"
xgbClassificationModel.write.overwrite().save(xgbClassificationModelPath)`

**Comment by cliveseldon** [comment]
Have you tried it with our Java wrapper : https://docs.seldon.io/projects/seldon-core/en/latest/java/README.html

**Comment by indranilr** [comment]
@cliveseldon  I have not tried the Java wrapper option - is there an example where Spark pipeline models are being wrapped using Java Wrapper that I can refer to ? The documentation has example of H2O and DL4J.

**Comment by indranilr** [comment]
> 
> 
> @cliveseldon I have not tried the Java wrapper option - is there an example where Spark pipeline models are being wrapped using Java Wrapper that I can refer to ? The documentation has example of H2O and DL4J.
> 
> Further to this there appears to be some overhead involved in single instance Prediction or online inference in xgboost4j-spark [https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#single-instance-prediction ](url). I was hoping there would be an implementation supported in Seldon Core which would support loading Spark Xgboost models in an optimized manner (equivalent to [Mleap ](https://github.com/combust/mleap))

An update on this - initial experiments with [https://github.com/komiya-atsushi/xgboost-predictor-java/tree/master/xgboost-predictor-spark](url) and Seldon Java wrapper on natively persisted xgboost4j-spark models has been successful.Mleap based exporting of spark model and inference using Mleap runtime wrapped in Seldon is next , shall update on findings.

**Comment by cliveseldon** [comment]
Great. @indranilr look forward to further updates.

**Comment by adriangonz** [comment]
I've had some success using MLflow to train (and serialise) `pyspark` pipelines, which can then be served using the [pre-packaged `MLFLOW_SERVER`](https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html) in Seldon. The only caveat was that Java still needs to be installed on the output image, even if you still use Python for inference.

Would this be an easy out-of-the-box option @indranilr?

**Comment by indranilr** [comment]
Closing this issue, solution we have settled on for the time being is using MLEAP 0.16 with Xgboost4j-Spark 1.0.0 using Seldon core wrapper 0.1.5.
