### ISSUE TITLE
Customization of seldon ambassador url 

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#1401]
Hi,
Is it possible to customize the seldon ambassador url?
I know that the url prefix can be changed from the default.
By default it is http://ambassador endpoint/seldon/namespace/seldon model name/api/v0.1/predictions.
I have seen cases where we can change the prefix upto api.
Is it possible to completely change the url according to user requirement?That is without the portion /api/v0.1/predictions?
Kindly help

**Comment by cliveseldon** [comment]
Its not possible to change the path completely at present as the service orchestrator and python wrappers create HTTP Servers that look for those paths.

**Comment by divyadilip91** [comment]
Oh ok. Thankyou
