### ISSUE TITLE
Flakiness on integration tests

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1402]
## Context

Sometimes integration tests seem to behave flaky and raise false errors. We have noticed two different cases where this usually happens:

1. `503` or `504` errors on one or two of the tests in [testing/scripts/test_rolling_updates.py](https://github.com/SeldonIO/seldon-core/blob/master/testing/scripts/test_rolling_updates.py). An example can be seen on the [log output for PR #1400](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1400/3.log). This has happened in the past either due to issues with Ambassador / Istio falling over to the new deployment (actual red flag) or due to spamming the `SeldonDeployment` pod with too many requests.

  https://github.com/SeldonIO/seldon-core/blob/f21fa8e8f16baef2455158eb67ae10c826c0f4ec/jenkins-x/logs/SeldonIO/seldon-core/PR-1400/3.log#L18139-L18170

2. An error installing Istio. In particular, a timeout waiting for the `istio-ingressgateway` pod to come up. Instead of failing early, the tests continue and this in turn causes (almost) all of them to fail. An example can be seen on the [log output for PR #1382](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/4.log). This has happened in the past whenever the cluster ran out of ephemeral storage (e.g. #1322).

https://github.com/SeldonIO/seldon-core/blob/f21fa8e8f16baef2455158eb67ae10c826c0f4ec/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/4.log#L340-L344

On both cases they seem to be intermittent. 

## Workaroud

While they are not fixed properly, we can verify if it's a red flag by running them locally (and adding a note about that on the PR for the reviewers).

**Comment by adriangonz** [comment]
As a temporary workaround, on PR #1415 I'm marking the tests relevant to `1.` above as *"flaky"* using the [`flaky`](https://github.com/box/flaky) package. This means that **upon failure they will be retried 1 more time**.

Note that this is temporary, it still can fail (if they fail more than 2 times) and it should be fixed properly.

**Comment by adriangonz** [comment]
I've been running the tests relevant to `1.` above (i.e. the suite in `test_rolling_updates.py`) locally to see if I could find any kind of pattern. 

As I can replicate the flakiness locally, it seems safe to assume that they are not just related to lack of resources on the Kind cluster. Instead, it seems that occasionally Istio and Ambassador may lose track of all the `Pods` in a `Service`. Every time that I saw this, it happened during the update from an old to a new version of the test model.

Whenever it happens, Istio returns a `503` and Ambassador returns a `504`. It's also way more frequent in Istio than it is in Ambassador (at least when I run them locally).

**Comment by RafalSkolasinski** [comment]
In https://github.com/SeldonIO/seldon-core/pull/1481 I increased flakiness max_retries parameter to 3.
This helped to have successful run of `test_rolling_updates` locally on the first try.

I have a feeling that introducing a short sleep to `assert_model_during_op` can help reduce the problem, though I didn't test it yet.

**Comment by cliveseldon** [comment]
Assumption is its Ambassador tests and due to the change for Ambassador retries to zero. Will change tests to do 1 retry. Am testing locally.
