### ISSUE TITLE
Support custom client protobufs in grpc server

### ISSUE THREAD

**Issue by groszewn** [SeldonIO/seldon-core#1420]
We have been using gRPC internally for most of our models for quite some time, so they already have protobufs that are specific to each model's features.  We would like to maintain the strong type safety provided by these custom protobufs across all of our models.

**Comment by cliveseldon** [comment]
With the new executor in master which is in golang this option becomes more likely. Be interesting to discuss how this would be done. 

I see golang's v2 protobufs allow more dynamic usage: https://github.com/golang/protobuf/issues/199

**Comment by groszewn** [comment]
Thoughts on possibly allowing the serialized proto message all the way to the method implementations?

**Comment by cliveseldon** [comment]
This should already be possible with the latest master as the http protocol is passed through as binary in the executor. So if you launched a pod that could decode the message it should work.

**Comment by groszewn** [comment]
Gotcha, I mistook `executor` for the model service container in your previous statement.

I stumbled across an Envoy blog post [here](https://blog.envoyproxy.io/dynamic-extensibility-and-protocol-buffers-dcd0bf0b8801) that discusses the tradeoffs between using `Any` and `Struct` for dynamically extending protobufs. Both of these seem like feasible approaches to introduce as few changes to the current `executor` and proto specs.  In cases where someone would want to use their custom protobuf, the executor can act like a reverse proxy and offload the deserializing and message parsing to the model service container.

**Comment by groszewn** [comment]
@cliveseldon let me know if you have any specific preferences in terms of this implementation.  I can try to take a crack at it if we're okay iterating a bit.

**Comment by cliveseldon** [comment]
So let me summarize the proposed solution to see if I understand:

  * Add a top level custom field to SeldonMessage of type Any in the proto defn
    * I don't see any changes to executor for this other than updated protos? or would the schema URL be checked inside the Any to reject early bad URLs payloads?
  * For the python wrapper you would need to ensure you used the predict_raw as you would need to get access to the custom field and parse the Any

**Comment by groszewn** [comment]
That covers it.  I don't see a clean way to make the executor aware of the type URLs as of yet, so it would just be updated protos for the executor.

**Comment by cliveseldon** [comment]
The PR is merged so closing.
