### ISSUE TITLE
Customize Seldon engine readiness and liveliness probes

### ISSUE THREAD

**Issue by ellisvalentiner** [SeldonIO/seldon-core#1423]
The Seldon engine container has default readiness and liveliness probes but the Seldon engine container readiness probe will fail if the model container is not yet ready. This can be an issue if the model `__init__` function takes longer than the engine container's readiness probe -- for example if loading a very large model file.

Slack conversation: [link](https://seldondev.slack.com/archives/C8Y9A8G0Y/p1581117945171500)

**Comment by arunbenoyv** [comment]
Is there an update on when the readiness probe timeout can be overridden

**Comment by cliveseldon** [comment]
Can you clarify the issue? Readiness probes should be failing until the model is ready and then the engine will become ready.

**Comment by cliveseldon** [comment]
@ellisvalentiner Which version is this and is it Java engine or Executor?

**Comment by ellisvalentiner** [comment]
I don't think the Slack conversation link works anymore because the original discussion was as long ago.

I don't recall which version(s) we were on at the time but I think this was prior to the executor being available.

The issue is that large models can take a long time to load. While it was possible to configure the readiness/liveliness probes for the model container (e.g. allow the model container to take longer to start up) there was no way to configure these for the Engine container. This can lead to the Engine container terminating in failure which then marks the whole Pod as Failed.

**Comment by cliveseldon** [comment]
ok I think that seems strange as:
 - The engine readiness probe failing is ok as it will revert to success when the model is ready
 - The engine liveness probe is a self-test so is not affected by the model

**Comment by cliveseldon** [comment]
Closing. Can you reopen if still an issue.
