### ISSUE TITLE
Seldon v1.0 CRD uses new (k8s 1.15) feature that not backward compatible with k8s versions (<= 1.14)

### ISSUE THREAD

**Issue by yufengshan** [SeldonIO/seldon-core#1431]
In the Seldon v1.0 CRD, the following is used ```x-kubernetes-int-or-string``` to replace ``` IntOrString```.  The "x-kubernetes-int-or-string" is introduced at k8s v1.15, and systems running pre k8s v1.15 can not handle this. 

Please consider to make this backward compatible.

**Comment by cliveseldon** [comment]
When you say k8s <1.15 can not handle this. From local testing with kind the CRD can be installed with no errors.
```
kind create cluster --image kindest/node:v1.12.10
cd operator
make install
```

**Comment by anggao** [comment]
I think he means the validating webhooks needs k8s >= 1.5

**Comment by cliveseldon** [comment]
Do you mean for the selectors?
See https://github.com/SeldonIO/seldon-core/blob/25778017d9f571e5be0be1a3bae7e163ced8ea4a/operator/config/webhook/kustomization.yaml#L8 for kustomize

The helm install has similar gates.

Can you clarify what you mean by the webhook needs k8s>= 1.15 ?

**Comment by yufengshan** [comment]
k8s < 1.15 can not handle "x-kubernetes-int-or-string".  When deploy the CRD to cluster, the is ignored, therefore, no validation is performed when a seldon deployment is deployed to cluster.

**Comment by cliveseldon** [comment]
Validation just for this part of the OpenAPISchema you mean or are you suggesting the whole schema is ignored? 
The validating webhook is still called I assume?

**Comment by yufengshan** [comment]
Only the part involved in "x-kubernetes-int-or-string", others are fine.

**Comment by cliveseldon** [comment]
So validation that it is not a float?

I think you will need to provide some example for when you comment out that kustomize patch. Which is also a solution if you are using kustomize BTW.

**Comment by yufengshan** [comment]
![Screen Shot 2020-02-18 at 5 00 03 PM](https://user-images.githubusercontent.com/50298152/74781819-3d828480-5270-11ea-9da7-a5f83ca7bbbc.png)

This is the screenshot after I apply the CRD to the cluster. From the diff you can see, the green lines are removed in the deployed object. 

We are not planning to fix it for now as we are upgrading our cluster to k8s 1.15. This is no longer an issue for the deployment. Just input an issue for others who still run k8s < 1.15

**Comment by cliveseldon** [comment]
Unless this is actually stopping some functionality from working I think we can leave it. Please reopen if you can provide an example in k8s < 1.15 for which functionality is broken.
