### ISSUE TITLE
Errors in explainer_examples notebook

### ISSUE THREAD

**Issue by glindsell** [SeldonIO/seldon-core#1434]
![pyerr](https://user-images.githubusercontent.com/19472951/74445510-6f5daa80-4e6e-11ea-8923-41a2cbfe5c86.png)

**Comment by glindsell** [comment]
![pyerr2](https://user-images.githubusercontent.com/19472951/74446062-44278b00-4e6f-11ea-8309-4cf275b4681d.png)

**Comment by glindsell** [comment]
![pyerr3](https://user-images.githubusercontent.com/19472951/74446369-b0a28a00-4e6f-11ea-86f8-78937d7e5035.png)

**Comment by glindsell** [comment]
![pyerr4](https://user-images.githubusercontent.com/19472951/74446521-e8113680-4e6f-11ea-9d1b-a7ef4e80b19e.png)

**Comment by glindsell** [comment]
Duplicate of #473

**Comment by cliveseldon** [comment]
Hopefuly fixed by #1466
