### ISSUE TITLE
Ambassador setup fails to complete on minikube

### ISSUE THREAD

**Issue by L-GCHQ** [SeldonIO/seldon-core#1435]
I've been trying to setup seldon core on my local machine with minikube using this guides:

- For the core deployment: https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#seldon-core-helm-install
- For adding ambassador Ingress to the core: https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#seldon-core-helm-install
- For installing ambassador: https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#seldon-core-helm-install

This steps lead to the following script:

```
minikube start --memory 8192 --kubernetes-version=v1.15.0
minikube dashboard &

kubectl create namespace seldon-system
helm install seldon-core seldon-core-operator --repo
https://storage.googleapis.com/seldon-charts --set usageMetrics.enabled=true --namespace seldon-system --set ambassador.enabled=true
helm repo add stable  https://kubernetes-charts.storage.googleapis.com/

helm repo update
helm install ambassador stable/ambassador --set crds.keep=false
```

I try to run the command to get the Ambassador endpoint IP, it turns up as pending forever:

```
$ kubectl get svc --namespace seldon-system ambassador
NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
ambassador   10.105.19.7   <pending>     80:32717/TCP,443:30499/TCP   5m
```

Could someone advise if something is missing from the guide or whether there's something specific to minikube that needs to be changed.

**Comment by cliveseldon** [comment]
On minikube by default you won't be able to create a loadbalancer. But you can following these docs:
 https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/Tasks/loadbalancer.md

**Comment by L-GCHQ** [comment]
I've been unable to run this unfortunately due to not have permissions to run `minkube tunnel`.

**Comment by cliveseldon** [comment]
If you can create a reproducible test please reopen
