### ISSUE TITLE
Errors in helm_examples notebook

### ISSUE THREAD

**Issue by glindsell** [SeldonIO/seldon-core#1436]
![pyerr-h](https://user-images.githubusercontent.com/19472951/74447902-fa8c6f80-4e71-11ea-8234-af812ae986bb.png)

**Comment by glindsell** [comment]
![pyerr-h2](https://user-images.githubusercontent.com/19472951/74448103-4fc88100-4e72-11ea-8e94-0f89e87d5592.png)

**Comment by glindsell** [comment]
Duplicate of #473

**Comment by cliveseldon** [comment]
Fixed by #1466
