### ISSUE TITLE
Errors in seldon_core_setup notebook

### ISSUE THREAD

**Issue by glindsell** [SeldonIO/seldon-core#1440]
When running the following command from the setup script:
```
!helm install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --set istio.enabled=true --set usageMetrics.enabled=true --namespace seldon-system
```

The seldon-controller pod goes into CrashLoopBackOff and the following logs are observed:

```
gl@gltp:~/work/seldonio/seldon-core/operator$ kubectl logs seldon-controller-manager-cd658fb4b-nxb48 --previous -n seldon-system
2020-02-13T15:52:15.846Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2020-02-13T15:52:15.847Z	ERROR	setup	unable to create controller	{"controller": "SeldonDeployment", "error": "no matches for kind \"VirtualService\" in version \"networking.istio.io/v1alpha3\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
	/workspace/main.go:89
runtime.main
	/usr/local/go/src/runtime/proc.go:200
```

**Comment by glindsell** [comment]
Fixed

**Comment by jkruzek** [comment]
@glindsell How did you fix this? I'm having the same issue

**Comment by glindsell** [comment]
@jkruzek I think it's because `--set istio.enabled=true` flag is set, so you have to have Istio running and I think I had neglected to run Istio. I believe that's what the error `"no matches for kind \"VirtualService\"` is saying.

You could try with  `--set istio.enabled=false` and see if the error persists?

**Comment by jkruzek** [comment]
@glindsell Thanks! Yeah I didn't have istio installed and running. Gonna get it going and try again.
