### ISSUE TITLE
Send back PUID on response

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1460]
The executor generates a Prediction UID (PUID) which is forwarded down to the predictor services. However, it doesn't send this back on the final response. This UID could be useful for the end-user.

## Suggested fix
It seems that, at "response time" (i.e. right before sending it back), the PUID is still present in the Go context. Therefore, the problem seems to be that the `respondWithSuccess` method in `rest.SeldonRestApi` doesn't serialise it.

https://github.com/SeldonIO/seldon-core/blob/946d5400a14e63a68c975cd3364e66b70d6cb262/executor/api/rest/server.go#L74-L82 

Adding there a `w.WriteHeader()` writing the PUID should be enough.

**Comment by adriangonz** [comment]
@cliveseldon would there be any other changes required for the gRPC endpoint?

**Comment by cliveseldon** [comment]
Closing this as fixed.
