### ISSUE TITLE
Shared Memory and Inferencing

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1463]
* Arrow
 * MLGraph integration
 * NVIDIA Rapids investigation

**Comment by gaocegege** [comment]
Can you please explain more about the MLGraph integration?  I cannot get why it can help implement GPU sharing.

**Comment by cliveseldon** [comment]
The question is where to focus the work. The thought was a new CRD might simplify that but actually might be more associated with components that handle the V2 dataplane proposal to allow shared memory references to be handled by any server and executor.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale
