### ISSUE TITLE
Prediction API should define a dedicated image type

### ISSUE THREAD

**Issue by pisymbol** [SeldonIO/seldon-core#1478]
Currently the message format of Seldon Core is defined by the protobuf spec listed here:

https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/prediction.html

Models that do a lot of image processing (e.g. object segmentation) are forced to use *bytes binData* by base64 encoding an image before sending a POST. 

That in turn means every single Seldon Core request has to have code  to convert the passed in byte array *X" to an image like so (e.g. Python, RGB image as input):

`
from PIL import Image

img = Image.open(io.BytesIO(X)).convert('RGB')
`

Instead, it would be nice if the protobuf format defined some kind of dedicated *imgData* type  which would act like *binData*  but would be serialized to an image (e.g. numpy array for Python) when it arrives at the model's predict() function so the model writer can use it immediately instead of having to convert "bytes" to "images" every single time as per above.

I realized this is harder than it sounds since recognizing different image formats and serializing them on the wire has its issues.

It just seems that unserializing image data at the Model node level is somewhat awkward given how common image data is as input.

**Comment by cliveseldon** [comment]
For your use cases and models can you illustrate what steps you are running in the python wrapper on the binData?

I think there are two considerations:

 1. Allowing easy way to send imgData, e.g. file attachment
 2. Deserializing it from the binary payload back to the appropriate input for the model nD-array in numpy.

**Comment by pisymbol** [comment]
@cliveseldon See above. I gave an example on what we do to convert binData to an image. From there you can do:

`
img = Image.open(io.BytesIO(X)).convert('RGB')
img = np.array(img)
img = img[:,:,-1] # BGR for OpenCV processing etc.
`

#2 was my focus since #1 can be accomplished a number of ways (including as a file attachment).

**Comment by cliveseldon** [comment]
I think there are too many variants to cover for a solution.

**Comment by pisymbol** [comment]
Then why not offer an API to turn X into an image as a convenience function?

**Comment by cliveseldon** [comment]
Happy to accept a PR here. My concern would be there are many image libraries and types of images so you would end up having a very long list.
