### ISSUE TITLE
NameError: global name 'ListValue' is not defined

### ISSUE THREAD

**Issue by rishi007bansod** [SeldonIO/seldon-core#148]
Hi,
   Getting following error

NameError: global name 'ListValue' is not defined

while running gRPC through [https://github.com/SeldonIO/seldon-core/blob/master/util/api_tester/api-tester.py](url) file. What might be the issue?

**Comment by cliveseldon** [comment]
PR https://github.com/SeldonIO/seldon-core/pull/150 should fix this.
There is an extended example at  https://github.com/SeldonIO/seldon-core/blob/master/examples/models/sklearn_iris/sklearn_iris.ipynb
