### ISSUE TITLE
Flask Theading bug, when using with sockeye and mxnet

### ISSUE THREAD

**Issue by Arttii** [SeldonIO/seldon-core#1498]
When trying to run a model using sockeye=="1.18.106 on mxnet, I am running into the following [issue](https://github.com/awslabs/sockeye/issues/671#issuecomment-477602579) .

It seems there is no way to override the flask startup [args](https://github.com/SeldonIO/seldon-core/blob/14c1b09283f090afe7f101fcd92d37add4b91ef4/python/seldon_core/microservice.py#L325).

Am I missing something and there is a way to override this or it something we need to add?

EDIT: Seems a workaround is to use gunicorn and set GUNICORN_WORKERS=N

**Comment by cliveseldon** [comment]
ok - so can you clarify your solution and close issue if solved or do you think the python library still needs an extra option?

**Comment by Arttii** [comment]
Maybe we can mention this in the GUNICORN documentation or we add the threading flag [here](https://github.com/SeldonIO/seldon-core/blob/14c1b09283f090afe7f101fcd92d37add4b91ef4/python/seldon_core/microservice.py#L294), should be simple to do. From my perspective we can close the issue.

**Comment by cliveseldon** [comment]
OK. Would be great if you can do a small PR for the docs.

That link you reference is for the Gunicorn case so are you saying a use case with workers>1 and notheading - so separate process forks?

**Comment by axsaucedo** [comment]
Gunicorn threads and workers are now configurable and docs were added
