### ISSUE TITLE
seldon support muti istio gateway

### ISSUE THREAD

**Issue by andrewshaoyu** [SeldonIO/seldon-core#1500]
separate sdep to different namespaces is a way. 

but seldon service path is related with namespace, so if i want to use another gateway, client need to change service request path.

**Comment by cliveseldon** [comment]
You can already do this with the annotation `seldon.io/istio-gateway`
See [here](https://docs.seldon.io/projects/seldon-core/en/latest/ingress/istio.html#install-seldon-core-operator)
