### ISSUE TITLE
Add default value to interface_name ("Model") and api_type ("REST")

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1503]
To simplify the model wrapping creation we could have a default for interface_name and api_type, so the s2i utility could be called without the need for an `.s2i/environment` file. This could remove some steps from the default examples, and for the GRPC ones would also be simplified by just passing a single parameter through the CLI (instead of the file).

**Comment by cliveseldon** [comment]
As we are moving to MLServer for custom models in roadmap longer term will close this.
