### ISSUE TITLE
missing python dependencies for integration tests

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1504]
After merge of notebook tests in https://github.com/SeldonIO/seldon-core/pull/1466 running them fails on local machines due to missing requirements like:
- sklearn
- matplotlib
- tensorflow < 2

I believe those should be added to `/testing/scripts/dev_requirements.txt`.

**Comment by RafalSkolasinski** [comment]
And alibi is missing too.

**Comment by cliveseldon** [comment]
Remove deps from core builder and add to testing dev_requirements
