### ISSUE TITLE
Add top level registry prefix to Helm Charts for custom registries

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1510]
As we see usecases in airgapped clusters, having the registries as a variable that can be changed in a single or fewer places. Potentially having a "global registry prefix" that could be set only if all the global registry is the same, alternatively if the user needs to use multiple registries for any reason this could be set blank.

This would apply primarily to the Seldon Core Analytics and the Seldon Core Operator Helm charts

**Comment by cliveseldon** [comment]
Check if there is a helm chart repo for this.

**Comment by ryandawsonuk** [comment]
There seem to be two common ways to specify a single image. Either:
```
image:
  registry:
  repository:
  tag:
```
Or:
```
image:
  repository:
  tag:
```
In the latter the registry is included in the repository entry. See for example https://github.com/helm/charts/blob/master/stable/airflow/values.yaml#L64

If there are other images used by the same chart then they can appear at a different level of indentation - https://github.com/helm/charts/blob/master/stable/airflow/values.yaml#L548

This presents a bit of awkwardness for the user in that they have to override each registry entry individually. It is possible to provide a global override as the mariadb chart does:

https://github.com/helm/charts/blob/283aca3551399d16b1e7b4ba13e1099483f34b04/stable/mariadb/values.yaml#L5

But that does add quite a bit of complexity.

I'd suggest for us that the operator chart is already pretty clear:

https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/values.yaml

And we could make the analytics chart clearer by adding some commented entries [in the values file](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-analytics/values.yaml) to show how the images are to be set on the charts we embed.

**Comment by cliveseldon** [comment]
But we have the pre-package server images and storage-initializer image using a different format. Should we change those to the more verbose but correct format?
