### ISSUE TITLE
h2o_mojo : o.s.boot.SpringApplication   : Application startup failed

### ISSUE THREAD

**Issue by jear** [SeldonIO/seldon-core#1523]
Hi, although the h2o_mojo s2i build is ok, I think that the Spring prostate_classifier is not working.

pip freeze in my miniconda env:
https://gist.github.com/jear/478da1aedbe45cd50d12b4f5ce10b3b7

And the log :
k logs h2o-deployment-h2o-predictor-1cc70ed-9d7654c84-hxt2q prostate-classifier > prostate-classifier.log
https://gist.github.com/jear/1752a805500a4cfaf140674097596b2c

**Comment by cliveseldon** [comment]
The Java wrapper is in incubation at present. We welcome further tests and PRs to update it.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Closing this. Happy to restart discussion on H20 and Java in new issue?
