### ISSUE TITLE
OpenShift 4.3 compatibility for Seldon-Operator 0.1.5

### ISSUE THREAD

**Issue by dianadujing** [SeldonIO/seldon-core#1524]
Hi there,

Can anybody share opinion about whether OpenShift 4.3 is compatible with Seldon-Operator 0.1.5? I found Seldon-Operator 0.1.5 in OperatorHub, but failed to run it on my openshift cluster. Is there any material available?

**Comment by cliveseldon** [comment]
We have #1477 and its associated work to add a new Operator for use in OpenShift. That will be available when 1.1 is releases in the next few weeks. Before that you should be able to install the existing 1.0.2 onto an Openshift customer yourself. We do have customers using Seldon on Openshift and as said with the upcoming 1.1 release you will be able to install from the offical UI for both community operators and certified operators.

**Comment by cliveseldon** [comment]
closing please reopen if needed
