### ISSUE TITLE
Allow to set MAX_CONTENT_LENGTH on Flask service

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1525]
It would be good to allow users control over the [`MAX_CONTENT_LENGTH` Flask config parameter](https://flask.palletsprojects.com/en/1.1.x/config/#MAX_CONTENT_LENGTH). This could be exposed either through an annotation or through environment variables, as we currently do for other Flask config variables:

https://github.com/SeldonIO/seldon-core/blob/9ff9647c31fbee02e3f59583fa563f3c549605ba/python/seldon_core/wrapper.py#L126-L141

In fact, we could potentially explore allowing override of all Flask config variables?

**Comment by cliveseldon** [comment]
Closing. Can this be addressed in MLServer @adriangonz

**Comment by adriangonz** [comment]
Sure thing @cliveseldon, moved it to https://github.com/SeldonIO/MLServer/issues/444
