### ISSUE TITLE
Invalid JSON: Unexpected type for Value message when passing tuples in json_data

### ISSUE THREAD

**Issue by taavi-primer** [SeldonIO/seldon-core#1527]
Seems SeldonClient is not able to encode tuples when they are passed in through json_data parameter. It is also unclear how to make use of the str_data and data input parameters (those could use documentation).

Small example:
```
import json
from seldon_core.seldon_client import SeldonClient

seldon_client = SeldonClient(
    gateway="istio",
    transport="rest",
    namespace="ml-serving",
    deployment_name="our-model",
    gateway_endpoint="our-istiogw",
)

example1 = ["Some text here.", "SomeName", [(0, 5)], [(10, 15)]]
example2 = json.loads(json.dumps(example1)) 

try:
    resp = seldon_client.predict(json_data=list([example1]), http_path="/api/v0.1/predictions")
    print(f"Response with example1: {resp.response.data.tensor}")
except Exception as ex:
    print(f"Exception thrown: {str(ex.message)}")

resp = seldon_client.predict(json_data=list([example2]), http_path="/api/v0.1/predictions")
print(f"Response with example2: {resp.response.data.tensor}")
```

Output from that is:
```
$ python ~/seldon_example1.py
Exception thrown: Invalid JSON: Unexpected type for Value message.
Response with example2: shape: 1
values: 0.006200790667543826
```

**Comment by cliveseldon** [comment]
Example1 is not valid JSON. The `json` module probably handles tuple automatically.

**Comment by taavi-primer** [comment]
How could it be? JSON is a string serialization of an object. Isn't the whole point of the json_data parameter to give it a Python object that needs to be serialized into a string? Or is the expected payload here already JSON-serialized? I don't think the latter works...

**Comment by cliveseldon** [comment]
The seldon client parses a json method first into a protoBuffer using:
https://github.com/SeldonIO/seldon-core/blob/574ac86fc80abf994473d965b60f8a6948cd8f9f/python/seldon_core/utils.py#L48

So the issue if that it fails at that point due to protoBuffers understanding of what is valid json and a `tuple` is not valid json.
