### ISSUE TITLE
Helm Chart variable credentials.s3.s3AccessKeyIDName/s3SecretAccessKeyName not used in Helm chart

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1528]
There is currently a set of values.yaml variables that are defined but not used in the template. There is also code in the operator which uses these variables, but currently in the docs we expect the logic for s3 secrets to be handled in the Seldon Deploymetn through the secret name or the service account+secret approach. 

It would still be useful to be able to set seldon-core-wide s3 credentials, but specifically in this case, these variables should either be documented and added to the template or alternatively we could remove the logic around these variables.

**Comment by axsaucedo** [comment]
It seems that this is relevant to the way credentials are obtained using a service account, mainly via `credentialsBuilder.CreateSecretVolumeAndEnv`, however it's not intuitive in the way it's expected to provide the credentials through the service account. A proposal is to depricate this in favour of the `envSecretRefName` and `defaultEnvSecretRefName` that is being implemented via #1530, as this will allow much more flexibility for the set-up of secrets. @cliveseldon was there a specific reason for the choice to do it by scanning all the secrets until there are name matches in KFServing? If not it seems to make sense to move fully towards the envSecretRefName implementation instead

**Comment by axsaucedo** [comment]
Having a further look at this, it seems that one of the main reasons why it seems to be required to have the functionality on `credentialsBuilder.CreateSecretVolumeAndEnv` because GCP requires a JSON file to exist in order for the credentials to work. A proposed fix for this to ensure consistency is to introduce a new variable specifically for Google Cloud called `GOOGLE_APPLICATION_CREDENTIALS_CONTENT`, and add logic in the container to ensure that the file is created if the file exists.

**Comment by cliveseldon** [comment]
Closing for possible new issue.
