### ISSUE TITLE
Option to setup Seldon without webhooks

### ISSUE THREAD

**Issue by naor2013** [SeldonIO/seldon-core#1529]
We use an old version of k8s and we can't use webhooks. We managed to make it work without it, we just delete those yaml files from the helm chart and we setup every SeldonDeployment with all the properties it needs (that the webhooks usually fill out for you).

The feature I'm asking for is that I would be able to disable webhooks in the helm chart values and also to have better error messages for missing values that the webhook usually fills out.
For example, we didn't have "implementation" in the SeldonDeployment, and instead of getting an appropriate error, we got an unusual error.
Inside the function "IsPrepack", you do "len(*pu.Implementation)" which assumes implementation exists, and in our case gives a null pointer exception or something like that.

If you can make sure that running without webhooks gives relevant errors and to give users an option to disable them, that would really help users without the ability to run them.

**Comment by cliveseldon** [comment]
The work done as part of RedHat operator includes an update to run defaulting at the start of Reconcile: https://github.com/SeldonIO/seldon-core/pull/1519/files#diff-b520473967af374ae98ad6019e5b84a4R1352-R1363

This should allow the Operator to also be run without webhooks. However no validation would then be done so we have not yet tested errors that maybe introduced by this. This would be less on any k8s version that allows OpenAPISchema. What version of k8s are you running?

**Comment by naor2013** [comment]
How will this operator work? Will I need to change something in my yamls? What would be different?
We use k8s 1.9 I think, not sure though.
Is it possible to do this validation as part of the engine if a helm setting is set or something?

**Comment by cliveseldon** [comment]
We officially only support k8s>= 1.12
The work above could help us support earlier versions but we would need to plan and prioritize it.

**Comment by naor2013** [comment]
I know you support 1.12 and up.
The issue I opened now is to help support older versions.

**Comment by cliveseldon** [comment]
Once version 1.1 is out you should be able to test without webhooks. We'd welcome your feedback that point.

**Comment by naor2013** [comment]
That's awesome! Can you tell me what change would it require me to do?
Any change in the helm values file?

**Comment by cliveseldon** [comment]
This is now possible in 1.1.0 although we don't provide at present a helm chart option to not create webhooks.

**Comment by chengcheng-pei** [comment]
@cliveseldon when the helm chart option to disable webhook can be provided?

**Comment by ryandawsonuk** [comment]
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/values.yaml#L28

**Comment by chengcheng-pei** [comment]
@cliveseldon `Once version 1.1 is out you should be able to test without webhooks. We'd welcome your feedback that point.` => this mean that createResource set to True and webhook will be created by controller automatically? or can we install seldon-core without webhook totally?

**Comment by cliveseldon** [comment]
By test I mean you can manually deleted webhooks and the server will work but without validation.
It will need some changes to Helm chart to add this as an automated default.

**Comment by cliveseldon** [comment]
We only have validation webhooks at present. Should think if webhook less operation is best for v2 APIs.

**Comment by cliveseldon** [comment]
In [v2](https://docs.seldon.io/projects/seldon-core/en/v2/) we don't use webhooks
