### ISSUE TITLE
Quickstart problem

### ISSUE THREAD

**Issue by djKooks** [SeldonIO/seldon-core#153]
Hello,
While following up quickstart process using Minikube - with RBAC, I faced error like below.

```
$ helm install helm-charts/seldon-core-crd --name seldon-core-crd --set usage_metrics.enabled=true
Error: apiVersion "apiextensions.k8s.io/v1beta1" in seldon-core-crd/templates/seldon-deployment-crd.json is not available
```
Do I have to change this value for going on?

**Comment by cliveseldon** [comment]
Can you detail the steps you took and how this differed from the steps when I ran the notebook today shown below and we can find whats going on:

![minikube_rbac_screenshot](https://user-images.githubusercontent.com/10563075/39965605-35b3bbc2-5694-11e8-8d2c-59bd0e371aa8.png)

**Comment by djKooks** [comment]
@cliveseldon thanks for reply.
It could be because I run in terminal instead of notebook. I'll test again and let you know.

**Comment by cliveseldon** [comment]
The same should work in a terminal, so something else must be different.

**Comment by gsunner** [comment]
@djKooks what version on minikube are you using?

**Comment by djKooks** [comment]
@cliveseldon @gsunner now it works! Sorry to take long for reply, because it shows error in newest version(0.26.1), 

https://github.com/kubernetes/minikube/issues/2703

so I reverted to 0.25.1 and find it work.

Thanks.
