### ISSUE TITLE
Deployments created by Seldon are apps/v1 but HPA scaleTargetRef is extensions/v1beta1

### ISSUE THREAD

**Issue by ahutterTA** [SeldonIO/seldon-core#1533]
We should change HPA to be apps/v1 as well

**Comment by ahutterTA** [comment]
Should be fixed by #1534

**Comment by vladislavkoz** [comment]
I'm facing this issue as well. It works good when I'm editing HPA config manually(until the first scalling iteration). Can someone provide me with the info on how to fix this? What I have to change in my deployment config?
