### ISSUE TITLE
Prow Integration

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#154]
We should look at tools like prow to create integration tests

**Comment by gsunner** [comment]
This initial prow integration work involved infrastructure setup to have prow systems running. 
* prod and dev prow systems setup to service SeldonIO/seldon-core repo
* initial config for managing PRs added

**Comment by ahousley** [comment]
Great to see this closed @gsunner :raised_hands: looking forward to seeing a demo. 
Is there a related docs task? If so, please share a link. Thanks!
