### ISSUE TITLE
Add support to add ambassador circuit-breaker in seldon deployment

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#1556]
Right now seldon-sore doesn't support ambassador circuit-breaker in the deployment. would be great to allow users to configure circuit-breaker for their model deployments.

**Comment by anggao** [comment]
Right now we can provide a custom ambassador config to workaround this issue:

https://github.com/SeldonIO/seldon-core/blob/master/operator/controllers/ambassador.go#L251

Seldon will use it directly,  would be great to make seldon merge custom ambassador config provided by users with the one generated by seldon.

**Comment by anggao** [comment]
@cliveseldon if no one take this I can grab it and try to fix it

**Comment by cliveseldon** [comment]
That would be great @anggao
