### ISSUE TITLE
Move metrics e2e tests from notebook to regular python tests

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1557]
A follow up to https://github.com/SeldonIO/seldon-core/issues/1476 that exposes custom metrics on wrapper endpoints. The https://github.com/SeldonIO/seldon-core/pull/1507 includes e2e tests in form of Jupyter Notebook (run by CI) but it would be good to move those to regular Python tests.

**Comment by cliveseldon** [comment]
Closing. Can reopen in general testing review
