### ISSUE TITLE
High number of concurrent users causing Seldon API to timeout

### ISSUE THREAD

**Issue by jsreid13** [SeldonIO/seldon-core#1558]
I'm using Seldon to create an API that reads values from different tables in Google Cloud Bigtable, but when we've been doing some performance testing it looks like when we get up to around 30 concurrent users calling the predict endpoint it starts timing out. No response is returned and there's no errors logged within Google Kubernetes Engine. This is the last error message before it hangs 
```seldon_core.user_model:client_custom_metrics:307 - INFO:  custom_metrics is not implemented```
I'm using 4 gunicorn workers, and I suspect that the backlog is getting filled with requests and not clearing. The load on the workers doesn't go up so kubernetes doesn't autoscale, however if I force there to be more replica pods created then it can handle more concurrent requests to a point, and then hangs again.
Any suggestions on parameters to change? Currently I'm looking into using async workers in gunicorn, the number of threads per worker and adjusting the max requests before restarting workers. Also has there been any performance testing done on Seldon? I'm curious what's the max number of concurrent users calling the API you've been able to achieve is.

**Comment by cliveseldon** [comment]
Benchmarking will depend heavily on your particular model. We have done some initial [benchmarking](https://docs.seldon.io/projects/seldon-core/en/latest/reference/benchmarking.html) but we need to update this. Also, specific benchmarking for the python language wrapper would be useful I agree to validate various settings.

The gunicorn issue is definitely something that needs further investigation. Maybe other can comment on their use cases if they can make them public? Maybe not using gunicorn workers and allowing k8s to scale replicas is an alternative or do you see that as a waste of resources?

**Comment by jsreid13** [comment]
That is a viable solution, but is very brute force. We've found even when scaling the hung pods do not recover without being restarted, is there a way that you know of to clear the backlog for an overloaded worker?

**Comment by cliveseldon** [comment]
Have you checked why the workers get blocked? I assume its not a gunicorn issue?

**Comment by jsreid13** [comment]
Yeah it doesn't look like a gunicorn issue, but since there's no logs just the API becomes unresponsive its tricky to understand why. It could be due to there being a buildup of backlog requests causing the API to become unresponsive, but I'm not sure how to debug that.
Do you know where the notebook used for benchmarking is? I followed the link you sent but it seems to have moved (https://github.com/SeldonIO/seldon-core/blob/master/notebooks/benchmark_simple_model.ipynb)

**Comment by cliveseldon** [comment]
Yes - we have actually removed it as its out of date. Will update docs.
You can find it at: https://github.com/SeldonIO/seldon-core/blob/v1.0.2/notebooks/benchmark_simple_model.ipynb

**Comment by axsaucedo** [comment]
@jsreid13 it woudl be good to understand why this issue is happening. Flask has become multithreaded / non-blocking since 1.0, so it would be good to understand if the blocking comes from the gunicorn workers themselves. If you scale the gunicorn workers do you get a linear increase on number of parallel tasks that you can be sending as requests? are there any memory limitations on the cluster that could be causing this issue duee to the model being repllicated for every thread?

**Comment by jsreid13** [comment]
I managed to get the locust load test running and have some results: Since we're using Google Kubernetes Engine I don'd have the option to pick a machine type of n1-standard-16, so I used a pod with 4Gi RAM 4CPU for the model, 1Gi RAM 1CPU router, 5Gi target average memory and 3Gi RAM 0.1 CPU engine to replicate you benchmark test and was unable to, perhaps I need more CPUs and RAM? With this pod I was only able to get up to 8 clients, 1 hatch rate and 2 replicas, when I increased it to 4 replicas it started timing out.
I also used a pod with 1Gi RAM 1CPU model, 1Gi RAM 1CPU router, 5Gi target average memory and 3Gi RAM 0.1 CPU engine all on 1 replica I was able to get up to around 222 requests/s from 5 clients without the API timing out, but at 10 clients it timed out. I'll keep running more tests, but if you have any suggestions to get more concurrent users I'd love to try them out!

**Comment by cliveseldon** [comment]
That's great @jsreid13 you got the setup working. Are you able to push a PR at some point with your tests so we can include them and allow iteration on them?

**Comment by jsreid13** [comment]
Sure I can take a shot at it, its pretty similar to the notebook you sent just specific for my environment. I can create a notebook similar to the one you have that has the helm template, kubectl apply and helm install locust commands, is there a specific location in the testing folder I should put it?

**Comment by cliveseldon** [comment]
Maybe create a new subfolder  `testing/benchmarking/notebooks` ?

**Comment by jsreid13** [comment]
I pushed an example notebook to perform a loadtest similar to the one we're doing but using your example mock_classifier and mab_epsilon_greedy router, the notebook can be found on my fork here https://github.com/jsreid13/seldon-core/blob/locust-loadtest/testing/benchmarking/notebooks/benchmark_simple_model.ipynb, I can create a PR to merge it into this repo if it looks good.
In order to run it you'll need to populate the NAMESPACE, GCP_PROJECT and 
LOCUST_IMAGE_LOCATION, they can be found in the first cell of the notebook. Let me know if you have any problems or questions!

**Comment by jsreid13** [comment]
Looks like we found a fix to the problem, the default options for spring.task.execution.pool.core-size,  spring.task.execution.pool.max-size, spring.task.execution.pool.queue-capacity need to be adjusted, we used 33, 200 and 1 respectively and found that the Seldon API no long hangs, but will instead return errors like 
```
"status": {
    "code": 206,
    "info": "org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ThreadPoolExecutor@25229f8c[Running, pool size \u003d 1000, active threads \u003d 121, queued tasks \u003d 0, completed tasks \u003d 137887]] did not accept task: org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$657/0x00000001006a3440@5981fd9",
    "reason": "Execution failure",
    "status": "FAILURE"
  }
```
Which are much more useful, and will just move on to the next request.

This can be added through the deployment YAML by setting spec.annotations.seldon.io/engine-java-opts to the value: 
`-server -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=127.0.0.1 -Dspring.task.execution.pool.core-size=33 -Dspring.task.execution.pool.max-size=200 -Dspring.task.execution.pool.queue-capacity=1`

**Comment by cliveseldon** [comment]
As this connects to #1597 - we should decide on what is a good default for the JAVA_OPTS

**Comment by cliveseldon** [comment]
Closing this. Please try in 1.1.0 for which the GoLang executor is now the default. This would be a good validation for your use case.
