### ISSUE TITLE
Allow users to define bin/bucket size for histogram custom metrics

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#1559]
According to discussion in : https://github.com/SeldonIO/seldon-core/pull/1507#discussion_r394480507

would be great to allow users define bin/bucket size for histogram custom metrics

**Comment by cliveseldon** [comment]
Can we configure executor for this as well.

**Comment by cliveseldon** [comment]
Closing as some investigation was done. Please reopen if issue.
