### ISSUE TITLE
Application level auth token verification on Seldon Core 

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1562]
This issue aims to explore the advantages / disadvantages of adding application level auth token verification with standard OICD provider options, with the objective of verifying or rejecting requests that have a token that is not valid. Currently the best practice and suggested authentication implementation is by ensuring the cluster has ingress-level authentication, so the token is actually validated on the ingress, instead to having it on an application-level.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by SachinVarghese** [comment]
I have been exploring this for quite some time and now started working on an example for clusters with istio enabled https://github.com/SachinVarghese/seldon-core/blob/auth/examples/auth/README.md

**Comment by cliveseldon** [comment]
This is great. Can you create a PR?

**Comment by cliveseldon** [comment]
Closing. Please reopen if we still need this or not done by @SachinVarghese PRs
