### ISSUE TITLE
seldon-core-crd helm chart is out of date

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1563]
https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-core-crd shows last changed 11 months ago

But https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml was last changed 2 days ago

**Comment by cliveseldon** [comment]
https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-core-crd should be deleted as its not used anymore.
