### ISSUE TITLE
Avoid logging that custom_tags or custom_metrics is not implemented on every request

### ISSUE THREAD

**Issue by taavi-primer** [SeldonIO/seldon-core#1565]
Currently the SeldonDeployments log on every request that custom_tags and custom_metrics are not implemented. This could be logged once on application start instead. Or at the very least moved to debug level.

```
2020-03-19 18:42:06,851 - seldon_core.user_model:client_custom_tags:131 - INFO:  custom_tags is not implemented
2020-03-19 18:43:10,423 - seldon_core.user_model:client_custom_metrics:304 - INFO:  custom_metrics is not implemented
```

**Comment by ChristophRose** [comment]
Even though this is closed, just a small note. To suppress this currently, add the following two functions to the model class:
`    def tags(self):
        return {}

    def metrics(self):
        return []`

**Comment by cliveseldon** [comment]
Thanks @ChristophRose If you think a small update to docs would help feel free to add a small PR.

**Comment by RafalSkolasinski** [comment]
I think such a note should specify for which wrapper version this is still relevant - latest s2i wrapper should properly have those logs at the `debug` level.
