### ISSUE TITLE
ensure we're using open source ambassador in examples

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1581]
Mostly we refer to a single setup page and leave it to the user to follow ambassador's docs. But sometimes we install ambassador and the default isn't the OSS version now. So https://github.com/SeldonIO/seldon-core/blob/master/components/outlier-detection/mahalanobis/outlier_mahalanobis.ipynb for example installs the trial version. 

To use the open source it should be https://www.getambassador.io/user-guide/install-ambassador-oss/#2-install-ambassador-api-gateway

**Comment by cliveseldon** [comment]
Do the core notebooks install the oss version?

**Comment by cliveseldon** [comment]
Looks like the other charts are deprecated so we should update to ensure Ambassador OSS is installed in future.

**Comment by cliveseldon** [comment]
The deprecated components have been removed. I think we can close this.
