### ISSUE TITLE
Make inclusion of metrics in SeldonMessage configurable in 1.1

### ISSUE THREAD

**Issue by ahutterTA** [SeldonIO/seldon-core#1582]
With model services directly exposing their own prometheus metrics the use cases for including them in the SeldonMessage diminish. We should make the inclusion of them in the returned SeldonMessage configurable through an environment variable (maybe `SELDON_SHOULD_SERIALIZE_METRICS`?) defaulting to `true`. In an upcoming release the default could be changed to `false`.

**Comment by RafalSkolasinski** [comment]
The environmental variable will be called `INCLUDE_METRICS_IN_CLIENT_RESPONSE` and can be set to `true` or `false`. Defaults to `true` for now.
