### ISSUE TITLE
Duplicated VirtualServices entries

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1594]
Using Istio, the operator seems to be creating duplicated `VirtualService` entries after updating some `SeldonDeployments`. Since both entries try to map the same URL, the result is that trying to access it will return in a **503 error**.

For a `SeldonDeployment` called `my-model-name`, the only differences between both seem to be:

- The service name in `Route.Destination.Host` changes between them. The old `VirtualService` points to a service name called `seldon-<hash>`, whereas the newer one points to `my-model-name`.
- The name of the `VirtualService` are also different. The old one is called `my-model-name-my-model-name-http`, whereas the new one is simply called `my-model-name-http`.

Maybe related to #1461?

**Comment by cliveseldon** [comment]
The name for the http virtual service should end in `-http` see https://github.com/SeldonIO/seldon-core/blob/7da6ec5f05371c738477fbb48333006227e0aec0/operator/controllers/seldondeployment_controller.go#L151

**Comment by adriangonz** [comment]
@cliveseldon that was a typo on my part. I've updated it on the description.
