### ISSUE TITLE
[document request] Add more technical details about service orchestrator

### ISSUE THREAD

**Issue by gaocegege** [SeldonIO/seldon-core#1596]
I am new to Seldon Core but familiar with KFServing. I find that the documentation about the service orchestrator is hard to understand. I cannot get why we need such an orchestrator and how it works.

I think we can improve it. We could have a graph like it and illustrate the workflow of orchestrator and help readers understand the design purpose of it.

![serving-Page-5](https://user-images.githubusercontent.com/5100735/77508395-8ea41a80-6ea5-11ea-9402-aaac9bc8582c.png)

**Comment by cliveseldon** [comment]
Hi @gageorge I agree better docs for the service orchestrator would be useful.
From 1.1 we will transition to a new GoLang executor for the service orchestrator: see https://github.com/SeldonIO/seldon-core/tree/master/executor

I think your diagram can be used for that as well. Happy to connect to chat.

**Comment by gaocegege** [comment]
Yeah, I notice that we are migrating to golang implementation. The graph I provided here is just used in my company to show the workflow of the orchestrator, not intend to be used by the doc directly.

**Comment by gaocegege** [comment]
BTW, there is a question about https://github.com/SeldonIO/mlgraph . I am wondering why we do not use the executor approach and propose mlgraph in Kubeflow community to implement the infer graph.

Personally, I think the executor is flexible and easy to maintain.
