### ISSUE TITLE
Be able to scale SeldonDeployment objects using kubectl

### ISSUE THREAD

**Issue by pisymbol** [SeldonIO/seldon-core#1598]
kubectl allows one to scale their normal Deployment objects using the 'kubectl scale' command by setting the '--replicaset' command line argument to the number of Pods you want the underlying ReplicaSet to achieve.

However, with SeldonDeployment objects, you can't do this. In fact, in 1.0+, you can't even use `kubectl scale` on the underlying Deployment object that backs the SeldonDeployment one to up the number of prediction server Pods.

What you have to do is delete and redeploy the SeldonDeployment object and up the number of 'replicas' in the original YAML/JSON deployment file.

I think it would be best if SeldonDeployment objects could scale like regular Deployment ones as their configuration and management idioms should be fairly the same.

(I also think both 'seldonDeployment' and 'seldondeploy' should work with kubectl too, just like deployment).

**Comment by cliveseldon** [comment]
Duplicate #1592
