### ISSUE TITLE
allow to use Java engine if helm installation defaults to executor

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1607]
If `seldon-core` is installed using helm with `--set executor.enabled=true` one cannot deploy a single POD using engine.

In opposite situation, when above is set to `false`, one can enforce executor with annotations:
```
spec:
  annotations:
    seldon.io/executor: "true"
```

P.S. Not sure how much it is important as we are going to deprecate Java engine.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by axsaucedo** [comment]
/remove-lifecycle stale
/priority p1
Adding high priority given that this will be quite key for backwards compatibility support
