### ISSUE TITLE
Explore how to support breaking change upgrades 

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1637]
## Context

We have seen in some recent changes (e.g. #1593, #1594) how, under some scenarios, we may require to make changes on the already-created resources existing in the cluster during upgrades of Seldon Core. 

Note that, on the issues listed above, we were able to either keep supporting the previous functionality or to let the operator "fix" the situation itself. However, that means that the code will now need to maintain explicit support for both scenarios (+ any new ones).

## Proposal

Moving forward, it would be good to explore if there are any other alternatives built into Kubernetes to handle these kinds of _"migrations"_. This means, a set of changes that get applied when we upgrade Seldon Core to a new version. For example, it could mean modifying all existing `SeldonDeployments` to change the value of one of the fields.

Keeping these migrations separate as small "scripts" / functions (which get applied sequentially upon an upgrade) would make them easier to maintain. Note that these migrations would ideally be kept separately from the main operator code, making them more explicit.

These would be analogous to the migrations which are usually ran for database changes.

**Comment by cliveseldon** [comment]
This should be handled by CRD conversion: https://book.kubebuilder.io/multiversion-tutorial/conversion.html
However, its a more recent feature in k8s.

**Comment by cliveseldon** [comment]
We have upgrade notes now. Closing - can reopen if we think the current process needs updates for V2
