### ISSUE TITLE
[document] Seldon Core Roadmap is missing

### ISSUE THREAD

**Issue by gaocegege** [SeldonIO/seldon-core#1646]
Cannot find the roadmap here: https://github.com/SeldonIO/seldon-core/blame/master/README.md#L348

It seems that after v1, we do not have a new roadmap.

**Comment by cliveseldon** [comment]
Yes we need to remove that page. The key pages are:
[Strategic Roadmap](https://github.com/SeldonIO/seldon-core/projects/19)
[Release 1.1](https://github.com/SeldonIO/seldon-core/projects/16)
[Release 1.2](https://github.com/SeldonIO/seldon-core/projects/18) - this still need Triage after 1.1 is out.

**Comment by cliveseldon** [comment]
Rather than remove have added in PR with above links
