### ISSUE TITLE
Request for Java version of Seldon Grpc Client 

### ISSUE THREAD

**Issue by rnarasimhan88** [SeldonIO/seldon-core#1656]
Hello,

I've successfully used the python SeldonClient in the past and currently I am working on project that requires me to use Java for inference over grpc. Is there a Java version of the SeldonClient available? 

I think it would be a good feature to add if it's currently not available.

**Comment by axsaucedo** [comment]
@rnarasimhan88 for GRPC you would be able to interact with the API with any Java GRPC library by using the Protos, that is one of the many benefits of the remote procedural call interface of GRPC. For REST we actually ensure that the APIs are aligned to the OpenAPI protocol which means that you can use the schema to automatically leverage the language clients https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/openapi.html
