### ISSUE TITLE
Use zap.New instead of zap.Logger

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1657]
In the operator we are currently using `zap.Logger()` to instantiate a new logging object. This is inherited from the code generated by Kubebuilder.

https://github.com/SeldonIO/seldon-core/blob/6818fb304e756d7c90f7fbe980c1af797e096631/operator/main.go#L70

However, [`zap.Logger()` has now been deprecated](https://github.com/kubernetes-sigs/controller-runtime/blob/df180accb901c816ced95a7b1a6eaf2c801f3560/pkg/log/zap/zap.go#L44-L50) for `zap.New()`. Kubebuilder has also updated how it generates the logging code to use the new method in https://github.com/kubernetes-sigs/kubebuilder/pull/1101.

**Comment by cliveseldon** [comment]
This should be for python wrapper, executor and operator.

**Comment by adriangonz** [comment]
Moved part of the scope of this issue to https://github.com/SeldonIO/seldon-core/issues/1737

**Comment by adriangonz** [comment]
Closing this one for now. The `zap.Logger()` method doesn't seem to be going anytime soon.
