### ISSUE TITLE
Profile the CRD operator

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#167]
We should run load tests with dummy prediction graphs to profile the CRD operator at scale.

**Comment by cliveseldon** [comment]
Any opinions on this @phsiao ?

**Comment by phsiao** [comment]
Have not given it much thought, but my general opinion is that admission controller's (mutating  and validating webhook) performance have more impacts on operations than the reconciliation controller.  But neither may not have direct impact to the user's perceived performance, as these happens in the background and user expect them to be consistent over the timescale of minutes.

I don't think we collect webhook/reconciliation loop response time stats, and that might be a starting point.

What would you consider to be at scale?  hundreds or thousands of seldon deployment, at the rate of change of tens per hour?

**Comment by cliveseldon** [comment]
Moving this to 1.1 for reason given above. Not sure yet on the bets tools for this.

**Comment by cliveseldon** [comment]
Duplicate of https://github.com/SeldonIO/seldon-core/issues/1731
