### ISSUE TITLE
Allow custom inference server without modifying global configmap

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1674]
If it possible to specify custom inference server without modifying `configmap` it may be worth adding.
It would allow users who only have single-namespace access to deploy such servers without asking admins to modify seldon-core wide configmap.

_Originally posted by @RafalSkolasinski in https://github.com/SeldonIO/seldon-core/pull/1673#issuecomment-610815733_

**Comment by cliveseldon** [comment]
This seems less likely. Can add to V2 as possible discussion point.

**Comment by cliveseldon** [comment]
Please try with [MLServer](https://github.com/SeldonIO/MLServer)
