### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 32772 path $.data.ndarray[1] at io.seldon.engine.pb.JsonFormat$ParserImpl.merge(JsonFormat.java:1132) ~[classes!/:0.5.1-SNAPSHOT] at io.seldon.engine.pb.JsonFormat$Parser.merge(JsonFormat.java:313) 

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#1680]
Hi Clive,
I am getting this issue when I am trying to pass a base64 string as input .

{'data': {'names': [],
  'ndarray': [["base64 string"]]}}.
I have seldon 0.5.2 installed on my google kubernetes engine.

I get the following response json back
{'status': {'code': 201,
  'info': '{"data": {"names": [], "ndarray": ["base64 string"],
  'reason': 'Invalid JSON',
  'status': 'FAILURE'}}

Kindly help.

**Comment by cliveseldon** [comment]
strange. `{"data": {"names": [], "ndarray": ["base64 string"]` does seem to be invalid.

I would also suggest upgrading to 1.0.2 of Seldon if possible.

**Comment by divyadilip91** [comment]
Oh is the json format invalid? What would be the correct format?The base64 string is that of an image that I give as input.
Yes I am planning to upgrade to 1.0.2..
Would replacing the old container image with the new one do the upgrade or I need to do uninstall the old one and start the installation from beginning?. I couldnt find any docs that describe the upgrade process. Please suggest

**Comment by cliveseldon** [comment]
Please follow https://docs.seldon.io/projects/seldon-core/en/v1.1.0/reference/upgrading.html
