### ISSUE TITLE
Seldon Build Permission Denied

### ISSUE THREAD

**Issue by praveenporsche** [SeldonIO/seldon-core#1689]
I am following the procedure to deploy a pipeline using Seldon Core.
I have all the files in the hierarchy per your examples under pipeline/pipeline_steps/transformer but, when I try to build the shell script using bash under the Jupyter notebook (build_image.sh), I get a permission denied error. How can I elevate my permissions within the Jupyter Notebook?

If I execute in a cell within the Jupyter notebook, "--user" does the trick. Not sure how that translates to running a bash script. Please help.

**Comment by cliveseldon** [comment]
Is this a kubeflow pipeline/jupyter issue? If so I assume it depends on the RBAC given to the kubeflow pipelines runner or jupyter user?

**Comment by axsaucedo** [comment]
Closing inactive issue
