### ISSUE TITLE
PREDICTIVE_UNIT_PARAMETERS: not able to set them up correctly

### ISSUE THREAD

**Issue by smolina74** [SeldonIO/seldon-core#170]
Hi,

I'm trying to pass extra parameters to my model using PREDICTIVE_UNIT_PARAMETER set in the s2i environment file. Currently my file looks like the one below

MODEL_NAME=SkMnist
API_TYPE=REST
SERVICE_TYPE=MODEL
PERSISTENCE=0
PREDICTIVE_UNIT_PARAMETERS=[{
    "a":2,
    "b":3
}]

but after deploying, when checking for PREDICTIVE_UNIT_PARAMETERS env variable I'm seeing just an empty array ([]).

Am I setting this variable in a proper way? (according to the documentation it is a json string.

thanks,
Santiago

**Comment by cliveseldon** [comment]
Hi,

You should add these to your SeldonDeployment resource, see [here](https://github.com/SeldonIO/seldon-core/tree/master/docs/crd). An example k8s json that shows this can be seen in a [random ab test](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/resources/random_ab_test.json). You can also add whatever env variables you want to the k8s PodTemplateSpec in your componentSpec field.
