### ISSUE TITLE
Add and example Notebook for Istio Setup and Integrations

### ISSUE THREAD

**Issue by roshanzameer** [SeldonIO/seldon-core#1712]
The current example notebooks which instruct on using Istio as ingress do not describe as to how Istio needs to be setup. An example which includes the below pointers would be a great help in using Istio over Ambassador as the latter doesn't support gRPC (Bugs).

1. Installation of Istio
2. Creating Istio gateway
3. Creating Istio Virtual Service and Service Entries  etc

**Comment by cliveseldon** [comment]
We would welcome additions to https://docs.seldon.io/projects/seldon-core/en/latest/ingress/istio.html to help make things clearer. If you are able to do a PR?

You should not need to create any Virtual Services.

**Comment by cliveseldon** [comment]
Also we have an example notebook https://docs.seldon.io/projects/seldon-core/en/latest/examples/istio_examples.html

**Comment by axsaucedo** [comment]
Istio has massively simplified installation with `istioctl install` and we now reference to it in the docs
