### ISSUE TITLE
Serialization of pre-processing pipeline for CI/CD

### ISSUE THREAD

**Issue by jhagege** [SeldonIO/seldon-core#1713]
Hi, thanks for the great library.
I noticed in your examples you serialize the preprocessing pipeline.
Does it assume that the pip dependencies of the preprocessing classes need to be the exact same version ? 
I'm trying to think how to package the inference workflow inside a single Dockerfile as part of a CI/CD pipeline.
How can I guarantee that I have a self-contained Docker image with the correct exact dependencies and the serialized pre-processing pipeline.

Thanks for any insights.

**Comment by cliveseldon** [comment]
Hi @jhagege 
Can you give some more details of the examples you are referring to and what you mean by "pre-processing pipeline"?

**Comment by jhagege** [comment]
@cliveseldon , thanks for your quick answer. 

I was referring to the following: 
![image](https://user-images.githubusercontent.com/7504908/79766217-57a01800-8330-11ea-8f8c-284055d63d37.png) from the [outlier_combiner](https://docs.seldon.io/projects/seldon-core/en/latest/examples/outlier_combiner.html) example.

I find the pattern elegant and I'm wondering how to take it one step further.
Each model created is defined by three "artifacts":
- Source code (commit id)
- Preprocessor pipeline (transforms) 
- Environment (python packages for example in a requirements.txt with their dependencies version).

I'd like to configure a CI pipeline to package all of those into some kind of an "uber-artifact", per model that is trained, so that it can provide an integrated environment for inference.

Thanks for any insights.

**Comment by RafalSkolasinski** [comment]
We are not really concentrating on training. 

It seems that the best approach is to have a solid reproducible preparation of artefacts / trained models (kubeflow, dvc, pachyderm, ...) and then package these into a Docker image that you can deploy with Seldon. 

Check our latest addition of model metadata: https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/metadata.html that allows one to make connection to the training source of the model.

**Comment by jhagege** [comment]
Thanks much, I'll review.
