### ISSUE TITLE
custom tags in release 1.1.0 not working

### ISSUE THREAD

**Issue by JulianBarr** [SeldonIO/seldon-core#1715]
Hi,

I've encountered this while using 1.1.0.

I have a pipeline of a few models/transformers.

In one of the transformer, I defined a tags method as below.

```python
def tags(self):
    return {"abc":"def"}
```

In subsequent transformers, in the transform_input method, I can't access the tags.

```python
def transform_input(self, X, names, meta):
    loggers.info(meta)
```
It's empty.

It was working in 1.0.0 release. I was able to get the information with `meta["tags"]["abc"]`.

**Comment by RafalSkolasinski** [comment]
Hi @JulianBarr! 

What version of s2i wrapper are you using? 
For `tags` to work properly you need wrapper 0.19 or greater (suggest 1.1.0).

**Comment by JulianBarr** [comment]
I am using 0.15. I'll try a newer version and test.

**Comment by RafalSkolasinski** [comment]
Yes, please do. I just verified that it should be working properly.

**Comment by RafalSkolasinski** [comment]
@JulianBarr I am closing this issue, please reopen if you find it not working properly with latest wrapper.

**Comment by JulianBarr** [comment]
Ok, it works in 1.1.0.
