### ISSUE TITLE
Leader election config map is not getting deleted in seldon-core-operator

### ISSUE THREAD

**Issue by mukul-shaunik** [SeldonIO/seldon-core#1717]
seldon-core-operator version -- seldon-core-operator-1.1.0.tgz

**Steps to reproduce**
```
helm install seldon-core-operator --name s2 --namespace s2
helm delete --purge s2
```

**Actual result**
`kubectl get configmaps -ns2`  gives output 
```
NAME                                 DATA   AGE
a33bd623.machinelearning.seldon.io   0      24m
```

**Expected result**
`kubectl get configmaps -ns2`
should not show any configmaps

**Comment by cliveseldon** [comment]
We use kubebuilder and we would need to see if its an issue in that project and raise an upstream request: https://github.com/kubernetes-sigs/kubebuilder/issues?q=is%3Aissue+is%3Aopen+leader

**Comment by axsaucedo** [comment]
@cliveseldon is this still an issue? Would it be linked / fixed with the update to latest kubebuilder with k8s 1.18?

**Comment by cliveseldon** [comment]
I think this is fixed in leadership election PR changes.
