### ISSUE TITLE
createResources flag in helm chart looks backwards

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1723]
Only creates configmap if createResources is set to false.

https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/configmap_seldon-config.yaml#L1

Passing this on after a customer hit trouble with it.

**Comment by cliveseldon** [comment]
`createResources` is for the Operator itself to create the core resources: configmap, webhook svc, webhook configuration rather than use yaml.

**Comment by ryandawsonuk** [comment]
Eventually we realised it needs to be set to false so that the resources are created via helm rather than operator.

It is a bit confusing as a [create flag is often used in helm charts](https://github.com/helm/charts/search?l=YAML&q=create) to indicate whether helm should create the resource.

**Comment by ryandawsonuk** [comment]
`createResourcesOnStartup` might be better

**Comment by ryandawsonuk** [comment]
Actually, thinking back what caused confusion was less the name and more the comment in the values file that says `# Whether to create the webhook service, and webhookconfigurations on startup` so it wasn't realised that it affected the configmap
