### ISSUE TITLE
seldon.io/rest-read-timeout for ambassador doesn't take effect in executor 1.1.0?

### ISSUE THREAD

**Issue by JulianBarr** [SeldonIO/seldon-core#1724]
While testing executor 1.1.0, I noticed that ambassador always take time out after about 3 seconds which should be the default setting.

I searched and noticed that java engines actually take `seldon.io/rest-read-timeout` to ambassador mapping `timeout_ms`. Is this not implemented in go version executor? If so, is there any way to work around with this?

Thanks.

**Comment by JulianBarr** [comment]
I figured out that ambassador custom config does work.

**Comment by cliveseldon** [comment]
This could be a docs bug can you try the annotation on https://docs.seldon.io/projects/seldon-core/en/v1.1.0/graph/annotations.html
