### ISSUE TITLE
problem configuring S3 access from MLFlow server

### ISSUE THREAD

**Issue by delcacho** [SeldonIO/seldon-core#1727]
I am trying to deploy a model from an Mlflow tracking server available in S3, passing AWS credentials through a secret in Kubernetes:

apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://mlruns/1/600d698441fd4fe1b99974fbf2b17d66/artifacts/wine
        name: classifier
        envSecretRefName: seldon-init-container-secret
      name: default
      replicas: 1

I have created the following secret

kubectl create secret generic seldon-init-container-secret \
    --from-literal=AWS_ACCESS_KEY_ID='XXXX' \
    --from-literal=AWS_SECRET_ACCESS_KEY='XXXX' \
    --from-literal=AWS_ENDPOINT_URL='clusters.dev.bayescluster.com' \
    --from-literal=USE_SSL=false

And here is the output of the log file of the init container. Any idea what's wrong? Thank you.

[I 200422 13:33:40 storage:35] Copying contents of s3://mlruns/1/600d698441fd4fe1b99974fbf2b17d66/artifacts/wine to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 50, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 65, in _download_s3
    client = Storage._create_minio_client()
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 217, in _create_minio_client
    secure=use_ssl)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 150, in __init__
    is_valid_endpoint(endpoint)
  File "/usr/local/lib/python3.7/site-packages/minio/helpers.py", line 301, in is_valid_endpoint
    if hostname[-1] == '.':

**Comment by delcacho** [comment]
Apparently, I have managed to get it working. I had the wrong AWS ENDPOINT. After changing it for https://s3.us-east-1.amazonaws.com/ it works like a charm. Case closed. Thank you for writing this piece of software.

**Comment by cliveseldon** [comment]
@delcacho Thanks for the report will be useful for others. Glad its working.
