### ISSUE TITLE
Enable production settings in loggers

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1737]
On the operator, it would be good to set the `Development` flag to `false` before through some environment variable, which [improves performance a bit in production environments](https://github.com/kubernetes-sigs/controller-runtime/blob/df180accb901c816ced95a7b1a6eaf2c801f3560/pkg/log/zap/zap.go#L128-L131). By default, it also controls [which levels are logged](https://github.com/kubernetes-sigs/controller-runtime/blob/df180accb901c816ced95a7b1a6eaf2c801f3560/pkg/log/zap/zap.go#L141-L144).

Additionally, we should also make sure that we do this for the Python wrapper and the executor.

**Comment by ellisvalentiner** [comment]
I am also interested in this.

Relevant slack: https://seldondev.slack.com/archives/C8Y9A8G0Y/p1589563385116600
