### ISSUE TITLE
Built-in header based routing

### ISSUE THREAD

**Issue by wave112** [SeldonIO/seldon-core#1739]
It would be great to have got the possibility to have 1 SeldonDeployment which might contain:
* multiple frameworks ie. TensorFlow or OpenVino etc. A client could choose which framework could use.
* multiple versions of the served model for a particular framework. I.e. TensorFlow has got 2 models: `resnet50 v1` and `resnet50 v2`. A client could choose which model version could use.

I do not mean to use a router component because I wouldn't like to implement a microservice and compare results between models or frameworks.
So that client could pick a framework or a model version that would like to use as a parameter of prediction.

**Comment by cliveseldon** [comment]
We want to do this as part of V2 data plane. Otherwise you might need to look at using a Router for now.
