### ISSUE TITLE
Support for using Contour as Ingress

### ISSUE THREAD

**Issue by josephglanville** [SeldonIO/seldon-core#1754]
Hi.

We (Postmates) are standardising on Contour as our edge/ingress stack of choice and want to integrate Seldon Core into our ML stack. As a part of this we are implementing support for creating Contour HTTPProxy objects for predictor/explainer services.

Would the Seldon Core project be open to a PR that implemented functionality similar to what currently exists for Ambassador utilising Contour?

I am currently in progress implementing said feature for our own use but would like to start dialog around how we could upstream this effort.

Namely for now I am "hacking" in support similar to how Istio/Ambassador are enabled using environment variables.

I think this is a good first pass but I think long term if Seldon wants to support more flexible means of routing traffic to models there should probably be an IngressPlugin interface implemented. If that is of interest I can create a separate issue to discuss what such an interface would need to expose to be effective.

**Comment by cliveseldon** [comment]
@josephglanville Yes be good some way to abstract ingress' to allow more to be added. Let's discuss.

**Comment by cliveseldon** [comment]
Please try in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/)
