### ISSUE TITLE
model server pods not created if controllerId set?

### ISSUE THREAD

**Issue by chengchengpei** [SeldonIO/seldon-core#1758]
I tried the following commands to install seldon-core on my minikube.
```
helm install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --namespace team-xxx --set usageMetrics.enabled=false --set ambassador.enabled=true --set ambassador.singleNamespace=true --set certManager.enabled=false --set createResources=false --set singleNamespace=true --set defaultUserID=team-xxx --set controllerId=seldon-core-controller-id

helm install ambassador stable/ambassador -n team-xxx --set crds.keep=false

kubectl apply -f ../tests/test_model.yml -n team-xxx
```

No errors. but model server pods are not created at all.
It seems that I cannot set `controllerId`.

**Comment by adriangonz** [comment]
@chengchengpei does the `test_model.yml` point to that `controllerId`? It needs to be labeled like `seldon.io/controller-id=seldon-core-controller-id`. 

You can read more on label-scoped deployments here: https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#label-focused-seldon-core-operator-version-1-0

**Comment by adriangonz** [comment]
@chengchengpei did you manage to fix the above? Please reopen if this is still an issue.
