### ISSUE TITLE
Organization of Python Modules

### ISSUE THREAD

**Issue by Ogaday** [SeldonIO/seldon-core#1759]
This is a bit pedantic, so feel free to ignore:

Working on #1757 I thought some improvements could be made to the organization of the Python modules.

I would have liked to have added the `split_image_tag` function to the `utils` module, but `utils` has a transitive dependency on the `metrics` module, meaning if `metrics` imports from `utils`, you get circular import errors.

![seldon_core](https://user-images.githubusercontent.com/6689770/80465655-4c05b000-8933-11ea-804f-5616556e3190.png)

Also, I notice there was some duplication between the metrics and the metadata modules in terms of grabbing image data. Perhaps this could be factored out so environment variables are only being accessed in one place, and not at the module scope level?

**Comment by cliveseldon** [comment]
We plan to move to MLServer  eventually for custom models. So maybe can you validate it provides more clarity?
