### ISSUE TITLE
Fix broken documentation links

### ISSUE THREAD

**Issue by ellisvalentiner** [SeldonIO/seldon-core#1760]
Slack thread: https://seldondev.slack.com/archives/C8Y9A8G0Y/p1588085733389600

Many documentation links are broken.

A tool like [muffet](https://github.com/raviqqe/muffet) may be helpful to check for dead links when building the documentation.

**Comment by adriangonz** [comment]
/priority p1

Some of these will get fixed in #1743, but it would be great to look at automating this.
