### ISSUE TITLE
Seldon Core v1.1.0 helm chart has outdated seldon-config configmap 

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1779]
All prepackaged model servers were updated in 1.1.0 but the changes were not reflected in the helm chart configmap. We should explore what's the best way of adding this change to v1.1.0 (override vs patch fix)
/priority p0
/milestone 1.2
/project 1.2.0

**Comment by cliveseldon** [comment]
This is being covered by https://github.com/SeldonIO/seldon-core/pull/1775
