### ISSUE TITLE
Exposing the wrapper version to operator for backwards compatibility flags

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1783]
Explore exposing the version of the wrappers used to containerise models through k8s config such that the operator / executor can use that information to enforce/infer backwards compatibility configurations required (which could help for backwards compatibility upgrades of executor when breaking changes take place such as the metrics piece in 1.1.0 or the "run-with-engine" tag)

**Comment by cliveseldon** [comment]
Closing. Can reopen if we think this still has import and overlaps testing review
