### ISSUE TITLE
Align GPU TF Python Image requirements and structure

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1789]
Currently the GPU TF python image has a few areas in which it differs from the python image:
* It contains a requirements.txt file by default that would be used if no requirements.txt is available
* Unlike the other images it doesn't support conda so it would crash if conda path was accessed
* Currently only python 3.7 is supported with TF image

**Comment by RafalSkolasinski** [comment]
First two points were just addressed in https://github.com/SeldonIO/seldon-core/pull/1972 and https://github.com/SeldonIO/seldon-core/pull/2045.

However there is still `requirements.txt` which includes `tensorflow-gpu`. 

As recently discussed with @axsaucedo we plan to deplracete `GPU TF` image and have a pure `GPU` image. 
This means that for current GPU image we need:
- [ ] tensorflow-gpu (drop requirements.txt completely as it only has this single dep right now)
- [ ] build for both Python 3.6 and 3.7
- [ ] deprecate `seldon-core-s2i-python3-tf-gpu` in favour of `seldon-core-s2i-python36-gpu` and `seldon-core-s2i-python37-gpu`

**Comment by RafalSkolasinski** [comment]
Wonder if we should try to make Python 3.8 a default now? 
@axsaucedo @cliveseldon, what do you think?

If we move master to be 3.8 by default now there should be plenty of time to test it in action before 1.3 release.
