### ISSUE TITLE
Introduce caching for image builds in our CI pipeline

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1794]
Currently images are built every time in our dated SNAPSHOT CI pipeline. We'd want to avoid rebuilding images if the respective source code has not been edited. Instead we could just tag the already existing image and push that. That woudl also ensure we avoid replication of layers in the docker side (and faster build times)

**Comment by cliveseldon** [comment]
Closing. Can be added maybe to a general review of CI in Seldon Core.
