### ISSUE TITLE
Seldon core wrapper support for Spring 2

### ISSUE THREAD

**Issue by gunjangsharma** [SeldonIO/seldon-core#1796]
The existing seldon-core-wrapper uses Spring Boot 1.5, when running H2O example on spring 2 app starts to fail with java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizer.

Can you update the example on how to use warpper with latest version of spring.

**Comment by cliveseldon** [comment]
I assume you are referring to the Java wrapper. This wrapper is still in incubating and we are looking for contributors to update it. Would you be willing to do a PR to provide the necessary update?

**Comment by marrrcin** [comment]
Java wrapper in current state is a disaster, it uses deprecated libraries, pushes a lot of assumptions and hidden dependencies into end user code - i.e it enforces to use Tomcat, enforces overall application structure and imports, always tries to boot GRPC even though it shouldn't. The wrapper and example assume that you use s2i, which in serious business environment is often not an option, when you have complex build pipelines.

**Comment by cliveseldon** [comment]
Sounds like you have a lot of good ideas to improve it. S2i is not required and is just one illustration of how to containerize the wrapper.
