### ISSUE TITLE
idletimeout between envoy and executor

### ISSUE THREAD

**Issue by andrewshaoyu** [SeldonIO/seldon-core#1797]
In my test environment, when call the model service by istio gateway with exectuor,then i found some 503 error.
finally, i found the error caused by the connection error.
1. envoy create a tcp connection to executor,send a http request
1. envoy keeps the connection,but in next 15s,no new http request use the connection,the connection is idle
1. executor send a fin to close the connection,because the executor's config readtimeout is also use as idletimeout
1. but before envoy replays to the fin, envoy send a new http request throw the connection
1. then envoy gets an error and replays 503 to downstream.

so exectour can set idletimeout instead of use default readtimeout,such as 65s,then in destinationrule set idletimeout 60s. let envoy close the connection.

**Comment by cliveseldon** [comment]
Hi @andrewshaoyu thanks for the detailed exploration.

So you are saying the executor idle timeout should always be smaller than that set of the virtualService created?

Are you able to create a small PR to focus the changes needed or put the details in this issue so we can discuss?

**Comment by andrewshaoyu** [comment]
yes, set the smaller value, let envoy to close connection,beacause envoy is the producer.
here is the error cap from envoy.
![图片](https://user-images.githubusercontent.com/7361471/81148485-efe40100-8fae-11ea-9b14-761e654e1319.png),
later, i will make the PR
