### ISSUE TITLE
Better names for metric ports of SeldonDeployment containers

### ISSUE THREAD

**Issue by xaniasd** [SeldonIO/seldon-core#1798]
SeldonDeployment defines the metrics port as `metrics` in the pod template. There are 2 such ports, one at the seldon-container-engine container and another at the predictive unit's container (for custom metrics). Since the deployment exposes multiple ports (with unknown port numbers until runtime), it would be convenient to have better names for the metrics ports. This would specifically allow defining prometheus jobs using regex to scrape the desired ports.

Ideally we'd like to have (optionally configurable) metrics port names that can be associated with seldon-specific jobs (e.g. metrics-seldon).

**Comment by cliveseldon** [comment]
Can you suggest an update like two new configurable env variables?, e.g.:

 - SVC_ORCH_METRIC_PORT_NAME: "metrics"
 - MODEL_METRIC_PORT_NAME: "metrics"

**Comment by xaniasd** [comment]
@cliveseldon I'm really bad with names :) and anything will do as far as I'm concerned. 

If I look at the currently used convention, perhaps `PREDICTIVE_UNIT_METRICS_PORT_NAME` and `SVC_ORCH_METRICS_PORT_NAME`? I see that EXECUTOR_ and ENGINE_ are used as well, are these deprecated?

**Comment by cliveseldon** [comment]
actually lets keep as EXECUTOR_ as that is still current. The engine is deprecated.

Are you able to create a PR for this?

**Comment by xaniasd** [comment]
sure, I'll take a stab at it
