### ISSUE TITLE
configurable metrics port name for analytics

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#1809]
The metrics port name has been hard-coded but is [now becoming configurable](https://github.com/SeldonIO/seldon-core/pull/1806) through a contribution from @xaniasd. 

That port name is referenced in the scrape config in the [seldon analytics chart](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-analytics/files/prometheus/prometheus-config.yaml#L99). We should make it configurable in that chart too.

**Comment by cliveseldon** [comment]
You interested @xaniasd to add a PR for this?

**Comment by axsaucedo** [comment]
We should probably move this to 1.2 as it seems we may get issues otherwise (such as #1854)

**Comment by ryandawsonuk** [comment]
Actually on a second look I don't think the name of the metrics port matters. I think seldon pod metrics get scraped on the correct port just because the metrics port points to the same port as the container port (8000).

Worth noting that port being scraped can be overridden with `prometheus.io/port` annotation. So if a different port were used then that annotation would be used to handle it. But there's no option to put the metrics endpoint on a different port with seldon, just to change its name. So this is a non-issue.
