### ISSUE TITLE
Multi-output support

### ISSUE THREAD

**Issue by pisymbol** [SeldonIO/seldon-core#1818]
We have several models that return an image as well as some meta along with it (e.g. annotations). Currently the SeldonMessage format is a bit restrictive on what return types it allows by using the "oneof" protobuf operator.

Why not just have the return type by any of the acceptable fields and serialize accordingly? This allows clients to cherry pick (or use all) of the model's output as it sees fit. Right now, the only work around seems to be to use the "names", "meta.tags", or stuff everything in a jsonDict which are all somewhat awkward.

**Comment by axsaucedo** [comment]
@pisymbol currently it's possible to just return a dictionary, which would end up returning as a jsonData. Would this not work? Alternatively you can use `predict_raw` which would allow you to deal with all of the inputs and outputs as required.

**Comment by pisymbol** [comment]
So how would an image tensor be encoded in the JSON? Would I have to base64 encode it?

**Comment by axsaucedo** [comment]
Yes, it has to be serialised as ultimately when it sends it through the network it ultimately is json, the alternative would be to use the grpc approach, but for the rest, it would always be a json

**Comment by cliveseldon** [comment]
This is addressed by V2 protocol.
