### ISSUE TITLE
Is it possible to access /health/status and /metadata endpoints defined in seldon through ambassador

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#1822]
Hi,

At present, I have noticed that /health/status and /metadata endpoints are accessible when the docker is run locally and tested 
Eg: curl http://ipaddress/health/status 
But when I try to access http://ambassadorexposedip/prefix/health/status, it shows 404 error.
So is /api/v0.1/predictions endpoint only accessible through ambassador?
Please do Reply

**Comment by cliveseldon** [comment]
Yes - we need to extend the external API to add status, health and metadata endpoints that are applicable per model component and for the entire graph. @RafalSkolasinski

**Comment by divyadilip91** [comment]
Thankyou @cliveseldon .So would this be applicable for the other endpoints as well such as /predict , /transform-input ,/transform-output , /route , /aggregate ?

**Comment by cliveseldon** [comment]
Was not thinking those as they are internal to the inference graph. But the ability to call any sub-part of the inference graph externally would be useful for testing.

**Comment by divyadilip91** [comment]
Yes true

**Comment by RafalSkolasinski** [comment]
I do believe that single model metadata endpoints are already available, for example
```
curl -s http://ambassador.mydomain.com/seldon/seldon/my-deployment/api/v1.0/metadata/my-model
```

**Comment by divyadilip91** [comment]
> I do believe that single model metadata endpoints are already available, for example
> 
> ```
> curl -s http://ambassador.mydomain.com/seldon/seldon/my-deployment/api/v1.0/metadata/my-model
> ```

my-model is the name of the model used in the graph rite?
Is this available in seldon v1.1.0?

**Comment by RafalSkolasinski** [comment]
Yes, that's the name used in the graph. It should be available in v1.1.0 if you run the new golang orchestrator (default).

**Comment by RafalSkolasinski** [comment]
The single model metadata are covered in the example: https://docs.seldon.io/projects/seldon-core/en/latest/examples/metadata.html

**Comment by divyadilip91** [comment]
@RafalSkolasinski Ok..so will this work if we have multinode graph?
Eg : a graph with a transformer and model.

**Comment by RafalSkolasinski** [comment]
This right now is querying the a single model at a time specified by the endpoint you're calling.
But yes, it will work with multi-node graphs but you have now to call each endpoint on your own.

We are currently working on providing a graph-level metadata in https://github.com/SeldonIO/seldon-core/issues/1728 (including all models' metadata too) but this is still WIP with initial PR https://github.com/SeldonIO/seldon-core/pull/1803 to land soon.

I guess the scope of the issue here would be to allow for sth like
```
curl -s http://ambassador.mydomain.com/seldon/seldon/my-deployment/api/v1.0/health/my-model
```
to work in similar manner as `metadata`.

**Comment by divyadilip91** [comment]
@RafalSkolasinski Yes

**Comment by divyadilip91** [comment]
> Was not thinking those as they are internal to the inference graph. But the ability to call any sub-part of the inference graph externally would be useful for testing.

@RafalSkolasinski Is this possible to be included in future seldon version wherein we can call the subpart of inference graph using the ambassador endpoint?

**Comment by cliveseldon** [comment]
In [v2](https://docs.seldon.io/projects/seldon-core/en/v2/) you can check status of individual models as well as for Pipelines get overall readiness.
