### ISSUE TITLE
Feedback method is not handled in the engine's REST API 

### ISSUE THREAD

**Issue by ejianu** [SeldonIO/seldon-core#1825]
Normally, the `/api/v1.0/feedback` (or `/api/v0.1/feedback`) should be handled so that we can make requests through the Seldon engine - as advertised in the documentation [here](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/external-prediction.html#feedback) via the external API.

We are able to use `/predictions` and `/send-feedback` (for calling the microservice API), both working as expected.

However, in the current server.go implementation there is no specification regarding feedback, resulting in **404 errors** in our environment when trying to use the external API.

Please add or guide us if we are misusing the API :) 
thank you

**Comment by cliveseldon** [comment]
Yes, this is missing from the go executor REST and should be added. It is available presently in gRPC.
