### ISSUE TITLE
Adding support for a post response hook

### ISSUE THREAD

**Issue by flpymonkey** [SeldonIO/seldon-core#1826]
Per my conversation in the slack community channel: https://seldondev.slack.com/archives/C8Y9A8G0Y/p1589319361077600

I am running into an issue where in my user model predict_raw module we are trying to log some information to a file inside of the running pod, but that logging is slowing down our response time for the seldon service. To try to solve this, we are spinning up a separate process to handle this logging; however, even trying to pipe log data over to that other process is slowing down the seldon response.
I was wondering if there was a way to use something like flask's teardown_request (https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.do_teardown_request), or atexit for a gunicorn process, to allow for a quick response while the logging thread/process is handled in the background or after the service response altogether?

Ideally what I think this would look like would be scheduling a concurrent task inside of the predict_raw method which then is sidelined to the main request handling, and is then wrapped up by seldon-core after a response is sent so that there is more support for long-running operations (such as logging) that shouldn't need to slow down the service responses.

The info we are trying to log is not in the request/response, so I don't think we can log with a sidecar or seldon's logging mechanisms. I am open to alternative approaches if anyone has any suggestions on handling this another way?

**Comment by cliveseldon** [comment]
As discussed in slack even the Flask option might not solve your issue if a new request is being handled. A shared memory solution with a sidecar might be best if its a priority given I/O is a bottleneck.
Maybe more testing and details are required as not sure how we can create a general solution for users here.

**Comment by cliveseldon** [comment]
@flpymonkey Can you open an issue on [MLServer](https://github.com/SeldonIO/mlserver) if this is still an issue as that is longer term solution for custom models along with [Tempo](https://github.com/SeldonIO/tempo) which you might want to investigate
