### ISSUE TITLE
Custom explainability models

### ISSUE THREAD

**Issue by Atharex** [SeldonIO/seldon-core#1832]
Hi!

Is it possible to create a custom explainability model and serve it under the /explain endpoint, like in the imagenet prepackaged explainer example?

https://github.com/SeldonIO/seldon-core/blob/master/notebooks/resources/imagenet_explainer_grpc.yaml#L47

**Comment by cliveseldon** [comment]
Yes the explainer struct takes a container spec:
https://github.com/SeldonIO/seldon-core/blob/79cfcd059caaf89e0f69a43d18499dff06f85ab1/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L255-L263

**Comment by Atharex** [comment]
And the explainer container works similarly like the main model wrapper?

A MyModel.py file with a MyModel class and a predict method for the functionality?
Or is there a specific explain method?

**Comment by cliveseldon** [comment]
We share the explainer wrapper code with kfserving with a few additions to allow grpc calling of the underlying model. So there is a specific explain endpoint:
https://github.com/SeldonIO/kfserving/blob/aadb2f2bb8f52ea729ad04dcfa28ea800ffd343a/python/kfserving/kfserving/kfserver.py#L65-L71

We haven't documented this in detail yet. Be good to understand your use case.

**Comment by Atharex** [comment]
Having this documented would be great! Maybe it already supports everything I'd like

For my use-case I was thinking to combine a LIME explainer along with the model in the main wrapper, and then have explanations independently served under the /explain endpoint like in the example below:

```
class Model(object):


    def __init__(self):
        self.model = load_model()

    def predict(self, X, feature_names):
        prediction = self.model.predict(X)
        return prediction

    def explain(self, X, feature_names):
        explainer = lime_image.LimeImageExplainer()
        segmenter = SegmentationAlgorithm(...)
        explanation = explainer.explain_instance(X, self.model.predict)
        return explanation.get_image_and_mask(X)
```

So querying /predict of this wrapper would return something like:
```
{
  result: Y,
  confidence: xy.z% 
}
```

and querying /explain of this wrapper with the same data would return something like:
```
{
  result: Y,
  confidence. xy.z%,
  mask: [...],
  any_other_custom_explanations: [...],
}
```

**Comment by Atharex** [comment]
Need to clarify this use-case a bit more...

This example represents a case I'd want to reuse my model serving to execute also explainability in parallel to the main inference workload (for the sake of testing). Such a scenario would enable  sharing resources from the same container, by using the existing model and an interpretability library on top of it. The up-side of this approach would be ease-of-use, the down side of course increased load on a single container and not the most optimal for production. 

Another case is then to run an explainability model in a separate container (your case with kfserving). Unfortunately I'm not that familiar with kfserving, so I'd love to see some documentation on how you guys did it! Also the example queries from above are something I'd like to get returned in both use cases.

I'm currently using LIME for interpretability, hence why I'd like to serve up my own custom explain endpoint, but also plan on looking into Alibi in the future when I get some time between projects.

**Comment by cliveseldon** [comment]
Can you investigate [Tempo](https://github.com/SeldonIO/tempo)?
