### ISSUE TITLE
Update to latest version of KFServing Storage Initialiser

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1845]
Currently we're using version 2.2 of the kfserving init storage initialiser. We would require version 0.3.1 to use the latest. THis would contain several fixes when env variables are not provided. It would be good to confirm there are no other breaking changes before adding.

**Comment by axsaucedo** [comment]
Would be good to make sure this is updated when https://github.com/kubeflow/kfserving/pull/832 is fixed as that's the main reason to upgrade.

**Comment by adriangonz** [comment]
@axsaucedo can this one be closed?

**Comment by cliveseldon** [comment]
KFServing initializer is deprecated.
