### ISSUE TITLE
Deprecate USE_SSL for S3_USE_HTTPS

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1847]
The `Storage.py` layer is shared across the KFServing and the Seldon Core projects (maintained by KFServing). However, there are some discrepancies for historic reasons. In particular, the flag used to enable SSL in AWS is called `USE_SSL` in SC and `S3_USE_HTTPS` in KFServing.

You can see the original PRs which added both on each project here:

- `USE_SSL` in SC: https://github.com/SeldonIO/seldon-core/pull/827
- `S3_USE_HTTPS` in KFServing: https://github.com/kubeflow/kfserving/pull/362

It would be good to deprecate the `USE_SSL` flag in SC and ask people to use `S3_USE_HTTPS` instead, so that we are aligned with the KFServing project.

## Update

Since the `Storage.py` layer is not in the `seldon_core` package anymore, we don't need to change any code. Instead, this is issue is just a matter of updating the docs to reflect the above.

**Comment by cliveseldon** [comment]
KfServing storage initializer is deprecated.
