### ISSUE TITLE
Add documentation that explains how to configure the named port

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1853]
Add documentation that explains how to configure the custom named port functionality as per https://github.com/SeldonIO/seldon-core/pull/1806/files

**Comment by cliveseldon** [comment]
@xaniasd Can you look at this?

**Comment by xaniasd** [comment]
sure thing!

**Comment by axsaucedo** [comment]
This was addressed by @xaniasd
