### ISSUE TITLE
Routers not working with new Executor

### ISSUE THREAD

**Issue by neopobo** [SeldonIO/seldon-core#1876]
Hi,

When using seldon 1.1 with new executor, router always return first children from its inference graph.

The problem is that when using python or R wrapper the format of message returned is:
{"data":{"ndarray":[[1]]}} 
but new executor expects:
{"data":{"ndarray":[1]}} 
where "1" is a route number.

Old java implementation is working ok with [[1]] ndarray.

I see in the api>rest>client_test.go file that there is wrong okRouteResponse expected.

My local build of the Executor works when changing in api>utill>utils.go func ExtractRouteFromSeldonMessage

Line 13: routeArr[i] = int(value.GetListValue().GetValues()[0].GetNumberValue())

**Comment by cliveseldon** [comment]
Thanks. Can we extend it to allow both for now. A small PR for this would be great?

**Comment by neopobo** [comment]
I have created PR #1890, 
Sorry do not know how to connect it with the issue
