### ISSUE TITLE
seldon-webhook-server-cert secret is not getting deleted 

### ISSUE THREAD

**Issue by Pallavi-28** [SeldonIO/seldon-core#1877]
I am trying to do kubeflow uninstall , even after successful uninstallation , secret 'seldon-webhook-server-cert' is not getting deleted .
However , the certificate 'seldon-serving-cert' is deleted .
I can also see in the deletion log which is stating 'seldon-webhook-server-cert secret is deleted but actually it exists:

customresourcedefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" deleted
mutatingwebhookconfiguration.admissionregistration.k8s.io "seldon-mutating-webhook-configuration-kubeflow" deleted
serviceaccount "seldon-manager" deleted
role.rbac.authorization.k8s.io "seldon-leader-election-role" deleted
role.rbac.authorization.k8s.io "seldon-manager-cm-role" deleted
clusterrole.rbac.authorization.k8s.io "seldon-manager-role-kubeflow" deleted
clusterrole.rbac.authorization.k8s.io "seldon-manager-sas-role-kubeflow" deleted
rolebinding.rbac.authorization.k8s.io "seldon-leader-election-rolebinding" deleted
rolebinding.rbac.authorization.k8s.io "seldon-manager-cm-rolebinding" deleted
clusterrolebinding.rbac.authorization.k8s.io "seldon-manager-rolebinding-kubeflow" deleted
clusterrolebinding.rbac.authorization.k8s.io "seldon-manager-sas-rolebinding-kubeflow" deleted
configmap "seldon-config" deleted
**secret "seldon-webhook-server-cert" deleted**
service "seldon-webhook-service" deleted
deployment.apps "seldon-controller-manager" deleted
certificate.cert-manager.io "seldon-serving-cert" deleted
issuer.cert-manager.io "seldon-selfsigned-issuer" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "seldon-validating-webhook-configuration-kubeflow" deleted
 
While debugging the issue I found out that secret 'seldon-webhook-server-cert' should have owner reference of certificate , so that when certificate is deleted , secret associated with that should also deleted.

#kubectl get certificate  -n kubeflow
NAME                  READY   SECRET                       AGE
seldon-serving-cert   True    seldon-webhook-server-cert   9m49s

After doing kubeflow deletion ,

#kubectl get certificate  -n kubeflow
No resources found in kubeflow namespace.

#kubectl get secret   -n kubeflow
NAME                         TYPE                                  DATA   AGE
seldon-webhook-server-cert   kubernetes.io/tls                     3      4m55s
webhook-certs                Opaque                                2      16m

Can anyone please suggest how to delete these secrets?

**Comment by ryandawsonuk** [comment]
Well I guess you could delete manually. 

There's [no manifest for that secret in the kubeflow manifests](https://github.com/kubeflow/manifests/search?q=seldon-webhook-server-cert&unscoped_q=seldon-webhook-server-cert). Looks like it is created by cert-manager. Would make sense for kubeflow to enable the cert-manager flag to have it turn on the owner refs - https://github.com/jetstack/cert-manager/issues/1944

**Comment by axsaucedo** [comment]
It seems this is an actual issue, linked to #2101

**Comment by cliveseldon** [comment]
Can you reopen if still an issue
