### ISSUE TITLE
Document Mistake about Endpoint Testing

### ISSUE THREAD

**Issue by George0112** [SeldonIO/seldon-core#1881]
In [this](https://github.com/SeldonIO/seldon-core/blob/v1.1.0/doc/source/workflow/serving.md) document, I can't use the curl command to test the endpoint. Eventually, I found out that the command should be 
```
curl -g http://localhost:5000/predict --data-urlencode 'json={"data": {"names": ["sepal_length", "sepal_width", "petal_length", "petal_width"], "ndarray": [[7.233, 4.652, 7.39, 0.324]]}}'
```
instead of  
```
> curl -X POST \
>     -H 'Content-Type: application/json' \
>     -d '{"data": { "ndarray": [[1,2,3,4]]}}' \
>         http://localhost:5000/api/v1.0/predictions
```
written in the document

**Comment by cliveseldon** [comment]
I the correct would be content-type JSON. Maybe you are using an old version of Seldon Core. JSON is valid for 1.1. Will close this. Please reopen if there is an issue in 1.1.0 version of docs and code.
