### ISSUE TITLE
Metrics notebook broken (gRPC)

### ISSUE THREAD

**Issue by glindsell** [SeldonIO/seldon-core#1886]
https://github.com/SeldonIO/seldon-core/blob/master/examples/models/metrics/metrics.ipynb

... is broken.

Due to https://github.com/SeldonIO/seldon-core/pull/1772 which introduced gRPC/HTTP multiplexing on the Executor. These changes mean that the Executor is created by the operator on port 8000 OR 5001 and all traffic (gRPC and HTTP) goes through one of those ports.

The executor used to be running on ports 8000 AND 5001. Thus the metrics example notebook looks for metrics on port 8000 in the gRPC example - when they are in fact running on port 5001.

This can be fixed by bringing the operator in line with the executor in regard to multiplexing.

Please see #1628

**Comment by RafalSkolasinski** [comment]
I believe that having executor always serve traffic in same port, like always `8000`, will pay off in a long run by removing ambiguity and confusion.

Whatever we choose we need to make sure that ambassador / istio are directing traffic to the right ports.
