### ISSUE TITLE
Deprecate annotations in the spec section

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1895]
Some of the annotations in `SeldonDeployment` resources (e.g. [Istio flags](https://docs.seldon.io/projects/seldon-core/en/latest/ingress/istio.html#istio-configuration-annotation-reference) currently go under `spec.annotations`. However, given that these are global, we could also place them directly under `metadata.annotations`.

The main (and only?) benefit of the latter is that it's a bit more standard.

**Comment by cliveseldon** [comment]
Will close now as we probably will not deprecate parts of v1 sdep CRD
