### ISSUE TITLE
How seldon custom metrics work? Can it be seen on grafana?

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#1898]
Hi,
Custom metrics seems to be little confusing. Could someone help me out how it works and what is the purpose for it.
I have included the metrics function in my model.py file
![image](https://user-images.githubusercontent.com/57779683/83283056-2529ea80-a20d-11ea-8fa1-780d25370e88.png)

Under grafana, I get this graph
![image](https://user-images.githubusercontent.com/57779683/83283158-54d8f280-a20d-11ea-9618-89aaa95457b7.png)

how does the custom metrics reflect?What does it mean?

**Comment by RafalSkolasinski** [comment]
Interpretation of each `type` is as follows
- COUNTER : a monotonically increasing value. It will be added to any existing value from the metric key.
- GAUGE : an absolute value showing a level, it will overwrite any existing value.
- TIMER : a time value (in msecs), it will be aggregated into Prometheus’ HISTOGRAM.

These are the prometheus types of metrics.

Custom metrics allow you to specify any of these under your custom name and give it any meaning you would to. Custom metrics in your model will be updated on any call to `predict`. `transform`, etc endpoints. 

You can use this feature to keep track of some custom counters, gauges or timers.

**Comment by divyadilip91** [comment]
Could you explain with an example for my above code? How do the values change for gauge?Will it be replaced everytime we make a call to metric?
Will these metrics be updated for every call to the lower level methods like predict_raw or transform_input_raw etc? Moreover how do we showcase these custom metrics on grafana?

**Comment by RafalSkolasinski** [comment]
- counter: increased on every call -> mycounter will be getting values 1, 2, 3, 4, ...
- gauge: set to given value on every call -> mygauge will be always set to 100
- timer: added to histogram on every call -> mytimer will always add value 20.2 to histogram -> in real life you want to have different number here

For the `_raw` methods you need to include metrics in the response on your own.
You can use test case as example how to do it:
https://github.com/SeldonIO/seldon-core/blob/2704bc1bae499f0343b37ec8eef8141d29513814/python/tests/test_metrics.py#L193-L211

I don't think we add custom metrics to grafana by default so this would require some work from your side. @cliveseldon or @ryandawsonuk may know more about it.

**Comment by divyadilip91** [comment]
Thankyou @RafalSkolasinski for explaining in detail. I initially thought that, the seldon dashboard has been designed such a way that whatever seldon metrics get scraped by Prometheus would be reflected under grafana.
