### ISSUE TITLE
Multipart form data not passed between chain of seldon components

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#1899]
Hi,
I just found that form data is not passed from one seldon component to another. I have tried passing normal data of content-type "application/json" between components and it works fine,but form data doesnt seem to be transfered between seldon components.

I have two programs,one  has input transformer and the other has model component. I have used transform_input_raw and predict_raw methods. I pass an audio file input with keyword "binData" . I am able to process the input in transformer and the input passed can be seen in logs...The transformer returns a dictionary containing the binary data which is to be received as input by the predict method in model.py file.But the model receives an empty dictionary and throws a key error.
PFA the method used in 2 program screenshots

![image](https://user-images.githubusercontent.com/57779683/83284202-fe6cb380-a20e-11ea-9c24-9a92f8eefc5a.png)

![image](https://user-images.githubusercontent.com/57779683/83284576-6a4f1c00-a20f-11ea-996f-3aabc79ab36b.png)

Someone please do look into this and do reply

**Comment by cliveseldon** [comment]
Which version of Seldon Core are you running?

**Comment by cliveseldon** [comment]
The content-type from the first response should be json so it should work when its passed to the second. The only reason would be if that was not the case its being kept as form-urlencoded for some reason.

**Comment by divyadilip91** [comment]
> Which version of Seldon Core are you running?

I am running seldon version 1.1.0

**Comment by divyadilip91** [comment]
> The content-type from the first response should be json so it should work when its passed to the second. The only reason would be if that was not the case its being kept as form-urlencoded for some reason.

Yes..since transform_input_raw returns a json , I ensured that the type of data returned is a dictionary..but model program with predict_raw method is not receiving the input..it received an empty dictionary

**Comment by cliveseldon** [comment]
can you set DEBUG on your components: https://docs.seldon.io/projects/seldon-core/en/latest/analytics/log_level.html?highlight=SELDON_LOG_LEVEL#setting-log-level-in-a-python-wrapper

I also suggest testing locally.

**Comment by divyadilip91** [comment]
> can you set DEBUG on your components: https://docs.seldon.io/projects/seldon-core/en/latest/analytics/log_level.html?highlight=SELDON_LOG_LEVEL#setting-log-level-in-a-python-wrapper
> 
> I also suggest testing locally.

Ok sure. I would try this and let you know.

**Comment by divyadilip91** [comment]
Hi Clive,
I tried debugging by setting the log level for each container .PFA the screenshots
Logs of transformer 
![image](https://user-images.githubusercontent.com/57779683/83323835-e1c68f00-a293-11ea-8cf2-34200e2c8a16.png)

![image](https://user-images.githubusercontent.com/57779683/83323838-eb4ff700-a293-11ea-900e-497f8b113c88.png)

![image](https://user-images.githubusercontent.com/57779683/83323859-120e2d80-a294-11ea-87c4-bea35febf0ad.png)

Logs of model
![image](https://user-images.githubusercontent.com/57779683/83323876-2520fd80-a294-11ea-8972-d2d98b5b8794.png)

![image](https://user-images.githubusercontent.com/57779683/83323887-2e11cf00-a294-11ea-8fd6-0ad6d0899d48.png)

As you can see that transformer has the response in proper json format...but the output doesnt reach the model. The model receives an empty dictionary.

**Comment by cliveseldon** [comment]
There does seem to be an issue that the content-type is being kept as multipart for all calls in the graph. Its a bug in how headers are handled.
