### ISSUE TITLE
/metrics endpoint to return a json file

### ISSUE THREAD

**Issue by Deunitato-sentient** [SeldonIO/seldon-core#1905]
Possibly to return a json file of the metrics when calling /metrics endpoint\

Reference to #1898 #1901

**Comment by RafalSkolasinski** [comment]
We could maybe have raw metrics (json) under `/metrics` and prometheus compatible form under `/prometheus`. 

Question: for returned json - do you think about raw output of `metrics` method or processed information same as one exposed for prometheus - just in json format?

**Comment by cliveseldon** [comment]
the `/metrics` is particular to prometheus. We could have a separate endpoint, e.g. `/statistics` for formatted metrics from the server. No plans at present for this.
