### ISSUE TITLE
Empty json parameter in data

### ISSUE THREAD

**Issue by booboothefool** [SeldonIO/seldon-core#1912]
When trying to follow the tutorial here: https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/iris.html

I am getting the following error:
```
curl  -s http://localhost:5000/predict -H "Content-Type: application/json" -d '{"data":{"ndarray":[[5.964,4.006,2.081,1.031]]}}'
{
  "status": {
    "code": -1, 
    "info": "Empty json parameter in data", 
    "reason": "MICROSERVICE_BAD_DATA", 
    "status": 1
  }
}
```

**Comment by booboothefool** [comment]
In addition, for this tutorial: https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/sklearn_spacy_text_classifier_example.html

I was getting errors with `dill==0.2.9` and could not make successful requests. I had to upgrade to `dill==0.3.1.1` for it to properly build.

**Comment by RafalSkolasinski** [comment]
Thanks @booboothefool, I will look into these issues. Will let you know if I need any more input.

With the `s2i` builds you can have a `requirements.txt` file and during the build process it will update the packages accordingly to it.

**Comment by booboothefool** [comment]
```
Building wheels for collected packages: en-core-web-sm
  Building wheel for en-core-web-sm (setup.py): started
  Building wheel for en-core-web-sm (setup.py): finished with status 'done'
  Created wheel for en-core-web-sm: filename=en_core_web_sm-2.2.5-cp37-none-any.whl size=12011740 sha256=5b1d3cfb3fa63096a5172fd8baa457f1d20c843f5d6061f885ea3e5b83c605a6
  Stored in directory: /tmp/pip-ephem-wheel-cache-aoo7lj83/wheels/6a/47/fb/6b5a0b8906d8e8779246c67d4658fd8a544d4a03a75520197a
Successfully built en-core-web-sm
Installing collected packages: en-core-web-sm
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/conda/lib/python3.7/site-packages/en_core_web_sm'
Consider using the `--user` option or check the permissions.
```

I was able to get past that by in `ml_utils.py` commenting `# download("en_core_web_sm")` then just adding the folder locally from https://github.com/explosion/spacy-models/releases//tag/en_core_web_sm-2.2.5.

I also feel like this might've worked (relying on `requirements.txt` instead of `download()`:
```
scipy>= 1.4.1
scikit-learn>=0.22.2.post1
spacy==2.2.4
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz#en_core_web_sm
dill==0.3.1.1
seldon-core==1.1.0
```

**Comment by RafalSkolasinski** [comment]
That's scarry. `Permission denied` error is definitely something does should not happen and probably deserves a separate issue. 

Let's keep this one for fixing the two notebooks you mentioned.

**Comment by RafalSkolasinski** [comment]
The iris example, https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/iris.html, works without issues on master. As we are close to release 1.2 it shall not be an issue.

**Comment by RafalSkolasinski** [comment]
I addressed problems in the spacy example.

The `Permission denied` issue was related to the fact that current implementation was downloading spacy language models on the container start up. Since recently containers run as non-root user this was causing problems.

A related PR fixes it by baking that into the image.
