### ISSUE TITLE
Seldon-core-microservice-tester command available for ambassador endpoint

### ISSUE THREAD

**Issue by Deunitato-sentient** [SeldonIO/seldon-core#1914]
I came across this [document](https://docs.seldon.io/projects/seldon-core/en/v0.3.0/workflow/api-testing.html) that mentions about the use of seldon-core-microservice-tester to do API testing.

Starting the docker:
`docker run --name "my_model" -d --rm -p 5000:5000 myimage:0.1` t

Running in shell:
 `seldon-core-api-tester contract.json  0.0.0.0 5000 ` 

Output:
```
----------------------------------------
SENDING NEW REQUEST:

[[4.27  3.509 3.344 1.981]]
RECEIVED RESPONSE:
meta {
}
data {
  names: "t:0"
  names: "t:1"
  names: "t:2"
  ndarray {
    values {
      list_value {
        values {
          number_value: 0.17256721070006628
        }
        values {
          number_value: 0.05667986765804383
        }
        values {
          number_value: 0.7707529216418899
        }
      }
    }
  }
}

```

However, when doing it with the ambassador, I tried

1. 
`seldon-core-microservice-tester contract.json <AMBASSADOR IP ADDRESS>/<DEPLOYMENT-PREFIX>/api/v1.0/predictions 80 -p`

Output:
```
SENDING NEW REQUEST:

[[5.1   4.591 2.159 2.897]]
RECEIVED RESPONSE:
None
```

2. 
`seldon-core-microservice-tester contract.json <AMBASSADOR IP ADDRESS>/<DEPLOYMENT-PREFIX> 80 -p`

Output:
```
----------------------------------------
SENDING NEW REQUEST:

[[6.963 2.35  1.763 1.369]]
RECEIVED RESPONSE:
None
```

3.` seldon-core-microservice-tester contract.json <AMBASSADOR IP ADDRESS> 80 -p`

Output:

```
----------------------------------------
SENDING NEW REQUEST:

[[4.348 4.431 4.943 1.057]]
RECEIVED RESPONSE:
None
```

Am I doing something wrong or using the wrong format? Why is the response not printing?
I am deploying this container on Kubernetes and the log file does not show anything regarding the request (Perhaps it is not able to connect?)

**Comment by cliveseldon** [comment]
Its probably simplest to follow the steps in https://docs.seldon.io/projects/seldon-core/en/v1.1.0/workflow/serving.html and use curl

For the external API ingress you need to use `seldon-core-tester` but as said curl is probably just as easy.
