### ISSUE TITLE
Allow globally configurable docker registry secret for seldon deployments

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1923]
Currently if seldon is installed in a cluster that needs ot run models with images from a private docker registry that needs credentials, it's necessary to add the existing containerSpec secrets for each deployment. The scope of this issue encompasses the ability to define a set of secrets that should be added by default to all the Seldon Core deployments such that it's used to authenticate with a docker registry.

**Comment by ryandawsonuk** [comment]
Might be able to leverage https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#verify-imagepullsecrets-was-added-to-pod-spec

**Comment by axsaucedo** [comment]
THis shoudl no longer be required as this can be done by just adding the secret to the service account and attach the service account as per https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-image-pull-secret-to-service-account
