### ISSUE TITLE
How to access rolling accuracy metrics?

### ISSUE THREAD

**Issue by booboothefool** [SeldonIO/seldon-core#1926]
According to this page: https://docs.seldon.io/projects/seldon-core/en/v1.1.0/analytics/analytics.html#custom-metrics

>Seldon Core exposes basic metrics via Prometheus endpoints on its service orchestrator that include request count, request time percentiles and **rolling accuracy** for each running model as described in metrics documentation.

I was able to view my metrics in Prometheus:
```
kubectl port-forward svc/classifier-example 8000:8000
curl -s localhost:8000/prometheus
```

However I only see:
>seldon_api_executor_server_requests_seconds_(bucket,count,sum) : Requests to the service orchestrator from an ingress, e.g. API gateway or Ambassador

>seldon_api_executor_client_requests_seconds_(bucket,count,sum) : Requests from the service orchestrator to a component, e.g., a model

Where can I see more metrics such as "rolling accuracy"? Also, I am on OpenShift and using the Seldon Core Operator https://catalog.redhat.com/software/operators/detail/5e9f1a3769aea31642b613f4. Is there a way I can view the Grafana dashboard using this operator instead of the seldon-analytics Helm chart, or do I have to point my own Prometheus/Grafana at it?

**Comment by cliveseldon** [comment]
Port 8000 would be for the executor (service orchestrator) which collects the basic metrics you mention. The custom metrics will be exposed on the models themselves, so the "metrics" port of you model.

**Comment by booboothefool** [comment]
@cliveseldon Is "rolling accuracy" an executor (service orchestrator) basic metric or is it a custom metric? The description makes it seem like it should be there by default. 

When attempting:
```
kubectl port-forward classifier-example-0-classifier-xxx-xxx 6000:6000
curl -s localhost:6000/prometheus
```

I get a blank response. I have not defined any custom metrics. Is "rolling accuracy" a custom metric?

**Comment by cliveseldon** [comment]
"rolling accuracy" is not any metric name we create. As said custom metrics need to be defined by the user and are exposed as described in https://docs.seldon.io/projects/seldon-core/en/v1.1.0/analytics/analytics.html#metrics-endpoints
