### ISSUE TITLE
ambassador helm chart deprecation warnings

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1928]
Since around last week `ambassador` installation renders following warning.
```
DEPRECATED!! This version of the chart has been deprecated.
```
We should verify if this requires any action from our side or is purely upstream issue.

**Comment by cliveseldon** [comment]
Here are the details
https://github.com/datawire/ambassador-docs/blob/master/user-guide/install-ambassador-oss.md#2-install-ambassador-api-gateway

**Comment by RafalSkolasinski** [comment]
Seems that the new instruction should be something along these lines
```
kubectl create namespace ambassador || echo "namespace ambassador exists"
helm repo add datawire https://www.getambassador.io
helm install ambassador datawire/ambassador \
	--set image.repository=quay.io/datawire/ambassador \
	--set enableAES=false \
	--set crds.keep=false \
	--namespace ambassador
```

There is also option to set image tag `--set image.tag=$version$` but not sure which version we should choose.

The `--set crds.keep=false ` is a flag we had previously, guess we should stil lleave it?
