### ISSUE TITLE
Format of the data sent as a request to the seldon REST api?

### ISSUE THREAD

**Issue by bhanu-sd** [SeldonIO/seldon-core#193]
what is the format of the data we send as a request to the seldon-core created REST api ?

I am trying to test the api created through seldon and want to send a request to the running docker image but am not able to find the proper format in which the data is sent to be as a request to the exposed link in the docs.

**Comment by cliveseldon** [comment]
Please look at the [proto buffer definitions](https://github.com/SeldonIO/seldon-core/blob/master/proto/prediction.proto) or the [OpenAPI definitions](https://github.com/SeldonIO/seldon-core/tree/master/openapi)
