### ISSUE TITLE
Explore the scope and methods where SSL can be supported in Seldon Core

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1931]
There has been discussions for Seldon Core to support SSL for data in transport. This has currently been achieved so far through our integrations with ingress (namely Istio and Ambassador), where SSL is enabled at the ingress level. 

This issue will explore whether further support for SSL is required in the seldon core endpoint(s) themselves, as well as the options available (as there will be a level of complexity on how certificates would be provided and managed).

This currently can also be achieved using service mesh frameworks such as istio to ensure service to service encryption [through side-car injection](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/)

It would be useful to underrstand from the community how currently they handle SSL within clusters, especially whether they use a cluster-wide service mesh provider to handle SSL, or whether it's expected for every single application to have functionality to support adding custom certificates. If the latter, it would be useful to understand as well how certificates are currently provided to applications, whether compoennts like cert-manager are used, or whether these are provided manually.

**Comment by hmonteiro** [comment]
Definitely +1 for intra cluster communications encryption. In this day and age, encrypting all network transport is essential.

**Comment by axsaucedo** [comment]
Thank you @hmonteiro - I completely agree, we're currently exploring what is the way people are currently achieving this. We have seen that some organisations are moving towards using service mesh providers such as Istio to achieve this through side-car injection. Have you explored this, or is this something you expect to be handled on an application basis - if the latter, how do you currently handle the provisioning of certificates?

I've updated the description to reflect the question - thank you @hmonteiro would be keen to get more insights.

**Comment by josephglanville** [comment]
I think internal and external TLS should get their own issues as both have different concerns. Namely internal TLS is generally the  simpler of the two, you don't need to worry about concerns about SNI or mTLS authentication etc.

The other thing I think should be highlighted is that reliance on a service mesh either for internal TLS or external TLS would be a deal breaker for many (our team included). A lot of what makes Seldon attractive over some of the other options available is that it's relatively unopinionated and has a nice understandable architecture and request routing flow. Not saying the service meshes shouldn't be a supported option, they certainly should be but I would be cautious about gating important functionality behind a large and devisive dependency.

**Comment by axsaucedo** [comment]
@ahutterTA @lennon310 @phsiao I remember we discussed briefly this point, we have now an open PR which is exploring the addition of SSL on Seldon Core, initially primarily through the executor and provided via a Secret (provisioned manually through Certmanager), but with the idea of extending it to graph-level and potentially managed certmanager Certificate resource creation. The PR has more insights on the current work and exploration, it woudl be great to hear your thoughts

**Comment by cliveseldon** [comment]
Closing - please reopen if still and issue and we can investigate for v2 APIs
