### ISSUE TITLE
"Empty Json Parameter in data" for model components in Spam Classifier Example

### ISSUE THREAD

**Issue by ntorba** [SeldonIO/seldon-core#1938]
Hi!

I am having some trouble with the [spam classifier example](https://github.com/SeldonIO/seldon-core/tree/5150973e2230de02934fff8930b24ba652dd494b/examples/combiners/spam_clf_combiner). I run `kubectl apply -f deploy.yaml` using the deployment file [here](https://github.com/SeldonIO/seldon-core/blob/5150973e2230de02934fff8930b24ba652dd494b/examples/combiners/spam_clf_combiner/deploy.yaml). 

After the deployment is ready, I make a request to my endpoint with the following code: 
```python
jsonData = {
    "data": {
        "names": ["message"],
        "ndarray": ["Me llamo Nick"]
    }
}
endpoint_url = "https://fake.com/api/v1/namespaces/protected/services/http:seldon-spam-classifier-seldon-combiner:8000/proxy/api/v0.1/predictions"
response = requests.post(endpoint_url, data={"json": json.dumps(jsonData)}, verify=False)
d = json.loads(response.text)
```
to which the output is: 
```python
{'data': {'names': ['message'], 'ndarray': ['My name is Nick']}, 'meta': {}}
```
Although this shows the translator is working, the expected output is a numeric score.  
The logs for the two models components (keras-spam-classifier and sklearn spam-classifer) show the same error for each request I make:
```python
2020-06-11 21:05:10,505 - werkzeug:_log:122 - INFO:   * Running on http://0.0.0.0:9002/ (Press CTRL+C to quit)
2020-06-11 21:12:14,836 - seldon_core.wrapper:handle_invalid_usage:25 - ERROR:  {'status': {'status': 1, 'info': 'Empty json parameter in data', 'code': -1, 'reason': 'MICROSERVICE_BAD_DATA'}}
2020-06-11 21:12:14,837 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [11/Jun/2020 21:12:14] "POST /predict HTTP/1.1" 400 -
2020-06-11 21:23:43,667 - seldon_core.wrapper:handle_invalid_usage:25 - ERROR:  {'status': {'status': 1, 'info': 'Empty json parameter in data', 'code': -1, 'reason': 'MICROSERVICE_BAD_DATA'}}
2020-06-11 21:23:43,667 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [11/Jun/2020 21:23:43] "POST /predict HTTP/1.1" 400 -
2020-06-11 21:25:39,908 - seldon_core.wrapper:handle_invalid_usage:25 - ERROR:  {'status': {'status': 1, 'info': 'Empty json parameter in data', 'code': -1, 'reason': 'MICROSERVICE_BAD_DATA'}}
2020-06-11 21:25:39,908 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [11/Jun/2020 21:25:39] "POST /predict HTTP/1.1" 400 -
```

I am unsure how to reconcile this issue. It seems that the request sent from the transformer to the models is not what the models are expecting. 

Also, is there a field I can set to throw an error when any of the component of the graph fails? I would prefer this for testing purposes.  

Any help is greatly appreciated!

**Comment by cliveseldon** [comment]
This looks like the example python code needs to be updated to latest wrapper @axsaucedo @RafalSkolasinski ?

**Comment by RafalSkolasinski** [comment]
Yes, most likely that is the issue. 
Seen something similar reported by https://github.com/SeldonIO/seldon-core/issues/1912.

There when I checked on master it was working fine with the latest wrapper indeed. I will take a look into this one to.

**Comment by RafalSkolasinski** [comment]
@gosandhya I can see that this example was contributed from you, would you mind taking a look on what may be going wrong?

I am afraid it may also be missing input data file `spam.csv` or code that would fetch it from some remote origin.

@ntorba In the meantime there is another combiner example you may be interested in checking: https://github.com/SeldonIO/seldon-core/blob/master/examples/outliers/alibi-detect-combiner/notebook.ipynb

**Comment by ntorba** [comment]
Thanks for pointing me to that other example @RafalSkolasinski. That example works great! Unfortunately, still haven't gotten this one working yet. As an update, I took out the translator component from this example, then sent the following request:
```python
jsonData = {
    "data": {
        "names": ["text"],
        "ndarray": ["I am Nick"]
    }
}

response = requests.post(test_url, data={"json": json.dumps(jsonData)}, verify=False)
# response = requests.post(test_url, data=json.dumps(jsonData), verify=False)
# d = json.loads(response.text)
response.text
```
To which the response is: 
```python
'json=%7B%22data%22%3A+%7B%22names%22%3A+%5B%22text%22%5D%2C+%22ndarray%22%3A+%5B%22I+am+Nick%22%5D%7D%7D'
```
Looking at the container logs, I see that both the models are showing `200` response for each request, but then the combiner shows the same error as before 
```python
2020-06-15 22:37:05,600 - seldon_core.wrapper:handle_invalid_usage:25 - ERROR:  {'status': {'status': 1, 'info': 'Empty json parameter in data', 'code': -1, 'reason': 'MICROSERVICE_BAD_DATA'}}
2020-06-15 22:37:05,601 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [15/Jun/2020 22:37:05] "POST /aggregate HTTP/1.1" 400 -
```

**Comment by RafalSkolasinski** [comment]
Could you try to send your request as
```python
response = requests.post(test_url, json=jsonData)
```
?

**Comment by ntorba** [comment]
Using 
```python
response = requests.post(test_url, json=jsonData)
```
I receive 
```python
2020-06-16 12:07:58,777 - seldon_core.wrapper:handle_invalid_usage:25 - ERROR:  {'status': {'status': 1, 'info': 'Empty json parameter in data', 'code': -1, 'reason': 'MICROSERVICE_BAD_DATA'}}
2020-06-16 12:07:58,778 - werkzeug:_log:122 - INFO:  127.0.0.1 - - [16/Jun/2020 12:07:58] "POST /predict HTTP/1.1" 400 -
```
from both of the model endpoints

**Comment by RafalSkolasinski** [comment]
Hmm... Did you try to update the s2i build using latest wrapper? Are you loading into the cluster the image you built? The `yaml` manifest in this tutorial was referring to images on contributor's of this example docker hub.

Would suggest to check following:
- what version of seldon-core operator are you running in your cluster
- what version of executor are your deployment using (configured through helm installation but basically depends on seldon-core operator installed)
- what image are the models running, especially hopeful may be to just build them fresh using latest s2i wrapper and make sure your local build is used in your cluster.

Are you using `kind`?

**Comment by ntorba** [comment]
Hey @RafalSkolasinski. Sorry for the long wait to reply. What command can I use to check the version of seldon-core-operator? 

I initially tried running this on an EKS cluster with the pre-built images. Do you know where I can find the `spam.csv` file used to train models so I can try building the images from scratch?

**Comment by cliveseldon** [comment]
We will remove this as the example is broken/missing files.

**Comment by gosandhya** [comment]
Apologies for the delayed response. 

Yes, the example assumes that you have CSV file locally and here is the public spam dataset this example is using: https://www.kaggle.com/uciml/sms-spam-collection-dataset

I can push the code that would fetch spam.csv from remote if you want to keep the example around.
