### ISSUE TITLE
Upgrade k8s client API to 1.18+

### ISSUE THREAD

**Issue by josephglanville** [SeldonIO/seldon-core#1949]
Multiple dependencies will shortly necessitate moving to k8s v1.18+ client libraries. This is a breaking change due to introduction of `context` on most of the API surface for creating resources and such. Istio is the main current feature that will require this upgrade to happen soon however Contour will need it too in order to update to the v1.5.0 client version.

**Comment by cliveseldon** [comment]
Hi @josephglanville We already have #1675 and #1678 
Is this issue referring to further changes required? If so can you specify them?

**Comment by josephglanville** [comment]
These may be related but I don't think address the actual k8s client-go upgrade and associated dependencies. All of these deps need to be updated in lockstep as I did for external-dns here https://github.com/kubernetes-sigs/external-dns/pull/1627
This can be a pain and especially because upgrading Istio attempts to upgrade gRPC past 1.27 which is another breaking change.

**Comment by cliveseldon** [comment]
Ok thanks. Will need to understand how this affects the executor and operator as we would want to support pre 1.18 k8s users given many clients are only on 1.14 at most.

**Comment by josephglanville** [comment]
If I end up being the one to do it I will validate that anyway because our clusters are on v1.15. My understanding is the client is backwards compatible to all 1.X server/cluster versions however so I don't anticipate any issues.

**Comment by cliveseldon** [comment]
Might be solved by https://github.com/SeldonIO/seldon-core/issues/2088

**Comment by RafalSkolasinski** [comment]
In #2088 we initially discussed bumping `k8s.io` deps to `v0.17.8`

**Comment by cliveseldon** [comment]
See https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20200123-client-go-ctx.md
