### ISSUE TITLE
Golang Service Orchestrator (Executor) fails to replace variables since no longer runs root

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#1955]
Currently we have changed such that the container doesn't run as root which brings benefits on security. This causes an error as the golang executor is no longer able to replace the variables on startup on the openapi files. The container runs with user 8888 so currently the solution would be change the owner of the directory to be user with ID 8888.

**Comment by cliveseldon** [comment]
It would be better to make the files globally writable maybe as the RedHat ubi image runs as 1001 user by default and may run as an arbitrary user provided at runtime by openshift.

**Comment by axsaucedo** [comment]
I completely agree, the main problems is that because we've also moved the distroless it's not possible to run the chmod command, so it's not possible to change permissions... the only command available seems to be --chown when using the docker `COPY` command, which is the suggested approach as well in the `distroless` issues, I can try to see if there are other ways to add chmod for files on distroless

**Comment by axsaucedo** [comment]
@cliveseldon ok it seems it was possible to achieve this by changing the chmod on the builder container and copying the files with the broad access permissions. #1956 should have the fix now
