### ISSUE TITLE
Update Payload Logger to use V1 Cloudevents

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#1958]
* Update cloudevents go library
 * Update code to use V1 protocol

**Comment by ryandawsonuk** [comment]
Oh I thought we were already https://github.com/SeldonIO/seldon-core/issues/1857. Maybe I looked in the wrong place. Presumably I should have looked at https://github.com/SeldonIO/seldon-core/blob/master/executor/go.mod#L6

**Comment by cliveseldon** [comment]
Looks like we are using V1 but the library is old. So only need to update library.
