### ISSUE TITLE
From Kubeflow to Seldon Documentation

### ISSUE THREAD

**Issue by nielsgroen** [SeldonIO/seldon-core#1961]
In our current setup, we have Kubeflow Pipelines running. Now I'm wondering, in a sense, how to deploy a TF/SKLearn model to Seldon Core. How can we make sure our model gets automatically picked up by a SeldonDeployment? Taking into account, the deployment of entirely new models, new versions of an existing model, and canarying.

There is plenty of material in the documentation on provisioning a SeldonDeployment by hand. But what if we had a trained model artifact (TF/SKLearn) in the pipeline, which we wanted to get running on a Seldon inference server? 
- Would it be possible to push a new model version (previous versions exist) to a volume, and have existing Seldon pods pick up on it? 
- When provisioning new pods/SeldonDeployments, how can one integrate this properly with Argo?

I did some scavenging on the docs, but couldn't figure it out, or I may have missed something:
- https://docs.seldon.io/projects/seldon-core/en/latest/analytics/kubeflow.html
- https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html

Many thanks in advance!

**Comment by ryandawsonuk** [comment]
There's also https://github.com/SeldonIO/seldon-core/tree/master/examples/kubeflow
and https://github.com/kubeflow/pipelines/tree/master/samples/contrib/seldon

Hopefully they answer some of the questions.

**Comment by nielsgroen** [comment]
Those are already some sources I must have missed. Thanks for the quick reply!
