### ISSUE TITLE
Allow to specify model version for tensorflow serving

### ISSUE THREAD

**Issue by zewelor** [SeldonIO/seldon-core#1964]
Allow to specify model version as shown here https://www.tensorflow.org/tfx/serving/api_rest#predict_api . From looking at the code, currently it doesn't seem possible: https://github.com/SeldonIO/seldon-core/blob/master/integrations/tfserving/TfServingProxy.py#L45

**Comment by cliveseldon** [comment]
If you use 1.1.0 of Seldon you can use the Tensorflow protocol directly. https://docs.seldon.io/projects/seldon-core/en/latest/graph/protocols.html#rest-and-grpc-tensorflow-protocol

Its true we don't expose the version path in REST
https://github.com/SeldonIO/seldon-core/blob/33d66aef2545a5fe2bcadbd264486faf67cb4525/executor/api/rest/server.go#L150

In grpc you should be able to use it at present.

**Comment by zewelor** [comment]
Thanks I will look into it.

**Comment by cliveseldon** [comment]
Will close this assuming using Tensoflow protocol is the best solution as suggested. Please reopen if still an issue.
