### ISSUE TITLE
Ability to return all outputs from tensorflow serving grpc

### ISSUE THREAD

**Issue by zewelor** [SeldonIO/seldon-core#1965]
It would be good to have ability to get all outputs, when tensorflow serving is used in grpc mode. Currently only rest can return all outputs. Grpc: https://github.com/SeldonIO/seldon-core/blob/master/integrations/tfserving/TfServingProxy.py#L76. Maybe make model_output optional, and return whole dict with outputs. When used via REST all outputs are returned now.

**Comment by cliveseldon** [comment]
See responses in #1964

**Comment by cliveseldon** [comment]
I'll close this if using the Tensorflow protocol directly is the best option. Please reopen if that is an issue.
