### ISSUE TITLE
Multiplexing or parallel serving of gRPC / REST in Python Wrapper

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#1968]
Sub-issue for https://github.com/SeldonIO/seldon-core/issues/1628

It would be a good idea to have gRPC / REST always supported by Python wrapper without the need to build / vary image builds.

As initially suggested by @cliveseldon we can achieve that by either multiplexing traffic on one port or having both exposed at once on different port. 

## Option 1 : multiplexing gRPC / REST on one port
![image](https://user-images.githubusercontent.com/10928117/84898071-8faca880-b09e-11ea-8d57-272417aa28ea.png)

In this option Python Wrapper could multiplex in similar fashion as `Executor` does and serve both traffic on single port. We couldn't find though a clean way to do it in Python, especially taking into account that there different technologies involved (flask, gunicorn, grpc) which creates a combination of multithreading / multiprocessing setup.

We should also not forget that even in gRPC mode we still serve `metrics` as pure http endpoint. 

## Option 2 : serve both simultaneously on separate ports 

![image](https://user-images.githubusercontent.com/10928117/84898619-75bf9580-b09f-11ea-8c38-557988dec285.png)

In this option Python wrapper would always expose both interfaces (on different ports). 
This would lead to slightly cleaner implementation. Behaviour may be configurable by environmental variables if required. 

Downside is that we will have to update CRD so that in example
```
- endpoint:
  type: REST
  service_host: 0.0.0.0
  service_port: 9000
```
becomes
```
- endpoint:
  service_host: 0.0.0.0
  service_rest_port: 9000
  service_grpc_port: 9001
```
or similar.

Good that there is already a logic in `operator` that assigns two ports to model, one for service and one for metrics, it would just have to be modified to have one for `rest` and one for `grpc`.

I suggest to go with option 2.

**Comment by chengcheng-pei** [comment]
Personally speaking,
I guess this will make seldon-core more and more complex. 
it is a break change for seldon core and exsiting model deployment resources files, I guess.
Too mush time should be spent to test all of them (executors, prepackaged models, explainers, ..).

it is better to use two containers to serve different endpoints. otherwise, it is complex to debug/maintain/monitor...

**Comment by RafalSkolasinski** [comment]
Updated part of CRD is not meant to be part that user's need to set. 
Actual idea is to make it simpler: right now you need to build model image configured to either REST or gRPC -> if it will multiplex you will only have to build image once. 

On other side it will also become clear that certain port is always GRPC and certain is always REST.

**Comment by RafalSkolasinski** [comment]
However it is indeed a valid point that this - as a joined change to operator, executor, and wrapper - may require update of the wrapper image in user's model.

**Comment by axsaucedo** [comment]
@RafalSkolasinski @cliveseldon can be closed?
