### ISSUE TITLE
re-define noEngine annotation

### ISSUE THREAD

**Issue by chengcheng-pei** [SeldonIO/seldon-core#1976]
this is original codes:
`_, noEngine := p.Annotations[machinelearningv1.ANNOTATION_NO_ENGINE]`

if `machinelearningv1.ANNOTATION_NO_ENGINE` in annotations, `noEngine` is true, otherwise, it is false.

This is confusing. we need check the value of `p.Annotations[machinelearningv1.ANNOTATION_NO_ENGINE]` instead of whether it exists in the annotations map or not.

there is same concern about `_, hasSeparateEnginePod := mlDep.Spec.Annotations[machinelearningv1.ANNOTATION_SEPARATE_ENGINE].`

Please leave comments, so that I can update the pr: https://github.com/SeldonIO/seldon-core/pull/1970

**Comment by cliveseldon** [comment]
I see you have created an initial PR. I will update to WIP and link to this issue. I agree its presently usinging exitence rather than boolean which makes more sense I think.
