### ISSUE TITLE
Custom fields in SeldonMessage

### ISSUE THREAD

**Issue by killwing** [SeldonIO/seldon-core#198]
The structure of SeldonMessage is not sufficient to carry custom parameters, sometimes we need both data and binData/strData.

```
message SeldonMessage {
  Status status = 1;
  Meta meta = 2;
  oneof data_oneof {
    DefaultData data = 3;
    bytes binData = 4;
    string strData = 5;
  }
}
```

Is it possible change to below ?
```
message SeldonMessage {
  Status status = 1;
  Meta meta = 2; 
  DefaultData data = 3;
  bytes binData = 4;
  string strData = 5;  
}
```

**Comment by cliveseldon** [comment]
Certainly something we could consider but it would be a big change as all the API components and wrappers would need changing.

Can you explain your use case so we can understand it better.

Certainly the ability to send data both outside the standard default data and inside it makes sense.

**Comment by killwing** [comment]
Seems that seldon wrappers only support classification ? 
Besides classification, we have more cases like object detection, feature extraction etc. that need some custom params.

**Comment by cliveseldon** [comment]
The wrappers support a predict which a general array (numpy for python) and returns an array (numpy for python). The shape of those arrays are unrestricted except at present for the return array which needs to have dimension >= 2.
 
So the possibilities are wider than classification.

However, we should try to support custom string/byte data easily as well.

I think a easy addition for your original requirement would be to extend the proto bufs with new fields for extra byte and string.

**Comment by killwing** [comment]
We're trying to add new fields for now. thx.

**Comment by cliveseldon** [comment]
I think adding new extra fields to the protobuf would mean the API can remain backwards compatible. If you could submit your changes as a Pull Request that would be great.

**Comment by cliveseldon** [comment]
Please update if there is work that can be contributed back @killwing. Will close for now.
