### ISSUE TITLE
Cannot connect to metrics port 6000 for custom models wrapped with s2i.

### ISSUE THREAD

**Issue by jlee3095** [SeldonIO/seldon-core#1988]
I am trying to write custom metrics so that I can expose them on prometheus and grafana following this guide (https://docs.seldon.io/projects/seldon-core/en/v0.3.0/examples/tmpl_model_with_metrics.html) to create a model with custom metrics.

I followed the instructions exactly to make a REST model. I wrapped the example(ModelWithMetrics.py) with s2i seldonio/seldon-core-s2i-python3:0.7 and deployed the model on seldon-core to k8s. 

However, when looking at the prometheus targets page I get an error:  
**Get "http://[IP address]:6000/prometheus": dial tcp 10.0.2.85:6000: connect: connection refused** 

In addition, I tried deploying the exact same already-wrapped model with custom metrics found in the github repo (https://raw.githubusercontent.com/SeldonIO/seldon-core/master/examples/models/custom_metrics/model_rest.yaml) and the 6000 port did not have any connection issues.

Any help would be appreciated.

**Comment by axsaucedo** [comment]
@jlee3095 this functionality was only introduced from v1.1.0+, you would have to re-wrap your container with a python wrapper v1.1.0 for the prometheus metrics endpoint is available from the model wrapper containers. Versions prior to 1.1.0 exposed metrics only through the service orchestrator.
