### ISSUE TITLE
Enable production mode in Python server by default

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#1993]
Currently, the Python server only uses Gunicorn and production settings if there are multiple workers. We should make sure that by default, even if it runs with a single worker, it also runs with production settings.

Additionally, it could be interesting to explore if it's possible (and makes sense) to always run the Python server with Gunicorn (i.e. even with a single worker).

**Comment by chengcheng-pei** [comment]
@adriangonz what do you mean by `production settings`? could you please give some details?

**Comment by adriangonz** [comment]
@chengcheng-pei the built-in Flask server is not really suited for production. Ideally we should use Gunicorn instead, even with a single worker.

The idea is to keep exposing the Flask server under a `--debug` flag, but default to Gunicorn.
