### ISSUE TITLE
requests per second from seldon_api_executor_cient_requests_count not right?

### ISSUE THREAD

**Issue by chengcheng-pei** [SeldonIO/seldon-core#2004]
## Describe the bug

I used the following three to get RPS:

1, `sum(rate(seldon_api_executor_client_requests_seconds_count{predictor_name=~"tf-rest.*"}[60s]))`

2, `sum(rate(seldon_api_executor_server_requests_seconds_count{predictor_name=~"tf-rest.*"}[60s]))`

3, I used python codes to count the requests per second to model.

`sum by (app) (rate(rest_requests_total{app=~"tf-.*bm"}[60s]))`

python codes:
```
c = Counter('{}_requests'.format("rest"), 'REST requests')
c.inc()
```
**But the first two are about HALF of the third**

Any idea why? Thanks

![Screen Shot 2020-06-22 at 4 26 06 PM](https://user-images.githubusercontent.com/57113014/85344947-edc5fb00-b4a5-11ea-91e8-68ff36d15854.png)

## Environment

* Kubernetes Version: [e.g. 1.15]
* Cloud Provider: [e.g. GKE, AWS, Bare Metal, Kind, Minikube]
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]
* Kubernetes Cluster Version [Output of `kubectl version`]

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
So the third is a custom metric in your python class? Can you show how you create it?

**Comment by chengcheng-pei** [comment]
```
    c = Counter('{}_requests'.format("rest"), 'REST requests')
    while True:
        data_ = random_d() if deploy == 'xgboost-rest' else random_d2()
        start = time.time()
        r = requests.post('http://{}.my-stage.net/api/v1.0/predictions'.format(hostname), json={ "data": { "ndarray": data_ } })
        delta = time.time() - start
        h.observe(delta)
        c.inc()
```

**Comment by cliveseldon** [comment]
You show the counter value. Have you checked the histogram total as well?
Have you check in python code what the req/sec is to get the truth?
