### ISSUE TITLE
Improving Documentation on Advanced / Core Seldon Components

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2012]
Currently Seldon has documentation covering most interfaces but there are several components that could be documented further. This issue is the parent issue to several documentation issues that are currently in place including:
* Adding documentation covering inference graph and components #2011 
* Documentation on Seldon Core Operator #1630 
* Documentation on Seldon Core Microservice https://github.com/SeldonIO/seldon-core/issues/2202
* Documentation on InitContainer #2055
* Documentation on overriding current prepackaged servers to updated versions of the libraries #2060 

Other things to explore:
* Documentation on initContainer (and extending it to create own initContainer)

**Comment by cliveseldon** [comment]
We have updated docs now for V1 APIs. Can address in general for V2 APIs.
