### ISSUE TITLE
Return pointer instead of value in SeldonApiClient methods

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2014]
Methods defined by `SeldonApiClient` interface in `executor` return `payload.SeldonPayload`s via value not reference. 

Is this a potential bottleneck? Could we gain by returning pointers there?

```
Conscious this is for consistency across all functions above, but why are we 
returning `payload.ModelMetadata` by value instead of reference/pointer? 
It seems like it would be quite inefficient to copy all the values that are 
returned by the client
```
_Originally posted by @axsaucedo in https://github.com/SeldonIO/seldon-core/pull/2005#discussion_r445608716

**Comment by RafalSkolasinski** [comment]
Interesting that running
```
package main

import (
	"fmt"
)

type Thing struct {

}

func main() {
	t := rt()
	fmt.Printf("%p\n", &t)
}

func rt() Thing {
	t := Thing{}
	fmt.Printf("%p\n", &t)
	return Thing{}
}
```
actually shows me twice the same address.

**Comment by glindsell** [comment]
`payload.SeldonPayload` is actually an interface which can hold either a struct or a pointer to a struct.

**Comment by RafalSkolasinski** [comment]
This is perfect @glindsell, thanks for the insight! I had to forgot about that Go nuance :)

**Comment by RafalSkolasinski** [comment]
Going down on Golang good practices I now wonder if it is best to have

1. `SeldonApiClient.Metadata` method that returns `payload.SeldonPayload` storing raw payload and `SeldonApiClient.ModelMetadata` that returns model metadata decoded to `payload.ModelMetadata` struct

or 

2. Have one method in `SeldonApiClient` that returns `payload.SeldonPayload` and extend `payload.SeldonPayload` interface to have a method that decodes payload to `ModelMetadata` struct.

**Comment by cliveseldon** [comment]
I think the SeldonPayload is meant to be very generic and not really get into the machine learning specifics. So I'd suggest not unless a good reason.

**Comment by RafalSkolasinski** [comment]
> I think the SeldonPayload is meant to be very generic and not really get into the machine learning specifics. So I'd suggest not unless a good reason.

Ok, that basically cross away `option 2` meaning that what is currently in metadata PR is right up to the return value instead of pointer for optimisation.
