### ISSUE TITLE
Switch Ambassador support to use Host/Mapping/etc CRDs

### ISSUE THREAD

**Issue by josephglanville** [SeldonIO/seldon-core#2015]
Currently Ambassador support is implemented by annotations on the predictor services. For more flexibility and better integration switching to the CRDs would be preferable.

**Comment by josephglanville** [comment]
Currently blocked on https://github.com/datawire/ambassador/issues/2830 or generating the client locally.

**Comment by cliveseldon** [comment]
Done as we support Ambassador v2 CRDs
