### ISSUE TITLE
dev guide doc: develop/test changes locally?

### ISSUE THREAD

**Issue by mlaicode** [SeldonIO/seldon-core#202]
I would like to contribute to this however did not find much details in developer guide. E.g. how to build/test locally before submitting a PR? It is documented somewhere? 
Could not find it here - https://github.com/SeldonIO/seldon-core/blob/master/docs/developer/readme.md

**Comment by cliveseldon** [comment]
I agree the developer docs need further detail - will add an issue for this. Most of the Java components can be run stand alone outside the cluster - in particular the Operator (cluster-manager) will pick up your local kube config settings.

The best option for now is to start an issue with the thing you are considering to contribute or to continue a conversation in an existing one and we can discuss.

Furthermore, feel free to contact us on Slack to discuss things.

**Comment by mlaicode** [comment]
got it, thanks.
