### ISSUE TITLE
Drop podinfo volume name backwards compatibility transition in 1.3 release

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2024]
Currently we are adding logic in the operator to enable the compatible transition of all live seldon models from 1.1 to 1.2.1 via #2019 (more info in #2017). We should aim to remove this in version 1.3, with an upgrading requirement to migrate to 1.2.1 if an earlier version of seldon core is being used.

**Comment by ryandawsonuk** [comment]
Looks like we will have to retain it for longer due to https://github.com/SeldonIO/seldon-core/pull/2019#issuecomment-651708216
