### ISSUE TITLE
No module named 'sklearn.linear_model._logistic' when using the docker image seldonio/sklearnserver_rest:1.2.0 due to `scikit-learn==0.20.3`

### ISSUE THREAD

**Issue by bydeath** [SeldonIO/seldon-core#2059]
## Describe the bug

When I deploy the model folowing [https://docs.seldon.io/projects/seldon-core/en/v1.2.0/workflow/github-readme.html#deploy-your-model-using-pre-packaged-model-servers](https://docs.seldon.io/projects/seldon-core/en/v1.2.0/workflow/github-readme.html#deploy-your-model-using-pre-packaged-model-servers), the pod is not running up, the status of the pod is 'CrashLoopBackOff', the error is:
> No module named 'sklearn.linear_model._logistic' 

I think the error is due to `scikit-learn==0.20.3` in the docker image `seldonio/sklearnserver_rest:1.2.0`. I uninstalled `scikit-learn==0.20.3` and installed the latest version of sklearn, it worked well without the error.

## To reproduce

The imageID of  image `seldonio/sklearnserver_rest:1.2.0` I used is `628254ff211b`.

Use below command to deploy a SeldonDeployment.
```bash
kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model
  namespace: seldon
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: pvc://seldon-models/sklearn/iris
      name: classifier
    name: default
    replicas: 1
END
```
## Expected behaviour

The pod is running of the SeldonDeployment 

## Environment

Kubernetes version: v1.15.12
Seldon Images: 1.2.0

## Model Details 

my model is trained with this code [https://github.com/SeldonIO/seldon-core/blob/v1.2.0/examples/models/sklearn_iris/train_iris.py](https://github.com/SeldonIO/seldon-core/blob/v1.2.0/examples/models/sklearn_iris/train_iris.py).

**Comment by axsaucedo** [comment]
@bydeath thank you for reporting the issue. Currently the prepackaged image is built with version 20.3 of sklearn, and you must train your models with that version to use the model server https://docs.seldon.io/projects/seldon-core/en/latest/servers/sklearn.html

If you wish you build your own image, you can update the prepackaged server by following the custom inference servers example https://docs.seldon.io/projects/seldon-core/en/latest/servers/custom.html - you can either override the base sklearn image or create your own.

**Comment by axsaucedo** [comment]
Added #2060 to improve documentation on this
