### ISSUE TITLE
Is there a way to specify URL of swagger-ui static resources instead of https://cdnsjs.cloudflare.com in a intranet k8s cluster

### ISSUE THREAD

**Issue by bydeath** [SeldonIO/seldon-core#2067]
I deployed a SeldonDeployment and access `http://<ingress_url>/seldon/<namespace>/<model-name>/api/v1.0/doc/`, and the  page renders failed, because these three files `swagger-ui.css`, `swagger-ui-bundle.js`,`swagger-ui-standalone-preset.js` failed to be fetched from `https://cdnsjs.cloudflare.com`. My k8s cluster is in a intranet and it can't access internet resources `https://cdnsjs.cloudflare.com` directly. 

I wonder is there a way to set the URL of swagger-ui static resources when I deploy seldon models, or is there a way to mount the static files manually?

**Comment by adriangonz** [comment]
@bydeath could you try accessing http://<ingress_url>/seldon/<namespace>/<model-name>/api/v1.0/doc/index_bundled.html instead?

**Comment by bydeath** [comment]
Yes, it worked. Thans for your reply.
