### ISSUE TITLE
Refactor KIND in Kubernetes Implementation for CICD

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2080]
There has been further extension on the Docker in Docker, and more specifically KIND in Kubernetes approach towards leveraging in integration tests and CICD via https://github.com/kubernetes-sigs/kind/issues/303. We should be able to refactor our current implementation for Docker in Docker, and potentially bake into the builder image. There was a good blogpost which we can follow from D2IQ https://d2iq.com/blog/running-kind-inside-a-kubernetes-cluster-for-continuous-integration

**Comment by anggao** [comment]
@axsaucedo As part of this work, will you plan migrate to github actions as well ?

**Comment by axsaucedo** [comment]
@anggao this task would comprise mainly of refactoring the underlying container that runs KIND, but not to change more beyond that. We've explored github actions, we definitely want to move some key workflows, but probably we won't be able to move everything that we're running in Jenkins X. 

For more detail, the current e2e tests run in containers so in theory we could move that to Github actions, however given that the hardware requirements are higher than the gh actions default limits, we would have to run in custom workers, and at that point it woudl be almost the same as running it in the Jx cluster.

We'd certainly be open to explore further tho, perhaps we can discuss this in the next community call?

**Comment by anggao** [comment]
I see, yeah this would be a great topic to cover in the community call, I hope we can speed up the integration test in the future  :)

**Comment by cliveseldon** [comment]
Closing this for now as many upgrades to CI process have been done.
