### ISSUE TITLE
how to explore grafana dashboard for seldon-core  in  web ui

### ISSUE THREAD

**Issue by mullerhai** [SeldonIO/seldon-core#209]
hi
      in  our doc  has not talk about the  monitor ,but  our team  need  some monitor  for seldon-core to know the  predict request and reponse  log  and data ,
in seldon-core project root directory  monitoring/  ,I  just run bashscript "start-all ",then I see 

alertmanager-deployment-5d4b5565d4-z7khd                          1/1       Running            1          22h
grafana-prom-deployment-dd84b7788-kb5w8                           1/1       Running            1          22h
grafana-prom-import-dashboards-6prd6                              0/1       Completed          0          21h

prometheus-deployment-6f6746d45c-74x7c                            1/1       Running            1          22h
prometheus-node-exporter-gwzsl                                    1/1       Running            1          22h

I do not know why grafana-prom-import-dashboards not running just completed ?  and  how to  see the  grafana dashboard  web ui  in  Explore  Chrome,,
who  could tell me the correct method , 

thanks

**Comment by cliveseldon** [comment]
The grafana dashboard import is a job that imports the grafana dashboards so its is correct to complete.
You can view the dashboards by port-forwarding the grafana pod like:
```
kubectl port-forward $(kubectl get pods -n seldon -l app=grafana-prom-server -o jsonpath='{.items[0].metadata.name}') -n seldon 3000:3000
```
and then visiting: http://localhost:3000/dashboard/db/prediction-analytics?refresh=5s&orgId=1

You will need to login using username "admin" and the password set when running the helm install.

Try the example notebook https://github.com/SeldonIO/seldon-core/blob/master/notebooks/kubectl_demo_minikube_rbac.ipynb

**Comment by mullerhai** [comment]
@cliveseldon  very thanks ! and  I think ,you should add these  on your project doc ,maybe many user will use it

**Comment by cliveseldon** [comment]
Good idea. Let's leave this issue open until that is done.

**Comment by cliveseldon** [comment]
There is now documentation describing the current [analytics](https://github.com/SeldonIO/seldon-core/blob/master/docs/analytics.md)
