### ISSUE TITLE
Refactor logging in Executor

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2090]
Sub Issue of https://github.com/SeldonIO/seldon-core/issues/2088.

Currently we use `go-logr` implementation coming from `sigs.k8s.io/controller-runtime/pkg/runtime/log`.
Using an alternative implementation or providing one on our own would allow to lift that dependency from Executor's `go.mod`.

**Comment by cliveseldon** [comment]
Not sure if we need to do this so will close.
