### ISSUE TITLE
Move fully to UBI based images

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2097]
Now that it's proven that Red Hat UBI images can work as a good base (python wrapper, prepackaged servers, etc) I think we should fully move to only support UBI based images: mostly to optimise maintenance effort:

- [ ] core-builder
- [ ] all wrapper images
- [x] all prepackaged images

Question: should we just deprecate current images and have UBI-based ones under a new name or just change base? 

Also to check: is there NVIdia/GPU image in UBI base.

**Comment by cliveseldon** [comment]
We should do a size comparison

**Comment by cliveseldon** [comment]
Will look in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html)
