### ISSUE TITLE
Existing Webhook Secret Clashes if own certificate provided when doing upgrade

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2101]
## Describe the bug

Currently the webhook has the option to either enable certmanager to perform the creation of the sercret, or alternatively to disable certmanager and create a certificate manually. However for users that want to configure the certificates manually, this would be an issue for the following two reasons:
1) The installation would fail if an existing secret is created
2) If the secret is removed, and the new secret is created, it would not be dynamically loaded immediately by the webhook

## To reproduce

1. Create an installation with certmanager disabled (such that a secret gets created)
2. Perform an upgrade which would lead into a clash of the secret

## Environment

Seldon Core 1.2.1

**Comment by ellisvalentiner** [comment]
any updates on this issue?

**Comment by axsaucedo** [comment]
After further research this seems to be expected behaviour from Certmanager. When Seldon Core is run with --set certmanager.enabled=true it would create a `Certificate` object - when seldon core is removed, the certificate object is correctly removed, but by default certmanager does not delete the secrets. If it's desired for certmanager to remove the secrets, certmanager as to be explicitly installed with a set of CLI parameters, as outlined here https://cert-manager.io/docs/usage/certificate/#cleaning-up-secrets-when-certificates-are-deleted

Closing as this seems to be expected behaviour, and solution is on certmanager installation configuration.
