### ISSUE TITLE
READWRITEMANY does not work on GCP

### ISSUE THREAD

**Issue by kapilsingh421** [SeldonIO/seldon-core#2102]
## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
by default GCP does not have readwritemany: https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

**Comment by kapilsingh421** [comment]
Ok then what is the solution for this ..
https://github.com/SeldonIO/seldon-core/tree/master/examples/kubeflow
<img width="1030" alt="Screenshot 2020-07-10 at 1 13 38 AM" src="https://user-images.githubusercontent.com/37150928/87083650-9916d400-c24a-11ea-8db4-3a29d1b78b4d.png">

**Comment by kapilsingh421** [comment]
i also tried with READWRITEONCE but got error,  i think to make this example work on gcp , need to specific volume for every container..Please help i am stucked in this above example.Please provide your suggestion.
i am using seldon core from GCP marketplace 2.1 tag
Kubeflow Pipeline from AI platform of GCP

<img width="1114" alt="Screenshot 2020-07-10 at 1 21 52 AM" src="https://user-images.githubusercontent.com/37150928/87084376-c1530280-c24b-11ea-8dbd-d4b2cdd8341c.png">

**Comment by kapilsingh421** [comment]
@cliveseldon 
> i also tried with READWRITEONCE but got error, i think to make this example work on gcp , need to specific volume for every container..Please help i am stucked in this above example.Please provide your suggestion.
> i am using seldon core from GCP marketplace 2.1 tag
> Kubeflow Pipeline from AI platform of GCP
> 
> <img alt="Screenshot 2020-07-10 at 1 21 52 AM" width="1114" src="https://user-images.githubusercontent.com/37150928/87084376-c1530280-c24b-11ea-8dbd-d4b2cdd8341c.png">



> Ok then what is the solution for this ..
> https://github.com/SeldonIO/seldon-core/tree/master/examples/kubeflow
> <img alt="Screenshot 2020-07-10 at 1 13 38 AM" width="1030" src="https://user-images.githubusercontent.com/37150928/87083650-9916d400-c24a-11ea-8db4-3a29d1b78b4d.png">
