### ISSUE TITLE
Add documentation of rules that python wrapper applies to convert incoming data into jsonData, tensor, etc in predict function

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2108]
Currently the way that the predict function converts the incoming data and more importantly the return statement is quite obscure, and the community tends to just look at the util.py functions, however they shouldn't have the need to read the source to know what rules apply. For this it would be useful to ahve a table or a high level overview of the rules that apply in regards to what data types get converted into what request/response type.
This is part of the documentation updates in #2012.

**Comment by cliveseldon** [comment]
Closing this as probably overlaps MLServer docs for roadmap.
