### ISSUE TITLE
Request logger drops incoming requests for traffic coming from a single model

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2109]
## Describe the bug

When sending a set of requests to a seldon model the request logger drops messages. If a number of requests (ie 100 or 1000) are sent to a seldon model, and the seldon model sends the requests to the payload logger at the same rate in which it processes them, only 300 messages are actually logged. 

Generally in logging atLeastOnce delivery is not as critical, however given that these would be used for audit logs, instead of just traditional logs (similar to the ones collected by fluentd), it would be key to ensure atLeastOnce delivery can be backed. This is also important as this is only traffic for one model, and the current architecture expects to have multiple (if not all) models, as well as other components like outlier detectors, to be sending payload to a single payload logger.

## To reproduce

Simply deploy a model with payload logging enabled, and run a basic set of requests:
```
for i in range(1000):
    pred_req = {"data":{"ndarray":[[1,2,3,4]]}}
    pred_resp = requests.post(f"{url}/predictions", json=pred_req)
    assert pred_resp.status_code == 200
```

Then count the number of resulting logs
```
es.count(index="inference-log-seldon-seldon-sklearn-default")
```

It can also be replicated with smaller numbers, such as 200.

## Expected behaviour

For the payload logger to be able to process requests at least at the same rate as a single seldon model would process them, and as a follow-up to explore adding atLeastOnce delivery.

**Comment by ryandawsonuk** [comment]
Interesting, I would guess it's probably hitting https://stackoverflow.com/questions/37855803/rejected-execution-of-org-elasticsearch-transport-transportservice-error/37891883#37891883

**Comment by axsaucedo** [comment]
Interesting, yes, it may be a combination of that and potentially a limit on concurrent requests being received by the request logger. These are the messages you can see in the logs when the messages are dropped:
```
ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='elasticsearch-master.seldon-logs.svc.cluster.local', port=9200): Read timed out. (read timeout=10))
ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='elasticsearch-master.seldon-logs.svc.cluster.local', port=9200): Read timed out. (read timeout=10))
ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='elasticsearch-master.seldon-logs.svc.cluster.local', port=9200): Read timed out. (read timeout=10))
```
It seems there are some improvements we can explore tho, currently the golang request logger implements a basic local queue, we could explore using a queue in the request logger as well, we could take a similar approach to how it's done in the python batch processing component. Once we have a way to buffer requests, it would also be easier to implement retries.

The request logger is currently using Flask development server, so we also need to make sure it runs behind gunicorn to ensure it's possible to leverage the same flags for number of workers and threads, which would make it more robust (although the queuing / buffering woudl still be required to avoid messages being dropped without retries)

**Comment by ryandawsonuk** [comment]
Could also try running more replicas of both elastic and logger. Though those messages look like it's elastic that isn't responding to an initial read request that the logger does. By default we we do run elastic as single-node and with reduced resources.

**Comment by ryandawsonuk** [comment]
Actually maybe we don’t reduce resources except on kind. But the chart’s defaults aren’t very high. Might also need to check whether the service calls are resulting in a round-robin among the nodes

**Comment by axsaucedo** [comment]
Yeah definitely, however I think there's quite a lot of improvements that can be done in the python code itself before thorough optimizations / exploration of horizontal scaling. I suspect that currently the service is limited to 100 threads with single worker/core. Given the processing in the default logger is quite minimal (with most of the time waiting for the elasticsearch request to be done) there could be quite a lot of performance improvements within the python code itself. Right now it seems a single request logger can't keep up with a single model (simple sklearn model), so there's some bottlenecks which if fixed could have quite significant improvements. Adding gunicorn on top will make workers + threads configurable, and there's a few things that may be possible to reuse from the batch processor such as basic queue buffering (similar to how the golang req logger worker does it). We can dive into it during the week, I also managed to find a few interesting insights exploring #2110 that would be interesting to discuss

**Comment by ryandawsonuk** [comment]
I recreated this and found that the timeouts were happening in the logger connecting to elastic. It actually doesn't need to do that repeatedly and could just do it on startup, so have made a PR for that change:

https://github.com/SeldonIO/seldon-core/pull/2120

After fixing that I then hit a bottleneck on the elastic side, an elastic req queue depth:
````
TransportError(429, 'es_rejected_execution_exception', 'rejected execution of processing of [10756282][indices:data/write/update[s]]: update {[inference-log-seldon-seldon-income-default][inferencerequest][f66f9392-67d4-4ba5-8fe1-023e814c1266], doc_as_upsert[true], doc[index {[null][_doc][null], 
...
on EsThreadPoolExecutor[name = elasticsearch-master-1/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@4c760952[Running, pool size = 1, active threads = 1, queued tasks = 200, completed tasks = 809333]]')
````
This is [configurable](https://stackoverflow.com/questions/37855803/rejected-execution-of-org-elasticsearch-transport-transportservice-error/37891883#37891883) though I haven't tried increasing that yet.

**Comment by ryandawsonuk** [comment]
Have now tried increasing the queue depth on the elastic side. When I combine that with increasing the read timeout I can get messages through at a high rate with much more reliability. If you push it hard enough it will be possible to hit a bottleneck on elastic that would ultimately mean adding more resource there. But [these changes](https://github.com/SeldonIO/seldon-core/pull/2120) are a big improvement.

**Comment by axsaucedo** [comment]
Nice one @ryandawsonuk ! I was thinking that some initial optimisations would make a difference but this is great!

**Comment by ryandawsonuk** [comment]
Yeah we could keep this open since, as you point out, there's other things that could be done. But I think this clears the key bottleneck so also an option to close and reopen in future.

**Comment by cliveseldon** [comment]
closing for #2141
