### ISSUE TITLE
deploy docker image is ok ,but deploy  k8s pod  always  failed

### ISSUE THREAD

**Issue by mullerhai** [SeldonIO/seldon-core#212]
for example  the   /example/models/keras-mnist 
I use to seldon-core-s2i-python3   wrapper it  ,then s2i  build   the docker image,
I try to run it ,and   successful ,
but ,when  I  try  kubectl  create -f   keras-mnist_deployment.json ,
wait for   some times ,the pod  always  not run 
keras-mnist-deployment-keras-mnist-predictor-svc-orch-6f47rcssd   0/1       CrashLoopBackOff   31         1h
prometheus-prometheus-alertmanager-dfdb5b4c5-rqgz9                2/2       Running            4          15h
prometheus-prometheus-kube-state-metrics-7b6f486656-kh7x4         1/1       Running            13         15h
prometheus-prometheus-node-exporter-j4kzg                         1/1       Running            2          15h
prometheus-prometheus-pushgateway-8bd4d8b7c-vcmwv                 1/1       Running            2          15h
prometheus-prometheus-server-577dd55455-4g5pd                     2/2       Running            4          15h
seldon-349347adca40c3fd7826c677243602b7-569b5b54c9-sh2sf          0/1       ImagePullBackOff   0          1h
seldon-core-redis-5f6bc97f64-9zvb5                                1/1       Running            2          15h
seldon-core-seldon-apiserver-68587c59f-bdk9x                      1/1       Running            2          15h
seldon-core-seldon-cluster-manager-7fb9798f98-r9xf5               1/1       Running            2          15h

**Comment by cliveseldon** [comment]
Are you following one of the notebooks to run this?
Can you show the  logs from the *svc-orch* pod that is crashing?
There was a bug in the engine 0.2.3-SNAPSHOT image yesterday and a new version was pushed. Can you try with a fresh minikube?

**Comment by mullerhai** [comment]
![seldon-keras-error-pod](https://user-images.githubusercontent.com/6143404/45003560-71cf9a00-b016-11e8-95e5-8bbbfeb7c177.png)
![seldon-error2](https://user-images.githubusercontent.com/6143404/45003576-9461b300-b016-11e8-8fcf-63bb04b9957d.png)

I do not know  why always  failed when I create the keras-mnist example

**Comment by cliveseldon** [comment]
Please reopen if still an issue.
