### ISSUE TITLE
Stateful Model Serving by Saving state to Redis

### ISSUE THREAD

**Issue by ramanNarasimhan77** [SeldonIO/seldon-core#2138]
Hello,

My understanding from `microservice.py` and `persistence.py` is that for saving model state:

a) seldon-core-microservice has to be invoked with persistence set to 1

b) microservice.py tries to restore existing state from redis and starts a new persistence thread that pushes to redis as per the `push_frequency`

c) Key used for storing state in Redis is `persistence_{DEPLOYMENT_ID}_{PREDICTOR_ID}_{PRED_UNIT_ID}`

Based on this understanding, I have couple of questions on stateful serving

1. If I use gunicorn by setting `GUNICORN_WORKERS` environment variable to 3, 3 gunicorn workers would be created in the container.  All of these 3 would load the model and can serve prediction requests.  My understanding is that in this case each worker would try to save its state. All the workers have same `REDIS_KEY` so they would overwrite each others state.
How should saving state work in this case?

2. I started with this example [DeepMnist.py](https://github.com/SeldonIO/seldon-core/blob/master/examples/models/deep_mnist/DeepMnist.py) and added an instance variable `no_of_requests`.  I am incrementing `no_of_requests` each time predict gets called.

I am also exposing `no_of_requests` value as a `custom metric`  so that I can verify it's value in the prediction response

```
  def metrics(self):
        return [
            {"type":"GAUGE","key":"no_of_requests","value":self.no_of_requests},
            ]
```

I started a local docker container running seldon-core-microservice serving using werkzeug (I am not using gunicorn)

My expectation is that if run 5 inference requests `no_of_requests` would get set to 5,  and save state to redis and stop the serving container (keep container running for more than a minute), and after sometime if start a new container and run inference requests, `no_of_requests` should start from 6 and not from 1

However when 1 minute was over, I saw that saving state to redis fails with this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/user/.local/lib/python3.7/site-packages/seldon_core/persistence.py", line 83, in run
    binary_data = pickle.dumps(self.user_object)
TypeError: can't pickle _thread.RLock objects
```

## Snippet used for running redis and starting inference:

```
version=1.0.0
model=deepmnist_rest:${version}
persistence=1
docker build --build-arg PERSISTENCE=${persistence} -t deepmnist_rest:${version} -f inference/Dockerfile inference
docker run --network redis --name redis-host --rm -d redis
docker run --network=redis --env-file env/properties -p 5000:5000  -it ${model}
```

Environment settings in env/properties file

```
SELDON_DEBUG=true
SELDON_LOG_LEVEL=DEBUG
REDIS_SERVICE_HOST=redis-host
REDIS_SERVICE_PORT=6379
```

**Comment by cliveseldon** [comment]
The persistence use case is very much in an alpha state. To answer your first question, yes the state would be overwritten so either we would need to extend the save handling if applicable or you would need a custom implementation for state saving.

In your example though it looks like even for 1 worker there is an issue?

**Comment by ramanNarasimhan77** [comment]
Yes @cliveseldon , I tested by serving using flask on werkzeug and got an error while saving state to redis

**Comment by axsaucedo** [comment]
Closing - see #2888
