### ISSUE TITLE
How to pass a contract.json as curl request. I keep getting bad data when i send a contract.json file as curl.

### ISSUE THREAD

**Issue by yashcodecollab** [SeldonIO/seldon-core#2151]
I want to pass the below contract.json for mean_classifier model as curl request. I am able to send it successfully using seldon-core-tester. But it fails with curl for me it says bad data sent when i send the contract using curl. @gsunner @cliveseldon .

{
    "features":[
        {
            "name":"x",
            "dtype":"FLOAT",
            "ftype":"continuous",
            "range":[0,1],
            "repeat":784
        }
    ],
    "targets":[
        {
            "name":"class",
            "dtype":"FLOAT",
            "ftype":"continuous",
            "range":[0,1],
            "repeat":10
        }
    ]
}

**Comment by cliveseldon** [comment]
This page should help: https://docs.seldon.io/projects/seldon-core/en/latest/workflow/serving.html

For curl something like, with the values 784 of them. 

```
curl -v 0.0.0.0:8003/seldon/mymodel/api/v1.0/predictions -d '{"data":{"names":["a","b"],"tensor":{"shape":[1,784],"values":[<784 values>]}}}' -H "Content-Type: application/json"
```

It may be easier to generate the data and send or see other examples for mnist: https://docs.seldon.io/projects/seldon-core/en/latest/examples/notebooks.html
Some of these use the Seldon python client.

**Comment by yashcodecollab** [comment]
I am trying to use the seldon-batch-processor .Given below is the command that i am running. I have also given the input.txt which i am trying to feed as input to the iris classifier model this is the same iris classfier sample code on your website.
But i dont get any ouput the output.txt file is empty. Am i doing anyhting wrong here. Is the input file in wrong format for a batch input.

**sh-4.2$ seldon-batch-processor -d "irisclassifier" -g seldon -n air9  -h 0.0.0.0 -t rest -a json -p ndarray -w 100 -r 3 -i "/app/input.txt" -o "/app/output.txt" -m predict --benchmark  
Elapsed time: 0.014407873153686523**

@cliveseldon @axsaucedo 


sh-4.2$ cat input.txt
[[5.964,4.006,2.081,1.031]]
[[1.964,5.006,22.081,1.031]]
[[2.964,6.006,21.081,1.031]]
[[3.964,7.006,22.081,1.031]]
[[4.964,8.006,24.081,1.031]]
[[5.964,9.006,2.081,1.031]]
[[6.964,10.006,2.081,1.031]]
[[7.964,11.006,2.081,1.031]]
[[8.964,12.006,2.081,1.031]]
[[9.964,13.006,20.081,1.031]]
