### ISSUE TITLE
Nodejs wrapper for javascript models

### ISSUE THREAD

**Issue by SachinVarghese** [SeldonIO/seldon-core#216]
With the release of Tensorflow js with nodeJS bindings, the number of developers using javascript for creating and deploying models has certainly increased. Creating a nodeJS wrapper for these models with a REST and gRPC endpoints would certainly attract a lot of new model developers to the Seldon project's language-agnostic way of deploying models.

**Comment by cliveseldon** [comment]
This sounds great. We would be happy to help you work on it.
Would an [S2I](https://github.com/openshift/source-to-image) wrapper make sense?

**Comment by cliveseldon** [comment]
There already exists some example of [S2I Node JS Builder images](https://github.com/sclorg/s2i-nodejs-container) which could be a base.
The key would be to create the microservice API server, which for example is Flask in python.

**Comment by SachinVarghese** [comment]
Yes, sure I can start creating an S2I wrapper for the same. Can someone share more details on how can I contribute to the project? I'll start by creating a builder image for a model component.

**Comment by cliveseldon** [comment]
I suggest you look at the python S2I wrapper code which can be found at: https://github.com/SeldonIO/seldon-core/tree/master/wrappers/s2i/python
Create something similar with a similar structure, testing and image name.

**Comment by SachinVarghese** [comment]
I have forked the Seldon-core repository and created an S2I wrapper code similar to python. I have tried to keep the idea similar as much as possible. Although it is limited to REST service only as of now, it is tested with an example tensorflow model. Please find the link at [seldon-core-s2i-nodejs ](https://github.com/SachinVarghese/seldon-core/tree/issue-216/wrappers/s2i/nodejs). 

@cliveseldon can you review and please let me know if I shall proceed with a pull request.

**Comment by cliveseldon** [comment]
This looks great. Feel free to do a Pull Request.
It would be great to add some docs in the docs folder following the pattern of the other wrappers available. Also, to add one example in example/models folder that can be referenced from the top level readme.

**Comment by SachinVarghese** [comment]
As per your suggestion, I have added a [nodejs tensorflow model](https://github.com/SachinVarghese/seldon-core/tree/issue-216/examples/models/nodejs_tensorflow) in the examples section and also added a doc for the [nodejs wrapper](https://github.com/SachinVarghese/seldon-core/blob/issue-216/docs/wrappers/nodejs.md).

- In the wrapper doc, I am refering to the nodejs wrapper image  at **seldonio/seldon-core-s2i-nodejs:0.1** which is not present yet at the location. Need some clarification on this.

- Some links may be broken as they refer to the upstream master branch and they will be automatically resolved when merged with master

- Lastly, I have not yet added the example to the top level readme as I will have to create an ipynb notebook to maintain the pattern followed. Will take it up later along with adding better examples.

**Comment by ahousley** [comment]
Fantastic @SachinVarghese - thanks for the great suggestion and quick implementation! I'm sure other members of the community will want to deploy Javascript models and find this wrapper useful. :thumbsup:

**Comment by SachinVarghese** [comment]
@cliveseldon and @ahousley  Thanks for your support in merging the implementation with a javascript model and a rest API. Nextly, I will plan for a gRPC API and other Seldon components.
