### ISSUE TITLE
CNCF-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [SeldonIO/seldon-core#2181]
Hello Seldom team,

I'm one of the co-chairs of the [CNCF SIG-Runtime](https://github.com/cncf/sig-runtime), I was looking at your project and I think it would be amazing for you to present/discuss it at one of our meetings. Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by cliveseldon** [comment]
Hi @raravena80 sounds great. Will reach out to you.

**Comment by raravena80** [comment]
[Video](https://youtu.be/Cm7s3U8MFMM) of the presentation.

**Comment by cliveseldon** [comment]
Great thanks @raravena80
