### ISSUE TITLE
Enable Batch Processor to work with local python microservice ("Seldon gateway")

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2182]
Currently batch processor is configured to work with the istio/ambassador ingress (ie prefixed with `/seldon/<namespace>/<sdep>/`, however for people that want to run it locally, we would have to add configuration that allows the SeldonClient to be configured with the `seldon_rest_endpoint` and `seldon_grpc_endpoint`. We could also explore modifying it to just use a single `endpoint`.

**Comment by axsaucedo** [comment]
Relevant to #2173

**Comment by cliveseldon** [comment]
Closing can reopen for more general batch processing discussion
