### ISSUE TITLE
seldon operator giving error 

### ISSUE THREAD

**Issue by kkuhu302** [SeldonIO/seldon-core#2184]
I have installed seldon operator in my openshift cluster. But at the time of creating seldon deployment instance it is giving error: Error "failed calling webhook "v1.mseldondeployment.kb.io": Post https://seldon-webhook-service.h2o.svc:443/mutate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s: service "seldon-webhook-service" not found" for field "undefined". I do have seldon-webhook-service in my project. But as per my finding it is targeting to another project's webhook service.

**Comment by cliveseldon** [comment]
Will close this as fixed by deleting old webhooks. Please reopen if deeper issue:
https://seldondev.slack.com/archives/CSVSD5S75/p1595988760343700?thread_ts=1595478379.339300&cid=CSVSD5S75
