### ISSUE TITLE
R wrapper s2i environment documentation missing Model file extension

### ISSUE THREAD

**Issue by SachinVarghese** [SeldonIO/seldon-core#219]
I tried deploying the example R iris model. I found that the s2i environment required as per the [R wrapper s2i env docs](https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/r.md#s2ienvironment) doesn't work. The parameter model name has to have the file extension also to make it work. For instance, the s2i/environment file, needs to be 
```
MODEL_NAME=MyModel.R
```

**Comment by cliveseldon** [comment]
Thanks. if you can create a small PR for this we can get it merged.

**Comment by SachinVarghese** [comment]
This is fixed. Closing.
