### ISSUE TITLE
Add / Extend  docs on seldon-core-microservice

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2202]
Sub issue for https://github.com/SeldonIO/seldon-core/issues/2012

We should have a good documentation on `selcon-core-microservice` from usage perspective: 
- CLI arguments
- Environmental Variables
- etc...

**Comment by siddygups** [comment]
Would be useful to have a --help option. Can model class and/or module path be specified?

**Comment by RafalSkolasinski** [comment]
Hi @siddygups, I don't fully understand what do you mean by specifying class/module path?

**Comment by RafalSkolasinski** [comment]
Once merged will be available at https://docs.seldon.io/projects/seldon-core/en/latest/python/python_server.html.
