### ISSUE TITLE
Update documentation to state Istio or Ambassador is a prerequisite

### ISSUE THREAD

**Issue by omerfsen** [SeldonIO/seldon-core#2212]
On https://github.com/SeldonIO/seldon-core/blob/master/doc/source/workflow/install.md it is better to add Istio/Ambassador as prerequisite as while doing the installation i kind of felt that command

```
helm install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --set istio.enabled=true --set usageMetrics.enabled=true --namespace seldon-system
```

will actually install Istio for me.

Also it would be nice to state which version you support for Istio. Is 1.6 latest is ok ?

**Comment by omerfsen** [comment]
https://github.com/SeldonIO/seldon-core/compare/master...os-virtualretail:patch-1 is proposed

**Comment by cliveseldon** [comment]
Sounds good. Can you create PR? @omerfsen

**Comment by cliveseldon** [comment]
Docs are no updated. Please reopen if not clear.
