### ISSUE TITLE
kubeflow central dashboard we could not see Manage Contributor menu

### ISSUE THREAD

**Issue by Kannanjm** [SeldonIO/seldon-core#2223]
Hello Team,
We have deployed Kubeflow on Kubernetes in kubeflow central dashboard we could not see Manage Contributor menu. Kindly help to fix this issue.
Below are the environment details.
OS Version: CentOS Linux release 7.8.2003 (Core)
Kubernetes Version: v1.18.6
Kubernetes platform: Openstack Instance
kfctl version: kfctl v1.0.2-0-ga476281
Kubeflow version: build version dev_local

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
I think you need to update or open this issue: https://github.com/kubeflow/kubeflow/pull/5147
