### ISSUE TITLE
graph implementation other than sklearn does not support modelUri for init container

### ISSUE THREAD

**Issue by maorlipchuk** [SeldonIO/seldon-core#2224]
## Describe the bug
I'm trying to run a model of mine saved in my s3 bucket.
It seems that once I try to add modelUri (so my model will be copied from the s3 bucket) to my graph template file, with model other than SKLEARN_SERVER, I get an exception indicating the following:
TypeError: __init__() got an unexpected keyword argument 'model_uri'
 from  is not getting executed for graphs other than SKLEARN_SERVER

## To reproduce
1. build a simple model with slearn_server implemetation containning model_uri field:
test.yaml:
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  name: myplace
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: s3://myplace
      envSecretRefName: seldon-init-container-secret
      name: classifier
    name: default
    replicas: 1

2. Apply the model: 
kubectl apply -f test.yaml

3. try to log the initi container and the container see that everything works:
➜ k logs sklearn-default-0-classifier-d79bb78b4-tk5sq classifier-model-initializer
[I 200801 00:18:41 initializer-entrypoint:13] Initializing, args: src_uri [s3://myplace] dest_path[ [/mnt/models]
[I 200801 00:18:41 storage:35] Copying contents of s3://myplace to local
[I 200801 00:18:42 storage:60] Successfully copied s3://myplace to /mnt/models

**Now try to do the same steps for an implementation type other than skleran_server for example MLFLOW_SERVER:**

Do the same with implementation of ML_FLOW for example cause me the following exception:
...
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/seldon-core-microservice", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 202, in main
    user_object = user_class(**parameters)
TypeError: __init__() got an unexpected keyword argument 'model_uri'

## Expected behaviour
See the following documentation for expected behaviour:
https://docs.seldon.io/projects/seldon-core/en/v1.1.0/servers/overview.html

Seems like once a modelUri field exists as part of the graph template an init container should be deployed, copy the files from the bucket.

## Environment
* Cloud Provider: AWS
* Kubernetes Cluster Version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:48Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
* Deployed Seldon System Images: 
          value: docker.io/seldonio/engine:1.2.1
          value: docker.io/seldonio/seldon-core-executor:1.2.1
        image: docker.io/seldonio/seldon-core-operator:1.2.1

**Comment by maorlipchuk** [comment]
The model which I try to deploy is keras model.
The files in my S3 are h5 and json

**Comment by cliveseldon** [comment]
Can you show the yaml that does not work?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
