### ISSUE TITLE
Missing log-dir parameter to operator-manager

### ISSUE THREAD

**Issue by MatanAmoyal** [SeldonIO/seldon-core#2237]
Hello,

I'm trying to execute the operator manager with local logs, but can't find any option.
In the deprecated repo of operator I saw the manager had --log_dir parameter.
https://github.com/SeldonIO/seldon-operator

Is it a bug that someone remove this parameter? there have another option to find logs in local file?

**Comment by cliveseldon** [comment]
Have you tried https://github.com/SeldonIO/seldon-core/tree/master/operator#local-development-deploy

**Comment by MatanAmoyal** [comment]
thanks for your answer

I tried it but i have the same behavior.
"manager --help" doesn't show a flag related to log file/folder. only log level..

and also the container doesn't expose the shell (because the distroless) so how can I get the logs from the container?

**Comment by cliveseldon** [comment]
closing. Can you reopen if still an issue.
