### ISSUE TITLE
How to solve race conditions between two requests.

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#2240]
I'm use GRPC, and I have custom predictor with `.predict()` and `.metrics()` methods, and I use a list `.metrics_list` to store metrics for each request, i.e. calling `.predict()` would update `self.metrics_list`, which will then be returned by `.metrics()`. 

Relevant seldon code:

https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/seldon_methods.py#L93-L103

My code is something like

```
class MyPredictor:
    def metrics(self):
        return self.metrics_list

    def predict(self, features, names, meta=None):
        self.metrics_list = []
        self.metrics_list.append(calc_metrics())
        prediction = calc_prediction()
        return prediction
```

Here is the problem, suppose two requests come in very close. In particular, the second one comes in before the first one triggers the calling of `.metrics()`. So the orders of calls for the two requests is 

```.predict() -> .predict() -> .metrics() -> .metrics()```

I noticed the second request would pollute the value of `.latest_metrics` for the first request. What's the recommended way to work around this, please?

**Comment by cliveseldon** [comment]
@RafalSkolasinski

**Comment by RafalSkolasinski** [comment]
@zyxue Currently the best approach is to use `predict_raw`  in  which you can return prediction and metrics from the same function.

**Comment by RafalSkolasinski** [comment]
@zyxue I extended https://github.com/SeldonIO/seldon-core/issues/1735 to cover this use case. We will close this issue.
Thanks for reporting this!
