### ISSUE TITLE
isolated seldon deployments manging namespaces labeled with controllerId

### ISSUE THREAD

**Issue by michallula** [SeldonIO/seldon-core#2242]
I want to setup the following multi operator deployment in one k8s cluster:

- first seldon-core-operator is deployed in namespace seldon-prod and controlls namespace models-prod which has some particular label set
- second seldon-core-operator is deployed in namespace seldon-acc and controlls namespace models-acc
- third seldon-core-operator is deployed in namespace seldon-dev and controlls namespae models-dev

In that way we would like to separate development/acceptance model instances from the production one.
I've played a bit with seldon-core-operator helm chart and tried different combination of `singleNamespace` and `controllerId` flags. It occurred that current logic is as follow:
- if singleNamespace flag is not set (what means that no --namespace parameter is provided for seldon controller manager) all namespaces with seldon.io/controller-id label set are ignored
- SeldonDeployment label `seldon.io/controller-id` must much seldon controller manager container env variable `CONTROLLER_ID` value

I've tried to adjust helm chart webhook selectors to change objectSelector to namespaceSelector in case when controllerId is provided, but it occurred that selectors logic is duplicated inside controller code: https://github.com/SeldonIO/seldon-core/blob/master/operator/controllers/seldondeployment_controller.go#L1431
What whas a reason behind that?
Does it possible to achive my scenario somehow?

**Comment by michallula** [comment]
I have an impression that if I will remove filtering logic around https://github.com/SeldonIO/seldon-core/blob/master/operator/controllers/seldondeployment_controller.go#L1431 and rely on webhook selectors solely it could work. But maybe I'm not aware of something important

**Comment by cliveseldon** [comment]
Have you tried 3 namespace installs and validated they are isolated? maybe you can clarify a test case which shows where things don't work for you?

**Comment by michallula** [comment]
What I was able to achieve is something like that:

I have the following utilities scripts:

1. setup-seldon.sh
```bash
NAMESPACE=$1
CRDS=${2:-false}
CONTROLLER_ID=${3:-$NAMESPACE}

kubectl create namespace $NAMESPACE || echo "namespace $NAMESPACE exists"
kubectl label namespace $NAMESPACE seldon.io/controller-id=$CONTROLLER_ID

kubectl create namespace $NAMESPACE-deployments

helm upgrade \
    --install \
    --debug \
    --set ambassador.enabled=true \
    --set singleNamespace=false \
    --set controllerId=$CONTROLLER_ID \
    --set crd.create=$CRDS \
    --skip-crds \
    --namespace $NAMESPACE \
    --wait \
    --repo https://storage.googleapis.com/seldon-charts \
    --version 1.2.2 \
    seldon-core-operator seldon-core-operator
```

2. setup-ambassador.sh
```bash
NAMESPACE=${1:-ambassador}
PORT=${2:-8003}
CRDS=${3:-true}

helm repo add datawire https://www.getambassador.io
helm repo update

kubectl create namespace $NAMESPACE || echo "namespace $NAMESPACE exists"

helm upgrade \
    --install \
    --debug \
    --set image.repository=quay.io/datawire/ambassador \
    --set enableAES=false \
    --set crds.keep=$CRDS \
    --set crds.enabled=$CRDS \
    --set scope.singleNamespace=false \
    --skip-crds \
    --namespace $NAMESPACE \
    ambassador datawire/ambassador

kubectl rollout status deployment ambassador -n $NAMESPACE

kubectl port-forward $(kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=ambassador -o jsonpath='{.items[0].metadata.name}') -n $NAMESPACE $PORT:8080 &
```

3. deploy-model.sh
```bash
NAMESPACE=$1
MODEL_NAME=$2
CONTROLLER_ID=${3:-$NAMESPACE}
GRAPH=${5:-default}
NAME=${6:-classifier}

kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: $MODEL_NAME
  namespace: $NAMESPACE
  labels: 
    seldon.io/controller-id: "$CONTROLLER_ID"
spec:
  name: iris
  predictors:
  - graph:
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/sklearn/iris
      name: $NAME
    name: $GRAPH
    replicas: 1
END

kubectl rollout status deployment $MODEL_NAME-$GRAPH-0-$NAME -n $NAMESPACE
```

4. setup.sh
```bash
#!/usr/bin/env bash

./setup-seldon.sh seldon-prod true
./setup-seldon.sh seldon-acc
./setup-seldon.sh seldon-dev

./setup-ambassador.sh ambassador

./deploy-model.sh seldon-prod-deployments test-01 seldon-prod
./deploy-model.sh seldon-prod-deployments test-02 seldon-acc
./deploy-model.sh seldon-prod-deployments test-03 seldon-dev
./deploy-model.sh seldon-acc-deployments test-04 seldon-prod
./deploy-model.sh seldon-acc-deployments test-05 seldon-acc
./deploy-model.sh seldon-acc-deployments test-06 seldon-dev
./deploy-model.sh seldon-dev-deployments test-07 seldon-prod
./deploy-model.sh seldon-dev-deployments test-08 seldon-acc
./deploy-model.sh seldon-dev-deployments test-09 seldon-dev
```

When I invoke:

```bash
minikube start --kubernetes-version v1.17.0

./setup.sh
```
All `SeldonDeployments` are served correctly. Each `SeldonDeployment` is handled by seldon-core-operator identified by label `seldon.io/controller-id` value, so all three operators deployed exactly one SeldonDeployment in each namespace.

What I would like to achieve is to force only one seldon-core-operator to serve all SeldonDeployments from particular namespace (for example `seldon-prod` should govern `seldon-prod-deployments` namespace) and prevent other operators to be able to serve SeldonDeployment from this namespace, regardles what is set in SeldonDeployment labels.

**Comment by cliveseldon** [comment]
closing. Can you reopen if still an issue.
