### ISSUE TITLE
Add additional labels to resources created by Operator

### ISSUE THREAD

**Issue by mwm5945** [SeldonIO/seldon-core#2246]
The operator should add additional labels to resources created for a seldondeployment. For Example--if the SDEP name is too long, the deployment name becomes `seldon-<long string of characters>`, but this makes it harder to search for resources like HPAs based on the model name. 

https://github.com/SeldonIO/seldon-core/blob/0f3dd84e0db31b662492af0895c6c7bb91f87bdc/operator/controllers/seldondeployment_controller.go#L119

**Comment by cliveseldon** [comment]
I think this is fixed to allow custom names. Please reopen if still an issue.
