### ISSUE TITLE
strData & binData not accepted by Python model microservice

### ISSUE THREAD

**Issue by sasvaritoni** [SeldonIO/seldon-core#225]
Hello,

Model rest microservice generated from Python models only accept DefaultData ("data") for /predict.
strData or binData are not accepted.

According to [https://github.com/SeldonIO/seldon-core/blob/master/docs/reference/prediction.md/#proto-buffer-and-grpc-definition  ](https://github.com/SeldonIO/seldon-core/blob/master/docs/reference/prediction.md/#proto-buffer-and-grpc-definition ) strData & binData should also be accepted, and e.g. the Java wrapped model does accept them as expected.

**Comment by cliveseldon** [comment]
Certainly something we should try to fix to allow this path through the API. We will look into it.
