### ISSUE TITLE
Is it possible to pass init parameters to Predictor class through seldon-core-microservice

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#2250]
my custom model is like:

```
class MyPredictor:
    def __init__(self, model_path):
        self._model = load(model_path)

    def predict(self, features, names, meta=None):
        transformed = transform(features)
        prediction = calc_prediction(transformed)
        return prediction
```

I wonder if there is a way to pass value to `model_path` through `seldon-core-microservice`?

Went throught the source code, https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L212-L296, there doesn't seem to be one. Am I missing some thing or is there another way to do something like this?

**Comment by cliveseldon** [comment]
Are you looking for https://docs.seldon.io/projects/seldon-core/en/latest/python/python_wrapping_s2i.html#model-class-arguments

**Comment by zyxue** [comment]
yes, this is what I'm looking for

* https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L222-L224, 
* https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L68-L114

I didn't fully get how `--parameters` is used, now it makes sense.
