### ISSUE TITLE
Add Support for RAPIDS.ai FIL

### ISSUE THREAD

**Issue by datametrician** [SeldonIO/seldon-core#2253]
FIL
https://medium.com/rapids-ai/rapids-forest-inference-library-prediction-at-100-million-rows-per-second-19558890bc35
https://medium.com/rapids-ai/sparse-forests-with-fil-ffbb42b0c7e3
From RAPIDS.ai is a GPU accelerated inference library for all tree models, SKL RF/GBM, RAPIDS RF, DMLC XGBoost, etc...

It would be great if you add support for this.

**Comment by ryandawsonuk** [comment]
Have added to next community call - https://docs.seldon.io/projects/seldon-core/en/latest/developer/community.html?highlight=community#working-group-calls

**Comment by datametrician** [comment]
Thanks @ryandawsonuk

**Comment by cliveseldon** [comment]
Rapid FIL is available in Triton
