### ISSUE TITLE
Create wrapper for R models

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#23]
* expose R models with a thin REST server or gRPC server that respects the [internal model API](https://github.com/SeldonIO/seldon-core/blob/master/docs/reference/internal-api.md#model)
 
 * Build Docker image

**Comment by Maximophone** [comment]
Use the python wrapper https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/python.md as a reference

**Comment by gipster** [comment]
I think it's worth investigating OpenCpu for that
https://www.opencpu.org 
https://www.r-bloggers.com/announcing-opencpu-2-0-building-and-deploying-scalable-r-apps-and-services/
