### ISSUE TITLE
Make deployment names configurable

### ISSUE THREAD

**Issue by hmonteiro** [SeldonIO/seldon-core#2301]
At the moment, as per [here](https://docs.seldon.io/projects/seldon-core/en/latest/reference/upgrading.html#deployment-naming-and-rolling-updates), the deployment names will be of the form `<seldondeployment name>-<predictor name>-<podspec idx>-<container names>` but only when that results in a string are smaller than a certain size. Because the container names are included, it is very easy to produce a graph that goes over the limit and, in that situation, we get a deployment name of `seldon-<hash>`. Since I foresee this to be a common problem, it would be very useful if we could specify our own prefix per deployment, so that, if that prefix is given, than the deployment name will be `<prefix>-<same hash as before>`, even when the original string was short enough so that we can produce predictable identifiers.

This would be very useful to make sure that a human can still distinguish between deployments when looking at the cluster.

**Comment by cliveseldon** [comment]
Could we use some parts of the deployment name. Would this acceptable?

**Comment by hmonteiro** [comment]
Since most of the problem lies in the fact that the name includes all the containers, it might be enough that, when that is too much, you first try to hash them so the name would become `<seldondeployment name>-<predictor name>-<hash>` for example, before you go straight to hashing everything.
