### ISSUE TITLE
[doc] where is "seldon wrappers guideline"?

### ISSUE THREAD

**Issue by sakaia** [SeldonIO/seldon-core#2307]
Where is "seldon wrappers guideline"?

In [examples/README.md](https://github.com/SeldonIO/seldon-core/blob/master/examples/README.md), it refers "seldon wrappers guideline" but this link is broken.

**Comment by adriangonz** [comment]
The main docs should cover that. In particular, you may find the quickstart guide useful: https://docs.seldon.io/projects/seldon-core/en/latest/workflow/github-readme.html
