### ISSUE TITLE
[examples] models/sk_mnist does not work on current code

### ISSUE THREAD

**Issue by sakaia** [SeldonIO/seldon-core#2319]
## Describe the bug

The models/sk_mnist does not work on the seldon-core example.
with
- scikit-learn 0.23.1
- joblib 0.14.1

I run it with following code. Hopefully this kind of code will be applied.

```python3
diff --git a/examples/models/sk_mnist/requirements.txt b/examples/models/sk_mnist/requirements.txt
index 3393557ca..f13cddc44 100644
--- a/examples/models/sk_mnist/requirements.txt
+++ b/examples/models/sk_mnist/requirements.txt
@@ -1,2 +1,3 @@
 scipy>= 0.13.3
 scikit-learn>=0.18
+tensorflow>=1.12.0,<2.0
diff --git a/examples/models/sk_mnist/train.py b/examples/models/sk_mnist/train.py
index 066b27765..919408d2c 100644
--- a/examples/models/sk_mnist/train.py
+++ b/examples/models/sk_mnist/train.py
@@ -1,8 +1,8 @@
 from sklearn.ensemble import RandomForestClassifier
 from sklearn import datasets, metrics
 from sklearn.utils import shuffle
-from sklearn.datasets import fetch_mldata
-from sklearn.externals import joblib
+from sklearn.datasets import fetch_openml
+import joblib

 from tensorflow.examples.tutorials.mnist import input_data
 mnist = input_data.read_data_sets("MNIST_data/")
```
## To reproduce

```bash
cd examples/models/sk_mnist
python3 train.py
```

## Expected behaviour
`python3 train.py` works fine!

## Environment
currently running on ubuntu 19.10 

Alternatively run `echo "#### Kubernetes version:\n $(kubectl version) \n\n#### Seldon Images:\n$(kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio)"`
-->

## Model Details 
This is example code issue. I skip this.

**Comment by cliveseldon** [comment]
Can you clarify the error you are seeing?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue on 1.12?
