### ISSUE TITLE
Enable Request-Response pair logging for a gRPC request

### ISSUE THREAD

**Issue by roshanzameer** [SeldonIO/seldon-core#2326]
Current Setup:
The [seldon-request-logger](https://github.com/SeldonIO/seldon-core/blob/master/examples/centralised-logging/seldon-request-logger.yaml) which fetches logs from the Knative data-broker and indexes to Elasticsearch, does so only for a request made via REST protocol. 

Feature Request:
The Seldon-request-logger should perform request-response logging also for a Model that has a gRPC endpoint and for a request made via the gRPC protocol.

**Comment by cliveseldon** [comment]
@ryandawsonuk to quantify work to fix

**Comment by ryandawsonuk** [comment]
We have a function to convert a [serialized SeldonMessage to numpy](https://github.com/SeldonIO/seldon-core/blob/a061624f38ef8619ecde58eefeb0cc295dba8060/python/seldon_core/utils.py#L189). Currently the logger assumes that it [will receive json](https://github.com/SeldonIO/seldon-core/blob/master/components/seldon-request-logger/app/default_logger.py#L56). I think in a GRPC case the logger would [receive a CloudEvent](https://github.com/SeldonIO/seldon-core/blob/master/executor/logger/worker.go#L92) with a grpc-encoded body containing a SeldonMessage. So presumably we could detect that it were GRPC and deserialize (am assuming we don't need an extra header for this). And could test this out with https://github.com/SeldonIO/seldon-core/blob/e84f7103315a13ddc5ce76ede2c22471a2ed8074/notebooks/protocol_examples.ipynb

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue with latest Seldon Core. If so we can look into it for V2 APIs
