### ISSUE TITLE
Inference Graph Example

### ISSUE THREAD

**Issue by akshatgit** [SeldonIO/seldon-core#2331]
Hi Seldon Core Team,

I deploy a model currently using seldon core, which is using a simple model. But our requirements have changed and I would like to know if I can use different components to combine to run the new model. However, I was unable to get a simple tutorial where all components of the microservice API is used. 
Ideally, I would like a tutorial where all [internal microservice API](https://docs.seldon.io/projects/seldon-core/en/v1.0.0/reference/apis/internal-api.html#internal-microservice-api) is used in an inference graph. If any tutorial is missed, please point me in the right direction.

Thanks

**Comment by cliveseldon** [comment]
We have various more complex examples for example:
https://docs.seldon.io/projects/seldon-core/en/latest/examples/openvino_ensemble.html
and
https://docs.seldon.io/projects/seldon-core/en/latest/analytics/routers.html

it would be great to understand your requirements so we can work on an appropriate example.

**Comment by akshatgit** [comment]
Hi @cliveseldon 

I have a 1000x1000x3 image, for which I have to do a certain prediction. Now my model takes in 100x100x3 as input and right now I cut 100 such blocks from an image and send them sequentially. But now I would like to use a transformer, which would take the image as input, make 100 such blocks, feed it into the model, and an out_transformer that would combine the outputs. This would remove the overhead of slicing the image from the application. If possible, I would like to send the blocks to say 10 models parallelly and combine them in out_transformer. 

Does this approach make sense or is it completely out of context for seldon microservice APIs?

Thanks

**Comment by akshatgit** [comment]
In [this](https://docs.seldon.io/projects/seldon-core/en/latest/examples/openvino_ensemble.html) I cannot find the code/dockerfile for creating the transformer block. 

Also, can we show seldon_ov_predict_ensemble.json and seldon_grpc_client.py on the page? It would be more helpful.

**Comment by akshatgit** [comment]
Even a small verbose example of how to create a pipeline with all dockerfile, python class, and Kube config would be very helpful.

**Comment by cliveseldon** [comment]
You will find the code at https://github.com/SeldonIO/seldon-core/tree/master/examples/models/openvino_imagenet_ensemble/resources for the open vino graph nodes

**Comment by akshatgit** [comment]
Got it. Thanks a lot. Feel free to close the issue.
