### ISSUE TITLE
Multi_Archtecture Support

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#2333]
Initial ideas in https://github.com/SeldonIO/seldon-core/pull/1852

Please comment here if this is important to you

**Comment by malarinv** [comment]
@cliveseldon is multi architecture supported by seldon-core now?

**Comment by cliveseldon** [comment]
No - its not clear the implications on exactly what would need to be carried out to support a different underlying architecture. In theory I assume cross compiling to say ARM the executor and operator are initial steps. But then all servers would need to be also converted which also includes external ones such as Triton Server and TFServing.

Can you discuss your use case? @malarinv

**Comment by malarinv** [comment]
> No - its not clear the implications on exactly what would need to be carried out to support a different underlying architecture. In theory I assume cross compiling to say ARM the executor and operator are initial steps. But then all servers would need to be also converted which also includes external ones such as Triton Server and TFServing.

but Triton Server already supports jetson(arm) targets as documented at https://github.com/triton-inference-server/server/releases/tag/v2.11.0
> 
> Can you discuss your use case? @malarinv 

I'm trying to build a cluster of embedded jetson nodes. was hoping seldon-core might help here.
