### ISSUE TITLE
Upgrading Jenkins X cluster from 2.x to 3.x

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2348]
Currently looking to upgrade the Jenkins X CI cluster from 2.x to 3.x since there seem to be a lot of improvements in [workflows and stability](https://jenkins-x.io/docs/v3/about/comparison/). Currently waiting for confirmation on resources for migration https://github.com/jenkins-x/jx/issues/7550

**Comment by cliveseldon** [comment]
On going Jenkins work so closing
