### ISSUE TITLE
Seldon pipeline crashes when there are a high volume of requests

### ISSUE THREAD

**Issue by tonykchen-pge** [SeldonIO/seldon-core#2358]
## Describe the bug
We started using Locust to load test a pipelines and noticed a lot of `5xx` errors being returned to the client. We monitored the containers in the pod and discovered the model container reaches its limit of `15Gi` and is eventually killed due to OOM. We noticed that memory isn’t being released properly, even when the load tests have stopped.

## To reproduce

This issue is observed in PyTorch computer vision models (object detection) and complex Sklearn pipelines which have been serialized with `joblib`.

These models are wrapped using the Python wrapper.

Locust configs:

* Number of users: 25
* Hatch rate: 1 user per second

We ran similar tests on a simple Sklearn pipeline (Iris classification), but received zero errors after 70k requests. The memory was also much more stable compared to the complex models described above.

## Expected behaviour

Memory should be released properly in container which serves the model. The container currently crashes with OOM errors, even when we set the memory limit to a very high and unreasonable limits like `15Gi`.

## Environment

* Seldon 1.1.0
* Components are served using Flask

**Comment by tonykchen-pge** [comment]
I'm planning on deploying one of the models using gunicorn to see if it makes a difference.

**Comment by axsaucedo** [comment]
@tonykchen-pge given that you are running a PyTorch model, we have seen similar behaviour as it seems some libraries such as this one don't scale well with multithreading. You are also using an older version of Seldon which runs with flask on single worker by default (and gunicorn when workers are set to more than 1) - the flask only server is not recommended given that it creates a thread every request that comes in, which is probably what is causing your issue.

In these cases we recommend to running the Seldon server with as SINGLE THREADED, and if you want to scale  you should use the GUNICORN_WORKERS or the deployed model replicas instead. 

Here is documentation https://docs.seldon.io/projects/seldon-core/en/latest/python/python_server.html?highlight=gunicorn_workers#workers, however it seems you're running an older version so you will have to set the FLASK flags as the old version runs with flask (I believe the env var is something like FLASK_SINGLE_THREADED, but it would be worth double checking. Once you try this we recommend you to upgrade as in the current version of Seldon it runs with gunicorn by default. If you do upgrade make sure you follow the UPGRADING.md page.

Can you try this single threaded suggesting and confirm?

**Comment by cliveseldon** [comment]
Please reopen if the above answer doesn't solve.

**Comment by tonykchen-pge** [comment]
@axsaucedo @cliveseldon We enabled Gunicorn for our components and they're now working beautifully! No more pipeline crashes when there is heavy load. 

Thank you so much for your help! 🙏

**Comment by cliveseldon** [comment]
@tonykchen-pge great!
