### ISSUE TITLE
Support YAML for SeldonDeployment definition in examples under seldon-core/helm-charts 

### ISSUE THREAD

**Issue by ramanNarasimhan77** [SeldonIO/seldon-core#2362]
Hello,

I am trying to customise and reuse the model deployment helm charts available under [seldon-core/helm-charts](https://github.com/SeldonIO/seldon-core/tree/master/helm-charts) for deploying the ml models that my team is building.
Our generic ci process lints every helm chart before uploading to our internal registry. Helm linting does not work with json.
Is there a way I can easily redefine helm charts like [seldon-single-model](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-single-model/templates/seldondeployment.json) to use yaml instead of json 

### Steps in CI process for uploading a helm chart to Helm registry:
1. Update Chart version in Chart.yaml
2. Update dependencies `helm dep up $CHART`
3. Lint helm chart `helm lint $CHART`
4. Package the helm chart `helm package -d . $CHART`
5. Push packaged chart to internal helm registry

### Error observed on running lint command:
```
Linting error:
$ helm lint seldon-single-model
==> Linting seldon-single-model
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/seldondeployment.json: file extension '.json' not valid. Valid extensions are .yaml, .yml, .tpl, or .txt
```

**Comment by ellisvalentiner** [comment]
@ramanNarasimhan77 you can just change the extension to `.yaml` and it will work fine because JSON is valid YAML.

**Comment by ramanNarasimhan77** [comment]
@ellisvalentiner  thank you for the suggestion. I will try this out

**Comment by cliveseldon** [comment]
You could raise a PR to change to yaml or push Helm to accept JSON for `lint`
