### ISSUE TITLE
semverComapre broken in some kubernetes flavours resulting in CRDs not being installed

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2367]
semverCompare breaks in kubernetes flavours that don't have the exact versioning convention when running `kubectl version`. This results in the CRDs not being created. An example is when a kubernetes version has a prefix of "v1.18" for example. We should explore a way to override the semver by passing it to the helm chart as something like --set semverOverride=1.17.0

**Comment by cliveseldon** [comment]
Is this a helm issue with that function? Also which type of clusters?

**Comment by axsaucedo** [comment]
Yeah it's it's a helm only issue - the problem seems to happen as the `kubectl version` seems to use node image tag as the reference to the version, so if it's using something that is not standard it would error out. I found out it's a semi-common issue when searching for the issue and finding a few projects seem to have open issues wiht strange naming convention for the version number. I would've assumed there would be a solution for this on the helm side tho...

**Comment by axsaucedo** [comment]
Here's one of those corner case examples https://github.com/helm/charts/issues/4953

It seems like it's strange enough that we can just rely on this for most cases, but it would still be required to provide some way to override. It seems that the CRD doesn't install otherwise (which would not be very intuitive until they look at that if statement). Maybe if it's an if/else as opposed to an if/if (atm it's set up with the latter), at least it would produce an explicit error. What do you think?

**Comment by cliveseldon** [comment]
helm/charts#4953 is not clear its an issue and there is an edit that maybe its not https://github.com/helm/charts/issues/4953#issuecomment-385678077 
I
