### ISSUE TITLE
where is tfserving-mnist chart?

### ISSUE THREAD

**Issue by sakaia** [SeldonIO/seldon-core#2372]
## Describe the bug
I cannot found tfserving-mnist chart. Where is tfserving-mnist chart?

```
helm install tfserving-mnist tfserving-mnist --namespace seldon --set tfserving.model_base_path=${MODEL_REPOSITORY_BUCKET}/mnist-model
```

https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/tfserving_mnist.html#Run-MNIST-Inference-Graph

## To reproduce

```
helm install tfserving-mnist tfserving-mnist --namespace seldon --set tfserving.model_base_path=${MODEL_REPOSITORY_BUCKET}/mnist-model
```
Error message is follows.

```
Error: failed to download "tfserving-mnist" (hint: running `helm repo update` may help)
```

## Expected behaviour
`helm install tfserving-mnist` works fine. 

## Environment
I install with `sudo snap install helm --classic`

**Comment by cliveseldon** [comment]
That chart is in the example folder https://github.com/SeldonIO/seldon-core/tree/735a97b1c4df79001975a4af855b673167cfb5a0/examples/models/tfserving-mnist
You would need to run from there.

**Comment by sakaia** [comment]
Thank you. I learned helm command argument and pass it.
