### ISSUE TITLE
Support traffic distribute by request content

### ISSUE THREAD

**Issue by simon-cj** [SeldonIO/seldon-core#2379]
Now seldon core support traffic distribute by weight，but not support by content, eg: distribute by http Header.
in some case, it need to canny feature  in online service, so suggest it that seldon core can support traffic distribute by request content.

**Comment by cliveseldon** [comment]
We could add this to the CRD but you can presently write your own Router to check the content/header and decide which child model to go to next.

**Comment by simon-cj** [comment]
Yes, we think so, we will write proposal to seldon community, hope that the community will be reviewed at that time.

**Comment by cliveseldon** [comment]
Will will support this in V2 APIs which will be agnostic to service mesh so you can use istio or whatever to split traffic. This is also possible now if you run AB tests at the istio level.

**Comment by cliveseldon** [comment]
Can you retry this with the [v2 APIs](https://docs.seldon.io/projects/seldon-core/en/v2/)
