### ISSUE TITLE
Using ArgoCD to deploy Seldon-core-operator shows Webhooks as OutOfSync

### ISSUE THREAD

**Issue by ramanNarasimhan77** [SeldonIO/seldon-core#2392]
Hello,
I am attempting to use ArgoCD to deploy Seldon-core-operator as part of our cluster bootstrap using GitOps.

The deployed manifest contains additional `namespaceSelectors` probably injected by the `seldon controller` after  deployment; causing argoCD to think that manifest is not in sync as explained in this issue  - https://github.com/argoproj/argo-cd/issues/4276

<img width="1229" alt="Screenshot 2020-09-07 at 12 16 59 PM" src="https://user-images.githubusercontent.com/52691361/92360465-78fc7780-f10a-11ea-9c68-207977fd00eb.png">

I have added `ignoreDifferences` spec for the json path `/webhooks/0/namespaceSelector/matchExpressions/1` so that argoCD does not report it as `OutOfSync` but this does not seem to resolve the differences

Can you please guide in fixing this issue?

**Comment by cliveseldon** [comment]
We don't add this namespaceSelector. What environ are you running in?

**Comment by cliveseldon** [comment]
Are you deploying the operator in namespace mode or with id?

**Comment by ramanNarasimhan77** [comment]
Hi @cliveseldon 

I am not setting the `controllerid` while deploying the operator

I am installing `ambassador` first and then `seldon-core-operator`. I have done this deployment using `argocd` on a `azure aks` cluster

I can see that on `onprem k8s clusters` this extra namespace selector does not get added. Hence this must be something to do with `aks`

References:
1. https://docs.microsoft.com/en-us/azure/aks/faq#can-i-use-admission-controller-webhooks-on-aks
2. https://github.com/Azure/AKS/issues/1771

**Comment by cliveseldon** [comment]
ok so the docs explain why the extra term is added to the webhook: https://docs.microsoft.com/en-us/azure/aks/faq#can-i-use-admission-controller-webhooks-on-aks
So maybe this is a question for ArgoCD community?

**Comment by ramanNarasimhan77** [comment]
Thanks @cliveseldon, I'll follow up with argocd community
