### ISSUE TITLE
Determine during .predict() or .transform() which models to call

### ISSUE THREAD

**Issue by pietermarsman** [SeldonIO/seldon-core#2410]
Hi there! I am consideren Seldon to deploy two ai models that are related. I want to use the output of the first model to determine the input for the second model. In other words, I want to be able to determine during the `.predict()` or `.transform()` method of a parent model if, and how many times, a child model should be called. Is it possible to implement this with Seldon?

**Context**

I have two deep learning models for image processing. The first does instance segmentation and returns a list of polygons. The second is a classification model. I want to apply the classification model for each of the instance polygons. 

I want to use the Python language wrapper for this. 

**Alternatives**

- I've considered using a `Router` for this.
    - But (as far as I understood) a router only gets information from the request to make its decision.
    - Also a `Router` does not do "for each" behavior. It redirects the request to one model. 
- I've considered using a `Transformer` for this. With this setup, the classification would "transform" the output of the segmentation model and add extra info to each polygon.
    - This does scale well if there are many polygons on an image. E.g. if there are 100 polygons I want to be able to dispatch 100 requests to the classification model and let seldon/kubernetes handle the scaling of the classification model. 
    - Also this solution does not allow to use the classification model without the segmentation model. E.g. just classify an image. 
- I've considered using a custom kubernetes container for this
    - Does not use the power of seldon

**Related issues**

- https://github.com/SeldonIO/seldon-core/issues/256: limitations of current graph components

**Comment by cliveseldon** [comment]
We will want to support this is v2 APIs we are investigating but you can presently do this with [Tempo](https://github.com/SeldonIO/tempo)

**Comment by cliveseldon** [comment]
Please test in v2
