### ISSUE TITLE
Install seldon-core-operator only working with old version

### ISSUE THREAD

**Issue by PhilipMay** [SeldonIO/seldon-core#2438]
* minikube `v1.13.0` installed with a k8s `GitVersion:"v1.19.1"` running
* I try to install `seldon-core-operator` like the guide sais.
* I created the namespace: `kubectl create namespace seldon-system`
* when doing this:

```bash
helm install seldon-core seldon-core-operator \
    --repo https://storage.googleapis.com/seldon-charts \
    --set usageMetrics.enabled=true \
    --namespace seldon-system \
    --set istio.enabled=true
```

This happens:
```
Error: failed to create resource: CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

When doing this with `--version 0.5.0` (and then with `--replace`) it works.

PS: Version `1.0.2` also works. Higher version does not work.

How does this come? Do I have the wrong minikube version?

**Comment by cliveseldon** [comment]
The 1.2.x version of Seldon Core runs on k8s <1.18 >= 1.12
The master version for 1.3 release will run on k8s >= 1.18
So you'll need to downgrade to lower version of k8s on minikube or use master helm chart.

**Comment by PhilipMay** [comment]
@cliveseldon thanks for the super quick answer.
I did not find this info on the docu pages or the release info.
Maybe you want to add it (or maybe I am blind)...

Thanks
Philip

**Comment by PhilipMay** [comment]
The newest version of `seldon-core-operator` is `1.2.3` when you look into https://storage.googleapis.com/seldon-charts
Which k8s version does that need?

**Comment by cliveseldon** [comment]
>= 1.12 <1.18 see https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#pre-requisites

**Comment by PhilipMay** [comment]
> > = 1.12 <1.18 see https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#pre-requisites

https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#pre-requisites sais:

> Kubernetes cluster version equal or higher than 1.12

And **not** <1.18 or so.
