### ISSUE TITLE
Question about running grafana-prom for examples/kubeflow

### ISSUE THREAD

**Issue by sakaia** [SeldonIO/seldon-core#2440]
I would be appreciate if the setup instruction of `grafana-prom` is given for kubeflow namespace.
I am try to run the examples/kubeflow on onprem.

Then, I am digging into the `grafana-prom` boot code, But I found boot code only for default name space.[/grafana-deployment.json](https://github.com/SeldonIO/seldon-core/blob/v1.2.3/monitoring/grafana/grafana-deployment.json#L50)

[6) Visualise Seldon's Production ML Pipelines](https://github.com/SeldonIO/seldon-core/tree/master/examples/kubeflow#6-visualise-seldons-production-ml-pipelines)

**Comment by adriangonz** [comment]
/label triage

Hey @sakaia, wouldn't it be possible to just change the namespace before applying them to the cluster?

**Comment by cliveseldon** [comment]
Please reopen if still an issue
