### ISSUE TITLE
Confusion on method_raw() methods 

### ISSUE THREAD

**Issue by ntorba** [SeldonIO/seldon-core#2473]
Hello, 

I have a quick questions regarding the _raw() functions (eg: predict_raw(), transform_input_raw(), etc.). 

It seems that the functions do support the return of dictionaries, but the structure these dictionaries require is not clear in the documentation. Based on the `handle_raw_custom_metrics()` call in `predict_raw()` in [seldon_methods.py](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/seldon_methods.py), it is required that the return from this function is a dictionary with a "meta" key, that has a corresponding value of type dictionary. 
However, in the [python component docs](https://docs.seldon.io/projects/seldon-core/en/v1.1.0/python/python_component.html), the function definitions show the return value is prediction_pb2.SeldonMessage, like `def predict_raw(self, msg: prediction_pb2.SeldonMessage) -> prediction_pb2.SeldonMessage: `.

Am I missing something in the docs that says where the dictionary return value is allowed and what the structure should be? 
Also, it seems like the handle_raw_custom_metrics() function in seldon_methods.py could be updated to allow the user to not include the "meta" key in the return value. 

I put this in as a feature request instead of bug report because the code does work, it just seems like I am missing where the docs for how _raw() functions work. 

Please let me know if I am missing something here. Thanks!

**Comment by cliveseldon** [comment]
related to #2497

**Comment by cliveseldon** [comment]
Let's spec out the consequences of protocol enforcement or not. @RafalSkolasinski

**Comment by cliveseldon** [comment]
[MLServer](https://github.com/SeldonIO/mlserver) is investigating multiple protocols. But we also want to support external protocols to transformations in V2 APIs. You can also look at using [Tempo](https://github.com/SeldonIO/tempo) for this.

**Comment by cliveseldon** [comment]
Closing for now - please migrate to v2 protocol
