### ISSUE TITLE
Support seldon-core running on knative serving like kfserving

### ISSUE THREAD

**Issue by heluocs** [SeldonIO/seldon-core#2476]
The request based autoscaling like concurrency、rps and serverless ability of knative serving is very useful in many scenario。so if seldon-core will support running on knative serving like nvidia triton https://github.com/kubeflow/kfserving/tree/master/docs/samples/triton ?

**Comment by cliveseldon** [comment]
There are a few answers:

 * Now in 1.3 we have begin support for KFServing protocol: https://docs.seldon.io/projects/seldon-core/en/latest/graph/protocols.html#v2-kfserving-protocol So this gives you options in future to use both as needed with same API
     * We support triton in this: https://docs.seldon.io/projects/seldon-core/en/latest/servers/triton.html
 * We are also investigating KEDA via https://github.com/SeldonIO/seldon-core/issues/2498

I'll close this for now.
