### ISSUE TITLE
ndarray greater than 15280 bytes

### ISSUE THREAD

**Issue by sathiez** [SeldonIO/seldon-core#248]
Hi,
I am unable to send ndarray greater than 15280 bytes.

**Comment by cliveseldon** [comment]
Is this for gRPC or REST?

**Comment by sathiez** [comment]
REST

**Comment by cliveseldon** [comment]
Can you show the error and stack trace you are seeing from either the engine (service orchestrator) or your wrapped model?

**Comment by sathiez** [comment]
Hi,
Actually, if I send a ndarray with 19000 values, I am able to get a response/messag. For any array size more than 19000, I get no response/message. I don't get any error either.

**Comment by sathiez** [comment]
My request is 
**{"data":{"ndarray":'+str(img_array.tolist())+'}}**

**Comment by cliveseldon** [comment]
What http code do you get back, 500. Does it say anything in it?
Can you check the logs of all the docker images running your graph to check for errors?

**Comment by sathiez** [comment]
Hi,
I didn't get any error message even nothing is displayed in log. Does REST have any size limit?

**Comment by sathiez** [comment]
No I didn't set any timeout.
Yes I am using ambassador API Gateway

**Comment by cliveseldon** [comment]
With Ambassador you should get a timeout if the request takes more than 3secs by default.

**Comment by sathiez** [comment]
Even I am unable to receive ndarray in seldon api. But If I send a minimum number of arrays I can able to get the output  properly.

**Comment by sathiez** [comment]
when I use curl and send the request I get **"32152"** . What does it mean?

**Comment by cliveseldon** [comment]
You'll need to give more detail on the full response.

**Comment by sathiez** [comment]
req.py
import cv2
import os
img_array = cv2.imread('imgpath')
os.system('curl  -H "Content-Type: application/json" -d \'{"data":{"ndarray":'+str(img.tolist())+'}}\' http://localhost:8080/seldon/model/api/v0.1/predictions')


It doesnt give any error message or response/http message.
when i print(os.system(curl........)) it returned only 32512.
