### ISSUE TITLE
Add selectorpath for /scale subresource in SeldonDeployment CRD

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#2485]
Right now in the seldon crd definition: https://github.com/SeldonIO/seldon-core/blob/master/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L443

It looks like `selectorpath` is missing, we can add that according to kubebuilder annotation: https://book.kubebuilder.io/reference/markers/crd.html

And this [must be set to work with HPA.](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource)

Can we add that to make seldon CR work with HPA ? Thanks!

**Comment by cliveseldon** [comment]
Can you create a PR for this?

**Comment by anggao** [comment]
> Can you create a PR for this?

Sure I will do!

**Comment by anggao** [comment]
@cliveseldon any suggestions on what JSONPath I should use for it, since Seldon supports multiple deployment per one SeldonDeployment ? I can use the selector created for the svc, but not sure that's the best to use

**Comment by cliveseldon** [comment]
Actually this is the reason we did not add it originally as the the HPAs can be created for each underlying deployment so there is no single selector that can be provided.

**Comment by anggao** [comment]
Hum...what about add KEDA support as part of seldon-core, e.g. extend the hpa section in the CRD to support KEDA and let the operator create KEDA object instead when KEDA hpa is used ? 
I think this will also help solve a similar request https://github.com/SeldonIO/seldon-core/issues/2406

**Comment by anggao** [comment]
@cliveseldon thoughts or suggestions on this ?
e.g. we can add KedaSpec similar to the HpaSpec here: https://github.com/SeldonIO/seldon-core/blob/master/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L287

**Comment by cliveseldon** [comment]
OK So we could extend the CRD to include a ScaledObject spec in the SeldonPodSpec, e.g.

```Go
type SeldonPodSpec struct {
	Metadata metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	Spec     v1.PodSpec        `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
	HpaSpec  *SeldonHpaSpec    `json:"hpaSpec,omitempty" protobuf:"bytes,3,opt,name=hpaSpec"`
	Replicas *int32            `json:"replicas,omitempty" protobuf:"bytes,4,opt,name=replicas"`
        KedaSpec *keda.ScaledObject.Spec
}
```

If set with a 1 of N semantic w.r.t. the HpaSpec we would create the ScaledObject filling in the deployment reference?

**Comment by anggao** [comment]
Yes, I think that's make sense, and it will be an extension for the HpaSpec, and users can optionally to use it if they have KEDA installed in the cluster.

**Comment by anggao** [comment]
@cliveseldon I can work on this if you think this is a reasonable addon for seldon-core

**Comment by cliveseldon** [comment]
Yes that would be great.

**Comment by anggao** [comment]
Cool, I will work on this and send a PR when it's ready for review

**Comment by anggao** [comment]
close this issue now and track the progress in https://github.com/SeldonIO/seldon-core/issues/2498
