### ISSUE TITLE
Explore adding support for arbitrary protocols in Seldon Core

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#2497]
The introduction of the executor started to add support for new protocols other than Seldon Core's default protocol. By protocol here we refer to either differences in payload shape, differences in the endpoint's path or both. Out of the box, the executor now supports Tensorflow's and the V2 Dataplane protocol alongside Seldon Core's standard one. 

It would be interesting to extend this to allow users to define arbitrary protocols. Custom protocols would also need to be taken into for other components downstream (e.g. virtual service generation, request logger, gRPC support, etc.).

**Comment by cliveseldon** [comment]
Closing as we would probably only allow an initial protocol to a transformation step
