### ISSUE TITLE
Add KEDA support for seldon-core

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#2498]
According to discussion in https://github.com/SeldonIO/seldon-core/issues/2485
[KEDA ](https://keda.sh/) could be a good addon for seldon-core, and this ticket is used to track the work for it.

**Comment by anggao** [comment]
@cliveseldon FYI and I will track the work with this issue

**Comment by cliveseldon** [comment]
@anggao Can you discuss the scenarios you plan to use KEDA in w.r.t to the SeldonDeployment rpc model
I'd be interested to understand the metrics you plan to use to scale.

**Comment by anggao** [comment]
@cliveseldon we plan to use KEDA to further automate our deployment process. e.g. our internal tool can provide estimated cpu/memory usage, and throughput a model instance can handle. With KEDA it will help add the missing HPA part, we'd like to scale the model based on rps to the model, also in the future scale based on queue size would be of interest to offline  training.
