### ISSUE TITLE
[example] link to  `setup cluster` is broken in autoscale example

### ISSUE THREAD

**Issue by sakaia** [SeldonIO/seldon-core#2503]
In following example, the link to setup cluster is broken.

above document goes to follow, but it does not exist. below url says

```
Unknown type
```
- [https://render.githubusercontent.com/notebooks/seldon_core_setup.ipynb#Setup-Cluster](https://render.githubusercontent.com/notebooks/seldon_core_setup.ipynb#Setup-Cluster)

It seems following URL seems correct.

- [Seldon Core Setup](https://docs.seldon.io/projects/seldon-core/en/latest/examples/seldon_core_setup.html)

**Comment by cliveseldon** [comment]
Docs have been updated. Please reopen if still an issue.
