### ISSUE TITLE
observing high and critical vulnerabilities in anchore scans reports for seldon server images configured  in config maps 

### ISSUE THREAD

**Issue by chetanoruganti** [SeldonIO/seldon-core#2504]
Hi ,
observing high and critical vulnerabilities in anchore scans in seldon server images . find the attached scans below . Attached scans for 1.2.1 dockers but looks like there is no change in 1.2.2 .  

[scans.zip](https://github.com/SeldonIO/seldon-core/files/5304770/scans.zip)

**Comment by cliveseldon** [comment]
We should look to add Dependabot and look ay Synk for these sub-components.

**Comment by cliveseldon** [comment]
Snyk now being used.
