### ISSUE TITLE
document best practices for multiprocessing / concurrency patterns in inference libraries

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2507]
There may be use cases where libraries called on `predict` would use thread/process pools on their own. 
It is important to understand side-effects of such configurations and provide best practices for these use cases.

That would include (but not be limited to) configuration of number of threads, workers and replicas.

**Comment by cliveseldon** [comment]
This is now in [docs](https://docs.seldon.io/projects/seldon-core/en/latest/production/optimization.html#)
