### ISSUE TITLE
helm install results in wrong configmap

### ISSUE THREAD

**Issue by Marcus-Rosti** [SeldonIO/seldon-core#2528]
## Describe the bug

```
$ kubectl describe configmap seldon-config
----
	"MLFLOW_SERVER": {
		"rest": {
			"image": "seldonio/mlflowserver_rest",
			"defaultImageVersion": "1.3.0"
		},
		"grpc": {
			"image": "seldonio/mlflowserver_grpc",
			"defaultImageVersion": "1.3.0"
		}
	}  <---- THERE'S NO COMMA HERE so it can't parse the json
	"TRITON_SERVER": {
		"rest": {
			"image": "nvcr.io/nvidia/tritonserver",
			"defaultImageVersion": "1.3.0"
		},
		"grpc": {
			"image": "nvcr.io/nvidia/tritonserver",
			"defaultImageVersion": "1.3.0"
		}
	}
}
```
results in a config map that's missing a comma 

## Expected behaviour

Installs with a configmap that includes this comma

## Environment
using kubernetes
seldon tag v1.3.0 with the default values.yaml

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
This PR fixed the kustomize. https://github.com/SeldonIO/seldon-core/pull/2527
This was via Helm not kustomize?
Can you try the latest Helm chart as we had to push a fix for the existing one to the helm repo.

**Comment by Marcus-Rosti** [comment]
yes via helm on 1.3.0
```
helm upgrade  --install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --namespace seldon-system -f seldon/values.yaml
```

I can give the it a try by cloning the repo and trying 1.3.0 vs latest

**Comment by cliveseldon** [comment]
This is fixed.
