### ISSUE TITLE
Integration test failed due to alibi_explainer container

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#2529]
## Describe the bug

The integration test failed due to the following test

```
[gw0] FAILED test_prepackaged_servers.py::TestPrepack::test_text_alibi_explainer 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-istio] 
[gw0] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-istio] 
=================================== FAILURES ===================================
____________________ TestPrepack.test_text_alibi_explainer _____________________
[gw0] linux -- Python 3.6.10 /usr/local/bin/python
self = <test_prepackaged_servers.TestPrepack object at 0x7f8babdb4470>
namespace = 'test-text-alibi-explainer'
    def test_text_alibi_explainer(self, namespace):
        spec = "../resources/movies-text-explainer.yaml"
        retry_run(f"kubectl apply -f {spec} -n {namespace}")
        wait_for_status("movie", namespace)
>       wait_for_rollout("movie", namespace, expected_deployments=2)
test_prepackaged_servers.py:191: 
```
The log from the container

```
2020-10-07 12:09:03.783057: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-07 12:09:03.783087: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/app-root/src/alibiexplainer/__init__.py", line 1, in <module>
    from .explainer import AlibiExplainer, Protocol
  File "/opt/app-root/src/alibiexplainer/explainer.py", line 32, in <module>
    from alibiexplainer.proto import prediction_pb2
  File "/opt/app-root/src/alibiexplainer/proto/prediction_pb2.py", line 17, in <module>
    from alibiexplainer.proto.tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/opt/app-root/src/alibiexplainer/proto/tensorflow/core/framework/tensor_pb2.py", line 14, in <module>
    from . import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/opt/app-root/src/alibiexplainer/proto/tensorflow/core/framework/resource_handle_pb2.py", line 15, in <module>
    from . import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2
  File "/opt/app-root/src/alibiexplainer/proto/tensorflow/core/framework/types_pb2.py", line 23, in <module>
    serialized_pb=b'\n%tensorflow/core/framework/types.proto\x12\ntensorflow*\xaa\x06\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0c\n\x08\x44T_FLOAT\x10\x01\x12\r\n\tDT_DOUBLE\x10\x02\x12\x0c\n\x08\x44T_INT32\x10\x03\x1
2\x0c\n\x08\x44T_UINT8\x10\x04\x12\x0c\n\x08\x44T_INT16\x10\x05\x12\x0b\n\x07\x44T_INT8\x10\x06\x12\r\n\tDT_STRING\x10\x07\x12\x10\n\x0c\x44T_COMPLEX64\x10\x08\x12\x0c\n\x08\x44T_INT64\x10\t\x12\x0b\n\x07\x44T_BOOL\x10\n\x12\x0c\n\
x08\x44T_QINT8\x10\x0b\x12\r\n\tDT_QUINT8\x10\x0c\x12\r\n\tDT_QINT32\x10\r\x12\x0f\n\x0b\x44T_BFLOAT16\x10\x0e\x12\r\n\tDT_QINT16\x10\x0f\x12\x0e\n\nDT_QUINT16\x10\x10\x12\r\n\tDT_UINT16\x10\x11\x12\x11\n\rDT_COMPLEX128\x10\x12\x12
\x0b\n\x07\x44T_HALF\x10\x13\x12\x0f\n\x0b\x44T_RESOURCE\x10\x14\x12\x0e\n\nDT_VARIANT\x10\x15\x12\r\n\tDT_UINT32\x10\x16\x12\r\n\tDT_UINT64\x10\x17\x12\x10\n\x0c\x44T_FLOAT_REF\x10\x65\x12\x11\n\rDT_DOUBLE_REF\x10\x66\x12\x10\n\x0
c\x44T_INT32_REF\x10g\x12\x10\n\x0c\x44T_UINT8_REF\x10h\x12\x10\n\x0c\x44T_INT16_REF\x10i\x12\x0f\n\x0b\x44T_INT8_REF\x10j\x12\x11\n\rDT_STRING_REF\x10k\x12\x14\n\x10\x44T_COMPLEX64_REF\x10l\x12\x10\n\x0c\x44T_INT64_REF\x10m\x12\x0
f\n\x0b\x44T_BOOL_REF\x10n\x12\x10\n\x0c\x44T_QINT8_REF\x10o\x12\x11\n\rDT_QUINT8_REF\x10p\x12\x11\n\rDT_QINT32_REF\x10q\x12\x13\n\x0f\x44T_BFLOAT16_REF\x10r\x12\x11\n\rDT_QINT16_REF\x10s\x12\x12\n\x0e\x44T_QUINT16_REF\x10t\x12\x11
\n\rDT_UINT16_REF\x10u\x12\x15\n\x11\x44T_COMPLEX128_REF\x10v\x12\x0f\n\x0b\x44T_HALF_REF\x10w\x12\x13\n\x0f\x44T_RESOURCE_REF\x10x\x12\x12\n\x0e\x44T_VARIANT_REF\x10y\x12\x11\n\rDT_UINT32_REF\x10z\x12\x11\n\rDT_UINT64_REF\x10{*5\n
\x0fSpecializedType\x12\x0e\n\nST_INVALID\x10\x00\x12\x12\n\x0eST_TENSOR_LIST\x10\x01\x42z\n\x18org.tensorflow.frameworkB\x0bTypesProtosP\x01ZLgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto\xf8\x01\x01
\x62\x06proto3'
  File "/opt/app-root/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 941, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorflow/core/framework/types.proto":
  tensorflow/core/framework/types.proto: A file with this name is already in the pool.
```

```
root at agao-dub ❯ k get pod -n test-text-alibi-explainer
NAME                                                   READY   STATUS             RESTARTS   AGE
movie-movies-predictor-0-classifier-7b57df7c47-plkr5   2/2     Running            0          8m
movie-movies-predictor-explainer-57d8bcc965-9985w      0/1     CrashLoopBackOff   6          8m
```

## To reproduce

Run integration test again master branch

## Expected behaviour

pass integration test

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by anggao** [comment]
Also I found I got a similar issue if I ran `make test` under `components/alibi-explain-server`

`----------------------------------------------------------------------------------------------------------- Captured stderr -----------------------------------------------------------------------------------------------------------
2020-10-07 16:32:04.332746: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-07 16:32:04.332781: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
________________________________________________________________________________________________ ERROR collecting tests/test_parser.py ________________________________________________________________________________________________
tests/test_parser.py:20: in <module>
    from alibiexplainer.parser import parse_args
alibiexplainer/__init__.py:1: in <module>
    from .explainer import AlibiExplainer, Protocol
alibiexplainer/explainer.py:32: in <module>
    from alibiexplainer.proto import prediction_pb2
alibiexplainer/proto/prediction_pb2.py:17: in <module>
    from alibiexplainer.proto.tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
alibiexplainer/proto/tensorflow/core/framework/tensor_pb2.py:14: in <module>
    from . import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
alibiexplainer/proto/tensorflow/core/framework/resource_handle_pb2.py:15: in <module>
    from . import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2
alibiexplainer/proto/tensorflow/core/framework/types_pb2.py:23: in <module>
    serialized_pb=b'\n%tensorflow/core/framework/types.proto\x12\ntensorflow*\xaa\x06\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0c\n\x08\x44T_FLOAT\x10\x01\x12\r\n\tDT_DOUBLE\x10\x02\x12\x0c\n\x08\x44T_INT32\x10\x03\x12\x0c\n\x08\x44T_UINT8\x10\x04\x12\x0c\n\x08\x44T_INT16\x10\x05\x12\x0b\n\x07\x44T_INT8\x10\x06\x12\r\n\tDT_STRING\x10\x07\x12\x10\n\x0c\x44T_COMPLEX64\x10\x08\x12\x0c\n\x08\x44T_INT64\x10\t\x12\x0b\n\x07\x44T_BOOL\x10\n\x12\x0c\n\x08\x44T_QINT8\x10\x0b\x12\r\n\tDT_QUINT8\x10\x0c\x12\r\n\tDT_QINT32\x10\r\x12\x0f\n\x0b\x44T_BFLOAT16\x10\x0e\x12\r\n\tDT_QINT16\x10\x0f\x12\x0e\n\nDT_QUINT16\x10\x10\x12\r\n\tDT_UINT16\x10\x11\x12\x11\n\rDT_COMPLEX128\x10\x12\x12\x0b\n\x07\x44T_HALF\x10\x13\x12\x0f\n\x0b\x44T_RESOURCE\x10\x14\x12\x0e\n\nDT_VARIANT\x10\x15\x12\r\n\tDT_UINT32\x10\x16\x12\r\n\tDT_UINT64\x10\x17\x12\x10\n\x0c\x44T_FLOAT_REF\x10\x65\x12\x11\n\rDT_DOUBLE_REF\x10\x66\x12\x10\n\x0c\x44T_INT32_REF\x10g\x12\x10\n\x0c\x44T_UINT8_REF\x10h\x12\x10\n\x0c\x44T_INT16_REF\x10i\x12\x0f\n\x0b\x44T_INT8_REF\x10j\x12\x11\n\rDT_STRING_REF\x10k\x12\x14\n\x10\x44T_COMPLEX64_REF\x10l\x12\x10\n\x0c\x44T_INT64_REF\x10m\x12\x0f\n\x0b\x44T_BOOL_REF\x10n\x12\x10\n\x0c\x44T_QINT8_REF\x10o\x12\x11\n\rDT_QUINT8_REF\x10p\x12\x11\n\rDT_QINT32_REF\x10q\x12\x13\n\x0f\x44T_BFLOAT16_REF\x10r\x12\x11\n\rDT_QINT16_REF\x10s\x12\x12\n\x0e\x44T_QUINT16_REF\x10t\x12\x11\n\rDT_UINT16_REF\x10u\x12\x15\n\x11\x44T_COMPLEX128_REF\x10v\x12\x0f\n\x0b\x44T_HALF_REF\x10w\x12\x13\n\x0f\x44T_RESOURCE_REF\x10x\x12\x12\n\x0e\x44T_VARIANT_REF\x10y\x12\x11\n\rDT_UINT32_REF\x10z\x12\x11\n\rDT_UINT64_REF\x10{*5\n\x0fSpecializedType\x12\x0e\n\nST_INVALID\x10\x00\x12\x12\n\x0eST_TENSOR_LIST\x10\x01\x42z\n\x18org.tensorflow.frameworkB\x0bTypesProtosP\x01ZLgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto\xf8\x01\x01\x62\x06proto3'
../../../miniconda/envs/seldon/lib/python3.7/site-packages/google/protobuf/descriptor.py:941: in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
E   TypeError: Couldn't build proto file into descriptor pool!
E   Invalid proto descriptor for file "tensorflow/core/framework/types.proto":
E     tensorflow/core/framework/types.proto: A file with this name is already in the pool.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================================== 2 errors in 2.84s ==========================================================================================================
`

**Comment by anggao** [comment]
A similar issue: https://github.com/ValvePython/csgo/issues/8#issuecomment-296345877

so I tried the following in my testing environment

```
pip uninstall protobuf
pip install --no-binary=protobuf protobuf
```
Now the test passed, I feel we should add `--no-binary` in some of the pip install process

**Comment by axsaucedo** [comment]
Thank you for the heads up @anggao, are the tests currently failing in master? I haven't seen PRs fail on this tests in particular, or is this something that you saw when running locally?

**Comment by anggao** [comment]
@axsaucedo  Yes I tested it against master
