### ISSUE TITLE
LibGL fix to be cherry picked for 1.3.1

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2534]
ADserver has a libGL shared library crash, which was fixed but the patch didn't make it to 1.3, we will want to cherry pick https://github.com/SeldonIO/seldon-core/pull/2482/files into 1.3.1.

This will also require the patch fix in #2533 otherwise the new build will result in issues as well.

**Comment by cliveseldon** [comment]
Fixed
