### ISSUE TITLE
Notebook test `test_custom_metrics` failing in master

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2541]
## Describe the bug

It seems that the `test_custom_metrics` test is failing across multiple PRs. 

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by anggao** [comment]
Any updates for this issue @RafalSkolasinski ?

**Comment by RafalSkolasinski** [comment]
Sorry, I am on holidays, back on Wednesday :)

**Comment by anggao** [comment]
😄  enjoy !

**Comment by RafalSkolasinski** [comment]
The notebook is now confirmed to be flaky and this is tracked in https://github.com/SeldonIO/seldon-core/issues/2570
