### ISSUE TITLE
Overwrite existing seldon deployment on kubernetes- Not working

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#2552]
## Describe the bug
Whenever I try to redeploy (with new changes made) on kuberenetes that already has the same seldon deployment in kubernetes, it doesnt get replaced. Instead it reruns with the old deployment version.
A normal deployment when tried to redeploy on kuberenetes doesnt show this issue and it just gets replaced.
Is there something I have missed or is this how the seldon deployment works?

## To reproduce
1. Build docker image with initial version v0.1
2. Deploy it on kubernetes (I am using seldon core 1.1.0 version)( kubectl apply -f  <seldondeployment>.yaml )
3. Make some changes and create a new docker image of version v0.2
4. Deploy it on kubernetes again using the same kubectl command. It doesnt get deployed..kubernetes shows the old deployment itself after getting redeployed.

## Expected behaviour
I expect the seldon deployment to get overwritten with the new docker image seldon deployment.
I shouldnt have to delete the old seldon deployment on kubernetes (kubectl delete -f <seldondeployment>.yaml and then redeploy the new seldon deployment for it to work. This causes a downtime.
Is there something I am missing?

## Environment

* Cloud Provider: GKE
* Kubernetes Cluster Version 1.14.10-gke.50
* Deployed Seldon System Images: 
value: docker.io/seldonio/engine:1.1.0
          value: seldonio/seldon-core-executor:1.1.0
        image: seldonio/seldon-core-operator:1.1.0

**Comment by cliveseldon** [comment]
Can you show a version of yaml - using dummy images that has this issue? For example based on https://github.com/SeldonIO/seldon-core/blob/master/notebooks/resources/model.yaml

**Comment by divyadilip91** [comment]
Hi @cliveseldon ,
Thankyou for your response. I used the same version shown in the above link. I had also used machinelearning.seldon.io/v1alpha2 apiversion too.
Is it any prob with the version?

**Comment by cliveseldon** [comment]
Can you provide a sequence of yamls the first and second so we can test?

**Comment by cliveseldon** [comment]
Closing. Please reopen if not working with latest version- presently 1.12
