### ISSUE TITLE
Pip cache removal in wrappers/s2i/python/s2i/bin/assemble

### ISSUE THREAD

**Issue by ramanNarasimhan77** [SeldonIO/seldon-core#2581]
Hello,
While packaging python model wrapper into a docker image, I observed considerable difference in image sizes built using `s2i` and my own `Dockerfile` (s2i image is always larger)

One of the reasons for this is that, the image built using `s2i retains the pip cache` whereas I'm removing pip caches in the Dockerfile by using `pip install` with `--no-cache-dir` flag

I think the s2i based build can also produce smaller images if --no-cache-dir is added to the s2i assemble script ( [here](https://github.com/SeldonIO/seldon-core/blob/master/wrappers/s2i/python/s2i/bin/assemble#L63) and [here](https://github.com/SeldonIO/seldon-core/blob/master/wrappers/s2i/python/s2i/bin/assemble#L66) )

This would be particularly useful for models which have a lot of dependencies.

I built a local s2i python builder image which has the `--no-cache-dir` flag added in the pip install commands in the assemble script. Using this builder image, I have wrapped the [deep-mnist](https://github.com/SeldonIO/seldon-core/tree/master/examples/models/deep_mnist) model

I see savings of ~140MB

```shell
$ docker images | grep -e REPO -e tf-example-mnist
REPOSITORY                                                                       TAG                     IMAGE ID            CREATED             SIZE
seldonio/tf-example-mnist-local                                                  0.2                     491dc6c9684b        4 seconds ago       1.33GB
seldonio/tf-example-mnist                                                        0.2                     d1d9f7b229b7        2 minutes ago       1.47GB
```

Later, I tried adding `torch` (pytorch) which is ~750MB in size as a dependency in `requirements.txt` for testing even though this model does not use pytorch. 

Here, there's a savings of 880MB

```shell
$ docker images | grep -e REPO -e tf-example-mnist
REPOSITORY                                                                       TAG                     IMAGE ID            CREATED             SIZE
seldonio/tf-example-mnist-local                                                  0.2                     b4c7c0ebacd9        11 minutes ago      2.84GB
seldonio/tf-example-mnist                                                        0.2                     f56e02f0b1f3        13 minutes ago      3.72GB
```

**Comment by cliveseldon** [comment]
Thanks. This makes a lot of sense. Are you able to do a small PR for this?

**Comment by ramanNarasimhan77** [comment]
Hi @cliveseldon 
Unfortunately, even though the terms of my current employment allow me to post issues/bugs, I am forbidden from making open source contributions.

**Comment by M46F** [comment]
Hi, may I work on this?

**Comment by cliveseldon** [comment]
Sure - go ahead @M46F
