### ISSUE TITLE
OSS-139: KeyError: 'data'

### ISSUE THREAD

**Issue by lomori** [SeldonIO/seldon-core#2582]
## Describe the bug

I'm getting the following exception while trying the seldon_e2e_cifar10 sample:

HTTPServerRequest(protocol='http', host='cifar10-classifier-default-explainer.luiz-omori:9000', method='POST', uri='/v1/models/cifar10-classifier:explain', version='HTTP/1.1', remote_ip='127.0.0.1')

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/app-root/src/alibiexplainer/server.py", line 95, in post
    response =self.model.explain(body)
  File "/opt/app-root/src/alibiexplainer/explainer.py", line 147, in explain
    response_list = rh.extract_request()
  File "/opt/app-root/src/alibiexplainer/seldon_http.py", line 83, in extract_request
    return _extract_list(self.request)
  File "/opt/app-root/src/alibiexplainer/seldon_http.py", line 15, in _extract_list
    data_def = body["data"]
KeyError: 'data'

Note that the predict endpoint works fine.

## To reproduce
Use this notebook: https://github.com/kubeflow/pipelines/blob/master/samples/contrib/e2e-outlier-drift-explainer/seldon/seldon_e2e_cifar10.ipynb

Exception in the explainer pod will happen at the cell "Make an explanation request"

## Expected behaviour

Explanation request completed without error.

## Environment
* Cloud Provider: Baremetal using Rancher deployment
* Kubernetes Cluster Version: 1.17 
* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]

Alternatively run `echo "#### Kubernetes version:\n $(kubectl version) \n\n#### Seldon Images:\n$(kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio)"`
-->

## Model Details 
* Images of your model: seldon-core-operator:1.2.1, seldonio/jupyter-lab-alibi-kale:0.20
* Logs of your model: see above

**Comment by cliveseldon** [comment]
Are there any errors in the prediction server pod containers?
It looks like the explainer wrapper got an empty reply for some reason.

**Comment by lomori** [comment]
No errors in the prediction server pod. 
    On Monday, October 26, 2020, 03:40:07 PM EDT, cliveseldon <notifications@github.com> wrote:  
 
 


Are there any errors in the prediction server pod containers?
It looks like the explainer wrapper got an empty reply for some reason.

**Comment by lomori** [comment]
And here is a Wireshark (kubectl sniff plugin) capture of my request. Have you changed the interface from "instances" to "data"?
Post:
 POST /v1/models/cifar10-classifier:explain HTTP/1.1host: cifar10-classifier-default-explainer.luiz-omori:9000user-agent: curl/7.58.0accept: */*content-type: application/jsoncontent-length: 63575x-forwarded-proto: httpx-request-id: 63062e67-4b14-41c2-b418-b7d4434a6d03x-envoy-decorator-operation: cifar10-classifier-default-explainer.luiz-omori.svc.cluster.local:9000/*x-istio-attributes: CjcKCnNvdXJjZS51aWQSKRIna3ViZXJuZXRlczovL3NlbGRvbi10ZXN0LTEtMC5sdWl6LW9tb3JpCl8KGGRlc3RpbmF0aW9uLnNlcnZpY2UuaG9zdBJDEkFjaWZhcjEwLWNsYXNzaWZpZXItZGVmYXVsdC1leHBsYWluZXIubHVpei1vbW9yaS5zdmMuY2x1c3Rlci5sb2NhbApdChdkZXN0aWfThJyvbi5zZXJ2aWNlLnVpZBJCEkBpc3RpbzovL2x1aXotb21vcmkvc2VydmljZXMvY2lmYXIxMC1jbGFzc2lmaWVyLWRlZmF1bHQtZXhwbGFpbmVyCkIKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRImEiRjaWZhcjEwLWNsYXNzaWZpZXItZGVmYXVsdC1leHBsYWluZXIKLQodZGVzdGluYXRpb24uc2VydmljZS5uYW1lc3BhY2USDBIKbHVpei1vbW9yaQ==x-b3-traceid: 651f1e35e20b9edd9e01a4ee4221564dx-b3-spanid: 9e01a4ee4221564dx-b3-sampled: 0
{"instances":[[[[0.3529411852359772, 0.48627451062202454, 0.5843137502670288], ..., [0.3490196168422699, 0.47058823704719543, 0.572549045085907]]]] }
Response:
HTTP/1.1 500 Internal Server Errorserver: istio-envoycontent-type: text/html; charset=UTF-8date: Wed, 28 Oct 2020 18:09:48 GMTcontent-length: 93x-envoy-upstream-service-time: 2
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>


    On Monday, October 26, 2020, 03:46:56 PM EDT, Luiz Omori <luiz_omori@yahoo.com> wrote:  
 
  No errors in the prediction server pod. 
    On Monday, October 26, 2020, 03:40:07 PM EDT, cliveseldon <notifications@github.com> wrote:  
 
 


Are there any errors in the prediction server pod containers?
It looks like the explainer wrapper got an empty reply for some reason.

**Comment by cliveseldon** [comment]
`instances` would be a tfserving request payload not a Seldon request payload which has `data`

**Comment by lomori** [comment]
So, this sample is outdated? kubeflow/pipelines

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
kubeflow/pipelines

Machine Learning Pipelines for Kubeflow. Contribute to kubeflow/pipelines development by creating an account on ...
 |

 |

 |

If yes, than there are quite a few others also.

    On Wednesday, October 28, 2020, 02:42:39 PM EDT, cliveseldon <notifications@github.com> wrote:  
 
 


instances would be a tfserving request payload not a Seldon request payload which has data

**Comment by cliveseldon** [comment]
No the example is using the tensorflow protocol. So that is correct.
Can you see the 500 error in the pod logs of the predictor anywhere?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
