### ISSUE TITLE
Allow Gunicorn Options to be specified for Python Wrapped models

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#2585]
Ability to configure Gunicorn on a per model basis.

**Comment by axsaucedo** [comment]
Explore if setting can be added to disable gunicord debug logs #2568

**Comment by cliveseldon** [comment]
Note env var used in MLFlow: https://github.com/mlflow/mlflow/issues/2108#issuecomment-620726657

**Comment by RafalSkolasinski** [comment]
> Explore if setting can be added to disable gunicord debug logs #2568

In regards to https://github.com/SeldonIO/seldon-core/issues/2568, should these 
```
[2020-10-21 18:57:25 +0000] [22] [DEBUG] Closing connection.
[2020-10-21 18:57:25 +0000] [22] [DEBUG] Closing connection.
[2020-10-21 18:57:27 +0000] [22] [DEBUG] Closing connection.
```
be disabled if `SELDON_LOG_LEVEL` is set to higher level, for example `INFO`? 

(it does not seem to be the case unfortunately...)

**Comment by cliveseldon** [comment]
Closing as we should open a similar issue in MLServer
