### ISSUE TITLE
Allow annotations on Service created by operator

### ISSUE THREAD

**Issue by groszewn** [SeldonIO/seldon-core#2590]
Certain integrations expect annotations placed on the service resource in order to work.  One, in particular, is the datadog healthcheck configuration which can seen [here](https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/#template-source-kubernetes-service-annotations).  

Similarly to how the predictorSpec annotations can be used to provide a [custom service name](https://github.com/SeldonIO/seldon-core/blob/f27558629e321345181b3af1f6a515f104343239/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L137), I'm thinking that we can have the predictorSpec annotations be applied to the corresponding created service as well.  It seems like these annotations would need to be added [here](https://github.com/SeldonIO/seldon-core/blob/13762c055f1e9e146d7c1111fc5d5aefcbf56f42/operator/controllers/seldondeployment_controller.go#L674) for the predictor service and [here](https://github.com/SeldonIO/seldon-core/blob/13762c055f1e9e146d7c1111fc5d5aefcbf56f42/operator/controllers/seldondeployment_controller.go#L769) (if needed) for the container service.

**Comment by cliveseldon** [comment]
Sounds good. Would you suggest a CRD addition?

**Comment by groszewn** [comment]
Definitely open to suggestions here.  It seems like the [PredictorSpec](https://github.com/SeldonIO/seldon-core/blob/f27558629e321345181b3af1f6a515f104343239/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L227) annotations could be reused and just applied to the created service.
