### ISSUE TITLE
Grafana on Ambassador (Public DNS)?

### ISSUE THREAD

**Issue by Seninus** [SeldonIO/seldon-core#2591]
Seldon has default setup for ambassador + namespace + modelName+ prediciton... and if i deployed on AWS EKS, it can be reached by using public DNS. 

Since seldon has other UI pages like Grafana, Prometeus, Kubeflow.  is it possible to custom config the ambassador and deploy multiple (4 UI pages here) using the one or multiple Ambassador?  

any example?

**Comment by cliveseldon** [comment]
Can you explain your requirement further with an example?

**Comment by Seninus** [comment]
Thanks, so for the deployed model in seldon namespace. we can use this URL to see the Swagger UI page. 
http://<ambassadorEndpoint>/seldon/<namespace>/<deploymentName>/api/v1.0/docs
and <ambassadorEndpoint> is the Public DNS i have in AWS once i installed Ambassador in EKS. 

Since Seldon also has other UI pages like Grafana and i am currently accessing it locally using Kubectl port-forward.... what i need is to be able to access Grafana, Premetheus, kubeflow also using the same configration like 
http://<ambassadorEndpoint>/seldon/<namespace>/..... (Grafana or Prometheus, Kubeflow) ...

is there any Yaml template for me to re-config Ambassador or Istio?

**Comment by cliveseldon** [comment]
We don't have a central config for these as for example the Grafana metrics is an example and should be managed by your organisation's access to Grafana. Similarly, for Kubeflow or Prometheus. 

If you create a nice solution we'd like to hear about it.
