### ISSUE TITLE
Conflict between gunicorn, gevent, and TensorFlow

### ISSUE THREAD

**Issue by amirclam** [SeldonIO/seldon-core#2603]
We are using seldon core to wrapper our tensorflow mlflow model inside a docker container
When using v.1.1.0 version it work  great
Using the new 1.4.0 version calling the predict gets stuck
Looking at the web we found out that
https://github.com/mlflow/mlflow/issues/2108 there is a conflict between gunicorn, gevent, and TensorFlow
the solution for now is to set gunicorn worker-class to us gthread instead of default gevent
how can I do it using the seldon-core wrapper ?

**Comment by cliveseldon** [comment]
Connected to #2585 
Probably best if this was configurable as needed for the same concerns expressed in https://github.com/mlflow/mlflow/issues/2108

**Comment by cliveseldon** [comment]
We don't actually use gevent by default - we use sync - are you sure this is the issue?
Do you have any further logs/details?

https://docs.gunicorn.org/en/stable/settings.html#worker-class

**Comment by amirclam** [comment]
The issue was that we have loaded our model in the class constructor

```
   def __init__(self):
        log.info ("Initializing")
        model_location = os.environ['MODEL_LOCATION']
        self.session = tf.Session(graph=tf.Graph())
        with self.session.graph.as_default():
            set_session(self.session)
            self.model = keras.load_model(model_location)

``` 
After going over https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html?highlight=gunicorn#gunicorn-and-load

we have change our code : 
```
    def load_model(self): 
        model_location = os.environ['MODEL_LOCATION']
        self.session = tf.Session()
        self.model = keras.load_model(model_location)
        self.loaded = True

    def predict(self, X: Union[np.ndarray, str], features_names: Iterable[str], meta: Dict = None) -> Union[
        np.ndarray, List, str, bytes]:
        """
        Return a prediction.

        Parameters
        ----------
        X : model input values. can be array like or if string then assumed json
        feature_names : array of feature names (optional)
        """
        log.debug(X)
        if type(X) == str:
            X = np.asanyarray(json.loads(X))
        if not self.loaded:
            self.load_model()
```
