### ISSUE TITLE
Tutorial issues - CIFAR10 Drift Detection

### ISSUE THREAD

**Issue by lomori** [SeldonIO/seldon-core#2605]
## Describe the bug
I'm having some issues following https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/drift_cifar10.html. The pod deployed by **kubectl apply -f cifar10.yaml** keeps crashing.

Log for the resnet32 container:
/usr/bin/tf_serving_entrypoint.sh: line 3:     6 Illegal instruction     (core dumped) tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"

Log for 
{"level":"info","ts":1604435433.4166596,"logger":"entrypoint","msg":"Hostname unset will use localhost"}
{"level":"info","ts":1604435433.4264307,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1604435433.4265187,"logger":"entrypoint","msg":"Starting","worker":2}
{"level":"info","ts":1604435433.4265313,"logger":"entrypoint","msg":"Starting","worker":3}
{"level":"info","ts":1604435433.4265423,"logger":"entrypoint","msg":"Starting","worker":4}
{"level":"info","ts":1604435433.426739,"logger":"entrypoint","msg":"Starting","worker":5}
{"level":"info","ts":1604435433.4296367,"logger":"entrypoint","msg":"Running http server ","port":8000}
{"level":"info","ts":1604435433.4297154,"logger":"entrypoint","msg":"Creating non-TLS listener","port":8000}
{"level":"info","ts":1604435433.4317653,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
{"level":"error","ts":1604435454.9092786,"logger":"SeldonRestApi","msg":"Ready check failed","error":"dial tcp 127.0.0.1:8501: connect: connection refused","stacktrace":"github.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).checkReady\n\t/workspace/api/rest/server.go:175\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.handleCORSRequests.func1\n\t/workspace/api/rest/middlewares.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.CORSMethodMiddleware.func1.1\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/middleware.go:51\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.xssMiddleware.func1\n\t/workspace/api/rest/middlewares.go:87\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1\n\t/workspace/api/rest/middlewares.go:47\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1\n\t/workspace/api/rest/middlewares.go:79\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2831\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1919"}

(the last entry is repeated forever...)

## To reproduce
Follow  https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/drift_cifar10.html.

## Expected behaviour
All containers should run without errors.

## Environment
* Cloud Provider: bare-metal (local)
* Kubernetes Cluster Version: 1.19.3 
* Deployed Seldon System Images: 
          value: docker.io/seldonio/engine:1.4.0
          value: docker.io/seldonio/seldon-core-executor:1.4.0
        image: docker.io/seldonio/seldon-core-operator:1.4.0

## Model Details
As described in the tutorial. See logs above.

**Comment by cliveseldon** [comment]
Did the tfserving container start ok?

**Comment by lomori** [comment]
I think that's the one you are talking about:

usr/bin/tf_serving_entrypoint.sh: line 3: 6 Illegal instruction (core dumped) tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"

Maybe there was a change affecting how MODEL_BASE_PATH and MODEL_NAME are being handled?

**Comment by cliveseldon** [comment]
Illegal instruction sounds bad. I assume you are running in standard hardware/CPUs? You might need a custom binary for your CPUs?

https://github.com/tensorflow/serving/issues/1342

**Comment by lomori** [comment]
Yeah, you are right. My test cluster has low end CPUs, including a Celeron. I've used the docker command below to test the tfserving and it works on Intel I5 but not on Celeron.

I guess I will have to play with Taints, Labels, or nodeSelectors. Do you know if there is a way to define nodeSelector in the SeldonDeployment in such a way that that is passed down to the Deployment generated by that CRD? I guess there must be otherwise how would I be able to select a node with GPU?

docker run -t --rm -p 8501:8501 \
  -e MODEL_NAME=resnet32 \
  -e MODEL_BASE_PATH=gs://seldon-models/tfserving/cifar10 \
  tensorflow/serving

cat /proc/cpuinfo
Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz -> OK
Intel(R) Celeron(R) CPU J3455 @ 1.50GHz -> Not OK

**Comment by cliveseldon** [comment]
Yes you can create the PodSpec for the tfserver. Just make sure its name is the same as the name in the inference graph. 
See the tfserving example in  https://github.com/SeldonIO/seldon-core/blob/master/notebooks/protocol_examples.ipynb

**Comment by lomori** [comment]
Thanks! I've found it simpler to just add nodeAffinity block and label my Celeron nodes as such. See below.

Thanks for your help!

kind: SeldonDeployment
metadata:
  name: tfserving-cifar10
  namespace: seldon-tests
spec:
  protocol: tensorflow
  transport: rest
  predictors:
  - componentSpecs:
    - spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cpu/type
                  operator: NotIn
                  values:
                  - Intel-Celeron
        containers:
        - args:
          - --port=8500
          - --rest_api_port=8501
          - --model_name=resnet32
          - --model_base_path=gs://seldon-models/tfserving/cifar10/resnet32
          image: tensorflow/serving
          name: resnet32
          ports:
          - containerPort: 8501
            name: http
    graph:
      name: resnet32
      type: MODEL
      endpoint:
        service_port: 8501
      logger:
        mode: all
    name: model
    replicas: 1

**Comment by cliveseldon** [comment]
Great @lomori
