### ISSUE TITLE
Seldon client can not send json data with metadata

### ISSUE THREAD

**Issue by amirclam** [SeldonIO/seldon-core#2607]
when using seldon client to send jsondata with metedata

the metadata is ignored

https://github.com/SeldonIO/seldon-core/blob/c576ee7fc02a5e451d8cc617e7d5bb8610680336/python/seldon_core/seldon_client.py#L1482

    elif json_data is not None:
        request = json_to_seldon_message({"jsonData": json_data})

fix should be 
    
    elif json_data is not None:
        request = json_to_seldon_message({"jsonData": json_data, "meta": metaJson})

**Comment by axsaucedo** [comment]
Thank you for reporting this @amirclam - that is correct, good shout, we'll have a look to fix this in v1.5

**Comment by axsaucedo** [comment]
This should be fixed, please reopen if still an issue
