### ISSUE TITLE
OSS-144: Move to OpenTelemetry libraries for tracing

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#2609]
Currently, the executor and the language wrapper use the OpenTracing libraries for tracing. However, that project is now moving into OpenTelemetry.

OpenTelemetry claims to offer a standard protocol that works alongside multiple tracing backends (e.g. Jaeger, DataDog, etc.). So in theory, moving to the OpenTelemetry client should add support for any backend.

**Comment by cliveseldon** [comment]
Probably a v2 work.

**Comment by mwm5945** [comment]
I know this would be appreciated in v1 from my perspective :) 

OTEL does offer shims for open tracing for both Python and Go: https://opentelemetry.io/docs/reference/specification/compatibility/opentracing/

**Comment by cliveseldon** [comment]
Please try v2 for this.
