### ISSUE TITLE
Custom predictor upstream request timeout with python3 GPU s2i images

### ISSUE THREAD

**Issue by ashrafgt** [SeldonIO/seldon-core#2616]
## Describe the bug

When upgrading from `seldonio/seldon-core-s2i-python3:0.3` or `seldonio/seldon-core-s2i-python3:latest` to `seldonio/seldon-core-s2i-python36:1.3.0-dev` or `seldonio/seldon-core-s2i-python36-gpu:1.3.0-dev`, `POST /predict` requests end up with a timeout.

## To reproduce

1. Paste predictor and requirements code in a `src/` directory

```python
# ProbabilityPredictor.py
import os
import pickle
import numpy as np
from transformers import BertForMaskedLM, BertTokenizer, pipeline
import torch

class ProbabilityPredictor(object):
    def __init__(self, model_uri):
        super().__init__()
        self.model_uri = model_uri
        self.ready = False
        self.load()

    def load(self):
        model = BertForMaskedLM.from_pretrained(self.model_uri).eval()
        tokenizer = BertTokenizer(
            os.path.join(self.model_uri, "vocab.txt"), do_lower_case=False
        )
        device = 0 if torch.cuda.is_available() else -1
        self.model = pipeline("fill-mask", model=model, tokenizer=tokenizer, device=-1,)
        self.ready = True

    def predict(self, X, names):
        try:
            if not self.ready:
                self.load()
            result = self.model(X.tolist())
            return np.array([result])
        except Exception as ex:
            print("Exception during predict")
            print(ex)
```
```python
# requirements.txt
pip==20.2.4
sentencepiece==0.1.92
torch==1.6.0
transformers==3.0.2
```

2. Build image

```bash
export S2I_IMAGE=seldonio/seldon-core-s2i-python36-gpu:latest
s2i build . \
  --env MODEL_NAME=ProbabilityPredictor \
  --env API_TYPE=REST \
  --env SERVICE_TYPE=MODEL \
  --env PERSISTENCE=0 \
  --context-dir=src \
  $S2I_IMAGE seldon-probability-predictor
```

As mentioned already, when using `seldonio/seldon-core-s2i-python3:0.3` it works fine unlike the image mentioned in the example

3. Tag and push image

```bash
docker tag seldon-probability-predictor [REGISTRY]/seldon-probability-predictor:latest
docker push [REGISTRY]/seldon-probability-predictor:latest
```

4. Add implementation (named `CUSTOM_PROBABILITY_PREDICTOR` in the deployment below) to the Seldon-core configmap

5. Create deployment

```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: probability-predictor
spec:
  name: bert-base-uncased
  annotations: 
    seldon.io/rest-timeout: "100000"
  predictors:
  - graph:
      children: []
      implementation: CUSTOM_PROBABILITY_PREDICTOR
      modelUri: gs://seldon-s2i-issue-report/bert-base-uncased
      name: model
    componentSpecs:
    - spec:
        containers:
        - name: model
          resources:
            requests:
              cpu: 3
              nvidia.com/gpu: 1
            limits:
              cpu: 3
              nvidia.com/gpu: 1  
    name: default
    replicas: 1
```

## Expected behavior

`POST http://[AMBASSADOR_EXTERNAL_URL]/seldon/[NAMESPACE]/probability-predictor/api/v1.0/predictions` returns a data object

## Actual behavior

The return is an error: `upstream request timeout` 

## Environment

* Cloud Provider: GKE
* Kubernetes Cluster Version: 
```bash
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Deployed Seldon System Images:
```bash
value: docker.io/seldonio/engine:1.4.0
value: docker.io/seldonio/seldon-core-executor:1.4.0
image: docker.io/seldonio/seldon-core-operator:1.4.0
```

* Helm command:
```bash
helm install seldon-core seldon-core-operator \
    --repo https://storage.googleapis.com/seldon-charts \
    --set usageMetrics.enabled=true \
    --namespace [NAMESPACE] \
    --set ambassador.enabled=true
``` 

## Model pod logs:

- `model` and `model-model-initializer` containers: No errors in the logs, just the expected healthy output
- `seldon-container-engine`:
```bash
{"level":"info","ts":1604576646.0409112,"logger":"entrypoint","msg":"Hostname unset will use localhost"}
{"level":"info","ts":1604576646.0457447,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1604576646.045791,"logger":"entrypoint","msg":"Starting","worker":2}
{"level":"info","ts":1604576646.045798,"logger":"entrypoint","msg":"Starting","worker":3}
{"level":"info","ts":1604576646.045803,"logger":"entrypoint","msg":"Starting","worker":4}
{"level":"info","ts":1604576646.045808,"logger":"entrypoint","msg":"Starting","worker":5}
{"level":"info","ts":1604576646.046813,"logger":"entrypoint","msg":"Running http server ","port":8000}
{"level":"info","ts":1604576646.046841,"logger":"entrypoint","msg":"Creating non-TLS listener","port":8000}
{"level":"info","ts":1604576646.0477536,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
{"level":"error","ts":1604578415.2337053,"logger":"SeldonRestApi","msg":"Ready check failed","error":"dial tcp 127.0.0.1:9000: connect: connection timed out","stacktrace":"github.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).checkReady\n\t/workspace/api/rest/server.go:175\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.handleCORSRequests.func1\n\t/workspace/api/rest/middlewares.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.CORSMethodMiddleware.func1.1\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/middleware.go:51\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.xssMiddleware.func1\n\t/workspace/api/rest/middlewares.go:87\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1\n\t/workspace/api/rest/middlewares.go:47\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1\n\t/workspace/api/rest/middlewares.go:79\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2831\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1919"}
```

**Comment by ashrafgt** [comment]
A possible workaround is adding the `--debug` flag to this line
https://github.com/SeldonIO/seldon-core/blob/master/wrappers/s2i/python/s2i/bin/run#L47

Any possible explanation?

**Comment by cliveseldon** [comment]
Adding the `--debug` flag would switch on Flask rather than Gunicorn. 
Are you loading your model in a `load` method? See https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load

**Comment by ashrafgt** [comment]
@cliveseldon yes, the model loading is done with this statement:
```python
model = BertForMaskedLM.from_pretrained(self.model_uri).eval()
```
Which is in the `load()` statement as you can see in the full core snippet.

**Comment by RafalSkolasinski** [comment]
Could try two things:
- remove `self.load()` from `__init__`, SC wrapper should call on its own
- run with single thread using `--single-threaded` or setting `FLASK_SINGLE_THREADED=1` (applied to both Flask and Gunicorn)

**Comment by RafalSkolasinski** [comment]
Also would recommend to probably use `1.3.0` or `1.4.0` images, the `-dev` ones are rolling and give you bleeding edge

**Comment by ashrafgt** [comment]
@RafalSkolasinski Thank you for the reply.

- Removing the `load()` call from the initialization means the first request will have to wait 10 secs or so, which is something we really need to avoid. Having the load operation run as soon as the pod is ready seemed quite good, so I don't see why that could be an issue.
- I will try using `FLASK_SINGLE_THREADED=1` and let you know how that goes, but could you please explain why this may be a solution?
- Yes, thank you for the suggestion. We're using `1.4.0` in production.

Right now, we're still using the `--debug` flag, and to avoid having to build our own base image and use it for `s2i build`, I unfortunately resorted to doing something like this:

```bash
export S2I_IMAGE=seldonio/seldon-core-s2i-python37-gpu:1.4.0
s2i build . \
  --env SERVICE_TYPE='MODEL --debug' \     # inject the --debug flag with one of the build args
  --env ... \
  $S2I_IMAGE seldon-probability-predictor
```

The example I provided should be easy to execute, provided you have a k8s cluster available. The bucket I mentioned exists and is public (created just for this issue). We could continue using this hack, but it's best if we get some closure on why this is happening. 

If running the provided reproduction example is not an option, please let me know so I can remove the aforementioned public bucket.

**Comment by cliveseldon** [comment]
Can you reopen if this is still an issue with latest 1.12 Seldon Core?

**Comment by geraldoramos** [comment]
Hi, I'm having the same issue with `seldonio/seldon-core-s2i-python37-gpu:1.15.0-dev` and `seldonio/seldon-core-s2i-python37-gpu:1.14.1`

By injecting the `--debug` flag in one of the build args (to switch to the flask test server), it works.
