### ISSUE TITLE
Python processes when running Seldon with Gunicorn

### ISSUE THREAD

**Issue by pdstrnadJC** [SeldonIO/seldon-core#2617]
## Describe the bug
Maybe this is more of a Gunicorn question, but trying here first. When I run Seldon with Gunicorn workers I see the worker processes, but after a closer look I see two additional Seldon processes which I can't account for. I start Seldon using seldon-core-microservice and immediately there's a defunct Seldon process - is that expected? There is also another process - I'm not sure how it's started or what its purpose is. Am I missing something?

Here is a concrete example from when I ran Seldon with two Gunicorn workers: 
```
process 1 is the rest server and it starts workers with process ID 39 and 40:
(mlflow) root@model-dd844f64-nfczw:/app# ps -ejH
  PID  PGID   SID TTY          TIME CMD
  378   378   378 pts/0    00:00:00 bash
  420   420   378 pts/0    00:00:00   ps
    1     1     1 ?        00:00:01 seldon-core-mic
   22     1     1 ?        00:00:00   seldon-core-mic
   30     1     1 ?        00:00:00   seldon-core-mic <defunct>
   32     1     1 ?        00:00:00   seldon-core-mic
   38     1     1 ?        00:00:00     seldon-core-mic
   39     1     1 ?        00:00:09   seldon-core-mic
   40     1     1 ?        00:00:09   seldon-core-mic
```

- process 1 is the REST server and it starts workers with process ID's 39 and 40. 
- process 30 is defunct - how/why does this happen?
- process 32 is the metrics server with its worker process is 38.
- process 22 - what is this one? It's running but I'm not sure what it's for. I'm not using a "custom service" so I thought no additional processes would be started. Interestingly I see it using some CPU when I run a load test, but it's minimal (~3%).

## To reproduce
Start Seldon using seldon-core-microservice using two Gunicorn workers (by setting the environment variable GUNICORN_WORKERS=2).

**Comment by axsaucedo** [comment]
Thanks for reporting - this does seem to be something quite gunicorn specific, in the seldon core we run the standard setup for gunicorn, so it may be worth asking in the gunicorn repo/community, have you gotten any insights from them by any chance? 

In regards to this current behaviour, does it cause issues, or is this just something that you noticed when looking at the processes?

**Comment by pdstrnadJC** [comment]
There are no issues, I just thought it was strange that it behaves this way.

**Comment by cliveseldon** [comment]
Closing this.Please reopen if its an issue.
