### ISSUE TITLE
Make initContainer available to all SeldonDeployments

### ISSUE THREAD

**Issue by kylegallatin** [SeldonIO/seldon-core#2632]
Currently, `seldon-core` provides an init container to all prepackaged inference servers and custom registered inference servers that allows users to pass convenient arguments like `modelURI` in the SeldonDeployment YAML. 

As I understand it, this is currently not enabled for deployments that are not registered with the Seldon Core operator. For other deployments, users typically must download models locally and copy them into the image itself, requiring rebuilds for every newly trained model. 

It would be convenient to be able to take full advantage of the initContainer and respective arguments for reasons such as versioning - where users may version images separately from model artifacts for unregistered models.

**Comment by cliveseldon** [comment]
Can you check the latest [init container docs](https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html#init-containers) cover what you need and reopen if now?
