### ISSUE TITLE
docs: No Release Highlights since 1.1.0

### ISSUE THREAD

**Issue by ellisvalentiner** [SeldonIO/seldon-core#2634]
The documentation for [release highlights](https://docs.seldon.io/projects/seldon-core/en/latest/reference/release-highlights.html) hasn't been updated since 1.1.0.

The page could be updated to have current documentation or redirect to the [release notes](https://github.com/SeldonIO/seldon-core/releases/) on GitHub.

**Comment by axsaucedo** [comment]
Good point @ellisvalentiner, most is now kept on the UPGRADING.md page, but you're right probably best to redirect to changelog.
