### ISSUE TITLE
Upgrade storage initializer image: Model initializer with tensorflow model on GCS using service account cannot load model

### ISSUE THREAD

**Issue by schmidt-jake** [SeldonIO/seldon-core#2637]
## Describe the bug

I'm trying to use a prepackaged tensorflow server to serve a model stored in a private google cloud storage bucket. I created a kubernetes service account following the [recommended steps](https://docs.seldon.io/projects/seldon-core/en/v1.1.0/servers/overview.html?highlight=google%20cloud#adding-credentials-for-google-cloud) and added it to my SeldonDeployment. My deployment works fine when I remove the service account and run the example deployment using the MNIST model stored at gs://seldon-models/tfserving/mnist-model.

Here's a snippet of my deployment spec:
```json
{
    "name": "rnn",
    "children": [],
    "implementation": "TENSORFLOW_SERVER",
    "modelUri": "gs://kfp1/mpm-trainer-hs9cm/train/mpm-trainer-hs9cm-821892510/export/best_model_on_train_data",
    "serviceAccountName": "user-gcp-sa",
    "parameters": [
        {
            "name": "signature_name",
            "type": "STRING",
            "value": "predict_images"
        },
        {
            "name": "model_name",
            "type": "STRING",
            "value": "my-model"
        }
    ]
}
```

When I deploy this, the `tfserving-model-initializer` container fails. Here is the stack trace from the container:
```
[I 201113 19:01:35 initializer-entrypoint:13] Initializing, args: src_uri [gs://kfp1/mpm-trainer-hs9cm/train/mpm-trainer-hs9cm-821892510/export/best_model_on_train_data] dest_path[ [/mnt/models]
[I 201113 19:01:35 storage:35] Copying contents of gs://kfp1/mpm-trainer-hs9cm/train/mpm-trainer-hs9cm-821892510/export/best_model_on_train_data to local
[I 201113 19:01:35 storage:111] Downloading: /mnt/models/1605293863
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 48, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 108, in _download_gcs
    os.makedirs(local_object_dir, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/mnt/models/1605293863'
```

## Environment
kubernetes 1.17.9
seldon-core-operator 1.4.0
the model I want to serve was exported using tensorflow 2.3.0
the image running in `tfserving-model-initializer` is `gcr.io/kfserving/storage-initializer:v0.4.0`

**Comment by JakeTheWise** [comment]
this may be related https://github.com/kubeflow/kfserving/issues/771

**Comment by cliveseldon** [comment]
Closing. Can you check this is still an issue with the latest Rclone based init containers for downloading artifacts?
