### ISSUE TITLE
Add symlinks for examples in docs

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#2649]
The notebook examples currently reside in 2 folders: `/notebooks` and `/examples`. These folders are outside of the `/doc` folder, which contains the generated documentation. This causes problems with `sphinx`, which is not happy linking to `*.ipynb` files outside of its root folder.

To work around this, we leverage the [`nbsphinx-link`](https://github.com/vidartf/nbsphinx-link) package. However, this package doesn't support relative links between notebooks outside of the `/doc` root folder. Instead, we are forced to use absolute links to the `https://docs.seldon.io` site. You can see an example here:

https://github.com/SeldonIO/seldon-core/blob/2a9fc3f5bce31eb139437aff10bf886348f8f543/examples/models/azure_aks_deep_mnist/azure_aks_deep_mnist.ipynb#L449

In the past, we've considered to move the examples into the `/doc` folder as a workaround. However, we've decided not to so that the examples can stay visible in the top-folder in the repo.

## Proposal

The scope of this issue aims to explore whether adding symbolic links from the `/doc` folder to the actual `/notebooks` and `/examples` folder could achieve the best of both worlds. E.g.

```
/doc/my-notebook.ipynb -> /examples/my-notebook.ipynb
```

**Comment by cliveseldon** [comment]
Docs have been refactored. Can look again with @edshee on further refactors
