### ISSUE TITLE
executor logging

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#2652]
The logs for the executor (seldon-container-engine container) look like this:
```
{"level":"info","ts":1605539564.0592835,"logger":"entrypoint","msg":"Hostname unset will use localhost"}
{"level":"info","ts":1605539564.0622413,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1605539564.0622847,"logger":"entrypoint","msg":"Starting","worker":2}
```

The timestamps here are not super-readable as it's unix epoch times. Guess this changed recently (in 1.4?). We've also now seen on a customer install that it can cause problems for and older version of elastic (7.3) and if there's other pods running in the cluster which also log a `level.info.ts` field but in a different format. They then see
```
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [ts] of type [date] in document with id 'MdZqwnUBcI59uH2IwWeA'. Preview of field's value: '1.6052845726310768E9'
```
The result is that the executor's logs don't get recorded by the fluentd collection process.

**Comment by cliveseldon** [comment]
Closing for now - can also be a V2 API improvement.
