### ISSUE TITLE
More restricted deployment rbac for seldon-core

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#2662]
Right now seldon-core service account needs cluster level permission to manage all deployments,
can we change it to namespace bound instead of cluster level ?

https://github.com/SeldonIO/seldon-core/blob/master/operator/config/rbac/role.yaml#L39

**Comment by cliveseldon** [comment]
From the discussion in the community call can this be closed now?
You can use namespace operator for this?

**Comment by anggao** [comment]
@cliveseldon  Yeah let's close this now and I will check whether kubebuilder support dynamic MultiNamespacedCacheBuilder
now. We use it to watch a specific set of namespaces but it needs operator restarts when the list changed
