### ISSUE TITLE
Is it possible to overwrite the bins for TIMER metrcis

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#2663]
I see the bins are hard-coded: https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/metrics.py#L38, just wondering if it's possible to overwrite it somehow.

More generally, I'm thinking of exporting prediction values to Grafana for visualization, which metrics type should I use?  I thought I would want to have a histogram over time kind of visualization like the one shown on https://grafana.com/docs/grafana/latest/getting-started/intro-histograms/.

**Comment by cliveseldon** [comment]
Can you create a PR for this?

**Comment by zyxue** [comment]
Here is an idea https://github.com/SeldonIO/seldon-core/pull/2713.

I wonder why is it called a TIMER? Why not just histogram, which would be more generally applicable. The unit of the value doesn't seem to have to be time-related (e.g. milliseconds), right?

**Comment by axsaucedo** [comment]
@zyxue the main reason behind the names is because underneath we expose everything as prometheus metrics, so all these are just aligned with prometheus terminology (same with the concept of tags, which is how prometheus allows you to filter the metrics).

**Comment by axsaucedo** [comment]
Btw thank you for the quick contribution @zyxue that looks like it's going towards the right direction, we're keen to discuss further and get something in that at least provides an initial configurability for users.

**Comment by duongnt** [comment]
> @zyxue the main reason behind the names is because underneath we expose everything as prometheus metrics, so all these are just aligned with prometheus terminology (same with the concept of tags, which is how prometheus allows you to filter the metrics).

@axsaucedo I'm not sure I follow what you were saying. In terms of prometheus terminology, I thought prometheus doesn't have a TIMER metrics type, only HISTOGRAM? https://prometheus.io/docs/concepts/metric_types/

**Comment by duongnt** [comment]
> Here is an idea #2713.
> 
> I wonder why is it called a TIMER? Why not just histogram, which would be more generally applicable. The unit of the value doesn't seem to have to be time-related (e.g. milliseconds), right?

I guess it's called TIMER and its buckets are called BINS because of historical reasons. StatsD uses TIMER/BINS: https://github.com/statsd/statsd/blob/master/docs/metric_types.md. Maybe earlier versions of Prometheus uses TIMER/BINS as well.

**Comment by cliveseldon** [comment]
We might look further in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html)
