### ISSUE TITLE
Seldon-core-operator Update for handling namespace 

### ISSUE THREAD

**Issue by ntorba** [SeldonIO/seldon-core#2676]
Hello! 

Quick ask about the seldon-core-operator helm chart. I'm using it as a dependency in another helm chart, and I would like to install it into a different namespace (`seldon-system`) from other dependencies. 
This can be done using [ambassador helm chart](https://github.com/datawire/ambassador-chart) as a dependency because they use a `namespaceOverride`, in the values.yaml file and assign the namespace based on a template in the `_helpers.tpl` file like this:

```yaml
{{/*
Create chart namespace based on override value.
*/}}
{{- define "seldon-core.namespace" -}}
{{- if .Values.namespaceOverride -}}
{{- .Values.namespaceOverride -}}
{{- else -}}
{{- .Release.Namespace -}}
{{- end -}}
{{- end -}}
```

and then specifying the namespace in kubernetes manifests like this: 
```yaml
namespace: {{ include "seldon-core.namespace" . }}
```

It looks like it would be pretty quick to implement. I'm willing to create the PR if the team is open to this change. 

Thanks!

**Comment by cliveseldon** [comment]
Sounds useful.
To do the PR though as we generate the Helm templates from kustomize config you would need to update https://github.com/SeldonIO/seldon-core/blob/master/operator/helm/split_resources.py

There are quite a few references there to the namespace so some testing would be needed.

There is a Makefile in that folder. To recreate the helm templates run `make create`
