### ISSUE TITLE
Prometheus gauge shown as NaN

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#2685]
## Describe the bug
My metric isn't showing up on grafana, so I took at a look at `curl http://my-predictor-svc:8000/prometheus`, and it returns

```
# HELP my_metric_seconds_gauge  
# TYPE my_metric_seconds_gauge gauge
my_metric_seconds_gauge{deployment_name="myapp",...,stats_type="p95",} NaN
my_metric_seconds_gauge{deployment_name="myapp",...,stats_type="p05",} NaN
my_metric_seconds_gauge{deployment_name="myapp",...,stats_type="median",} NaN
```

So the metric value somehow becomes `NaN`. I'm quite sure my exported metrics are numbers. I'm using the gRPC and [`.predict_raw`](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/seldon_methods.py#L100-L102) method. I'm not sure of the code path for handling the metrics `predict_raw`, so wondering where it becomes NaN.

## To reproduce
Not sure how to reproduce easily, but I've tried redeploying my service multiple times, every time it starts emitting the metric as expected, but then at some point, it would stop (assuming due to NaN) and once it stops, it never comes back again.

**Comment by cliveseldon** [comment]
Are you sure a string is not being sent at some point?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
