### ISSUE TITLE
Seldon cluster-manager  k8s cluster wide operations

### ISSUE THREAD

**Issue by hjarraya** [SeldonIO/seldon-core#269]
Currently seldon cluster-manager is namespaced, you will need one in each namespace to control the deployment launched within that namespace. 
By having seldon cluster-manager k8s cluster wide operation, we can deploy models per namespace, where a namespace is a natural separation between teams using Seldon to deploy their models. 
Also, from the monitoring perspective all data is collected in one place, then the dashboard can be created per namespace and/or seldon deployment.

**Comment by cliveseldon** [comment]
I think we would want to keep both methods as some organisations want to be able to create and pull down Seldon in isolated namespaces for ease of use and limiting RBAC privileges.
The work would need to identify which k8s API calls need to change (maybe just the watches). The RBAC permissions will be different so the helm/ksonnet will need to change to handle either scenario.

I think namespaced should be the default. For example, GCP Marketplace assumes any "Application" is namespaced - other than the CRD creation.
