### ISSUE TITLE
helm chart imagePullSecrets support to bypass ratelimiting

### ISSUE THREAD

**Issue by omerfsen** [SeldonIO/seldon-core#2694]
**Current behavior**

Current helm chart does not support imagePullSecrets and with new dockerhub rate limitation https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/ pulling image will be limited to 100 per 6 hours to anonymous and 200 per 6 hours for free authenticated tiers. Though paid users will not see this limit.
**Enhancement**

Support imagePullSecrets on helm charts (core and analytics) and use it if it is defined

**Comment by omerfsen** [comment]
Is it possible Seldon moves from dockerhub to Quay.io ? Even if you are on paid version as you are using dockerhub you will face another issue (retention) https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/

**Comment by cliveseldon** [comment]
https://github.com/kubeflow/manifests/issues/1668

**Comment by axsaucedo** [comment]
@omerfsen we just closed #1923 as this can be done with service account - this should be enough for your current situation as well, can you set up the imagePullSecrets with just a service account instead?

**Comment by omerfsen** [comment]
Hi @axsaucedo I saw that. I think that would be enough for now though secret must be created each namespace and each role on that namespace (possibly default and seldon-manager SA) though we wont have seldon-manager SA until we install seldon-core
