### ISSUE TITLE
Enable skip-certificate-verify on batch processor component

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2702]
Currently the batch processor component cannot work with self signed certificates. The underlying SeldonClient can be exposed through the client to allow unsecure / skip-ssl-verify to ensure it doesn't require the checks. For GRPC this woudl also be required to skip SSL check.

**Comment by omerfsen** [comment]
Also afaik batch processor does not support https istio ingress so

1. Able to define schema (http/https)
2. Skip ssl verify
3. Define different port number (as ingress gateway may run on different ports)

It is as defined #2638 which is just closed of being duplicate of this issue

**Comment by cliveseldon** [comment]
Close for larger refactor of Batch processor.
