### ISSUE TITLE
Allow user to disable gunicorn access logs

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#2705]
After upgrade to seldon-core python module v1.4
We found the following log lines in the model container:

```
127.0.0.1 - - [24/Nov/2020:19:42:44 +0000] “POST /predict HTTP/1.1” 500 290 “-” “python/gevent-http-client-1.3.1dev”
127.0.0.1 - - [24/Nov/2020:19:42:44 +0000] “POST /predict HTTP/1.1" 500 290 “-” “python/gevent-http-client-1.3.1dev”
```

Would be useful to have a config to allow users to disable these logs.

**Comment by anggao** [comment]
Looks like this method in `app.py` controls it

```
def accesslog(log_level: str) -> Union[str, None]:
    """
    Enable / disable access log in Gunicorn depending on the log level.
    """

    if log_level in ["WARNING", "ERROR", "CRITICAL"]:
        return None

    return "-"
```

`-` means stdout, it feels to me we should change the condition to `if log_level not in ["WARNING", "ERROR", "CRITICAL"]:` ?
@RafalSkolasinski

**Comment by cliveseldon** [comment]
Can you do a small PR for this @anggao ?

**Comment by adriangonz** [comment]
@anggao wouldn't it be enough to set the log level to `WARNING` or above to disable the access logs? Or is there a use case where you want both `INFO`-level and access logs?

If that's the case maybe we could have a separate flag for the access logs.

**Comment by anggao** [comment]
@cliveseldon sure I will do.

@adriangonz I feel we should only enable access log when debug level is higher than `WARNING` :) , but I agree add a new flag seems better, I will do a PR for that.
