### ISSUE TITLE
Using seldon-core-microservice how does one turn on SSL?

### ISSUE THREAD

**Issue by srajabi** [SeldonIO/seldon-core#2706]
Currently we're working towards getting Seldon installed within our OpenShift cluster but we're not there yet.

So for the interim we're using the custom Python wrappers with seldon-core-microservice. It seems this calls gunicorn directly from Python, which prevents me from providing a certfile like so: https://stackoverflow.com/a/14163851

What is the best way to provide the cert file to seldon-core-microservice? I don't see the argument for it in the command line.

It also doesn't seem to load the config from the environment like so:
https://github.com/benoitc/gunicorn/blob/20.0.4/gunicorn/app/base.py#L171
From their docs: https://docs.gunicorn.org/en/stable/settings.html the `GUNICORN_CMD_ARGS` parameter.

Please advise if I'm missing something.

Thanks!

**Comment by axsaucedo** [comment]
@srajabi the recommended way to enable SSL is through the Istio / Ambassador gateway, as opposed to on the microservice level. We do offer pod-level SSL, but this is not achieved through the seldon-core-microservice, but instead it's enabled through the service orchestrator which is the first point of contact to all rest requests. You can see how you can enable SSL in the example provided https://github.com/SeldonIO/seldon-core/blob/master/examples/security/ssl_requests/README.ipynb

You are also able to provide your own certificate. Currently we're still exploring the best way(s) to enable SSL, so this is a feature that is currently only on core capabilities, as most of our users do leverage the ingress providers to enable SSL. 

Having said that for now it seems this should address your approach for now.

**Comment by narasago** [comment]
Why is the SSL termination being tested with "-k" option which skips the secure verification? What needs to be done to have the cacert from the client side to be verified by the seldon server? Thanks in advance
