### ISSUE TITLE
Seldon deployment support for google kubernetes ingress

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#2714]
Hi,
I am aware that seldon supports ambassador ingress and istio ingress. Does it support an nginx ingress or a gke loadbalancer?

**Comment by cliveseldon** [comment]
We do have users using nginx and there is another issue open for this https://github.com/SeldonIO/seldon-core/issues/416
At present you would need to do the configuration yourself.
The same would be true for GKE w.r.t. authentication.

**Comment by divyadilip91** [comment]
@cliveseldon Thankyou for your immediate response. Ok so would this be solved in 2.0 release?

**Comment by cliveseldon** [comment]
I think we would need to look more deeply into handling further ingresses inside Seldon Core. As said, we have users who use both GCP and NGINX but manage the configuration outside Seldon Core themselves.

**Comment by divyadilip91** [comment]
Ok thankyou. Is there any document or references that I could refer and would help me out to set up this configuration outside of seldon core.?

**Comment by cliveseldon** [comment]
Not at present. I suggest looking at what is added in the code for Ambassador and in particular the connection to the service: https://github.com/SeldonIO/seldon-core/blob/f042f677bb2563276569ec8a78bb8ce7e19f2ff6/operator/controllers/ambassador.go#L197

**Comment by divyadilip91** [comment]
Ok thankyou
