### ISSUE TITLE
Question: Option to remove meta.requestPath from responses?

### ISSUE THREAD

**Issue by Atharex** [SeldonIO/seldon-core#2721]
When I issue a request to a model deployed behind Ambassador, I get in the response the meta.requestPath json. Though this is useful for debugging, I would also like to have an option to remove it from responses.

Now:
```
>>> curl -X POST -H "Content-Type: multipart/form-data" -F "binData=@mnist-pic.jpg" <ambassador-endpoint>/api/v1.0/predictions
{ 
  "jsonData": {
    "result": {
      "class": "4",
      "confidence": "0.963153"
    }
  },
  "meta": {
    "requestPath": {
      "mnist-images": "<my-private-container-registry-name-i-dont-want-in-a-response>/mnist-image-model:1.1"
    }
  }
}
```

Desired outcome:
```
>>> curl -X POST -H "Content-Type: multipart/form-data" -F "binData=@mnist-pic.jpg" <ambassador-endpoint>/api/v1.0/predictions
{ 
  "jsonData": {
    "result": {
      "class": "4",
      "confidence": "0.963153"
    }
  },
  "meta": {}  ##or also without this key
  }
}
```

Is there an option to remove this meta information from responses, or to not produce it in the first place? 

Using version 1.5.0 of Seldon Core Operator

**Comment by cliveseldon** [comment]
At present its not optional. Happy for a PR to allow it to be
https://github.com/SeldonIO/seldon-core/blob/3c943be7c8888c5b3986a51b8724659b40834f24/python/seldon_core/utils.py#L481

@RafalSkolasinski Any reasons not to?

**Comment by RafalSkolasinski** [comment]
I don't see any problems with making it optional. Probably configurable through environmental variable.

**Comment by cliveseldon** [comment]
Closing this for now. Please reopen if you plan to provide a PR. For V2 APIs we are investigating we will be more agnostic to service meshes and ingresses so you can have more freedom to build on top.
