### ISSUE TITLE
Document how to run python wrapper locally for development

### ISSUE THREAD

**Issue by narennadig** [SeldonIO/seldon-core#2722]
As suggested by @ryandawsonuk ,
In the python wrapper example given in the docs([Link](https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/iris.html?highlight=ir)is) ,  it doesn't tell that seldon-core provides a CLI, maybe adding that to the doc will make it easier as many devlopers like me  used to  build the docker image and then test it.

**Comment by ryandawsonuk** [comment]
This observation was made after @RafalSkolasinski pointed on [slack](https://seldondev.slack.com/archives/C8Y9A8G0Y/p1606399551250100) out that you can test locally by running:
```
seldon-core-microservice Model REST --service-type MODEL --log-level DEBUG --workers 10 --threads 10
```
from the folder that has Model.py, which will start the microservice running on localhost.

**Comment by narennadig** [comment]
Kool thanks

**Comment by RafalSkolasinski** [comment]
Renamed the issue so it is clear that this is about adding documentation.
