### ISSUE TITLE
Can not create seldondSeldonDeployment crd in k8s v1.19.2

### ISSUE THREAD

**Issue by simon-cj** [SeldonIO/seldon-core#2726]
## Describe the bug

we install seldon operator in k8s v1.19.2, but it is error to create crd. the error as follow:
```
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[graph].properties[children].items.type: Required value: must not be empty for specified array items
```
if we use https://github.com/SeldonIO/seldon-core/blob/master/operator/config/crd/bases/machinelearning.seldon.io_seldondeployments.yaml, there are ok.
but if we generate crd yaml by running `make manifests_v1`, it is not work. 

Need you help @cliveseldon

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
I tried with master on a 1.19.1 Kind cluster `make install_v1` and this worked.

The errors mentioned should all be fixed in v1 manifests by https://github.com/SeldonIO/seldon-core/blob/3c943be7c8888c5b3986a51b8724659b40834f24/operator/config/crd_v1/kustomization.yaml#L22-L38

**Comment by simon-cj** [comment]
Thanks for your reply， it is ok, we found it that we can not use the crd which is generate by `make manifests_v1`, by kustomize command, it patch some default value, now it works.
Thanks again.

**Comment by cliveseldon** [comment]
Will close, please reopen if still an issue.
