### ISSUE TITLE
MAB study case: use SeldonResponse for runtime metrics

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2728]
Now when we implemented [runtime metrics](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#runtime-metrics-and-tags) through usage of `SeldonResponse` we should make use of it in MAB study case.

See this conversation on recent PR: https://github.com/SeldonIO/seldon-core/pull/2723#discussion_r533436105

**Comment by RafalSkolasinski** [comment]
@midhun1998 The `SeldonResponse` code can be found here https://github.com/SeldonIO/seldon-core/blob/9fb1910100f24e0c20cbe652ea83f5996a5dabb8/python/seldon_core/user_model.py#L27-L51

And the usage is described in [here](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#runtime-metrics-and-tags).

**Comment by cliveseldon** [comment]
Closing as not currently prioritised.
