### ISSUE TITLE
Use f-strings in MAB study case examples

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2729]
Using f-strings may be cleaner solution

_Originally posted by @RafalSkolasinski in https://github.com/SeldonIO/seldon-core/pull/2723#discussion_r533456018_

**Comment by midhun1998** [comment]
Hi @RafalSkolasinski . I'm new to Seldon and find it pretty interesting. If this issue is still open can I take it up?

**Comment by RafalSkolasinski** [comment]
Hi @midhun1998, welcome to Seldon world! 

Yes!! The issue is still open :)

**Comment by RafalSkolasinski** [comment]
@midhun1998 if you planning to look into this one you may find https://github.com/SeldonIO/seldon-core/issues/2728 interesting as well as it touches the same code base

**Comment by midhun1998** [comment]
Thank you @RafalSkolasinski . Sure. Will definitely give it a try. 😀

**Comment by midhun1998** [comment]
Hi @RafalSkolasinski . Could you please share an example file where you have implemented `SeldonResponse ` class for runtime metrics. I tried to go through to understand but couldn't. Thanks.

**Comment by RafalSkolasinski** [comment]
@midhun1998, sure, I replied in https://github.com/SeldonIO/seldon-core/issues/2728
