### ISSUE TITLE
Seldon component exit on failure without passing to next component in the seldon graph

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#2730]
Hi team,

My current scenario uses a seldon graph containing two components chained together - that is 2 models.
INPUT----> MODEL1------> MODEL2------> OUTPUT.
I have included error handling in the code for both components.
So my query is, if model1 fails ,can it return the error directly to the user after exiting the seldon graph rather than passing the error to the model2 which will inturn return the error of model2 to the user which is wrong coz the main error that occured was in model1 and the user should see the error message of model1 rather than model2.
Kindly help if there is some solution existing to solve this.

**Comment by cliveseldon** [comment]
If you return an exception or non-200 it should fail immediatly

**Comment by divyadilip91** [comment]
Hi @cliveseldon ,

Is this possible only if I use the seldon UserCustomException for handling exceptions?
My current code has exceptions handled in this manner. 

< try:
            print("hello")
except Exception as e:
            logging.error(e,sys.exc_info())
            return {"error":str(sys.exc_info())} >``
I find that the error is returned to the second component rather than exiting from the first component.
Is there something that I have missed by which it doesnt exit?
Awaiting your reply

**Comment by cliveseldon** [comment]
yes - as in above you would be a 200 OK result returned.

**Comment by divyadilip91** [comment]
Ok..so if I want to exit from the first component , I need to use the seldon custom exception ?

**Comment by cliveseldon** [comment]
Yes

**Comment by cliveseldon** [comment]
You can also have a router after the first model and return -2 see https://docs.seldon.io/projects/seldon-core/en/latest/analytics/routers.html
This way you can keep your current design

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
