### ISSUE TITLE
Add the ability to define custom annotations in the Helm Chart

### ISSUE THREAD

**Issue by pierluigilenoci** [SeldonIO/seldon-core#2735]
For many reasons (i.e: the selection of node pools in which to run the software, cost allocation, network policies, etc) it is useful to be able to add annotations to the deployments in the cluster.

**Comment by cliveseldon** [comment]
Are you saying you want a set of annotations that are added to every Deployment created?

**Comment by pierluigilenoci** [comment]
Hi @cliveseldon,
I mean that I want to add labels and annotations to the `seldon-controller-manager` deployment. To be more specific here: https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml#L23-L31

**Comment by cliveseldon** [comment]
Yes, that makes sense. Will add to 1.6.

**Comment by cliveseldon** [comment]
Annotations are now possible for the seldon manager. Please reopen if still an issue

**Comment by pierluigilenoci** [comment]
Thank you @cliveseldon and what about #2860?
