### ISSUE TITLE
remove requirements_server.txt from alibi-detect-server

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2736]
A redundant requirements file is present. It shall be removed.

File: https://github.com/SeldonIO/seldon-core/blob/master/components/alibi-detect-server/requirements_server.txt

**Comment by RafalSkolasinski** [comment]
Actually, the `requirements_server.txt` is used to provide more reproducible `Docker` builds. 
We could explore replacing `adserver`'s `setup.py` with [pyproject.toml](https://github.com/SeldonIO/seldon-core/issues/2584) and build Docker image from a lock file.

**Comment by cliveseldon** [comment]
We now use Poetry so will close this.
