### ISSUE TITLE
Error when using the R language wrapper

### ISSUE THREAD

**Issue by FarrandTom** [SeldonIO/seldon-core#2744]
## Describe the bug

When trying to deploy either of the R models which Seldon Core provides (be it [this skeleton](https://github.com/SeldonIO/seldon-core/tree/master/incubating/wrappers/s2i/R/test/model-template-app), or [the iris example](https://github.com/SeldonIO/seldon-core/tree/master/incubating/examples/r_iris)) the model endpoint always returns a HTTP 500 error:
`<simpleError: Argument 'txt' must be a JSON string, URL or file.>`

For reference the payloads that have been tested are:
1. `{"data":{"ndarray":[1, 2]}}`
2. `{"jsonData": [1, 2]}`
3. `{"data":{"names":["a","b"],"ndarray":[[1.0,2.0]]}}`

All of these payloads return the same error. The container works locally and when tested with the `seldon-core-tester`, but fails when deployed onto the Seldon Deploy platform. API calls have been made to the model both via cURL and via the UI- both resulting in the same error.

## To reproduce

1. Train and save your iris model. 
2. Containerise using s2i
3. Test locally using `seldon-core-tester`
4. Push image to registry
5. Deploy onto Seldon Deploy cluster
6. Submit request to endpoint --> 500 error

## Expected behaviour

A submitted request should return a 200 status code, and a prediction based upon the data provided.

## Environment

Seldon Deploy 0.8.2

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by omerfsen** [comment]
+1
