### ISSUE TITLE
Ability to use Rest as input, from the user, and use grpc internally

### ISSUE THREAD

**Issue by zewelor** [SeldonIO/seldon-core#2751]
From what I understand, currently its not possible to send request via rest in json, and have services communication, using grpc ? I think it would be useful to allow Rest requests, from the outside, but inter children communication, in graph, to be handled via grpc.

**Comment by mwm5945** [comment]
@cliveseldon isn't this similar to https://github.com/SeldonIO/seldon-core/issues/2299, which was fixed?

**Comment by cliveseldon** [comment]
It similar but at present if your request comes in externally as REST it will stay as REST. I think the proposal here is to allow internal calls in the inference graph to be GRPC for speed but allow external calls to be REST.

**Comment by zewelor** [comment]
@cliveseldon Good summary, that's what I had in mind. For developers it would be easier to use JSON, but for internal communication in graph, probably grpc will have more benefits for speed, both data transfer and serialization / deserialization ?

**Comment by mwm5945** [comment]
(adding here form slack)
It would also be nice to have the opposite be true. I.e. connect fo the executor via GRPC, and the executor connects to the node via REST. Specifically, this would be helpful for wrappers that don't support GRPC (I.e. R, JNI)

**Comment by cliveseldon** [comment]
Closing as going forward we will use V2 servers which support both for custom and standard models.

**Comment by zewelor** [comment]
Whats the v2 servers ?
