### ISSUE TITLE
Create a thinner Java package for the JNI wrapper

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#2759]
The new JNI wrapper leverages the Python inference server for all the networking. However, it still points to the `io.seldon.wrapper:seldon-core-wrapper` which also includes Spring and a set of other unused dependencies.

It would be good to consider creating a new lighter Java package which only contains the minimum business logic (i.e. the model interface), removing all of these unused dependencies.

**Comment by cliveseldon** [comment]
Part of MLServer roadmap. So closing here.
