### ISSUE TITLE
Storage initialiser does not work with IAM roles

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2760]
Currently the storage initialiser only works with s3 bucket permissions as it uses the minio client. This is being fixed via https://github.com/kubeflow/kfserving/pull/1130.

**Comment by RafalSkolasinski** [comment]
Also the related issue in kfserving: https://github.com/kubeflow/kfserving/issues/831

**Comment by cliveseldon** [comment]
KfServing storage initializer is deprecated.

**Comment by AlexandreBrown** [comment]
@cliveseldon Could you provide more information and sources? Thanks

**Comment by cliveseldon** [comment]
There are docs [here](https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html) and an example [here](https://docs.seldon.io/projects/seldon-core/en/latest/examples/rclone-upgrade.html)
