### ISSUE TITLE
TestTagsPythonS2iK8s.test_model_combiner_grpc is flaky

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2785]
It seems that test `TestTagsPythonS2iK8s.test_model_combiner_grpc` is flaky. 

It did fail here: https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/19.log
Passed in next run: https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/20.log
## To reproduce
Seems to be reproducible when running integration tests locally.

## Expected behaviour

Tests passes. 

## Environment

Kind cluster.

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Closing as test flakiness has been addressed. Can open new issue for test updates and CI improvements.
