### ISSUE TITLE
Helm failing to fetch https://kubernetes-charts.storage.googleapis.com/ resulting in failing tests

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2808]
Currently helm is failing when fetching `https://kubernetes-charts.storage.googleapis.com/`.

The logs appear as follows:
```
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
Error: looks like "https://kubernetes-charts.storage.googleapis.com/" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

This issue does seem to appear quite a lot online and seems it may not be necessary so the fix may just require removing that from the helm install (eg https://stackoverflow.com/questions/61954440/how-to-resolve-https-kubernetes-charts-storage-googleapis-com-is-not-a-valid)

**Comment by ssainz** [comment]
Solved this problem by removing the registry config file and cached repository indexes. 

type `helm | grep registry-config` and `helm | repository-config` to find the default location, and then delete them.

**Comment by doschkinow** [comment]
This workaround does not work for me. I am having the same issue, but with https://svc-catalog-charts.storage.googleapis.com:

(base) [opc@bastion ~]$ helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
Error: looks like "https://svc-catalog-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://svc-catalog-charts.storage.googleapis.com/index.yaml : 403 Forbidden
(base) [opc@bastion ~]$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

This worked in the past, wondering what has changed...

**Comment by jlamb1** [comment]
@doschkinow google retired that URL and threw a 401 instead of a 301 for some reason. You want to use https://charts.helm.sh now. something like `helm init --stable-repo-url https://charts.helm.sh/stable`

**Comment by doschkinow** [comment]
@jlamb1 Thanks! But this does not help:

[opc@frankfurt ~]$ helm repo list
NAME    URL
stable  https://charts.helm.sh/stable
gitpod  https://charts.gitpod.io
[opc@frankfurt ~]$ helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
Error: looks like "https://svc-catalog-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://svc-catalog-charts.storage.googleapis.com/index.yaml : 403 Forbidden

I need the svc-cat charts from https://svc-catalog-charts.storage.googleapis.com, they are not in the stable helm repo.

**Comment by doschkinow** [comment]
resolved: a workaround for me was to get the service catalog charts not from google but directly from github:

helm repo add svc-cat https://kubernetes-sigs.github.io/service-catalog

Still would be interesting to know why https://svc-catalog-charts.storage.googleapis.com does not work ...

**Comment by Eugst** [comment]
`helm repo add "stable" "https://charts.helm.sh/stable" --force-update`
https://helm.sh/blog/new-location-stable-incubator-charts/

**Comment by nkovacic** [comment]
`helm repo add "stable" "https://charts.helm.sh/stable" --force-update` gives me an Error: unknown flag: --force-update on helm 3.x.

Directly using `helm repo add "stable" "https://charts.helm.sh/stable"` works.

**Comment by ozbillwang** [comment]
https://helm.sh/blog/new-location-stable-incubator-charts/

```
helm repo add "stable" "https://charts.helm.sh/stable"
helm repo add "common" https://charts.helm.sh/incubator
helm repo update
```

**Comment by ye** [comment]
`--force-update` seems to be a Helm v3 version directive. If you are on helm v2, leaving that part out should work.
