### ISSUE TITLE
Simplify initial workflow through automated project template creation with Cookiecutter

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2825]
Currently project creation can be carried out by following the steps in the documentation, however these can be standardised and streamlined by leveraging automated project template creation tools such as cookiecutter.

Cookiecutter is "A command-line utility that creates projects from cookiecutters (project templates), e.g. Python package projects, VueJS projects. " https://github.com/cookiecutter/cookiecutter

This issue would consist of creating a cookiecutter base that can allow projects to be created for prepackaged model servers and custom servers. initially both would be for simple single node graphs, but it could be explored later on to extend further cookiecutter commands to enable addition of further graph components.

**Comment by cliveseldon** [comment]
Closing until we look at MLServer and V2 improvements.
