### ISSUE TITLE
Automatic Python SDK generation from OpenAPI Swagger Schema

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2826]
To simplify maintenance of the Seldon Client, we could leverage tools like https://swagger.io/docs/open-source-tools/swagger-codegen/ to automatically generate the SDK files required to interact with the REST API. We can also explore for tools that can aid on the automatic generation for GRPC specificlaly using the proto files.

**Comment by cliveseldon** [comment]
closing for now - need to revisit for v2
