### ISSUE TITLE
curl not found error

### ISSUE THREAD

**Issue by paudan** [SeldonIO/seldon-core#283]
During deployment of test models, Kubernetes dashboard produces an error: 

Liveness probe failed: Get http://172.17.0.24:8082/ready: dial tcp 172.17.0.24:8082: getsockopt: connection refused
Exec lifecycle hook ([/bin/sh -c curl 127.0.0.1:8000/pause && /bin/sleep 5]) for Container "seldon-container-engine" in Pod "deep-mnist-single-model-svc-orch-6b5c55bb97-7bjng_seldon(a3704d8b-e0f3-11e8-8dac-00155d09a30d)" failed - error: command '/bin/sh -c curl 127.0.0.1:8000/pause && /bin/sleep 5' exited with 127: /bin/sh: curl: not found , message: "/bin/sh: curl: not found\n" 

Does it mean that curl is not installed in created pod? I see numerous errors like this, while looking at the pods list of the model deployment

**Comment by cliveseldon** [comment]
This fix should be available in 0.2.4-SNAPSHOT images
