### ISSUE TITLE
Ready check of SeldonRestApi is failing with "error":"dial tcp [::1]:9000: connect: connection refused"

### ISSUE THREAD

**Issue by Manibharathi476** [SeldonIO/seldon-core#2834]
Hello,

I tried to deploy seldon-single-model helm chart [https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-single-model](url). Used this helm chart to deploy a single model. On deploying it, 2 containers were created and they are model and seldon-container-engine. Seldon-container-engine is failing.

logs of seldon-container-engine is:

{"level":"info","ts":1610469395.5589485,"logger":"entrypoint","msg":"Hostname unset will use localhost"}
{"level":"info","ts":1610469395.5630333,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1610469395.5630815,"logger":"entrypoint","msg":"Starting","worker":2}
{"level":"info","ts":1610469395.5630891,"logger":"entrypoint","msg":"Starting","worker":3}
{"level":"info","ts":1610469395.5630934,"logger":"entrypoint","msg":"Starting","worker":4}
{"level":"info","ts":1610469395.563097,"logger":"entrypoint","msg":"Starting","worker":5}
{"level":"info","ts":1610469395.564216,"logger":"entrypoint","msg":"Running http server ","port":8000}
{"level":"info","ts":1610469395.564228,"logger":"entrypoint","msg":"Creating non-TLS listener","port":8000}
{"level":"info","ts":1610469395.5646167,"logger":"entrypoint","msg":"Running grpc server ","port":5001}
{"level":"info","ts":1610469395.5646267,"logger":"entrypoint","msg":"Creating non-TLS listener","port":5001}
{"level":"info","ts":1610469395.564681,"logger":"entrypoint","msg":"Setting max message size ","size":2147483647}
{"level":"info","ts":1610469395.566125,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
{"level":"error","ts":1610469418.7026064,"logger":"SeldonRestApi","msg":"Ready check failed","error":"dial tcp [::1]:9000: connect: connection refused","stacktrace":"github.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).checkReady\n\t/workspace/api/rest/server.go:177\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.handleCORSRequests.func1\n\t/workspace/api/rest/middlewares.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.CORSMethodMiddleware.func1.1\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/middleware.go:51\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.xssMiddleware.func1\n\t/workspace/api/rest/middlewares.go:87\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1\n\t/workspace/api/rest/middlewares.go:47\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1\n\t/workspace/api/rest/middlewares.go:79\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2036\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2831\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1919"}

Please help me resolve this!

**Comment by cliveseldon** [comment]
Can you just the other container has started successfully?

**Comment by Manibharathi476** [comment]
yes, the other container started successfully.

**Comment by cliveseldon** [comment]
Which version of seldon core and what is the version of the model container image?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.

**Comment by AmyHoney** [comment]
> I also encountered the same issue. seldon core version is 1.14/stable, model container image is seldonio/mlflowserver:1.14.0-dev. This issue was closed, but I still don't know how to solve this issue. Please help me resolve this!

**Comment by cliveseldon** [comment]
Suggest you test with latest and open an issue with more details of your environment after testing the basic examples to validate they work.

**Comment by leo83** [comment]
Have the same issue.
Versions: 
- kind version 0.20.0
- seldon-core-operator:1.17.1
- istio-1.20.1

try to apply this yaml
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: some-mail-model
spec:
  name: some-mail-deployment
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: "gs://my-mdodel-store/4461760cde7f4bfdb8196daa1fc97695/artifacts/some-mail-classifier-catboost"
        name: mail-classifier
      name: some-mail-graph
      replicas: 1
```

`*-initialiser` container have run successfully.

`seldon-core-engine` container produces following error during startup

```
{"level":"error","ts":1704378693.0525522,"logger":"SeldonRestApi","msg":"Ready check failed","error":"dial tcp [::1]:9000: connect: connection refused","stacktrace":"net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/seldonio/seldon-core/executor/api/rest.handleCORSRequests.func1
	/workspace/api/rest/middlewares.go:64
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/gorilla/mux.CORSMethodMiddleware.func1.1
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/middleware.go:51
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/seldonio/seldon-core/executor/api/rest.xssMiddleware.func1
	/workspace/api/rest/middlewares.go:87
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1
	/workspace/api/rest/middlewares.go:47
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1
	/workspace/api/rest/middlewares.go:79
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2879
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1930"}
```

**Comment by leo83** [comment]
Closed without solution - very nice!
