### ISSUE TITLE
Broken Link to Documentation Example I'd like to find if it exists

### ISSUE THREAD

**Issue by ntorba** [SeldonIO/seldon-core#2836]
## Describe the bug

On the README provided in the [seldon-core/examples/models directory](https://github.com/SeldonIO/seldon-core/tree/master/examples/models), there is a broken link for a Keras MNIST Classifier example. 

If that example does exist, I would like to find it, because I am running into [this issue](https://github.com/SeldonIO/seldon-core/issues/2220) with my current attempt to serve a keras model. 

## To reproduce

Navigate to https://github.com/SeldonIO/seldon-core/tree/master/examples/models and click on on the link for [Keras MNIST Classifier](https://github.com/SeldonIO/seldon-core/blob/master/examples/models/keras_mnist/keras_mnist.ipynb)

## Expected behaviour

Take to example

**Comment by ntorba** [comment]
I just checked and it seems all of the example links on that page are broken

**Comment by cliveseldon** [comment]
We have removed those links. The docs should be used for examples.
