### ISSUE TITLE
OpenAPI Swagger spec does not mention jsonData

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2838]
Currently Swagger OpenAPI spec does not refrence jsonData, so we should update the spec to reflect this

**Comment by joehoeller** [comment]
What’s the status on this? I’m struggling to get Seldon the json spec from Seldon, and then read by OpenAPI.

I did find this thread here: https://github.com/SeldonIO/seldon-core/issues/1855 , and am going to try the operator. 

Is everything I need to run that in that thread though? Plz validate(?)

**Comment by cliveseldon** [comment]
As we are focusing on V2 Protocol going forward will close this unless specific users want to reopen.
