### ISSUE TITLE
FlatBuffers support

### ISSUE THREAD

**Issue by paudan** [SeldonIO/seldon-core#284]
After deploying one of the example models, I tried to execute command to test FlatBuffers support

`tester.py contract.json 0.0.0.0 5000 -p --fbs`

as described in [here](https://github.com/SeldonIO/seldon-core/blob/master/docs/api-testing.md#seldon-api-tester) and it failed,  producing an error: 

```
----------------------------------------
SENDING NEW REQUEST:
('Will send', 18560, 'bytes')
Traceback (most recent call last):
  File "../../../wrappers/testing/tester.py", line 275, in <module>
    run_predict(args)
  File "../../../wrappers/testing/tester.py", line 256, in run_predict
    arr = SeldonRPCToNumpyArray(data)
  File "/home/user/seldon-core/wrappers/testing/tester_flatbuffers.py", line 81, in SeldonRPCToNumpyArray
    raise flatbuffers.FlatbuffersInvalidMessage("Message is not of type DefaultData")
AttributeError: 'module' object has no attribute 'FlatbuffersInvalidMessage'
```

Does it mean, that FlatBuffers support is still experimental? While it is clearly a Python import error, exception also states, that message is not compatible with FlatBuffers. Note, that gRPC testing was OK, and ended up in returning some predictions, as expected

**Comment by cliveseldon** [comment]
FlatBuffers is still experimental and not supported. There is an initial implementation in the python wrappers. If you are using the tester it would imply that your local environment does not have the python FlatBuffers library installed.

**Comment by paudan** [comment]
Apparently, FlatBuffers is installed:
`flatc --version` outputs `flatc version 1.10.0 (Oct 25 2018 14:19:21)`
`pip show flatbuffers`:

```
Metadata-Version: 1.0
Name: flatbuffers
Version: 20181025110722
Summary: The FlatBuffers serialization format for Python
Home-page: https://github.com/google/flatbuffers
Author: FlatBuffers Contributors
Author-email: me@rwinslow.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages/flatbuffers-20181025110722-py2.7.egg
```
During deployment, I also ran `make build_fbs` and it did not produced any errors.

**Comment by cliveseldon** [comment]
Not a priority. Please reopen if demand.
