### ISSUE TITLE
Specification of a Service Account

### ISSUE THREAD

**Issue by elliers** [SeldonIO/seldon-core#286]
We noticed that the seldon cluster manager does not specify a service account for the seldon engine pod, and adding that configuration is not exposed to the user. In our k8s cluster, a pod security policy is set up such that the service accounts running each pod need to be able to use the psp. Since no service account is specified, the default service account is used, but we do not want to give the default service account permission to use the psp. It would be nice if the cluster manager allowed the specification of a service account.

**Comment by cliveseldon** [comment]
@elliers Can you test this PR? You will need to rebuild the cluster-manager image for 0.2.4-SNAPSHOT to test.
