### ISSUE TITLE
Raise common version compatibility exceptions

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#2862]
When using certain frameworks, compatibility between artifacts and inference environments depends heavily on the Python version and the libraries versions. For example, SKLearn artifacts trained in Python 3.6 probably won't work in Python 3.7, and models trained with older versions of SKLearn won't work on newer versions either. 

Usually, these errors surface at init time, during artifact loading. However, they usually carry  very obscure messages (e.g. differences in the `pickle` protocol, missing fields on a class definition, etc.). 

To make these errors more meaningful to the user, it would be good to catch well-known exceptions coming from compatibility errors and re-raise them as something more meaningful (e.g. `Artifact trained with incompatible version of SKlearn, should be X.Y.Z`).

**Comment by cliveseldon** [comment]
Closing as is MLServer issue now.
