### ISSUE TITLE
Docker image "seldonio/seldon-core-s2i-python3" uses old Python 3.6

### ISSUE THREAD

**Issue by oshev** [SeldonIO/seldon-core#288]
The latest Python stable release is 3.7. It would be great to have an model serving with the latest Python. Thanks!

**Comment by cliveseldon** [comment]
This was the issue: https://github.com/tensorflow/tensorflow/issues/20444

Which is referenced in https://github.com/SeldonIO/seldon-core/blob/master/wrappers/s2i/python/build_python3.sh

Need to ensure this is fully fixed. I see the issue is closed.

**Comment by oshev** [comment]
Yes, I'm not sure they fixed TF for Python 3.7. I was investigating a bit a couple of weeks ago and it seemed to be WIP but I'm not sure.

However, it's only an issue if you use TF in model serving. In all other cases - PyTorch, XGBoost, Scikit-learn - there is no problem at all.

**Comment by cliveseldon** [comment]
Maybe one solution is to have multiple variants of the python wrappers for python 3, so python3.6 and python3.7 versions.

**Comment by oshev** [comment]
That would be great!

**Comment by cliveseldon** [comment]
@oshev If you could test the newly pushed python wrapper images - see #290 for details

**Comment by oshev** [comment]
I've tried to build new model containers and it seems to work fine! Just in case, tried to SSH into the container and got there Python 3.7 indeed. Thank you so much! That was fast. :-)
