### ISSUE TITLE
Add default /health/status implementation for models

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#2899]
Currently, the models expose the `/health/status` endpoint. However, this endpoint is only active when you explicitly override the `health_status` method of your model class. 

When that method is not overriden, the endpoint will just return a `400`. It would be good to, instead, fallback to a default behaviour for `/health/status` similar to `/health/ping` (which can still be later overriden by extending the `health_status` method).

**Comment by nadinet** [comment]
Fixed by: #3023
