### ISSUE TITLE
CR reference in documentation contains irrelevant parts of seldondeployment_types.go

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#2901]
The [CR reference page in docs](https://docs.seldon.io/projects/seldon-core/en/latest/reference/seldon-deployment.html) contains block of codes that are not relevant to the struct definitions (it actually starts in the middle of a function showing only closing `}` brackets and `return nil` statement.

**Comment by axsaucedo** [comment]
@RafalSkolasinski good shout, this is because there is a line crop in the include, which you can see in the docs https://github.com/SeldonIO/seldon-core/blob/master/doc/source/reference/seldon-deployment.rst

**Comment by axsaucedo** [comment]
Ok Added a very quick one it seems it just required a +40 (well -40) https://github.com/SeldonIO/seldon-core/pull/2905

**Comment by RafalSkolasinski** [comment]
Just wonder if everything at the end is also relevant, this does not really look like it
```
func init() {
	SchemeBuilder.Register(&SeldonDeployment{}, &SeldonDeploymentList{})
}
```
