### ISSUE TITLE
Remove all references to contract.json in examples

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#2913]
The contract.json is no longer the standard way to show how to interact with models, and there were initial efforts to update most examples to reflect the more comon ways of interacting with the deployed seldon models. There are still however a handful of examples that still use the contract.json approach, so this issue will just require updating the remaining examples to work using the seldon python client directly (or using curl)

**Comment by omerfsen** [comment]
What do we use instead of contract.json? For example R model examples still uses it.

**Comment by axsaucedo** [comment]
@omerfsen this was actually in context of the R exampel, as a user was confused trying to send the request as it currently is in the contract.json. 

FOr the iris R example you woulld just use a normal curl like:
```
curl -v -X POST -H 'Content-Type: application/json' \\\n",
    -d '{"data": {"ndarray": [[0,1,2,3]], "names": ["sepal_length", "sepal_width", "petal_length", "petal_width"] }}'",
    http://localhost:80/seldon/default/seldon-deployment-example/api/v1.0/predictions"
```

**Comment by cliveseldon** [comment]
Think we can close this now.
