### ISSUE TITLE
packaging for python microservice wrapper

### ISSUE THREAD

**Issue by kalefranz** [SeldonIO/seldon-core#293]
Hello,

I'm a maintainer on the conda project, and we're interested in having the python microservice wrapper code in this repo be packageable as a conda package.  As it exists right now, without a proper `setup.py` python project configuration file, the package wouldn't be as clean as it otherwise could be.  Would you be open to a pull request with some moderate refactoring that would make https://github.com/SeldonIO/seldon-core/tree/cac15ba/wrappers/python more easily distributed as a conda package (and also able to be distributed as standard package on PyPI)?

I've got potential WIP code at https://github.com/kalefranz/seldon-python-microservice showing what the changes might look like.  If you're open to it and have any thoughts, comments, or advice before I open the PR, happy to take the feedback early.

**Comment by cliveseldon** [comment]
Hi,

 This looks great. We were planning on cleaning up the python code so this is very timely. Some points:

  * Would your PR make this part of the seldon-core codebase or are you working on extracting the code to a separate code base? 
     * There are proto buffer and flatbuffer dependencies that need to match a seldon-core version so we need to consider this as part of the clean up (see #290)
  * There have been some recent updates with extra pytests that need to be included.
  * The version of the package needs to match Docker images for Python 2,3 (3.6 and 3.7). So we need to discuss how this is maintained separately or as part of this work. Python 3 is complex as python 3.7 has issues with TensorFlow so only python 3.6 is safe at the moment. ( see #288)

 @jklaise was planned to work on python cleanup so we should all get together to discuss.

**Comment by jklaise** [comment]
@kalefranz We are planning a python package for the wrappers and client commands to make the whole process of wrapping images and testing live deployments easier. We will host this within the main seldon-core repo and are keen to make it installable from pip and conda. Would you like to connect on Slack to discuss your ideas?

**Comment by jklaise** [comment]
@kalefranz I've started work on the Python package, it would be great if you could review it, especially re. conda recipe: https://github.com/SeldonIO/seldon-core/pull/306

**Comment by jklaise** [comment]
Closing via #306. A release on PyPI to follow together with a new release of Seldon Core. A release on conda-forge to follow shortly after, opened an issue at #341 @kalefranz .
