### ISSUE TITLE
Seldon Batch Template Bug?

### ISSUE THREAD

**Issue by snowneji** [SeldonIO/seldon-core#2943]
## Describe the bug

I'm using the helm template here to experiment a batch processing pipeline with Seldoncore.

In this file: https://github.com/SeldonIO/seldon-core/blob/master/examples/batch/argo-workflows-batch/helm-charts/seldon-batch-workflow/templates/workflow.yaml, line 69-70, shouldn't  `containers` be under `spec` instead of in a list at the same level?

Also locally I'm getting this error using the helm template which possibly confirms the issue, so I guess the hierarchy issue cause the error?
```
The SeldonDeployment "seldon-7ceba0fc-4fd9-416f-8d92-46ed3e577f62" is invalid: spec.predictors.componentSpecs.spec: Invalid value: "null": spec.predictors.componentSpecs.spec in body must be of type object: "null"
```

**Comment by RafalSkolasinski** [comment]
Hi @snowneji, what version of:
- helm
- SC
- kubernetes
do you run?
