### ISSUE TITLE
seldon-batch-processor Install Instruction Missing

### ISSUE THREAD

**Issue by snowneji** [SeldonIO/seldon-core#2956]
Hello, I've been exploring the batch processing of SeldonCore, but I couldn't find documentation that shows how to install the `seldon-batch-processor`.  Can anyone show me how to do it? And is it possible to add it to the documentation like here: https://docs.seldon.io/projects/seldon-core/en/latest/servers/batch.html

**Comment by omerfsen** [comment]
it comes default by any docker images but you can install locally on your machine with 

```bash
pip3 install seldon-core

```

**Comment by snowneji** [comment]
@omerfsen Thanks for the help. Just wondering is this the correct image? `seldonio/seldon-core-s2i-python3`

**Comment by omerfsen** [comment]
> @omerfsen Thanks for the help. Just wondering is this the correct image? `seldonio/seldon-core-s2i-python3`

all `seldon-core-s2i-pythonxx` images have it

**Comment by snowneji** [comment]
@omerfsen Actually I found an issue in the Docker images. In `setup.py` the entry_points does not include `seldon-batch-processor`. But in the Github repo `setup.py` has that:https://github.com/SeldonIO/seldon-core/blob/master/python/setup.py

My screenshot of the setup.py in the Docker image:
![image](https://user-images.githubusercontent.com/10824322/108093762-b19e6680-7043-11eb-8146-3512923cf076.png)

**Comment by snowneji** [comment]
I guess it has to do with versions. The default `seldon-core` pkg in the image `seldon-core-s2i-python3:0.18` is `1.0.2`, which doesn't have the batch-processing functionality. Just wondering which version of the image contains the batch processor?

**Comment by axsaucedo** [comment]
From memory, batch processing may not have been introduced until around version 1.2.x

**Comment by snowneji** [comment]
1.2.0 handles both real-time and batch well, thanks for the help!
