### ISSUE TITLE
Enable Mounting Model Checkpoint PV as ReadWrite

### ISSUE THREAD

**Issue by ashrafgt** [SeldonIO/seldon-core#2982]
## Feature Description:
Enable configuring the access mode of the volume mount used for model checkpoints (`/mnt/models`) which is currently fixed to `ReadOnly`:
https://github.com/SeldonIO/seldon-core/blob/bc038c5a0744fbaf0268c086e9601760b61e602d/operator/controllers/model_initializer_injector.go#L177

## Example Usecase:
When deploying prediction servers for models based on `torch.hub`, we try to point the cache directory to `/mnt/models` in order for Torch Hub to find the already downloaded checkpoint and use it instead of trying to download it again (and fail, because it tries to download to `/.cache`, which is not permitted). Unfortunately, Torch Hub will try to create temporary files directories in that cache directory, but because it's `ReadOnly`, an exception is raised, and the model can't be loaded.

## Implementation Suggestion:
Add a new `modelReadOnly` attribute to inference `graph` objects in `SeldonDeployment`, with a default value of `true`. In addition, the attribute would be configurable in the `seldon-single-model` helm chart (and other charts where applicable).

**Comment by axsaucedo** [comment]
@ashrafgt this use-case sounds interesting, could you share your pytorch wrapper code to see what the logic to read the torch-hub component is?

**Comment by ashwin-borneo** [comment]
Hi 
Is this issue fixed? I have similar use case where I am using paddleOCR and it needs access to .cache as well.

**Comment by adriangonz** [comment]
Hey @ashrafgt @ashwin-borneo ,

Torch's cache folder can be controlled through the `TORCH_HOME` env var. So pointing this to a folder with write access should sort this out (e.g. `TORCH_HOME=/mnt/models` or `TORCH_HOME=/microservice`).

Feel free to reopen if you still find issues with that workaround.
