### ISSUE TITLE
Make Seldon Client REST requests more efficient

### ISSUE THREAD

**Issue by sebov** [SeldonIO/seldon-core#3001]
Hello All!
Right now using the client's methods/functions you will encounter a flow like:
```python
    ...
    elif json_data is not None:
        request = json_to_seldon_message({"jsonData": json_data})
    ...
    payload = seldon_message_to_json(request)

    response_raw = requests.post(..., data={"json": json.dumps(payload)},)
    # or 
    response_raw = requests.post(..., json=payload,)
```

For my case where the input json_data is large (~ 4-5 MB) and represents payload passed to a tensorflow model in the 'inputs'-like format described, e.g., here https://www.tensorflow.org/tfx/serving/api_rest, the total request time is ~4-6 seconds.
I also measured two things:
- doing `seldon_message_to_json(json_to_seldon_message({"jsonData": json_data}))` separately takes ~4-5 seconds
- invoking REST directly, e.g., in console or through python's requests package, takes ~0.6-0.7 seconds

Would it be possible to add some bypassing logic for that case, i.e., get rid of the back and forth serialization json -> SeldonMessage -> json? Or maybe it is just justified from the architectural point of view and should be left as is?

**Comment by cliveseldon** [comment]
For low latency grpc or direct requests usage would be best. We are exploring a new way to interact with Seldon models which we will release soon.

**Comment by rohan-wadhavkar** [comment]
Hi. Facing the same issue in which seldon_message_to_json method takes a long time with large json inputs. Have there been any updates such as bypassing the method as @sebov mentioned or are there any recommended approaches for sending large json inputs?
