### ISSUE TITLE
Torchserve support

### ISSUE THREAD

**Issue by boniek83** [SeldonIO/seldon-core#3002]
Support serving pytorch models via torchserve.  Provide prepackaged model server.

**Comment by axsaucedo** [comment]
@boniek83 thank you for opening the issue - maybe we should make it more explicit in the docs, but currently pytorch models are supported via the Triton prepackaged server support https://docs.seldon.io/projects/seldon-core/en/latest/servers/triton.html Closing this issue, please reopen if there are areas where triton doesn't fully cover

**Comment by boniek83** [comment]
What about AMD GPUs (rocm). Does Triton support them?

**Comment by axsaucedo** [comment]
Triton uses a vanilla pytorch backend, so it should support the same capabilities https://github.com/triton-inference-server/pytorch_backend - having said that, we haven't tried running on AMD, so would be great to confirm

**Comment by boniek83** [comment]
@axsaucedo It doesn't work. Whatever backend it uses it is NVidia specific.
