### ISSUE TITLE
Azure credentials can't be configured via service account

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3003]
## Describe the bug

Currently only Google Cloud and S3 are supported through the [service account configuration option](https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html#adding-credentials-for-google-cloud). In order to be aligned with the secrets configuration of KFServing, it would be required to extend the current logic to also support the secret provisioning for azure secrets.

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Closing as assume this is fixed via Rclone. Reopen if needed
