### ISSUE TITLE
Cannot create new SeldonDeployment after seldon-core automatic  update from 1.5 to 1.6

### ISSUE THREAD

**Issue by FrancescoFanchin** [SeldonIO/seldon-core#3005]
## Describe the bug

After seldon-core automatic update, from 1.5 to 1.6, we are not able to create a new SeldonDeployment from yaml file.
The following error message appears:
"Error "failed calling webhook "v1.mseldondeployment.kb.io": Post https://seldon-webhook-service.xxxxxxxxxxxxxxxx/mutate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Seldon")" for field "undefined".

## To reproduce

1. Go to Seldon Operator
2. Create Seldon Deployment
3. Insert a yaml template that is expected to work (e.g. default mock classifier)

## Expected behaviour

Seldon Operator should create a new SeldonDeployment.

## Environment

Openshift 4 on Azure

**Comment by cliveseldon** [comment]
Are you running on Openshift and installed via the Marketplace?

**Comment by FrancescoFanchin** [comment]
Seldon is running on Openshift and was installed via Operatorhub, but not the Marketplace one.
We deleted the MWC and it worked, many thanks!
