### ISSUE TITLE
after run "kubectl get seldondeployments" but got "No resources found."

### ISSUE THREAD

**Issue by heimao63531** [SeldonIO/seldon-core#3010]
## Describe the bug
i follow readme to install seldon and apply the iris-model. Then i try to get the seldondeployment status with kubectl get seldondeployments but it returns "No resources found."

[root@c-pk6wiuog-6ypfs6s2 seldon]# kubectl apply -f iris-model.yaml
seldondeployment.machinelearning.seldon.io/iris-model created
[root@c-pk6wiuog-6ypfs6s2 seldon]# kubectl get seldondeployments.machinelearning.seldon.io
No resources found.

**Comment by cliveseldon** [comment]
Can you provide more details on your k8s environment and how you installed Seldon Core.
Can you check you have the seldon-controller-manager running in the seldon-system namespace and if so check its logs.

**Comment by axsaucedo** [comment]
Closing for now, please reopen if still issue
