### ISSUE TITLE
gRPC metrics not exposed to prometheus

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#302]
Might need to include inspired by linked project in the [issue on micrometer](https://github.com/micrometer-metrics/micrometer/issues/656)

**Comment by tilast** [comment]
Does this issue mean that if one uses a GRPC mode for the model then metrics will not be collected by prometheus?

**Comment by cliveseldon** [comment]
Sorry missed this. Yes at present micrometer doesn't support grpc our of the box.

**Comment by tilast** [comment]
thanks! so if you say it does not support grpc out of the box, is there an existing workaround?

**Comment by pravingadakh** [comment]
@cliveseldon Is there any workaround exist for this or will we have to wait until micrometer issue is fixed?

**Comment by cliveseldon** [comment]
Well, yes I suppose a workaround is to create out own but was hoping we could continue to use micrometer. Not sure of the short term fixes that could help.

**Comment by cliveseldon** [comment]
Also, eventually we want to replace the Java engine with GoLang so then hopefully there is a grpc metrics library in GoLang for this.

**Comment by cliveseldon** [comment]
Also, we should allow metrics directly from each model. So I think this also is the best solution going forward. So out python wrappers could expose a /metrics endpoint.

**Comment by HunterEl** [comment]
Any movement on this issue?

**Comment by RafalSkolasinski** [comment]
This should be fixed in recent PR https://github.com/SeldonIO/seldon-core/pull/1507 about exposing metrics directly on Python wrapper.

**Comment by RafalSkolasinski** [comment]
Please, reopen if issue is not fixed on master.

**Comment by cliveseldon** [comment]
Yes - gRPC and REST metrics will be exposed in 1.1 via the new GoLang executor: 

* overview:  https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html
* Notebook: https://docs.seldon.io/projects/seldon-core/en/latest/examples/metrics.html

**Comment by HunterEl** [comment]
Thanks all!
