### ISSUE TITLE
Misaligned documentation for SKLearn pre-packaged model server 

### ISSUE THREAD

**Issue by Roymprog** [SeldonIO/seldon-core#3029]
I was reading through the documentation on pre-packaged model servers for SKLearn. The [quickstart guide](https://docs.seldon.io/projects/seldon-core/en/latest/workflow/github-readme.html#deploy-your-model-using-pre-packaged-model-servers) uses a `model.pickle`  as name the serialized model using the SKLearn model server, but the [detailed SKLearn model server documentation](https://docs.seldon.io/projects/seldon-core/en/latest/servers/sklearn.html#sklearn-server) explicitly states one should use `model.joblib`.

The truth appears to be [model.joblib](https://github.com/SeldonIO/seldon-core/blob/fc551c0bf19eaa999e520e35efe715430c043d46/servers/sklearnserver/sklearnserver/SKLearnServer.py#L12), hence the quickstart documentation should be updated.

**Comment by axsaucedo** [comment]
Good shout @Roymprog ! Yes we should fix this - would you be able to add a small PR with fix? Otherwise we'll be able to address, let us know and we can proceed accordingly
