### ISSUE TITLE
 no matches for kind "SeldonDeployment" in version "machinelearning.seldon.io/v1alpha2"

### ISSUE THREAD

**Issue by vladislavkoz** [SeldonIO/seldon-core#3037]
## Describe the bug
I'm trying to apply deployment YAML on my KubeFlow(1.2) cluster.

After running: kubectl apply -f deployment.yaml I'm getting the following error:
error: unable to recognize "deployment.yaml": no matches for kind "SeldonDeployment" in version "machinelearning.seldon.io/v1alpha2"

## Expected behaviour
Deployment created. The deployment.yaml file is ok.
I was using it with the previous KubeFlow versions deployed using kfctl + [manifest](https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.2.yaml) 

## Environment
Kubeflow 1.2
1.18.12-gke.1210

**Comment by cliveseldon** [comment]
This looks like Seldon Core is not installed and the CRD is not there. Are you sure you see the seldon-core-manager running in the kubeflow namespace?

**Comment by vladislavkoz** [comment]
@cliveseldon, You are right. I thought that it comes with the KubeFlow by default. I've tried to install it manually but faced another issue.
https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#install-seldon-core-with-helm

kubectl create namespace seldon-system

Now we can install Seldon Core in the seldon-system namespace.

helm install seldon-core seldon-core-operator \
    --repo https://storage.googleapis.com/seldon-charts \
    --set usageMetrics.enabled=true \
    --namespace seldon-system

helm install seldon-core seldon-core-operator \
>     --repo https://storage.googleapis.com/seldon-charts \
>     --set usageMetrics.enabled=true \
>     --namespace seldon-system
index.go:339: skipping loading invalid entry for chart "seldon-core-crd" "0.1.5a" from https://storage.googleapis.com/seldon-charts: validation: chart.metadata.version "0.1.5a" is invalid
index.go:339: skipping loading invalid entry for chart "seldon-core-crd" "0.1.6_SNAPSHOT" from https://storage.googleapis.com/seldon-charts: validation: chart.metadata.version "0.1.6_SNAPSHOT" is invalid
index.go:339: skipping loading invalid entry for chart "seldon-core-crd" "0.1.6_SNAPSHOT" from https://storage.googleapis.com/seldon-charts: validation: chart.metadata.version "0.1.6_SNAPSHOT" is invalid
index.go:339: skipping loading invalid entry for chart "seldon-core" "0.1.6_SNAPSHOT" from https://storage.googleapis.com/seldon-charts: validation: chart.metadata.version "0.1.6_SNAPSHOT" is invalid
index.go:339: skipping loading invalid entry for chart "seldon-core-crd" "0.1.5a" from /home/kf26/.cache/helm/repository/zisUqB+lZeeRsx0t1AW1jGWS32I=-index.yaml: validation: chart.metadata.version "0.1.5a" is invalid
index.go:339: skipping loading invalid entry for chart "seldon-core-crd" "0.1.6_SNAPSHOT" from /home/kf26/.cache/helm/repository/zisUqB+lZeeRsx0t1AW1jGWS32I=-index.yaml: validation: chart.metadata.version "0.1.6_SNAPSHOT" is invalid
index.go:339: skipping loading invalid entry for chart "seldon-core-crd" "0.1.6_SNAPSHOT" from /home/kf26/.cache/helm/repository/zisUqB+lZeeRsx0t1AW1jGWS32I=-index.yaml: validation: chart.metadata.version "0.1.6_SNAPSHOT" is invalid
index.go:339: skipping loading invalid entry for chart "seldon-core" "0.1.6_SNAPSHOT" from /home/kf26/.cache/helm/repository/zisUqB+lZeeRsx0t1AW1jGWS32I=-index.yaml: validation: chart.metadata.version "0.1.6_SNAPSHOT" is invalid
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "seldondeployments.machinelearning.seldon.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "seldon-core"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "seldon-system"

**Comment by axsaucedo** [comment]
@vladislavkoz I just ran the command locally and didn't seem to get any error, perhaps theree is already a CRD installed? Can you try upgrade helm CLI and remove all CRDs from Seldon and try again?

**Comment by cliveseldon** [comment]
Closing now. Please reopen if still an issue.

**Comment by pierluigilenoci** [comment]
@cliveseldon if you try to use v3.5.* of helm you get the error.
