### ISSUE TITLE
Allow user to disable Redis in seldon-core helm chart

### ISSUE THREAD

**Issue by ChenyuanZ** [SeldonIO/seldon-core#304]
`Redis` shipped in `seldon-core` helm chart is used for two purposes:

1. Store oauth keys for `seldon-apiserver`.
2. Persist `Predictive Unit` if its `.s2i/environment` `PERSISTENCE` flag is set to 1.

Since we can use `ambassador` to replace `seldon-apiserver` (which means we can disable `seldon-apiserver` in that case), and we can use a different `Redis` server for `PERSISTENCE` flag (if the admin already has a `Redis` server running), there is a need to disable the `Redis` shipped in `seldon-core` helm chart.

**Comment by cliveseldon** [comment]
Fixed by #305
