### ISSUE TITLE
Extend seldon-request-logger support for different response formats

### ISSUE THREAD

**Issue by gs-alt** [SeldonIO/seldon-core#3041]
In working with Seldon Core's request logger for payload logger, I have found that there are some response formats that throw exceptions, thus leading to only the request being logged, but not the response.

## Format of names

The `names` data in the response which comes from the `class_names()` function only allows string and bytes types for the elements of the list. Integers do not work. The error happens in the [default_logger](https://github.com/SeldonIO/seldon-core/blob/master/components/seldon-request-logger/app/default_logger.py#L329).

This can be problematic as, for example, I got the class names from a scikit-learn model and they turned out to be integer. I had to convert the class names to string to make it work.

For example:

I get the class names of my model via:

```python
class_list = self.model.classes_.tolist() 
```

But these are integers in the list, so it would throw an error in the request logger. Thus, I must convert everything to string for it to work:

```python
class_list = self.model.classes_.tolist() 
ret_list = [str(x) for x in class_list]
```

It would be better if the seldon-request-logger was able to handle all data types for the names list in the response

## Standard predict() function response

The request logger works when the number of columns in each row of the ndarray equals the length of the names list. But otherwise, it will throw an error.

For example, inside of the Seldon Model class `predict()` function, of scikit-learn, I can run my model with `model.predict()` like so:

```python
def predict(self, X: np.ndarray, names: Iterable[str] = None, meta: Dict = None) -> Union[np.ndarray, SeldonResponse]:
        """
        - Input X should always be np.ndarray
        - The 'names' are the names of the input columns
        """
        try:
            if not self.ready:
                self.load()

            preds = self.model.predict(X)
            result = preds.reshape(len(X), -1)

            logger.info(f"Prediction result: {result}")

            return result
        except Exception as ex:
            message = "Exception during predict: {}".format(str(ex))
            raise SeldonMicroserviceException(message=message, status_code=500)
```

Which will return something similar to for example `[[0], [2], [2]]` i.e one column per row (just the class label). However, this does not work with the seldon-request-logger, because it expects that the length of the `names` list equals the number of columns in each row of the response's `ndarray`. The error that is thrown happens [here](https://github.com/SeldonIO/seldon-core/blob/master/components/seldon-request-logger/app/default_logger.py#L447).

This does however work with I run a `model.predict_proba()` with my scikit-learn model which actually returns all the probabilities i.e for each row [[0.96, 0.038, 0.0020], [0.0020, 0.038, 0.96], [0.0020, 0.038, 0.96]]. Thus, we have 3 columns for each row, which is equal to the length of the `names` list.

It would be better for the selon-request-logger to also be able to handle the regular `predict()` function as it will come with many libraries.

**Comment by gs-alt** [comment]
I also just found something else for logging for the request: there can be some errors when you pass certain metadata. For example, I sent in the following request:

```bash
curl -X POST http://localhost:8003/seldon/seldon/seldon-model/api/v1.0/predictions -H 'Content-Type: application/json' -d '{ "data": { "ndarray": [[5.1,3.5,1.4,0.2], [7.7,3.0,6.1,2.3]] }, "meta": {"method": "predict_proba"} }'
```

Which failed, due to the fact that the seldon-request-logger only accepts certain keys in the `meta` dictionary:

```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/seldon_core/utils.py", line 65, in json_to_seldon_message
    json_format.ParseDict(message_json, message_proto)
  File "/opt/app-root/lib64/python3.8/site-packages/google/protobuf/json_format.py", line 454, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/opt/app-root/lib64/python3.8/site-packages/google/protobuf/json_format.py", line 485, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/opt/app-root/lib64/python3.8/site-packages/google/protobuf/json_format.py", line 597, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse meta field: Message type "seldon.protos.Meta" has no field named "method".
 Available Fields(except extensions): ['puid', 'tags', 'routing', 'requestPath', 'metrics'].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app/default_logger.py", line 72, in index
    process_and_update_elastic_doc(
  File "app/default_logger.py", line 93, in process_and_update_elastic_doc
    new_content_part = process_content(message_type, message_body)
  File "app/default_logger.py", line 228, in process_content
    requestCopy = extract_data_part(content)
  File "app/default_logger.py", line 333, in extract_data_part
    requestMsg = json_to_seldon_message(copy)
  File "/opt/app-root/lib64/python3.8/site-packages/seldon_core/utils.py", line 68, in json_to_seldon_message
    raise SeldonMicroserviceException("Invalid JSON: " + str(pbExc))
seldon_core.flask_utils.SeldonMicroserviceException
```

**Comment by cliveseldon** [comment]
Are you able to investigate a small PR to fix these?

**Comment by gs-alt** [comment]
Sure

**Comment by cliveseldon** [comment]
Can you reopen this if still and issue or you have a PR
