### ISSUE TITLE
Add health/ping to api v1

### ISSUE THREAD

**Issue by ktleung2017** [SeldonIO/seldon-core#3046]
#3022 handled `/health/status` in api v1. Would like to have `/health/ping` for lightweight health checking as well.

**Comment by axsaucedo** [comment]
Looks good, i added a comment to add docs and ran integration tests

**Comment by cliveseldon** [comment]
@ktleung2017 There is https://github.com/SeldonIO/seldon-core/blob/9f069ff4a304cc1ebf3b07a97e7f3e5eeb44ea8d/executor/api/rest/server.go#L161 which has been recently added which essentially does this. Would this be ok?

**Comment by ktleunghk01** [comment]
@cliveseldon there are some cases that we only want a lightweight ping no matter a model is loaded or not.

**Comment by cliveseldon** [comment]
The above does just do a TCP connect to the assigned port for the model to succeed and will work for any model not just ones created via the Seldon Python wrapper.

**Comment by ktleung2017** [comment]
Yes that will be enough.
