### ISSUE TITLE
Moving Request Logger to Separate Repo and Outline Roadmap Towards Graduation

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3062]
The request logger initially started as an example, and now has grown into a component that is able to provide quite important capabilities for seldon. There is however a well over-due re-architecture / refactor before the request logger can handle further scale - this includes adding a more reliable HTTP server (like tornado / gunicorn) as well as further reassessment of the schema, flow and how to handle different protocols, data-types potentially leveraging more modular design patterns, such as having an abstract class for the class that handles protocols, and derived classes for the implementations (rest / grpc / kafka), etc.

This issue encompasses moving the current request logger as is into incubation, as well as outlining the roadmap of features required in order to consider the requset logger as a graduated component.

**Comment by ryandawsonuk** [comment]
related https://github.com/SeldonIO/seldon-core/issues/2141

**Comment by cliveseldon** [comment]
Closing as we don't plan to move.
