### ISSUE TITLE
Explore OpenTelemetry Collector

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#3068]
The OpenTelemetry project now has a `Collector` component, which can be seen as `fluentd` for traces. The collector offers a single (vendor agnostic) centralised point to gather traces from different components, that can then be pushed to a 3rd party vendor backend (e.g. Jaeger, Datadog, etc). 

It would be good to explore whether this could be used as the default in Seldon Core, so that we decouple vendor-specific code from Seldon components, and thus enable support for any tracing backend. 

More details can be found in their repo: https://github.com/open-telemetry/opentelemetry-collector

**Comment by cliveseldon** [comment]
Duplicate of https://github.com/SeldonIO/seldon-core/issues/2609

**Comment by cliveseldon** [comment]
v2
