### ISSUE TITLE
Python-wrapper: Use debug flag to provide useful information

### ISSUE THREAD

**Issue by epa095** [SeldonIO/seldon-core#309]
The python model microservice [accepts](
https://github.com/SeldonIO/seldon-core/blob/48d2bbbd9583feed2bd4d06adef01784609d4f7c/wrappers/python/model_microservice.py#L50) a debug-flag, but it does not use it for anything. It seems reasonable for it to use it for at least two things:
* Pass it along to the flask server, so it can be in debug/non-debug mode, and 
* Provide different level of logging. For the latter I recommend using the logging module in Python instead of "print" statements scattered around in the code:
  * On the top of the class get the logger with `logger = logging.getLogger(__name__)`
  * Around in the code log to different levels, using e.g. `logger.debug` or `logger.info`
  * Set the loglevel of the logger based on the debug toggle.

**Comment by cliveseldon** [comment]
These changes make sense. We are updating the python code to create a Seldon module for easier testing (#306) and usage and we can add these changes into that. @jklaise

**Comment by masonlr** [comment]
@cliveseldon #306 was merged, but did hot-reloading make it into the `seldon_core.microservice` module?

Hot-reloading would be useful for iterative development. A use case would be to mount local files into a model container using something like:

```
docker run -it -p 5000:5000 -v ${PWD}:/microservice name:version /bin/bash
```

then run a debug mode from within the container (although with a `--debug` flag, or a `DEBUG` environment variable, etc.)

```
seldon-core-microservice Model REST --service-type MODEL --debug 
```

and then be able to make local file changes and see the model hot-reload. The change would be to support passing debug variable state through to (https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L224):

```
 app.run(host='0.0.0.0', port=port, debug=True)
```

A hot-reload option might also be useful for accelerating k8s iterative development if using dev tools like skaffold filesync (https://skaffold.dev/docs/how-tos/filesync/).

**Comment by cliveseldon** [comment]
This sounds useful. You happy to do a PR for adding that to debug mode?

**Comment by masonlr** [comment]
Yes can do. Do you have a preference for the interface? i.e. `--debug` flag or specific env variable?
