### ISSUE TITLE
Add support for transformers with arbitrary request/response format (ie. not SeldonMessage)

### ISSUE THREAD

**Issue by mlegore** [SeldonIO/seldon-core#3096]
One feature I have been looking for in Seldon is the ability to pre-process requests of formats that don't comply with SeldonMessage. This would be useful for glueing together systems that don't know they're calling seldon.

For example, I'd like to set up a model to be called from a Google Pub/Sub message, but the json message that is sent by Pub/Sub is not in the format of a SeldonMessage, so right now I would have to set up another worker component (a cloud function or similar) to translate the message into a SeldonMessage before calling Seldon. It would be useful if seldon could include that in its routing graph and keep more of the logic contained within Seldon.

**Comment by axsaucedo** [comment]
@mlegore although not exlplicitly documented it is currently possible to send arbitrary payloads to the API, and process them using `predict_raw`, or in your case `transform_input_raw`. We currently have #2497 to explore this, so closing this issue.

**Comment by mlegore** [comment]
@axsaucedo is there some examples or documentation for this, in particular how to do this with a language other than python?
