### ISSUE TITLE
Wrong required variable in documentation

### ISSUE THREAD

**Issue by PranY** [SeldonIO/seldon-core#3097]
## Describe the bug
I was trying to run seldon-core packaged server and after wasting too much time providing the credentials mentioned at https://github.com/SeldonIO/seldon-core/blob/v1.1.0/doc/source/servers/overview.md , I was forced to read the storage.py documentation. There I found that `AWS_ENDPOINT_URL` isn't a required parameter 'S3_ENDPOINT' is. Please change the documentation or the code.

## To reproduce
Run any custom seldon-core model using 
https://github.com/SeldonIO/seldon-core/blob/v1.1.0/doc/source/servers/overview.md

## Expected behaviour
the deployment should work

## Environment
* Cloud Provider: minikube
* Kubernetes Cluster Version: Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"

**Comment by axsaucedo** [comment]
Thanks for opening the issue. Latest seldon core now uses a latter version of kfserving which renamed the variable, so the documentation for this version reflects this change
