### ISSUE TITLE
Implement a hierarchy of tags for components with children.

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#310]
Currently the engine provides tags relating to each individual component (e.g. model_name, model_image), however if a component has children there are no tags to identify the existence and identity of these. Having these tags would enable us to do to things like metrics that relate to the performance of children (e.g. a router collecting metrics relating to the performance of its children) be easier to implement.

**Comment by cliveseldon** [comment]
Leave for https://github.com/SeldonIO/mlgraph
