### ISSUE TITLE
Kafka connector failure takes too long 

### ISSUE THREAD

**Issue by maayanshem** [SeldonIO/seldon-core#3100]
## Describe the bug
During system sanity tests, we've noticed that Seldon's kafka-server failure is taking a long time.
Logs that prove the problem: 
```
{"level":"error","ts":1617013575.758387,"logger":"entrypoint.KafkaServer","msg":"Received kafka error","error":"kafka-set:9092/bootstrap: Connect to ipv4#10.156.2.136:9092 failed: Connection refused (after 1042ms in state CONNECT)","stacktrace":"github.com/seldonio/seldon-core/executor/api/kafka.(*SeldonKafkaServer).Serve\n\t/workspace/api/kafka/server.go:243\nmain.main.func1\n\t/workspace/cmd/executor/main.go:308"}
{"level":"error","ts":1617013575.7584689,"logger":"entrypoint.KafkaServer","msg":"Received kafka error","error":"1/1 brokers are down","stacktrace":"github.com/seldonio/seldon-core/executor/api/kafka.(*SeldonKafkaServer).Serve\n\t/workspace/api/kafka/server.go:243\nmain.main.func1\n\t/workspace/cmd/executor/main.go:308"}
{"level":"info","ts":1617013575.758484,"logger":"entrypoint.KafkaServer","msg":"Final Processed","messages":0}
{"level":"info","ts":1617013575.7585006,"logger":"entrypoint.KafkaServer","msg":"Closing consumer"}
{"level":"info","ts":1617014044.171323,"logger":"entrypoint","msg":"shutting down"}
```
As you can see above, it takes 469 seconds (~8 mins) for the orchestrator to shut-down which initiate new pod with new connection. 

## To reproduce
1. Run seldon kakfa server 
2. Restart or scale down kakfa pods 
3. Wait for seldon orchestrator failure/restart 

## Expected behaviour
Option 1: Closing the kafka connection will be a seconds matter
Option 2: While restarting the connection, the orchestrator health check will be return false.

## Environment

* Cloud Provider: GKE
* Kubernetes Cluster Version :
 ```
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

```
* Deployed Seldon System Images: 1.5.1

**Comment by axsaucedo** [comment]
Thanks for creating the issue @maayanshem. It's not clear on the steps to reproduce, when you mention "Wait for failure", what kind of failure would this be? Would it be failure in the worker? Would be easier if you can provide an eexample payload that allows for reproducing issue

**Comment by maayanshem** [comment]
@axsaucedo I've edited the bug description

**Comment by axsaucedo** [comment]
@maayanshem I dont't think it's clear what you mean - so when you restart or scale down kafka, does the executor / service orchestrator fails immediately, or is the problem that it takes too long to fail? Why should you expect it to fail?

**Comment by cliveseldon** [comment]
Please reopen if still an issue
