### ISSUE TITLE
document request id header

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#3102]
Should say that header is `Seldon-Puid`

See https://github.com/SeldonIO/seldon-core/blob/117fed77b4097547a45aad22708669ddcc4cf19a/executor/api/payload/metadata.go#L4 and https://github.com/SeldonIO/seldon-core/blob/426432a8344056b6251881628d5cd88d441f4f76/python/seldon_core/batch_processor.py#L277

If you want shadow request to be logged under same id as main predictor request then you have to add this header. (Related https://github.com/SeldonIO/seldon-core/issues/2823). So basically you should send this for shadow use-cases.

Thinking it could go here - https://github.com/SeldonIO/seldon-core/blob/402a65e1714efa7cfbaa3c2ff0c7d92d47ab1691/doc/source/analytics/logging.md#L1

**Comment by cliveseldon** [comment]
Payload logging in AB tests will be handled in v2. But is also better supported via Iter8 configurations over separate sdeps.
