### ISSUE TITLE
Support preprocessor when use alibi-detect-server

### ISSUE THREAD

**Issue by cksac** [SeldonIO/seldon-core#3112]
https://docs.seldon.io/projects/seldon-core/en/latest/examples/outlier_combiner.html
Above example has outlier detection model with preprocessor, how to start the outlier detector using alibi-detect-server with per-processing step?

**Comment by cliveseldon** [comment]
There are various options depending on what you want.

 1. You can log requests not directly to the outlier detector but another component that does a preprocessing step and then return a cloud event to forward to the outlier detector. We don't have an example of this but it would be a knative eventing pipeline.
 2. You could log requests after they have been through a preprocessing step in your inference graph as the logger field can be specified at any node in the inference graph

**Comment by cksac** [comment]
Option 1 should work but added extra services and complexity to the user.
Option 2 works if the outlier detector share the same preprocessing logic of the prediction model. However in the above example, the preprocessing logic of outlier detection model is different from prediction model.

**Comment by cliveseldon** [comment]
In this case only option 1 is presently available. Managing asynchronous components such as outlier and drift is presently something we are investigating for an updated higher level inference CRD that allows one to define and manage all inference related components but not just predictor.

**Comment by cliveseldon** [comment]
This is possible in the v2 APIs.
