### ISSUE TITLE
Reduce size of images created by Python wrapper

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#312]
Need to look into alternative base images for Python (e.g. built on Alpine) for lightweight component images after wrapping.

**Comment by jklaise** [comment]
It appears that Python wheel packages are not supported on Alpine which makes installing python packages via pip build the libraries from source taking a lot longer. Currently Alpine base images seem to be a poor fit for data science containers. See https://github.com/docker-library/docs/issues/904

**Comment by gsunner** [comment]
closing this stale issue, re-open if necessary
