### ISSUE TITLE
Python SeldonClient Not OK but curl OK

### ISSUE THREAD

**Issue by sebg1** [SeldonIO/seldon-core#3136]
## Describe the bug

Curl command and query from swagger are OK (200)
With the python client : 405 Method Not Allowed

My config : minikube, ambassador, seldon deployement of a mlflow server (custom code) + minikube tunnel

## Expected behaviour

Should respond 200 with the following result : 
```
curl -k -X POST "https://10.96.37.239/seldon/seldon/reco-doc-user/api/v1.0/predictions" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"data\":{\"names\":[\"customer_code\",\"project_code\",\"community_code\",\"entity_id\",\"destination\",\"reco_max_nb\"],\"tensor\":{\"shape\":[1,6],\"values\":[\"CustomerC\",\"ProjectP\",\"CommunityC\",\"EntityE\",\"Email\",\"4\"]}}}"
{"data":{"names":[],"ndarray":["docId1","CustomerC","ProjectP","CommunityC","EntityE","Email","4"]},"meta":{"requestPath":{"reco-doc-user":"seldonio/mlflowserver:1.7.0"}}}
```

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

```
`sc = SeldonClient(
    gateway="ambassador",
    namespace="seldon",
    transport="rest",
    deployment_name="reco-doc-user",
    gateway_endpoint='10.96.37.239:80',
    debug=True,
    channel_credentials=SeldonChannelCredentials(verify=False)
    )
client_prediction = sc.predict(
    data=np.array(["CustomerC","ProjectP","CommunityC","EntityE","Email","4"]),
    deployment_name="reco-doc-user",
    payload_type= 'ndarray',
    shape=(1,6))
```
Output: 
```
send: b'POST /seldon/seldon/reco-doc-user/api/v1.0/predictions HTTP/1.1\r\nHost: 10.96.37.239\r\nUser-Agent: python-requests/2.23.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-Length: 99\r\nContent-Type: application/json\r\n\r\n'
send: b'{"meta": {}, "data": {"ndarray": ["CustomerC", "ProjectP", "CommunityC", "EntityE", "Email", "4"]}}'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: location: https://10.96.37.239/seldon/seldon/reco-doc-user/api/v1.0/predictions
header: date: Thu, 22 Apr 2021 13:14:11 GMT
header: server: envoy
header: connection: close
header: content-length: 0
send: b'GET /seldon/seldon/reco-doc-user/api/v1.0/predictions HTTP/1.1\r\nHost: 10.96.37.239\r\nUser-Agent: python-requests/2.23.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 405 Method Not Allowed\r\n'
header: date: Thu, 22 Apr 2021 13:14:11 GMT
header: content-length: 0
header: x-envoy-upstream-service-time: 1
header: server: envoy
/home/sebastien/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.96.37.239'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
```

With the request lib, it works perfectly : 

```
import requests
headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json',
}
url = 'https://10.96.37.239/seldon/seldon/reco-doc-user/api/v1.0/predictions'
data = '{"data":{"names":["customer_code","project_code","community_code","entity_id","destination","reco_max_nb"],"tensor":{"shape":[1,6],"values":["CustomerC","ProjectP","CommunityC","EntityE","Email","4"]}}}'
response = requests.post(url=url, headers=headers, data=data, verify=False)
```
Output : 
```
response.content
Out[67]: b'{"data":{"names":[],"ndarray":["docId1","CustomerC","ProjectP","CommunityC","EntityE","Email","4"]},"meta":{"requestPath":{"reco-doc-user":"seldonio/mlflowserver:1.7.0"}}}\n'
```

**Comment by sebg1** [comment]
I have some additional infos got with the python debugger. :-)
With the following config, it works :

```
sc = SeldonClient(
    gateway="ambassador",
    namespace="seldon",
    transport="rest",
    deployment_name="reco-doc-user",
    gateway_endpoint='10.96.37.239',
    debug=True,
    channel_credentials=SeldonChannelCredentials(verify=False),
    call_credentials=SeldonCallCredentials(None)
    )
```

For my situation, the good url is 
'http**s**://10.96.37.239/seldon/seldon/reco-doc-user/api/v1.0/predictions'

If I use no call_credentials in initiating SeldonClient, the protocol is set as http by the code.

There were 2 mistakes : call_credentials&protocol and gateway_endpoint&port.

**Comment by sebg1** [comment]
There is a similar issue with the feedback query : not compatible with https + verify False.
Solution : requests lib

`import requests
headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json',
}
url = 'https://10.96.37.239/seldon/seldon/reco-doc-user/api/v1.0/'
data = '{"data":{"names":["customer_code","project_code","community_code","entity_id","destination","reco_max_nb"],"tensor":{"shape":[1,6],"values":["CustomerC","ProjectP","CommunityC","EntityE","Email","4"]}}}'
for i in range(10000):
    response_prediction = requests.post(url=f"{url}predictions", headers=headers, data=data, verify=False)
    payload = {'reward': np.random.rand()*100}
    response_feeback = requests.post(url=f"{url}feedback", json=payload, verify=False)`

Another solution could be to modify the file seldon_client.py, function rest_feedback_gateway
in a similar way that the function rest_predict_gateway.

**Comment by cliveseldon** [comment]
Assuming fixed. Please reopen if not.
