### ISSUE TITLE
Alibi Explain Server won't fail if explainer artifact is missing

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#3138]
## Describe the bug

When using the Alibi Explain Server, if the `explainer.dill` artifact is missing, instead of triggering an error it will go ahead using an `string` instead of the loaded artifact. This will cause a downstream an error when trying to explain a prediction,

```
ERROR:tornado.application:Uncaught exception POST /v1/models/fraud-detector:explain (10.244.0.117)
HTTPServerRequest(protocol='http', host='fraud-detector-default-explainer.dev:9000', method='POST', uri='/v1/models/fraud-detector:explain', version='HTTP/1.1', remote_ip='10.244.0.117')
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/app-root/src/alibiexplainer/server.py", line 95, in post
    response =self.model.explain(body)
  File "/opt/app-root/src/alibiexplainer/explainer.py", line 148, in explain
    explanation = self.wrapper.explain(response_list)
  File "/opt/app-root/src/alibiexplainer/anchor_tabular.py", line 55, in explain
    self.anchors_tabular.predictor = self.predict_fn
AttributeError: 'str' object has no attribute 'predictor'
ERROR:tornado.access:500 POST /v1/models/fraud-detector:explain (10.244.0.117) 9.77ms
```

This happens because the current logic won't raise an error if the neither of the expected filenames (i.e. `explainer.dill` or `model.h5`) are found:

https://github.com/SeldonIO/seldon-core/blob/2a09a8da682bba6c9600947e311dcbc2c8bbeb3f/components/alibi-explain-server/alibiexplainer/__main__.py#L45-L54

## Expected behaviour

An error should be raised, flagging that the artifact file is missing.

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Closing and explainers are better supported via MLServer and latest poetry version of explainer server. Can reopen if still an issue.
