### ISSUE TITLE
Allow any structure in custom field in metadata

### ISSUE THREAD

**Issue by dmirecki** [SeldonIO/seldon-core#3144]
I am working on a model for which I need to define what kind of data the model is able to process. I define some high level structure that describes the data and now I am trying to put it in the seldon's metadata. In this way, client can easily check what kind of data my model supports.

I tried to use `custom` field in `metadata` endpoint, but, unfortunately, the field only supports str -> str mapping. As I mentioned, I have to pass more complicated structure (nested dictionary, lists). From that stems my feature request to allow any structure in `custom` field in `metadata`.

**Comment by RafalSkolasinski** [comment]
Hi @dmirecki,

The `custom` field is really meant to be `tags` or `labels` (so just str->str) but is named `custom` to avoid confusion with k8s labels or request tags. 

What you can do is to specify type `jsonData` and then `schema` field should (as far as I remember) accept anything you define there, see https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/metadata.html#jsondata-input-output

**Comment by dmirecki** [comment]
Hi, thank you for response. 

Your were right, `schema` in `input` and `output` accept any structure, so I can use that for my case.

Thank you!
