### ISSUE TITLE
python wrapping docker/s2i docs need updating

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#3145]
Red Hat were setting up a model for a demo in https://github.com/sub-mod/2021-ai/tree/21f177fd1d386c1af27403f50923216e7384d69c

They had trouble getting it working because:

1. The docker/s2i flow in our docs was hard to find
2. The[ relevant docs page ](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html)doesn't mention the now required meta parameter in the predict signature
3. They wanted to curl the docker container locally without k8s and were struggling to find the port or url.
4. Something weird happened with s2i and it wasn't clear that s2i was to blame. That only became clear with an exec into the docker container which revealed that the files hadn't updated.

@RafalSkolasinski got to the bottom of everything. He pushed a version that [features the meta param](https://github.com/RafalSkolasinski/2021-ai/commit/79fe3376ec82a54ebf5051ee2fda12bde1458c48#diff-1287bf26835710d7b906f8846a8bdadf3ce922a8cc797b190e0227abc12d06afR19) and the[ docker run and curl](https://github.com/RafalSkolasinski/2021-ai/commit/79fe3376ec82a54ebf5051ee2fda12bde1458c48#diff-5de36acd90308dc62abf7855a686ee7052ffb6e762c756fd735fb0c9fbd9595dR8). But we should update our docs.

**Comment by cliveseldon** [comment]
Closing as old version of docs.
