### ISSUE TITLE
The response returned by Flask server is unicode literal, which is not good, and no config can be used to change this behaviour

### ISSUE THREAD

**Issue by wineternity** [SeldonIO/seldon-core#3146]
## Describe the bug

Create a python wrapper sample with return the request,  predict with request contains Chinese， And the response output is  unicode
![image](https://user-images.githubusercontent.com/1088645/116537639-0fd7a780-a919-11eb-9b3f-45eeac9e2fb7.png)

## To reproduce
the main file:
`
# -*- encoding=utf-8 -*-
import logging
logger = logging.getLogger(__name__)
class Simple(object):
    """
    Model template. You can load your model parameters in __init__ from a location accessible at runtime
    """

    def __init__(self):
        """
        Add any initialization parameters. These will be passed at runtime from the graph definition parameters defined in your seldondeployment kubernetes resource manifest.
        """
        print("Initializing")
        logger.info("Initializing")

    def predict(self, X, features_names=None):
        """
        Return a prediction.

        Parameters
        ----------
        X : array-like
        feature_names : array of feature names (optional)
        """
        print("Predict called - will run identity function v1")
        print(type(X))
        logger.info("Predict called - will run identity function v1")
        logger.info(type(X))
        logger.info(X)
        str={"url":"中文测试", "X":X}
        return str
`

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Is this still an issue? Please reopen. Also look at [MLServer](https://github.com/SeldonIO/mlserver) for custom models to see if that fits your use case.
