### ISSUE TITLE
Streamlined Optimization of Deployed Model Configuration via Automated Performance Evaluation / Benchmarking

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3149]
Currently we have examples showing how to leverage vegeta/ghz with argocd to perform grid-search-like performance evaluation https://github.com/SeldonIO/seldon-core/tree/master/examples/batch/benchmarking-argo-workflows, however we would like to have more automated ways that can allow users to perform automated performance evluation to identify the most optimal performance configuration.

**Comment by cliveseldon** [comment]
Closing for now as probably out of scope for this project
