### ISSUE TITLE
Custom metrics in feedback

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/seldon-core#315]
Custom metrics in the Python model microservice are collected under [Predict](https://github.com/SeldonIO/seldon-core/blob/7d91ac590a1dbf4c3a57303f15e1b05d0905ac11/wrappers/python/model_microservice.py#L87). It would make sense to also include custom metrics in SendFeedback (eg for RL problems).

**Comment by RafalSkolasinski** [comment]
@cliveseldon Is this issue still relevant? The related code has been already moved. 
I can work on it but the issue require updating the scope first. 

I did check with @arnaudvl as he initially opened it but we were unable to decide if this is still relevant or what scope of it may be now.

**Comment by jorgyz** [comment]
I've noticed that the metrics method gets called when the feedback endpoint is hit but the returned metrics are only passed to Prometheus when the predictions endpoint is hit. Is this intentional? Personally I'd like the metrics to be passed to Prometheus for both predict and feedback.

**Comment by cliveseldon** [comment]
This is relevent to ensure the python wrapper returns custom metrics for feedback.
The Java engine is missing the ability to capture these so its probably worth fixing this. The new executor which replaces the java engine should provide basic metrics for feedback but custom metrics is one break change we want to add to the components itself so @RafalSkolasinski maybe open an issue to ensure custom metrics are exposed on a python wrapper prometheus endpoint for scraping.

**Comment by RafalSkolasinski** [comment]
According to a simple test, adding `metrics` method from [template model with metrics](https://github.com/SeldonIO/seldon-core/blob/master/examples/models/template_model_with_metrics/ModelWithMetrics.py) to [template model with feedback](https://github.com/SeldonIO/seldon-core/blob/master/examples/models/template_model_with_feedback/ModelWithFeedback.py)
```
    def metrics(self):
        return [
            {"type": "COUNTER","key": "mycounter","value": 1}, # a counter which will increase by the given value
            {"type": "GAUGE","key": "mygauge","value": 100},   # a gauge which will be set to given value
            {"type": "TIMER","key": "mytimer","value": 20.2},  # a timer which will add sum and count metrics - assumed ms
        ]
```
the metrics is returned in `response.meta.metrics` keys:
```bash
$ seldon-core-tester contract.json 0.0.0.0 5000 -p --endpoint send-feedback
----------------------------------------
SENDING NEW REQUEST:
RECEIVED RESPONSE:
Success:True message:
Request:
request {
  data {
    ndarray {
      values {
        list_value {
          values {
            number_value: 6.44
          }
          values {
            number_value: 3.067
          }
          values {
            number_value: 3.53
          }
          values {
            number_value: 1.535
          }
        }
      }
    }
  }
}
response {
  meta {
    metrics {
      key: "mycounter"
      value: 1.0
    }
    metrics {
      key: "mygauge"
      type: GAUGE
      value: 100.0
    }
    metrics {
      key: "mytimer"
      type: TIMER
      value: 20.200000762939453
    }
  }
  data {
    names: "t:0"
    names: "t:1"
    names: "t:2"
    names: "t:3"
    ndarray {
      values {
        list_value {
          values {
            number_value: 6.44
          }
          values {
            number_value: 3.067
          }
          values {
            number_value: 3.53
          }
          values {
            number_value: 1.535
          }
        }
      }
    }
  }
}
reward: 1.0

Response:
meta {
  metrics {
    key: "mycounter"
    value: 1.0
  }
  metrics {
    key: "mygauge"
    type: GAUGE
    value: 100.0
  }
  metrics {
    key: "mytimer"
    type: TIMER
    value: 20.200000762939453
  }
}
data {
  ndarray {
  }
}
```

Therefore it indeed seems this issue may be close already.

@cliveseldon Shall we modify any of this examples to illustrate this behaviour?
@jorgyz For Prometheus interaction please see https://github.com/SeldonIO/seldon-core/issues/1362. That's the issue mentioned by Clive in which we will discuss how the metrics and metadata will be handled in the future.
