### ISSUE TITLE
Openshift CRC install 

### ISSUE THREAD

**Issue by oluies** [SeldonIO/seldon-core#3161]
Openshift CRC install 

```
$ oc version
Client Version: 4.6.4
Server Version: 4.7.5
Kubernetes Version: v1.20.0+bafe72f
```

#3122

## Describe the bug
Trying to install on a local CRC instance. Istio installed. 

## To reproduce

1. helm uninstall 
```
$ helm uninstall  seldon-core-operator --namespace seldon-system
W0505 08:11:19.824809   17840 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
release "seldon-core-operator" uninstalled
```
2. helm install 
```
helm install -f values-seldon-core-operator.yaml seldon-core-operator seldonio/seldon-core-operator --namespace seldon-system
W0505 08:11:57.413861   15420 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W0505 08:11:59.233753   15420 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
NAME: seldon-core-operator
LAST DEPLOYED: Wed May  5 08:11:55 2021
NAMESPACE: seldon-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
3. istio gateways
```
$ oc apply -f seldon-gateway.yaml
gateway.networking.istio.io/seldon-gateway unchanged
kubeadmin@api-crc-testing:6443 pvctfjob .../git
$ oc apply -f seldon-networkpolicy.yaml
networkpolicy.networking.k8s.io/seldon-webhook unchanged
deploy ...
```
4. Check for control plane 
```
$ oc get pods --namespace seldon-system
No resources found in seldon-system namespace.
```

## Environment
Windows Redhat Openshift CRC 

```
$ oc version
Client Version: 4.6.4
Server Version: 4.7.5
Kubernetes Version: v1.20.0+bafe72f
```

* Deployed Seldon System Images: 

```
$ oc get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio
          value: redhat-connect-docker-test-remote.repo-k1.utv.xx.se/seldonio/engine:1.7.0
          value: redhat-connect-docker-test-remote.repo-k1.utv.xx.se/seldonio/seldon-core-executor:1.7.0
        image: redhat-connect-docker-test-remote.repo-k1.utv.xx.se/seldonio/seldon-core-operator:1.7.0
```

## Model Details 

`Error "failed calling webhook "v1.vseldondeployment.kb.io": Post "https://seldon-webhook-service.seldon-system.svc:443/validate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s": no endpoints available for service "seldon-webhook-service"" for field "undefined".`

**Comment by oluies** [comment]
Vals https://gist.github.com/oluies/fafadcf45311e5572a41282c7477a5bc

**Comment by oluies** [comment]
Saw this: 
```
Error creating: pods "seldon-controller-manager-74b9cdbbc8-" is forbidden: unable to validate against any security context constraint: 
[spec.containers[0].securityContext.runAsUser: Invalid value: 8888: must be in the ranges: [1000620000, 1000629999]]

```

Changed the users in the values to empty

**Comment by oluies** [comment]
Which helped 

```
$ oc get pods -n seldon-system
NAME                                         READY   STATUS    RESTARTS   AGE
seldon-controller-manager-7568f464b7-njvzg   1/1     Running   0          2m2s
```

But still problem with the webhook 

```
$ oc apply -f triton-pvc.yaml
Error from server (InternalError): error when creating "triton-pvc.yaml": Internal error occurred: failed calling webhook "v1alpha2.vseldondeployment.kb.io": Post "https://seldon-webhook-service.seldon-system.svc:443/validate-machinelearning-seldon-io-v1alpha2-seldondeployment?timeout=30s": x509: certificate has expired or is not yet valid: current time 2021-05-04T21:45:13Z is before 2021-05-05T07:25:53Z

```

**Comment by ryandawsonuk** [comment]
Seems you were hitting https://github.com/SeldonIO/seldon-core/issues/527

For the webhook you may need a [NetworkPolicy](https://docs.seldon.io/projects/seldon-core/en/latest/ingress/openshift.html?highlight=openshift#namespace-seldon-core-install) or you could go with [turning off the webhook](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/values.yaml#L33) as discussed in https://github.com/SeldonIO/seldon-core/issues/1529. I'd recommend checking you're on the latest version of seldon core. You also have the option to [install via operatorhub](https://operatorhub.io/operator/seldon-operator) as an alternative to helm - that install is aimed at openshift.

**Comment by oluies** [comment]
> You also have the option to [install via operatorhub](https://operatorhub.io/operator/seldon-operator) as an alternative to helm - that install is aimed at openshift.

Sure do you know how to inject the regsristy mirrors we are using? In HELM values I just edit them

executor:
  port: 8000
  metricsPortName: metrics
  image:
    pullPolicy: IfNotPresent
    registry: **redhat-connect-docker-test-remote.repo-k1.utv.xx.se**
    repository: seldonio/seldon-core-executor
    tag: 1.7.0

**Comment by ryandawsonuk** [comment]
Well when you install via operatorhub, it creates a Subscription and [that can be edited](https://github.com/SeldonIO/seldon-deploy-operator/blob/master/helm-charts/seldon-deploy/templates/openshift-seldon-core-subscription.yaml). I think each of the settings you need [can be set as environment variables](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml). I guess it's up to you whether this is easier or more difficult than the helm route.

**Comment by oluies** [comment]
> Well when you install via operatorhub, it creates a Subscription and [that can be edited](https://github.com/SeldonIO/seldon-deploy-operator/blob/master/helm-charts/seldon-deploy/templates/openshift-seldon-core-subscription.yaml). I think each of the settings you need [can be set as environment variables](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml). I guess it's up to you whether this is easier or more difficult than the helm route.

I did not understand how to edit in the image repository there, I was there looking.

**Comment by ryandawsonuk** [comment]
True, you can't change the image of the operator itself as that isn't an environment variable, it's only the other images that can be changed as environment variables.

**Comment by oluies** [comment]
Env value for TRITON_SERVER is missing?

https://github.com/SeldonIO/seldon-core/blob/v1.7.0-release/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml

**Comment by ryandawsonuk** [comment]
Yeah that does appear to be missing. If you're not using that then you don't necessarily need to worry about it. The triton image would only be pulled when a Triton model is used.

I said above you could change most of the images through env section in the Subscription if using operatorhub. I think the one image you can't change like that is the operator image itself. That one is [set in the ClusterServiceVersion](https://github.com/SeldonIO/seldon-core/blob/master/operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml#L51) which is installed automatically when installing from operatorhub. If the hosting of that image is a problem for you and you want to go the operatorhub route then it is possible to install a ClusterServiceVersion yourself and then edit the resulting Subscription. [Here](https://github.com/SeldonIO/seldon-deploy-operator/blob/0.7.0-branch/openshift-full-setup/seldon/install.sh) is an example of doing that.

**Comment by cliveseldon** [comment]
Are you sure you are not hitting https://github.com/SeldonIO/seldon-core/issues/3019 ?

**Comment by oluies** [comment]
> Are you sure you are not hitting #3019 ?

1. I did run "oc adm policy add-scc-to-group anyuid system:serviceaccounts:<namespace> on the namespace I tried to run TRITON in 
![image](https://user-images.githubusercontent.com/150961/117416039-431dc600-af19-11eb-9ac5-8e64dcb64d71.png)

2. problem is that I cannot reach nvcr so I have to redirect that image to a internal repository (artifactory)

**Comment by oluies** [comment]
> I said above you could change most of the images through env section in the Subscription if using operatorhub. I think the one image you can't change like that is the operator image itself. That one is [set in the ClusterServiceVersion](https://github.com/SeldonIO/seldon-core/blob/master/operator/bundle/manifests/seldon-operator.clusterserviceversion.yaml#L51) which is installed automatically when installing from operatorhub. If the hosting of that image is a problem for you and you want to go the operatorhub route then it is possible to install a ClusterServiceVersion yourself and then edit the resulting Subscription. 

Tried that looks promesing but says **CatalogSource was removed**.

![image](https://user-images.githubusercontent.com/150961/117417571-c7bd1400-af1a-11eb-9fbd-a21b271ca4eb.png)

**Comment by ryandawsonuk** [comment]
Does 'catalogsource was removed' cause it to not work? It looks like a warning.

Presumably the triton stuff is more serious for you. I'd assumed above that you weren't specifically trying to use triton. But from your recent comments it sounds like you do want to use the triton server?

**Comment by oluies** [comment]
1. Seemes to work just uncertain on why it is there I get `Error "failed calling webhook "v1.vseldondeployment.kb.io": Post "https://seldon-webhook-service.openshift-operators.svc:443/validate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s": service "seldon-webhook-service" not found" for field "**undefined**".`
2. Triton is a nice to have, but can live witout it for now.

**Comment by cliveseldon** [comment]
Number 1 seems a strange error is the operator installed and running ok. Is there a `seldon-webhook-service` SVC running in the operator namespace for seldon.

**Comment by oluies** [comment]
> Number 1 seems a strange error is the operator installed and running ok. Is there a `seldon-webhook-service` SVC running in the operator namespace for seldon.

**If I install through the user interface (operatorhub add certified seldon operator)** 
$ oc get pods -A |grep seldon
openshift-operators                          seldon-controller-manager-7c6f5d696c-v2tcn                        1/1     Running     0          2m24s
$ oc get services -A |grep seldon
openshift-operators                                seldon-webhook-service                     ClusterIP      10.217.4.24    <none>                                 443/TCP                                         5m34s

**with oc apply** 
$ oc get services -A |grep seldon
kubeadmin@api-crc-testing:6443 pvctfjob .../operator
$ oc get pods -A |grep seldon
kubeadmin@api-crc-testing:6443 pvctfjob .../operator
$

**Comment by cliveseldon** [comment]
Please reopen if not working with latest Seldon Core.
