### ISSUE TITLE
Add support for gRPC to Java JNI wrapper

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#3165]
The JNI wrapper doesn't currently support gRPC. This requires figuring out a way to implement the "payload passthrough" on the gRPC server. Otherwise, we risk an increased latency due to de-serialising and serialising payloads twice (once in the Python server and another one in the Java side).

**Comment by cliveseldon** [comment]
Java will be supported via MLServer which support grpc.
