### ISSUE TITLE
High latency, is seldon-core hard for transmit the big picture data?

### ISSUE THREAD

**Issue by archwolf118** [SeldonIO/seldon-core#3173]
I want to use seldon-core to do some deep learning missions, like segmentation or objection-detection.
I found if we transmit big picture, the latency is too high.
below is my code:
```
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
h, w =  img.shape[:2]
sc = SeldonClient(microservice_endpoint="127.0.0.1:9002")
res = sc.microservice(data=img, method="predict", payload_type="ndarray",transport="rest")
```
if the img is 1024*1024 pixel (very normal for object detection mission), the transmit latency is about 30s, and then the model begin to tackle the image nparray.
Any suggest?
Thank you for your help!

**Comment by axsaucedo** [comment]
There is most likely an overhead on serialising the numpy array into rest request, and then the serialisation / deserialisation inside the model - although not clear from the details provided.

Either way, you can avoid any of these serialisation costs by sending the request using the `raw_data` parameter in the seldon client's `sc.predict` or just using the python `requests.post` library, and then in the deployed model wrapper using the `predict_raw` function of the seldon python wrapper instead of the `predict` function

**Comment by archwolf118** [comment]
@axsaucedo Thank you!
I use the bin_data to transfer bytes object, and speed is very fast.

```
def convert_image_to_binary(image_path):
    image = Image.open(image_path)
    img_bytes = io.BytesIO()
    image.save(img_bytes, format="JPEG")
    image_bytes = img_bytes.getvalue()
    return image_bytes

image_bytes = convert_image_to_binary(img_path)
res = sc.predict(bin_data=image_bytes, transport="rest",gateway_endpoint="localhost:9002", deployment_name="dbnet", gateway='seldon')
```

**Comment by axsaucedo** [comment]
@archwolf118 ok that makes sense - in that case did you get a chance to try using `predict_raw` inside of your python wrapper implementation? That would remove most of the serialisation costs - do you know where most of the latency is currently added in your usecase? We'd be keen to introduce any optimizations if there are actually bottlenecks that cannot be overcome with these functions

**Comment by axsaucedo** [comment]
Just following up with this @archwolf118 - did you get a chance to try out that suggestion above?

**Comment by archwolf118** [comment]
@axsaucedo yes, I use `sc.predict` This function call "predict_raw function" in docker directly.
My class is:
`class panet(object):
    def __init__(self):
        self.loaded = False
    def load_model(self):
        print("*****load model*****")
        DEVICE = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
        self.model = load_model("./model/panet.pth", DEVICE)
    def predict_raw(self, request):
        data = request.get("binData", {})
        if data != None:
            byte_data = base64.b64decode(data)
            img = Image.open(io.BytesIO(byte_data))
            return self.inference(np.array(img))
    def predict(self, X, features_names):
        return self.inference(X)
    def inference(self, X):
        X = X.astype(np.uint8)
        if not self.loaded:
            self.load_model()
            self.loaded = True
        boxList = im_detect_all_v1(self.model, X)
        res = json.dumps({'boxlist': np.array(boxList).tolist()})
        return res`

You can see I init the model in the first predict in GPU environment, because __init__ function init the model the main process, and cuda threads cannot find the model weights. So I suggest the your team consider this problem in GPU environment (CPU environment has no this problem).

**Comment by alex-seto** [comment]
Hello, I have been following this thread as I have also been trying to construct a seldon graph which includes a model which takes an image as input. It is awesome to see that this shaves so much time off my prediction time but I was wondering if there are any suggestions about how to apply this method such that the model can take multiple images at one time. My current thought is to serialize the images together and pass this to the model where it would unserialize them into a list of images but I am wondering if there is a more straight forward method. Thanks.

**Comment by cliveseldon** [comment]
Closing this but please reopen in a separate issue if any of the participants has an example they want to delve deeper into for which they have an issue.
