### ISSUE TITLE
Seldon graph complexity 

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3184]
![image](https://user-images.githubusercontent.com/57779683/117913879-c887e880-b314-11eb-83e8-8655b5776b1e.png)
Hi @RafalSkolasinski @cliveseldon . I am using seldon core 1.1.0 version .Can seldon graph be created for the above pipleine?
If so can you show how the seldon graph is structured.

**Comment by divyadilip91** [comment]
graph: 
        children:
        - name: combiner1
          endpoint:
            type: REST
          type: COMBINER
          children:
          - name: model1
            endpoint:
              type: REST
            type: MODEL
            children: 
            - name: model2
              endpoint: 
                type: REST
              type: MODEL
              children: []
          - name: model1
            endpoint:
              type: REST
            type: MODEL
            children:
            - name: model3
              endpoint: 
                type: REST
              type: MODEL
              children: []
        name: outputtransformer
        endpoint:
          type: REST
        type: OUTPUT_TRANSFORMER

I tried the above graph and it does not seem to be working

**Comment by cliveseldon** [comment]
For the current Seldon Core I think you can get it to work with

```
model1 -> output-transformer -> combiner -> (model2, model3)
```

You could also look at [Tempo](https://github.com/SeldonIO/tempo)  our new Python MLOps SDK which would make this structure much easier.

**Comment by divyadilip91** [comment]
@cliveseldon Thankyou so much. The above graph you mentioned worked.
