### ISSUE TITLE
Adjust outlier examples to use rclone based storage initializer

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3189]
Oncehttps://github.com/SeldonIO/seldon-core/pull/3159is merged we should adjust outlier server and outlier examples to use the storage initializer pattern and new rclone-based storage initializer.

**Comment by axsaucedo** [comment]
@RafalSkolasinski may be worth linking to PR - I've moved to MLOps sprint "in review"

**Comment by RafalSkolasinski** [comment]
It should be linked already

![image](https://user-images.githubusercontent.com/10928117/118245233-75d73980-b498-11eb-8244-0a4ef607f7c7.png)
![image](https://user-images.githubusercontent.com/10928117/118245242-78399380-b498-11eb-80c9-9746a830da9b.png)
