### ISSUE TITLE
New Flask version

### ISSUE THREAD

**Issue by naor2013** [SeldonIO/seldon-core#3202]
Flask 2.0 has been released with many interesting improvements and features. It would be great if you can update the dependencies to use it.
There is already a pull request opened by the bot here: #3194

**Comment by juliusvonkohout** [comment]
@axsaucedo  is there something specific holding this back? Is there something i can test for you with flask 2.0?

**Comment by cliveseldon** [comment]
@juliusvonkohout are you able to provide a PR for this.

**Comment by juliusvonkohout** [comment]
Well i can test to just replace the dependencies and see if it works, but i have to fix a lot of other stuff in kubeflow with higher priority first.

**Comment by axsaucedo** [comment]
We are now recommending moving to MLServer instead which is the v2 python wrapper which runs by default in seldon core when the `v2` protocol is enabled, and we will be moving towards making this the default in the short/medium term https://mlserver.readthedocs.io/en/latest/
