### ISSUE TITLE
RBAC name

### ISSUE THREAD

**Issue by oluies** [SeldonIO/seldon-core#3212]
https://github.com/SeldonIO/seldon-core/blob/fdbe433281a199ec9485c35b8d84deef3b9537d0/helm-charts/seldon-core-analytics/templates/prometheus/prometheus-rbac.yaml#L5

Why are thease cluster level? Can the name be configured?

**Comment by cliveseldon** [comment]
This helm chart is an example Prometheus integration. We welcome further updates to allow configuration for it if you wish to propose a PR. For production many people run their own Prometheus setup basing the configuration on this to scrape seldon metrics.
