### ISSUE TITLE
Kafka - Make producer optional

### ISSUE THREAD

**Issue by naor2013** [SeldonIO/seldon-core#3224]
Currently, when using the Kafka executor of seldon-core, you are required to have a Consumer and a Producer.
It makes sense that the Consumer is always required because it is the trigger that runs the prediction. It cannot be optional.
But the Producer can be optional if the user wants to save the output in another way he chooses, for example, in a DB.
A good point that @axsaucedo made is the following:

> we should consider that the "callers" or producers of inference datapoints may still require an output instance produced to acknowledge end-to-end processing, an example can be found in our implementation of the kafka enabled service orchestrator graph which executes the seldon computational graph with kafka topics, but still has the respective logic to ensure data instances flow through each of the nodes (this is particularly important with combiner/aggregating nodes). Due to this, we may require always the producer outputto be available.

This seems to be mostly talking about the Kafka graph feature which is disabled by default.
Maybe a good solution for this would be to make Producer required when the graph feature is enabled but optional otherwise.

A PR with a starting point for this feature can be found here: #3223

**Comment by cliveseldon** [comment]
Can you describe more your use case where you don't want an output topic?

**Comment by naor2013** [comment]
@cliveseldon sure.
My use case is that I have data coming in from Kafka topics. I want to trigger a prediction every time data comes in from that topic as a Producer.
So far that's how Seldon works so great!
But my "consumer" for the output data expects it in a DB and not a Kafka topics.
My prediction saves that data into a DB and doesn't "return" anything from the function.
I can set it up to a "mock" Consuner topic and just delete the data there just so I can work with Seldon but I rather it would be optional.

**Comment by cliveseldon** [comment]
Sounds like its an easy fix to make this optional. I suppose many organisation would have that DB code separated and reading from the producer topic to save. If you can create a PR that allows the producer as optional that would be great.

**Comment by naor2013** [comment]
> Sounds like its an easy fix to make this optional. I suppose many organisation would have that DB code separated and reading from the producer topic to save. If you can create a PR that allows the producer as optional that would be great.

I already had a PR combined with code for another issue but I'm not familiar enough with Go so I don't know how to compile or test it. It might be easy enough for you guys to take the part of my PR that is relevant and change it a bit to make sure it works.

**Comment by cliveseldon** [comment]
Can you try your use case with a custom MLServer model inside a Pipeline in v2?
