### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by Augis363** [SeldonIO/seldon-core#3235]
## Describe the bug

The documentation of how to use model wrapper with the current TensorFlow version (2.41 or 2.5) is missing. The current one -> https://docs.seldon.io/projects/seldon-core/en/v1.8.0/python/python_component.html is quite outdated and it takes quite a lot of time to figure out how to use it.

Could someone update this and include examples with TensorFlow>2.4.1?
Thanks in advance!

**Comment by cliveseldon** [comment]
Do you have sections you could contribute here?

**Comment by cliveseldon** [comment]
Docs have been updated in general. Please reopen if further clarifications needed
