### ISSUE TITLE
Usage of route_raw in seldon core 1.1.0

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3236]
Hi @RafalSkolasinski @cliveseldon ,
I am working on an urgent usecase where I want to serve a single endpoint and it redirects to either of the 2 models based on input model selecction. Hence I would like to use a router with route_raw function. It doesnt seem to work and I am bit confused on how the router works when a route_raw function is used and what would be the datatype of the object returned from route_raw function.?

This is the seldon graph to be formed.
![image](https://user-images.githubusercontent.com/57779683/119834066-35fd6100-bf32-11eb-8e68-899b40e56b28.png)

```
def route_raw(self,features):
       """
        Route a request.
        Parameters
        ----------
        features : dictionary
        """
        try:
            if features["model"]=="model1":
                return {"N":1}  #redirect the request to child 1 (model1)
            else:
                return {"N":2}  #redirect the request to child 2 (model2)
            else:
        except Exception as e:
            logging.error(e,sys.exc_info())
            return {"error":str(sys.exc_info())}

The above code doesnt work. Am I doing any mistake?

This is the seldon graph used 
''' graph:
        name: inputtransformer
        endpoint:
            type: REST
        type: TRANSFORMER
        children:
        - endpoint:
            type: REST
          name: router
          type: ROUTER
          parameters:
          - name: n_branches
            type: INT
            value: '2'
          children: 
          - name: model1
            endpoint:
              type: REST
            type: MODEL
            children: []   
          - name: model2
            endpoint:
              type: REST
            type: MODEL
            children: [] 
Can someone please help me on this urgently.

**Comment by cliveseldon** [comment]
You should return the child ID in a an ndarray. e.g.
```
{
"data" : {
 "ndarray": [0]
 }
}
```

See https://github.com/SeldonIO/seldon-core/blob/master/executor/api/util/utils.go

**Comment by divyadilip91** [comment]
Now its working.  @cliveseldon Thankyou very much for your help. Appreciate it. 
I would also suggest if there would be a documentation for the lower level methods used in seldon  along with examples to avoid future problems.
