### ISSUE TITLE
Seldon-request-logger with Bulks API

### ISSUE THREAD

**Issue by shoval-a** [SeldonIO/seldon-core#3242]
Currently seldon-request-logger doesn't support Bulk API (optimized way for ingesting documents to Elasticsearch), and not inserting document one-by-one like now.
In addition, we would like you to add some index partitioning configuration. For instance, daily Elasticsearch  index configuration (yyyy-MM-dd) or monthly Elasticsearch  index configuration (yyyy-MM) and not just one Elasticsearch index like now (one index which handles the entire logs is not best practice for read/write operations).

**Comment by ryandawsonuk** [comment]
Date-based indexes would make it a lot easier to configure [curator](https://medium.com/@hagaibarel/running-curator-as-a-kubernetes-cronjob-19eaab9afd3b) to remove old data. This would make a lot of sense in that respect.

Using the bulk API I'm not so sure about. Our current insertion method is upsert and it's not even really one-by-one. When a response comes in for a request then the response is added to the request document. The document can be further enriched with data later from detectors (e.g. is this an outlier). Each step is unaware of what is already in the document and just adds its piece. So moving to the bulk API would basically be a redesign.

**Comment by cliveseldon** [comment]
Fixed.
