### ISSUE TITLE
Documentation for lower level methods for the Seldon components along with sample code and yaml

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3245]
Hi ,
I would like to suggest if there would be a documentation for the lower level methods used in seldon along with examples to avoid future problems regarding the input and output types, the yaml formats etc.
#3236

**Comment by cliveseldon** [comment]
Docs have been updated but we plan to move more towards v2 API used by [MLServer](https://github.com/SeldonIO/mlserver) and Triton. See there for docs.
