### ISSUE TITLE
cant build simple-cpp example

### ISSUE THREAD

**Issue by eugtsa** [SeldonIO/seldon-core#3251]
## Describe the bug
simple-cpp example from https://docs.seldon.io/projects/seldon-core/en/latest/examples/cpp_simple.html is not working

## To reproduce
Install docker, brew on mac. Install s2i via brew.
1. `git clone https://github.com/SeldonIO/seldon-core.git`
2. `cd seldon-core; jupyter notebook`
3. locate `notebooks/examples/models/cpp/simple-cpp/README.ipynb`
4. run all cells

Cell with s2i call would produce an error: 
```
pulling image error : Error response from daemon: pull access denied for seldonio/s2i-cpp-build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
pulling image error : Error response from daemon: pull access denied for seldonio/s2i-cpp-build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: An error occurred: unable to get seldonio/s2i-cpp-build:0.0.1
ERROR: Suggested solution: check image name, or if using a local image set the builder image pull policy to "never"
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.
```

If I include `docker login` before that same call, so the cell is `!docker login; s2i build . seldonio/s2i-cpp-build:0.0.1 seldonio/simple-cpp:0.1` then I get:
```
Authenticating with existing credentials...
Login Succeeded
pulling image error : Error response from daemon: pull access denied for seldonio/s2i-cpp-build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
pulling image error : Error response from daemon: pull access denied for seldonio/s2i-cpp-build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: An error occurred: unable to get seldonio/s2i-cpp-build:0.0.1
ERROR: Suggested solution: check image name, or if using a local image set the builder image pull policy to "never"
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.
```

## Expected behaviour
No errors on model build

## Environment
Macos Big Sur 11.3.1
Docker desktop 3.3.0 (62916), Engine 20.10.5
s2i v1.3.1-dirty (installed with brew)

## Additional comments
s2i works, for example I can build ```s2i build https://github.com/openshift/ruby-hello-world centos/ruby-25-centos7 test-ruby-app;docker run --rm -i -p :8080 -t test-ruby-app``` successfully

**Comment by axsaucedo** [comment]
Thank you for reporting this, it seems there are reported issues with cmake in ubi8 images so we'll have a look at why this is the case.
