### ISSUE TITLE
Custom name for Seldon deployment instead of metadataname-graph component names

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3253]
Hi @cliveseldon @RafalSkolasinski ,
Is there a way to give a customname for the seldon deployment rather the automatic formation of name from the metadataname and graph component names.
Eg : if we have multiple components in our graph and if the automatically formed name exceeds the length limit , a dummy name starting with seldon-2323133 is formed which becomes confusing in between such multiple deployments. I am using seldon core v1.1.0
![image](https://user-images.githubusercontent.com/57779683/120460479-bfe27980-c3cb-11eb-9246-3685a5721c42.png)

Can user customise the name ?

**Comment by axsaucedo** [comment]
This is currently possible by adding the `"seldon.io/svc-name"` annotation to your seldondeployment manifest

**Comment by divyadilip91** [comment]
Hi @axsaucedo , 
I am using seldon core 1.1.0 and tried the above annotation and it does not seem to work. It still shows the name as seldon-random number.
Is there some additional setting that needs to be done.
Awaiting for your response
Thanks
