### ISSUE TITLE
How to integrate existing mlflow Docker Image

### ISSUE THREAD

**Issue by sivakumarl** [SeldonIO/seldon-core#3259]
Hi Team,
               We had mlflow custom docker image currently and serving the model with the help of mlflow api's (mlflow models serve) , now we are trying to integrate seldon by leveraging the existing image . Please let us know the possibilities. Thank you

Regards,
Siva Kumar.

**Comment by cliveseldon** [comment]
Please see [MLServer](https://github.com/SeldonIO/mlserver) docs and reopen if an issue there.
