### ISSUE TITLE
Failed Calling Webhook 

### ISSUE THREAD

**Issue by rahuja23** [SeldonIO/seldon-core#3263]
When trying to deploy one of our models with an output transformer the model deployment fails showing the following error:
`Error from server (InternalError): error when creating "model-test2.yaml": Internal error occurred: failed calling webhook "v1.vseldondeployment.kb.io": Post "https://seldon-webhook-service.seldon-system.svc:443/validate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s": EOF`

The log files on seldon-controller-manager shows the following error:
`{"level":"info","ts":1622803381.7529385,"logger":"seldondeployment","msg":"Validating v1alpha2 Webhook called for CREATE","name":"tfserving-transporter-testing"}
 2021/06/04 10:43:01 http: panic serving 10.42.0.0:52991: runtime error: invalid memory address or nil pointer dereference
 goroutine 500 [running]:
 net/http.(*conn).serve.func1(0xc0002ee960)
     /usr/local/go/src/net/http/server.go:1800 +0x139
 panic(0x17031c0, 0x27a5c10)
     /usr/local/go/src/runtime/panic.go:975 +0x3e3
 github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1.(*SeldonDeploymentSpec).checkPredictiveUnits(0xc00000d978, 0xc0007f44d0, 0xc000bda838, 0xc000980180, 0x0, 0x0, 0x0, 0x28, 0xc000bda488, 0x40de46)
     /workspace/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go:83 +0xe3f
 github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1.(*SeldonDeploymentSpec).checkPredictiveUnits(0xc00000d978, 0xc000bda848, 0xc000bda838, 0xc000980150, 0x0, 0x0, 0x0, 0x801, 0xc000214240, 0x400)
     /workspace/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go:120 +0x425
 github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1.(*SeldonDeploymentSpec).ValidateSeldonDeployment(0xc00000d978, 0x1920b1f, 0x2d)
     /workspace/apis/machinelearning.seldon.io/v1/seldondeployment_webhook.go:251 +0x56e
 github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1alpha2.(*SeldonDeployment).ValidateCreate(0xc00000d860, 0xc000afcd80, 0x24)
     /workspace/apis/machinelearning.seldon.io/v1alpha2/seldondeployment_webhook.go:48 +0xde
 sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*validatingHandler).Handle(0xc00079c880, 0x1b629a0, 0xc00013e7c0, 0xc000afcd80, 0x24, 0xc000b156a0, 0x19, 0xc0005f8670, 0x8, 0xc0005f8680, ...)
     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/webhook/admission/validator.go:69 +0x9a4
 sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(0xc00079b1a0, 0x1b629a0, 0xc00013e7c0, 0xc000afcd80, 0x24, 0xc000b156a0, 0x19, 0xc0005f8670, 0x8, 0xc0005f8680, ...)
     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/webhook/admission/webhook.go:135 +0xa7
 sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc00079b1a0, 0x7f409c8bf8f8, 0xc000473400, 0xc000ab7700)
     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/webhook/admission/http.go:87 +0xada
 github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7f409c8bf8f8, 0xc000473400, 0xc000ab7700)
     /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:40 +0xab
 net/http.HandlerFunc.ServeHTTP(0xc00079b440, 0x7f409c8bf8f8, 0xc000473400, 0xc000ab7700)
     /usr/local/go/src/net/http/server.go:2041 +0x44
 github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x1b5eee0, 0xc0009442a0, 0xc000ab7700)
     /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:100 +0xda
 net/http.HandlerFunc.ServeHTTP(0xc00079b590, 0x1b5eee0, 0xc0009442a0, 0xc000ab7700)
     /usr/local/go/src/net/http/server.go:2041 +0x44
 github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x1b5eee0, 0xc0009442a0, 0xc000ab7700)
     /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:76 +0xb2
 net/http.HandlerFunc.ServeHTTP(0xc00079b680, 0x1b5eee0, 0xc0009442a0, 0xc000ab7700)
     /usr/local/go/src/net/http/server.go:2041 +0x44
 net/http.(*ServeMux).ServeHTTP(0xc0007b4100, 0x1b5eee0, 0xc0009442a0, 0xc000ab7700)
     /usr/local/go/src/net/http/server.go:2416 +0x1a5
 net/http.serverHandler.ServeHTTP(0xc0000d9500, 0x1b5eee0, 0xc0009442a0, 0xc000ab7700)
     /usr/local/go/src/net/http/server.go:2836 +0xa3
 net/http.(*conn).serve(0xc0002ee960, 0x1b629a0, 0xc00013e440)
     /usr/local/go/src/net/http/server.go:1924 +0x86c
 created by net/http.(*Server).Serve
     /usr/local/go/src/net/http/server.go:2962 +0x35c`

**Comment by axsaucedo** [comment]
This tends to mean that your model YAML is not valid - can you check that it complies with  all the required configurations? Please share the details as per the issue template with versions, yamls, logs, etc

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue with latest version.
