### ISSUE TITLE
Conda version in S2i builder image does not match Miniconda base image

### ISSUE THREAD

**Issue by ramanNarasimhan77** [SeldonIO/seldon-core#3264]
## Describe the bug

Conda version in S2i builder image does not match Miniconda base image

## To reproduce
Build the image using the `makefile` available in `wrappers/s2i/python` as shown below, docker build logs show that `conda` is not pinned

<img width="1680" alt="Screenshot 2021-06-04 at 9 41 23 PM" src="https://user-images.githubusercontent.com/52691361/120832156-f5c75f80-c57d-11eb-944f-7d12addecc72.png">

Alternatively check the conda version inside the s2i builder image

## Expected behaviour
From the Dockerfile it looks like the intention of the developer was to pin the conda version to the version defined in the `makefile` . 

To do so, the CONDA_VERSION arg has to be redeclared in the Dockerfile under the FROM statement as well 

Line1 has to be copied and pasted before this line
https://github.com/SeldonIO/seldon-core/blob/v1.6.0/wrappers/s2i/python/Dockerfile#L9 

Also, there are a bunch of other Dockerfiles in the same folder, same fix might be needed in those as well.

**Comment by axsaucedo** [comment]
Thanks for reporting this - looking at this issue, from the last work we did in these images we pinned the conda images based on the base images, which has seemed to be enough - is there a reason why this pinning is not enough even though it's still static?

**Comment by ramanNarasimhan77** [comment]
@axsaucedo 
The CONDA_VERSION arg is only available above the FROM statement, not below. So run command effectively becomes

`RUN conda install --yes python=3.7 conda=`

and this results in the installation of latest conda always. 

See https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

From the docker documentation:
`An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM. To use the default value of an ARG declared before the first FROM use an ARG instruction without a value inside of a build stage:`

Example
```
ARG VERSION=latest
FROM busybox:$VERSION
ARG VERSION
RUN echo $VERSION > image_version
`` `

**Comment by axsaucedo** [comment]
We've now updated the images - can you confirm if this issue still exists in the latest dockerfiles with your usecase?

**Comment by ramanNarasimhan77** [comment]
hi @axsaucedo - I have reviewed the fix and I can confirm that it looks good. Thank you for fixing this.
