### ISSUE TITLE
ValidatingWebhookConfiguration fails in case seldon is installed with cluster scope and istio MTLS strict

### ISSUE THREAD

**Issue by narasago** [SeldonIO/seldon-core#3266]
Error from server (InternalError): error when creating "seldon-sklearn.yaml": Internal error occurred: failed calling webhook "v1alpha2.vseldondeployment.kb.io": Post "https://seldon-webhook-service.testns.svc:443/validate-machinelearning-seldon-io-v1alpha2-seldondeployment?timeout=30s": x509: certificate is not valid for any names, but wanted to match seldon-webhook-service.testns.svc

## Describe the bug
Certification validation issue seen when creating SeldonDeployment. 

## To reproduce
1. Install istio with version 1.7.6 with sidecar injection, cni enabled. 
 sudo helm3 install istio-crd-install https://repo3.cci.nokia.net/artifactory/csf-generic-delivered/BCMT/istio-charts/bcmt-istio-init-1.5.0.tgz --atomic --namespace istio-system --create-namespace --set global.hub=csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/bcmt --set global.tag=1.7.6-centos7 --wait --timeout=300s

sudo helm3 install bcmt-istio https://repo3.cci.nokia.net/artifactory/csf-generic-delivered/BCMT/istio-charts/bcmt-istio-1.5.0.tgz --atomic --namespace istio-system --create-namespace --set global.hub=csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/bcmt --set global.tag=1.7.6-centos7 --set istiocni.enabled=true --set istiocni.repair.enabled=true --set istiocni.cniConfDir=/etc/cni/net.d --set sidecarInjectorWebhook.rewriteAppHTTPProbe=true

2. Install seldon-core-operator 1.6.0 with istio MTLS STRICT mode enabled. 
  helm install csf-incubator/seldon-core-operator -n seldon-core-operator --namespace india --set istio.injection.enabled=true --set istio.mtls.permissive=false --set singleNamespace=false
 kubectl get po -n testns
NAME                                         READY   STATUS    RESTARTS   AGE
seldon-controller-manager-75c48fbdfd-7qjkx   2/2     Running   1          55m

3. Create SeldonDeployment. 

kubectl create -f seldon-deployment.yaml -n testns 
Error from server (InternalError): error when creating "seldon-sklearn.yaml": Internal error occurred: failed calling webhook "v1alpha2.vseldondeployment.kb.io": Post "https://seldon-webhook-service.testns.svc:443/validate-machinelearning-seldon-io-v1alpha2-seldondeployment?timeout=30s": x509: certificate is not valid for any names, but wanted to match seldon-webhook-service.testns.svc

## Expected behaviour
SeldonDeployment should be created successfully followed by pods creation that serve the seldon model. 

## Environment

Simple sklearn example with the model stored in pvc.
Error seen in the seldon-controller-manager pod when seldon deployment is created:
kubectl logs seldon-controller-manager-75c48fbdfd-7qjkx -n testns manager
2021/06/06 15:24:55 http: TLS handshake error from 127.0.0.1:44428: EOF

**Comment by axsaucedo** [comment]
This seems that the error is with the validationwebhook as opposed to the deployment with the sidecar, from my understanding istio sidecars are only applied to pods and not directly to the k8s api webhooks - based on this, the issue seems to be with the expected certificates on the webhook configuration. You can see the helm chart that the cert step is present there so you should be able to override accordingly in the helm chart. Probably best to have a look there as from this I'm not clear it's a seldon specific issue but a current cluster configuration, although would be great to get more insights if that is not the case.

**Comment by cliveseldon** [comment]
You can set TLS MODE in helm chart. 

https://github.com/SeldonIO/seldon-core/blob/547d083ea2e0c1d8e0cf91fa704ef1b85f2b2e5b/helm-charts/seldon-core-operator/values.yaml#L19

This will be used to set the tls mode in the istoi destination rule.

**Comment by narasago** [comment]
Ok, I will try with the values ISTIO_MUTUAL and MUTUAL and post the results.

**Comment by narasago** [comment]
I just had chance to check with various tls modes of istio like "MUTUAL" and "ISTIO_MUTUAL". 

Found something about the mismatch in the certificates. In the validatingwebhookconfiguration, the certificate after decoding is:
-----BEGIN CERTIFICATE-----
MIIDZjCCAk6gAwIBAgIQNcfvwTmC0dEyoqq0GYD/2jANBgkqhkiG9w0BAQsFADAt
MSswKQYDVQQDEyJzZWxkb24td2ViaG9vay1zZXJ2aWNlLnNlbHRlc3Quc3ZjMB4X
DTIxMDYxNDE2MjcyM1oXDTIxMDkxMjE2MjcyM1owLTErMCkGA1UEAxMic2VsZG9u
LXdlYmhvb2stc2VydmljZS5zZWx0ZXN0LnN2YzCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALpbu7EtHOqNDYsjjyeKZWZ26j99RuSqc19WEsTG1z5rHShg
VDJhsO2IkA6LbBQEnOuU1XuzPKbcthrQ4TUOR8DSUBIGKdhlny096rES+pYVbXLL
PWHQXUSrQPa1AdNuxb7t2H4U0Y7LANzJfhJ+vN2QoePJH14TjnsPuNy7Jtlrf5EX
Gp5dfAYAjysLGaV9W81O7rcuFR/BhoFRq/iFCSjLtemyY2QLA6lRcRElKc0vv3yH
wxIu4NGuw3iUfb6wOEfYcSEEn2tuOETOj2tBcL+6IYQ1afBENA7lVFAQWN4Ljn/V
wX/8OZrzGsJL1F5QH7ay7D9FYEW48r2buh8dbsECAwEAAaOBgTB/MA4GA1UdDwEB
/wQEAwIFoDAMBgNVHRMBAf8EAjAAMF8GA1UdEQRYMFaCMHNlbGRvbi13ZWJob29r
LXNlcnZpY2Uuc2VsdGVzdC5zdmMuY2x1c3Rlci5sb2NhbIIic2VsZG9uLXdlYmhv
b2stc2VydmljZS5zZWx0ZXN0LnN2YzANBgkqhkiG9w0BAQsFAAOCAQEAIsEVsh0R
gJuymrlsHDIme0H4V3VAK0m3ulqTsXOZcENMVFGlmhOb9X2giKyu3oRPFdBWIfWl
kWvPCKZoZgH6fj91auiv+BoCmvTmDhys6TR0qMgVpFRupw5Wsoeq/neGKaUIOnJ/
XS6XB2CvQNtRV3COYwdc5bIHDeDwGZMhQjAlVKfnmg7+oR5qc6FApHmym7i40/ss
Yzu8EOyw1dHdpMXHv7XY73l8OvqVTt8doz+Q7CZpl8IoRHc62cJg/dr6XVugMdP5
aPZwwUbBhd1oxjoUXnOOuATWcSdVt/+55M+2ahyfRm9elzxJMMvuIuisNWajWqrB
5adpLtHmJNWn5Q==
-----END CERTIFICATE-----

It is same in the tls secret that is mounted in the service through deployment. The secret is created through cert manager.



When checked with the certificates that the webhook service is exposing, below are the certificates that don't match above one:

[root@nc0376node02 minio]# openssl s_client -showcerts -connect 10.254.190.113:443 -debug
CONNECTED(00000003)

Certificate chain
 0 s:
   i:/O=cluster.local
-----BEGIN CERTIFICATE-----
MIIDJzCCAg+gAwIBAgIRAMJsliyuHd5KZlcRWf9GBx8wDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMTA2MTYxMTQ2NDRaFw0yMTA2
MTcxMTQ2NDRaMAAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8ra51
r6dYFBc+OyH1rDurbhtd5UTO4sNTJgXxtMCYmkJFyvHNZYyXlrD6cyMktqvKGLFj
9bsDhZ/Mq0J7AQZr7SwwCGHzcSYV4s/U37sCCkmweGd7rsqySqhrrQ5la7FPszh+
qELkzeoBPrYALagsJnFq7hNIbuKSuwGn5Le+RvpW+s1HQNCyAMnAba3gMjDzVwp5
TIes9Bi60o3/HVxEIVaeCVzQ1tubkm/dazqC9fcT9/9LGTyP6UOi6y8rVC4C4DiN
B+/ikblTXdEm2VG7Ym8jTMa+uUKRjHm2xzGt/pBpBgcyG78xYfeKUPMl6DbIQEBG
0o1SlqbfbG2SZ3epAgMBAAGjgYMwgYAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMEEGA1UdEQEB/wQ3
MDWGM3NwaWZmZTovL2NsdXN0ZXIubG9jYWwvbnMvc2VsdGVzdC9zYS9zZWxkb24t
bWFuYWdlcjANBgkqhkiG9w0BAQsFAAOCAQEAzv30hyT3T1l6niCMNLclQkN6X6a6
o+QH0vNnd07REL3V+Hnx3VO61sfBOvQ+yKfERK3Y6ItOCJXAsqslCpr/DN7AlVNQ
ktTk5Jx9ud4QthXNc0Cr1EUVwKXCVaauazpH8HAEkhFSk0qbuzuqQJmYNxXAB0Yd
2qAhDfcD+d1CXI/QloOwPsefL9kpmMIpor+R4tHdYmsZI96tosuxwOGnq6v9IZSq
xc5KoEt4Jit/BxGlzLcyowATqSoUb6QJPVt0+aPHW+y3E4d0ENkPmVJ0oTl8QMMC
99yXfOF5qBbojGaV+jRBHDt32TZcySunIQF84aXG6ffJwpdB5EJ6ndzCPA==
-----END CERTIFICATE-----
 1 s:/O=cluster.local
   i:/O=cluster.local
-----BEGIN CERTIFICATE-----
MIIC3TCCAcWgAwIBAgIQdP9zNUTTm12h6jzCElhT+jANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIxMDUxMDA2MTEwMVoXDTMxMDUw
ODA2MTEwMVowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBANrV84cBafMEm1DcHYXIJo8jxTZzPaXJUHvnlD9G
5tBlWgt1f81PC8TbBIEe9h6bBNQG95BldY28XBTt8yloLXY61UMICiIhx7DPKg8+
bdsOzcyQxMNlJrRXHJJVMOgEdodwL2eUsAKqaZLIJs1qKIjISOjh83LjfSjtffKw
LX1WoxOkB2DTvYgBABNLO5R7+eW0o/+6bproecknxOBtDN7/JUDKEqbhBnketnOV
e7ZaZMsLrqucKP+57q2YalBrtwiXW2MX13HCewyM4hICP2wXDuKz6fZvrcDmsl8U
TwNm2v54HM5ooffu2PKx2yRoz2Fdd7EvAaNl/ftgvoNZ7Q0CAwEAAaMjMCEwDgYD
VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AM1BOJnJwOUgghhitxjz2DJvjjlzhrFU4w2RNiRq8QJspAa1GJYUOVA62oETaaOY
WtvqKNoQO1eBuIyWm5TNG4qzbvxBJVeksoG4BfarPBi1/wQi7E90L3TKVKGFS9FF
sXkFCfBhHSv7O0I0EPkcSq0lEb/OerRfKpd52bzQrg1pnQ/U4N+t101GY9Cctn6k
xHlgKPCyo3eOVXTwuXmG5lhjPcajbLrulGiIlhqdxSFt+BJjT+Uw9PNoWHwPYC8z
JYbAE/id9mk4KQGXDilDuCiivud+QkGkRet+rBQvgQ6BrTGq+Gx1cBMc2TLf0a5g
C+5N1RsFZYhF8BuA9xAkJPg=
-----END CERTIFICATE-----

Please note that only in this case(singlenamespace=false) the namespace matches the criteria mentioned in ValidatingWebhookConfiguration, otherwise the webhook is not invoked, which feels that no problem with the webhook. 


Please let me know for any information required further.

**Comment by narasago** [comment]
This actually looks to be an issue, if possible please have a check.

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
