### ISSUE TITLE
GRPC max message size not being set correctly

### ISSUE THREAD

**Issue by bdalal** [SeldonIO/seldon-core#3273]
## Describe the bug

I am setting the `grpc_max_send_message_length` and `grpc_max_receive_message_length` params to `1000 * 1024 * 1024` but the `predict` call still errors out with
```
Exception: Encountered error querying model: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (13625440 vs. 4194304)"
	debug_error_string = "{"created":"@1623098828.539796398","description":"Error received from peer ipv4:127.0.0.1:5000","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Received message larger than max (13625440 vs. 4194304)","grpc_status":8}"
>
```
indicating that the message size was not appropriately set.

## To reproduce

Here's the code I use to create the client and call `predict`:
```
class SeldonFetcher(BaseFetcher):
    def __init__(self, seldon_host: str = "127.0.0.1:5000", transport: str = "grpc"):
        super(SeldonFetcher, self).__init__("Seldon")
        self.seldon_host = seldon_host
        self.seldon_client = SeldonClient(
            microservice_endpoint=seldon_host,
            transport=transport,
            debug=False,
            client_return_type="proto",
            grpc_max_send_message_length=1000 * 1024 * 1024,
            grpc_max_receive_message_length=1000 * 1024 * 1024,
        )

    def query(
        self, data: np.ndarray, names: List[str], meta: Optional[Dict[str, Any]] = None
    ):
        return self.seldon_client.predict(
            data=data,
            names=names,
            transport="grpc",
            payload_type="ndarray",
            method="predict",
            meta=meta,
            gateway_endpoint=self.seldon_host,
        )

```

## Expected behaviour

Message size should be updated as expected and resource exhausted error shouldn't show up.

## Environment

Version: `1.8.0`

**Comment by cliveseldon** [comment]
Have you tested the notebook https://docs.seldon.io/projects/seldon-core/en/latest/examples/max_grpc_msg_size.html ?

**Comment by bdalal** [comment]
@cliveseldon Thanks for getting back and apologies on the delay, I was on vacation.
I haven't tested this notebook but I'm not deploying my model in kubernetes either. I run it as a simple docker container via `seldon-core-microservice`.
Do I need to set separate env variables in my container to enable larger messages?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.

**Comment by zachary-jablons-okcupid** [comment]
I'm encountering a similar issue - I'm just testing this image out now, and haven't gotten to setting it up in Kubernetes, but I'd like to avoid that if possible at this stage. I'm not clear how to translate the instructions in [this guide](https://docs.seldon.io/projects/seldon-core/en/latest/examples/max_grpc_msg_size.html) to a situation where I'm just building the image from a Dockerfile and running it directly.

**Comment by cliveseldon** [comment]
See https://github.com/SeldonIO/seldon-core/blob/008f4da969753903ba9a37a79bb62e3e1a5bf43c/python/seldon_core/wrapper.py#L291

**Comment by zachary-jablons-okcupid** [comment]
Yeah - I've been poking around the codebase, and it seems like if I set an annotations file that mocks what's expected in `/etc/podinfo/annotations` and just copy it there, that might work - testing that right now. 

If there's a more direct route would be happy to hear it, but I'm not clear how I can set it through `exec seldon-core-microservice` otherwise.
