### ISSUE TITLE
Clarity needed for ivp6 support for seldon core executor and sklearn 

### ISSUE THREAD

**Issue by Pallavi-28** [SeldonIO/seldon-core#3274]
Hi,
As per my understanding, seems that ipv6 support for seldon core executor is not available . referred beflow file to understand a bit .
https://github.com/SeldonIO/seldon-core/blob/v1.6.0/executor/api/rest/server.go . 

Also, while trying serving with sklearn server , figured out that liveliness probe is failing with ipv6 address.
`Events:
  Type     Reason     Age                    From                                          Message
  ----     ------     ----                   ----                                          -------
  Warning  Unhealthy  51m (x968 over 21h)    kubelet, bcmt-sandbox8-3c3w2e-2003-worker-02  Liveness probe failed: dial tcp [2001:283:4000:2001::5d31]:9000: connect: connection refused
  Warning  Unhealthy  21m (x4165 over 21h)   kubelet, bcmt-sandbox8-3c3w2e-2003-worker-02  Readiness probe failed: dial tcp [2001:283:4000:2001::5d31]:9000: connect: connection refused
  Normal   Started    6m9s (x334 over 21h)   kubelet, bcmt-sandbox8-3c3w2e-2003-worker-02  Started container classifier
  Warning  Unhealthy  68s (x10075 over 21h)  kubelet, bcmt-sandbox8-3c3w2e-2003-worker-02  Readiness probe failed: HTTP probe failed with statuscode: 503`
  

I had checked in below mentioned file which indicates that ivp6 support is not there for sklearn server as well ,https://github.com/SeldonIO/seldon-core/blob/v1.6.0/python/seldon_core/microservice.py 

can you please confirm that ipv6 support is available for seldon ?

**Comment by axsaucedo** [comment]
@Pallavi-28 I don't think this has been explicitly added as a feature, but we are using Flask as the core orchestrator in the v1 python wrapper and fastAPI on the v2 python wrapper (mlserver), I would assume that these both support IPV6 and would only require configurations on the respective servers. This is most likely something that would be on their documentation however - if you are able to do some investigation we would be keen to update the documentation in Seldon Core to point to the relevant pages on their side

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.

**Comment by chethanmahadevaiah** [comment]
From the below link I understand for starting the flask application which can work on dual ipv4 and ipv6 or pure ipv6 machines should start the app with **app.run(host='::')**

https://quorten.github.io/quorten-blog1/blog/2016/07/20/ipv4-ipv6-python-flask
https://www.titanwolf.org/Network/q/59b5e9d1-e6f9-47cf-8814-c6303fc3e911/y
https://stackoverflow.com/questions/7023052/configure-flask-dev-server-to-be-visible-across-the-network

However, in the seldon core we are observing host is configured with ipv4 only while starting the flask app.

https://github.com/SeldonIO/seldon-core/blob/v1.11.0/python/seldon_core/microservice.py#L392

        def rest_prediction_server():
            app = seldon_microservice.get_rest_microservice(user_object, seldon_metrics)
...
...
            app.run(
                **host="0.0.0.0",**
                port=http_port,
                threaded=False if args.single_threaded else True,
            )

**Comment by cliveseldon** [comment]
We presently don't support ipv6 on k8s. Happy to revisit as this becomes more the norm. Any PR might need to handle all components in an inference graph not just Flask, i.e. executor, request logger, knative and all servers.
