### ISSUE TITLE
page on openshift covering metrics setup

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#3275]
We currently have https://github.com/SeldonIO/seldon-core/blob/master/doc/source/ingress/openshift.md but that's a page on ingress. We could do with something under reference covering metrics too. Kinda similar to https://docs.seldon.io/projects/seldon-core/en/latest/analytics/kubeflow.html. It can point to the other page for ingress.

On metrics there's two things we do to make that work.

One is telling core to use metrics path '/metrics':
https://github.com/SeldonIO/seldon-deploy-operator/blob/master/helm-charts/seldon-deploy/values-redhat.yaml#L239

The other is creating the PodMonitor resources to tell openshift prom to scrape:
https://github.com/SeldonIO/seldon-deploy-operator/blob/master/helm-charts/seldon-deploy/templates/openshift-prometheus-monitoring.yaml

Need to explain this. And also that the metrics should be visible in the built-in openshift prometheus.

**Comment by oluies** [comment]
What does "--set usageMetrics.enabled=true" do in the Helm chart?

**Comment by ryandawsonuk** [comment]
That enables anonymous usage metrics to be collected so that the Seldon team can see how much use the tool is getting

**Comment by oluies** [comment]
Yay seemes to work

![image](https://user-images.githubusercontent.com/150961/121475796-29fbaf80-c9c6-11eb-9341-2e9b1f14efe7.png)
