### ISSUE TITLE
Image seldonio/seldon-core-s2i-python3 is missing in Red Hat Ecosystem Catalog

### ISSUE THREAD

**Issue by jensaug** [SeldonIO/seldon-core#3276]
## Describe the bug
Of the [31 images Seldon provides as OpenShift certified images in the RedHat Ecosystem Catalog](https://catalog.redhat.com/software/containers/search?q=Seldon&p=1&vendor_name=Seldon&rows=60) none is seldonio/seldon-core-s2i-python3. Thus, OpenShift users depending on certified images from Seldon can deploy Seldon Operator, but Jenkins/OpenShift pipelines cannot build images using Seldons s2i wrapper.

This is filed as a bug since this behaviour [surprised some in a Slack Seldon Community discussion](https://seldondev.slack.com/archives/C8Y9A8G0Y/p1623067950194900).

## To reproduce
1. podman pull registry.connect.redhat.com/seldonio/seldon-core-s2i-python3
2. [login]
3.  Response is 
```
Error: Error initializing source docker://registry.connect.redhat.com/seldonio/seldon-core-s2i-python3:latest: Error reading manifest latest in registry.connect.redhat.com/seldonio/seldon-core-s2i-python3
```

## Expected behaviour
```
Trying to pull registry.connect.redhat.com/seldonio/seldon-core-s2i-python3:latest...
Getting image source signatures...
```
## Environment
* OS: Ubuntu 20.04.2 LTS
* Cloud Provider: Red Hat OpenShift 4.7
* Kubernetes Cluster Version: v1.20.0+7d0a2b2 
* Deployed Seldon System Images: 1.7.0

**Comment by axsaucedo** [comment]
THanks for the heads up @jensaug - as discussed on slack for now there is a workaround whereby existing images built on top of the python s2i image such as the mock classifier can be used as base images instead. We will have a look at addressing this in the next few redhat releases.
