### ISSUE TITLE
How to override Seldon Core Operator default env variables while installing from OpenShift Operator Hub?

### ISSUE THREAD

**Issue by moodymuggle** [SeldonIO/seldon-core#3283]
Hi,

I want to override default istio values and similar env variables of the Seldon Core Operator on OpenShift. How should I do that?

On another note -I added my custom inference server with quay url to seldon-config cm & added quay pull secret to seldon-sa. Is that the recommended approach?

**Comment by cliveseldon** [comment]
You should be able to update the CSV in the openshift control panel.

Yes for customer inference servers that is the recommended approach: https://docs.seldon.io/projects/seldon-core/en/latest/servers/custom.html

**Comment by ranipm2705** [comment]
I had tried editing the live CSV earlier, but it keeps getting modified constantly and any modification's save action results in below error:
Operation cannot be fulfilled on clusterserviceversions.operators.coreos.com "seldon-operator.v1.7.0": the object has been modified; please apply your changes to the latest version and try again

P.S: I am on OCP 4.6.x, 

I dont see an

**Comment by cliveseldon** [comment]
Have your tried updating from admin console for cluster.

**Comment by ranipm2705** [comment]
Yes, I have cluster-admin rbac & am editing from Administrator console of OCP 4.6. 
Should I generate a new csv version? Is this something I should do as an user?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue with latest version
