### ISSUE TITLE
Add top level documentation on metrics servers in custom metrics section

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3292]
Currently we have an example that shows how to metrics servers to expose custom metriscs to prometheus through a scalable archtectural pattern that provides a separate optino to adding it to the custom python wrapper. However currently it is not documented, so we should add top level documentation in the metrics section, with a link to the examples provided.

**Comment by cliveseldon** [comment]
Will close can reopen if we think docs still lacking
