### ISSUE TITLE
x509: certificate relies on legacy Common Name field

### ISSUE THREAD

**Issue by edbighead** [SeldonIO/seldon-core#3293]
## Describe the bug

Getting the following error when using the self-signed certs created with `./operator/generate-keys.sh` script
```
Internal error occurred: failed calling webhook "v1alpha2.vseldondeployment.kb.io": Post "https://seldon-webhook-service.seldon-system.svc:443/validate-machinelearning-seldon-io-v1alpha2-seldondeployment?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Just to clarify. Are you using Kustomize to install the operator rather than the Helm chart as there is code in Helm to also do this.

**Comment by edbighead** [comment]
> Just to clarify. Are you using Kustomize to install the operator rather than the Helm chart as there is code in Helm to also do this.

yes, using Kustomize

**Comment by cliveseldon** [comment]
Closing as PR seen as not needed.
