### ISSUE TITLE
S2i build image with private pip repository

### ISSUE THREAD

**Issue by vincentarthur** [SeldonIO/seldon-core#330]
Currently for using S2i to build image for Seldon, it's going through Internet. However, in some cases, the network is only for intranet only which unable to reach Internet. So a new requirement would be - 
   S2i build image stage should be able to configure whether to use Local private repository for installing python libraries. (Both conda url and folders for .whl)

**Comment by vincentarthur** [comment]
@jklaise ,Thanks in advance.

**Comment by jklaise** [comment]
@vincentarthur I've created a pull request #332 which enables you to use local Python wheels to install your runtime dependencies. This solution requires to put the wheels into a "whl" directory where your component source code lives. I understand this is not ideal as you probably want to reuse the same wheels for several components, we have an open issue for this (#324) but presently it seems non-trivial to extend the wrapping process to look for dependencies outside the local directory.

**Comment by vincentarthur** [comment]
@jklaise Thanks for the PR. How about this ?

- s2i build . -v /whl/dir:/whl image-name
- (inside assemble) pip install --find-links /whl -r requirements.txt

**Comment by jklaise** [comment]
@vincentarthur thanks, that looks a lot cleaner. For some reason I couldn't make it work with the -v flag but it does work with the -i (inject directories) flag, so the syntax would be ```s2i build -i /whl/dir:/whl . builder_image target_image```, I think using the -i is preferable to -v as well as it doesn't leave the binaries hanging around after the build process finishes.

**Comment by jklaise** [comment]
@vincentarthur you can now use the ```0.5-SNAPSHOT``` s2i builder image to achieve the desired functionality, full syntax available [here](https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/python.md#local-python-dependencies). Closed by #332.
