### ISSUE TITLE
I deploy tensorflow model using tensorflow2.4.1 and occur error:CUDA error (3): initialization error.

### ISSUE THREAD

**Issue by hhhhhhogan** [SeldonIO/seldon-core#3314]
## Describe the bug
I deploy tensorflow model using tensorflow2.4.1 and occur error:CUDA error (3): initialization error.
How can I fix the error.I think it may be casued by  multi thread.But I do not know how to fix.

## Environment

centor

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by axsaucedo** [comment]
Can you provide more information and logs? This sounds similar to [this issue](https://github.com/SeldonIO/seldon-core/issues/2680) could you try the suggested solution there?

**Comment by hhhhhhogan** [comment]
> Can you provide more information and logs? This sounds similar to [this issue](https://github.com/SeldonIO/seldon-core/issues/2680) could you try the suggested solution there?

OK，Thanks。I had solved the issue after reading the issue you sent me.I do not rewrite the load() function and do not read the origin code carefully before.But After I change my code and debug,it sloved!Thank you !

**Comment by axsaucedo** [comment]
Great - closing as solved
