### ISSUE TITLE
Create "documentation by example" similar to Argo Workflows docs

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3331]
The argo workflows documentation has a page that provides a massive dump of a broad range of examples ranging from basic to advanced - this would be quite a useful addition for showcasing all the different configurations of seldon core. Currently the examples in the notebooks provide an end to end workflow that shows how to install, send requests, etc, but would still be useful to have a single page that contains a broad range of different examples. Here is the referenced page https://argoproj.github.io/argo-workflows/examples/

**Comment by cliveseldon** [comment]
Docs have been updated. Cab revisit with @edshee
