### ISSUE TITLE
Explore adding a default taint and selector for all seldon models deployed to enable for separate node groups used for models

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3349]
Explore allowing a configurable parameter in the installation helm chart that sets a baseline default for a node taint and node selector that can get added to all seldon models created. This would allow for all models to be allocated in a separate node group specifically for machine learning models. A similar approach to this has been done with the `defaultEnvSecretRefName`.

**Comment by cliveseldon** [comment]
will reinvestigate in v2
