### ISSUE TITLE
go mod fails because of invalid character in file name

### ISSUE THREAD

**Issue by smthpickboy** [SeldonIO/seldon-core#3354]
When I'm trying to compile using:
```
require github.com/seldonio/seldon-core v1.9.1
```
go mod complains:
```
	github.com/seldonio/seldon-core/operator/apis/machinelearning.seldon.io/v1: create zip: doc/source/images/adversarial-attack.png:Zone.Identifier: malformed file path "doc/source/images/adversarial-attack.png:Zone.Identifier": invalid char ':'
doc/source/images/anchors.jpg:Zone.Identifier: malformed file path "doc/source/images/anchors.jpg:Zone.Identifier": invalid char ':'
doc/source/images/kibana-custom-search.png:Zone.Identifier: malformed file path "doc/source/images/kibana-custom-search.png:Zone.Identifier": invalid char ':'
```

Please refer to: https://github.com/golang/go/issues/28001

Since there's actually no go.mod in the project root directory, the correct way should be using:
```
require github.com/seldonio/seldon-core/operator v1.9.0
```
but I get:
```
go: github.com/seldonio/seldon-core/operator@v1.9.1: reading github.com/seldonio/seldon-core/operator/operator/go.mod at revision operator/v1.9.1: unknown revision operator/v1.9.1
```
That's because the tag is supposed to be `operator/v1.9.1` for go.mod.

The only workaround seems to be not using tags, but delete the require statement in go.mod and let go mod generate pseudo-version.

Maybe we should add `operator/v1.9.1` tag?

**Comment by cliveseldon** [comment]
Sorry missed this. Yeah we should revisit. @axsaucedo @gsunner

**Comment by ivan-valkov** [comment]
We now have the correct tags for all releases of the operator after v1.0.0. I have tested it and it works fine. @smthpickboy can you try using `require github.com/seldonio/seldon-core/operator v1.9.0` again. Let me know if there are any issues. I am closing this issue for now.
