### ISSUE TITLE
Update Core Builder to use more recent version of Python

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3358]
Currently Core builder image uses python 3.6, which results in some inconsistencies when running tests (from local dev on 3.7) - the one that was identified is the python `subprocess` module `run` function not having the `capture_output` parameter in the CI.

**Comment by cliveseldon** [comment]
Also `AttributeError: module 'socket' has no attribute 'SO_REUSEPORT'` in older python
