### ISSUE TITLE
Potential problem in EpsilonGreedy.py?

### ISSUE THREAD

**Issue by sasvaritoni** [SeldonIO/seldon-core#336]
I created a MAB by using the Kubeflow template seldon-mab-v1alpha2.
It seems that the router is stuck at best branch 0, no matter what feedback I send in. The counters are not changing any time, constant 0's are printed:

```
10.233.75.41 - - [07/Dec/2018 13:51:22] "POST /send-feedback HTTP/1.1" 200 -
Routing
Current best branch: 0
Selected branch: 1

10.233.75.41 - - [07/Dec/2018 13:51:23] "POST /route HTTP/1.1" 200 -
Training
Prev success # [0, 0]
Prev tries # [0, 0]
Prev best branch: 0
New success # [0, 0]
New tries # [0, 0]
New best branch: 0

10.233.75.41 - - [07/Dec/2018 13:51:23] "POST /send-feedback HTTP/1.1" 200 -
Routing
Current best branch: 0
Selected branch: 1

10.233.75.41 - - [07/Dec/2018 13:51:23] "POST /route HTTP/1.1" 200 -
Training
Prev success # [0, 0]
Prev tries # [0, 0]
Prev best branch: 0
New success # [0, 0]
New tries # [0, 0]
New best branch: 0
```

This is the feedback sample I am sending in:
```

{'response': 
 {
	"meta": {
		"puid": "6dho003ic6p177pn2s3gv898vt",
		"tags": {
		},
		"routing": {
			"eg-router": 1
			
		}
	},
	"data": {
		"names": [
			"t:0",
			"t:1",
			"t:2"
		],
		"ndarray": [
			[
				"n02504013",
				"Indian_elephant",
				"0.8157868"
			],
			[
				"n01871265",
				"tusker",
				"0.11059379"
			],
			[
				"n02504458",
				"African_elephant",
				"0.071501344"
			]
		]
	}
},
'reward': '0.9'} 
```
 
Any hints? Anyone tested the MAB router before?

**Comment by cliveseldon** [comment]
Try
  * Sending your request as well. This is where the epsilonGreedy is presently getting the number of predictions.
 * Sending a binary reward (1 or 0)

**Comment by sasvaritoni** [comment]
Wow, sending the request as well did the trick indeed!
Actually I sent in a dummy request, because I did not want to send in the whole image data again.

In case of AB-test, I only sent the response and the reward, and that was enough just to have the feedback counters work with Prometheus, that's why I did not consider sending the request here either.
I think in some cases the request data may not be available anymore (or may be too big) to send in again with the feedback.

Anyway, it works now, thank you!

**Comment by sasvaritoni** [comment]
I just noticed that you were right with the 2nd hint as well, seems that only binary reward works.

Isn't it supposed to accept any real number between 0 and 1?
At least on the orchestrator service level real numbers are accepted both for AB-test and MAB.
Seems that the router itself can only interpret binary numbers.

**Comment by sasvaritoni** [comment]
Thank you for the help and explanation, this was really useful!
