### ISSUE TITLE
Deployment giving certificate expired or is not yet valid

### ISSUE THREAD

**Issue by sv711** [SeldonIO/seldon-core#3366]
On deploying new manifests, getting the following error:

`error: seldondeployments.machinelearning.seldon.io "reactivation-post-processor" could not be patched: Internal error occurred: failed calling webhook "v1.mseldondeployment.kb.io": Post https://seldon-webhook-service.seldon-system.svc:443/mutate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s: x509: certificate has expired or is not yet valid 
`
* Cloud Provider: GKE
* Kubernetes Cluster Version: v1.17.17-gke.4900
* Deployed Seldon System Images: 
![image](https://user-images.githubusercontent.com/72063890/124273973-4ff81800-db5e-11eb-8bf7-1164f35db279.png)

**Comment by cliveseldon** [comment]
How are you installing Seldon Core? Helm, GCP marketplace, Kustomize. Can you provide the command you use in full.

**Comment by sv711** [comment]
@cliveseldon , I have installed the seldon core using:
`helm install seldon-core seldon-core-operator --repo https://storage.googleapis.com/seldon-charts --set ambassador.enabled=true --set usageMetrics.enabled=true --namespace seldon-system`

helm version: 
`version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}`

**Comment by cliveseldon** [comment]
Is there some reason why you have 1.2.0 installed which is not the latest? Are you able to install the latest Seldon Core on a v1.18 cluster?
I can reproduce this on a v1.18 cluster with latest Seldon Core.

**Comment by edbighead** [comment]
Might be related to https://github.com/SeldonIO/seldon-core/pull/3294

**Comment by cliveseldon** [comment]
Please reopen if still an issue.

**Comment by spicoflorin** [comment]
Hi!

I solve this issue following the steps:

1. check the webhook certificate expiration issue command:` kubectl get secret seldon-webhook-server-cert -n seldon-system -o jsonpath='{.data.tls\.crt}' | base64 --decode | openssl x509 -text -noout| grep 'Not After'`
2. delete the expired certificate `kubectl delete secret seldon-webhook-server-cert -n seldon-system`
3. renew the certificate via command `helm upgrade seldon-core seldon-core-operator --version 1.17.1 --repo https://storage.googleapis.com/seldon-charts  -n seldon-system`

Before step 3, check your helm chart version for the seldon-core-operattor chart.

I hope it helps.
Florin
