### ISSUE TITLE
Can't change REST timeout

### ISSUE THREAD

**Issue by naor2013** [SeldonIO/seldon-core#3368]
## Describe the bug

I try to set the 'seldon.io/rest-timeout: "100000"'.
It returns 504 timeout after 30 seconds.
The seldondeployment pod continues the prediction even after the timeout.
When we try to set that parameter to be lower, it works differently. It didn't return 504, but an empty answer instead and continued the calculation.
So it seems like the timeout works but with an upper limit of 30 seconds.

Is there any way to change it?

Note: We use Seldon Core 1.4 but I didn't see any change it later versions to fix it.

**Comment by cliveseldon** [comment]
Are you running against a service mesh such as istio? There may be timeouts at that level as well you need to adapt.

**Comment by cliveseldon** [comment]
Can you also try this notebook setting the delay as appropriate to test how to works in your k8s cluster: https://docs.seldon.io/projects/seldon-core/en/latest/examples/timeouts.html

**Comment by naor2013** [comment]
I don't use istio and I used the annotation in the notebook example. Below 30 seconds worked as expected, above 30 seconds just had a timeout of 30 seconds

**Comment by cliveseldon** [comment]
You are using Ambassador?

**Comment by naor2013** [comment]
No, I'm using OpenShift's routes instead of ingress

**Comment by cliveseldon** [comment]
Can you try this updated notebook in https://github.com/SeldonIO/seldon-core/pull/3416
It updates the test to run with a 30sec delay for the "model" and a 40 second timeout. This works for me with istio in a Kind cluster.

I imagine your issue may be due to Openshift settings but would need to find if there are any defaults that are different in Openshift service mesh etc.

Which version of Openshift are you using? So if not istio you are just adding Routes manually?

**Comment by cliveseldon** [comment]
See https://docs.openshift.com/container-platform/3.9/architecture/networking/routes.html
where it says

```
ROUTER_DEFAULT_CLIENT_TIMEOUT | 30s | Length of time that a client has to acknowledge or send data.
```

**Comment by cliveseldon** [comment]
Given the above can we close this issue?

**Comment by naor2013** [comment]
Wow thank you! Didn't know about it and I definitely tried googling it.
I'll check what settings do I have on the Openshift cluster and close the issue tomorrow if that is indeed the issue.
Thank you again! 😄
