### ISSUE TITLE
Lacking requirements in Kubeflow example

### ISSUE THREAD

**Issue by sramirez** [SeldonIO/seldon-core#3372]
## Describe the bug

https://github.com/SeldonIO/seldon-core/tree/master/examples/kubeflow example is really great, but there are some minor changes required to make it work:

1. s2i package and kfp client need to be installed.
2. Pandas is not present in:

https://github.com/SeldonIO/seldon-core/blob/master/examples/kubeflow/pipeline/pipeline_steps/data_downloader/requirements.txt

If you think this change is appropriate, I may create a simple PR.

Just follow the example in: https://github.com/SeldonIO/seldon-core/blob/master/examples/kubeflow/pipeline/pipeline_steps/data_downloader/requirements.txt

## Expected behaviour 

A clean installation of the e2e pipeline.

## Environment

Ubuntu 20.04.2 LTS
KF local installation on microk8s: https://www.kubeflow.org/docs/distributions/microk8s/kubeflow-on-microk8s/ (lite version)
Using seldon-core integrated in KF

**Comment by cliveseldon** [comment]
Sorry - missed this. Please add a PR and link to this issue.

**Comment by westford14** [comment]
hey all -- just picking this up quickly and have opened a PR here: https://github.com/SeldonIO/seldon-core/pull/3654 let me know what everyone thinks
