### ISSUE TITLE
click dependencies could not be resolved

### ISSUE THREAD

**Issue by chinaliwenbo** [SeldonIO/seldon-core#3373]
## Describe the bug

Could not find a version that matches click<8.0,<8.1,>=5.1,>=8.0.0a1
seldon-core==1.9.0
  - click [required: >=8.0.0a1,<8.1, installed: 8.0.1]
    - importlib-metadata [required: Any, installed: 4.6.1]
      - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
      - zipp [required: >=0.5, installed: 3.5.0]
  - cryptography [required: ==3.4, installed: 3.4]
    - cffi [required: >=1.12, installed: 1.14.5]
      - pycparser [required: Any, installed: 2.20]
    - setuptools-rust [required: >=0.11.4, installed: 0.12.1]
      - semantic-version [required: >=2.6.0, installed: 2.8.5]
      - setuptools [required: >=46.1, installed: 52.0.0]
      - toml [required: >=0.9.0, installed: 0.10.2]
  - Flask [required: <2.0.0, installed: 1.1.2]
    - click [required: >=5.1, installed: 8.0.1]
      - importlib-metadata [required: Any, installed: 4.6.1]
        - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
        - zipp [required: >=0.5, installed: 3.5.0]
    - itsdangerous [required: >=0.24, installed: 2.0.1]
    - Jinja2 [required: >=2.10.1, installed: 3.0.1]
      - MarkupSafe [required: >=2.0, installed: 2.0.1]
    - Werkzeug [required: >=0.15, installed: 2.0.1]
      - dataclasses [required: Any, installed: 0.8]
  - Flask-cors [required: <4.0.0, installed: 3.0.10]
    - Flask [required: >=0.9, installed: 1.1.2]
      - click [required: >=5.1, installed: 8.0.1]
        - importlib-metadata [required: Any, installed: 4.6.1]
          - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
          - zipp [required: >=0.5, installed: 3.5.0]
      - itsdangerous [required: >=0.24, installed: 2.0.1]
      - Jinja2 [required: >=2.10.1, installed: 3.0.1]
        - MarkupSafe [required: >=2.0, installed: 2.0.1]
      - Werkzeug [required: >=0.15, installed: 2.0.1]
        - dataclasses [required: Any, installed: 0.8]
    - Six [required: Any, installed: 1.16.0]
  - Flask-OpenTracing [required: >=1.1.0,<1.2.0, installed: 1.1.0]
    - Flask [required: Any, installed: 1.1.2]
      - click [required: >=5.1, installed: 8.0.1]
        - importlib-metadata [required: Any, installed: 4.6.1]
          - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
          - zipp [required: >=0.5, installed: 3.5.0]
      - itsdangerous [required: >=0.24, installed: 2.0.1]
      - Jinja2 [required: >=2.10.1, installed: 3.0.1]
        - MarkupSafe [required: >=2.0, installed: 2.0.1]
      - Werkzeug [required: >=0.15, installed: 2.0.1]
        - dataclasses [required: Any, installed: 0.8]
    - opentracing [required: >=2.0,<3, installed: 2.4.0]
  - flatbuffers [required: <2.0.0, installed: 1.12]
  - grpcio [required: <2.0.0, installed: 1.38.1]
    - six [required: >=1.5.2, installed: 1.16.0]
  - grpcio-opentracing [required: >=1.1.4,<1.2.0, installed: 1.1.4]
    - grpcio [required: >=1.1.3,<2.0, installed: 1.38.1]
      - six [required: >=1.5.2, installed: 1.16.0]
    - opentracing [required: >=1.2.2, installed: 2.4.0]
    - six [required: >=1.10, installed: 1.16.0]
  - grpcio-reflection [required: <1.35.0, installed: 1.34.1]
    - grpcio [required: >=1.34.1, installed: 1.38.1]
      - six [required: >=1.5.2, installed: 1.16.0]
    - protobuf [required: >=3.6.0, installed: 3.17.3]
      - six [required: >=1.9, installed: 1.16.0]
  - gunicorn [required: >=19.9.0,<20.2.0, installed: 20.1.0]
    - setuptools [required: >=3.0, installed: 52.0.0]
  - jaeger-client [required: >=4.1.0,<4.5.0, installed: 4.4.0]
    - opentracing [required: >=2.1,<3.0, installed: 2.4.0]
    - threadloop [required: >=1,<2, installed: 1.0.2]
      - tornado [required: Any, installed: 6.1]
    - thrift [required: Any, installed: 0.13.0]
      - six [required: >=1.7.2, installed: 1.16.0]
    - tornado [required: >=4.3, installed: 6.1]
  - jsonschema [required: <4.0.0, installed: 3.2.0]
    - attrs [required: >=17.4.0, installed: 21.2.0]
    - importlib-metadata [required: Any, installed: 4.6.1]
      - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
      - zipp [required: >=0.5, installed: 3.5.0]
    - pyrsistent [required: >=0.14.0, installed: 0.18.0]
    - setuptools [required: Any, installed: 52.0.0]
    - six [required: >=1.11.0, installed: 1.16.0]
  - numpy [required: <2.0.0, installed: 1.19.5]
  - opentracing [required: >=2.2.0,<2.5.0, installed: 2.4.0]
  - prometheus-client [required: >=0.7.1,<0.9.0, installed: 0.8.0]
  - protobuf [required: <4.0.0, installed: 3.17.3]
    - six [required: >=1.9, installed: 1.16.0]
  - PyYAML [required: >=5.4,<5.5, installed: 5.4.1]
  - requests [required: <3.0.0, installed: 2.25.1]
    - certifi [required: >=2017.4.17, installed: 2021.5.30]
    - chardet [required: >=3.0.2,<5, installed: 4.0.0]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.25.9]
  - setuptools [required: >=41.0.0, installed: 52.0.0]
  - urllib3 [required: ==1.25.9, installed: 1.25.9]

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Can you provide more information on your use case and how to reproduce this. Please reopen if so.
