### ISSUE TITLE
Ability to use nodeSelector to specify specific nodepools.

### ISSUE THREAD

**Issue by sudosoup** [SeldonIO/seldon-core#3382]
Is there an ability to use nodeSelector? I'd like to issue seldon-core-manager to a custom node pool, but currently seem unable to.

**Comment by cliveseldon** [comment]
For the manager itself, for the helm charts not at present if you mean https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml

This would be easy to add yourself and we could consider this for a PR. We would need to update the kustomize at https://github.com/SeldonIO/seldon-core/blob/master/operator/config/manager/manager.yaml which is used to derive the helm charts.

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue
