### ISSUE TITLE
S2I builder images should have pinned Python dependencies

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#340]
Currently S2I builder images use "pip install seldon-core" or the local equivalent to install the seldon-core Python package and its dependencies, we should specify to use the requirements.txt for pinned package versions.

**Comment by JoelH96** [comment]
#1160

**Comment by RafalSkolasinski** [comment]
@JoelH96 @jklaise I think this issue can be already closed or there is something still missing?

**Comment by jklaise** [comment]
I don't quite remember the context of this, but I think it may have been to do with having pinned versions of packages that `seldon-core` itself depends on which the merged PR does not address, however I don't recall why I wanted this now.

On a related note, now that 1.0 is out, the `seldon-core` version should be updated in the `requirements.txt`.

**Comment by RafalSkolasinski** [comment]
Seldon-core itself dependencies are listed in the setup.py under [install_requires](https://github.com/SeldonIO/seldon-core/blob/00e50db53ed4752f430c8e97672f999cefcd3933/python/setup.py#L27).

Good point about the seldon-core version in requirements.txt. Though, I am not sure where that is actually used as latest image from docker hub seems to use 1.0 installed from sources:
```bash
satriani ➜  ~ docker run --rm -it seldonio/seldon-core-s2i-python37:0.15 bash
root@11dab7628ff1:/microservice# pip freeze | grep seldon
# Editable install with no version control (seldon-core==1.0.0)
```

**Comment by RafalSkolasinski** [comment]
Looking at the initial scope and changes introduced in #1160 I believe this one is closed. 
We should open a new issue if there are any unpinned dependencies somewhere else.

Closing.
