### ISSUE TITLE
request validation via metadata schema

### ISSUE THREAD

**Issue by RadionBik** [SeldonIO/seldon-core#3402]
Hi! following the discussion in Slack: https://seldondev.slack.com/archives/C8Y9A8G0Y/p1625234947022700

It would be great to have the validation functionality (possibly toggle-able) for the input and output messages basing on the metadata scheme, if one is specified. 

This function could be used in custom clients, and even in auto-generated ones, initiated with a request to the metadata endpoint, for instance. 

This could simplify maintenance and debugging of seldon clients, and to assert the metadata is always up-to-date.

**Comment by cliveseldon** [comment]
I think this is a great idea. Just need to decide how best to include it. Ties in with our https://github.com/SeldonIO/ml-prediction-schema work

**Comment by cliveseldon** [comment]
Could you have a look at [MLServer](https://github.com/SeldonIO/mlserver) to see if our new V2 python model server could facilitate this:

**Comment by RadionBik** [comment]
Hi! It is difficult to tell, because I don't understand whether MLserver is a part of SeldonCore that provides pre-packaged servers functionality or a separate project. If it is a part, why the request schemas differ? I looked at examples https://github.com/SeldonIO/MLServer/blob/master/docs/examples/mms/README.md and https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/metadata.html#ndarray-input-output

Also, I couldn't find a high level description of various Seldon projects and their relation to each other in one place, I think it will help many newbies like me to understand the entire ecosystem better.

**Comment by cliveseldon** [comment]
Thanks @RadionBik 
Yes, we are planning a docs update to provide more clarity on the projects and how they relate. @edshee 
As for MLServer - it is our V2 Python Inference Server for python models (sklearn, xgboost, custom, MLFlow etc) and in future also other languages. It can be used with Core when you choose the kfserving v2 protocol.
