### ISSUE TITLE
conda-forge integration

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#341]
Releasing the Python seldon-core package on conda-forge is a separate process which may require changing the conda recipe to fetch source from PyPI (once published there) or from our source code @kalefranz

**Comment by RafalSkolasinski** [comment]
If this is still relevant shall we pin it to 1.1 or 1.2?

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by RafalSkolasinski** [comment]
Added `triage` so we can review on next planning session if this is still needed.

**Comment by cliveseldon** [comment]
Close unless more demand
