### ISSUE TITLE
Support class method import in `seldon-core-microservice` using `package.module.SeldonClass:static_method`

### ISSUE THREAD

**Issue by JBosom** [SeldonIO/seldon-core#3436]
This issue asks for a new feature in `seldon-core-microservice` command line. Currently, it is possible to call this command line with, for example :

```bash
seldon-core-microservice package.module.SeldonClass --service-type MODEL
```

In order to automatize the generation of some classes answering specific use cases we have, we would like to be able to encapsulate a `SeldonClass` thanks to a decorator. However, the needed encapsulation changes the behaviour of the class which cannot be used as it is during the `seldon-core-microservice` call.

Our use case is about decorators but the same can be simply achieved with a class as in the following example :

```python
class SeldonClass:
    @staticmethod
    def static_method(*args, **kwargs):
        class _EncapsulatedModel:
            def predict(self, X, names, meta=None):
                return X
        return _EncapsulatedModel(*args, **kwargs)
```

This new use case can be supported with minimal code changes at [this line in the main](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L375) of `seldon_core/microservice.py`. What I suggest is the use of the separator `:`, therefore the call to `seldon-core-microservice` for the previous class would look like :

```bash
seldon-core-microservice package.module.SeldonClass:static_method --service-type MODEL
```

From my understanding of the structure of the project, I think the changes to support such an option are limited to the Python part of the project and should not affect other parts. If that is correct, the changes are only the following code ([code from this line in the main](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L367)) and the associated test functions :

```python
    # I copy the first lines of the if to ease the reading but they won't change
    parts = args.interface_name.rsplit(".", 1)
    if len(parts) == 1:
        logger.info("Importing %s", args.interface_name)
        interface_file = importlib.import_module(args.interface_name)
        user_class = getattr(interface_file, args.interface_name)
    else:
        logger.info("Importing submodule %s", parts)
        interface_file = importlib.import_module(parts[0])
        
        # The suggested changes
        subparts = parts[1].split(":", 1)
        if len(subparts) == 1:
            user_class = getattr(interface_file, parts[1])  # Original code
        else:
            logger.info("Importing method %s in submodule %s", (subparts[0],
                                                                subparts[1]))
            intermediate_class = getattr(interface_file, subparts[0])
            user_class = getattr(intermediate_class, subparts[1])
```

If this new feature is accepted, I can open a pull request with the code and tests according to the contributing best practices defined for this (awesome) project.

Again, these changes are minimal and should not impact other parts. Also, this feature is motivated by more advanced use cases implying decorators. I presented here only a minimal working use case (that we can use for tests) based on a class with a static method. Thank you for your time.

**Comment by cliveseldon** [comment]
This sounds like a reasonble small change. If you could create a PR.

Thanks!

**Comment by JBosom** [comment]
Thanks a lot for the approval. I'll open a PR as soon as I have some time next week.

**Comment by cliveseldon** [comment]
Closing - please reopen if still an issue or PR available.
