### ISSUE TITLE
what is the best way for receiving/sending data fast?

### ISSUE THREAD

**Issue by dedoogong** [SeldonIO/seldon-core#3449]
hello~! I have used seldon for deploying out custom models. 
Recently I found a serious problem in speed(TPS) between server/client.
The main bottle neck is base64 encoding/decoding(Only those take 90% of all time! and super slow!)
I'd like to ask you what is the clever way to receive/send data faster than base64 encoding/decoding.

Thank you!

**Comment by cliveseldon** [comment]
Can you provide further details of your model and SeldonDeployment use case?
For binary data grpc may be faster. Are you using the `binData` field at present with REST?

**Comment by cliveseldon** [comment]
Please reopen if you have further updates.
