### ISSUE TITLE
[executor] Move to the new Go Protobuf API

### ISSUE THREAD

**Issue by ivan-valkov** [SeldonIO/seldon-core#3452]
Earlier this year the v2 protobuf api for Go was released - https://blog.golang.org/protobuf-apiv2

We use the v1 api (github.com/golang/protobuf) in several places in the executor. Given it is being deprecated we should look into migrating over to the v2 api (google.golang.org/protobuf) at some point.

**Comment by cliveseldon** [comment]
Updated in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html)
