### ISSUE TITLE
Mlflow getting downgraded 

### ISSUE THREAD

**Issue by raghulkrishna** [SeldonIO/seldon-core#3454]
Mlflow getting downgraded with mlflow server when trying to serve random forest regressor built using sklearn logged in mlflow 

i have attached the following screenshots here If needed i can provide more details Thank you

<img width="1440" alt="Screenshot 2021-08-04 at 7 38 58 AM" src="https://user-images.githubusercontent.com/62284209/128130047-64e8cec0-b4cf-42c0-998c-0a6dcb3cdeb9.png">
<img width="823" alt="Screenshot 2021-08-04 at 7 32 14 AM" src="https://user-images.githubusercontent.com/62284209/128130056-8dc4de86-c049-43aa-bdfa-e69bb254b8a0.png">
<img width="1012" alt="Screenshot 2021-08-04 at 7 29 59 AM" src="https://user-images.githubusercontent.com/62284209/128130062-9af8bf5d-a3fa-45c6-87b5-2f2f4fa63405.png">
 (image :seldonio/mlflowserver:1.9.0)

**Comment by cliveseldon** [comment]
We are moving to handle MLFlow via out MLServer project can you see if your use case can follow this example: https://docs.seldon.io/projects/seldon-core/en/latest/examples/mlflow_v2_protocol_end_to_end.html

This way supports the V2 protocols and MLFlow protocol.
