### ISSUE TITLE
When is a Sdep exposed via Ambassador ready to serve Inference Requests 

### ISSUE THREAD

**Issue by ramanNarasimhan77** [SeldonIO/seldon-core#3474]
Hello,

This issue is based on this slack discussion: https://seldondev.slack.com/archives/C8Y9A8G0Y/p1628321849073000 

![image](https://user-images.githubusercontent.com/52691361/128672467-f86f63c2-9f17-4b86-8a32-f2c555db6e3e.png)

We are building automated tests, so having the ability to know when the Seldon Deployment is ready to serve requests, would help in differentiating between actual invoke errors vs errors thrown due to Seldon deployment/Ambassador not being ready. Right now we are just retrying the invoke 5 times blindly until it succeeds, and mark it as failed if it fails even after all the retries

Thanks
Raman

**Comment by cliveseldon** [comment]
We have added status conditions in 1.11.0. Does this help you. If not it could be that Ambassador is taking some time to update its Envoy configuration which is out of our control.

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
