### ISSUE TITLE
Ensure containerSpec override works for svcOrch correctly to allow for attributes like tolerations, etc

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3480]
Currently if a containerSpec is provided to override the service orchestrator, ie. a container with the name "seldon-container-engine", the replace happens without autmenting current values, and hence everything has to be provided in order to work. The solution would be that the containerSpec only overrides the fields provided in the existing container, such that things like tolerations, or even image overrides can be specified. This is going to be approached instead of #2755.

**Comment by marcoramosh** [comment]
what is the status of this issue?

**Comment by cliveseldon** [comment]
Further work has not been started on this issue yet. A useful addition would be to clarify your use case for us @marcoramosh that is affected by this issue.

**Comment by cliveseldon** [comment]
Please try [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html) as we have ServerConfig's you can customize
