### ISSUE TITLE
Add documentation in UPGRADING page that outlines new explainer URI model param limitation

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3499]
Since version 1.10, we added changes in the explainer code which ensure that the model name in the v1 tfserving protocol is actually used, as opposed to before where it wasn't, so we should add documentation in case anyone was not using it.

**Comment by RafalSkolasinski** [comment]
Summarizing the discussion we had on Slack. 

The model-name is currently optional in the prediction API of Tensorflow protocol (in Seldon) as docoumented [here](https://docs.seldon.io/projects/seldon-core/en/latest/graph/protocols.html#rest-and-grpc-tensorflow-protocol):
```
a non-standard Seldon extension is available to call predict on the graph as a whole: /v1/models/:predict.
```

https://github.com/SeldonIO/seldon-core/pull/3501 brings back this non-standard extension for the explainer API

**Comment by axsaucedo** [comment]
@RafalSkolasinski are we OK to close this one?

**Comment by RafalSkolasinski** [comment]
I believe so

**Comment by axsaucedo** [comment]
OK cool, closing
