### ISSUE TITLE
Add where to download model from modeluri

### ISSUE THREAD

**Issue by donggrame** [SeldonIO/seldon-core#3502]
It is pretty tedious to specify all the init container configs only to change the directory where modeluri to be downloded.

specifically for triton, model must be in a single directory. But if a model is structured like this,

```
s3://model_registry
ㄴmodel1/
    ㄴ config.pbtxt
    ㄴ 1/
```

with modeluri s3://model_registry/model1, init container make a structure like this

```
/mnt/models
ㄴ confug.pbtxt
ㄴ 1/
```

which causes model load error. Of course, we can change the triton argument like ‘model-repository=/mnt’, but this will loss specific model name ‘model1’

we have to make them nested like

```
s3://model_registry/model1/model1
s3://model_registry/model2/model2
```

to use `modeluri: s3://model_registry/model1` without tedious init container configs

why dont we just add a field to specify where to download its contents in modeluri?

**Comment by cliveseldon** [comment]
Have you tried using the latest rclone init : https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html
This is the default from 1.8 - which version of Core are you using?

**Comment by cliveseldon** [comment]
Closing - please reopen if Rclone solution not satisfactory.
