### ISSUE TITLE
Add automated check for licenses in CI job

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3537]
Currently we have a set of CI jobs that extract all the licenses from the dependencies in the codebase, however we currently don't have an automated check that validates that non-permissive OSS libraries aren't added. We should add an extra check that does a validation of libraries that should not be included as dependencies without previous approval, including the following:

    GNU GPL (version 1, version 2, version 3, or any future versions): GPL-licensed libraries cannot be linked to from non-GPL projects.
    GNU AGPLv3: AGPL-licensed libraries cannot be linked to from non-GPL projects.
    Open Software License (OSL): is a copyleft license. In addition, the FSF recommend against its use.
    GNU Lesser General Public License (GNU LGPL) (version 2, version 3): GPL constraints regarding modification and redistribution under the same license are not required of projects using an LGPL library, only upon modification of the LGPL-licensed library itself.

**Comment by cliveseldon** [comment]
Will close in favour of larger CI overhaul if needed.
