### ISSUE TITLE
Does Seldon work similar to Node Red

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3544]
Hi @cliveseldon @RafalSkolasinski 

Does seldon allow to connect two seldon deployments in gke as a pipeline instead of having a seldon inference graph connecting two components in a single deployment.

**Comment by cliveseldon** [comment]
You can call out to another Seldon Deployment but you would need to get the SVC URI from the status field

**Comment by divyadilip91** [comment]
@cliveseldon Thank you for your reply. Did you mean SVC uri as the cluster ip obtained after executing kubectl get svc command?

**Comment by cliveseldon** [comment]
No I mean the SeldonDeployment Status has a url field which could be used to find it and call it.

**Comment by cliveseldon** [comment]
Did this fix your issue @divyadilip91 
Note - we are also looking in updated V2 APIs to make it easier for models to be chained together.

**Comment by divyadilip91** [comment]
Hi @cliveseldon 
Apologies for the delayed feedback. I found the url under the seldon deployment status field. But my doubt is whether the first deployment can make an internal call to the second deployment. If possible how is it possible.
