### ISSUE TITLE
Python language wrapper doesn't work with PyTorch load_state_dict

### ISSUE THREAD

**Issue by lihan** [SeldonIO/seldon-core#3547]
## Describe the bug

Pytorch `model.load_state_dict(state)` will stuck when wrapped using Python language wrapper

## To reproduce

1. Trying to load_state_dict in a module
2. Run `seldon-core-microservice module.ClassName --service-type MODEL`

## Expected behaviour

load_state_dict should load the state into Pytorch model

## Environment

Any

## Walkaround

* Do `torch.set_num_threads(1)` at the file header, this works, but disables multi-threading
* Or, add `--debug` flag to `seldon-core-microservice`

## Ideas

* Allow initialising pytorch model in the master thread before gunicorn fork child process. In pytorch, there is `model.share_memory()`

## Related issue

* https://github.com/benoitc/gunicorn/issues/2608
* https://stackoverflow.com/questions/59144482/running-pytorch-multiprocessing-in-a-docker-container-with-gunicorn-worker-manag

**Comment by axsaucedo** [comment]
This could be related to the gunicorn worker, so you could choose to run it with single worker such that it only runs with flask, that means that it wouldn't run as multiprocessing. Would you be able to try that?

**Comment by cliveseldon** [comment]
Did you load your model in a `load` method? e.g. https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
