### ISSUE TITLE
Istio enabled Seldon core: Support for URI re-write customization in VirtualService created by the controller.

### ISSUE THREAD

**Issue by kpriyank20** [SeldonIO/seldon-core#3550]
In case of ambassador, the deployed model endpoints can be easily customized with URI path re-write option with the below annotation -
**_seldon.io/ambassador-config_**

Example SeldonDeployment: 
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  creationTimestamp: '2021-07-06T13:15:24Z'
	................
	................
	........
spec:
  annotations:
     .......
    project-name: test_project
    seldon.io/ambassador-config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: seldon_testmodel_default_rest_mapping1
      prefix: /xyz/test_project/testmodel/
      rewrite: /
      service: testmodel-default.svc:9000
      timeout_ms: 300000
      ---
	............
	
However, if Istio ingress is enabled in seldon core operator, the related virtual service is auto generated by the controller and I could not find any documentation on seldon.io, on how we can customize the model endpoints in the virtual service to achieve similar flexibility as offered in case of ambassador.

Kindly share the relevant documentation if this is possible ? If not, is there any road map to extend customized URI re-write feature to istio virtual service creation as well ?

**Comment by cliveseldon** [comment]
No you are right we have limited customization functionality at present: https://docs.seldon.io/projects/seldon-core/en/latest/ingress/istio.html#istio-configuration-annotation-reference

Can you describe your use case?

**Comment by kpriyank20** [comment]
The use case we have is - we are using seldon core operator to manage ML models deployment on RedHat OpenShift cluster. While doing so we are using Istio ingress to expose the MLOps endpoints to external systems, so requirement here is to have some custom URI prefix path instead of the default prefix, in the auto generated Istio virtual service as shown below - 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
.................
................
    - match:
        - uri:
            **_prefix: /seldon/<namespace_name>/<deployment_name>/_**
      rewrite:
        uri: /
................

**Comment by cliveseldon** [comment]
If we had a single vanilla SVC endpoint for all models then we could allow users to add any istio resources as needed as the spec for these would be of a predictable nature. This is something we are investigating for v2 APIs in core. This would allow you to create any customized istio resources as needed when deploying a model.
