### ISSUE TITLE
hello I do not know the composition of json？Can you tell me something about it ?

### ISSUE THREAD

**Issue by hhhhhhogan** [SeldonIO/seldon-core#3556]
I see the  json input like '{ "data": { "ndarray": [[1,2,3,4]] } }'.Can I remove the keyword like data or ndarray?I don’t understand what these keywords do？Thank your  answer！

**Comment by cliveseldon** [comment]
The Seldon protocol allows various formats to send prediction payloads as shown here: https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/external-prediction.html

ndarray is a popular one. So in answer no you can't remove that structure in the current Seldon V1 API.

**Comment by hhhhhhogan** [comment]
Ok,I know,Thanks!
















At 2021-08-31 17:24:27, "cliveseldon" ***@***.***> wrote:

The Seldon protocol allows various formats to send prediction payloads as shown here: https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/external-prediction.html

ndarray is a popular one. So in answer no you can't remove that structure in the current Seldon V1 API.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
