### ISSUE TITLE
Support Alibi Detect as Prepackaged Server

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#3557]
Currently MLServer's Alibi Detect Server (introduced in https://github.com/SeldonIO/MLServer/pull/271) can be a prepackaged server in itself as it has a similar workflow to the normal models. This means that it could use a lot of the similar workflows involved in the alibi-detect-server in Seldon Core to build a base that could import models for outlier detectors, drift detectors and adv detectors from Alibi Detect.

**Comment by cliveseldon** [comment]
fixed in v2
