### ISSUE TITLE
FastAPI integration with Seldon

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3575]
Hi @cliveseldon 
I would like to know the list of API frameworks that have been integrated with Seldon. Is it just flask or any other framework too?
Will there be an integration with Fast API framework since its found to be much faster than a Flask framework.
Awaiting your response

**Comment by cliveseldon** [comment]
Our v1 python wrapper uses Flask for Debug mode and Gunicorn for production. Our v2 python server is [MLServer](https://github.com/SeldonIO/mlserver) which uses FastAPI based framework.

**Comment by divyadilip91** [comment]
Thankyou @cliveseldon
