### ISSUE TITLE
Should allow user customize LeaderElectionID

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-core#3576]
Right now LeaderElectionID is hardcoded, this will cause issue if we run side-by-side seldon-core operator, 
maybe should allow user to customize this ?
https://github.com/SeldonIO/seldon-core/blob/1f910d4a4bf95abf8ea26862f72c242ce2d12398/operator/main.go#L160

**Comment by cliveseldon** [comment]
Yes this makes sense.

**Comment by anggao** [comment]
Great, I will try to put a PR for it.
