### ISSUE TITLE
Error in accessing Grafana Dashboard

### ISSUE THREAD

**Issue by 123dhruv123** [SeldonIO/seldon-core#3581]
I am able to access my Grafana dashboard connected to seldon core using seldon-core-analytics on localhost in my Ubuntu server. But I am not able to see it on my windows machine even though I have set port 3000 in inbound and outbound rules on AWS. But it's not working.

**Comment by NhatAnh** [comment]
Hi,
I also have problem with grafana. I install and forward port like the document said https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html

But when access localhost:3000, it asks for username and password

**Comment by 123dhruv123** [comment]
You can put username-admin password-admin and try

**Comment by NhatAnh** [comment]
Hey thanks, but I did try admin/admin and it did not work.
I also add `grafana_prom_admin_password` when install but it also doesn't seem to change thing
```
helm install seldon-core-analytics seldon-core-analytics \
    --repo https://storage.googleapis.com/seldon-charts \
    --set grafana_prom_admin_password=admin \
    --namespace seldon-system
```

**Comment by leeeanh** [comment]
@NhatAnh  You can also try username:admin, password:password which mentions in https://docs.seldon.io/projects/seldon-core/en/latest/charts/seldon-core-analytics.html?highlight=Grafana#values

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
