### ISSUE TITLE
How seldon core analytics is working for model metrics monitoring ???

### ISSUE THREAD

**Issue by nitesh31mishra** [SeldonIO/seldon-core#3592]
Can someone explain how Seldon core analytics is working with Seldon core, Prometheus, and grafana ??? Like how can I get the model metrics for the model served with Seldon core...

**Comment by cliveseldon** [comment]
We have an example monitoring setup you can try https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html
However you may want to utilize this as a base for your production setup
