### ISSUE TITLE
disable grpc server or rest server  

### ISSUE THREAD

**Issue by TaylorHere** [SeldonIO/seldon-core#3597]
In our scenario， we only want to start a rest server,  our model will use gpu mem, and our gpu can only load one model, if rest server and grpc server all start, which will crash

can we add an option at https://github.com/SeldonIO/seldon-core/blob/0699f0be0f1322586865410a100b91d01d7795c8/python/seldon_core/microservice.py#L50 to determine which server to start?

**Comment by cliveseldon** [comment]
We provide an example monitoring integration you can try: https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html
However, you may want to take this and incorporate into your own production setup.

**Comment by cliveseldon** [comment]
This will not be an issue with MLServer https://github.com/SeldonIO/mlserver
Longer term we will be advancing the use of this server for python based models in Core. You can see the mlserver docs for custom models https://github.com/SeldonIO/MLServer/blob/master/docs/examples/custom/README.md
The docs for clear use in Core are not yet created.

**Comment by TaylorHere** [comment]
looks like mlserver didn't support onnxruntime

**Comment by TaylorHere** [comment]
we still want an option to determine which server to start, only one server will used in production, no reason to run another one, and which also execute `load_model`

**Comment by archwolf118** [comment]
I agree with TaylorHere, I found the GPU memory can be wasted with 2 type service. So  How I can modify this problem?@TaylorHere @cliveseldon

**Comment by TaylorHere** [comment]
@archwolf118 I rewrite the code at https://github.com/SeldonIO/seldon-core/blob/ce9a2842a95a3212044542f78aa299c26fe1264d/python/seldon_core/microservice.py#L55

**Comment by cliveseldon** [comment]
@TaylorHere  Have you tried [MLServer](https://github.com/SeldonIO/mlserver) for your use case as not sure this is an easy fix for python wrapper as we do assume REST and gRPC are wired up for all servers.

**Comment by cliveseldon** [comment]
Closing please reopen if still an issue

**Comment by cliveseldon** [comment]
reopening for further investigation

**Comment by axsaucedo** [comment]
Closing in favour of #4031
