### ISSUE TITLE
urllib <1.26.5 security vulnerability fix

### ISSUE THREAD

**Issue by vojavocni** [SeldonIO/seldon-core#3603]
## Describe the bug
seldon-core seems to require urllib3==1.25.9 (https://github.com/SeldonIO/seldon-core/blob/4853a497561a55933a598a876542b2e08d46c7c9/python/setup.py#L47). 

However, all versions <1.26.5 have a security vulnerability of high severity as described here: https://github.com/advisories/GHSA-q2q7-5pp4-w6pg.

## To reproduce
/

## Expected behaviour
/

## Environment
/

## Model Details 
/

**Comment by axsaucedo** [comment]
Thank you for the update @vojavocni - we will have a look at resolving this

**Comment by cliveseldon** [comment]
Assuming fixed in latest. Please reopen if CVEs still occur.
