### ISSUE TITLE
Are you interested in becoming a listed KEDA end-user?

### ISSUE THREAD

**Issue by tomkerkhove** [SeldonIO/seldon-core#3612]
Are you interested in becoming a listed KEDA end-user?

**Comment by cliveseldon** [comment]
@tomkerkhove Yes sounds good. do we need to do anything?

**Comment by tomkerkhove** [comment]
That's great, thanks a ton!

All that would be required would be to open a PR similar to https://github.com/kedacore/keda-docs/pull/437 - Thank you!

**Comment by cliveseldon** [comment]
Added https://github.com/kedacore/keda-docs/pull/541

**Comment by cliveseldon** [comment]
Thanks @tomkerkhove  https://keda.sh/community/

**Comment by tomkerkhove** [comment]
Thank YOU!
