### ISSUE TITLE
Support Prometheus Monitor CRD in deployment controller.

### ISSUE THREAD

**Issue by swartz-k** [SeldonIO/seldon-core#3615]
In my env, we use Prometheus Operator. To use PodMonitor、ServiceMonitor I have to write an external crd after create deployment crd, could controller supporet it if possible? I would like to make a pr if this is allowed.

**Comment by cliveseldon** [comment]
What would you see the core steps in the PR? Can you not setup PodMonitors and ServiceMonitors as needed to match what we create?

**Comment by swartz-k** [comment]
> What would you see the core steps in the PR? Can you not setup PodMonitors and ServiceMonitors as needed to match what we create?

Here, It will auto add annotation.  https://github.com/SeldonIO/seldon-core/blob/228b41765fc57fda26f0b5d00526ff423d06206d/operator/controllers/seldondeployment_engine.go#L495

If possible, in this step, we want to be able to choose to create a PodMonitor CRD or just annotation.

**Comment by cliveseldon** [comment]
On the whole Prometheus configuration we see as outside the scope of the project. We will look at making clearer how scraping rules can be added to your own Prometheus setup.
