### ISSUE TITLE
Request logger doesn't log request to elastic when meta field is transmitted

### ISSUE THREAD

**Issue by RadionBik** [SeldonIO/seldon-core#3620]
## Describe the bug
Request logger doesn't log request to elastic when meta field is a non-empty dictionary. 

## To reproduce
I tested this behaviour with strData and jsonData request formats. Let's consider the following request body:
`{"strData": "some data", "meta": {}}`

The request and response fields in elastic log will be present and it is expected.
But when I add arbitrary information to meta (which is something I could use for further processing), for example:
`{"strData": "some data", "meta": {"key1": "value1"}}`

the log in elastic will contain only the response part. Which is why I suspect Request Logger in this bug. 

## Expected behaviour
I expect the logs to contain request-response parts along with meta field AS IS.

## Environment

* Deployed Seldon Version: v1.9.0

**Comment by Atharex** [comment]
Perhaps something I came across today is also a related issue? I'm using "binData" in my requests, without any meta information and I also get only responses logged into elasticsearch. 

The log of the request logger also complains about some missing env. var and a metadata service.

```
[2021-09-29 14:37:49 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-09-29 14:37:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-09-29 14:37:49 +0000] [1] [INFO] Using worker: gthread
[2021-09-29 14:37:49 +0000] [12] [INFO] Booting worker with pid: 12
[2021-09-29 14:37:49 +0000] [13] [INFO] Booting worker with pid: 13
[2021-09-29 14:37:49 +0000] [14] [INFO] Booting worker with pid: 14
starting logger
Connected to Elasticsearch
No DEPLOY_API_HOST - will not look up metadata from Deploy
starting logger
Connected to Elasticsearch
No DEPLOY_API_HOST - will not look up metadata from Deploy
starting logger
Connected to Elasticsearch
No DEPLOY_API_HOST - will not look up metadata from Deploy

metadata service not configured
upserted to doc inference-log-model-seldon-test-deployment/_doc/386d5889-cf3b-4a8d-9f72-26acd14f8951 adding response
```

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue with latest version 1.12
