### ISSUE TITLE
Features to setup kafka properties for input, output topic

### ISSUE THREAD

**Issue by nbowon** [SeldonIO/seldon-core#3621]
Hi I'm trying to use seldon for long running algorithm (usually it takes more than 2 minutes). 

I think kafka is best option for my use case.
and I also need to apply security credential for kafka. 
So I want to make it by SASL using JAAS
please refer this https://docs.confluent.io/platform/current/kafka/authentication_sasl/index.html

So, properties are like this
- sasl.jaas.config
- security.protocol
- sasl.mechanism

Could you help to support to input this properties? 
or Can you guys provide some way to input whatever name of properties?

**Comment by openrory** [comment]
Hey guys, is there any way we can bump this up on your backlog? We are planning on using Seldon for our project, but we need SASL SCRAM-SHA-265 support to connect to Kafka

**Comment by cliveseldon** [comment]
Thanks for the update. Can you provide some more details on the Kafka installation you are using?, e.g. Strimzi, AWS Managed Kafka, Confluent etc?

**Comment by openrory** [comment]
Thanks @cliveseldon for responding so quickly! Currently we're using Managed Kafka on AWS (by Aiven), but we will be moving to Confluent (Cloud) Kafka soon. For testing purposes we use Strimzi on an EKS cluster. So we're basically using all of them ;-) But the Confluent Kafka would be the most important one.
Let me know if you need more information, happy to jump on a call with you if needed.

**Comment by agrski** [comment]
I suspect this will come down to the features exposed by the Go Kafka library we use, which in turn is a wrapper around `librdkafka`.  I believe there are relevant security settings already exposed by the Go library, so it's a case of testing to get these right.

The changes in #3813 give a good idea of how this should work.  I'm happy to help review if someone would like to put in an open-source contribution!

**Comment by cliveseldon** [comment]
Please try in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html)
