### ISSUE TITLE
seldon multi-armed bandits mab_thompson_sampling issue 

### ISSUE THREAD

**Issue by subhabratabanerjee** [SeldonIO/seldon-core#3622]
using https://hub.docker.com/r/seldonio/mab_thompson_sampling/tags?page=1&ordering=last_updated , but route not working it’s returning same request as response . can some one check docker please ,it’s 3 years old one,

https://hub.docker.com/r/seldonio/mab_epsilon_greedy/tags?page=1&ordering=last_updated (epsilon_greedy) is working fine

**Comment by cliveseldon** [comment]
we support [Iter8](https://docs.seldon.io/projects/seldon-core/en/latest/rollouts/abtests.html?highlight=iter8) for MAB experiments and will look further into MABs in new V2 APIs.
