### ISSUE TITLE
Found potential CVEs - CVE analysis for Seldon 1.11.0

### ISSUE THREAD

**Issue by vikulaggarwal** [SeldonIO/seldon-core#3643]
We are on our way to upgrade to Seldon 1.11.0 from 1.2.X. As part of the upgrade effort, we've done CVE analysis for Seldon Go Operator and Seldon Go Executor modules. We have found some potential CVEs. An Excel sheet with the information is attached.

[Potential CVEs 1_11_0.xlsx](https://github.com/SeldonIO/seldon-core/files/7290555/Potential.CVEs.1_11_0.xlsx)

Please advise on which of these packages are runtime packages. We would need to replace these packages for higher versions where the CVE has been addressed.

if possible, please advise the versions that can be used for replacing such packages so that the functionality is not affected.

## To reproduce
1. The analysis was done manually by searching the packages on https://cve.mitre.org/cve/search_cve_list.html

## Expected behaviour
Runtime packages which are potentially impacted by a CVE are replaceable with a higher version where the CVE has been addressed.

## Environment
We have to use Seldon Deployments on linux environments running Kubernetes 1.20.X.

**Comment by cliveseldon** [comment]
Closing. Please reopen if still CVEs for 1.12
