### ISSUE TITLE
Seldon Deployment not working on an air gapped onprem server

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3649]
Hi @cliveseldon @axsaucedo 
I have setup seldon core 1.1.0 on an air gapped onprem server using helm by downloading the seldon core helm charts and seldon docker images and pushing them into the local server docker registry. The installation was set up fine. But an error was thrown when I tried to apply a deployment yaml
**Error from server (InternalError): error when creating "onprem-deployment.yaml": Internal error occurred: failed calling webhook "v1.mseldondeployment.kb.io": Post "https://seldon-webhook-service.seldon-system.svc:443/mutate-machinelearning-seldon-io-v1-seldondeployment?timeout=30s": context deadline exceeded**

From this we see that the deployment is trying to make a https call which is not possible on an air gapped server. When we enabled firewall for the server, the deployment worked fine. How to avoid this. Is there any yaml where we can configure the https webhook endpoint being called to our local server ip and port number
We need to deploy everything on an air gapped server which cannot be changed. Kindly help me with this issue since I am working on an urgent setup and I am stuck at this point and need to clear this soon.

#1374

**Comment by divyadilip91** [comment]
@cliveseldon Thankyou for your quick response. The kubernetes is also setup on the air gapped on prem server on which seldon core has been installed. So is it possible for the k8s api-server to make a https call to the webhook server?I am quite curious. Please correct me if I am wrong.

**Comment by cliveseldon** [comment]
The k8s-api server calling the webhook via https is the standard way. I suggest you look into your on-prem k8s install to check the networking. How did you install k8s?

**Comment by divyadilip91** [comment]
Hi @cliveseldon I just now figured that closing the internet connection is not causing the prob, but the port is causing the issue. 
In our onprem server we have allowed only few ports(443,and so on) to be opened for internal use without internet connection(intranet). Deploying the yaml under this setup is throwing the above mentioned error. But when we opened all ports for internal use without internet connection, deploying the yaml does not create any issue. So the issue is caused because a particular port is closed from our side.
So can you please guide me whether I am missing any port that seldon is using by which this issue is caused.
It would be helpful if you can provide a list of ports that need to be opened for internal use for seldon deployments to work.
Thanks

**Comment by divyadilip91** [comment]
@cliveseldon @axsaucedo  Thank you for your quick response. Actually in the air gapped server, only specific ports are open for internal communication. So is there any such specific port that seldon uses for routing internally that is required to be kept open? Or is it some kubernetes port ?

**Comment by cliveseldon** [comment]
Please reopen if still an issue.
