### ISSUE TITLE
Json payload size increases when I use json.dumps

### ISSUE THREAD

**Issue by sathiez** [SeldonIO/seldon-core#365]
My Image array (numpy array) size is 921728 bytes.But when I use json.dumps it becomes 3473742 bytes. Due to increase in payload size, my request takes more time to get processed. How could we reduce response time?

**code:**
**data = {"data":{"ndarray":imgarray.tolist()}}
data=json.dumps(data, separators=(',',': '))
r = requests.post(url, data={'json':data})**

**Comment by sathiez** [comment]
Can you tell me How to use gRPC ? any tutorial available?

**Comment by cliveseldon** [comment]
For Seldon you can look at

 * [Example python code](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/seldon_utils.py)
 * [Commands to build python code from proto buffers](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/Makefile)

In general I suggest you look at [grpc docs](https://grpc.io/)

We will add reference python code to our PyPI seldon-core module soon.

**Comment by sathiez** [comment]
Hi,
When I run seldon model image I get **"GRPC Microservice Running on port 5000"**.
How can I send request to it?

**Comment by sathiez** [comment]
Hi, 
My code is,

**datadef = prediction_pb2.DefaultData(tensor = prediction_pb2.Tensor(shape = shape,values =arr))
request = prediction_pb2.SeldonMessage(data = datadef)
deploymentname = "grpc-grpc"
namespace = "aimodels"
channel = grpc.insecure_channel("192.168.1.246:80")
stub = prediction_pb2_grpc.SeldonStub(channel)
metadata = [('seldon',deploymentname)]

response = stub.Predict(request=request,metadata=metadata)**

and I get the following error message,

_status = StatusCode.CANCELLED
details = "Received http2 header with status: 404"
debug_error_string = "{"created":"@1546785969.550709886","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":121,"grpc_message":"Received http2 header with status: 404","grpc_status":1,"value":"404"}"_

Is that mean connection is established and server side fault. can you help me?

**Comment by cliveseldon** [comment]
404 would suggest your deployment name is incorrect.
I assume you are using Ambassador. I would suggest checking the [Ambassador diagnostics UI](https://www.getambassador.io/reference/diagnostics/)  to check the endpoint has been created.
You could also check the logs of the pods running in your deployment to see if there are any errors.

**Comment by sathiez** [comment]
Thank you, I changed the deployment name now I am getting the following error,	


_status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "{"created":"@1546925188.754944146","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"","grpc_status":2}"_

**Comment by cliveseldon** [comment]
Hard to say from that. You should

 * check the status of the seldon deployment to ensure its been deployed successfully, see ```kubectl get sdep -o json```
 * Check the logs of the seldon-engine and your model components in the running pod.

**Comment by sathiez** [comment]
Hi,
I checked everything. All logs are showing fine. How can I troubleshoot this? can you please help me?

**Comment by cliveseldon** [comment]
Its either an issue in your client or the server. So there must be an error in 1 of the two. You need to track each step of the request and show the logs from the components.

**Comment by sathiez** [comment]
Hi,
Even the ambassador log shows **POST /seldon.protos.Seldon/Predict HTTP/2" 200 - 55 0 2 2 "-" "grpc-python/1.17.1 grpc-c/7.0.0** . I am using seldon in kubeflow. Is there any other troubleshoot method available ?

**Comment by cliveseldon** [comment]
I would add some logging to your model to check the predict call reaches it.

**Comment by sathiez** [comment]
I already added logging to the model, call didn't reach to model.

**Comment by sathiez** [comment]
Hi,
I get this error when I try to install seldon using kubeflow,
**ERROR handle object: patching object from cluster: merging object with existing state: ClusterRoleBinding.rbac.authorization.k8s.io "seldon" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"seldon-crd"}: cannot change roleRef**

**Comment by cliveseldon** [comment]
Is this using ksonnet? How did you install Seldon? Was there an existing Seldon running?

**Comment by sathiez** [comment]
yes by using ksonnet. But now I installed seldon, still I get the same error "grpc status = StatusCode.UNKNOWN"

**Comment by cliveseldon** [comment]
I assume this is from the engine logs? You need to check the error stack trace.

Are you running a gRPC or REST model? 
Does this match your definition in the SeldonDeployment json resource definition?
What endpoint is it trying to call and is this correct?

**Comment by sathiez** [comment]
https://github.com/SeldonIO/seldon-core/issues/365#issuecomment-452299865 
getting the same error while installing seldon with ksonnet.

**Comment by cliveseldon** [comment]
Did you install it over a previous installation? That error looks like its trying to recreate or reassign a RBAC role.

**Comment by sathiez** [comment]
Yes, but I removed all my previous installation. Now I am trying a fresh installation still issue persist

**Comment by sathiez** [comment]
My model deployment jsonnet file,

**local env = std.extVar("__ksonnet/environments");
local params = std.extVar("__ksonnet/params").components.myout;


local k = import "k.libsonnet";
local serve = import "kubeflow/seldon/serve-simple.libsonnet";

// updatedParams uses the environment namespace if
// the namespace parameter is not explicitly set
local updatedParams = params {
  namespace: if params.namespace == "null" then env.namespace else params.namespace,
};

local name = params.name;
local image = params.image;
local namespace = updatedParams.namespace;
local replicas = params.replicas;
local endpoint = params.endpoint;
local pvcName = params.pvcName;

local serveComponents = [
  serve.parts(namespace).serve(name, image, replicas, endpoint, pvcName),
];

local pvcComponent = [
  serve.parts(namespace).createPVC(pvcName),
];

if pvcName != "null" && pvcName != "" then
  k.core.v1.list.new(serveComponents + pvcComponent)
else
  k.core.v1.list.new(serveComponents)**

**Comment by cliveseldon** [comment]
You can look at:

 * https://github.com/SeldonIO/seldon-core/blob/master/docs/annotations.md
 * https://github.com/SeldonIO/seldon-core/blob/master/notebooks/max_grpc_msg_size.ipynb

**Comment by sathiez** [comment]
If I send a tensor.proto from client side, I am getting empty messages in server side. How to get the actual values?

**Comment by sathiez** [comment]
Do I need to do change any settings?

**Comment by cliveseldon** [comment]
No the above should work via the latest python wrapper. Can you check you have wrapped your model with the latest s2i wrapper image.

**Comment by sathiez** [comment]
oh. tensor.proto won't work in **"seldonio/core-python-wrapper:0.7"** ???

**Comment by jklaise** [comment]
@sathiez, the core-python-wrapper has been deprecated, you should use the s2i Python wrapper: https://github.com/SeldonIO/seldon-core/blob/master/docs/wrappers/python.md#step-3---build-your-image

**Comment by sathiez** [comment]
Thank You,

I tried with **"seldonio/seldon-core-s2i-python3:0.4"** and I get the following error,


 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.6/site-packages/seldon_core/model_microservice.py", line 169, in Predict
    predictions, class_names, default_data_type)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 215, in array_to_grpc_datadef
    ndarray=array_to_list_value(array)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 104, in array_to_list_value
    array_to_list_value(sub_array, sub_lv)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 100, in array_to_list_value
    lv.extend(array)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/well_known_types.py", line 799, in extend
    self.append(value)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/well_known_types.py", line 795, in append
    _SetStructValue(self.values.add(), value)
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/well_known_types.py", line 714, in _SetStructValue
    raise ValueError('Unexpected type')
ValueError: Unexpected type

**Comment by sathiez** [comment]
Now I get the following error,

 **Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.6/site-packages/seldon_core/model_microservice.py", line 169, in Predict
    predictions, class_names, default_data_type)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 215, in array_to_grpc_datadef
    ndarray=array_to_list_value(array)
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 102, in array_to_list_value
    for sub_array in array:
TypeError: iteration over a 0-d array** 


My code is,
#where arr.shape = (480, 640, 3)
arr = tf.make_tensor_proto(arr)
datadef =  prediction_pb2.DefaultData(tftensor = arr)
request = prediction_pb2.SeldonMessage(data = datadef)

How can I solve it?

**Comment by cliveseldon** [comment]
This issue has various threads. Please open more specific issues/bugs with more specific focus.
