### ISSUE TITLE
Move sklearnserver server to use Poetry

### ISSUE THREAD

**Issue by seldondev** [SeldonIO/seldon-core#3655]

**Comment by cliveseldon** [comment]
Closing for now until proven required.

**Comment by RafalSkolasinski** [comment]
uncontrolled deps change that causes failure like that should not happen so this proves the move poetry there required

**Comment by RafalSkolasinski** [comment]
the above mentioned problem is fixed on master through https://github.com/SeldonIO/seldon-core/pull/3948
