### ISSUE TITLE
Batch processor cast integers to floats in payloads

### ISSUE THREAD

**Issue by seldondev** [SeldonIO/seldon-core#3681]
When input file to batch processor contains explicit integer values these are casted to floats.This is limitation of `seldon_client` identified to happen when an `ndarray` data go through this line https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/utils.py#L325 ,the value in the data will be changed to float automatically.

**Comment by RafalSkolasinski** [comment]
https://github.com/SeldonIO/seldon-core/pull/3718 will respect its when using "raw" inputs
