### ISSUE TITLE
Propagate content-encoding header to the logging endpoint

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#3690]
When upgrading Tritonserver to 21.08-py in https://github.com/SeldonIO/seldon-core/pull/3589 we had to include propagation of `Content-Encoding` header back to api clients such that they are aware about `gzip` compressed payloads. 

It turns out that we will need to modify `executor` to also forward this payload to the default logging endpoint (e.g. knative broker) so that request logger microservices know how to decode it successfully.

**Comment by RafalSkolasinski** [comment]
To properly send cloud event with gzip encoded content we should first update [cloudevents/go-sdk](https://github.com/cloudevents/sdk-go/issues/735). 

However, for the full setup to work properly we need to first guarantee that consumers of these events (#3747, #3748) can understand payloads marked as `Content-Encoding: gzip` properly. 

The temporary fix to the issue is being added by https://github.com/SeldonIO/seldon-core/pull/3746/ which for time being will decompress gzip encoded payloads before sending them as cloud events.

**Comment by RafalSkolasinski** [comment]
Re-opening as https://github.com/SeldonIO/seldon-core/pull/3746 closed https://github.com/SeldonIO/seldon-core/issues/3749 instead of this one as a temporary solution

**Comment by cliveseldon** [comment]
Not planned.Closing

**Comment by RafalSkolasinski** [comment]
Note for context, the solution introduced by https://github.com/SeldonIO/seldon-core/issues/3749 and merged in https://github.com/SeldonIO/seldon-core/pull/3746 solves the issue by forwarding decoded events. As above, there is no plan to forward gzip-compressed events.
