### ISSUE TITLE
Currently engine related values cannot be ommited from the values.yaml while deploying seldon

### ISSUE THREAD

**Issue by narasago** [SeldonIO/seldon-core#3691]
## Describe the bug
In the seldon-core-operator helm chart, the engine related values are still mandatory to be provided. As the engine is deprecated since seldon 1.1, it would be better to provide values "engine.enabled" and based on that the values can be used in the seldon manager deployment.

## Expected behaviour
Addition of "engine.enabled" flag and based on the same, the values needs to be considered when created seldon manager deployment.

## Environment
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

## Model Details 
NA

**Comment by RafalSkolasinski** [comment]
Hi @narasago,

I am not sure I understand the problem. The `engine.enabled` is part of default values. In your custom helm values file `values.yaml` (or whatever name you give it) you do not need to provide it. This value usually should only contain "flags" that you want to overwrite.

**Comment by RafalSkolasinski** [comment]
Actually, I do not see any `engine.enabled` flag in there https://github.com/SeldonIO/seldon-core/blob/fe2660c61ab3cb378164191a471a4578a8e4b518/helm-charts/seldon-core-operator/values.yaml#L179-L198

**Comment by RafalSkolasinski** [comment]
Closing. When providing custom values to helm installation one does not need to provide all helm values, only the overwrites one. Therefore engine related values can be safely skipped. 

Removal of engine section from helm values can be considered.
