### ISSUE TITLE
seldon ambassador inference issue

### ISSUE THREAD

**Issue by subhabratabanerjee** [SeldonIO/seldon-core#3696]
I am following https://docs.seldon.io/projects/seldon-core/en/latest/examples/seldon_core_setup.html
process follow ..

1. I am using ambassador for ingress gateway
2. I have created separate namespace for Seldon - seldon-system like doc,
As ambassador was other namespace with same name  , I created ‘ambassador-seldon’ inside seldon-system 

(with unchange ‘ambassador' error was---  Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "ambassador" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "seldon-system": current value is "ambassador") 

3. I have checked all pods are running state, I deployed sample model all are running state,   but inference api is not working . 
Can you please help me .

Additional Questions: 
1. Can I use another ambassador present in other namespace, if yes what changes required.
2. As ambassador present same where core installed  other name , like ambassador-seldon (same name not accepting ) ,how  to use it
3. Without port fwd I need to use.

:~# kubectl get po -n seldon-system
NAME                                                 READY   STATUS    RESTARTS   AGE
ambassador-seldon-79898c9d9f-bmqjr                   1/1     Running   0          12h
ambassador-seldon-79898c9d9f-dkpdg                   1/1     Running   0          12h
ambassador-seldon-79898c9d9f-hzcb6                   1/1     Running   0          12h
ambassador-seldon-agent-6869cb9b97-qc6qj             1/1     Running   0          12h
seldon-controller-manager-8457b8b5c7-g99wh           1/1     Running   0          12h
seldon-model-example-0-classifier-5b6bd6b9fc-zstnw   2/2     Running   0          12h

kubectl get svc --namespace seldon-system ambassador-seldon -o jsonpath='{.status.loadBalancer.ingress[0].ip}';echo
10.xx.231.zz

curl -s -d '{"data": {"ndarray":[[1.0, 2.0, 5.0]]}}'  -X POST http://10.xx.231.zz/seldon/seldon-system/seldon-model/api/v1.0/predictions -H "Content-Type: application/json" -v
*   Trying 10.xx.231.zz...
* TCP_NODELAY set
* Connected to 10.xx.231.zz (10.xx.231.zz) port 80 (#0)
> POST /seldon/seldon-system/seldon-model/api/v1.0/predictions HTTP/1.1
> Host: 10.xx.231.zz
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 39
>
* upload completely sent off: 39 out of 39 bytes
< HTTP/1.1 301 Moved Permanently
< location: https://10.xx.231.zz/seldon/seldon-system/seldon-model/api/v1.0/predictions
< date: Fri, 22 Oct 2021 08:54:07 GMT
< server: envoy
< connection: close
< content-length: 0
<
* Closing connection 0

kubectl logs ambassador-seldon-79898c9d9f-bmqjr -n seldon-system
….

ACCESS [2021-10-22T08:48:04.791Z] "POST /seldon/seldon-system/seldon-model/api/v1.0/predictions HTTP/1.1" 301 - 0 0 1 - "10.zzz.86.aaa” "curl/7.58.0" "1ecac54f-50b5-4785-b0cf-66c3355df5c9" "10.xx.231.zz" "-"

…

kubectl logs seldon-model-example-0-classifier-5b6bd6b9fc-zstnw -n seldon-system -c classifier
…
…
 * Debug mode: off
2021-10-21 17:04:54,420 - werkzeug:_log:122 - INFO:   * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)

kubectl logs seldon-model-example-0-classifier-5b6bd6b9fc-zstnw -n seldon-system -c seldon-container-engine
{"level":"dpanic","ts":1634835900.223747,"logger":"entrypoint","msg":"odd number of arguments passed as key-value pairs for logging","ignored key":1,"stacktrace":"go.uber.org/automaxprocs/maxprocs.(*config).log\n\t/go/pkg/mod/go.uber.org/automaxprocs@v1.4.0/maxprocs/maxprocs.go:47\ngo.uber.org/automaxprocs/maxprocs.Set\n\t/go/pkg/mod/go.uber.org/automaxprocs@v1.4.0/maxprocs/maxprocs.go:123\nmain.main\n\t/workspace/cmd/executor/main.go:266\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
{"level":"info","ts":1634835900.2237105,"logger":"entrypoint","msg":"maxprocs: Updating GOMAXPROCS=%v: using minimum allowed GOMAXPROCS"}
{"level":"info","ts":1634835900.2243607,"logger":"entrypoint","msg":"Hostname unset will use localhost"}
{"level":"info","ts":1634835900.228554,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1634835900.2285955,"logger":"entrypoint","msg":"Starting","worker":2}
{"level":"info","ts":1634835900.2286036,"logger":"entrypoint","msg":"Starting","worker":3}
{"level":"info","ts":1634835900.2286074,"logger":"entrypoint","msg":"Starting","worker":4}
{"level":"info","ts":1634835900.228611,"logger":"entrypoint","msg":"Starting","worker":5}
{"level":"info","ts":1634835900.2297442,"logger":"entrypoint","msg":"Running http server ","port":8000}
{"level":"info","ts":1634835900.229774,"logger":"entrypoint","msg":"Creating non-TLS listener","port":8000}
{"level":"info","ts":1634835900.229978,"logger":"entrypoint","msg":"Running grpc server ","port":5001}
{"level":"info","ts":1634835900.2299862,"logger":"entrypoint","msg":"Creating non-TLS listener","port":5001}
{"level":"info","ts":1634835900.230025,"logger":"entrypoint","msg":"Setting max message size ","size":2147483647}
{"level":"info","ts":1634835900.2314453,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}

kubectl get seldondeployment -n seldon-system seldon-model -o yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  creationTimestamp: "2021-10-21T17:03:42Z"
  generation: 1
  name: seldon-model
  namespace: seldon-system
  resourceVersion: "1331134"
  uid: 00cbf2be-7c3c-42d3-927a-8e73e409a683
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: example
    replicas: 1
status:
  address:
    url: http://seldon-model-example.seldon-system.svc.cluster.local:8000/api/v1.0/predictions
  conditions:
  - lastTransitionTime: "2021-10-21T17:05:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: DeploymentsReady
  - lastTransitionTime: "2021-10-21T17:03:42Z"
    reason: No HPAs defined
    status: "True"
    type: HpasReady
  - lastTransitionTime: "2021-10-21T17:03:42Z"
    reason: No KEDA resources defined
    status: "True"
    type: KedaReady
  - lastTransitionTime: "2021-10-21T17:03:42Z"
    reason: No PDBs defined
    status: "True"
    type: PdbsReady
  - lastTransitionTime: "2021-10-21T17:05:22Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-10-21T17:05:22Z"
    reason: All services created
    status: "True"
    type: ServicesReady
  - lastTransitionTime: "2021-10-21T17:05:22Z"
    reason: No VirtualServices defined
    status: "True"
    type: istioVirtualServicesReady
  deploymentStatus:
    seldon-model-example-0-classifier:
      availableReplicas: 1
      replicas: 1
  replicas: 1
  state: Available

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
