### ISSUE TITLE
Allow for Annotations and Labels to be injected into helm chart templates

### ISSUE THREAD

**Issue by mwm5945** [SeldonIO/seldon-core#3699]
It would be great if we could inject labels and/or annotations into some of the templates in the helm chart. this would be particularly helpful for the CRD which is quite large, and ArgoCD doesn't like the size of the metadata (particularly `last-applied-configuration`). We could inject an argo sync annotation to help avoid that issue.

**Comment by cliveseldon** [comment]
Seems reasonable can we discuss a PR

**Comment by mwm5945** [comment]
@cliveseldon i've opened the above PR, but i've only added annotations to the CRD and the Deployment templates, as those are really the only places i can think of them being useful. I can also add a `global` annotation spec, and add them to each of the templates if you think thats a good idea. The PR is still a draft until what annotations we'd like to be added are finalized, then i'll udpate documentation, etc :)
