### ISSUE TITLE
Enhancement suggestion for a complex inference graph use case

### ISSUE THREAD

**Issue by gambitvk** [SeldonIO/seldon-core#3722]
Hi Guys,

I have got a use case that I already confirm on Slack that is not currently supported in Seldon, so just opening a ticket here as a future enhancement idea.

so here is what i wanted to do:

1. Model1 outputs a list of strings
2. For each string in the output of Model1 I want it to pass it to a Model2
3. Model2 takes a single value as input and a single value as output
4. Final output will be a list of pairs from the output of Model1 and Models2

eg.  Model1 output : [a, b , c ,d ]
a -> Model2 -> 1
b-> Model2 -> 2 .......
final output = [(a,1), (b,2), (c,3), (d,4)) ]

Also the number of outputs from Model1  can vary. We have 1 prpject where the output is always going to be less than 25... and another the output list could have thousands strings. ... so being able to (auto)scale individual steps in the graph will also be a key in solving our use case above.

cheers

**Comment by cliveseldon** [comment]
Thanks we will take this into account for V2 Inference Graph. Hopefully we can provide some details soon so you can comment.
