### ISSUE TITLE
Enable WhiteBox explainer v2 (e.g. IntegratedGradients)

### ISSUE THREAD

**Issue by seldondev** [SeldonIO/seldon-core#3723]
In the current design of SC we have the assumption that a model has one `ModelUri` however in the case of white box explainers we can have upto 2 artifacts (the explainer artifact and the underlying inference model artifact) to load.

I am not sure if there is an easy way to fully support this use case, some alternatives are:

follow explainer server v1patternof assuming that we can only load the inference model) and we always create the explainer on the fly

assume that `ModelUri` is a directory that would contain both the explainer and the model artifacts.

**Comment by cliveseldon** [comment]
Please test in v2
