### ISSUE TITLE
Seldon controller name is hardcoded and does not allow deployments with different names

### ISSUE THREAD

**Issue by DomFleischmann** [SeldonIO/seldon-core#3733]
## Describe the bug
When deploying the seldon controller manager with a different name than `seldon-controller-manager`, the deployment fails due to this name being hardcoded [here](https://github.com/SeldonIO/seldon-core/blob/master/operator/constants/constants.go#L44).

This is an issue for operators that want to offer a customizable experience where you would like to deploy seldon with different names. An example for an operator like this is our [seldon-core-operator](https://github.com/canonical/seldon-core-operator) used in Canonicals MLOps solution.

## To reproduce with out operator
```bash 
# Ubuntu 20.04 machine
sudo snap install microk8s --classic --channel=1.21/stable
sudo snap install juju --classic
sudo usermod -a -G microk8s ubuntu
sudo chown -f -R ubuntu ~/.kube
newgrp microk8s
microk8s enable storage dns
microk8s status --wait-ready
juju bootstrap microk8s 
juju add-model seldon
juju deploy seldon-core
```
After some time, checking with `juju status` the deployment will fail with a container error.
When reading the logs of the deployed pod the following error appears:
```bash
$ microk8s kubectl -n seldon logs pod/seldon-core-57778474cf-b7vw2
{"level":"info","ts":1636625946.6306317,"logger":"setup","msg":"Intializing operator"}
{"level":"error","ts":1636625946.7374682,"logger":"setup","msg":"unable to initialise operator","error":"deployments.apps \"seldon-controller-manager\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/workspace/main.go:149\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"
```

## Expected behaviour
The pod name should be configurable through some environment variable or something else, instead of having it hardcoded to `seldon-controller-manager`.

**Comment by cliveseldon** [comment]
Please try our latest release [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html)
