### ISSUE TITLE
Ensure integration tests always runs parallel and sequential tests

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3760]
Currently the integration tests stop after running the parallel tests if any of them fails - this was initially done to save time and avoid running the rest of the tests. Given there has been a few flaky tests in the build it was raised that ideally all tests are always run every time even if the parallel tests fail.

**Comment by sakoush** [comment]
This is done already [link](https://github.com/SeldonIO/seldon-core/blob/6fc7f9b3f661b12d9f5732f9e046fa29e73309dc/testing/scripts/kind_test_all.sh#L188-L222)
