### ISSUE TITLE
Deploy explainer after inference model has been deployed successfully

### ISSUE THREAD

**Issue by sakoush** [SeldonIO/seldon-core#3764]
Based on a recent change to create `svc` as soon as possible with a sdep, the explainer deployment will attempt a dummy inference request to the inference model, this will fail as long as the inference model is not yet up and running.

Therefore initially the explainer deployment will go into a couple of crashloop , eventually succeeding. 

Perhaps we want to deploy the inference model first then deploy the explainer?

**Comment by cliveseldon** [comment]
I think we can leave this for now given priorities. Can reopen if there is customer pushback and fix for V2 APIs
