### ISSUE TITLE
Custom metrics timer implementation

### ISSUE THREAD

**Issue by razf** [SeldonIO/seldon-core#3773]
Hi,

I have a question about the implementation of the custom timer metric.
The code that exposes the internal histogram preforms `np.cumsum` before creating the prometheus object (python/seldon_core/metrics.py, `_expose_histogram`) , and the resulting prometheus histogram metric is a cumsum histogram instead of a regular one, as I would have expected to have if I implemented the metric collection on my own using prometheus-client.

Is this a bug or intended behavior? 
If it is indeed intended behavior, what's the logic behind diverging from the prometheus implementation?

**Comment by cliveseldon** [comment]
Hi - sorry for missing this. Can you provide further links to the code parts you are referring to and suggest fixes?

**Comment by razf** [comment]
Yes. The line in question is https://github.com/SeldonIO/seldon-core/blob/64825dea70c1e89f3da8290781e0431df6a9876f/python/seldon_core/metrics.py#L226

I was wondering why there's np.cumsum on the values. I could do a PR with a suggested fix (removing it, and possibly adding configuration for the timer buckets) for review if it's not intended behavior.

**Comment by cliveseldon** [comment]
Yes it you could propose a PR that would be great. @RafalSkolasinski did the work on that line so will loop him in and assign the issue for his response.

**Comment by RafalSkolasinski** [comment]
Timer is a legacy name, histogram would be more appropriate. These are exposed as Prometheus' [Histogram](https://prometheus.io/docs/concepts/metric_types/#histogram) type (as well as Summary). According to documentation these are cumulative histograms. 

If you compare custom metrics exposed from python servers with metrics exposed automatically via executor, you will see that executor also exposes cumulative histograms.

**Comment by RafalSkolasinski** [comment]
Closing as this works as intended. @razf please provide references that would indicate this would need to behave differently
