### ISSUE TITLE
seldon-core-microservice: error: unrecognized arguments: test REST --service-type MODEL --persistence 0

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#3775]
Hi @cliveseldon @RafalSkolasinski 
## Describe the bug
Receiving the following error
**seldon-core-microservice: error: unrecognized arguments: Test REST --service-type MODEL --persistence 0**
I have seldon core 1.1.0 installed on gke and I deploy a docker image that was build by wrapping seldon using the CMD exec seldon-core-microservice command. I have installed seldon-core 1.1.0 py package during the docker build.
When I try to test this deployment in gke, it throws the above error. I even tried running the docker image from my local and it threw the same error. This is the first time I have encountered this error and I doubt is it due to any python package dependency issues. Can you please help me to resolve this soon.

## To reproduce
1. The docker image is built of MODEL type. My model name is **Test** and my py file and class within the py file is named **Test**
2. I used seldon-core==1.1.0 package
3. Below is the list of packages included in the requirements.txt file.
Flask==1.1.1
scipy==1.1.0
matplotlib
Werkzeug==0.15.5
easydict==1.9
opencv_python
gevent==1.4.0
mxnet_mkl
tqdm==4.35.0
#blosc
bcolz==1.2.1
Pillow==6.1.0
mtcnn_pytorch==1.0.2
mxnet==1.5.0
scikit_learn==0.21.3
tensorboardX==1.8
torch==1.9.0
torchvision==0.10.0
pyparsing==2.4.7
numpy==1.20.0
flask-ngrok
seldon-core==1.1.0

## Expected behaviour
Expected behaviour  is not to throw unrecognised arguments and execute the code successfully 

## Environment
I deployed this on a gke with seldon core operator 1.1.0 installed. GKE version is 1.19.14-gke.1900. 
My local environment is Linux os with seldon-core 1.1.0 pypi installed.

* Cloud Provider: GKE
* Kubernetes Cluster Version - 1.19.14-gke.1900.
* Deployed Seldon System Images: 
* value: docker.io/seldonio/engine:1.1.0
   value: seldonio/seldon-core-executor:1.1.0
   image: seldonio/seldon-core-operator:1.1.0

**Dockerfile**
FROM python:3.7

WORKDIR /app

COPY . . 

WORKDIR /app
RUN apt-get -y update

RUN apt-get -y upgrade 

RUN apt-get install ffmpeg libsm6 libxext6  -y
 
RUN export DISABLE_BCOLZ_AVX2=true && pip install -r requirements.txt

EXPOSE 5000

ENV SERVICE_TYPE MODEL

ENV MODEL_NAME Test

ENV API_TYPE REST

ENV PERSISTENCE 0

CMD exec seldon-core-microservice $MODEL_NAME $API_TYPE \
    --service-type $SERVICE_TYPE \
    --persistence $PERSISTENCE

**Comment by RafalSkolasinski** [comment]
Seldon Core 1.1.0 is a legacy now. We are on 1.11.2. Could you please try with newer version?

I have the feeling that there may be anyway a mismatch in versions, `$API_TYPE` CLI arg got deprecated a long time ago.

**Comment by divyadilip91** [comment]
Hi @RafalSkolasinski 
Thank you for your quick response.
I even tried using the latest seldon-core 1.11.2 py package and ran from my local. It still throws the error
**seldon-core-microservice: error: unrecognized arguments: Test --service-type MODEL --persistence 0**
Hence I wonder what could be the issue.

**Comment by divyadilip91** [comment]
Hi @RafalSkolasinski 
I found that the issue was caused due to the parser.arguments statements that I missed to remove from the __init__ function by which I received the above error. Thanks for your help.
