### ISSUE TITLE
Issue facing with Routing when predictors and models are in different container

### ISSUE THREAD

**Issue by durgasusm** [SeldonIO/seldon-core#3776]
Hi,
I am trying a routing example to work with multiple replicas.

But I am getting 503 Service Unavialable Issue. I deployed the sdep with Debug mode enabled which shows intenally where it is getting routed to .

## Yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: egreedy
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/seldonio/mock_classifier:1.11.0-dev
          name: classifier-3
    - spec:
        containers:
        - image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/seldonio/mab_epsilon_greedy:1.11.0-dev
          name: eg-router
    - spec:
        containers:
        - image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/seldonio/mock_classifier:1.11.0-dev
          name: classifier-1
    - spec:
        containers:
        - image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/seldonio/mock_classifier:1.11.0-dev
          name: classifier-2
    graph:
      children:
      - name: classifier-1
        type: MODEL
      - name: classifier-2
        type: MODEL
      - name: classifier-3
        type: MODEL
      name: eg-router
      parameters:
      - name: n_branches
        type: INT
        value: '3'
      - name: epsilon
        type: FLOAT
        value: '0.3'
      - name: verbose
        type: BOOL
        value: '1'
      type: ROUTER
    svcOrchSpec:
      env:
      - name: SELDON_ENABLE_ROUTING_INJECTION
        value: 'true'
      - name: SELDON_LOG_LEVEL
        value: "DEBUG"
    name: multi-models-predictor
    replicas: 1

When I execute the steps as given in 
https://render.githubusercontent.com/view/ipynb?color_mode=auto&commit=bce0b301ce3fa33b0af519c1625fb4b020e3a05f&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f53656c646f6e494f2f73656c646f6e2d636f72652f626365306233303163653366613333623061663531396331363235666234623032306533613035662f636f6d706f6e656e74732f726f75746572732f657073696c6f6e2d6772656564792f656772656564792e6970796e62&nwo=SeldonIO%2Fseldon-core&path=components%2Frouters%2Fepsilon-greedy%2Fegreedy.ipynb&repository_id=114898943&repository_type=Repository#E-Greedy-Test

When I execute the below py file
import requests
#rewards = {0: 0, 1: 1, 2: 0}
rewards = {0: 1, 1: 0, 2: 0}
for i in range(0, 50):
    req = {"data": {"ndarray": [[1.0, 2.0, 5.0]]}}

    res_raw = requests.post(
        "http://10.10.160.149:31897/seldon/mltest/egreedy/api/v1.0/predictions", json=req
    )
    res = res_raw.json()
    print(res)
    feedback = {
        "request": req,
        "response": res,
        "reward": rewards[res["meta"]["routing"]["eg-router"]],
    }
    res_raw = requests.post(
        "http://10.10.160.149:31897/seldon/mltest/egreedy/api/v1.0/feedback", json=feedback
    )
    assert res_raw.status_code == 200
    
 I get a 503 error.
 
 The logs of the Seldon-container-engine shows:
 
 # kubectl logs egreedy-multi-models-predictor-0-classifier-3-5cdd74c675-qd9vm -n mltest -c seldon-container-engine
{"level":"dpanic","ts":1638184289.883969,"logger":"entrypoint","msg":"odd number of arguments passed as key-value pairs for logging","ignored key":1,"stacktrace":"go.uber.org/automaxprocs/maxprocs.(*config).log\n\t/go/pkg/mod/go.uber.org/automaxprocs@v1.4.0/maxprocs/maxprocs.go:47\ngo.uber.org/automaxprocs/maxprocs.Set\n\t/go/pkg/mod/go.uber.org/automaxprocs@v1.4.0/maxprocs/maxprocs.go:123\nmain.main\n\t/workspace/cmd/executor/main.go:266\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
{"level":"info","ts":1638184289.883949,"logger":"entrypoint","msg":"maxprocs: Updating GOMAXPROCS=%v: using minimum allowed GOMAXPROCS"}
{"level":"info","ts":1638184289.8841262,"logger":"entrypoint","msg":"Hostname unset will use localhost"}
{"level":"info","ts":1638184289.8912287,"logger":"entrypoint","msg":"Starting","worker":1}
{"level":"info","ts":1638184289.8922787,"logger":"entrypoint","msg":"Starting","worker":2}
{"level":"info","ts":1638184289.89236,"logger":"entrypoint","msg":"Starting","worker":3}
{"level":"info","ts":1638184289.8923671,"logger":"entrypoint","msg":"Starting","worker":4}
{"level":"info","ts":1638184289.8923714,"logger":"entrypoint","msg":"Starting","worker":5}
{"level":"info","ts":1638184289.8950186,"logger":"entrypoint","msg":"Running http server ","port":8000}
{"level":"info","ts":1638184289.895055,"logger":"entrypoint","msg":"Creating non-TLS listener","port":8000}
{"level":"info","ts":1638184289.8953633,"logger":"entrypoint","msg":"Running grpc server ","port":5001}
{"level":"info","ts":1638184289.8953848,"logger":"entrypoint","msg":"Creating non-TLS listener","port":5001}
{"level":"info","ts":1638184289.8954792,"logger":"entrypoint","msg":"Setting max message size ","size":2147483647}
{"level":"info","ts":1638184289.8968446,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
{"level":"debug","ts":1638184507.4445834,"logger":"SeldonRestApi","msg":"Predictions called"}
{"level":"debug","ts":1638184507.444706,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://egreedy-multi-models-predictor-eg-router.mltest.svc.cluster.local.:9001/route"}
{"level":"info","ts":1638184507.4697971,"logger":"JSONRestClient","msg":"httpPost failed","response code":503}
{"level":"debug","ts":1638184507.4977603,"logger":"SeldonRestApi","msg":"Predictions called"}
{"level":"debug","ts":1638184507.4978275,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://egreedy-multi-models-predictor-eg-router.mltest.svc.cluster.local.:9001/route"}

It should get routed to "http://egreedy-multi-models-predictor-eg-router.mltest.svc.cluster.local:9001/route"

But a '.' is getting appended at the end, which is causing the issue. If I remove the '.' and execute the route url manually , it gives me a 200 response.

Let me know how to fix the issue .

**Comment by durgasusm** [comment]
In the constants file,

https://github.com/SeldonIO/seldon-core/blob/v1.11.0/operator/constants/constants.go

DNSClusterLocalSuffix = ".svc.cluster.local."

A '.' is added at the end , Is it causing the issue ?

**Comment by cliveseldon** [comment]
The dot at the end of the URI is standard practice so would not be causing the issue.

**Comment by cliveseldon** [comment]
Have you tried with latest 1.12 release to confirm still an issue?
