### ISSUE TITLE
Allow customisation of request-logger authorisation header

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#3786]
In certain scenarios Elasticsearch may require
```
Authorization: ApiKey ${TOKEN}
```
header to authenticate with Elasticsearch. Right now we hard-code to
```
Authorization: Bearer ${TOKEN}
```
so we should ideally just make it customisable through environmental variables (or just option for ApiKey header).

**Comment by RafalSkolasinski** [comment]
https://www.elastic.co/guide/en/kibana/master/api-keys.html

**Comment by cliveseldon** [comment]
Closing this. Please reopen if a priority.
