### ISSUE TITLE
Fix flakiness on server examples notebook test

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#3798]
## Describe the bug

There seems to be some flakiness on the server examples notebook. It's not clear how common is though, but we've seen it failing before (e.g. in https://github.com/SeldonIO/seldon-core/pull/3782).

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Closing until we figure clear steps to fix general flakiness.
