### ISSUE TITLE
Seldon-core python package upgrade (v1.2.2 to v1.5.0) leads to accumulation of local kafka producer queue

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#3803]
## Describe the bug

I recently tried to upgrade seldon-core python package from v1.2.2 to v1.5.0, and it leads to `BufferError: Local: Queue Full` from kafka, e.g.

```
  File "/app/path/to/myapp_image.binary.runfiles/vendor_python_pypi__confluent_kafka/confluent_kafka/serializing_producer.py", line 176, in produce
    super(SerializingProducer, self).produce(topic, value, key,
BufferError: Local: Queue full%   
```

I'm using a custom predictor by implementing the `predict_raw` method. In the method, it also writes send some data to kafka.

To debug this issue, I also made my predictor emit the local queue size of the Kafka producer as a metric, too, as shown below.

<img src="https://user-images.githubusercontent.com/527862/146029730-99331b91-dbeb-4759-a17c-38686548432f.png" width=800/>

as seen, in v1.2.2, the queue size stays flat, while in v1.5.0, it keeps going up, which I suppose eventually goes above either `queue.buffering.max.messages` (default 1e5) or `queue.buffering.max.kbytes` (default 1Gb).

The kafka related code for emitting data is like

```
producer.produce(topic=self.topic, key=str(uuid.uuid4()), value=df)
producer.poll(timeout=0)
```

so I do run `poll` after producing each message, based on https://github.com/confluentinc/confluent-kafka-python/issues/137#issuecomment-282427382.

Also, the seldon-core-operator version is v1.11.2.

This is puzzling because I didn't expect Seldon upgrade to change the behavior of kafka producer at all. I wonder if anyone has any insight into a possible reason?

**Comment by axsaucedo** [comment]
@zyxue not sure I'm fully clear so more context would be important, are you saying that you have a custom python wrapper that consumes directly from a kafka queue? Or do you mean the executor is the one consuming / producing and having the memory issue? Can you share the wrapper code?

**Comment by zyxue** [comment]
Assume by executor you mean the seldon-core-operator (usually a container named `seldon-container-engine` ), but I'm not talking about the executor.

The idea of my wrapper code is like

```python
class MyPredictor:
    def __init__(self, model_path):
        self._topic = 'my-topic'
        self._model = load(model_path)
        self._producer = confluent_kafka.SerializingProducer(...)

    def predict_raw(self, seldon_message):
        transformed = transform(seldon_message)
        self._producer.produce(topic=self._topic, key=str(uuid.uuid4()), value=transformed)
        self._producer.poll(timeout=0)

        kafka_metrics = [
            prediction_pb2.Metric(
                key=f"{my_kafka_queue_size",
                type="GAUGE",
                value=len(self._producer),
            )
        ]
        prediction = calc_prediction(transformed)

       out = wrap_metrics(prediction, kafka_metrics
        return out
```

It does seem unrelated to the seldon upgrade, which is why it's puzzling. My hunch is that seldon may interfere with the behavior of `self._producer.poll(timeout=0)`, which seems unlikely, but I can't think of any other reason for now.

Btw, how is Kafka used by seldon?

**Comment by cliveseldon** [comment]
Have you tried with the latest release and the issue still remains?

**Comment by zyxue** [comment]
I tried 1.6.0, and it's the same. I can't try higher version at the moment due to some dependency conflict, other parts of the system needs `click < 8`

**Comment by cliveseldon** [comment]
I'm not sure we can help here as this is not using the [default Kafka implementation we have](https://docs.seldon.io/projects/seldon-core/en/latest/streaming/kafka.html). Is there some reason you are choosing not to use that?

My suggestion would be to test in a local Docker container or directly to debug further. I can't see why the python wrapper would affect the Kafka producing without further logs/debug.

**Comment by zyxue** [comment]
I'm not quite sure how the seldon's kafka integration works, e.g. does it use schema registry, too?

**Comment by zyxue** [comment]
when using gRPC, it seems seldon's kafka integration just sends the whole serialized protobuf message to the topic?

https://github.com/SeldonIO/seldon-core/blob/master/executor/api/kafka/worker.go#L64-L68

**Comment by cliveseldon** [comment]
Yes it send serialized protos.

**Comment by cliveseldon** [comment]
Closing this.

**Comment by zyxue** [comment]
I checked this change of behavior happens between seldon-1.4.0 and seldon-1.5.0.

Based on https://github.com/confluentinc/confluent-kafka-python/issues/417, which reports a similar producer behavior. It is due to the producer initialized and used in two different processes.

Checking the seldon code, it does appear that
* in 1.4.0, the kafka producer is initialized in the main process when [the predictor class is initialized](https://github.com/SeldonIO/seldon-core/blob/v1.4.0/python/seldon_core/microservice.py#L352), and the grpc server also runs in the main process.
* But in 1.5.0, the kafka producer is still initialized in the main process, but the grpc server is run in a forked process.

Is it the case now both REST and gRPC services are run based on https://github.com/SeldonIO/seldon-core/blob/v1.5.0/python/seldon_core/microservice.py#L468 even if my service only supports gRPC?
```
    start_servers(server1_func, server2_func, server3_func, metrics_server_func)
```
