### ISSUE TITLE
Calling multiple model endpoints using SeldonClient

### ISSUE THREAD

**Issue by dhakrasp** [SeldonIO/seldon-core#3814]
In my Tensorflow SaveModel I have 2 methods exposed: predict() and get_weights().
I am using Tensorflow Proxy to load my model without any language wrapper.
I am able to successfully call the predict method using the Seldon Client. 
Is there any way to call the other method exposed by the model via Seldon Client? 
Is there any reference/questions/issues pointing to similar use cases?

**Comment by cliveseldon** [comment]
We don't support this by default in the python wrapper. You could extend the custom python you write to add further endpoints but not sure we have an example.
