### ISSUE TITLE
Write prediction errors to a dedicated Kafka topic

### ISSUE THREAD

**Issue by ashrafgt** [SeldonIO/seldon-core#3823]
## Problem Summary:
The native Kafka integration for Seldon Core currently only writes successful prediction requests to the output Kafka topic. This means the client has pretty much no way of determining if their request failed and why it failed.

## Improvement Suggestion:
Write errors to a Kafka topic `KAFKA_ERROR_TOPIC` that's dedicated to prediction errors. This means clients will have to add another consumer to their applications to detect prediction errors, but it'll ensure their data models won't be broken when parsing messages from `KAFKA_OUTPUT_TOPIC`.

The structure of the messages written to this error topic could be inspired by the information provided though the model logs. This for example:
```bash
2021-12-28 11:17:04,336 - werkzeug:_log:225 - INFO:  127.0.0.1 - - [28/Dec/2021 11:17:04] "POST /predict HTTP/1.1" 500 -        
2021-12-28 11:18:30,651 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': "can't multiply sequence by non-int of type 'float'", 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
```
would translate to:
```json
{ "message": "can't multiply sequence by non-int of type 'float'", "reason": "MICROSERVICE_INTERNAL_ERROR" }
```

**Comment by cliveseldon** [comment]
Feel free to provide a PR for this but not presently a priority or available resources.
