### ISSUE TITLE
Autoscaling is not achieved in pre-packaged servers

### ISSUE THREAD

**Issue by durgasusm** [SeldonIO/seldon-core#3827]
## Describe the bug

Trying to achieve the autoscaling for seldon with prepackaged server as describe in the 
https://docs.seldon.io/projects/seldon-core/en/latest/examples/autoscaling_example.html#Create-Load

## To reproduce

`apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: tfserving
  namespace: mltest
spec:
  name: anomaly
  annotations:
    #Use either of the annotations
    #traffic.sidecar.istio.io/excludeOutboundIPRanges: "<minio-service-ip>/32"
    traffic.sidecar.istio.io/excludeOutboundPorts: "9000"
  predictors:
  - componentSpecs:
    - hpaSpec:
        maxReplicas: 3
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 05
          type: Resource
        minReplicas: 1
      spec:
        containers:
        - name: tfserving
          command:
          - /usr/bin/tensorflow_model_server
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "100m"
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      implementation: TENSORFLOW_SERVER
      modelUri: s3://tfserving/verA
      envSecretRefName: seldon-init-container-secret
      name: anomaly
      parameters:
        - name: signature_name
          type: STRING
          value: predict_anomaly
        - name: model_name
          type: STRING
          value: anomaly
    name: default
`

After I execute the sdep.yaml , when I try to see the hpa it will show as unknown.

![image](https://user-images.githubusercontent.com/95343433/148321769-f661ecf9-b611-42aa-9f4d-f52853daadd6.png)

## Expected behaviour

Initially when no load is injected ; it should show 0%
![image](https://user-images.githubusercontent.com/95343433/148321998-b0fc159a-fbc2-43a2-ba59-c4860ccb79c6.png)

## Environment
# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Logs:

`[root@nc0747node02 load]# kubectl describe hpa tfserving-default-0-tfserving-anomaly -n mltest
Name:                                                  tfserving-default-0-tfserving-anomaly
Namespace:                                             mltest
Labels:                                                seldon-deployment-id=tfserving
Annotations:                                           <none>
CreationTimestamp:                                     Thu, 06 Jan 2022 03:04:24 +0000
Reference:                                             Deployment/tfserving-default-0-tfserving-anomaly
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 5%
Min replicas:                                          1
Max replicas:                                          3
Deployment pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age                    From                       Message
  ----     ------                        ----                   ----                       -------
  Warning  FailedGetResourceMetric       4m26s (x2 over 4m42s)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  4m26s (x2 over 4m42s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  104s (x10 over 4m11s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: missing request for cpu
  Warning  FailedGetResourceMetric       87s (x11 over 4m11s)   horizontal-pod-autoscaler  missing request for cpu
`

**Comment by durgasusm** [comment]
I tried to create without using prepackaged Server but still same issue.
`apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: tfserving1
  namespace: mltest
spec:
  annotations:
    #Use either of the annotations
    #traffic.sidecar.istio.io/excludeOutboundIPRanges: "<minio-service-ip>/32"
    traffic.sidecar.istio.io/excludeOutboundPorts: "9000"
  predictors:
  - name: default
    replicas: 1
    graph:
      name: anomaly
      type: MODEL

    componentSpecs:
    - hpaSpec:
        maxReplicas: 3
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 05
          type: Resource
        minReplicas: 1
      spec:
        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: kfserving/storage-initializer_python:0.7.0
          imagePullPolicy: IfNotPresent
          args:
            - "s3://tfserving/verA"

          envFrom:
          - secretRef:
              name: seldon-init-container-secret

        containers:
        - name: anomaly
          image: seldon/tfserving-proxy:1.11.0.2435
          command:
          - /usr/bin/tensorflow_model_server
          resources:
            requests:
              cpu: "250m"
`

**Comment by axsaucedo** [comment]
Thanks for the details @durgasusm. From the errors it seems like you don't have the metrics server installed, you need to set it up in order to use HPA as a general Kubernetes functionality - closing issue given this is not a seldon specific issue, but if there's issues persisitng once HPA is setup correctly feel free to create another issue
