### ISSUE TITLE
Add an WSGI app server to Python REST wrappers

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#383]
We should use e.g. Gunicorn to replace the Flask built-in server.

**Comment by ryandawsonuk** [comment]
See https://ironboundsoftware.com/blog/2016/06/27/faster-flask-need-gunicorn/

Related is #453

**Comment by marrrcin** [comment]
Have you considered using simpler WSGI server like Cheroot? It can be configured directly from the code.
