### ISSUE TITLE
Add integration tests for Kafka

### ISSUE THREAD

**Issue by agrski** [SeldonIO/seldon-core#3830]
There are no integration tests for Kafka integration, for example for the executor.  As this integration is increasingly popular, it would be beneficial to have high confidence in it.

As Confluent's `confluent-kafka-go` library seems to have no support for mocks or stubs for unit testing, it is not possible to effectively unit test this integration otherwise.

Note that that library's own tests are either integration tests or use a limited set of options for e.g. producers.

**Comment by agrski** [comment]
As a concrete example, testing SSL without a real broker is practically impossible - the `NewProducer` function is happy when provided with SSL options, but a quick dig into the underlying code suggests it doesn't check anything related to SSL at that point.

**Comment by cliveseldon** [comment]
Closing for now.
