### ISSUE TITLE
Clarify support on storage initializers

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#3831]
Currently our documentation mentions two storage initializers:
- kfserving storage initializer
- new rclone-based storage initializers

The kfserving storage initializer is more of a legacy thing to us with no plans to maintain it or solve issues if ones arise. 
We should clarify that in the documentation and mark it as deprecated. 

As both images are:
-  taking two args (source,dest paths)
-  are configurable by k8s secrets (but secret variables are different) 

the kfserving storage initializer will (most likely) continue to work.

**Comment by cliveseldon** [comment]
Think we can close this now as docs exist
