### ISSUE TITLE
unable to find proto file which defines grpc

### ISSUE THREAD

**Issue by ro7m** [SeldonIO/seldon-core#384]
i am unable to find proto file in the source code which defines CombinerGrpc , RouterGrpc ,etc.
@cliveseldon

**Comment by cliveseldon** [comment]
The proto definitions are [here](https://github.com/SeldonIO/seldon-core/blob/master/proto/prediction.proto)
 Which language are you using and can you explain your issue a bit more?

**Comment by cliveseldon** [comment]
For Java you can look at one of the Maven projects in the seldon-core tree, for example the engine folder:

 * See the [Makefile](https://github.com/SeldonIO/seldon-core/blob/3e24640615feef70b89e55b2a417eed4e2b616cd/engine/Makefile.ci#L41-L52) For example of how to get all the proto files
 * See the [pom.xml](https://github.com/SeldonIO/seldon-core/blob/3e24640615feef70b89e55b2a417eed4e2b616cd/engine/pom.xml#L134-L157) for the plugin to compile the protos
