### ISSUE TITLE
is it possible prevent hashed pod name on k8s

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#3847]
I see pod name like `seldon-408840920c1fe6d5eda0b20cec757dd2`, when I do `k get pod`, which isn't informative, is it possible to specify pod name in `SeldonDeployment` directly?

**Comment by cliveseldon** [comment]
There is the helm value https://github.com/SeldonIO/seldon-core/blob/21be14485bf038c9505b727c19f4b5765f54e356/helm-charts/seldon-core-operator/values.yaml#L87 which will use the deployment name as prefix to make things more readable

**Comment by zyxue** [comment]
@cliveseldon , do you mean I need to configure `deploymentNameAsPrefix` for the `seldon-core-operator` instead of configuring `SeldonDeployment` CRD?

**Comment by cliveseldon** [comment]
No I mean if you set this value when deploying via Helm then hashed pods will use as a prefix not `seldon-` but the name of your SeldonDeployment CRD.

**Comment by zyxue** [comment]
> No I mean if you set this value when deploying via Helm then hashed pods will use as a prefix not `seldon-` but the name of your SeldonDeployment CRD.

where should I set it in `SeldonDeployment`? I only see `deploymentNameAsPrefix` in operator code... maybe I'm missing something?

**Comment by cliveseldon** [comment]
See the above link to the Helm value.

**Comment by zyxue** [comment]
your link points to the configuration of the operator, right? `deploymentNameAsPrefix` is used in env of the operator deployment

```
 160   │         - name: DEPLOYMENT_NAME_AS_PREFIX
 161   │           value: '{{ .Values.manager.deploymentNameAsPrefix }}'
```

but I thought I can configure this value in `SeldonDeployment`? Do you have an more specific example?

**Comment by cliveseldon** [comment]
This setting will mean that if name of your pod would be too long so the operator needs to hash it then it will start the hash with the name of your SeldonDeployment so therefore its easier to match pod names to their owned SeldonDeployment.
