### ISSUE TITLE
Add lifecycle prestop hook to service orchestrator to sleep

### ISSUE THREAD

**Issue by dantheman0207** [SeldonIO/seldon-core#3849]
The services have a lifecycle prestop hook that causes them to sleep for 10 seconds. It appears the service orchestrator does not have this and we believe it is causing issues for us when the pods restart. Is it possible to add this? Happy to provide any more info.

**Comment by cliveseldon** [comment]
You mean the deployed containers have the livecycle prestop added? Its true its not added to the executor.

Can you give more details on what issues you are seeing so we can correlate to the preStop not being there?

**Comment by dantheman0207** [comment]
During pod autoscaling we are seeing lots of delayed and failed HTTP responses from the API. Our hypothesis is that the pods being downscaled are made unavailable before the new pods are brought up.

**Comment by cliveseldon** [comment]
So are you seeing it on rolling updates mainly and has it begin recently? Which version are you using?

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
