### ISSUE TITLE
Seldon-manager pod is failing to comeup

### ISSUE THREAD

**Issue by Tejasbglr** [SeldonIO/seldon-core#3850]
Hi Team,

I was deploying the seldon pod on AWS cluster. The manager pod is not coming up and the pod is going into the crashloop backoff stage. 

The kubectl version are

root@90e49e7c58b5:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

has anyone faced this kind of issue before?

**Comment by cliveseldon** [comment]
To clarify - you are saying the Seldon manager pod is not coming up? Can you provide the logs for the manager?
What is clog-sidecar?
Can you confirm the version of Seldon Core installed and how you installed it?

**Comment by Tejasbglr** [comment]
We are not getting any logs for the manager pod
	
	root@90e49e7c58b5:~/tejas/ml-inference-server# kubectl logs ml-test-server-seldon-66dff46db8-zk8tj -n tejas -c manager
    root@90e49e7c58b5:~/tejas/ml-inference-server#
    
	We are using seldon version 1.11

**Comment by Tejasbglr** [comment]
These are the contents i got when i described the pod 

Events:
  Type     Reason     Age                            From               Message
  ----     ------     ----                           ----               -------
  Normal   Scheduled  <invalid>                      default-scheduler  Successfully assigned tejas/ml-test-server-seldon-5d5f9cb975-sn7zf to ip-10-255-144-18.eu-central-1.compute.internal
  Normal   Pulling    <invalid>                      kubelet            Pulling image "709777208329.dkr.ecr.eu-central-1.amazonaws.com/nokia/bcmt-istio-proxyv2:1.7.6"
  Normal   Created    <invalid>                      kubelet            Created container istio-validation
  Normal   Started    <invalid>                      kubelet            Started container istio-validation
  Normal   Pulled     <invalid>                      kubelet            Successfully pulled image "709777208329.dkr.ecr.eu-central-1.amazonaws.com/nokia/bcmt-istio-proxyv2:1.7.6" in 163.80161ms
  Normal   Pulling    <invalid>                      kubelet            Pulling image "709777208329.dkr.ecr.eu-central-1.amazonaws.com/nokia/bcmt-istio-proxyv2:1.7.6"
  Normal   Started    <invalid>                      kubelet            Started container istio-proxy
  Normal   Created    <invalid>                      kubelet            Created container istio-proxy
  Normal   Pulled     <invalid>                      kubelet            Successfully pulled image "709777208329.dkr.ecr.eu-central-1.amazonaws.com/nokia/bcmt-istio-proxyv2:1.7.6" in 115.654531ms
  Normal   Pulled     <invalid> (x2 over <invalid>)  kubelet            Container image "csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/bkfw/distroless/seldon-core-operator:1.11.0.2497" already present on machine
  Normal   Started    <invalid> (x2 over <invalid>)  kubelet            Started container manager
  Normal   Created    <invalid> (x2 over <invalid>)  kubelet            Created container manager
  Normal   Started    <invalid> (x2 over <invalid>)  kubelet            Started container clog-sidecar
  Normal   Created    <invalid> (x2 over <invalid>)  kubelet            Created container clog-sidecar
  Normal   Pulled     <invalid> (x2 over <invalid>)  kubelet            Container image "csf-docker-candidates.repo.lab.pl.alcatel-lucent.com/bkfw/seldon/seldon-clog_centos7:1.11.0" already present on machine
  Warning  Unhealthy  <invalid> (x3 over <invalid>)  kubelet            Readiness probe failed: Get "http://192.168.38.105:15021/healthz/ready": dial tcp 192.168.38.105:15021: connect: connection refused
  Warning  BackOff    <invalid> (x2 over <invalid>)  kubelet            Back-off restarting failed container


Along with the manager container we have clog-sidecar and istio-proxy containers.........those two containers are coming up.

Below is the logs for clog-sidecar conatiner

root@90e49e7c58b5:~/tejas/ml-inference-server# kubectl logs ml-test-server-seldon-5d5f9cb975-sn7zf -n tejas -c clog-sidecar
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "setup : maxprocs: Updating GOMAXPROCS=%v: using minimum allowed GOMAXPROCS"}, "time": "2022-01-17T08:14:01.374Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.manager : Failed to get API Group-Resources"}, "time": "2022-01-17T08:14:01.374Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "setup : unable to start manager"}, "time": "2022-01-17T08:14:01.375Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": ""}, "time": "2022-01-17T08:14:02.376Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "ment\"}"}, "time": "2022-01-17T08:14:25.401Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.builder : Registering a validating webhook"}, "time": "2022-01-17T08:14:25.401Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.webhook : registering webhook"}, "time": "2022-01-17T08:14:25.402Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.builder : Registering a mutating webhook"}, "time": "2022-01-17T08:14:25.402Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.webhook : registering webhook"}, "time": "2022-01-17T08:14:25.402Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.builder : Registering a validating webhook"}, "time": "2022-01-17T08:14:25.402Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.webhook : registering webhook"}, "time": "2022-01-17T08:14:25.402Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.builder : Registering a mutating webhook"}, "time": "2022-01-17T08:14:25.403Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.webhook : registering webhook"}, "time": "2022-01-17T08:14:25.403Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.builder : Registering a validating webhook"}, "time": "2022-01-17T08:14:25.403Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.webhook : registering webhook"}, "time": "2022-01-17T08:14:25.403Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "setup : starting manager"}, "time": "2022-01-17T08:14:25.404Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "I0117 08:14:24.661649       1 leaderelection.go:243] attempting to acquire leader lease tejas/a33bd624.machinelearning.seldon.io..."}, "time": "2022-01-17T08:14:25.404Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.manager : starting metrics server"}, "time": "2022-01-17T08:14:25.404Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.webhook.webhooks : starting webhook server"}, "time": "2022-01-17T08:14:25.404Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.manager : error received after stop sequence was engaged"}, "time": "2022-01-17T08:14:25.404Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "E0117 08:14:24.662357       1 leaderelection.go:325] error retrieving resource lock tejas/a33bd624.machinelearning.seldon.io: Get \"https://172.20.0.1:443/api/v1/namespaces/tejas/configmaps/a33bd624.machinelearning.seldon.io\": context canceled"}, "time": "2022-01-17T08:14:25.405Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": "setup : problem running manager"}, "time": "2022-01-17T08:14:25.405Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.tejas", "system": "ml-inf-seldon", "type": "log", "log": {"message": ""}, "time": "2022-01-17T08:14:57.439Z"}

**Comment by cliveseldon** [comment]
Are you able to run without istio-sidecar or other sidecar injection to check perhaps ports are being blocked by istio?

**Comment by Tejasbglr** [comment]
we have disabled the sidecar injection as part of our deployment by setting the following field in the seldon-controller-manager-deployment.yaml to false 

**sidecar.istio.io/inject: "false"**

even after that we are observing the same issue

**Comment by Tejasbglr** [comment]
Below are  the logs for the seldon pod 

{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.<namespace>", "system": "ml-inf-seldon", "type": "log", "log": {"message": "controller-runtime.manager : error received after stop sequence was engaged"}, "time": "2022-01-17T08:14:25.404Z"}
{"version": "1.0", "level": "INFO", "host": "ml-test-server-seldon-5d5f9cb975-sn7zf.<namespace>", "system": "ml-inf-seldon", "type": "log", "log": {"message": "E0117 08:14:24.662357       1 leaderelection.go:325] error retrieving resource lock <namespace>/a33bd624.machinelearning.seldon.io: Get \"https://172.20.0.1:443/api/v1/namespaces/<namespace>/configmaps/a33bd624.machinelearning.seldon.io\": context canceled"}, "time": "2022-01-17T08:14:25.405Z"}

**Comment by cliveseldon** [comment]
Are there any particular RBAC setup on your cluster. This looks like a failure to connect to Kube API or a networking issue. Can you run without any sidecars?

**Comment by Tejasbglr** [comment]
Hi cliveseldon,

When I tried deploying seldon chart with version 1.6 on the cluster the deployment was successful.

But when i tried to deploy the seldon chart with version 1.11 i am facing the above mentioned issue.

**Comment by cliveseldon** [comment]
OK thanks. Can you try with 1.12 which is the latest? Also, 1.10 if 1.12 fails.

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
