### ISSUE TITLE
HPA Spec missing ScaleDown spec and is at v2beta

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#3854]
The current HPA spec we allow is at v2beta2 and does not allow [Scaling Behaviour](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#horizontalpodautoscalerbehavior-v2beta2-autoscaling) to be specified.

Need to investigate if

 * We upgrade to v1 spec
 * Allow ScalingBehaviour also to be specified

**Comment by OrenLederman** [comment]
It looks like Seldon supports Keda. If you have Keda installed, you can use it to control ScaleDown and ScaleUp
https://docs.seldon.io/projects/seldon-core/en/latest/examples/keda.html
https://keda.sh/docs/2.8/concepts/scaling-deployments/#scaledobject-spec
