### ISSUE TITLE
Failing notebooks integration test on MLFLow  prepackaged server

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3856]
## Describe the bug

The test `test_server_examples` in the notebooks e2e test seem to be failing consistently. The error that seems to appear is the mlflow server gets stuck when creating:

![image](https://user-images.githubusercontent.com/1447507/149757146-406bc5ff-3a12-46e1-a258-880880e2acca.png)

This may be related to https://github.com/SeldonIO/seldon-core/issues/3846

## To reproduce

* Run the wine example used in the integration tests
* View logs until it freezes
* If running the tests, wait until it times out and test fails

**Comment by mohammedi-haroune** [comment]
I'm having the exact same issue with seldon-core 1.12

**Comment by mohammedi-haroune** [comment]
But before that I was facing another problem, the pod kept restarting until I removed the default resources limits of the model container

The pod events shows this message:
```Pod sandbox changed, it will be killed and re-created```

This [StackOverflow answer](https://stackoverflow.com/a/60816665/7573221) hinted to me the fix of removing the resources limit

**Comment by mohammedi-haroune** [comment]
I'd like to know what fixed the issue ?
