### ISSUE TITLE
Failing ambassador rolling updates tests 

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#3857]
Currently the `test_rolling_update10` and `test_rolling_update5` are failing consistently for the ambassador tests, whilst passing on the istio tests. This can be reproduced locally by running the tests with the following commands:

```
pytest  -v -s --capture=no --log-cli-level=DEBUG test_rolling_updates.py::TestRollingHttp::test_rolling_update5
```

```
pytest  -v -s --capture=no --log-cli-level=DEBUG test_rolling_updates.py::TestRollingHttp::test_rolling_update10
```

The tests run for the 5 retries and fail on each, whilst passing on the istio configuration.

**Comment by cliveseldon** [comment]
Unlikely will look at until Ambassador update or deprecation
