### ISSUE TITLE
Upgrade executor confluent-kafka-go version to v1.8.2

### ISSUE THREAD

**Issue by stephen37** [SeldonIO/seldon-core#3866]
The executor is currently using [confluent-kafka-go v1.4.2 ](https://github.com/SeldonIO/seldon-core/blob/master/executor/go.mod#L7)that has been published in [May 2020](https://github.com/confluentinc/confluent-kafka-go/releases/tag/v1.4.2), if we want to support the ability to add CA certificate by PEM string, we need to use v1.8.2. 

https://github.com/confluentinc/confluent-kafka-go/releases/tag/v1.8.2

**Comment by cliveseldon** [comment]
@stephen37 Will you be able to add a PR for this to follow on from https://github.com/SeldonIO/seldon-core/pull/3813 ?
