### ISSUE TITLE
SOAP API

### ISSUE THREAD

**Issue by psinger** [SeldonIO/seldon-core#387]
Instead of REST API, we require to utilize a SOAP API. As far as I can see, Seldon can only serve REST APIs. Is there some plan on extending this to other API standards in the future, or is there an "easy" way for me to transform it to a SOAP API?

**Comment by cliveseldon** [comment]
Seldon presently exposes REST and gRPC endpoints.
We haven't considered SOAP. I imagine some SOAP to REST/gRPC proxy would be the best best.
I'm not sure of the current state of SOAP in the Cloud Native world of Kubernetes is.

**Comment by psinger** [comment]
Thanks @cliveseldon, that means we have to figure it out on our end how to transform it via some form of proxy.

**Comment by cliveseldon** [comment]
Closing as this seems outside our concern. Please reopen if further interest.
