### ISSUE TITLE
Seldon core installation with Ambassador in K8s 1.22+

### ISSUE THREAD

**Issue by ramanNarasimhan77** [SeldonIO/seldon-core#3872]
Hello,

We are making our application compatible with K8s 1.22+. We are using `seldon-core` with `datawire/ambassador`

Latest `datawire/ambassador` shown below uses removed/deprecated objects [See [Deprecation Guide v1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) ]

```
❯ helm search repo datawire/ambassador
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
datawire/ambassador             6.9.3           1.14.2          A Helm chart for Datawire Ambassador
datawire/ambassador-operator    0.3.0           v1.3.0          A Helm chart for Kubernetes

```

Also as per Seldon core documentation for [Ambassador ingress](https://docs.seldon.io/projects/seldon-core/en/latest/ingress/ambassador.html#installing-ambassador)

`Seldon Core currently only supports the V1 Ambassador APIs. You must use the datawire/ambassador helm chart rather than the V2 datawire/edge-stack or V2 datawire/emissary charts. Following the installation instructions below or in our installation guides should work fine.`

I was able to find an already open issue for verifying [Ambassador V2 support](https://github.com/SeldonIO/seldon-core/issues/3790)

**In the meantime is there any way forward for getting Ambassador + Seldon Core Operator working on Kubernetes 1.22+?**

**Comment by cliveseldon** [comment]
Thanks for the info. Can you validate if the [v1 emissary chart](https://github.com/emissary-ingress/emissary/tree/release/v1.14/charts/ambassador) also is not valid for k8s 1.22+? 

For full support, we would need to update seldon core to support the v2 API as discussed in the [issue](https://github.com/SeldonIO/seldon-core/issues/3790) you reference.

**Comment by ramanNarasimhan77** [comment]
Hi @cliveseldon 

On Analyzing the v1 emissary chart's Chart.yaml, I see it is same as  `ambassador` chart `appVersion: 1.14.2`

I looked at some of the objects like CRDs, Cluster Roles etc and these are use versions removed in 1.22+

![image](https://user-images.githubusercontent.com/52691361/150304180-b8166f80-c3da-4c04-9c8f-1309c61e7eae.png)

**Comment by ramanNarasimhan77** [comment]
Hello @cliveseldon 

I have a follow up question. Does `Seldon Operator` require any of the following CRDs? 

```
authservices.getambassador.io 
consulresolvers.getambassador.io 
devportals.getambassador.io 
filterpolicies.getambassador.io 
filters.getambassador.io 
hosts.getambassador.io 
kubernetesendpointresolvers.getambassador.io 
kubernetesserviceresolvers.getambassador.io 
logservices.getambassador.io 
mappings.getambassador.io 
modules.getambassador.io 
projectcontrollers.getambassador.io 
projectrevisions.getambassador.io 
projects.getambassador.io 
ratelimits.getambassador.io 
ratelimitservices.getambassador.io 
tcpmappings.getambassador.io 
tlscontexts.getambassador.io 
tracingservices.getambassador.io 

```

Looking at the [deprecated/removed resources list](https://github.com/SeldonIO/seldon-core/files/7909501/deprecations.txt), rest of the objects can be easily updated to meet the latest k8s 1.22+ spec. If seldon-core operator does not use any of the ambassador custom resource definitions then it might be worth a shot to try out uplifting remaining objects and skipping crds during installation.

**Comment by wumbrath** [comment]
Any plans for resolving this in the near future? Our kubernetes installation will be upgraded to 1.22 in about 2-3 months and we need to have a solution for this until then.

**Comment by cliveseldon** [comment]
We have not had a chance to spec out the work required yet. Are you able to clarify the core resources we would need to update and manage in the operator?

**Comment by wumbrath** [comment]
I don't know for all the already existing ones, but `Host` and `Mapping` has changed and a new mandatory one has been added. The major changes are summarized here: https://www.getambassador.io/docs/edge-stack/latest/about/changes-2.x/

**Comment by bchahn** [comment]
@cliveseldon 
Thanks a lot for the great work on seldon.io. We are currently using Seldon Core on K8s 1.21 and our cluster is expected to be upgraded to 1.22 in a few weeks. So we are a little uncertain how to proceed. Hopefully you can give us some transparency.
Can we expect this issue to be addressed shortly? If not, what is your suggestion how we should proceed? Do you recommend an alternative to Ambassador instead? In this case we would probably replace Ambassador by this alternative.
Thanks a lot in advance!

**Comment by ramanNarasimhan77** [comment]
From the documentation it looks like the only viable alternative is Istio. Howv

> Hello @cliveseldon
> 
> I have a follow up question. Does `Seldon Operator` require any of the following CRDs?
> 
> ```
> authservices.getambassador.io 
> consulresolvers.getambassador.io 
> devportals.getambassador.io 
> filterpolicies.getambassador.io 
> filters.getambassador.io 
> hosts.getambassador.io 
> kubernetesendpointresolvers.getambassador.io 
> kubernetesserviceresolvers.getambassador.io 
> logservices.getambassador.io 
> mappings.getambassador.io 
> modules.getambassador.io 
> projectcontrollers.getambassador.io 
> projectrevisions.getambassador.io 
> projects.getambassador.io 
> ratelimits.getambassador.io 
> ratelimitservices.getambassador.io 
> tcpmappings.getambassador.io 
> tlscontexts.getambassador.io 
> tracingservices.getambassador.io 
> ```
> 
> Looking at the [deprecated/removed resources list](https://github.com/SeldonIO/seldon-core/files/7909501/deprecations.txt), rest of the objects can be easily updated to meet the latest k8s 1.22+ spec. If seldon-core operator does not use any of the ambassador custom resource definitions then it might be worth a shot to try out uplifting remaining objects and skip crds during installation.

As a short term solution; we ended up making a custom ambassador chart without any CRD resources and updated the rest of the deprecated objects to work on K8s 1.22. We were able to deploy and use this with seldon-core,

For the long term solution, I see these are our options. 

1. Wait for Seldon-core to provide Ambassador V2 support? OR
2. Evaluate Istio based Ingress option which is already supported by Seldon ? OR
3. Wait for one of these tickets to be solved so that we could adopt any one of these ingress?
   [Support for using Contour as Ingress · Issue #1754 · SeldonIO/seldon-core (github.com)](https://github.com/SeldonIO/seldon-core/issues/1754)
[Support Traefik Ingress · Issue #1129 · SeldonIO/seldon-core (github.com)](https://github.com/SeldonIO/seldon-core/issues/1129)
[Nginx-Ingress Integration · Issue #416 · SeldonIO/seldon-core (github.com)](https://github.com/SeldonIO/seldon-core/issues/416)

**Comment by cliveseldon** [comment]
Thanks for the detailed response. These do seem the alternatives. For 3. we are looking for future API updates to Seldon to be more agnostic w.r.t service meshes so any can be used but that is some time away. Istio is supported and used by many seldon customers so 2. is definiely an option. 1. depends on resources and probably needs to be investigated further.

**Comment by bchahn** [comment]
> As a short term solution; we ended up making a custom ambassador chart without any CRD resources and updated the rest of the deprecated objects to work on K8s 1.22. We were able to deploy and use this with seldon-core,

@ramanNarasimhan77 
Your workaround would be interesting for us as well. Is there a chance that you can contribute this and @cliveseldon accepts the contribution?
 
> For the long term solution, I see these are our options; but we are not sure which one to finalize:
> 
> 1. Wait for Seldon-core to provide Ambassador V2 support? OR
> 2. Evaluate Istio based Ingress option which is already supported by Seldon ? OR
> 3. Wait for one of these tickets to be solved so that we could adopt any one of these ingress?
>    [Support for using Contour as Ingress · Issue #1754 · SeldonIO/seldon-core (github.com)](https://github.com/SeldonIO/seldon-core/issues/1754)
>    [Support Traefik Ingress · Issue #1129 · SeldonIO/seldon-core (github.com)](https://github.com/SeldonIO/seldon-core/issues/1129)
>    [Nginx-Ingress Integration · Issue #416 · SeldonIO/seldon-core (github.com)](https://github.com/SeldonIO/seldon-core/issues/416)

Thanks a lot for documenting the options. 
Regarding option 2: To be honest we are a bit reluctant in adopting Istio because it seems rather complex for this use case. In addition for us the integration between seldon.io and Kafka is very important. We are using https://strimzi.io/ for our Kafka deployment and unfortunately there are some conflicts when deploying Istio and strimzi.io at once. So we would prefer one of the other options.

**Comment by cliveseldon** [comment]
Needs further investigation
