### ISSUE TITLE
Prometheus Exporter Pod pending

### ISSUE THREAD

**Issue by roshanzameer** [SeldonIO/seldon-core#3880]
Seldon-Core: 1.11.0
Seldon-Core-Analytics: 1.11.0
Kubernetes: v1.19.11

The issue is also observed in Seldon-Core 1.12.0.

Issue 1:
   1. All the Model Metrics graphs on Grafana have no data.
   2. Could be linked to the below issue. 
   
Issue 2:
    1. seldon-core-analytics-prometheus-node-exporter pods remain in pending state.
    2. There are 5 node-exporter pods that remain in running state
    3. The pod description says " Normal   NotTriggerScaleUp  2m7s (x151 over 27m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't have free ports for the requested pod ports"
    4. Can the number of exporter pods be reduced?

**Comment by agrski** [comment]
Hi @roshanzameer,

To answer (4), there will always be one exporter pod per node, as the exporter needs to run on the node for which it is collecting metrics.  If you have a 20-node cluster, there would be 20 exporter pods.

For the rollout issue, are you saying that there are _already_ 5 node-exporter pods running from some other installation?  If so, that explains the conflict over ports - the `seldon-core-analytics` pods are standard node-exporter pods so would use the same ports as another standard node-exporter installation.

If there _are_ two separate node-exporter installations, the solution would be to remove one of them.  It should be possible to disable the bundled node-exporter in `seldon-core-analytics` with the following snippet in your Helm values file:
```yaml
prometheus:
  nodeExporter:
    enabled: false
```

**Comment by cliveseldon** [comment]
This PR https://github.com/SeldonIO/seldon-core/pull/4038 will be the preferred way of using prometheus going forward. Closing this issue.
