### ISSUE TITLE
Legacy cert-manager API versions are no-longer served: v1alpha2, v1alpha3, and v1beta1

### ISSUE THREAD

**Issue by jonathansp** [SeldonIO/seldon-core#3887]
## Describe the bug

cert-manager v1 API version [was released around 1 year ago](https://github.com/cert-manager/website/blob/master/content/en/docs/installation/upgrading/upgrading-0.16-1.0.md
). cert-manager 1.6 onwards [deprecates v1alpha2, v1alpha3, and v1beta1](https://cert-manager.io/docs/release-notes/release-notes-1.6/
).

When `certManager.enabled` is `true`, seldon-core-operator chart [uses cert-manager v1alpha2/3](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/certificate_seldon-serving-cert.yaml#L2), not allowing the usage of newer cert-manager versions.

## To reproduce
1. install cert-manager 1.6 using helm.
2. install seldon-core (using helm) with `certManager.enabled` set to `true`, 
3. see the error.

## Expected behaviour

Update chart to use v1 API from cert-manager.

## Environment
Any

**Comment by cliveseldon** [comment]
Looks like we should certainly upgrade to v1. Are you able to provide a simple PR for this?

**Comment by jonathansp** [comment]
@cliveseldon sure https://github.com/SeldonIO/seldon-core/pull/3888
