### ISSUE TITLE
Jaeger tracing with b3 propagation leads to a span being a child of itself

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#3889]
## Describe the bug

I have made jaeger tracing work with Seldon already with the default propagation format, and I can visualize the tracing within the inference graph on jquery UI.

But in order to integrate with the tracing setup of the rest of the microservices, I need to use [b3](https://github.com/openzipkin/b3-propagation) propagation. Based on 

https://github.com/SeldonIO/seldon-core/blob/ddcbf7fd1110e7dcad31aa5aac40908addb105ac/executor/api/tracing/trace.go#L24

I added 

```yaml
...
svcOrchSpec:
  env:
    - name: JAEGER_TRACE_PROPAGATION_TYPE
      value: b3
...
```

under `svcOrchSpec` in `SeldonDeployment` CRD, and added similar update toe the predictive unit containers. The trace still shows up on Jaeger UI, but the trace name becomes `<trace-without-root-span>`, 

![image](https://user-images.githubusercontent.com/527862/150924870-9cc29534-8d5a-452e-bcbe-b522e4f3d32b.png)

Inspecting the corresponding json of the trace, I see the root span becomes the child of itself, e.g.

```
            "spans": [
                {
                    "traceID": "5d2b7be4923f0fd9853be1cc9e5161bd",
                    "spanID": "34aef51038e82e3b",
                    "flags": 1,
                    "operationName": "/seldon.protos.Seldon/Predict",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "5d2b7be4923f0fd9853be1cc9e5161bd",
                            "spanID": "853be1cc9e5161bd"
                        },
                        {
                            "refType": "CHILD_OF",
                            "traceID": "5d2b7be4923f0fd9853be1cc9e5161bd",
                            "spanID": "34aef51038e82e3b"
                        }
                    ],
```

Note, spanID `34aef51038e82e3b` is a child of itself!

## To reproduce

seldon-core-operator: v1.12.0
jaeger-agent: 1.30

## Expected behaviour
traces can be properly visualized with b3 propagation and stitched to the rest of the microservices in the system.

## Environment

Cloud Provider: k8s on google cloud

Kubernetes Cluster Version: v1.20

Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]
```
          value: docker.io/seldonio/engine:1.12.0
          value: docker.io/seldonio/seldon-core-executor:1.12.0
        image: docker.io/seldonio/seldon-core-operator:1.12.0
```

All communications among predictive units and executor are in gRPC.

Any idea how to debug this?

**Comment by cliveseldon** [comment]
So this issue only happens when you switch on b3? if so can you try a trace without the other microservices - so directly calling Seldon to see if the issue arises?

I see this in [Istio](https://github.com/istio/istio/issues/11954) - could it be related?

**Comment by zyxue** [comment]
>So this issue only happens when you switch on b3? 

yes

> if so can you try a trace without the other microservices - so directly calling Seldon to see if the issue arises?

If I send a request to seldon without any `x-b3-` header, it works. 

But if I set `x-b3-` header, to mimic a request from other microservice, e.g.

```
with grpc.insecure_channel(f"localhost:5001") as channel:
    stub = prediction_pb2_grpc.SeldonStub(channel)
    response, call = stub.Predict.with_call(
        request=prediction_pb2.SeldonMessage(binData=request.SerializeToString()),
        metadata=(
            ("x-b3-traceid", "11111111111111111111111111111114"),
            ("x-b3-spanid", "1111111111111114"),
            ("x-b3-sampled", "1"),
        ),
    )
```
Then the reported trace shown up on Jaeger UI has similar problem, i.e. a span being child of itself.

**Comment by zyxue** [comment]
>So this issue only happens when you switch on b3? 

yes

> if so can you try a trace without the other microservices - so directly calling Seldon to see if the issue arises?

If I send a request to seldon without any `x-b3-` header, it works. 

But if I set `x-b3-` header, to mimic a request from other microservice, e.g.

```
with grpc.insecure_channel(f"localhost:5001") as channel:
    stub = prediction_pb2_grpc.SeldonStub(channel)
    response, call = stub.Predict.with_call(
        request=prediction_pb2.SeldonMessage(binData=request.SerializeToString()),
        metadata=(
            ("x-b3-traceid", "11111111111111111111111111111114"),
            ("x-b3-spanid", "1111111111111114"),
            ("x-b3-sampled", "1"),
        ),
    )
```
Then the reported trace shown up on Jaeger UI has similar problem, i.e. a span being child of itself.

**Comment by zyxue** [comment]
sending `x-b3-parentspanid` too reproduced the bug
```
            ("x-b3-traceid", "11111111111111111111111111111116"),
            ("x-b3-spanid", "1111111111111116"),
            ("x-b3-parentspanid", "2222222222222226"),
            ("x-b3-sampled", "1")
```
out:
```
"traceID": "11111111111111111111111111111116",
"spanID": "1111111111111116",
"flags": 1,
"operationName": "/seldon.protos.Seldon/Predict",
"references": [
{
"refType": "CHILD_OF",
"traceID": "11111111111111111111111111111116",
"spanID": "2222222222222226"
},
{
"refType": "CHILD_OF",
"traceID": "11111111111111111111111111111116",
"spanID": "1111111111111116"
}
],
```
seem the confusing part is why a span becomes a child of itself.

**Comment by zyxue** [comment]
Hey @andrewshaoyu , I see you added the b3 support at https://github.com/SeldonIO/seldon-core/pull/1445, thought you may have some insights.

**Comment by yurishkuro** [comment]
Please remember that Jaeger SDKs are officially deprecated in favor of OpenTelemetry.

**Comment by zyxue** [comment]
>Jaeger SDKs are officially deprecated 
yeah, but seldon still uses jaeger-client-go at the moment.

**Comment by yurishkuro** [comment]
I get that, my point is that if you find it's an actual bug in the SDK then we don't plan to release any more fixes. Also, you may want to consider using w3c propagation format instead of b3

**Comment by zyxue** [comment]
I understand. thanks for the reminder. The issue is that the rest of my org uses b3... 

At the moment, I am just curious why this error happens (maybe there is an easy fix), but I'm kind of out of idea now.

**Comment by yurishkuro** [comment]
yeah, I don't know, it seems odd. It may be related to zipkin's one span ID for client/server spans practice, but in Jaeger SDKs you usually need to enable that behavior explicitly via a flag, which is a property of the Tracer not the context marshaller.

**Comment by andrewshaoyu** [comment]
you can debug seldon-core executor,find where spans generate.

**Comment by cliveseldon** [comment]
please reopen if you can find the issue
