### ISSUE TITLE
Not able to hit seldon python language wrapper api with react frontend due to CORS policy

### ISSUE THREAD

**Issue by shashankc28** [SeldonIO/seldon-core#3891]
Hi ,
Is there a way to enable CORS policy for cross origin at seldon end .

getting below error :
Access to XMLHttpRequest at '<backendurl>' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

request used:
const url = "http://"+deployRoute+"/api/v1.0/predictions"
    const res = await axios.post(url, json, {
      headers: {
        // Overwrite Axios's automatically set Content-Type
        'Content-Type': 'application/json'
      }
    });

**Comment by axsaucedo** [comment]
Currently the Python language wrapper doesn't support CORS - we have an open PR that is looking to add CORS, and may go ahead either during the next release next month or the following https://github.com/SeldonIO/seldon-core/pull/3819/files

For the meantime you can use the new Python V2 language wrapper instead as this does support CORS https://github.com/SeldonIO/MLServer there are several examples how you would be able to use it as it has some key differences to the current (v1) wrapper.
