### ISSUE TITLE
SeldonDeployment as a service on Openshift Catalog

### ISSUE THREAD

**Issue by mabruch123** [SeldonIO/seldon-core#3893]
Hello,
This is not really a feature request, but this type of issue is the closest to what I am aiming for.
Looking for suggestions, really.
I have a private Openshift v4.5 cluster, and I am trying to utilize the Catalog and Template features in order to create a self-service for consuming SeldonDeployment objects.
The main issue I'm facing is that as opposed to other self-services we have set up here (MongoDB, Kafka etc.), the core of a SeldonDeployment object is vastly different from one another (due to the fact that at the heart of the deployment sits a unique model, which unique attributes and configurations are derived from it [Volumes, Configmaps, Ports etc.])
Hence why I am having trouble creating a generic-enough Template to suit the vast majority of consumers.
I was wondering if you had any suggestions regarding this topic? how to properly implement such generic service? Which parameters should I use as part of the Template?
Any ideas and suggestions are welcome.
Thanks

**Comment by cliveseldon** [comment]
Can you provide references to example Catalog and Template features you have done already?

**Comment by cliveseldon** [comment]
You can also look at [our Helm charts](https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-single-model) for inspiration. Closing as not sure how else we can help.
