### ISSUE TITLE
Tensorflow / Seldon protocol proxy specify resources by default to make autoscaling easier

### ISSUE THREAD

**Issue by jacobmalmberg** [SeldonIO/seldon-core#3899]
Autoscaling requires the user to specify resources for each container, such as input transformer and model, in the graph. When using tensorflow with the seldon protocol, an additional proxy container is spawned. To use autoscaling, one then has to specify resource requests for that container too. It is not obvious to the user that this has to be done; the user does not have to specify resource requests for other system containers such as the seldon-container-engine since its resource requests are set by default. It would make autoscaling easier to use if resource requests/limits was specified by default for the proxy container.

**Comment by cliveseldon** [comment]
Thanks for this. Have you investigated the range of values that would make sense as defaults?

**Comment by jacobmalmberg** [comment]
Somewhat. In my experience the load on the tfserving container does not go up significantly when scaling up. Below is the output from ` k top pods --containers=true --use-protocol-buffers`. As can be seen, tfserving is about 50% higher than seldon-container engine. The default requests/limits for seldon-container-engine are cpu 500m / mem Mi 512. Perhaps the limit/requests for tfserving should then be cpu 750m / mem 768 Mi

```sh
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-hr2mg          input-transformer                 137m         97Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-hr2mg          output-transformer                215m         113Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-hr2mg          seldon-container-engine           173m         135Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-hr2mg          tfserving                         267m         191Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-hr2mg          trace-model-pipeline              427m         253Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-l2hpp          input-transformer                 137m         105Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-l2hpp          output-transformer                252m         118Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-l2hpp          seldon-container-engine           190m         122Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-l2hpp          tfserving                         269m         195Mi
seldon-540032753260be1f5d608c0d4ca93727-64b66c8489-l2hpp          trace-model-pipeline              487m         259Mi
```

**Comment by cliveseldon** [comment]
At present a workaround is to set the resource/requests in the containerSpec explicitly. So if you create two containers one with the name of your predicticeUnit and one called "tfserving" and add values for requests.

Otherwise we would need to add defaults for all prePackaged servers. 

I have added an example test in https://github.com/SeldonIO/seldon-core/pull/3928
