### ISSUE TITLE
Allow binary file upload via REST API

### ISSUE THREAD

**Issue by adrianloy** [SeldonIO/seldon-core#3914]
From my current understanding, it seems like if I do a seldon model deployment with a `predict` or a `predict_raw` method, there is no way to send raw bytes to my `predict` method via the seldon Rest API. That means, that if I have an image classifier, I can not handle the decoding of an image file myself, I have to do it on the client side. This is suboptimal, as it means I have to send the image with a string representation (either directly the numpy array values, or a base64 encoded string representation of the image). 
However, it seems to be preferable to allow my seldon deployment to handle requests like created by this curl command:
```
curl -F "binData=@image3.jpeg" http://localhost:9000/api/v1.0/predictions/
```

Am I correct that currently there is no way to send binary data via the REST API?

**Comment by cliveseldon** [comment]
We do support in the python wrapper [multipart forms with bindata passed as file](https://github.com/SeldonIO/seldon-core/blob/fd79a637478d230d141b86e215d03b62b354a785/python/seldon_core/flask_utils.py#L11-L17). 

Can you also verify if your issue is related to https://github.com/SeldonIO/seldon-core/issues/3862

**Comment by adrianloy** [comment]
Thanks for the pointer,  `curl -X POST -H "Content-Type: multipart/form-data" -F "binData=@image3.jpeg" http://localhost:9000/api/v1.0/predictions` indeed did the job for me. Was hard for me to figure this out without help, as the [docs](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/internal-api.html) indicate that you can just send a JSON request to the Rest API.

**Comment by SanthoshRaju91** [comment]
I would have struggled to find a solution or contact the Seldon team from our company's enterprise support if I had not seen this github issue. Indeed the docs are difficult to find specs for Api reference, please for the better developer experience improve the docs. My only feedback. Thank you.

**Comment by cliveseldon** [comment]
Thanks for the feedback @SanthoshRaju91 I know @edshee wants to work further on the docs. Also, if you are able to create a PR for a small docs update that would help.

**Comment by XiaoxueWang1** [comment]
Does seldon allow binary file upload via REST API  with v2 protocol?

**Comment by cliveseldon** [comment]
We don't presently provide this for v2 protocol. But note there are some good [clients](https://github.com/triton-inference-server/client#client-library-apis) from triton for the protocol which might help.

**Comment by XiaoxueWang1** [comment]
OK, thank you. And I have a similar question:
Does seldon allow binary file upload via REST API for tensorflow protocol?
