### ISSUE TITLE
Bug: Disabling seldon-container-engine for existing deployment creates duplicate services with same ports

### ISSUE THREAD

**Issue by senyo-asamoah-zefr** [SeldonIO/seldon-core#3935]
Given an existing seldon deployment will all accompanying resources, ie: services and virtualservices, disable the seldon container engine by adding the annotation;
```
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
```
Results in the container engine being removed successfully but also results in the associated service which. is normally being served over port 80 and 5000 to be switched to that of the classifiers' ports, ie 9000 and 9500.

## To reproduce
1. define model ...
2. build image ...
3. deploy ...
4. edit the Kubernetes manifest for your seldon deployment and add the annotation stated above to the predictors
5. Apply the changes from step 4
6. Verify that container-engine sidecar is no more part of the deployment and verify the services available

## Expected behavior
1. Only the classifiers services should remain
Actual:
1. There are 2 services still but this time both have the same ports, ie 9000 and 9500

## Environment

* Cloud Provider: AWS
* Kubernetes Cluster Version 1.22
* Deployed Seldon System Images: 
```
          docker.io/seldonio/engine:1.6.0
          docker.io/seldonio/seldon-core-executor:1.6.0
        idocker.io/seldonio/seldon-core-operator:1.6.0
```

**Comment by senyo-asamoah-zefr** [comment]
First of all i am so sorry for my very late response. Yes , i think the expectation with turning the engine off is that the associated objects ie the k8s service will equally be deleted but that is not the case, resulting in 2 services with same name with same port-mappings.

**Comment by cliveseldon** [comment]
Happy to review a PR but as this does not affect functionality will close for now
