### ISSUE TITLE
model pipeline failing

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#3936]
Newer version of pip for some obscure reasons does not create conda-pack entrypoint / tool / script in corresponding `.bin` folder in the model pipeline.

Replacing 
```
env:
	python3 -m venv .env
	./.env/bin/pip install --upgrade pip setuptools
	./.env/bin/pip install -r requirements.txt
```
with
```
env:
	python3 -m venv .env
	./.env/bin/pip install --upgrade pip==21.2.4 setuptools==58.1.0
	./.env/bin/pip install -r requirements.txt
```
in `seldon-core/servers/mlflowserver/models/elasticnet_wine/Makefile` fixes the problem.

Note, this is the same version we lock pip and setuptools in other places.

**Comment by axsaucedo** [comment]
Fixed as part of release process and merged via #3939
