### ISSUE TITLE
Organize docs

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#394]
We should structure the docs using some static page generator and hosting it on the docs.seldon.io subdomain. Some options:

  * Sphinx + readthedocs.org theme (e.g. [Pachyderm](http://docs.pachyderm.io/en/latest/))
  * Hugo with an appropriate theme (e.g. [Kubeflow](https://www.kubeflow.org/docs/))

**Comment by cliveseldon** [comment]
We now use readthedocs
