### ISSUE TITLE
Build multi-arch images if possible, including arm64

### ISSUE THREAD

**Issue by ezelenka** [SeldonIO/seldon-core#3947]
Please build multi-arch images if possible, including at least arm64 platform.

**Comment by cliveseldon** [comment]
Are you able to provide a PR for this or an outline of steps?

**Comment by ezelenka** [comment]
@cliveseldon I found the code here: https://github.com/SeldonIO/seldon-core/tree/master/core-builder
which uses docker directly and potentially some precompiled packages as well. This potentially can be done using buildx - https://docs.docker.com/buildx/working-with-buildx/ , or podman - https://podman.io/ and feels like fair amount of work. I don't have PR for this work. Why I'm saying "if possible", is because I'm not sure if there are pre-build dependencies for this image which are arch specific or not.

**Comment by cliveseldon** [comment]
Not for now - closing
