### ISSUE TITLE
Tracking custom metrics in predict raw

### ISSUE THREAD

**Issue by harshita-meena** [SeldonIO/seldon-core#3964]
## Describe the bug
The predict_raw function does not track any metrics defined in metrics() in the user_model, it takes only the metrics inside the seldon request json. https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/seldon_methods.py#L105-L108 I wonder why is that so, can we not call client_custom_metrics for predict raw as well. 

## To reproduce
Define a predict_raw function in user model, prometheus metrics like RPS,latency (logic in user model code) are not exported. 

## Expected behaviour
All the metrics being raw inside request or not should be exported as part of any predict function(predict or predict_raw)

**Comment by axsaucedo** [comment]
@harshita-meena currently this is actually supported, you can add your metrics by putting them under the `{... "meta": { "metrics": ... } }` location in the same format - you can see how it's processed here:

https://github.com/SeldonIO/seldon-core/blob/970d254c3ff0bc81f7fb2d5cb479b224b0a24625/python/seldon_core/seldon_methods.py#L105
