### ISSUE TITLE
Seldon 1.12.0 in OCP 4.8.x

### ISSUE THREAD

**Issue by RaulBMG** [SeldonIO/seldon-core#3965]
## Context
We use OpenShift Container Platform 4.8 in our installations. The latest version, 1.12.0, is not available for this Platform using the Marketplace for version 4.8.x.

## The necesity
This latest version has some features that we are really interested in using and integrating with our platform, hence the need for this latest version.

## The request
Could you please make Seldon 1.12.0 available for OCP 4.8 ?

## Acceptance criteria
- [ ] Seldon Core 1.12.0 and all of his componentes are available in OpenShift 4.8.x Operator Marketplace (available [here](https://catalog.redhat.com/software/operators/detail/5ec3fa5778e79e6a879fa213#deploy-instructions)).

**Comment by cliveseldon** [comment]
That is strange as the 1.12.0 release of core was [merged into certified operators](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/405)

**Comment by RafalSkolasinski** [comment]
I just spun up OpenShift 4.8 instance and I do see following operators available 
![image](https://user-images.githubusercontent.com/10928117/156624529-101b23a9-f4f4-4bb6-89ef-c17592b9a663.png)

For comparison, on OpenShift 4.9 I see
![image](https://user-images.githubusercontent.com/10928117/156624668-d941ec49-fef1-4f87-a9d8-05337f82c3e8.png)

@RaulBMG Could you check if in `openshift-marketplace` namespace there are no `openshift-operators-xxx` pods in the `ImagePullBackOff` state?

**Comment by RaulBMG** [comment]
Greetings!

I do see the Operators, however the latest version I can install for Seldon is `v1.7.0` , which is not what we need. Are you sure that you can see the `v1.12.0` for OCP 4.8.x?

**Comment by axsaucedo** [comment]
Thank you for reporting/following-up @RaulBMG - we're currently in discussions with the Redhat team about this as it does seem to be an issue, which can be followed at https://github.com/redhat-openshift-ecosystem/certified-operators/issues/576

**Comment by axsaucedo** [comment]
@RaulBMG it seems that this may have been partially fixed - I can now see the tag 1.13.1 in various listings, can you confirm that this is the case from your side as well?

**Comment by cliveseldon** [comment]
Closing as should be available now. Please reopen if not.
