### ISSUE TITLE
Duplicate metrics generated for GRPC requests hitting seldon predict_raw

### ISSUE THREAD

**Issue by harshita-meena** [SeldonIO/seldon-core#3968]
## Describe the bug
Currently trying to host a model on seldon, using python seldon-core inside kubernetes deployment, I started noticing that the RPS recorded is always coming out to be half of the actual value, on further analysis saw that same prometheus metrics with same tags is generated twice but with different value. 
My metric function looks like this
```
return [
            {
                "type": "TIMER",
                "key": "seldon_run_time_milisecs_histogram",
                "value": self.request_duration_ms,
                "tags": {"service": self.model_name, 'route': <REST or GRPC>},
            },
        ]
```
The duplicate metrics for count with two different values
```
seldon_run_time_milisecs_histogram_count{SAME TAGS, route="GRPC", worker_id="86"} 994
seldon_run_time_milisecs_histogram_count{SAME TAGS, route="GRPC", worker_id="86"} 1005

```

## To reproduce
Host a seldon model and send a curl (any http load testing tool) and grpcurl (or ghz) command, grpc metrics will have two different values while rest looks fine. 

## Expected behaviour
Would like to get an aggregate metric
```
seldon_run_time_milisecs_histogram_count{SAME TAGS, route="GRPC", worker_id="86"} 1999

```

**Comment by axsaucedo** [comment]
I'm not sure I fully understand the current issue - just for context, the requests-per-second metric is not calculated/exposed in the python component/container, but it's exposed by the service orchestrator component (which you can see is deployed by default as part of every model you deploy). 

It seems the error you are reporting seems to be specifically about the service orchestrator metrics, but it also seems you're aiming to replicate an issue with the python language wrapper custom metrics functionality.

Is the current issue you are seeing that you are getting half the total RPS metric?

**Comment by harshita-meena** [comment]
Hi Alejandro
Thanks for your reply! I am only using the seldon sdk and not the complete Seldon service. I am hosting a model on a kubernetes basic deployment with seldon image with the latest python version. So i do not have the orchestrator which comes by default with seldon. I am also not entirely sure why it is happening but yes your understanding is correct that I am getting half of the RPS from what i expect to get, if you have any context on why that could happen. I am using predict raw and it is happening only for that case, the metrics are exported fine with predict but not so for predict_raw. Due to some upstream issues we had to use the custom predict_raw instead of predict. 

My predict_raw looks like this
```
    def predict_raw(self, msg) -> Union[prediction_pb2.SeldonMessage, dict]:
        is_proto = isinstance(msg, prediction_pb2.SeldonMessage)

        t0 = time.time()
        output = super().predict_raw(msg)
        self.request_duration_ms = (time.time() - t0) * 1000

        if is_proto:
            self.route = "GRPC"
            # extend metrics meta in seldon msg
            meta_json = get_meta_from_proto(output)
            metrics = meta_json.get("metrics", [])
            metrics.extend(self.metrics())
            meta_json["metrics"] = metrics

            metrics_meta = prediction_pb2.Meta()
            json_format.ParseDict(meta_json, metrics_meta)
            return prediction_pb2.SeldonMessage(data=output.data, meta=metrics_meta, status=output.status)
        else:
            self.route = "REST"
            return construct_response_json(self, False, msg, output, output.get("meta", None), self.metrics())
```

**Comment by harshita-meena** [comment]
I can give you an example of a model i tried hosting locally. 
I sent 5 REST and 8 GRPC requests which has 2 rest and 2 grpc workers, this is the output of my metrics endpoint hosted on port 6000. 
```

seldon_run_time_milisecs_histogram_count{SAME_TAGS..,route="GRPC",worker_id="31"} 4.0
seldon_run_time_milisecs_histogram_count{SAME_TAGS...,route="GRPC",worker_id="31"} 1.0
seldon_run_time_milisecs_histogram_count{SAME_TAGS...,route="GRPC",worker_id="33"} 1.0
seldon_run_time_milisecs_histogram_count{SAME_TAGS...,route="GRPC",worker_id="33"} 2.0
seldon_run_time_milisecs_histogram_count{SAME_TAGS...,route="REST",worker_id="48"} 1.0
seldon_run_time_milisecs_histogram_count{SAME_TAGS...,route="REST",worker_id="38"} 4.0
```

As you can see the same tags for worker 31 and 33 that belongs to grpc requests were generated twice, so prometheus is having trouble processing this data as it does not aggregate same metric keys with different values.

**Comment by harshita-meena** [comment]
I found a solution to the duplicate metric issue, it is related to a temporary tag key used for prometheus pushes which can have multiple values (unordered dictionary) if extracted from a proto message. 
https://github.com/SeldonIO/seldon-core/compare/master...harshita-meena:patch-1

**Comment by axsaucedo** [comment]
Great to hear @harshita-meena - thanks
