### ISSUE TITLE
Serving Alibi-Detect models

### ISSUE THREAD

**Issue by aqibfayyaz** [SeldonIO/seldon-core#3979]
HI i am trying this example https://mlserver.readthedocs.io/en/latest/examples/alibi-detect/README.html but when i run command mlserver start . i get the following error
pydantic.error_wrappers.ValidationError: 1 validation error for ModelSettings
implementation
  ensure this value contains valid import path or valid callable: Module "mlserver_alibi_detect" does not define a "AlibiDetectRuntime" attribute (type=type_error.pyobject; error_message=Module "mlserver_alibi_detect" does not define a "AlibiDetectRuntime" attribute)

**Comment by cliveseldon** [comment]
Can you reopen in [mlserver](https://github.com/SeldonIO/mlserver) github repo?
