### ISSUE TITLE
Error in creating custom model

### ISSUE THREAD

**Issue by vaporpin** [SeldonIO/seldon-core#3988]
Hi, 

at this section, https://docs.seldon.io/projects/seldon-core/en/latest/workflow/github-readme.html#deploy-your-custom-model-using-language-wrappers. I created an image using 

s2i build https://github.com/myGitHubUsername/seldon.git --context-dir=sklearn-model seldonio/seldon-core-s2i-python3 myDockerUsername/sklearn_iris:0.1 --env MODEL_NAME=iris-model --env API_TYPE=REST --env SERVICE_TYPE=MODEL --env PERSISTENCE=0

In the github repo, i have Model.py and model.pickle file  in a sklearn-model folder. Model.py as follows : 

-----------------------------------------------------------------------------
import pickle
class Model:
    def __init__(self):
        self._model = pickle.loads( open("model.pickle", "rb") )

    def predict(self, X):
        output = self._model(X)
        return output

I have these errors when I apply the manifest below

$ kubectl apply -f - << END
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model
  namespace: model-namespace
spec:
  name: iris
  predictors:
  - componentSpecs:
    - spec:
      containers:
      - name: classifier
        image: myDockerUsername/sklearn_iris:0.1
  - graph:
      name: classifier
    name: default
    replicas: 1
END

DEBUG : Configuration directory could not be created and will not be used: mkdir /config: permission denied
ERROR : Local file system at /data/myDockerUserName/sklearn_iris:0.1: error reading source root directory: directory not found"

Any idea what error is this? Or is there any other examples i can follow to create my own custom model? Thank you.

**Comment by cliveseldon** [comment]
Can you clarify where those errors are coming from? Which pod?

**Comment by cliveseldon** [comment]
Did you get any further debugging this issue?

**Comment by cliveseldon** [comment]
Closing - please reopen if new info can be provided
