### ISSUE TITLE
How to check version in seldon-core

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [SeldonIO/seldon-core#4007]
This is not a bug, but more of a question
## Describe the question

I am trying to do an upgrade of seldon-core to a latest version. We are following [kustomize installation](https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html#seldon-core-kustomize-install) for upgrading from v1.1.0 to v1.13.0.
 I want to verify if it's really upgraded by checking version of seldon-core. Any suggestion on how to check version for seldon-core?
 
 Thanks, for all the amazing work the team does.

**Comment by cliveseldon** [comment]
You could check what is on the [configmap](https://github.com/SeldonIO/seldon-core/blob/master/operator/config/manager/configmap.yaml) or the image of the manager pod.

**Comment by axsaucedo** [comment]
Normally the way to verif the images are:
```
kubectl get pods -n seldon-system -o yaml | grep image
```
as well as validating the configmap as clive suggests - eg
```
kubectl get cm -n seldon-system seldon-config -o yaml
```

Closing but feel free to reopen if still an issue
