### ISSUE TITLE
upstream request timeout error when deploying Keras model object image in my local mac

### ISSUE THREAD

**Issue by varunTealium** [SeldonIO/seldon-core#4012]
## Describe the bug
I am trying to deploy a Keras model object image via seldon core. When I am creating a Post request via Postman I am running into following error:
upstream request timeout

## To reproduce
Steps required to reproduce the issue:
1. define model - Here is my Model.py

```python
import tensorflow as tf

class Model(object):
    def __init__(self):
        self._model = tf.keras.models.load_model('keras_model.h5') #pickle.loads(open("keras_model.h5", "rb") )
        print("initializing")

    def predict(self, X, features_names):
        output = self._model.predict(X)
        return output
```

3. build image
I tried following IMAGE URLS and nothing worked for me:

s2i build /Users/varunkumar/PycharmProjects/seldon_testing seldonio/tfserving-proxy:1.13.1 keras-image:0.1
and
s2i build /Users/varunkumar/PycharmProjects/seldon_testing seldonio/seldon-core-s2i-python3:1.13.1 keras-image:0.1
and
s2i build /Users/varunkumar/PycharmProjects/seldon_testing seldonio/seldon-core-s2i-python3:1.14.1-dev keras-image:0.1

5. deploy - I used following command to deploy:

```bash
kubectl apply -f - << END                                                                                     
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: kerasm19
  namespace: seldon
spec:
  name: kerasm19
  annotations:
    seldon.io/rest-timeout: "100000"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: kerasm19
          image: keras-image:0.1
    graph:
      children: []
      name: kerasm19
      endpoint:
        type: REST
      type: MODEL
    name: kerasm19
    replicas: 1
END
```

## Expected behaviour
I passed in following input data via POSTMAN in my post request:
 
```json
{"data": { "ndarray": [[-0.41605629,  1.38631762, -2.11444564,  0.93449351, -0.32028268,
         0.49530232,  1.19900006, -0.80316913, -0.04789653, -1.02827329,
        -1.64387761, -1.30813206,  0.19726349, -1.25939166, -1.18891931,
         1.59210675, -0.43880024, -0.78005846, -0.72677247,  1.48749822,
         0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0 , 0.0, 0.0,  0.0]], "names": "1" } }
```
And I expect following output:
array([[1.]], dtype=float32)

P. S - I get the exact output if I try to predict above mentioned Model.py with the mentioned input data in my IDE (jupyter notebook). 

## Environment

* Cloud Provider: local mac
* Kubernetes Cluster Version [Output of `kubectl version`]: kubectl version                                                                                               
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cliveseldon** [comment]
You probably want to load you model in a separate `load` method as described [here](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load)

**Comment by varunTealium** [comment]
Thank you, this worked for me. Here is my new Model.py which worked:

```python
import tensorflow as tf

class Model(object):
    def __init__(self):
        print("initializing")

    def load(self):
        self._model = tf.keras.models.load_model('keras_model.h5')

    def predict(self, X, features_names):
        self.load()
        output = self._model.predict(X)
        return output
```
