### ISSUE TITLE
Removal & depreciation of request logger component

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#4013]
We are looking to depreciate and remove the request logger component as the python request logger was initially created as an example that can be used to show the functionality in the service orchestrator to push inputs and outsputs to external URLs, and show how the request can be inserted into an elasticsearch store.

As further protocols have been added and further data type schemas have been added the complexity of this component has grown significantly but it has also not improved in its reliability and best practices. We are looking to depricate and remove this component, and instead provide an example for users to showcase how they can use the request-forwarding functionality of the service orchestrator to integrate with other systems respectively.

**Comment by ysk24ok** [comment]
@axsaucedo Hello, [the feedback metrics server example](https://github.com/SeldonIO/seldon-core/tree/master/examples/feedback/feedback-metrics-server) still has `seldon-request-logger` component. Don't you need to delete it as well?
Also, what is the alternative to the request logger to dump request/response to elasticsearch?

**Comment by RafalSkolasinski** [comment]
Hi @ysk24ok - we do not maintain the `seldon-request-logger` Python implementation that has been in this repo any longer and hence it was deprecated and removed. You can check out old version to use the implementation as an example to work out your own solution.

**Comment by ysk24ok** [comment]
@RafalSkolasinski Thank you for your reply. But I think you may want to show that `seldon-request-logger` was deprecated in [the feedback metrics server example](https://github.com/SeldonIO/seldon-core/tree/v1.16.0/examples/feedback/feedback-metrics-server) as it's confusing.

**Comment by RafalSkolasinski** [comment]
Thanks, that's a good idea to add there a note indeed
