### ISSUE TITLE
Vowpal Wabbit

### ISSUE THREAD

**Issue by remidebette** [SeldonIO/seldon-core#4029]
Hi,

I see that Vowpal Wabbit format inference was supported in seldon-server.
https://github.com/SeldonIO/seldon-server

Is there a way to support it today with seldon core?
Thank you

**Comment by cliveseldon** [comment]
We don't presently support it although I imagine as people have [tried via Python](https://towardsdatascience.com/serving-vowpal-wabbit-models-on-kubernetes-de0ed968f3b0) it would be possible in either a custom python class.

**Comment by remidebette** [comment]
Thanks for your response.
To be able to have performance at scale, python is not a good option and one needs to run the library in [daemon mode](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Daemon-example).
It is a basic TCP socket and can respond to JSON or VW format today.

But I understand this native VW is not supported today
