### ISSUE TITLE
seldon-core error whe using with ambassador configuration

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [SeldonIO/seldon-core#4034]
## Describe the bug

I have been trying to deploy a micro service we developed to use with MLServer. We have been deploying it previously with `seldon-core` and we are using `ambassador` as well.

`seldon_deployment.yaml` file is given below:

```code
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: enmltranslation 
spec:
  protocol: kfserving
  annotations:
    project_name: enmltranslation
    deployment_version: v0.1.0
    seldon.io/rest-timeout: '60000'
    seldon.io/rest-connection-timeout: '60000'
    seldon.io/grpc-read-timeout: '60000'
    seldon.io/ambassador-config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: enmltrans_mapping_v0.1.0
      prefix: /microservices/nlp/enmltrans/v0/getpredictions
      service: enmltranslation-pod.default:8000
      rewrite: /nlp/enml/predictions

  predictors:
    - name: default
      graph:
        name: manglish-model 
        type: MODEL
      componentSpecs:
        - spec:
            containers:
              - name: manglish-model  
                image: manglishdummy:v0.1.0 
                ports:
                  - containerPort: 8080
                    name: http
                    protocol: TCP
                  - containerPort: 8081
                    name: grpc
                    protocol: TCP
```

When accessing the URL via ambassador we are 503 HTTP error indicating service is unavailable.

**Update:**

I was able to bring up a normal kubernetees deployment by following a [`deployment.yaml` similar to the one provided in tutorial.](https://mlserver.readthedocs.io/en/latest/examples/custom/README.html#deploying-our-custom-image) Yet ambassador support for MLServer seems not working at the moment.

## To reproduce

1. Download and install seldon-core v1.12.0 & Mlserver
2. Using configuration shared above, try deploying the application with above file

## Environment

* Cloud Provided: GKE
* Kubernetes Cluster Version: v1.20.15-gke.1000
* Deployed Seldon System Images:

```
          value: docker.io/seldonio/engine:1.12.0
          value: seldonio/seldon-core-executor:1.12.0
        image: seldonio/seldon-core-operator:1.12.0
```

Edit:

More context of issue can be found at: https://github.com/SeldonIO/MLServer/issues/549

**Comment by cliveseldon** [comment]
We don't support Ambassador V2 APIs at present. See https://github.com/SeldonIO/seldon-core/issues/3790.
Which version of Ambassaor have you installed?

**Comment by kurianbenoy-sentient** [comment]
@cliveseldon we have used Ambassador version 1.5.3

**Comment by cliveseldon** [comment]
Needs further investigation for Ambassador V2 APIs
