### ISSUE TITLE
[Feature Request] Add request-id to tracing tags

### ISSUE THREAD

**Issue by swearitagain** [SeldonIO/seldon-core#4050]
I hope to add request-id (or SeldonPUID) to tracing tags when seldon executor starts a span, so that I can correlate the request log with the trace information together.

Currently I can only get these information from tracing as shown in the figure, which is not enough to locate a certain request.
![image](https://user-images.githubusercontent.com/37062654/162873709-58993f67-99e8-49b5-9ab2-d4268c62c4e7.png)

**Comment by cliveseldon** [comment]
We would need to update the executor tracing integration to add extra metadata to the created spans.

**Comment by cliveseldon** [comment]
Please look at [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html) which has latest tracing and definitely includes request-id
