### ISSUE TITLE
clusterDomain can  written in configuration from seldondeployment controller

### ISSUE THREAD

**Issue by kbsonlong** [SeldonIO/seldon-core#4053]
Inside my cluster, the clusterDomain has been modified,  But the default clusterDomain is still displayed when viewing SeldonDeployment resources through describe.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/23339284/163130190-3ac0061b-e1cb-4c3d-b78d-52e44730432d.png">

https://github.com/SeldonIO/seldon-core/blob/50145a471f1ae3d68816c099f7301ece5626ac70/operator/controllers/seldondeployment_controller.go#L127

**Comment by cliveseldon** [comment]
Are you able to suggest a modification for this code to derive the current domain?

**Comment by cliveseldon** [comment]
Closing this. Please reach out if still an issue.
