### ISSUE TITLE
outputs shared with previous calls?

### ISSUE THREAD

**Issue by davidgr-pge** [SeldonIO/seldon-core#4056]
On a pipeline deployed using seldon version 1.7.0

On a selected handful of inputs, I have noticed that repeated calls to the same pipeline with same input returns different results. Strangely, the result seems to be taken from previous calls that used different inputs. Not sure if this is something anyone has seen before?

The pipeline is deterministic so the expected behavior is that a given call to the pipeline with identical input should always return identical results.

running on AWS EKS, kubernetes version 1.20

seldon images
engine:1.7.0
seldon-core-executor:1.7.0
seldon-core-operator:1.7.0

For context, the pipeline accepts JPG image inputs and produces predictions that include confidence values and bounding boxes (x1, x2, y1, y2). The pipeline includes 2 model components, and we're saving the output of each model in the meta tags so we can retrieve in the end. Looking through the logs indicates that that the model components do return a fixed output. It is the final component (the output transformer) where, for a select group of images, information in the tags appear to come from previous calls with other images.

As an example, here's the output of the second model component using one of said images (note that I've formatted the values for 'data' keys to look like a dict but it's actually a string with encoded values):

{
  'meta': {
    'tags': {
      'chook-hplate-det': {
        'predictions': {
          'data': '[
            {
              "class": "chook-hplate", "x1": 1711, "y1": 1969, "x2": 1742, "y2": 1998, "confidence": {"py/reduce": [{"py/function": "numpy.core.multiarray.scalar"}, {"py/tuple": [{"py/reduce": [{"py/type": "numpy.dtype"}, {"py/tuple": ["f4", false, true]}, {"py/tuple": [3, "<", null, null, null, -1, -1, 0]}]}, {"py/b64": "qWxWPw=="}]}]}
            }, 
            {
              "class": "chook-hplate", "x1": 2681, "y1": 1281, "x2": 2707, "y2": 1305, "confidence": {"py/reduce": [{"py/function": "numpy.core.multiarray.scalar"}, {"py/tuple": [{"py/id": 3}, {"py/b64": "IOUePw=="}]}]}
            },
            {
              "class": "chook-hplate", "x1": 3263, "y1": 1200, "x2": 3300, "y2": 1226, "confidence": {"py/reduce": [{"py/function": "numpy.core.multiarray.scalar"}, {"py/tuple": [{"py/id": 3}, {"py/b64": "fR0YPw=="}]}]}
            }
          ]'
          '_encoded': 1,
        },
        'type': 'MODEL',
        'version': '3.2.0'
      },
      'chook-hplate-cls': {
        'predictions': {
          'data': '[
            {
              "class": "over_thirty", "confidence": {"py/reduce": [{"py/function": "numpy.core.multiarray.scalar"}, {"py/tuple": [{"py/reduce": [{"py/type": "numpy.dtype"}, {"py/tuple": ["f4", false, true]}, {"py/tuple": [3, "<", null, null, null, -1, -1, 0]}]}, {"py/b64": "DJUQPg=="}]}]}, "x1": 1711, "x2": 1742, "y1": 1969, "y2": 1998
            }
          ]',
          '_encoded': 1
        },
        'type': 'MODEL',
        'version': '4.0.0'
      }
    }
  }
}

...and the final transformer output below. here, the values for bounding boxes (x1, y1, x2, y2) should be the same as above, but they actually correspond to outputs from previous calls with another image, and can change again if more calls are made to the pipeline with other images:

{
  'meta': {
    'tags': {
      'chook-hplate-det': {
        'predictions': [
          {
            'class': 'chook-hplate',
            'x1': 1923,
            'y1': 706,
            'x2': 2005,
            'y2': 834,
            'confidence': 0.9392454028129578
          }
        ],
        'type': 'MODEL',
        'version': '3.2.0'
      },
      'chook-hplate-cls': {
        'predictions': [
          {
            'class': 'over_thirty',
            'confidence': 0.1619611382484436,
            'x1': 1923,
            'x2': 2005,
            'y1': 706,
            'y2': 834
          }
        ],
        'type': 'MODEL',
        'version': '4.0.0'
      }
    }
  }
}

are there any related issues about this kind of behavior that are worth looking through?

**Comment by cliveseldon** [comment]
Are you able to test this with the latest release or create a small example that shows the behaviour?

**Comment by davidgr-pge** [comment]
it's difficult to reproduce, as the behavior seems to be intermittent. i'll monitor and see if this comes up with the latest version. i'll close for now and reopen if i see it with 1.13.1
