### ISSUE TITLE
Request & response HTTP header access

### ISSUE THREAD

**Issue by MattiaGallegati** [SeldonIO/seldon-core#4060]
In complex production environments it is not uncommon to have custom headers requirements during comunication between systems.
More in general it would be usefull if Seldon Core could:
1) Access the request headers from the code wrapper, this would enable features like header parsing for authentication, etc..
2) Create response with custom headers in order to be compliant to enteprise standards.
Is that possible right now?

**Comment by adriangonz** [comment]
Hey @MattiaGallegati ,

This should be already possible with Seldon's "V2" inference server (i.e. [MLServer](https://mlserver.readthedocs.io/en/latest/)). You can find some docs covering the manipulation of headers within custom runtimes [here](https://mlserver.readthedocs.io/en/latest/runtimes/custom.html#read-and-write-headers).

To leverage MLServer, you will also need to [enable the "V2" protocol](https://docs.seldon.io/projects/seldon-core/en/latest/graph/protocols.html#v2-protocol) within your `SeldonDeployment` manifests.

**Comment by MattiaGallegati** [comment]
Hi @adriangonz and thank you for your kind request.
Can I ask you to clarify a little bit more the adoption of V2 protocol?
I can see that both enable model serving in a similar way. What I cannot understand is how to fit Seldon Core V1 concepts into V2. For example I/O transformer, routers, custom metrics, etc.. that are enabled by Seldon Core language wrappers seems to be missing inside MLServer for V2. 
Adopting MLServer and V2 protocol means to lose some SeldonCore V1 features?
As a suggestion I think that the documentation must be clearer on these aspects.
Thank you

**Comment by adriangonz** [comment]
Hey @MattiaGallegati ,

Those are great points. 

It's currently possible to chain multiple models, which can be used as transformers (e.g. check this [example from the docs](https://docs.seldon.io/projects/seldon-core/en/latest/examples/transformers-v2-protocol.html)). However, routers and custom metrics are not supported yet. Work on custom metrics is already on the MLServer roadmap though.

If you want to stay with the V1 wrapper, it should be possible to read the request headers by importing Flask's request object directly (e.g. check this [SO answer](https://stackoverflow.com/a/29387151/5015573)). However, it's not possible to write headers back on the response, and adding that support is not currently on the roadmap.
