### ISSUE TITLE
Seldon-core helm chart doesn't work with kube 1.21+

### ISSUE THREAD

**Issue by karolmigo** [SeldonIO/seldon-core#4062]
## Describe the bug

We can't install Seldon-core from a helm chart.

## To reproduce
1. Add https://storage.googleapis.com/seldon-charts repo
2. Try to install seldon-core helm chart
3. Get an error message of the following:

```no matches for kind "Deployment" in version "apps/v1beta1"```

## Expected behaviour

Proper installation from helm.

## Environment
* Cloud Provider: AWS EKS
* Kubernetes Cluster Version 
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by cliveseldon** [comment]
Which version of Seldon Core are you trying to install?

**Comment by karolmigo** [comment]
it was 0.2.7

**Comment by karolmigo** [comment]
I tried latest as well

**Comment by axsaucedo** [comment]
We run all our integration tests on k8s 1.21, and we have been doing developemnt in 1.22 during the last few weeks so this is not correct. It seems you are installing an incorrect chart, you are using `seldon-core` but should be using `seldon-core-operator` as outlined in the docs. Please reopen if still an issue with the latest charts
