### ISSUE TITLE
Complex preprocessing and inference graph for model

### ISSUE THREAD

**Issue by MattiaGallegati** [SeldonIO/seldon-core#4088]
Hello everyone,
For my own production case I will have a model ready to answer production calls served possibily with Seldon Core.
When a prediction request arrives, before the actual prediction can be called, a complex data preprocessing has to be made on input data.
This preprocessing involves many Python scripts and the use of multiple models serialized in pkl format in order to complete the preprocessing task, for the sake of semplicity suppose that I want to use two different Scaler models on input data and other (hundreds) lines of code.

How do you suggest to break down this use case with Seldon?
My first hypothesis is to import all the code inside the seldon custom service (built via language wrapper) and also to load all the needed artifacts at the service startup (in __init__ function) connecting to a data storage.
Is this the correct way to go or I have to adopt another strategy, like building a complex inference graph serving each artifact as a Seldon service and make a preprocessing step for each step?
Thank you

**Comment by cliveseldon** [comment]
It depends how configurable and separately scalable you want the inference pipeline to be. You could have separate components with a routing component to decide where the request goes. To start with I would put everything in 1 node and then separate out as needed.

**Comment by cliveseldon** [comment]
In theory should be ok. It will depend on the latencies, startup times and what you want to do.
