### ISSUE TITLE
Example graph with pre-processor and post-processor outdated

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [SeldonIO/seldon-core#4090]
## Describe the bug

The example provided in graph for influencing with pre-processing and post-processing is [outdated](https://docs.seldon.io/projects/seldon-core/en/latest/graph/inference-graph.html#example-of-graph-with-pre-processor-and-post-processor)

**Issues:**

1. container_name given in list of predictors is in underscores and not able to create a pod(step_one, step_two, step_three)
2. docker images provided not able to be pulled

## To reproduce

Try out deploying with [yaml file](https://docs.seldon.io/projects/seldon-core/en/latest/graph/inference-graph.html#example-of-graph-with-pre-processor-and-post-processor)

**Comment by cliveseldon** [comment]
I think this is just for illustration but I agree is maybe confusing. This [notebook](https://docs.seldon.io/projects/seldon-core/en/latest/examples/graph-metadata.html) show various examples.
