### ISSUE TITLE
Custom Torch server models should not be loaded in the init function to the document

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4102]
Hi Seldon team,

I was following the link [Custom inference servers](https://docs.seldon.io/projects/seldon-core/en/latest/servers/custom.html) for making my own custom torch server. The document suggest to use the sklearn server as a blueprint example:

> As inspiration, you can see how the [SKLearn server](https://github.com/SeldonIO/seldon-core/blob/d84b97431c49602d25f6f5397ba540769ec695d9/servers/sklearnserver/sklearnserver/SKLearnServer.py#L16-L23) and the [other pre-packaged inference servers](https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html) handle these as part of their __init__() method:

In the skelearn server example the `load()` method is invoked in the `__init__` function, therefore I first implement my server as follows:
``` py 
class CascadeResnet(object):
    def __init__(self) -> None:
        super().__init__()
        # standard resnet image transformation
        self.transform = transforms.Compose([
            transforms.Resize(256),                    
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]                  
            )])
        self.loaded = False
        self.load()
        logger.info('Init function complete!')

    def load(self):
        logger.info('loading the ML models')
        self.device = torch.device(
            "cuda:0" if torch.cuda.is_available() else "cpu")
        resnet = torchvision.models.resnet101(pretrained=True)
        # <------------------- stucked here :( ------------------>
        resnet.eval()
        self.loaded = True
        logger.info('model loading complete!')

    def predict(self, X, features_names=None):
        if self.loaded == False:
            self.load()
        logger.info(f"Incoming input:\n{X}\nwas recieved!")
```
However, the code everytime got stucked in the mentioned line and I tried a lot of stuff to find out what the bug is (e.g. changing the env workers, checking downloaded model user access privilages etc) and it only worked on the Falsk without Gunicorn. Finally by reading https://github.com/SeldonIO/seldon-core/issues/2680 which wasn't directly related but by a back to back comparison with torch code there I noticed that `load()` should not be called in the `__init__()` function and simply commenting the loading line in the `__init__()`. I'm still unsure what is the reason but I think it has to do something with the multi-process loading of the model in Gunicorn.
Since PyTorch is a widely used library could you please add this to the documentation and the underlying cause so it could avoid confusion for future users? Specially since I guess most of the users will follow the sklearn server pointed out by the [Custom inference servers](https://docs.seldon.io/projects/seldon-core/en/latest/servers/custom.html) which calls the load on the init. I think the [Gunicorn and load](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load) could be expanded to include a warning of not using it in the init because of ... and also add the torch to tensorflow. I was going to add it in a pull request but I am unsure about the reason of why this problem is happening.

Thanks!

**Comment by cliveseldon** [comment]
We do have a section in the [docs](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load) for this. If you think there could be extra docs we would welcome further updates to other sections of the docs to point to this. Will close now but thanks for the details description and perhaps you could add a PR to update the docs?
