### ISSUE TITLE
s2i-java-jni-runtime:0.5.1 security vulnerabilities

### ISSUE THREAD

**Issue by indranilr** [SeldonIO/seldon-core#4103]
We have been using s2i-java-jni-runtime:0.5.1 and builder image to create java wrapper based model images in our project. 
Recent security scans on the model image using [Grype ](https://github.com/anchore/grype)has revealed several vulnerabilities. Below is a summary.

- Critical 23
- High 195
- Medium 564
- Low 282 

Most of the VAs seem to originate from the below paths 

`/var/lib/rpm/Packages`
`/opt/app-root/src/jboss/.m2/repository`
`/usr/lib/node_modules/npm`
`/opt/app-root/src/python/.tox`
`/opt/app-root/lib/python3.6`

Please advise if any new s2i jni runtime image needs to be used to mitigate these issues or how we can build our own runtime image with alternative base os, python package etc. I can provide the detailed list of CVEs on request ( attaching here did not seem a good idea).

**Comment by cliveseldon** [comment]
We are looking for external support for helping with this s2i wrapper to update it.

**Comment by cliveseldon** [comment]
We will handle this in [MLServer](https://github.com/SeldonIO/MLServer)
