### ISSUE TITLE
Helm installing Grafana & Prometheus not compatible with kubectl v1.22.5

### ISSUE THREAD

**Issue by Al4DIN** [SeldonIO/seldon-core#4106]
Hello, I've the same issue while trying to install seldon-analytics (Grafana & Prometheus) 
This is my kubectl version
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```
And I'm using `Kind`, and this is my version `kind v0.12.0 go1.17.8 windows/amd64`

This is the error :
So except downgrading my kubectl version I can't fix it?

_Originally posted by @Al4DIN in https://github.com/SeldonIO/seldon-core/issues/3618#issuecomment-1131701984_

**Comment by cliveseldon** [comment]
You should look at our [updated docs on prometheus](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html).
