### ISSUE TITLE
Kaniko Integration

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#411]
Allow users to use [Kaniko](https://github.com/GoogleContainerTools/kaniko) to turn their source into images for management by Seldon Core.

**Comment by cliveseldon** [comment]
Add documentation with example in future. Closing for now,

**Comment by ryandawsonuk** [comment]
We could refer to https://github.com/kubeflow/pipelines/blob/master/samples/contrib/seldon/mnist_tf.py#L62 or https://github.com/kubeflow/example-seldon/blob/95e386b344e17158455353ed61135230b5fa8838/workflows/training-r-mnist-workflow.yaml#L58
