### ISSUE TITLE
why my http request is faster than grpc request, 2000items  and each item 555features, http request takes 500ms ,but grpc request takes 8000ms, too large to accept 

### ISSUE THREAD

**Issue by HubSKY** [SeldonIO/seldon-core#4128]
## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Can you provide more details on your yaml and model you are using so we can understand more the conext?

**Comment by cliveseldon** [comment]
Closing for now - will reopen if more details provied
