### ISSUE TITLE
Getting (s3)storage not recognized as well as credentials error, while deploying a simple deployment with seldon

### ISSUE THREAD

**Issue by Anujay-Saraf** [SeldonIO/seldon-core#4129]
Hi Seldon Team,
I am facing s3 storage not recognize error message as a issue, while accessing the same via seldon deployment along with Storage feature of seldon, which is using private s3 bucket, and even while accessing it boto3 we are facing credentials error on the same EKS cluster, where both deployments are using wrapped docker image contains instructions of wrapper file and trying to pull a simple model file from s3 storage.

Where-else, when we are trying to download or access the file using python boto3 , that works smoothly.

Thus @seldon-team please suggest working strategy or help us with this bug.

**Comment by axsaucedo** [comment]
You have to make sure that your storageInitialiser secret is correctly configured and referenced, providing the relevant configuration to the initContainer, there is more information here https://docs.seldon.io/projects/seldon-core/en/latest/examples/rclone-upgrade.html and you can find end to end examples in the documentation - however because we use rclone as the storage initialiser, the best documentation would be on rclone site itself

**Comment by Anujay-Saraf** [comment]
This example talks about two things, rclone and minio storage, where else we are not having any association to use Minio as of today but we want to directly access the s3 bucket and download the artifacts from it, inside the containerized image which is deployed with seldon deployment as a custom inference server.

Request to help in those direction.

**Comment by axsaucedo** [comment]
Ok I see, unfortunately custom inference servers do not work with initContainers, so you would need a prepackaged server in order for this to work correctly as prepackaged server and download with initContainer. If you indeed follow that approach, you  would need to configure the rclone secret with the values required for the s3 bucket as suggested in the docs.

**Comment by axsaucedo** [comment]
@Anujay-Saraf closing this issue given the custom inference servers point, but it seems rclone documentation should fix - reopen if still facing issues after testing as suggested
