### ISSUE TITLE
Splunk integration for application logs

### ISSUE THREAD

**Issue by MattiaGallegati** [SeldonIO/seldon-core#4131]
Hello everyone,
I'm trying to integrate log sampling to a Splunk service. The integration happens with the use of a Splunk agent inside/outside the target pod.
With Seldon I cannot find any clear reference on how this kind of pattern must be implemented, can I add my custom container inside the model's POD? What I actually need to sample in order to get the log out?
Can you please clarify how application log sampling must be implemented?

**Comment by axsaucedo** [comment]
If you are trying to log only requests and responses you can do so with request logging https://docs.seldon.io/projects/seldon-core/en/latest/examples/payload_logging.html

**Comment by MattiaGallegati** [comment]
@axsaucedo nope.
My intent is collect the logs from the application, if I log.info("something") I want to be able to collect these logs and send them to Splunk.
https://docs.seldon.io/projects/seldon-core/en/latest/analytics/log_level.html
Here you explain that logs are stored in JSON format but I have no evidence  of where to find them and what is the correct pattern in order to integrate a custom agent in order to collect them.

In the case of predictions request/response to Splunk (which will be the next use case form me) if I did not misenderstood I can collect them using FluentD and send them to Splunk.
For both cases no example is provided.

Can you give some more details on these aspects?
Thank you.

**Comment by axsaucedo** [comment]
ok I see @MattiaGallegati - for now the only way we have been able to do this is by using a tool like fluentd to push the logs into elasticsearch. I would suggest exploring something similar to that for splunk. Closing as it seems this is more as a fluentd/splunk general container logs question as opposed to a seldon core specific one.
