### ISSUE TITLE
Investigate Edge/IOT deployments

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#414]
[Azure](https://azure.microsoft.com/en-gb/blog/manage-azure-iot-edge-deployments-with-kubernetes/) has the most developed options for running deployments at the edge on k8s.

Can a SeldonDeployment be run on [IOT Hub](https://azure.microsoft.com/en-gb/services/iot-hub/?&OCID=AID719823_SEM_gcOTmaKh&lnkd=Google_Azure_Brand&dclid=CKu8veLOkOACFZkFBgAd_fgBOw)?

**Comment by cliveseldon** [comment]
Close. Can reopen if there of community interest.

**Comment by josefkorbel** [comment]
Hello, we are just choosing the right framework, and seldon-core seems to be the best fit for us.
We are deploying models on cloud and on the edge, are there any informations regarding this in seldon-core ?

**Comment by cliveseldon** [comment]
We have not done any further work on edge deployments. We'd love to chat further on your use case. Feel free to email or slack me or comment further here.
