### ISSUE TITLE
Add imagePullSecret to Helm values

### ISSUE THREAD

**Issue by danielsteman** [SeldonIO/seldon-core#4140]
We are trying to deploy Seldon Core Operator with Helm and we want to use images from a private registry. However, we can't pass the secret name of our registry to the Helm values, like we do for other Helm deployments. We would expect to find a key like `imagePullSecret` in the root of `seldon-core-operator/values.yaml` which would be used to authenticate to the private registry, in case for example `executor.image.registry` is something private.

**Comment by axsaucedo** [comment]
Thank you for raising this question @danielsteman - our workaround/suggestion would be to add a default imagePullSecrets through the service account mapping capabilities of Kubernetes, which will make sure all resources using that respective service account would be using the default parameters provided. You can find more details here https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Comment by RafalSkolasinski** [comment]
SeldonDeployment pods will by default use SA named `default`. This simple command will set the image pull secrets for them with for example
```bash
kubectl patch sa default -n seldon -p '"imagePullSecrets": [{"name": "seldon-docker-secret" }]'
```

For Seldon Core Operator this will be for example
```bash
kubectl patch sa seldon-manager -n seldon-system -p '"imagePullSecrets": [{"name": "seldon-docker-secret" }]'
```

**Comment by axsaucedo** [comment]
@danielsteman does the workaround suggestsions address the issue you initially provided?

**Comment by danielsteman** [comment]
@axsaucedo thanks for the response, this solves my issue. I couldn't find this anywhere in the docs though. Did I overlook something? Otherwise I can add it with a PR.
