### ISSUE TITLE
How to increase the shm (shared memory) size of docker container, build using seldon core Dockerfile

### ISSUE THREAD

**Issue by divyadilip91** [SeldonIO/seldon-core#4150]
## Describe the bug
@cliveseldon @axsaucedo @RafalSkolasinski 
Hi, I have deployed a microservice wrapped using Seldon Core Dockerfile. This docker image has been deployed on Kubernetes engine. When I  test the microservice using a very large input, I receive 500 error from the microservice and from the logs it shows 
**Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).**
How do we solve this issue. The solutions given online say that the docker run command should have the shm-size variable to increase the shm size, but confused on how to do this using docker file used for seldon core. Would really appreciate your help.

* Cloud Provider:GKE, 
* Kubernetes Cluster Version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:42:07Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

* Deployed Seldon System Images: Seldon core 1.1.0

**Comment by axsaucedo** [comment]
Unfortunately this sounds more like a docker question than specific to seldon core so may be better off asking on slack community to see if any members have any insights, or better perhaps asking in the docker forums/channels
