### ISSUE TITLE
How we can make a sync in between S3 bucket and Init container if deployment is already present for one application

### ISSUE THREAD

**Issue by Anujay-Saraf** [SeldonIO/seldon-core#4151]
Hey Team,

To make a automated pipeline in between s3 and container for having a good sync ups, which is to enable the deployment to get the updated artifacts automatically from the bucket and keep running the predictions with updated/re-trained model.

Please suggest a possible to strategically implement the same without restarting/deploying the deployment itself.

Regards,
Anujay

**Comment by cliveseldon** [comment]
Usually in Kubernetes you would want to make a clear separation between versions by changing the YAML spec so you can then roll back if there are issues. If you bypass Kubernetes declarative infratstructure its harder to manage.

However, servers such as [Triton can POLL](https://github.com/triton-inference-server/server/blob/main/docs/model_management.md) the model repository for changes. So if you used a PVC and had some other process update files in the repo you could do some of what you want. A similar technique could be done in custom python code.
