### ISSUE TITLE
HTTP metrics

### ISSUE THREAD

**Issue by kbcasagrande** [SeldonIO/seldon-core#4154]
I'd like to suggest seldon-core to expose metrics regarding the HTTP return codes for incoming requests to the executor, similarly to the ones exposed when using prometheus_flask_exporter for flask projects(histogram with labels):

```
http_request_duration_seconds_bucket{le="xxx",method="HTTP_METHOD",path="PATH",status="INT_HTTP_STATUS_CODE"} VALUE
http_request_duration_seconds_count{method="HTTP_METHOD",path="PATH",status="INT_HTTP_STATUS_CODE"} VALUE
http_request_duration_seconds_sum{method="HTTP_METHOD",path="PATH",status="INT_HTTP_STATUS_CODE"} VALUE
http_request_duration_seconds_created{method="HTTP_METHOD",path="PATH",status="INT_HTTP_STATUS_CODE"} VALUE
```

The context of it is the need to track metrics about errors/exceptions that might happen during the inference. 
It seems more efficient to track it generically based on the HTTP return code than creating a counter metric to track only the exceptions.

**Comment by axsaucedo** [comment]
This sounds reasonable, although the implementation may require further thinking as we'd need to collect the return codes and pass them to the prometheus metrics utilities as currently metrics are mostly automatically collected, we can add to backlog and review if this is something we can include or we can consider for our current refactor explorations

**Comment by cliveseldon** [comment]
This should be happening will close now please try with latest and confirm its an issue
