### ISSUE TITLE
Extending MLFlowServer to support running predict_proba on Classifier

### ISSUE THREAD

**Issue by hjilke** [SeldonIO/seldon-core#4159]
Hi Everyone,

I recently got started using Seldon & really like it!

I heavily use MLFlow & hence my models are packaged using the MLFlow format.
For some of the models I need to run _predict_proba_, which is currently not support by the MLFlowServer. As a work around, I wrote my own model server, e.g. [here](https://github.com/hjilke/seldon-mlflow-custom-server/blob/master/mlflowserver/MLFlowServer.py).

Are there any plans to add support for e.g. _predict_proba_ with the MLFlowServer?

**Comment by cliveseldon** [comment]
HI. Moving forward we are using [MLServer](https://github.com/SeldonIO/mlserver) for python based models including MLServer. You need to use thev2 protocol but it should support your MLFlow needs better as its already integrated into MLFlow.

See also [here](https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#v2-protocol)

**Comment by cliveseldon** [comment]
Will close but feel free to comment if not clear.

**Comment by hjilke** [comment]
@cliveseldon Looking at the [MLServe](https://github.com/SeldonIO/MLServer/tree/master/runtimes/mlflow/mlserver_mlflow) implementation for MLFlow I do not see how predict_prob is supported.

What am I missing.
