### ISSUE TITLE
Nginx-Ingress Integration

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#416]
Allow [Nginx-ingress](https://github.com/kubernetes/ingress-nginx)  as an alternative ingress for Seldon Core.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by senthilrch** [comment]
@cliveseldon : this is a much-needed feature in seldon, given nginx ingress controller is widely used.

**Comment by senthilrch** [comment]
Issue #1778

**Comment by cliveseldon** [comment]
Thanks @senthilrch 

Its certainly something we want to look at. Are there any nginx users who would care to comment on any of the complexities or challenges in integrating with it?

**Comment by ryandawsonuk** [comment]
We're looking at how we can expand our support in the most general way possible. Hoping to avoid having lots of different implementations for different gateways. See [discussion on the SMI-SPEC project](https://github.com/servicemeshinterface/smi-spec/issues/123#issuecomment-741713062)

**Comment by cliveseldon** [comment]
[v2](https://docs.seldon.io/projects/seldon-core/en/v2/) is agnostic to service meshes and has a single SVC entrypoint to allow easy integration. Please try with v2.
