### ISSUE TITLE
How to pass local mlflow model path in ModelUri in Seldon yaml file?

### ISSUE THREAD

**Issue by nitesh31mishra** [SeldonIO/seldon-core#4171]
How to pass the local mlflow artifact model in ModelUri of Seldon YAML file. I am using my local file storage for storing my artifact folder and not S3 or GS.

This is the general YAML config for passing artifact model path store on s3/gs 

> apiVersion: machinelearning.seldon.io/v1alpha2
> kind: SeldonDeployment
> metadata:
>   name: mlflow
> spec:
>   protocol: v2  # Activate the v2 protocol
>   name: wines
>   predictors:
>     - graph:
>         children: []
>         implementation: MLFLOW_SERVER
>         modelUri: gs://seldon-models/test/elasticnet_wine
>         name: classifier
>       name: default
>       replicas: 1

I am trying to pass the path of my local artifact folder here like below: 

> apiVersion: machinelearning.seldon.io/v1alpha2
> kind: SeldonDeployment
> metadata:
>   name: mlflow
> spec:
>   protocol: v2  # Activate the v2 protocol
>   name: wines
>   predictors:
>     - graph:
>         children: []
>         implementation: MLFLOW_SERVER
>         modelUri: home/ubuntu/file-store/mlruns/elastic_wine
>         name: classifier
>       name: default
>       replicas: 1
      
 But while running the `kubectl apply -f serving.yaml` the pod is getting created but gives an error - Back-off restarting failed error.

**Comment by axsaucedo** [comment]
You cannot use local storage, but you can use something like a PVC or minio, the latter is probably the best option for you, you can follow this example https://docs.seldon.io/projects/seldon-core/en/latest/examples/iris_explainer_poetry.html
