### ISSUE TITLE
Resuse the same image as different types of components

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#418]
Currently one needs to specify the component type (Model, Transformer etc.) at the time of wrapping with s2i which means that components which can be used in several different ways end up having to be wrapped multiple times resulting in several images. We should move towards delaying the decision about what type of component it is until deployment time so that one image can be reused for multiple types of components.

An  example of this would be an outlier detector which can be used either as a model in its own right or as an outlier detector on top of a primary model in a deployment (link to example to follow).

**Comment by cliveseldon** [comment]
This should be addressed in V2 and also via MLServer custom integrations.
