### ISSUE TITLE
CRD deployment graph specification for flexible deployments

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#419]
Currently the [Seldon deployment CRD](https://github.com/SeldonIO/seldon-core/blob/c2a57cf57b5cae72e94f3ade0d0889ebb3ebd3f7/proto/seldon_deployment.proto) defines the deployment graph as a nested parent-children structure. In some cases this representation of a directed acyclic graph (DAG) could be limiting to compose flexible deployment manifests programmatically. It might be better to use an alternative graph encoding, e.g. a flat list of graph components `{"graph" : [<component1>,component2>...]}` where each component has a list specifying its upstream nodes `{... "upstream":[<component name1>,<component name2>..]}` (similar to [Apache Airflow](https://airflow.apache.org/tutorial.html#example-pipeline-definition)).

Other representations of DAGs could also be useful, we would like to know if the community has any thoughts on what the best representation offering maximum flexibility could be.

**Comment by nareshganesan** [comment]
+1

Argo also has a similar way of representing DAG. [here](https://github.com/argoproj/argo/blob/master/examples/dag-nested.yaml)

**Comment by cliveseldon** [comment]
We are working on https://github.com/SeldonIO/mlgraph for this.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Closing as this is covered in general work towards a new graph structure.
