### ISSUE TITLE
Session Affinity

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#420]
We need to ensure the same container are used for each step in a single API call. This will be the case if all parts of the SeldonDeployment are defined in the same PodTemplateSpec but if they are split then this will not be the case.

Solution : Make all internal services have SessionAffinity ClientIP.

For external API calls for more advanced stateful services such as reinforcement learning and other advanced use cases it may be required to ensure multiple API requests go to same set of components. 

Solution: Document Session Affinity for external Ingress. Ambassador provides Envoy V1 ClientIP Hashes and will have more powerful mechanisms when they implement v2 of Envoy: see [here](https://github.com/datawire/ambassador/issues/422). Other Ingress solutions would have other ways of doing this.

Proposed work would be to:

 1. Add sessionAfinity IP to Services created
 1. Document Ambassador usage (now and future)
 1. Create an example

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
possible in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/) experiments
