### ISSUE TITLE
Add ONNX support without using Triton

### ISSUE THREAD

**Issue by SergeyShk** [SeldonIO/seldon-core#4201]
Hi. Is it possible to use ONNX models like torch models, i.e. without Triton?

**Comment by cliveseldon** [comment]
Can you specify why you need this? MLServer does have support at present for HuggingFace models which use the onnx_runtime. @adriangonz

**Comment by SergeyShk** [comment]
At this moment I use fine-tuned PyTorch model wrapped in SeldonModel and then run it like that: 
seldon-core-microservice service.seldon.SeldonModel --service-type MODEL

I tried just replace PyTorch model by ONNX, but the service failed to start.

**Comment by SergeyShk** [comment]
Or maybe you could provide some example of using MLFlow + onnx_runtime model?

**Comment by SergeyShk** [comment]
Just to clarify my case. Here is the Seldon class:
```python
class SeldonModel:
    model_error_handler = flask.Blueprint("error_handlers", __name__)

    @model_error_handler.app_errorhandler(ClassifierError)
    def handle_custom_error(self):
        response = flask.jsonify(self.to_dict())
        response.status_code = self.status_code
        return response

    def __init__(self):
        self.model = Classifier() # PyTorch model is being initialized here

    def predict(self, features, names=None, meta=None) -> Dict[str, Any]:
        prediction = self.model.predict(features["text"])
        return {"class": prediction.class, "confidence": prediction.confidence}

    def init_metadata(self):
        return {}
```

Then I run:

```bash
seldon-core-microservice service.seldon.SeldonModel --service-type MODEL
```

With PyTorch model it works (but only on seldon-core 0.9.0, I don't why). With ONNX model initialization step fails.

**Comment by SergeyShk** [comment]
Kind of reminder

**Comment by SergeyShk** [comment]
What do you mean by "building python wrapped model"?
Here:

`self.model = Classifier()`

I just run:

`AutoModelForSequenceClassification.from_pretrained(model, config=self.config)`

**Comment by cliveseldon** [comment]
Can you tell/show us the error?

**Comment by SergeyShk** [comment]
When I run:

```bash
seldon-core-microservice service.seldon.SeldonModel --service-type MODEL
```

 I get this error:

```bash
File "/Users/testuser/Library/Caches/pypoetry/virtualenvs/classifier-HzMM1FG7-py3.9/bin/seldon-core-microservice", line 8, in <module>
    sys.exit(main())
  File "/Users/testuser/Library/Caches/pypoetry/virtualenvs/classifier-HzMM1FG7-py3.9/lib/python3.9/site-packages/seldon_core/microservice.py", line 497, in main
    start_servers(server1_func, server2_func, server3_func, metrics_server_func)
  File "/Users/testuser/Library/Caches/pypoetry/virtualenvs/classifier-HzMM1FG7-py3.9/lib/python3.9/site-packages/seldon_core/microservice.py", line 64, in start_servers
    p2.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in init
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in init
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.grpc_prediction_server'
```

**Comment by adriangonz** [comment]
Hey @SergeyShk ,

This doesn't seem caused by ONNX, but by running the `seldon-core-microservice` CLI in MacOS. Unfortunately, there's a known issue which means the `seldon-core-microservice` CLI won't start there. You can find more info in this existing issue:

https://github.com/SeldonIO/seldon-core/issues/3697

We do not develop on Apple machines so it is difficult for us to even replicate the issue. The `seldon-core-microservice` CLI is meant to be run as a pod in a K8s cluster, where it works without issues.

@SergeyShk  can you confirm whether the PyTorch example you mentioned was run on a Linux or MacOS environment?

**Comment by SergeyShk** [comment]
Hi @adriangonz . Yes, it was run on a MacOS machine. I managed to run it inside a Linux docker container, but the following issue occurred.
Here:

```python
return {"intent": prediction.intent, "confidence": prediction.confidence}
```

confidence is a float number. It wasn't a problem when I used a PyTorch model, but when I tried ONNX I got this error:

`Object of type float32 is not JSON serializable`

**Comment by SergeyShk** [comment]
And can I replace service-type to TRANSFORMER in my case? What's the difference from MODEL?

**Comment by adriangonz** [comment]
Thanks for confirming that point @SergeyShk. In that case, since the issue of adding support for Mac is already consolidated on the other one (#3697), I'll close down this issue.
