### ISSUE TITLE
Metrics provided by Seldon core for monitoring ML models' performance in production

### ISSUE THREAD

**Issue by that-rahul-guy** [SeldonIO/seldon-core#4219]
Hello,
For monitoring the **ml models in production** (deployed via seldon core) I came across the following link which talks about integration with Prometheus: https://docs.seldon.io/projects/seldon-core/en/latest/analytics/analytics.html
As far as I understood seldon will expose the metrics on an endpoint `/metrics` and Prometheus will collect them and then we can use Grafana for further visualizations..

I want to understand **_what all metrics will the be readily available_** in `/metrics` for observing the model performance in production.
Is there a list which mentions all the metrics being calculated and exposed by seldon at `/metrics` endpoint?
Also is there any way I can add custom metrics as per requirements?

Please guide me to some resources (if any) or comment below.

Thanks.

**Comment by cliveseldon** [comment]
You can create custom metrics as outlined [here](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_wrapping_docker.html#custom-metrics). Does this fulfil your requirements?

**Comment by cliveseldon** [comment]
closing for now - please also look at [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html)
