### ISSUE TITLE
seldon-core-s2i-python3 is not "openshift ready"

### ISSUE THREAD

**Issue by vincentclaes** [SeldonIO/seldon-core#422]
since this image uses s2i we used it for our continuous build process on our openshift container platform. the existing image does not work on openshift but below you can find the adapted version that does work.
```
# we need this docker file because the original seldon-core
# cannot be handled by openshift. we made the necessary changes here
FROM seldonio/seldon-core-s2i-python3:0.4

USER root
RUN chgrp -R 0 /microservice /usr/local/lib/python3.6 && \
    chmod -R gu+rwX /microservice /usr/local/lib/python3.6

USER 1001
```

**Comment by cliveseldon** [comment]
If this is compatible can you do a PR to modify the existing or do we think an Openshift specific container is needed?

**Comment by vincentclaes** [comment]
@cliveseldon maybe a silly question but where are these dockerfiles stored?

**Comment by cliveseldon** [comment]
They are [here](https://github.com/SeldonIO/seldon-core/tree/master/wrappers/s2i/python)
They are at 0.5-SNAPSHOT so we can leave at that and then release 0.5 when ready. There is a discussion that we should change to be in line with core release but we can stick with how it is for now.

**Comment by axsaucedo** [comment]
This has now been resolved, and we're in the final stages of certifying the operators. If you wish to use the images you can find them here:
* https://github.com/SeldonIO/seldon-core/tree/master/engine/custom-images
* https://github.com/SeldonIO/seldon-operator/tree/master/custom-images
