### ISSUE TITLE
Not getting Prediction when passing the json to mymodel through seldon batch but when directly passing getting the exact prediction. Could you please suggest.

### ISSUE THREAD

**Issue by premaprakash** [SeldonIO/seldon-core#4223]
**Direct Input to my model :** 
{
    "utterances": [
        "This is prem",
        "This will help me",
        "Its very good experience to be here seldon IO",
        "Thank you"
    ]
}

**Model Response :** 
-------------------
{
    "jsonResponse": {
        "modelPrediction": {
            "firstHalfSentimentDist": {
                "Negative": 0,
                "Positive": 3,
                "Neutral": 1
            },
            "commonFirsrt": "Positive",
            "commonSecond": "Neutral",
            "secondHalfSentimentDist": {
                "Negative": 0,
                "Positive": 3,
                "Neutral": 1
            },
            "totalutterance": 11
        }
    }
}
------------------------------
**Seldon taking the above json input in the below form in single line  👍 --**
{"utterances": ["This is prem", "This will help me", "Its very good experience to be here seldon IO", "Thank you" ]}

**error response from myModel - 👍** 
"utter_list = utter_list['utterances']\nKeyerror : 'utterances'\n"

Kindly advice me on this . FYI I am executing this from command line with the following command ,

**seldon-batch-processor -d my-model -n my-namespace -a json -i  mypath/input.txt -o mypath/ouput.txt -l debug -h myhost.com --use-ssl TRUE --ssl-verify false**

@axsaucedo

**Comment by premaprakash** [comment]
@Alejandro Saucedo

**Comment by axsaucedo** [comment]
@premaprakash you have to send your request following the SeldonMessage schema, so this would be:

```
{
   "jsonData": {"utterances": ["This is prem", "This will help me", "Its very good experience to be here seldon IO", "Thank you" ]}
}
```

**Comment by axsaucedo** [comment]
Closing for now as it seems to be specific to the schema, please reopen with further information if still an issue
