### ISSUE TITLE
How to connect to Azure blob storage for Model files

### ISSUE THREAD

**Issue by sahilangra-TA** [SeldonIO/seldon-core#4225]
I have my manifest file which points to my Blob storage container that has my "model.joblib" file. When I pass its URL to the manifest file, my pod goes uninitialized with the message "Back-off restarting failed container". I understand maybe I am missing something, but the docs don't seem to be talking anything about Azure blob other than _"For these servers you only need the location of the saved model in a local filestore, Google bucket, S3 bucket, azure or minio."_ which I seem to have provided. Can anyone perhaps guide me into a direction I should be looking in?

My manifest : 
![image](https://user-images.githubusercontent.com/106382360/180662025-aa6b8842-443d-48f9-b2a8-64d586d68169.png)

Status of my Pod:
![image](https://user-images.githubusercontent.com/106382360/180662060-471315ca-b759-40f2-8270-d2c6c36cc93a.png)

P.S : Yes, I am new to Seldon and kubernetes!

**Comment by Yuvraj2300** [comment]
hey @sahilangra-TA I am in the same boat - I have .joblib files on a private ABS container.

Would be very kind of you give me pointers to this. TIA :)

**Comment by agrski** [comment]
Hi @Yuvraj2300,

This is probably about needing the right credentials to access private buckets.  Please see [this section](https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html#handling-credentials) in the Seldon Core v1 documentation for details.
The short summary is that Rclone is the default storage initializer and you need to create a Kubernetes `secret` containing the right credentials for Rclone to use to access Azure (or any other compatible bucket store).

**Comment by Yuvraj2300** [comment]
@agrski  Thanks, got it.  ☑️
