### ISSUE TITLE
seldondeployment is not considering the parameters present under securitycontex parallel to volumes under pod spec

### ISSUE THREAD

**Issue by poornachandratejasvi** [SeldonIO/seldon-core#4229]
Trying to deploy SeldonDeployment by adding the below section parallel to volumes, but I'm able to observe that fsgroup is not getting considered, but always runAsUser: 8888 is getting overwriten.

```
securityContext:
          fsGroup: 2014

```
Please find the deployment file in the attachment (abclad.txt) . [abclad.txt](https://github.com/SeldonIO/seldon-core/files/9188640/abclad.txt)

find the output of kubectl get pods <modelpod> -o yaml (get-pod.txt)  
[get_pods.txt](https://github.com/SeldonIO/seldon-core/files/9188667/get_pods.txt)

Seldon core operator version: 1.13.1

**Comment by poornachandratejasvi** [comment]
HI , any update on the issue ?

**Comment by cliveseldon** [comment]
Please try [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html) where you have full control of the ServerConfig resource to customize the Server stateful set created.

**Comment by poornachandratejasvi** [comment]
is there a way if out by using v1  ?

**Comment by ShaswataJash** [comment]
As part of Seldon Core 1.16, this issue has been marked as done. Can we able to get the pull-request number through which it is marked as done?

**Comment by RafalSkolasinski** [comment]
It's marked as done as it was done in v2.
