### ISSUE TITLE
Mlflow-custom-transformation

### ISSUE THREAD

**Issue by Jaidatt** [SeldonIO/seldon-core#4233]
We are trying to serve mlflow models via seldon core for this it is using this python file for the prediction of mlflow model https://github.com/SeldonIO/seldon-core/blob/d84b97431c49602d25f6f5397ba540769ec695d9/servers/mlflowserver/mlflowserver/MLFlowServer.py ,
Is there any way to provide custom python pre/post transformation function for the mlflow model to serve it on seldon-core.

**Comment by cliveseldon** [comment]
You can add input and output transformers to the inference graph. Have you tried this?

**Comment by cliveseldon** [comment]
Closing
