### ISSUE TITLE
Default to rclone storage initializer for OpenShift releases

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#4246]
1. make [components/storage-initializer](https://github.com/SeldonIO/seldon-core/tree/master/components/storage-initializer) to be just re-tagged [components/rclone-storage-initializer](https://github.com/SeldonIO/seldon-core/tree/master/components/rclone-storage-initializer)
2. change default in https://github.com/SeldonIO/seldon-core/blob/master/operator/config/manager/configmap.yaml#L95

**Comment by RafalSkolasinski** [comment]
This is in progress and will actually be included in 1.14.1

**Comment by axsaucedo** [comment]
@RafalSkolasinski was this done or should we move to 1.16?

**Comment by RafalSkolasinski** [comment]
Yes, it's done. We can close it.

**Comment by RafalSkolasinski** [comment]
https://docs.seldon.io/projects/seldon-core/en/latest/reference/upgrading.html#openshift-default-storage-initializer
