### ISSUE TITLE
Revamp how the engine handles metadata

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#426]
Currently the engine merges the metadata between components based on whatever metadata the new component adds: https://github.com/SeldonIO/seldon-core/blob/cbbcc6b41ef2cd9ccfd94c21a7784ee4a1758876/engine/src/main/java/io/seldon/engine/predictors/PredictiveUnitBean.java#L350-L364

A drawback of this is that some metadata can get lost, e.g. the engine currently doesn't pass the puid along (#424 fixes this). A better way would be only to add to the metadata so nothing is lost in the flow.

**Comment by cliveseldon** [comment]
Close. Can reopen if we decide to revamp how metadata is handled in general on a per-request basis.
