### ISSUE TITLE
multi model graphs request propagation

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4260]
Follow up to [Slack channel question](https://seldondev.slack.com/archives/C03DQFTFXMX/p1659621260141289) with @adriangonz . As part of a project, I have a set of interconnected nodes (each node is a Triton server) in which each of them has a number of models (with the same goal) and I want each request to pass through a different set of models. For example, I want request 1 to pass through model 1 in node 1 -> model 1 in node 2 -> model 1 in node 3, and another path R2. The path for each request is determined prior to run the request and can be possibly sent through metadata to the Triton servers and Seldon core graph.

![181790732-dcbab48e-2658-426c-a409-a7fdf5a119e9 (2)](https://user-images.githubusercontent.com/6298780/183110105-d9f4d2b9-b5fe-4da6-b8de-a8ea510cda81.png)

P.S A possible use case is that I have requests with different latency-accuracy requirements and I want to choose the path of the request based on that.

**Comment by cliveseldon** [comment]
In general you could achieve this by 

1.  Extending your graph to have a Router before each item. Although this is a challenge with Triton as that is using the V2 protocol.
2. Utilize Triton's [business logic scripting](https://github.com/triton-inference-server/python_backend#business-logic-scripting)  to call the models as needed

In general we will be investigating these use cases in v2 of our APIs.

**Comment by cliveseldon** [comment]
Please test in v2
