### ISSUE TITLE
Back-off restarting failed container

### ISSUE THREAD

**Issue by RishabhPandit-00** [SeldonIO/seldon-core#4285]
## Describe the bug

I  am trying to deploy mlflow model using seldon core . But getting Back-off restarting failed container error during implemetation.
@adriangonz can you help me this ?...

## To reproduce
Using mlflow manifest already in mlflow-talk (https://github.com/adriangonz/mlflow-talk/blob/master/README.ipynb) yaml file before deployment. I follow all step mentioned in seldon core document for its installation  in gcp.(used Helm and Istio)

## Expected behaviour
As per steps, I should  be able to reproduce same result .

## Environment

Cloud Provider: GCP
kubectl version- 1.24(client) 1.22(server)

**Comment by adriangonz** [comment]
Hey @RishabhPandit-00 ,

Generally this can happen when the probe timeouts are not configured correctly. This can lead to timeouts due to how the [Conda environment is created on-the-fly](https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#conda-environment-creation).

Based on the above, could you confirm that your `SeldonDeployment` manifest has the right `livenessProbe` and `readinessProbe` set up?

**Comment by RishabhPandit-00** [comment]
Hi, @adriangonz  Thanks for the response.

Please find below manifest which I used during deployment.


```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  predictors:
  - componentSpecs:
    - spec:
        # We are setting high failureThreshold as installing conda dependencies
        # can take long time and we want to avoid k8s killing the container prematurely
        containers:
        - env:
          - name: FOO
            value: bar
          # Note that name matches your nodes's name
          name: dev-log1
        - name: classifier
          livenessProbe:
            initialDelaySeconds: 180
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            #timeoutSeconds: 20  
          readinessProbe:
            initialDelaySeconds: 180
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
              
    graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: gs://seldon_deploy_model/model-a
      name: classifier
    name: default
    replicas: 1
```
Could you help mw with what's wrong here?...

Also sharing information after `kubectl describe pod`

<img width="1429" alt="Screenshot 2022-08-16 at 9 18 20 PM" src="https://user-images.githubusercontent.com/65149432/184923078-510780fc-1d93-494b-a57f-acf44afb8f6b.png">

**Comment by adriangonz** [comment]
Thanks for sharing that manifest @RishabhPandit-00.

From there, I can see that you've got a `dev-log1` container that it's not reflected in your graph. Could you remove that entry from the list of `containers`?

**Comment by RishabhPandit-00** [comment]
The manifest for deployment after removing name field is given below :-


```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  predictors:
  - componentSpecs:
    - spec:
        # We are setting high failureThreshold as installing conda dependencies
        # can take long time and we want to avoid k8s killing the container prematurely
        containers:
        # - env:
        #   - name: FOO
        #     value: bar
          # Note that name matches your nodes's name
          #name: dev-log1
        - name: classifier
          livenessProbe:
            initialDelaySeconds: 180
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            #timeoutSeconds: 20  
          readinessProbe:
            initialDelaySeconds: 180
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
              
    graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: gs://seldon_deploy_model/model-a
      name: classifier
    name: default
    replicas: 1

```
The status  and log after `kubectl apply ` and `kubectl logs` is given below:
<img width="1145" alt="Screenshot 2022-08-16 at 9 47 22 PM" src="https://user-images.githubusercontent.com/65149432/184929539-36eecb08-1db0-4adb-88ab-a067402cbce1.png">

Stil getting the same issue.

**Comment by adriangonz** [comment]
Right, thanks for trying that out.

Could you share the logs from your model container?

**Comment by adriangonz** [comment]
Right, thanks for trying that out.

It looks like your pod is crashing during the init stage. Therefore, it's not even getting to starting up your model container.

Could you share the logs from your init container? You should be able to get more info from there.

**Comment by RishabhPandit-00** [comment]
I am sharing Logs of init container
<img width="1414" alt="Screenshot 2022-08-16 at 10 10 12 PM" src="https://user-images.githubusercontent.com/65149432/184933200-ea5e33df-da41-4c1d-863e-e54bb196df60.png">

**Comment by adriangonz** [comment]
Hey @RishabhPandit-00 ,

As you can see on the logs from the init container, it is failing to download the model artefact from your GCS bucket. Since it appears to be a private bucket, you will need to configure your GCS credentials through an RClone secret. You can read more on this below:

https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html#handling-credentials

**Comment by RishabhPandit-00** [comment]
I am using this yaml for GCS credentials through Rclone, but still inti container crash.


```
apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
type: Opaque
stringData:
  RCLONE_CONFIG_GS_TYPE: google cloud storage
  RCLONE_CONFIG_GS_ANONYMOUS: "true"
  
---  
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  name: wines
  predictors:
  - componentSpecs:
    - spec:
        # We are setting high failureThreshold as installing conda dependencies
        # can take long time and we want to avoid k8s killing the container prematurely
        containers:
        # - env:
        #   - name: FOO
        #     value: bar
          # Note that name matches your nodes's name
          #name: dev-log1
        - name: classifier
          livenessProbe:
            initialDelaySeconds: 180
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
            #timeoutSeconds: 20  
          readinessProbe:
            initialDelaySeconds: 180
            failureThreshold: 200
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /health/ping
              port: http
              scheme: HTTP
              
    graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: gs://seldon_deploy_model/model-a
      name: classifier
      envSecretRefName: seldon-rclone-secret
    name: default
    replicas: 1
```

could you suggest any improvement is above yaml file?

**Comment by RishabhPandit-00** [comment]
Thanks @adriangonz . I will using my private bucket credential or I will make bucket public. If still issue persist , then will ping you. I am very impressed with you mlflow talk and you helping nature. Keep it up.
