### ISSUE TITLE
Why is seldon-app-svc of Deployment is set to the name of last PU of the inference graph

### ISSUE THREAD

**Issue by zyxue** [SeldonIO/seldon-core#4302]
The `seldon-app-svc` key in Deployment labels keep being updated when creating service for each container:

https://github.com/SeldonIO/seldon-core/blob/7a94dbfe354cef2ada1b6a563f7acf66328463df/operator/controllers/seldondeployment_controller.go#L752-L754

At the end, the value of that key becomes the name of the last container in the inference graph, which doesn't seem to make sense. E.g. 

```
k get deployment.apps/my-predictor -o yaml 
```

will return something like

```
  12   │   labels:
  13   │     app: my-predictor
...
  17   │     seldon-app: my-predictor-svc
  18   │     seldon-app-svc: <NAME-OF-LAST-CONTAINER-IN-THE-INFERENCE-GRAPH>
...
```

Worse, it causes problems whenever I try to update the graph with an error like

```
  Description:             Deployment.apps "my-predictor" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"seldon-app":"my-predictor-svc", "seldon-app-svc":"<NAME-OF-LAST-CONTAINER-IN-THE-INFERENCE-GRAPH>", "seldon-deployment-id":"my-predictor-di"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
 ```

In my case, I have just one Deployment, but many services are were created based on it. 

I wonder why is `seldon-app-svc` set in the Deployment, is it a bug?

**Comment by cliveseldon** [comment]
We create services that point to each container in the deployment so this may change if the names change on your SeldonDeployment spec.

We are working on a [PR](https://github.com/SeldonIO/seldon-core/pull/4043) for the selector change as this can't be accomplished via an update as your saw as these are immutable.
