### ISSUE TITLE
Return object in SeldonResponse does not have names parameter

### ISSUE THREAD

**Issue by aditya-AI** [SeldonIO/seldon-core#4311]
Hi Team,

Could you please add the `names` field in the `SeldonResponse` currently it supports the `data`, `meta`, etc. but not `names`. I was told to raise an issue so that you would be able to add the `name` parameter as well. 

Best,
Aditya

**Comment by cliveseldon** [comment]
Can you provide an example or link to the slack thread?

**Comment by cliveseldon** [comment]
Closing - please provide further details if still an issue
