### ISSUE TITLE
JSON Format Logs Python Model Servers.

### ISSUE THREAD

**Issue by hjilke** [SeldonIO/seldon-core#4312]
Hi Everyone,

I am using Seldon & I am fetching logs to Datadog. While doing so, I noticed some issues:

**Question 1:**

- Is there a particular reason why for the e.g. python MLFlow model server we log in non JSON format. Could we change this?

**Question 2:**

- I do not find the logs regarding HTTP requests to the classifiers. Not in the logs of the operator nor executor. I am more interested to see something like `root:_predict:42 - INFO:  Calling predict_proba`, not the payload send itself. Is there any way to have these logs in the executor or operator? 

Thanks Guys!

**Comment by cliveseldon** [comment]
For question 1 - can you try the [MlServer MLFlow integration](https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#v2-protocol)? Also, maybe point to the code or an example?

For question 2 - We only send payload logs so you would need to scrape or add something like fluentd to Seldon to scrape the raw logs from the containers.

**Comment by JoaNIO** [comment]
@cliveseldon 
Can you give some examples about how to collect Seldon raw logs?

**Comment by cliveseldon** [comment]
See [here](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/logging.html)

**Comment by cliveseldon** [comment]
Closing for now - please update if more details. Also please investigate [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html)
