### ISSUE TITLE
Mentioning MLServer as one of the prepackaged runtinmes

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4327]
I think there should be a page added to doc with an MLServer example in [Servers](https://docs.seldon.io/projects/seldon-core/en/latest/nav/config/servers.html) page.

I also think that there should be somewhere in the doc (maybe in the same page mentioned above) making the distinction between using [MLServer custom models runtime](https://mlserver.readthedocs.io/en/latest/examples/custom/README.html) (which could also be used in Seldon) and [Seldon custom Python runtime](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html). As far as I can understand from the v2 plan they will be some merging between both methods eventually. However, in the meantime, I think it will be useful to have some writing about their distinctions and plans for merging in the doc. Personally, I found it confusing at first.

**Comment by cliveseldon** [comment]
Thanks for this. Yes we will be moving towards MLServer for the way to write custom models in the future. We are planning to update the docs to provide further clarity.

**Comment by saeid93** [comment]
Great!

**Comment by cliveseldon** [comment]
As Sledon Core V2 is now available and is focused on Open Inference Protocols servers such as MLServer and NVIDIA Triton will close this for now.
