### ISSUE TITLE
Kafka Integration AVRO support

### ISSUE THREAD

**Issue by nicklausbrown** [SeldonIO/seldon-core#4333]
Hi @cliveseldon!

I've been tracking Seldon Core for some time back to 2019. I'm curious with the Kafka integration if it is possible to process AVRO messages. In particular, it would be nice to know if one can use the confluent schema registry to do so!

Thank you!

**Comment by cliveseldon** [comment]
Not at present. It would be good to understand the steps to allow this though. 
We are moving towards the [v2 protocol](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/v2-protocol.html) which has proto buffer and JSON definitions. Can you suggest how this would best be integrated with Avro support?

**Comment by cliveseldon** [comment]
Closing this for now. We send Open Inference Protocol messages in Seldon Core V2. We are unlikely to look into this for Seldon Core V1 although a PR or design would be welcome to discuss.
