### ISSUE TITLE
Alllow arbitrary JSON as a payload

### ISSUE THREAD

**Issue by oshev** [SeldonIO/seldon-core#434]
Currently, Seldon restricts queries to the prediction models to be in one of predefined formats. In production, however, it's not always possible/convenient to force clients to follow one of these formats. It would be helpful to have a possibility to receive arbitrary JSON requests in the model.

**Comment by oshev** [comment]
Ideally, the same should be applied to the output format as well. Thanks.

**Comment by gsunner** [comment]
added PR#595
