### ISSUE TITLE
Open the settings of readiness probe and liveness probe

### ISSUE THREAD

**Issue by yaliqin** [SeldonIO/seldon-core#4348]
Hi team,
We met a problem of one big model loading needing more time and it leads to the pod restarting. We added the readiness probe and liveness probe sections in this model seldon deployment YAML file. 

Is it possible to open the settings in the below code, then we can have a global setting for that:
https://github.com/SeldonIO/seldon-core/blob/d8ded76d815397fa0ff05f4359236850db8a90f6/operator/controllers/seldondeployment_controller.go#L784

**Comment by cliveseldon** [comment]
Have you set this to true:

https://github.com/SeldonIO/seldon-core/blob/2f3b55992493f5a080035a9ce72c4c2135d409c9/helm-charts/seldon-core-operator/values.yaml#L72

**Comment by yaliqin** [comment]
The deployment of this cluster is  v1.7.0 and I haven't found this field in the values.

**Comment by cliveseldon** [comment]
You may need to upgrade then if you want to use it.

**Comment by cliveseldon** [comment]
closing - please reopen if still an issue after upgrade
