### ISSUE TITLE
Rolling update incorrectly triggered in master due to deployment recreation

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#4359]
## Describe the bug

There has been an issue introduced by #4043 which causes the rolling update to not be triggered correctly.

Namely the expected and current behaviour for a rolling update are:
Expected: `new_pod[creating]->new_pod[running]->old_pod[terminating]`
Actual: `old_pod[terminating]->new_pod[creating]->new_pod[running]`

It seems the issue is the recreation of the deployment which may need to be re-explored 

https://github.com/SeldonIO/seldon-core/blob/1e2482dcce33e96530180ada4a8391242fbf35b6/operator/controllers/seldondeployment_controller.go#L1546-L1557

**Comment by cliveseldon** [comment]
Closing this. Can reopen if we see a test case that shows it.
