### ISSUE TITLE
Seldon Deployment on other microk8s node

### ISSUE THREAD

**Issue by Jaidatt** [SeldonIO/seldon-core#4376]
I did join two microk8s nodes: on master node I did install seldon-system, now I want to deploy seldon deployment pods on other node(worker node). I've gone through seldon core templates, inside [this template](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml) they have mentioned node affinity rule. Is something similar to this possible in seldon core deployment?

**Comment by cliveseldon** [comment]
Yes you should be able to add this to your seldon deployment podSpec: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#affinity-v1-core
