### ISSUE TITLE
Unable to get token

### ISSUE THREAD

**Issue by sathiez** [SeldonIO/seldon-core#438]
Hi, 
when I use this prog to get token 

` def get_token(oauth_key,oauth_secret,namespace,endpoint):

	payload = {'grant_type': 'client_credentials'}
  
	if namespace is None:
  
		key = oauth_key
    
	else:
  
		key = oauth_key+namespace
    
	response = requests.post(
				"http://"+endpoint+"/oauth/token",
				auth=HTTPBasicAuth(key, oauth_secret),
				data=payload)
	print(response.text)
	token =  response.json()["access_token"]
	return token'

I get the following error,

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.17.0.1 - - [11/Feb/2019 07:12:00] "POST /oauth/token HTTP/1.1" 404 -
--------------------------------------------------------------------------------------------

<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

How can I solve it?

**Comment by cliveseldon** [comment]
I assume you have port forwarded to 0.0.0.0:5000 ? What have you port-forwared? It should be the API Gateway if you are using OAuth.
404 suggest the endpoint does not exist.

**Comment by cliveseldon** [comment]
I'm assuming this is fixed as stale. Please reopen if not @sathiez
