### ISSUE TITLE
Model explainer does not respect isito hosts annotation

### ISSUE THREAD

**Issue by huangyq23** [SeldonIO/seldon-core#4381]
## Describe the bug

When deploying model explainer along with a model in the same `SeldonDeployment`.
The explainer does not respect the `seldon.io/istio-host` annotation.

## To reproduce
1. Follow https://docs.seldon.io/projects/seldon-core/en/latest/analytics/explainers.html
2. Add `seldon.io/istio-host` annotations to `spec.annotations`

## Expected behaviour

The host are set on the underlying Virtual Service

## Environment

Kubernetes 1.23.12
Seldon 1.14.1

## Potential Cause
There are discrepancies in how `seldon.io/istio-host` annotation is applied to underlying `VirtualService`: 

https://github.com/SeldonIO/seldon-core/blob/1e06db27cadb70aff35ee9de5bf552cb0a37a773/operator/controllers/seldondeployment_controller.go#L240-L245

https://github.com/SeldonIO/seldon-core/blob/1e06db27cadb70aff35ee9de5bf552cb0a37a773/operator/controllers/seldondeployment_explainers.go#L325-L331

**Comment by cliveseldon** [comment]
Thanks for this. I've added to 1.15 project but are you able to provide a PR to fix this?

**Comment by huangyq23** [comment]
@cliveseldon I submitted https://github.com/SeldonIO/seldon-core/pull/4401

**Comment by cliveseldon** [comment]
great
