### ISSUE TITLE
Set allowPrivilegeEscalation=false in executor

### ISSUE THREAD

**Issue by wumbrath** [SeldonIO/seldon-core#4409]
To be able to run Seldon in more restricted environments we need the executor container to have the `securityContext.allowPrivilegeEscalation` set to `false`.

Currently no value is set and according to the Kubernetes documentation the default value is not clearly specified. As a consequence some policies are blocking model deployments(like the [privilege escalation one in Azure AKS](https://learn.microsoft.com/en-us/azure/aks/policy-reference)).

As the container does not need privilege escalation it could have the property set [here](https://github.com/pdstrnadJC/seldon-core/blob/master/operator/controllers/seldondeployment_engine.go#L428) or allow the user to configure it via `svcOrch`.

<sup>Winfried Umbrath winfried.umbrath@mercedes-benz.com, Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

**Comment by cliveseldon** [comment]
This seems the place that needs to be configurable: https://github.com/SeldonIO/seldon-core/blob/685fe3d4691cf63ee9978aea5662911f3e7cefbe/operator/controllers/seldondeployment_engine.go#L339-L341

**Comment by wumbrath** [comment]
Yes, or just set to false, as the container does not need the privilege escalation.

**Comment by cliveseldon** [comment]
Could you do a PR for this. Would be much appreciated.

**Comment by wumbrath** [comment]
I'll try to find some time for it next week.
