### ISSUE TITLE
Not able to deploy Xgboost models

### ISSUE THREAD

**Issue by altruistcoder** [SeldonIO/seldon-core#4425]
Hello,

I have a Seldon Operator (version 1.7.0) installed on my Openshift cluster.

I have been deploying multiple models using various Prepackaged Inference servers provided by Seldon from quite some time and they all were running fine till some time ago.

From yesterday, I have started facing a problem with the XGBoost Inference Server because of which I am not able to deploy any XGBoost model using Seldon. As soon as I deploy a XGBoost model using Seldon's XGBoost Inference Server, I am getting `ImagePullBackOff` error. I have attached a screenshot of the same.

![image](https://user-images.githubusercontent.com/31319270/199329487-434d1cdf-1c20-4847-a726-00b85744bc74.png)

The image version which comes us in the resulting deployment is:

```
registry.connect.redhat.com/seldonio/xgboostserver@sha256:85a572a03e2c0ce1a7fb10c622f73c65d717a6e05c1ee00f5148b25774394f0b
```

I checked `seldon-config` ConfigMap present in seldon-operator namespace in my cluster and I found the implementation written for XGBoost Inference Server as follows:

```
"XGBOOST_SERVER": {
      "protocols" : {
        "seldon": {
          "image": "seldonio/xgboostserver",
          "defaultImageVersion": "1.7.0"
          },
        "kfserving": {
          "image": "seldonio/mlserver",
          "defaultImageVersion": "0.1.0"
          }
        }
    },
```

I checked the Redhat registry for finding this image but this image was not present there.

So, I have also tried modifying the `seldon-config` ConfigMap to add an additional Implementation under "**predictor_servers**" key as follows:

```
"XGBOOST_SERVER_CUSTOM": {
      "protocols" : {
        "seldon": {
          "image": "registry.connect.redhat.com/seldonio/xgboostserver",
          "defaultImageVersion": "1.14.1"
          },
        "kfserving": {
          "image": "seldonio/mlserver",
          "defaultImageVersion": "0.1.0"
          }
        }
    },
```

Using this model implementation image, the XGBoost's model are getting deployed successfully,

I just want to know whether the image `seldonio/xgboostserver:1.7.0` have been removed recently and are there major differences between the versions **1.7.0** and **1.14.1**?

And, is it alright to use the version 1.14.1 in place of the 1.7.0 for XGBoost's model Inference server?

**Comment by RafalSkolasinski** [comment]
Hi @altruistcoder,

Which exactly operator did you install on OpenShift cluster? We have three flavours:
- operatorhub: [here](https://github.com/k8s-operatorhub/community-operators/tree/main/operators/seldon-operator)
- community: [here](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/seldon-operator)
- certified: [here](https://github.com/redhat-openshift-ecosystem/certified-operators/tree/main/operators/seldon-operator-certified)


The 1.7.0 I only see on OperatorHub. As far as I am aware for operatorhub and community flavours source of images is from `docker.io` registry and not from the `registry.connect.redhat.com` so I cannot find anything on 1.7.0 xgboost image being in the red hat registries in the first place. 

I would recommend to update to 1.14.1 version of operator in general to stay on the latest. Also on OpenShift the `seldon-config` may be overwritten in certain situations and the way to set it up is via the `RELATED_IMAGE_XGBOOSTSERVER` env variable that can be set on CSV

**Comment by cliveseldon** [comment]
closing this. Please reopen if an issue for 1.14.1
