### ISSUE TITLE
SeldonClient: need a method to read model metadata

### ISSUE THREAD

**Issue by Felix-neko** [SeldonIO/seldon-core#4426]
Hi folks! And thank you for your great project.

Can you please somehow add some method for `SeldonClient` that could access model's metadata? It would be extremely useful...

**Comment by RafalSkolasinski** [comment]
Hi @Felix-neko, this sounds reasonable but unfortunately we do not plan to be extending `SeldonClient` in the near future. If you be willing to prepare a PR with this feature we can review it.

**Comment by saeid93** [comment]
Hi @RafalSkolasinski, Is there a plan for writing the same client for the V2 and it's integration with the MLServer?

**Comment by RafalSkolasinski** [comment]
Hey @saeid93, yes, that's something on our radar and we are thinking about it. It was not prioritized yet. 

As MLServer implements V2 protocol it is compatible with [tritonclient](https://github.com/triton-inference-server/client) (though not all methods will work via Executor). We already use it inside mlserver codebase to implement `mlserver infer ...` batch processing that is coming in 1.2 of MLServer.

But as `tritonclient` is sometimes a bit awkward to work with we indeed think about adding an MLServer client. That's the discussion for [MLServer](https://github.com/SeldonIO/MLServer) repo though.

**Comment by saeid93** [comment]
Thanks for your reply. @RafalSkolasinski That's interesting, I didn't realize that Triton Client could have out-of-the-box integration with MLServer as their both on v2. Yea, tritonclient is a bit awkward and the syntax is not as straightforward as SeldonClient. Glad to hear that's something on agenda, a client that is also integrated with MLServer codecs is something that I think will be really useful in terms of ease of use from the user side.

**Comment by RafalSkolasinski** [comment]
Yes, codecs is not something that `tritonclient` supports well as you cannot set the `parameters` in the requests well. You can workaround it though by setting it in the `model-settings.json` as discussed [here](https://mlserver.readthedocs.io/en/latest/user-guide/content-type.html#model-metadata).

**Comment by RafalSkolasinski** [comment]
Closing as we will not be extending existing V1 `SeldonClient` to provide methods for metadata retrieval.
