### ISSUE TITLE
logs collection

### ISSUE THREAD

**Issue by JoaNIO** [SeldonIO/seldon-core#4428]
Hi, 
Recently, we were studying how to collect logs of models deployed with Seldon. we found that current `logger` mechanism cannot collect logs of the seldon framework itself and we don't know how to collect these log information to help troubleshoot problems. Is there any good suggestions?

**Comment by agrski** [comment]
Hi @JoaNIO,

The `logger` mechanism in the Seldon Core orchestrator/executor is for capturing inference logs (requests and responses), so will not capture general application logs, as you've identified.

As Seldon Core runs on Kubernetes, the standard approach for collecting application logs would be via tools like Fluentd or Logstash (if you want open-source), or the various enterprise and vendor-specific alternatives to these.
Which you choose is entirely up to you, and is completely independent of Seldon tools.

If you haven't already found it, [this page](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/log_level.html) discusses setting the log level of Seldon components, e.g. to make them more verbose.

I hope this helps!
