### ISSUE TITLE
Consider hosting helm charts on stable repo, or at least a chart repository

### ISSUE THREAD

**Issue by naseemkullah** [SeldonIO/seldon-core#443]
Having the charts hosted on the official helm stable repo (preferred, imho) or your own such as `https://charts.seldonio.com` for example, makes their consumption much smoother for the end user.

**Comment by ryandawsonuk** [comment]
There is currently https://storage.googleapis.com/seldon-charts - it is [referenced in the docs](https://docs.seldon.io/projects/seldon-core/en/latest/graph/helm_charts.html). 

We're considering contributing the operator chart to [the official repo](https://github.com/helm/charts/) and also getting it [listed in kubeapps](https://hub.kubeapps.com/charts?q=operator)

**Comment by ryandawsonuk** [comment]
@naseemkullah actually it would be cool if we could keep this issue open while we consider the options, if you're ok with that.

**Comment by naseemkullah** [comment]
@ryandawsonuk Absolutely!

**Comment by ryandawsonuk** [comment]
We should keep an eye on https://github.com/kubeflow/tf-operator/issues/716 and what the kubeflow project does in general. Especially important in the light of https://github.com/SeldonIO/seldon-core/issues/477

**Comment by ryandawsonuk** [comment]
Now got the charts listed at https://hub.helm.sh/charts?q=seldon

Also have open PR at operatorhub https://github.com/operator-framework/community-operators/pull/395

**Comment by cliveseldon** [comment]
Fixed
