### ISSUE TITLE
Intra Cluster Communication with Seldon deployed CRD

### ISSUE THREAD

**Issue by igor-stranjanac** [SeldonIO/seldon-core#4439]
## Describe the bug
Hello!
We use Seldon core to deploy ML model, where we use the Python language wrapper. We would like to communicate with the Seldon resource which is deployed in an Istio sidecar injected namespace (pod to pod communication).
The problem which we are facing is when we try to establish the communication from one pod from within a Istio sidecar injected namespace, to the Seldon resource pod which is deployed in the same namespace.
When we establish communication between pods from different namespaces, then it works as expected by following the Kubernetes guidelines and hitting this url:
**http://<service_name>.<namespace_name>.svc.cluster.local:8000/api/v1.0/predictions**

In the case when we have a pod within the same namespace as our Seldon deployed resource, then we are not able to reach it, with an error Connection refused, on the following url:
**http://<service_name>:8000/api/v1.0/predictions**
We have tried the following hosts:
* Using Istio ingress service:
**http://istio-ingressgateway-seldon.istio-system.svc.cluster.local:80**
* Using the same endpoint as in the case when the pods are communicating between different namespaces:
**http://<service_name>.<namespace_name>.svc.cluster.local:8000/api/v1.0/predictions**

## To reproduce
Have a running instance of a Seldon CRD deployed in Amazon EKS, where Istio is used as a sidecar in the namespace. Then try to create a POST request to the Seldon endpoint with a Pod which is running in the same namespace as the Seldon resource.

## Expected behavior
Expected is to be able to communicate to the seldon deployed model from within the same namespace, by following the Kubernetes guidelines for intra cluster communication:
1. When pods communicate from different namespaces, the following url should be used:
http://<service_name>.<namespace_name>.svc.cluster.local:8000/api/v1.0/predictions
2. When pods communicate within the same namespaces, the following url should be used:
http://<service_name>:8000/api/v1.0/predictions

## Environment

* Cloud Provider: [AWS]
* Kubernetes Cluster Version v1.21.14-eks-fb459a0 
* Deployed Seldon System Images: Seldon 1.14.0

**Comment by igor-stranjanac** [comment]
Hi guys, do you have some advices/hints for me here?

**Comment by cliveseldon** [comment]
This may be being stopped by the istio sidecar?
Have you set up and allowed internal svc calls in istio?

**Comment by igor-stranjanac** [comment]
I think so, since in the gateway I have the istio-ingressgateway-seldon Service defined as NodePort, and currently, the servers.hosts I have defined "*" on port 80. Could you maybe elaborate a bit more on how to allow internal svc calls in istio?

**Comment by igor-stranjanac** [comment]
Hi all, just to mention, it was an Istio configuration problem. The issue was happening because I was doing a curl request before the Istio sidecar container was starting. Hence the connection refused. By adding the annotation bellow: 
`annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'`

I was able to delay the application start until the proxy started and hence the connection was established. 

This issue can be closed.
