### ISSUE TITLE
Enriching the svc logs

### ISSUE THREAD

**Issue by saeid93** [SeldonIO/seldon-core#4445]
As per [community Slack conversation](https://seldondev.slack.com/archives/C03DQFTFXMX/p1667547280921139?thread_ts=1667513017.768049&cid=C03DQFTFXMX) svc logs could be improved with additional data like id of the request and their duration.

**Comment by cliveseldon** [comment]
Can you reopen if this info is not available in [v2](https://docs.seldon.io/projects/seldon-core/en/v2/index.html) for what you need.
