### ISSUE TITLE
Kafka producer does not pass headers along

### ISSUE THREAD

**Issue by rio** [SeldonIO/seldon-core#4447]
There is currently nothing happening with any headers that need to be sent out of kafka. Think of for example a CloudEvent envelope or other custom trace information etc.

[Here](https://github.com/SeldonIO/seldon-core/blob/master/executor/api/kafka/worker.go#L58) you see the slice being allocated but it never gets filled with anything. We're currently considering to work around it by useing the built in kafka integration in MLServer but at that point seldon basically becomes a fancy alternative for a Deployment ;)

**Comment by cliveseldon** [comment]
Can you outline the headers you are looking to add?

**Comment by cliveseldon** [comment]
But just to clarify these are headers on the input topic message? So you are saying you want these copied to output topic message?

**Comment by rio** [comment]
No, not copied. Just the ability to set headers in the response.

**Comment by cliveseldon** [comment]
OK. But the problem is the underlying graph might have multiple components so its less clear how we decide how pass that information back from models. Or, do you mean static headers you can define on the yaml of your spec?

**Comment by rio** [comment]
Well currently it's not passing anything so that seems to be the main problem regardless of how the graph is built up. Either way the one who builds the graph has a responsibility for how the headers are manipulated and passed through it. 

Static headers might work but dynamic headers like the id header in the cloudevent would still need to be set.

**Comment by cliveseldon** [comment]
The cloud event id would be in the input topic message so could be copied.
Adding headers from arbitary parts of the graph would be more difficult but is handled in API updates to seldon we will be releasing this quarter.

**Comment by rio** [comment]
It won't be in the input if the upstream service does not generate one. I don't really understand why simply passing on the headers into the kafka message if they are provided by the model response? Now they're just empty.

Do you have an example of these API updates you're talking about? This will help us determine if we're going to put time into building our own or helping seldon-executor forward.

**Comment by cliveseldon** [comment]
Can you try this with v2 as this uses Kafka under the hood and does pass all headers with an `x-` prefix. See [here](https://docs.seldon.io/projects/seldon-core/en/v2/contents/inference/index.html#pipeline-metadata).
