### ISSUE TITLE
Nginx controller support

### ISSUE THREAD

**Issue by habilmohammed** [SeldonIO/seldon-core#4488]
1) Does seldon-core supports using the nginx controller for managing the traffic as it is widely used everywhere, or are there plans to support this in the future.

2) Also, I was trying to setup the seldon-core in my local machine by following the installation guidelines (https://docs.seldon.io/projects/seldon-core/en/latest/install/kind.html) and tried to deploy a sample iris model using these steps (https://docs.seldon.io/projects/seldon-core/en/latest/workflow/github-readme.html). 
I am not able to get the <ingress_url> in my local for hitting the model endpoints as the istio-ingressgateway is having the EXTERNAL-IP in PENDING state. Is there a way to hit the deployed models(in local machine) without using a LoadBalancer.

<img width="1378" alt="Screenshot 2022-12-07 at 3 27 10 PM" src="https://user-images.githubusercontent.com/31307307/206148252-24cefe83-8b1d-4dee-8c74-93d419024574.png">

<img width="998" alt="Screenshot 2022-12-07 at 3 36 37 PM" src="https://user-images.githubusercontent.com/31307307/206150128-1656140f-a497-491f-b59b-e80a7e07d712.png">

**Comment by cliveseldon** [comment]
We suggest you look at [v2](https://docs.seldon.io/projects/seldon-core/en/v2/) which is agnostic to service meshes and provides a single SVC entrypoint. We would be very keen to see an example using NGINX with v2. Closing this for now.
