### ISSUE TITLE
Empty reply from SendFeedback

### ISSUE THREAD

**Issue by becartef** [SeldonIO/seldon-core#449]
svc-orch engine does return an empty message for SendFeedback.

SeldonMessage returned by the sendFeedback method in the seldon java wrapper is ignored:

predictionService.sendFeedback(feedback);
            String json = "{}";
            return new ResponseEntity<String>(json,HttpStatus.OK);

**Comment by jklaise** [comment]
This is also a bug in the current Python wrapper.

**Comment by cliveseldon** [comment]
Should be updated as part of https://github.com/SeldonIO/mlgraph

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Closing. Please reopen if still an issue.
