### ISSUE TITLE
Don't disable istio sidecar injection

### ISSUE THREAD

**Issue by ceastman-r7** [SeldonIO/seldon-core#4521]
Our company uses Istio for egress filtering, so bypassing the Istio sidecar injection is bypassing one of our companies security measures. Please remove references like this:

https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/deployment_seldon-controller-manager.yaml#L29

        sidecar.istio.io/inject: 'false'

thank you

**Comment by cliveseldon** [comment]
There is an issue with sidecars and the init-containers we use to download models in v1 of Seldon Core - for discussion see [here](https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers) and [here](https://github.com/istio/istio/issues/23802#issuecomment-628035658).

For [v2](https://docs.seldon.io/projects/seldon-core/en/v2/) of Seldon Core we don't use init-containers and have no annotations to stop sidecar inject as we intend to be service-mesh agnostic. We welcome further docs and examples for all service meshes: see [here](https://github.com/SeldonIO/seldon-core/tree/v2/service-meshes/istio) for the current examples that need to be further extended.

For v1 of Seldon Core we would need time to investigate proper docs to illustrate and test the changes to remove these restrictions for istio users.

We welcome PRs to help in these areas.

**Comment by ceastman-r7** [comment]
Is there an eta on v2? looks like another v1 was released last month: 

v1.15.0 [Latest](https://github.com/SeldonIO/seldon-core/releases/latest)
@[RafalSkolasinski](https://github.com/RafalSkolasinski) RafalSkolasinski released this last month

**Comment by agrski** [comment]
> Is there an eta on v2? looks like another v1 was released last month:

v2 has already been released!  Clive's link above is for the branch, but there's also the [release itself](https://github.com/SeldonIO/seldon-core/releases/tag/v2.0.0).

**Comment by ceastman-r7** [comment]
ah thank you very much. have a great day.
