### ISSUE TITLE
V2: Can't deploy a local model file

### ISSUE THREAD

**Issue by Niklas2501** [SeldonIO/seldon-core#4525]
## Describe the bug

Currently testing the seldon core V2 on a kubernetes cluster. I followed [these instructions](https://docs.seldon.io/projects/seldon-core/en/v2.0.0/contents/getting-started/kubernetes-installation/helm.html) and everything works for the [IRIS examples](https://docs.seldon.io/projects/seldon-core/en/v2.0.0/contents/examples/k8s-examples.html#seldon-v2-kubernetes-examples) as expected. 

Then I wanted to deploy a model from a local source. For V1 of seldon-core I followed [this approach](https://github.com/SeldonIO/seldon-core/tree/1481b0c6d31e7678decb3789e5279334e455af76/examples/models/pvc-tfjob) of creating a persistent volume with the required files, which also worked. 

With V2 and using the .yaml file below this approach does not seems to be working properly. 
When checking the status of the model I get:
```
Failed to sync/copy pvc://ml-models-pvc/models/sf_model to /mnt/agent/rclone/4243286861
Failed rclone request to host:0.0.0.0 port:5572 path:/sync/copy
```

I can't use the approach described in the [docker installation](https://docs.seldon.io/projects/seldon-core/en/v2.0.0/contents/getting-started/docker-installation/index.html) because I'm using an Apple M1 Mac and currently seldon-cli does not support arm64.

How can i fix this issue with the PVC-storageUri or are there any other ways to deploy a local model? 

I know rClone also supports the local file system as a source but I'm not sure where to put the files and how to set the storageUri in this case. 

Any advice is welcome.
Thank you very much for your help! 

## To reproduce

1.  Setup seldon-core as described [here ](https://docs.seldon.io/projects/seldon-core/en/v2.0.0/contents/getting-started/kubernetes-installation/helm.html)
2. Deploy the[ IRIS example](https://docs.seldon.io/projects/seldon-core/en/v2.0.0/contents/examples/k8s-examples.html#seldon-v2-kubernetes-examples) as reference 
3. Create pv, pvc and the model using the yaml file shown below
4. Check the status of the model with `kubectl get model sf-model -n seldon-mesh -o jsonpath='{.status}' | jq -M .`

[pv_data.zip](https://github.com/SeldonIO/seldon-core/files/10285997/pv_data.zip)

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-immediate
provisioner: rancher.io/local-path
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ml-models-pv
  namespace: seldon-mesh
  labels:
    type: local
spec:
  storageClassName: local-path-immediate
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # pv_data contains models/sf-model/model.joblib, models/sf-model/model-settings.json
    path: "/Users/nw/pv_data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ml-models-pvc
  namespace: seldon-mesh
spec:
  storageClassName: local-path-immediate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: sf-model
  namespace: seldon-mesh
spec:
  storageUri: "pvc://ml-models-pvc/models/sf-model" 
  # secretName: "rclone-config"
  requirements:
  - sklearn
  memory: 500Ki
```

## Expected behaviour

- rclone should correctly copy the model files from the PV to the ml-server pod
- The model should be running

## Environment

- Proivder: Rancher Desktop
- Architekture: ARM64 / M1 Mac
- Kubernetes Cluster Version: 
    - Client Version: v1.25.2
    - Kustomize Version: v4.5.7
    - Server Version: v1.25.4+k3s1
- Deployed Seldon System Images: image: docker.io/seldonio/seldonv2-controller:latest

**Comment by cliveseldon** [comment]
Thanks for this. We don't have an example for v2 8s pvc use at present so will add one to illustrate as we definitely want to support this use case.

**Comment by cliveseldon** [comment]
This should be fixed now - you can check the example and additions to [docs](https://docs.seldon.io/projects/seldon-core/en/v2/contents/kubernetes/resources/server/index.html#server-with-pvc)

**Comment by Niklas2501** [comment]
Looks like santa's elves are also working on seldom-core ;) 
Thank you very much for your quick update!
