### ISSUE TITLE
Inference graph combiner + 2 mlflow models fails to complete deployment successfully.

### ISSUE THREAD

**Issue by mmanikan** [SeldonIO/seldon-core#4527]
we are trying out inference graph combiner + 2 mlflow models. But ,we are seeing combiner and mlflow are running.
whereas seldon-container-engine  fails with the following error:
{"level":"info","ts":1671732515.950374,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
{"level":"info","ts":1671732515.950417,"logger":"entrypoint","msg":"http server started"}
{"level":"error","ts":1671732539.438227,"logger":"SeldonRestApi","msg":"Ready check failed","error":"dial tcp 127.0.0.1:9001
-------
which is part of combiner. I am unable to change port for this. I am not sure where port 9001 pickedup
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
my yaml file looks like :
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: ad-combiner
  namespace: my-mlops
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/metadata-generic-node:1.14.0-dev
          name: node-combiner
    - spec:
        containers:
        - name: node-one
    - spec:
        containers:
        - name: node-two
    graph:
      name: node-combiner
      type: COMBINER
      children:
      - name: node-one
        type: MODEL
        implementation: MLFLOW_SERVER
        modelUri: s3://xxxxxx/model
        envSecretRefName: seldon-rclone-secret
        parameters:
          - name: xtype
            type: STRING
            value: DataFrame
        children: []
      - name: node-two
        type: MODEL
        implementation: MLFLOW_SERVER
        modelUri: s3://yyyyyyy/model
        envSecretRefName: seldon-rclone-secret
        parameters:
          - name: xtype
            type: STRING
            value: DataFrame
        children: []
    name: example
    replicas: 1
---------
seldon-core version: 1.15.0

**Comment by cliveseldon** [comment]
This is due to the assumption the container is on first componentSpec here: https://github.com/SeldonIO/seldon-core/blob/1f32da11897909e235d5974ca0b7100850ea0cb0/operator/apis/machinelearning.seldon.io/v1/defaults.go#L258

This will be fixed by finding the componentSpec index for the container.
