### ISSUE TITLE
Support MLeap serialized Spark mllib models in MLServer

### ISSUE THREAD

**Issue by indranilr** [SeldonIO/seldon-core#4531]
[MLeap](https://github.com/combust/mleap) is used to deploy Spark mllib models (including Spark Xgboost and others) for inference through Java runtime. With Seldon core the Java language wrapper was used to wrap these MLeap format models and deploy using Java JNI wrapper. The JNI wrapper however had many vulnerabilities [(#4103 )](https://github.com/SeldonIO/seldon-core/issues/4103).

Please support deployment of MLeap serialized models in MLServer.

NOTE : Since the MLLib documentation is not present in MLServer I could not figure out how once could continue to deploy Mleap serialized models in MLServer paradigm.

**Comment by cliveseldon** [comment]
Thanks for your interest in MLeap with Seldon Core. There is an [issue](https://github.com/SeldonIO/MLServer/issues/183) for Java runtime in MLServer. Could you add your comment there or open a new issue on the MLServer repo. Will close this here and a new issue can be opened once Java models are supported on MLServer.
