### ISSUE TITLE
Kafka neccessary for Seldon to run?

### ISSUE THREAD

**Issue by habilmohammed** [SeldonIO/seldon-core#4532]
Hi,
I was trying to setup the Seldon V2 on a GCP Kubernetes Cluster. I am getting error logs attached below, and the model inference doesn't seem to be working for me. 
Do we need to setup Kafka for the inference to be functional?

### **Logs:**
kubectl logs -f seldon-dataflow-engine-f64cf4cb-vkpk5 -n seldon-mesh

W1216 14:41:25.182648   48135 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2022-12-16 09:11:10:527 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.20.2
[otel.javaagent 2022-12-16 09:11:12:501 +0000] [main] INFO io.opentelemetry.javaagent.shaded.instrumentation.jmx.engine.JmxMetricInsight - Empty JMX configuration, no metrics will be collected for InstrumentationScope io.opentelemetry.jmx
09:11:12.978495908  INFO [                main] :        Configuration : Setting configuration using the DSL with append=false
09:11:13.064524673  INFO [                main] :        Configuration : Setting configuration using the DSL with append=false
09:11:13.069372827  INFO [                main] :           i.s.d.Main : initialised with config [(log.level.app, INFO), (log.level.kafka, WARN), (upstream.host, seldon-scheduler), (upstream.port, 9008), (kafka.bootstrap.servers, seldon-kafka-bootstrap.seldon-mesh:9092), (kafka.security.protocol, PLAINTEXT), (kafka.partitions.default, 1), (kafka.replication.factor, 1), (kafka.state.clean, true), (kafka.join.window.millis, 60000), (tls.client.ca.path, /tmp/certs/kafka/client/ca.crt), (tls.client.key.path, /tmp/certs/kafka/client/tls.key), (tls.client.cert.path, /tmp/certs/kafka/client/tls.crt), (tls.broker.ca.path, ), (tls.client.secret, ), (tls.broker.secret, ), (tls.endpoint.identification.algorithm, )]
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
    at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:546)
    at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:478)
    at org.apache.kafka.clients.admin.Admin.create(Admin.java:133)
    at io.seldon.dataflow.kafka.KafkaAdmin.<init>(KafkaAdmin.kt:31)
    at io.seldon.dataflow.PipelineSubscriber.<init>(PipelineSubscriber.kt:53)
    at io.seldon.dataflow.Main.main(Main.kt:65)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
    at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89)
    at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
    at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:498)
    ... 5 more
09:11:13.419003885  WARN [                main] :  o.a.k.c.ClientUtils : Couldn't resolve server seldon-kafka-bootstrap.seldon-mesh:9092 from bootstrap.servers as DNS resolution failed for seldon-kafka-bootstrap.seldon-mesh
[otel.javaagent 2022-12-16 09:11:13:546 +0000] [OkHttp http://seldon-collector:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: seldon-collector: Name or service not known

➜  gs git:(master) ✗ kubectl logs -f seldon-controller-manager-799869dd48-h2qpt  -n seldon-mesh

W1216 14:41:57.539824   48189 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
I1216 09:10:59.778349       1 request.go:601] Waited for 1.037837202s due to client-side throttling, not priority and fairness, request: GET:https://10.113.60.97:443/apis/autoscaling/v2beta2?timeout=32s
1.6711818598333528e+09  INFO    controller-runtime.metrics  Metrics server is starting to listen    {"addr": ":4000"}
1.6711818598337605e+09  INFO    schedulerClient Running scheduler client in plain text mode {"port": 9004}
1.6711818598340638e+09  INFO    schedulerClient Connected to scheduler  {"host": "seldon-scheduler", "port": 9004}
1.6711818598342514e+09  INFO    setup   starting manager
1.6711818598347037e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
I1216 09:10:59.834895       1 leaderelection.go:248] attempting to acquire leader lease seldon-mesh/e98130ae.seldon.io...
1.6711818598349214e+09  INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:4000"}
1.6711818598371696e+09  ERROR   setup   Failed to subscribe to scheduler model events   {"error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.113.60.104:9004: connect: connection refused\""}
main.main.func1
    /workspace/main.go:106
1.6711818598372176e+09  ERROR   setup   Failed to subscribe to scheduler server events  {"error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.113.60.104:9004: connect: connection refused\""}
main.main.func2
    /workspace/main.go:113

**Comment by cliveseldon** [comment]
Yes, you will need to setup Kafka for full system functionality. See [here](https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/kubernetes-installation/index.html). We provide an [Ansible script](https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/kubernetes-installation/ansible.html#setup-ecosystem) for setting up the ecosystem components such as Kafka.

**Comment by cliveseldon** [comment]
To add to this. Isolated Models can be used without Kafka but at present we have not provided setup instructions for this.

**Comment by habilmohammed** [comment]
Is it possible to use **GCP Pub/Sub** service instead of Kafka so that we would be able to align with our existing infra setup?

**Comment by cliveseldon** [comment]
At present no - an option may be to push from [Kafka to GCP pub/sub](https://cloud.google.com/pubsub/docs/connect_kafka) but its not something we have tried.

**Comment by agrski** [comment]
To add some context, it's an explicit decision to be cloud agnostic so that Seldon Core v2 can be run on any cloud (or none at all).  Using Kafka allows that, and theoretically also allows Kafka-compatible alternatives to be used.

As Clive mentions, if cloud-specific tools have connectors for Kafka, that's the way to go as the integration is very much around Kafka itself and affects multiple components.
