### ISSUE TITLE
Deprecated API poddisruptionbudgets:v1beta1 LIST and WATCH apis being called in seldon version 1.14.1

### ISSUE THREAD

**Issue by sl0wc0der** [SeldonIO/seldon-core#4539]
## Describe the bug

We're using seldon-core 1.14.1 on openshift (Kubernetes v1.23) which will remove support for poddisruptionbudgets:v1beta1 api in version 1.25

## To reproduce
Deploy a model and monitor the apis on the Kubernetes cluster.
The following prometheus query should return no results.
`group by(group, version, resource, verb) (sum by(group, version, resource, verb) (rate(apiserver_request_total{resource="poddisruptionbudgets", version="v1beta1"}[30m]))) > 0`

Currently it shows this result
<img width="1487" alt="AAA" src="https://user-images.githubusercontent.com/22419321/210016037-caf902d0-1353-4684-9093-fb9365e12749.png">

## Expected behaviour

The deprecated APIs shouldn't be called.

## Environment

* Cloud Provider: On-prem deployment of Openshift
* Kubernetes Cluster Version: 1.23
* Deployed Seldon System Images: seldon-core-executor:1.14.1

**Comment by RafalSkolasinski** [comment]
Related to https://github.com/SeldonIO/seldon-core/issues/4339 and https://github.com/SeldonIO/seldon-core/issues/3854 and most likely to be fixed by https://github.com/SeldonIO/seldon-core/pull/4172
