### ISSUE TITLE
could you add possibility to set annotations in Server's Pod?

### ISSUE THREAD

**Issue by michaln-gc** [SeldonIO/seldon-core#4542]
This applies to Seldon Core v2.
It should be set here:
https://github.com/SeldonIO/seldon-core/blob/5a2ee046ee5e90f1886eaaa706cdd76c12041441/operator/controllers/reconcilers/statefulset/statefulset_reconciler.go#L72

I have a case where I need to provide annotations that configure Multus to define the second network interface in Server's Pod that is required by my model's workload.

**Comment by michaln-gc** [comment]
It was discussed on Slack channel:
https://seldondev.slack.com/archives/C03DQFTFXMX/p1672751257591779

**Comment by cliveseldon** [comment]
I think we can just apply the annotations and labels from the ServerConfig downwards with ones on a Server taking precedence.They would be applied to the Stateful set managed by the Server?

**Comment by michaln-gc** [comment]
This sounds good :)

**Comment by sakoush** [comment]
@michaln-gc this is now done and included in the latest release [v2.1.0](https://github.com/SeldonIO/seldon-core/releases/tag/v2.1.0)

**Comment by michaln-gc** [comment]
It works. Thanks much :)
