### ISSUE TITLE
Additional parameter types Seldon deployment proto

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/seldon-core#456]
It would be helpful to allow parameter types like LIST and DICT in the [deployment proto](https://github.com/SeldonIO/seldon-core/blob/2e48a87a79f3bee0b00a779e3412728d35ed7466/proto/seldon_deployment.proto).

**Comment by cliveseldon** [comment]
Unlikely to be done until we revamp the way graphs/DAGs are specified. Will close. https://github.com/SeldonIO/mlgraph
Please reopen if this is an urgent need for someone.
