### ISSUE TITLE
Dual Stack support for model pods/services

### ISSUE THREAD

**Issue by sujaykulkarn** [SeldonIO/seldon-core#4564]
Hi Seldon team,

Wanted to know if there is a way to configure ipFamily and ipFamilyPolicies for the Seldon deployment so that it works/binds with both the ipFamilies(IPv4 and IPv6) when deployed in the dual stack lab. (https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services ). Thanks, Sujay

**Comment by cliveseldon** [comment]
Not at present. This may be a useful edition to both v1 and v2 of Seldon Core. For Seldon Core v2 there is only one external facing Service. Can you explain the limitations you are facing by not having this feature?

**Comment by sujaykulkarn** [comment]
Hi @cliveseldon, There are no limitations as such for dual-stack support, but we wanted to configure both the network for the service based on the Cluster's network configuration, Currently Seldon only supports IPv4 I believe, It will be good if we get some configurable options at Seldon deployment level then it might get qualified for IPv6(https://github.com/SeldonIO/seldon-core/issues/3274) as well as dual-stack.
Thanks, Sujay

**Comment by cliveseldon** [comment]
Not presently planned - please re-comment if needed
