### ISSUE TITLE
Restarting seldon-managed deployments results in newly spawned pods terminating

### ISSUE THREAD

**Issue by sebastianmarkow** [SeldonIO/seldon-core#4567]
## Describe the bug
Restarting a seldon-managed deployment will immediately terminate newly spawned pods. 

### Setup
~~~bash
minikube start --kubernetes-version 1.23.13
minikube addons enable metrics-server
helm repo add seldon https://storage.googleapis.com/seldon-charts
helm install -n seldon-system --create-namespace --version=1.15.0 seldon/seldon-core-operator seldon-operator
cat > seldondeployment.yaml <<EOF
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test
  namespace: seldon-serving
spec:
  predictors:
  - annotations:
      seldon.io/svc-name: test
    componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier:1.15.0
          name: mock
    graph:
      name: mock
    name: test
EOF
kubectl create ns seldon-serving
kubectl apply -f seldondeployment.yaml
~~~

### Restarting deployment

~~~
kubectl rollout restart -n seldon-serving deploy test-test-0-mock
~~~

## Expected behaviour
Deployment is restarted, current associated pods are rolledover for newly spawned pods.

## Environment
* Cloud Provider: verified on GKE and Minikube
* Kubernetes Cluster Version 1.23.x
* Deployed Seldon System Images: docker.io/seldonio/seldon-core-operator:1.15.0

## Model Details 
* Mock Classifier: docker.io/seldonio/mock_classifier:1.15.0

**Comment by cliveseldon** [comment]
As the Deployment is managed by the operator this maybe causes a conflict with operator reconcilliation. The question is what is best practice for custom resource managed Deployments and whether `kubectl rollout` is a valid thing to do rather than modifying an annotation on the SeldonDeployment to force an update.

Seems related to [this](https://fluxcd.io/flux/faq/#why-are-kubectl-edits-rolled-back-by-flux) discussion in Flux operator.

**Comment by sebastianmarkow** [comment]
Hey @cliveseldon,

thanks for explaining. I do understand that the deployment resource is owned and managed by the operator - and I'm not knowledgeable enough about the reasons why/how pods are managed by the operator as well. I've never encountered any issues with Flux owned kustomizations to be rolledover - as far as I can see it refers to manually edited resources. E.g. we utilise traffic shifting for treatment testing (A-n test) via Istio, instead of rolling over the deployments we would need to annotate them to inject a new sidecar on an istio version bump (introduces unnecessary commits, require manual checks or additional automation). Just wanted to make sure this is the expected behaviour since it seems counterintuitive to not being able to restart a deployment without resource changes.

**Comment by cliveseldon** [comment]
At present I assume its to do with the operator redoing the Deployment which trickles down but would need to validate the conflict.

**Comment by cliveseldon** [comment]
I think we will close this. A rollout can be done by changing an annotation on the sdep PodSpec which is what `kubectl rollout restart` does by adding a `restartedAt` annotation.

**Comment by B1F030** [comment]
I met this problem too, and resolve with this:
```
kubectl patch seldondeployment -n {namespace} {seldondeploy-name} --type=json -p='[{"op": "replace", "path": "/spec/predictors/0/componentSpecs/0/metadata/annotations/kubectl.kubernetes.io~1restartedAt", "value": "'$(date -u +"%Y-%m-%dT%H:%M:%S+08:00")'"}]'
```
For anyone who might need this.
