### ISSUE TITLE
The output from ambassador converts integer types to float .

### ISSUE THREAD

**Issue by nandagopal1992** [SeldonIO/seldon-core#458]
For instance the output of my s2i wrapped docker images looked like "{"data": "ndarray" : [{"values" : [0,1,2]"}]}" but when the same output comes from ambassador the response looks like "{"data": "ndarray" : [{"values" : [0.0,1.0,2.0]}]}"

**Comment by axsaucedo** [comment]
This has now been fixed in #707 specifically with REST requests
