### ISSUE TITLE
Microservice stays in a loop

### ISSUE THREAD

**Issue by LenaMetzen** [SeldonIO/seldon-core#4587]
## Describe the bug
When calling the client_prediction (microservice) the program stays in a loop and does not terminate.

```
batch = x_test[0]
batch= batch.reshape(1, 28, 28, 1)
endpoint = "localhost:9008"
payload_type = "ndarray"

sc = SeldonClient(microservice_endpoint=endpoint)

client_prediction = sc.microservice(
  data=batch, method="predict", payload_type=payload_type, names=["tfidf"]
)

print(client_prediction)
```

## To reproduce
1. python train.py
2. python test_mnist_model.py
3. python mnistNN.py
4. python test_mnist_nn.py
5. docker build . -t lena246/mnist_seldon:latest
6. docker run -dp 9009:9000 lena246/mnist_seldon:latest
7. python request.py

## Expected behaviour
When calling the predict function (python test_mnist_nn.py) the output is [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]. I would expect this after calling python request.py, too.

## Environment
Docker container

No output after calling python request.py
[mnist_seldon.zip](https://github.com/SeldonIO/seldon-core/files/10419968/mnist_seldon.zip)

**Comment by cliveseldon** [comment]
You may wan to ensure you load your tensorflow model in the `load` metho: see [here](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load).

Please comment further if not working with latest release.
