### ISSUE TITLE
Question: Support for Ambassador for K8s v1.22+ ?

### ISSUE THREAD

**Issue by SebastianScherer88** [SeldonIO/seldon-core#4597]
Are there any plans to provide support for the Ambassador type ingress on AWS EKS for K8s v1.22?

[These docs say there isnt any at the moment.](https://docs.seldon.io/projects/seldon-core/en/latest/install/aws.html)

My team uses EKS with linkerd as a service mesh and has experience with Ambassador but not Istio, so would be a great nice-to-have.

**Comment by cliveseldon** [comment]
We support v2 Ambassador with [this](https://github.com/SeldonIO/seldon-core/pull/4290) PR.
This is a mistake in the docs so we can leave this here until fixed.

**Comment by cliveseldon** [comment]
Also [Seldon Core V2](https://docs.seldon.io/projects/seldon-core/en/v2/) is agnostic to ingress - so will work with most service mesh technologies.

**Comment by SebastianScherer88** [comment]
ah interesting! so you're saying:

- seldon core v1.x is currently supporting amabassador v2.x for k8s v1.22+, and
- seldon core v2.x will be dropping the istio/ambassor dependency altogether?

that sounds really good, thanks for the quick feedback

**Comment by cliveseldon** [comment]
> ah interesting! so you're saying:
> 
>     * seldon core v1.x is currently supporting amabassador v2.x for k8s v1.22+, and
> 
>     * seldon core v2.x will be dropping the istio/ambassor dependency altogether?
> 
> 
> that sounds really good, thanks for the quick feedback

correct
