### ISSUE TITLE
Support GKE autopilot (Ingress controller already works)

### ISSUE THREAD

**Issue by fediazgon** [SeldonIO/seldon-core#4598]
I've installed Seldon on an autopilot cluster successfully even when the [docs](https://docs.seldon.io/projects/seldon-core/en/latest/install/gcp.html) warn against it.

I had no problem when installing the Ingress controller, however, there is a problem if you try to install the `seldon-operator` with `--set usageMetrics.enabled=true`, since it will try to create SAs in the `kube-system` namespace which is managed:

```
Error: UPGRADE FAILED: failed to create resource: services is forbidden: User "xxxx" cannot create resource 
"serviceaccounts" in API group "" in the namespace "kube-system": GKEAutopilot authz: the namespace 
"kube-system" is managed and the request's verb "create" is denied
```

Would it be possible to create these resources elsewhere?

**Comment by cliveseldon** [comment]
Just to validate are you able to get a fully working installation with usage metrics switched off?

**Comment by cliveseldon** [comment]
UsageMetrics creates pods for Spartakus anonymous metrics. If this is restricted in your environment the best solution is to run without usageMetrics.
