### ISSUE TITLE
Document installation using published charts

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#4599]
For Kubernetes, we publish Core V2 charts as GH pages attached to this repository https://github.com/seldonio/helm-charts. 
We should document this as official means of installation for K8s. 

On the side note: we should clearly document that Ansible installation is meant for testing / trial / development purposes only.

**Comment by Rajakavitha1** [comment]
Closing this issue because this is now documented: https://docs.seldon.io/projects/seldon-core/en/v2.6.0/contents/getting-started/kubernetes-installation/helm.html

**Comment by Rajakavitha1** [comment]
Closing the issue because it is now documented: https://docs.seldon.io/projects/seldon-core/en/v2.6.0/contents/getting-started/kubernetes-installation/helm.html
