### ISSUE TITLE
V2: Parameters missing in reponse

### ISSUE THREAD

**Issue by Niklas2501** [SeldonIO/seldon-core#4602]
## Describe the bug

Parameters defined in the model-settings.json are missing in the metadata response of the model. 

## To reproduce

1. Followed the [tutorial for using a PVC as model source](https://docs.seldon.io/projects/seldon-core/en/v2/contents/examples/k8s-pvc.html) with my own model.
2. Besides the standard parts like inputs and outputs i wanted to add additional parameters to the model, especially the "extra" dictionary described [here](https://mlserver.readthedocs.io/en/latest/reference/model-settings.html#mlserver.settings.ModelParameters). For example, i wanted to add the feature names for the inputs. (See the full model-settings.json below)
3. The model was deployed successfully and can be inferenced but the parameters defined in the model-settings.json are not returned (inference as well as meta data call)

![image](https://user-images.githubusercontent.com/24296462/213380043-69fe6653-3e57-4540-9537-59a4b3b2eb26.png)

## Expected behaviour

- The response should contain the parameters defined in the model-settings.json
- Or have I completely misunderstood how the parameters work / what their use case is? If so, a more detailed explanation would be very helpful.

## Environment

Proivder: Rancher Desktop
Architekture: ARM64 / M1 Mac
Kubernetes Cluster Version:
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.4+k3s1
Deployed Seldon System Images: image: docker.io/seldonio/seldonv2-controller:latest

### model-settings.json
```
{
    "name": "sf-model-2",
    "implementation": "mlserver_sklearn.SKLearnModel",
    "inputs":
    [
        {
            "name": "feature-input",
            "datatype": "FP64",
            "shape":
            [
                1,
                6
            ]
        }
    ],
    "outputs":
    [
        {
            "name": "class-output",
            "datatype": "INT64",
            "shape":
            [
                1,
                1
            ]
        }
    ],
    "parameters":
    {
        "extra":
        {
            "param1": 1,
            "param2": 2
        },
        "version": "1.0"
    }
}
```

### model.yaml
```
apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: sf-model-2
  namespace: seldon-mesh
spec:
  storageUri: "/var/models/sf-model-2"
  requirements:
  - sklearn
  - pvc
```

**Comment by adriangonz** [comment]
Hey @Niklas2501 ,

The parameters in the `model-settings.json` file are used to configure the model, as well as some defaults (e.g. default content type when none is specified in the request), but won't be returned with each response. 

The parameters for the response are generally set within the inference runtime itself, and usually represent metadata about the response itself.  

Hope that answers your question! Feel free to reopen if you have any extra queries.

**Comment by adriangonz** [comment]
Hey @Niklas2501 ,

Yes, that's correct. What we've seen so far is that custom parameters generally go attached to custom logic which decides their value, so we haven't considered the use case of returning constant parameters in the response.

**Comment by Niklas2501** [comment]
Ok, thanks again for your help! Have a good day.
