### ISSUE TITLE
In Seldon V2, Model name does not obey, as per the model definition given. It always suffix _1 with it by default

### ISSUE THREAD

**Issue by mmanikan** [SeldonIO/seldon-core#4638]
Model name does not obey, as per the model definition given. It always suffix _1 with it by default.

Say Model name given in definition is iris2. To access the model , I need to use iris2_1 instead of iris2.

```
./seldon model status iris2
{"modelName":"iris2", "versions":[{"version":1, "serverName":"mlserver", "kubernetesMeta":{"namespace":"seldon-mesh", "generation":"1"}, "modelReplicaState":{"0":{"state":"Available", "lastChangeTimestamp":"2023-02-01T17:22:43.423489710Z"}}, "state":{"state":"ModelAvailable", "availableReplicas":1, "lastChangeTimestamp":"2023-02-01T17:22:43.423489710Z"}, "modelDefn":{"meta":{"name":"iris2", "kubernetesMeta":{"namespace":"seldon-mesh", "generation":"1"}}, "modelSpec":{"uri":"gs://seldon-models/mlserver/iris", "requirements":["sklearn"]}, "deploymentSpec":{"replicas":1}}}]}
```
-------------------------------------------
```
ubuntu@ip-172-31-18-30:~/seldon-core/operator/bin$ ./seldon model infer iris2  '{"inputs": [{"name": "predict", "shape": [1, 4], "datatype": "FP32", "data": [[1, 2, 3, 4]]}]}'

**Error: V2 server error: 404 {"error":"Model iris2 not found"}**
```
-------------------------------------------
```
ubuntu@ip-172-31-18-30:~/seldon-core/operator/bin$ ./seldon model infer iris2_1  '{"inputs": [{"name": "predict", "shape": [1, 4], "datatype": "FP32", "data": [[1, 2, 3, 4]]}]}'
{
	"model_name": "iris2_1",
	"model_version": "1",
	"id": "65e7c589-f1f3-4bc3-ab15-0310be20d97f",
	"parameters": {},
	"outputs": [
		{
			"name": "predict",
			"shape": [
				1,
				1
			],
			"datatype": "INT64",
			"data": [
				2
			]
		}
	]
}
```

More details : https://seldondev.slack.com/archives/C03DQFTFXMX/p1675196884908829

```
ubuntu@ip-172-31-18-30:~/seldon-core/operator/bin$ k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-26T15:06:14Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by agrski** [comment]
Hi @mmanikan,

The fact that the naming is different is completely expected.  This is the difference between the model's external and internal names.  Models are internally given a name corresponding to an internal notion of versioning (separate from the Kubernetes understanding of this).  This internal name is picked up by servers like MLServer, which is why model metadata, etc., will return it.

However, you shouldn't need to know the internal name -- you should be able to use the external model name that you originally set (i.e. `iris2` rather than `iris2_1`).  So, that definitely looks like something isn't right.

What's your setup, e.g. Kubernetes in X cloud or `kind` or `k3s`?
What is your config for the `seldon` CLI, as nothing in your commands is setting an inference or scheduler host?
What version of Core v2 are you running?
How recent is your version of the `seldon` CLI?

**Comment by mmanikan** [comment]
What's your setup, e.g. Kubernetes in X cloud or kind or k3s?
 --> k3s
What is your config for the seldon CLI, as nothing in your commands is setting an inference or scheduler host?
--> Used an environment variable to set inference/schedulers host
What version of Core v2 are you running?
--> seldon-core-v2      	seldon-mesh	1       	2023-01-24 19:11:08.844084879 +0000 UTC	deployed	seldon-core-v2-setup-0.1.1  	0.1.1  
How recent is your version of the seldon CLI?
--> Build from source

**Comment by agrski** [comment]
> What version of Core v2 are you running? --> seldon-core-v2 seldon-mesh 1 2023-01-24 19:11:08.844084879 +0000 UTC deployed seldon-core-v2-setup-0.1.1 0.1.1

The 0.x charts are really quite old and aren't recommended.  As you can see [here](https://github.com/SeldonIO/helm-charts/blob/master/helm-charts/seldon-core-v2-setup/Chart.yaml#L2) and [here](https://github.com/SeldonIO/seldon-core/releases/tag/v2.1.0), the current latest release of Core v2 is 2.1 from about 2 weeks ago.

I'm not actually sure how you've got 0.1.1!  It's certainly not available via the our Helm repository:
```
$ helm search repo seldon-charts/seldon-core-v2-setup --versions
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION         
seldon-charts/seldon-core-v2-setup	2.1.0        	2.1.0      	Seldon Core V2 Setup
seldon-charts/seldon-core-v2-setup	2.0.0        	2.0.0      	Seldon Core V2 Setup
seldon-charts/seldon-core-v2-setup	0.4.0        	0.4.0      	Seldon Core V2 Setup
```

Could you try upgrading to the latest release and seeing if your problem persists?

**Comment by mmanikan** [comment]
I have followed this doc - https://docs.seldon.io/projects/seldon-core/en/v2.0.0/contents/getting-started/kubernetes-installation/helm.html

Location : https://github.com/SeldonIO/seldon-core/blob/v2/k8s/helm-charts/seldon-core-v2-setup/Chart.yaml

**Comment by cliveseldon** [comment]
Closing this. Please comment if you think still an issue with latest version.
