### ISSUE TITLE
How can we specify nested python class in .s2i/environment?

### ISSUE THREAD

**Issue by yu-iskw** [SeldonIO/seldon-core#465]
# Motivation
We want to manage the training code and the serving code as well. But, we want to manage the files in a directory. So, our question is can we specify such a nested python class in `.s2i/environment` or not.

# Expectaed Behavior
We want to specify a nested class as below.

## Example .s2i/environment
```
MODEL_NAME=src.v1.IrisClassifier
API_TYPE=REST
SERVICE_TYPE=MODEL
PERSISTENCE=0
```

## Example Directory Structure
```
.
├── IrisClassifier.sav
├── contract.json
├── requirements.txt
├── sklearn_iris.ipynb
├── sklearn_iris_deployment.json
├── src
│   └── v1
│       └── IrisClassifier.py
│       └── train_iris.py
```

## Error Message
```
starting microservice
2019-03-13 17:44:26,507 - seldon_core.microservice:main:261 - INFO:  Starting microservice.py:main
2019-03-13 17:44:26,510 - seldon_core.microservice:main:292 - INFO:  Annotations: {}
Traceback (most recent call last):
  File "/usr/local/bin/seldon-core-microservice", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/seldon_core/microservice.py", line 295, in main
    user_class = getattr(interface_file, args.interface_name)
AttributeError: module 'src.v1.IrisClassifier' has no attribute 'src.v1.IrisClassifier'
```

**Comment by cliveseldon** [comment]
We use [Importlib](https://docs.python.org/3/library/importlib.html)  specifically `importlib.import_module` which should handle the dot notation. We have not tested this case, but we definitely need a story to provide this.

**Comment by jlewi** [comment]
Won't we have problems here

https://github.com/SeldonIO/seldon-core/blob/6b30fb6684d6a156f3b0e8fd5d97a4b162d72797/python/seldon_core/microservice.py#L188

if interface_name contains a dotted path.

e.g. in this case suppose interface_name = "v1.IrisClassifier"

So we end up calling 

```
    interface_file = importlib.import_module("v1.IrisClassifier")
    user_class = getattr(interface_file, "v1.IrisClassifier)
```

The call to getattr is using the full module dotted name of the package which doesn't match the class name; I think it should be 

```
  user_class = getattr(interface_file, "IrisClassifier")
```

Would it make sense to allow the module path and class to be specified separately?

One option would be to just assume everything after the last "." is the class name and everything before is the module you could then parse it doing something like

```
full_module, user_class = args.interface_name.rsplit(".", 1)
```
