### ISSUE TITLE
Allow users to specify namespaces for controller

### ISSUE THREAD

**Issue by shaahmed115** [SeldonIO/seldon-core#4666]
For the current Seldon Core [helm chart](https://docs.seldon.io/projects/seldon-core/en/latest/charts/seldon-core-operator.html), it seems there is no way to provide a list of namespaces , we can only configure it to watch it's own namespace or all namespaces.

Would it be possible to be able to provide a list of namespaces for the operator to watch?

 At some organisations, for instance there is a controller and application namespace for every project, and the operator has to be configured  in each of the controller namespaces to watch just the application namespace.

**Comment by cliveseldon** [comment]
This is not possible as its all namespaces or just 1. All has cluster roles and 1 namespace has roles. There is not easy change to the manager to ignore messages from namespaces other than a given subset. I think at present we will not look into this.
