### ISSUE TITLE
x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by stephen37** [SeldonIO/seldon-core#4700]
## Describe the bug

When using Seldon-Core v1.x and trying to patch SeldonDeployment on K8s 1.24, there is a problem with SHA-1 certificate and the following error appears. 

```
Internal error occurred: failed calling webhook "v1.vseldondeployment.kb.io\": failed to call webhook: Post "[https://seldon-webhook-service.seldon-system.svc:443/validate-machinelearning-seldon-io-v1-seldondeployment?timeout=10s](https://seldon-webhook-service.seldon-system.svc/validate-machinelearning-seldon-io-v1-seldondeployment?timeout=10s)": x509: certificate signed by unknown authority (possibly because of \"x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate 
```

I think it's because K8s 1.24 is using Go 1.19 and Go 1.19 doesn't support SHA-1 anymore due to it being a security issue as you can see here https://github.com/golang/go/issues/41682 

We didn't have a problem when we were running K8s 1.23.13 as it is using Go 1.17.

## To reproduce
1. Have Seldon-Core V1 deployed on K8s 1.24 
2. Deploy a model
3. Try to patch the model running on K8s

## Expected behaviour

We should be able to patch the SeldonDeployment with no problem and we shouldn't have an error about SHA-1 certificate. 

## Environment

* Cloud Provider: AWS 
* Kubernetes Cluster Version : 1.24.10 
* Deployed Seldon System Images: 1.13.0 
* Kops: 1.24.5

## Model Details 

Not relevant here.

**Comment by cliveseldon** [comment]
Are you using certManager to create the certificates?

**Comment by stephen37** [comment]
We do have certManager on the cluster, but we don't use it for Seldon.

**Comment by stephen37** [comment]
We've checked certificate related secrets that we have in `seldon-namespace`, all of them seem to be signed with sha256 algorithm:
```
Signature Algorithm: sha256WithRSAEncryption
```

Also, the certificate that's in use (Admission Controller Webhook Demo CA) is signed by using SHA256. We also have one that's managed by cert-manager, that one is also signed with SHA256, none of those two are expired. caBundle in the webhook manifest is valid one, so I don't know why Kubrentes sees it as SHA-1 signed.
