### ISSUE TITLE
Can't make predicitons on "/api/v1.0/predictions" for R models

### ISSUE THREAD

**Issue by that-rahul-guy** [SeldonIO/seldon-core#4715]
Hello,
We are trying to deploy R models and following [this doc](https://docs.seldon.io/projects/seldon-core/en/latest/R/r_wrapping_docker.html).
[This](https://github.com/SeldonIO/seldon-core/blob/master/incubating/examples/r_iris/r_iris_deployment.json) is the JSON used for deployment.
The Model Pod is running and it is creating 2 SVCs.
![image](https://user-images.githubusercontent.com/100487809/223703764-b41c78dc-2546-4639-b398-3e04971aa301.png)
![image](https://user-images.githubusercontent.com/100487809/223703521-ba53d4ba-d25e-4c05-9548-79699df78253.png)

On one of the SVCs (seldon-deployment-example-r-iris-predictor with port 8000), we are getting /prometheus metrics but  getting `internal server error` while trying to get prediction on /api/v1.0/predictions.
But if we are trying to get predictions on directly /predict (for both the SVCs), it is giving predictions (we inspect that it is directly going to the Plumber API w/o goin through Seldon)

We need to get both `/api/v1.0/predictions` as well as `/prometheus`.

Please let me know what am I doing wrong and guide.
Thanks

**Comment by cliveseldon** [comment]
The R model wrapper is in incubation and at present not planned for further work. We may look into supported [R in MLServer](https://github.com/SeldonIO/MLServer/issues/183). I will close this now as its unlikely we will look into it.

@edshee The doc is in "Archived" section but suggest we remove or renamed as "deprecated".

**Comment by edshee** [comment]
> 

Should be fine to remove in Master. It'll still be there on previous docs builds for anyone running older versions. I'll do that now.
