### ISSUE TITLE
intermittent UNIMPLEMENTED error from ambassador

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#473]
Spotted this in the helm_examples notebook but have also seen in the E2E tests. Was seeing:

```
_Rendezvous: <_Rendezvous of RPC that terminated with:
    status = StatusCode.UNIMPLEMENTED
    details = ""
    debug_error_string = "{"created":"@1553618148.143629760","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"","grpc_status":12}"
```
Might especially affect the A/B test scenario but not sure. Was encountered when testing https://github.com/SeldonIO/seldon-core/pull/445 but it isn't related to that change as has been seen separately.

**Comment by ryandawsonuk** [comment]
Seems to especially affect first request so could be related to https://github.com/datawire/ambassador/issues/504
Also related to https://github.com/grpc/grpc/issues/16515 as 503 is unavailable and it seems this is the behaviour for a network connectivity failure

**Comment by ryandawsonuk** [comment]
Seem to be able to resolve this for tests using https://github.com/SeldonIO/seldon-core/commit/656ac5b07193a54ce182d480c1750e4f16e89cd7#diff-3119fc203a07a67876b8d74d342faceeR44 - have only applied that in a particular branch for now

**Comment by ryandawsonuk** [comment]
I think upgrading to latest ambassador (through https://github.com/SeldonIO/seldon-core/pull/480) also resolves this for the notebooks. I was seeing this intermittently in notebooks and haven't seen it in that branch with the latest ambassador

**Comment by ryandawsonuk** [comment]
Turns out the issue is present in 0.53.1 but can be worked around by setting ambassador to run as root.

Will check again in 0.60.0 - https://github.com/datawire/ambassador/issues/504

**Comment by ryandawsonuk** [comment]
Actually issue still present even when running as root. I managed to recreate the ambassador grpc problem from the helm_examples.ipynb. This time though I didn't uninstall and reinstall ambassador. I just followed the notebook and for the AB test scenario (at which point ambassador has been there for a while) I saw was the grpc calls reporting as failed for a good minute while REST requests worked. It seems the issue actually affects the initial period when a new instance comes online, specifically for A/B tests. Oddly, ambassador logs were reporting that the requests were going through successfully and there were no errors in other logs but the response was clearly a failure:

![image](https://user-images.githubusercontent.com/22754674/55871152-f7559280-5b81-11e9-997a-5698b98be2ee.png)

Eventually grpc requests start working but it can take a whole minute.

We can work around this by downgrading to 0.50.0, even though that means putting references to the ambassador API back down to v0.

**Comment by damitkwr** [comment]
Is this issue still present in Ambassador v73.0?

**Comment by cliveseldon** [comment]
Its not been confirmed or closed by Ambassador : see https://github.com/datawire/ambassador/issues/1587

**Comment by axsaucedo** [comment]
+1

**Comment by lennon310** [comment]
We are using ambassador 0.73.0, and we are having this gRPC issue.  May I have an update on how to resolving this?

**Comment by cliveseldon** [comment]
We need to determine with Ambassador community if this is a Seldon issue or Ambasador issue. If Ambassador we need to evaluate if we continue to support Ambassador long term.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
This issue should be fixed for grpc. There is still the issue of envoy updates not always happening immediately in an Ambassador update which means e2e tests can be flaky.
