### ISSUE TITLE
How to enable cluster wide operator? [v2 version]

### ISSUE THREAD

**Issue by XinSean** [SeldonIO/seldon-core#4735]
Seldon core V2 branch not support cluster wide operator, how to enable this, thx~

**Comment by cliveseldon** [comment]
This is something we are investigating at present.

**Comment by XinSean** [comment]
Got it.  Thanks.

**Comment by Kolajik** [comment]
Hello! Our company would love to see such feature in v2 as well. We [utilize it in Seldon v1](https://docs.seldon.io/projects/seldon-core/en/latest/examples/multiple_operators.html) pretty extensively.

We do have a testing k8s cluster in which users spin up their own namespaces in which they can do whatever they want. Part of it is having Seldon controller in one fixed namespace and inference server with models deployed in user's respective namespaces. As there might be hundreds of namespaces, we do not want to take up resources by duplicating the controller (and more components in Seldon v2) in each namespace.

 - controller lives in namespace `static`
 - `userX` user wants to deploy `inference_server-modelX` into its namespace `user-X`
   - controller does that just fine from `static` namespace
 - `userY` user wants to deploy `inference_server-modelY` into its namespace `user-Y`
   - note that `inferece_server-modelY` has different trained model and version of inference server than `inference_server-modelX` from namespace `user-X`
   - controller does that also from the same `static` namespace

If something similar is to be done with Seldon v2, we expect that Envoy can route traffic into the correct namespaces and servers/models.

**Comment by dtpryce** [comment]
Hey @cliveseldon any potential idea of timeline here? We have a workaround but would definitely appreciate is behaviour being mimicked from V1 to V2 :) thanks!

**Comment by cliveseldon** [comment]
There is a functioning PR -  tests and docs are remaining.https://github.com/SeldonIO/seldon-core/pull/4847
