### ISSUE TITLE
Inference timeouts with transformers pipeline

### ISSUE THREAD

**Issue by SergeyShk** [SeldonIO/seldon-core#4749]
Hello. I'm trying to deploy a transformers pipeline for inference using Seldon Core (1.15.0), but I'm constantly getting timeout errors. The deployment works fine, but when I try to make predictions, the request times out.

Here's a simplified version of the SeldonModel and TransformerModel classes I'm using:

```python
class SeldonModel:
    def __init__(self):
        self.model = TransformerModel()

    def predict(self, features, names=None, meta=None) -> dict[str, Any]:
        return self.model.predict(features["text"])


class TransformerModel(AbstractModel):
    def __init__(self, model: str = MODEL_DIR):
        super().__init__()
        self.model = pipeline("token-classification", MODEL_DIR, aggregation_strategy="first")

```

To run the deployment I'm using:

```dockerfile
CMD ["seldon-core-microservice", "service.seldon.SeldonModel", "--service-type", "MODEL"]
```

I've tried adjusting the timeout values in the Seldon Core configuration file, but that doesn't seem to help. I've also tried running the pipeline locally on my machine, and it works without any issues, so I think the problem is with the Seldon Core deployment.

Has anyone else experienced similar issues with transformers pipelines in Seldon Core? Any suggestions on how to fix this issue or work around it would be greatly appreciated. Thanks in advance!

**Comment by cliveseldon** [comment]
Do you have any logs? Do you prediction requests being made inside your model?

**Comment by SergeyShk** [comment]
What kind of logs do you mean? I don't see any messages in docker logs for example.
Yes, prediction is being made in TransformerModel class here:

`self.model = pipeline("token-classification", MODEL_DIR, aggregation_strategy="first")`

**Comment by cliveseldon** [comment]
Logs from the Pod running the model and the engine in seldon core v1. Be good to understand the predict request makes it to the model when running in k8s.

**Comment by cliveseldon** [comment]
If  you add debug it will run in Flask rather than Gunicorn. This suggests it might be connected to [this](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_component.html#gunicorn-and-load) advice to put model create/load inside load method.

**Comment by SergeyShk** [comment]
I've tried it, nothing changed in terms of service response

**Comment by SergeyShk** [comment]
The only suspicious thing I see is that the model is loaded twice:

```bash
2023-03-20 12:19:10,938 - service.seldon:load:39 - INFO:  Loaded model
2023-03-20 12:19:11,875 - service.seldon:load:39 - INFO:  Loaded model
```

**Comment by cliveseldon** [comment]
This will be for grpc and http endpoints. You can control the number of workers for either [to zero if needed](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_server.html).

**Comment by SergeyShk** [comment]
Hmm, looks like `GRPC_WORKERS=0` helped

**Comment by SergeyShk** [comment]
It looks like that after updating seldom to 1.16.0 the problem has returned. I get timeouts even with `GRPC_WORKERS=0`. Only debug mode helps.
