### ISSUE TITLE
use recommended labels

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#475]
The [process of moving to the ambassador chart ](https://github.com/SeldonIO/seldon-core/pull/445#issuecomment-477953912)has highlighted that the seldon labels aren't in line with the[ k8s recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels). I think this is because the recommended labels are relatively new but the official helm charts use them so it would be good to standardise on that format.

**Comment by ryandawsonuk** [comment]
Our example models/graphs should use them too. It would aid discoverability

**Comment by cliveseldon** [comment]
I believe this is fixed.
