### ISSUE TITLE
Couldn't find http://localhost:5000/api/v1.0/predictions

### ISSUE THREAD

**Issue by onlyone2019** [SeldonIO/seldon-core#4750]
# Describe the bug

I followed this [tutorial](https://github.com/SeldonIO/seldon-core/blob/8004de80ec447d5337d78ef630328584b3177829/examples/models/chainer_mnist/chainer_mnist.ipynb) to build my image `mnist-seldon:v0.0.1` . Then I run a docker container using `docker run --name chainer_mnist -p 5000:5000 mnist-seldon:v0.0.1`. Finally, I used curl to test it, as described in this [tutorial](https://docs.seldon.io/projects/seldon-core/en/latest/workflow/serving.html).
```
curl -X POST \
>     -H 'Content-Type: application/json' \
>     -d data.json \
>      http://localhost:5000/api/v1.0/predictions
```
**Unfortunately, it tells me that the `http://localhost:5000/api/v1.0/predictions` page is not found.**

```
starting microservice
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.17.0.1 - - [20/Mar/2023 12:50:24] "POST /api/v1.0/predictions HTTP/1.1" 404 -
172.17.0.1 - - [20/Mar/2023 12:51:07] "POST /api/v1.0/predictions HTTP/1.1" 404 -
172.17.0.1 - - [20/Mar/2023 12:51:52] "POST /api/v1.0/predictions HTTP/1.1" 404 -
```

Interestingly,I tested `seldon-core-tester contract.json 0.0.0.0 5000 -p`, and got the right reply.

Why?

**Comment by onlyone2019** [comment]
I have found the right API `http://localhost:5899/predict`.

**Comment by cliveseldon** [comment]
Have you built with latest version - the docs presently say 
```
s2i build . seldonio/seldon-core-s2i-python37-ubi8:1.7.0-dev chainer-mnist:0.1
```

Can you try building with latest: https://hub.docker.com/repository/docker/seldonio/seldon-core-s2i-python38-ubi8/general

**Comment by cliveseldon** [comment]
Please retry with MLServer
