### ISSUE TITLE
seldon mlflow failure at conda env creation

### ISSUE THREAD

**Issue by arunbenoyv** [SeldonIO/seldon-core#4751]
## Describe the bug

Mlflow pre-packaged server is failing at conda env create stage with error

Executing before-run script
---> Creating environment with Conda...
INFO:root:Copying contents of /mnt/models to local
INFO:root:Reading MLmodel file
Traceback (most recent call last):
  File "./conda_env_create.py", line 151, in <module>
    main(args)
  File "./conda_env_create.py", line 146, in main
    setup_env(model_folder)
  File "./conda_env_create.py", line 51, in setup_env
    env_file_path = os.path.join(model_folder, env_file_name)
  File "/opt/conda/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/opt/conda/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'dict'

In the error i do see python 3.7 is refrenced , please note the model is built with 3.9 as you can see in the yamls below
## To reproduce

**Kubernetes files** 
_secret.yaml_

apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: AWS
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: "" 
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "" 
  RCLONE_CONFIG_S3_ENV_AUTH: "true"
  RCLONE_CONFIG_S3_REGION: us-west-2

_deployment.yaml_

apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  annotations:
    annotations.iam.amazonaws.com/role: dummyvalue 
  name: wine
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://dummybucket/model/
        name: classifier
        envSecretRefName: seldon-rclone-secret
      name: default
      replicas: 1

##Files under mlflow folder in S3
_MLmodel_

artifact_path: model
databricks_runtime: 12.0.x-cpu-ml-scala2.12
flavors:
  python_function:
    env:
      conda: conda.yaml
      virtualenv: python_env.yaml
    loader_module: mlflow.sklearn
    model_path: model.pkl
    predict_fn: predict
    python_version: 3.9.5
  sklearn:
    code: null
    pickled_model: model.pkl
    serialization_format: cloudpickle
    sklearn_version: 1.0.2
mlflow_version: 2.0.1
model_uuid: dummyvalue
run_id: dummyvalue
utc_time_created: '2023-03-18 12:49:40.088440'

_conda.yaml_

channels:
- conda-forge
dependencies:
- python=3.9.5
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - typing-extensions==4.1.1
name: mlflow-env

## Expected behaviour

Mlflow pre-packaged server should not fail at conda env create stage

## Environment
Cloud Provider: AWS
Kubernetes Cluster Version : v1.23.15
Deployed Seldon System Images: seldon-core-operator:1.15.0, seldon-core-executor:1.15.0
ML Flow model created with Databricks : 12.0.x-cpu-ml-scala2.12

**Comment by arunbenoyv** [comment]
Ok, is the helm chart 1.16.0-dev a stable version which can be used for deployment?

**Comment by adriangonz** [comment]
Most likely it's a timeout issue - you can find more info on the docs:

https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#conda-environment-creation

If you keep having issues, feel free to open a new issue though.
