### ISSUE TITLE
Seldon v2 support for custom python models

### ISSUE THREAD

**Issue by aishwaryagirish** [SeldonIO/seldon-core#4752]
Hi,
Does seldon v2 provide support for custom python models? Like if I want to deploy a tensorflow, keras, onnx models etc., is that possible? If yes, can you please point me to it?
Thank you

**Comment by cliveseldon** [comment]
See [this](https://docs.seldon.io/projects/seldon-core/en/v2/contents/models/inference-artifacts/index.html) page
