### ISSUE TITLE
Remove old Kafka docs for Strimzi

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#4757]
Remove old kafka docs and refer to ansible install [here](https://docs.seldon.io/projects/seldon-core/en/v2/contents/kubernetes/kafka/index.html)

**Comment by Abhinavfreecodecamp** [comment]
Hi @cliveseldon could you please share link to old kafka docs you want to remove for new ones ? as I can start working on this.

**Comment by RafalSkolasinski** [comment]
The strimzi doc are now in good state. This issue can be closes
