### ISSUE TITLE
use official helm charts

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#476]
Much as with https://github.com/SeldonIO/seldon-core/issues/258 but for the redis in https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-core/templates

We could use https://github.com/helm/charts/tree/master/stable/redis

**Comment by ryandawsonuk** [comment]
Other examples:

locust:
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-loadtesting/templates/locust-master.yaml
https://github.com/helm/charts/tree/master/stable/locust

kafka:
https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-core-kafka
there are options on this one but could be
https://github.com/helm/charts/tree/master/incubator/kafka
or wait for it to move to stable

Prometheus:
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-analytics/templates/prometheus-deployment.json
https://github.com/helm/charts/tree/master/stable/prometheus

Grafana:
https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-analytics/templates/grafana-prom-deployment.json
https://github.com/helm/charts/tree/master/stable/grafana

**Comment by cliveseldon** [comment]
Fixed

**Comment by ryandawsonuk** [comment]
@cliveseldon did we close this prematurely? I don’t see helm requirements.yaml files in analytics for example

**Comment by cliveseldon** [comment]
Yes you are right. Let me open a new one specifically for the analytics component.
