### ISSUE TITLE
Support for modifying container name - seldon-container-engine

### ISSUE THREAD

**Issue by harshitasaxena05** [SeldonIO/seldon-core#4765]
Hi team,

Observed that container names are hardcoded in seldon.  There should be a provision to change that during deployment.

EngineContainerName     = "seldon-container-engine"     

https://github.com/SeldonIO/seldon-core/blob/v1.14.1/operator/controllers/seldondeployment_engine.go#L58

Thanks.

**Comment by cliveseldon** [comment]
not planned
