### ISSUE TITLE
Support to pass allowPrivilegeEscalation: false parameter to all containers in seldon-deployment.

### ISSUE THREAD

**Issue by Tejasbglr** [SeldonIO/seldon-core#4766]
Hi Community,

We have deployed Seldon ( 1.14.1) in a cluster where allowPrivilegeEscalation is set to false by default and readOnlyRootFilesystem is set to true. 

We tried with the sample seldon deployment but we are facing the below issue.

Seldon deployment is not coming up, please find the logs below 

```
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  14s (x15 over 97s)  replicaset-controller  Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [psp-allow-privilege-escalation-container] Privilege escalation container is not allowed: seldon-container-engine
```

Please let us know how to pass the security context parameter ( allowPrivilegeEscalation: false ) for all the containers which come as part of seldon deployment.

**Comment by poornachandratejasvi** [comment]
HI , even im facing this issue when OPA is enabled in kubernates cluster, any one can help in resolving this issue  ?

**Comment by RafalSkolasinski** [comment]
SeldonDeployment CRD allows to specify PodSpec https://docs.seldon.io/projects/seldon-core/en/latest/reference/seldon-deployment.html - did you try to provide security context this way to your deployment?
