### ISSUE TITLE
deprecate ksonnet

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#477]
Due to https://github.com/ksonnet/ksonnet/commit/8b64c6082179cbeac56ef8aff129e3d63a2b6f00

**Comment by cliveseldon** [comment]
We will remove the ksonnet folder at some point but the previous version of the [install docs](https://docs.seldon.io/projects/seldon-core/en/v0.2.7/workflow/install.html) refers to the master branch which means this will stop working if we delete the folder.

We could create a bug fix just to update the docs?

**Comment by cliveseldon** [comment]
Fixed
