### ISSUE TITLE
Addressable placeholder no longer needed ?

### ISSUE THREAD

**Issue by matzew** [SeldonIO/seldon-core#4773]
Looking here, I see a placeholder for `Addressable`:
* https://github.com/SeldonIO/seldon-core/blob/master/operator/apis/machinelearning.seldon.io/v1/seldon_deployment_status.go#L35-L40

The referenced `controller-tools` issue does point me to this fixed issue on `knative/pkg`:
https://github.com/knative/pkg/pull/2431

Perhaps worth to revisit this?

**Comment by cliveseldon** [comment]
If you can create a PR we could consider it seems its mostly a code cleanup issue unless we are missing functionality/compatibility  somewhere?

**Comment by cliveseldon** [comment]
Not planned
