### ISSUE TITLE
Update Knative Eventing examples

### ISSUE THREAD

**Issue by matzew** [SeldonIO/seldon-core#4778]
The Knative Eventing examples in here:
* https://github.com/SeldonIO/seldon-core/blob/d0437e499c0b1b6d11acaf0909fe42109fac942e/examples/streaming/knative-eventing/README.md
* https://github.com/SeldonIO/seldon-core/blob/e7bde6d9bb73537ea9a117e1db4f89d69dfb9fa8/doc/source/streaming/knative_eventing.md

are using outdated (unsupported) APIs, such as `Trigger` in `v1alpha1` and `v1beta1`.

In contrast this Elastic Search [here](https://github.com/SeldonIO/seldon-core/blob/d0437e499c0b1b6d11acaf0909fe42109fac942e/examples/feedback/feedback-metrics-server/README.md) already uses the latest `v1` APIs.

One aspect of the documentation is also that the ingress URL for the broker in the two outdated examples is wrong, since it changed, hence may lead to problems when trying the tutorial with a "recent" version of Knative Eventing (1.9 is the latest release).

**Comment by aliok** [comment]
I guess this would be a nice "good-first-task"

**Comment by MuhammadAgf** [comment]
Hi, may I work on this?

**Comment by RafalSkolasinski** [comment]
Sounds good

**Comment by Abhinavfreecodecamp** [comment]
Maybe asking an trivial one but for which branch the PR needed to be created as `v2` is a release branch would it be `master` ? @matzew @RafalSkolasinski @aliok

**Comment by cliveseldon** [comment]
@Abhinavfreecodecamp  this would be a PR for master

**Comment by cliveseldon** [comment]
Fixed by #4886
