### ISSUE TITLE
SeldonCore v1  Kafka Server - Support of inference protocol v2 with grpc transport

### ISSUE THREAD

**Issue by giulianc-65** [SeldonIO/seldon-core#4789]
https://github.com/SeldonIO/seldon-core/blob/dfb705c89add7f6836257b8c2910b4dee8bb0663/executor/api/kafka/server.go#L92-L98

SeldonCore v1 Kafka Server is currently not supporting the usage of grpc transport in case of protocol v2 (aka kfserving).
Sending protocol v2 inference request with protobuffer binary serialization to kafka topic results in decoding error or in POD crashes if metadata (i.e. Kafka message header) is also sent trying to follow what reported in SCv1 documentation (https://docs.seldon.io/projects/seldon-core/en/latest/streaming/kafka.html) 

SCv1 documentation in fact states that 
"Create requests streams for the input prediction of your specified protocol and transport.
For REST: the JSON representation of a predict request in the given protocol.
For gRPC: the protobuffer binary serialization of the request for the given protocol. You should also add a metadata field called proto-name with the package name of the protobuffer so it can be decoded, for example tensorflow.serving.PredictRequest. We can only support proto buffers for native grpc protocols supported by Seldon."

That needs to be updated with what will be applicable in case of usage of inference protocol v2.

It would be nice to have a solution that avoids usage of transport specification rest/grpc in sdep CRD (as in SeldonCorev2).

**Comment by giulianc-65** [comment]
What do you mean by PR ? A Pull Request, i.e. I provide related code changes to solve the issue ?

**Comment by agrski** [comment]
@giulianc-65 Yes, exactly this

**Comment by giulianc-65** [comment]
I'm sorry , but I cannot take care of that: I'm not a Go developer, I don't have a full understanding of the Seldon Core code

**Comment by cliveseldon** [comment]
Please use core v2 for Kafka support for Open Inference Protocol
