### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#4803]
Python 3.7 will be End-Of-Life in a few months, however we still have a few pre-packaged servers and wrappers running with Python 3.7 by default.

https://endoflife.date/python

As part of this issue, we should explore bumping these to Python 3.8+.

**Comment by adriangonz** [comment]
Hey @Abhinavfreecodecamp ,

We're just getting started on this one. This is relevant just for the v1 images (i.e. not MLServer - which has its own separate set of images). Therefore, it includes updating:

1. The V1 pre-packaged servers (i.e. the ones under the `./servers` folder).
2. The Alibi Explain and Alibi Detect V1 servers (i.e. the ones under the `./components` folder).
3. Updating any demo artefact that needs re-training to work under Python 3.8.

`1.` should be relatively straightforward (:crossed_fingers: ), but I expect more headaches with `2.` and `3.`.

**Comment by Abhinavfreecodecamp** [comment]
> Hey @Abhinavfreecodecamp ,
> 
> We're just getting started on this one. This is relevant just for the v1 images (i.e. not MLServer - which has its own separate set of images). Therefore, it includes updating:
> 
> 1. The V1 pre-packaged servers (i.e. the ones under the `./servers` folder).
> 2. The Alibi Explain and Alibi Detect V1 servers (i.e. the ones under the `./components` folder).
> 3. Updating any demo artefact that needs re-training to work under Python 3.8.
> 
> `1.` should be relatively straightforward (:crossed_fingers: ), but I expect more headaches with `2.` and `3.`. 

Sure @adriangonz let start working through it. Thanks

**Comment by Abhinavfreecodecamp** [comment]
@adriangonz if there is any ongoing PR then please could you share the link as I didn't find any if not then I'll will start working on fresh one.

**Comment by adriangonz** [comment]
Fixed by #4910 and #4912
