### ISSUE TITLE
Cannot change Deployment labels when `--create-resources=true`

### ISSUE THREAD

**Issue by bcbrockway** [SeldonIO/seldon-core#4804]
## Describe the bug
The `--create-resources` setting relies on a YAML manifest for the webhook Service that is copied to the image at build time (see [here](https://github.com/SeldonIO/seldon-core/blob/ddcbf7fd1110e7dcad31aa5aac40908addb105ac/operator/utils/k8s/initializer.go#L120) and [here](https://github.com/SeldonIO/seldon-core/blob/ddcbf7fd1110e7dcad31aa5aac40908addb105ac/operator/Dockerfile#L56)) however this means that you can never change the labels of the Seldon Core Operator deployment because it will always create a Service that selects pods based on those hard-coded labels.

## To reproduce
1. Deploy Seldon Controller Manager with different `app.kubernetes.io/instance`, `app.kubernetes.io/name`, etc. pod labels and `--create-resources` enabled.

## Expected behaviour
Seldon Controller Manager will create a Kubernetes Service that selects the pods in its deployment.

## Environment
* Cloud Provider: EKS
* Kubernetes Cluster Version: v1.24.12-eks-ec5523e
* Deployed Seldon System Images:
  * docker.io/seldonio/engine:1.12.0
  * docker.io/seldonio/seldon-core-executor:1.12.0
  * docker.io/seldonio/seldon-core-operator:1.12.0

**Comment by cliveseldon** [comment]
Not planned as this flag is mostly for Openshift coverage
