### ISSUE TITLE
Alternative to seldon-request-logger in order to dump logs to Elasticsearch

### ISSUE THREAD

**Issue by ysk24ok** [SeldonIO/seldon-core#4813]
Even after I read https://docs.seldon.io/projects/seldon-core/en/latest/analytics/logging.html, I'm not quite sure how to dump logs (request/response) to Elasticsearch. When I specify a knative broker url to `logger.url` field, I need a knative trigger and a knative service which the trigger sends an event to, and which dumps logs to ES.
The knative service used to be `seldon-request-logger` component, but it was deleted as part of #4013. #4033 was supposed to provide an example but it looks like it ended up being closed without adding any example.
It'd be great if you could provide an example to do it. Thank you in advance!

**Comment by cliveseldon** [comment]
For Seldon Core V2 everything is in kafka topics so you can connect those where you wish. For Seldon Core V1 you would need something to handle the cloud events. We deprecated the request logger as it was only an example but could use the old version as an example.
