### ISSUE TITLE
Any way to filter logs on the service orchestrator side?

### ISSUE THREAD

**Issue by ysk24ok** [SeldonIO/seldon-core#4816]
In case a SeldonDeployment processes a bunch of requests, logging all of the requests/responses causes big loads on the log store such as Elasticsearch. Thus sampling requests/responses on the service orchestrator (executor) side is beneficial in such a case.
Is there any way to do this and if not is there a plan to implement this feature?

**Comment by cliveseldon** [comment]
It has been something we have considered for some time to allow a simple sample rate specification. 

For V2 we use Kafka as a backbone so you can choose how you push from Kafka topics to a metrics store and Kafka itself is more suited to high volume scenarios.

**Comment by agrski** [comment]
Also worth noting that in Core v1 individual requests can decline to be logged by using [a header](https://github.com/SeldonIO/seldon-core/blob/988fadfbc132688a0c942abb0c49bc1c62c166cf/executor/api/payload/metadata.go#L9).  This is handled [here](https://github.com/SeldonIO/seldon-core/blob/988fadfbc132688a0c942abb0c49bc1c62c166cf/executor/predictor/predictor_process.go#L404) in the Core v1 executor.

Obviously this isn't Core v1 itself sampling, but it does allow some process to inject this header, either randomly or for particular requests.

**Comment by ysk24ok** [comment]
@agrski Thank you for sharing it. If I understand correctly, a client has to send a request with `Seldon-Skip-Logging: true` header to a SeldonDeployment, meaning we'd need to update the client to have the header.
I could use it in the meantime, but it'd be great if Seldon Core v1 itself handles this. Is there any plan for this?

**Comment by cliveseldon** [comment]
Not planned for Core V1
