### ISSUE TITLE
seldon-agent dont tolerate model-settings.json

### ISSUE THREAD

**Issue by Maksim-Siniugin** [SeldonIO/seldon-core#4819]
## Describe the bug
MLserver 1.3.0+ provide feature with model tarball [environment](https://mlserver.readthedocs.io/en/1.3.1/reference/model-settings.html#mlserver.settings.ModelParameters.environment_tarball).
Seldon agent on model deploy rewrite model-settings.json file from model s3 repository and delete environment_tarball key from model configuration

## To reproduce
1. deploy any model with environment tarball and model-settings.json like this:
```
{
    "name": "test",
    "implementation": "mlserver_mlflow.MLflowRuntime",
    "parameters": {
        "uri":"./",
        "environment_tarball": "environment.tar.gz"
    }
}
```
2. after deploy seldon agent rewrite file, and it looks like this:
```
$ cat /mnt/agent/models/test_1/1/model-settings.json 
{"name":"test_1","implementation":"mlserver_mlflow.MLflowRuntime","parameters":{"uri":"./","version":"1"}}
```
environment_tarball parameter is missed

## Expected behaviour
Seldon agent must copy model-settings.json file from the model repository, or transfer all parameters to a new model-settings.json file

## Environment
docker.io/seldonio/seldon-agent@sha256:b72c7f22f31235efd655420e1c34cc1d8f34622ccc2fec35f3c37af317f3425e
docker.io/seldonio/seldon-rclone@sha256:a03cb24f148bebe0b4f8725c74fa79de87bae478d620726206a33fbfd01c6fad
docker.io/seldonio/mlserver@sha256:e7e7d48821d408d3e19f260016566c806cbeeda7c168ff2d073a6077d07c1e9c

**Comment by agrski** [comment]
It sounds like the `agent` is simply overwriting the `parameters` instead of merging these.  Should be a straightforward fix.

**Comment by MiF36rus** [comment]
> It sounds like the `agent` is simply overwriting the `parameters` instead of merging these. Should be a straightforward fix.
i couldn't find source code of seldon agent to confirm this

**Comment by cliveseldon** [comment]
It ma be because this struct does not contain `environment_tarball` https://github.com/SeldonIO/seldon-core/blob/006af7b290b07b61bd4165a691eaa073ee336977/scheduler/pkg/agent/repository/mlserver/mlserver.go#L80-L90

We should check the full list of allowed values and add?

**Comment by MiF36rus** [comment]
> It may be because this struct does not contain `environment_tarball`
> 
> https://github.com/SeldonIO/seldon-core/blob/006af7b290b07b61bd4165a691eaa073ee336977/scheduler/pkg/agent/repository/mlserver/mlserver.go#L80-L90
> 
> We should check the full list of allowed values and add?

I think yes.
I only need "environment_tarball" parameter, but other people may need the full set of parameters that can be specified in this place. Here is reference of parameters.
https://mlserver.readthedocs.io/en/1.3.1/reference/model-settings.html#extra-model-parameters

**Comment by cliveseldon** [comment]
This should be fixed in master if you can test?
