### ISSUE TITLE
Enable SASL_SSL kafka protocol with PLAIN mechanism

### ISSUE THREAD

**Issue by RafalSkolasinski** [SeldonIO/seldon-core#4828]
When using in example managed Kafka from Confluent Cloud, the provided config may correspond to `SASL_SSL` protocol with `PLAIN` mechanism.

```bash
# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=<broker servers uri>:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=<user>
sasl.password=<password>

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000
```

however we currently do not support this

https://github.com/SeldonIO/seldon-core/blob/17c37214877706f9fd485a7093c54c33cad4095b/scheduler/pkg/kafka/config/tls.go#L34-L45

which leads to e.g. following errors from Pipeline Gateway microservice

```
time="2023-05-03T20:59:50Z" level=info msg="Options:prefix= validationPrefix=KAFKA_BROKER clientset=<nil>" source=CertificateStore
time="2023-05-03T20:59:50Z" level=info msg="Just looking for validation cert" source=CertificateStore
time="2023-05-03T20:59:50Z" level=info msg="Getting validation certificate for KAFKA_BROKER" source=CertificateStore
time="2023-05-03T20:59:50Z" level=fatal msg="Failed to create kafka manager" error="open /tmp/certs/kafka/broker/ca.crt: no such file or directory"
```

**Comment by RafalSkolasinski** [comment]
Note: this is covering case not-covered by prior https://github.com/SeldonIO/seldon-core/issues/4415 solved by https://github.com/SeldonIO/seldon-core/pull/4416

**Comment by RafalSkolasinski** [comment]
For clarification. One thing we need to include is definitely option to set `sasl.mechanism` to `PLAIN` as now it is hard-coded to `SCRAM-SHA-512`. The other thing to decide is weather we could make `ssl.client.brokerValidationSecret` optional and change base from `ubi-micro` to `ubi-minimal` such that it comes with `ca-certificates` package and can work with e.g. Confluent Kafka out of the box.

**Comment by RafalSkolasinski** [comment]
In https://github.com/SeldonIO/seldon-core/pull/4831 we make sure that `ubi-minimal` certificates `/etc/ssl/certs/ca-bundle.crt` are available under location that pipeline/model gateway or dataflow engine expects them, `/tmp/certs/kafka/broker/ca.crt`. We also make sure that `/tmp/certs/` is write-able such that if certificates are provided via secrets / helm values we can read them from it and write there.

**Comment by SDJustus** [comment]
Hi @RafalSkolasinski, is there a way you can have a look at SSL Connection to Kafka without the use of mTLS as specified [here](https://github.com/SeldonIO/seldon-core/pull/4658) as well?

**Comment by RafalSkolasinski** [comment]
@SDJustus - yes, we can look into this next, sounds useful. Do you have a specific Kafka provider in mind for this use case? 

As the PR you linked does not reference any issue, it may be worth opening one. 

P.S. This issue here is now closed via https://github.com/SeldonIO/seldon-core/pull/4831

**Comment by SDJustus** [comment]
Hi @RafalSkolasinski, the Provider I'd like to use is AWS MSK... Since the Secrurity Aspaects can be enforced using AWS landscape, we don't need to use mTLS. Shall I open a Issue for this?

**Comment by RafalSkolasinski** [comment]
So basically the security is PLAIN (no SASL and no mTLS) but you want to have one sided TLS on brokers?
