### ISSUE TITLE
Add imagePullSecret to seldon-core-operator

### ISSUE THREAD

**Issue by ekhaydarov** [SeldonIO/seldon-core#4849]
## Describe the bug

You are not able to pull an image through a private repository because the chart does not have the capability to add imagePullSecrets to add docker credentials to service account/pod.

## To reproduce
Try and pull any private image

## Expected behaviour
can pull a private image

[Here](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/serviceaccount.yaml#L4) is an example of adding imagePullSecrets to service account so that it can authenticate pods docker images

## Environment
not important.

**Comment by RafalSkolasinski** [comment]
Please see https://github.com/SeldonIO/seldon-core/issues/4140#issuecomment-1165316812 for workaround on how to attach docker image pull secrets to the service accounts used by Core v1.
