### ISSUE TITLE
Deployment of seldon as a new custom resource via fabric8

### ISSUE THREAD

**Issue by OrBarda** [SeldonIO/seldon-core#486]
Hi,

we are trying to integrate Seldon into our pipeline in the company, and a part of it is the deployment of some Seldon deployment into our CI environment using an in house plugin built on top of the fabric8 client.
There is no documentation for deployment using fabric8, but maybe you have tried it on and can help with it.
We also created an issue in fabric8's git. fabric8io/kubernetes-client#1461

Thanks in advance.

**Comment by ryandawsonuk** [comment]
As it happens I did do something to deploy the custom resource with the fabric8 client. Actually I was aiming to deploy custom resources in general with the seldon one as a particular example and found it was quite awkward to do this without first creating java classes to represent each particular custom resource - https://github.com/fabric8io/fabric8-maven-plugin/issues/1377#issuecomment-459969325. This makes handling custom resources a general problem for the fabric8 maven plugin as you can't add new classes to the maven plugin when you want to deploy a new type of custom resource. Perhaps it's a challenge for your in house system too.

I was working with my own project and aiming to support any kind of custom resource deployment with fabric8. I did manage to get something working - https://github.com/ryandawsonuk/crdtester/blob/df0c2752d1af309aead960bc7714a90ccffe5d59/src/main/java/org/k8sclient/crdtester/services/deploy/Fabric8DeployService.java
and deploying a seldon model
https://github.com/ryandawsonuk/crdtester/blob/df0c2752d1af309aead960bc7714a90ccffe5d59/src/main/resources/model.json

I was only deploying the custom resource and [not the custom resource definiton](https://github.com/ryandawsonuk/crdtester/issues/3) with fabric8 - I was assuming that the CRD would already be present, though I think that could be handled too.

**Comment by cliveseldon** [comment]
@OrBarda Can we close this?

**Comment by cliveseldon** [comment]
closing. Please reopen if issue.
