### ISSUE TITLE
Use one-sided TLS for Kafka communication

### ISSUE THREAD

**Issue by SDJustus** [SeldonIO/seldon-core#4870]
Following on @RafalSkolasinski work at #4828, it would be nice for client side authentication to be optional when using SSL (at the moment only SASL and mTLS are possible). 

The use case is not having to maintain client side certificates, if the security aspect is covered by other infrastructure, such as having the Cluster and the Kafka in the same VPC in an AWS Environment.

#4658 already did some work on this, so maybe this could be a supported mechanism for connecting a Kafka broker to seldon-core v2.

**Comment by RafalSkolasinski** [comment]
@SDJustus thanks for opening the issue! W

Would be great to have some example Kafka configuration that illustrated desired consumer/producer config.

**Comment by SDJustus** [comment]
Of course.
This would be the broker settings (AWS MSK):
![Screenshot from 2023-05-26 13-05-31](https://github.com/SeldonIO/seldon-core/assets/44165116/1d9740d7-5a55-4e9f-8356-afa1db994b4b)

Kafka Client Security Settings (i.e. from a Spring Boot Application):
```
security.protocol: SSL
ssl.endpoint.identification.algorithm: HTTPS
```

Let me know, if you need further information. Thanks for having a look on this.

**Comment by RafalSkolasinski** [comment]
@SDJustus is the `ssl.endpoint.identification.algorithm: HTTPS` option just cherry on top or required for it to work properly?

**Comment by SDJustus** [comment]
I just checked the confluence [page](https://docs.confluent.io/platform/current/kafka/authentication_ssl.html) and https seems to be the default.. Therefore I don't think it needs to be specified.

**Comment by RafalSkolasinski** [comment]
closed via https://github.com/RafalSkolasinski/seldon-core/pull/131

**Comment by RafalSkolasinski** [comment]
closed via https://github.com/SeldonIO/seldon-core/pull/4916

**Comment by SDJustus** [comment]
Will take a look. Thank you very much for implementing!
