### ISSUE TITLE
S3 secret keys are printed into K8s logs

### ISSUE THREAD

**Issue by pmuilu** [SeldonIO/seldon-core#4903]
Seldon seems to print S3 secret keys into K8s logs.

## Describe the bug

Example:

kubectl logs -n my_namespace lgbtest-default-0-classifier-5c9fc46cf7-xkgmj classifier-model-initializer

2023/06/08 11:02:13 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "copy" "-vv" "s3://mlflow/0/e4373918554f4ed5b4adf7d62f9c4146/artifacts/model" "/mnt/models"]
2023/06/08 11:02:13 DEBUG : Creating backend with remote "s3://mlflow/0/e4373918554f4ed5b4adf7d62f9c4146/artifacts/model"
2023/06/08 11:02:13 DEBUG : Setting type="s3" for "s3" from environment variable RCLONE_CONFIG_S3_TYPE
2023/06/08 11:02:13 DEBUG : Setting provider="minio" for "s3" from environment variable RCLONE_CONFIG_S3_PROVIDER
2023/06/08 11:02:13 DEBUG : Setting env_auth="false" for "s3" from environment variable RCLONE_CONFIG_S3_ENV_AUTH
2023/06/08 11:02:13 DEBUG : Setting access_key_id="AKIA..." for "s3" from environment variable RCLONE_CONFIG_S3_ACCESS_KEY_ID
2023/06/08 11:02:13 DEBUG : Setting secret_access_key="**SECRET ACCESS KEY AS A PLAIN TEXT**" for "s3" from environment variable RCLONE_CONFIG_S3_SECRET_ACCESS_KEY

## Environment
Charmed Kubeflow + Mlflow + Seldon, on-prem KOps based K8s

**Comment by RafalSkolasinski** [comment]
@pmuilu please provide version of Seldon Core you are using - we have decreased the verbosity of logging some time ago

**Comment by RafalSkolasinski** [comment]
@pmuilu could you confirm if you also observe the issue using latest Seldon Core?

**Comment by cliveseldon** [comment]
Closing - please update if still an issue with latest release
