### ISSUE TITLE
Dependency Hell when using pytorch-lighting and seldon-core

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [SeldonIO/seldon-core#4904]
## Describe the bug

- When I try looking into running an ML microservice with pytorch-lightning, I noticed that it's causing pip to cause dependency conflict. I realized it seems like a [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) as seldon-core seems to be tied hardly to `itdangerous==1.1.0`.
```
  ERROR: Cannot install lightning and seldon-core because these package versions have conflicting dependencies.
Discarding itsdangerous==1.1.0 (from -r requirements.txt (line 32)) to proceed the resolution
  ERROR: Cannot install lightning and seldon-core because these package versions have conflicting dependencies.
Traceback (most recent call last):
  File "/home/hello34/mambaforge/envs/piptools/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 316, in _backjump
    name, candidate = broken_state.mapping.popitem()
KeyError: 'dictionary is empty'

During handling of the above exception, another exception occurred:
```

## To reproduce

1. Install both `pytorch-lightning` and `seldon-core`

## Environment

* Cloud Provider: GKE
* Kubernetes Cluster Version: 

```
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.24.12-gke.500
```

* Deployed Seldon System Images: [Output of `kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio`]

```
value: docker.io/seldonio/seldon-core-executor:1.14.1
image: docker.io/seldonio/seldon-core-operator:1.14.1
```

**Comment by cliveseldon** [comment]
Please retry on MlServer
