### ISSUE TITLE
mlflow server as modelUri

### ISSUE THREAD

**Issue by amin-oj** [SeldonIO/seldon-core#4906]
Hi
i want to use mlflow server directly to deploy models using seldon-core rather that using the storage bucket. similar to what we have with mlflow itself where we can serve a specific version or stage of the model.

for example, instead of this:
modelUri: s3://mlflow/end-to-end/elasticnet_wine_model/

i want to config seldon, so that it connects to the mlflow server and deploys the latest or a specific version, or a specific stage of a registered model.

is this possible with seldon-core?

**Comment by cliveseldon** [comment]
We don't have plans to support direct connections to an MLFlow server. We support all artifact locations supported by rclone.
