### ISSUE TITLE
v2 model version is not catch up from model-settings.json

### ISSUE THREAD

**Issue by T1murKO** [SeldonIO/seldon-core#4907]
## Describe the bug

I want to serve multiple models using mlserver with different versions and query it with appropriate endpoint.
I checked this mlserver [guide](https://mlserver.readthedocs.io/en/stable/examples/mms/README.html) where `model-settings.json` file was used and model version specified via:
```
 "parameters": {
        "version": "v0.1.0"
    }
```
I did the same, but when my iris model started no version was there in metadata. Am I doing something wrong to specify model version?

## To reproduce
Use model from local iris example, but add
`model-settings.json` to the model folder
```
{
    "name": "iris",
    "implementation": "mlserver_sklearn.SKLearnModel",
    "parameters": {
        "version": "v0.1.0"
    }
}
```

## Expected behaviour
Model version appear in model metadata and in prediction route.

## Environment

v2 local deployment

**Comment by sakoush** [comment]
At present we only support one model version (`latest`) to be deployed at any particular point in time and therefore from seldon core v2 perspective the `version` in `model-settings.json` is not used and instead we use an incremental sequence.

and when calling `infer` no version should be specified by the user, internally it should point to `latest`.

With the exception of a rolling update during which `infer` can happen to return from different versions. Response metadata should indicate which one is being used. After the rolling update has finished we unload the previous version.

Do you have a specific usecase where the `version` in `model-settings.json` is used?

**Comment by agrski** [comment]
Hi @T1murKO,

Core v2 needs to adjust a few things from MLServer's view of the world, including the naming of model versions. 

You can specify which version of a model to use from a storage bucket by using **both** `storageUri` and `artifactVersion`.  This expects the normal directory structure used by MLServer to understand versions.  See [here](https://github.com/SeldonIO/seldon-core/blob/8ffd095da6f4907b17a76d58dc0529a4783c2f4d/operator/apis/mlops/v1alpha1/model_types.go#L100) and [here](https://github.com/SeldonIO/seldon-core/blob/8ffd095da6f4907b17a76d58dc0529a4783c2f4d/operator/apis/mlops/v1alpha1/model_types.go#L104) for reference.

When you create a `Model` in Core v2, it will have an internal version number assigned to it, which overrides the version specified in `model-settings.json`.  Different versions of a model that need to run concurrently should be treated as different models in Core v2.

Does that clarify things?

**Comment by cliveseldon** [comment]
Closing - please reopen if needed.
