### ISSUE TITLE
Seldon Manager reconciliation logs are not controlled via MANAGER_LOG_LEVEL

### ISSUE THREAD

**Issue by KashyapAdarsh** [SeldonIO/seldon-core#4917]
## Describe the bug

We are using Seldon v1 **version 1.16.0**. In our Azure managed Kubernetes test environment I have been seeing a lot of reconciliation logs. I understand that these logs are emitted whenever their are differences detected that need to be reconciled. We have set our MANAGER_LOG_LEVEL to ERROR and we still see them, but we don't see any other error logs saying reconcile failed or issues with reconcile.

![Screenshot 2023-06-14 at 10 04 27 AM](https://github.com/SeldonIO/seldon-core/assets/25337979/190f1cf5-d6b2-4979-baa9-7af3c9db36b0)

![Screenshot 2023-06-14 at 10 02 05 AM](https://github.com/SeldonIO/seldon-core/assets/25337979/4d6bb8a2-6ded-4fd8-b58e-c625a568ebd6)

I think these logs are not logged via logger. Please take a look at how we can control these logs. 

## To reproduce

- Bring up seldon manager and resources managed by the manager.
- Whenever there is some reconcile request, you should see these logs.

## Expected behaviour

MANAGER_LOG_LEVEL should also control these logs and these logs should be DEBUG logs.

## Environment
 K8s: v1.26.3

**Comment by agrski** [comment]
Hi @KashyapAdarsh,

From a quick look at the code, I can see that although the Helm charts use `MANAGER_LOG_LEVEL`, the operator's `main.go` uses `SELDON_LOG_LEVEL`.  See [here](https://github.com/SeldonIO/seldon-core/blob/f9d39508c1957c7aacd09b0a46e73e7171dcbee4/operator/main.go#L149) and [here](https://github.com/SeldonIO/seldon-core/blob/f9d39508c1957c7aacd09b0a46e73e7171dcbee4/operator/main.go#L54).

Could you try setting `SELDON_LOG_LEVEL` and confirm it that behaves the way you'd expect?  If so, we can look at updating the Helm chart.

**Comment by adarshkp23** [comment]
@agrski I don't think that helps. I tried setting that env variable for `seldon-controller-manager` deployment and I still see those logs.
![Screenshot 2023-06-15 at 11 22 35 AM](https://github.com/SeldonIO/seldon-core/assets/132311616/87a02967-a2a3-409e-a8b0-974eaf69e094)

These logs do not have any log level as well. Its like print statements that are sent to STDOUT.

![Screenshot 2023-06-15 at 11 24 22 AM](https://github.com/SeldonIO/seldon-core/assets/132311616/b759799c-e4f8-4c32-b00e-7700227283ad)
