### ISSUE TITLE
Scheduler fails to read TracingConfig.Ratio on startup

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#4932]
## Describe the bug

When running `make deploy-local` the scheduler fails to start with this error:

```
time="2023-06-21T10:21:18Z" level=fatal msg="Failed to configure otel tracer" error="json: cannot unmarshal number into Go struct field TracingConfig.Ratio of type string"
```

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

**Comment by cliveseldon** [comment]
Fixed
