### ISSUE TITLE
Model gateway tls ca.crt load failure for mTLS kafka connection

### ISSUE THREAD

**Issue by ukclivecox** [SeldonIO/seldon-core#4936]
```
time="2023-06-22T14:24:02Z" level=error msg="Failed to add model tfsimple1" error="ssl.certificate.location failed: error:140DC009:SSL routines:use_certificate_chain_file:PEM lib" source=KafkaSchedulerClient
```

Could be a local filesystem artifact as file does exist. One solution is to use latest librdkafka which has fixed https://github.com/confluentinc/confluent-kafka-go/issues/827

**Comment by Rajakavitha1** [comment]
closing this  issue because it is fixed in #4940
