### ISSUE TITLE
The way Seldon Core uses the python wrapper cannot move data to the GPU

### ISSUE THREAD

**Issue by ming-shy** [SeldonIO/seldon-core#4948]
How can I solve this problem
The following error will be reported:
{
    "status": {
        "code": -1,
        "info": "Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method",
        "reason": "MICROSERVICE_INTERNAL_ERROR",
        "status": 1
    }
}

The model definition file is as follows：

class ChatGLM:

    def __init__(self):
        model_path = '/root/Models/chatglm_6b_int4'
        self.tokenizer = aT.from_pretrained(model_path, trust_remote_code=True, revision="001")
        self.model = aM.from_pretrained(model_path, trust_remote_code=True, revision='001').half().cuda()

    def predict(self, x, features_names=None):
        ipt_ids = self.tokenizer(x[0], return_tensors='pt')
        for k, v in ipt_ids.items():
            print(v)
            ipt_ids[k] = v.cuda()   # **ERROR**
        print(ipt_ids)
        out = self.model(**ipt_ids)
        print(out)
        return x

The interesting thing is that the model can be moved to the GPU normally, but the data cannot be moved to the GPU.

**Comment by cliveseldon** [comment]
This issue and solutions (move to MLServer) are discussed in this issue: https://github.com/SeldonIO/seldon-core/issues/4429
I will close this as I think the connected issue has all the required solutions.
