### ISSUE TITLE
How to create Seldon External Prediction API which support binary request data

### ISSUE THREAD

**Issue by JibinNajeeb** [SeldonIO/seldon-core#4964]
As per the documentation mentioned here
https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/external-prediction.html

It explains Seldon supports custom string or binary as request data. But I could not find an example or proper documentation on how to do this. All examples available point to either ndarray or tensor.

I am trying to post CSV file to seldon rest api like shown below
`curl -X POST -F data_file=@data.csv 'http://localhost:5000/seldon/seldon/echo/api/v1.0/predictions '`

Is this even possible? if so kindly please support us with some examples

Thanks

**Comment by cliveseldon** [comment]
Not sure we have a direct example but you can find issues discussing this, e.g.: https://github.com/SeldonIO/seldon-core/issues/3862

You should also consider using [MLServer](https://github.com/SeldonIO/MLServer) as that is the preferred means of creating custom models with support for the Open Inference Protocol.
