### ISSUE TITLE
Seldon v2: Helm chart missing variables and a protocol: TCP

### ISSUE THREAD

**Issue by FredericJames** [SeldonIO/seldon-core#4976]
## Describe the bug

In the Helm chart, I have no possibility to add my labels/annotations/nodeSelector/tolerations/affinity/anti-affinity ...

Furthermore, there's protocol: TCP missing line 1661 in file seldon-v2-components.yaml
Argocd is raising an error, preventing a good sync of the apps
![image](https://github.com/SeldonIO/seldon-core/assets/6051126/69afb73f-5db8-4a67-a6cd-6fd8065c915d)

## To reproduce

Deploy seldon v2 setup with argocd.
try to add labels/annotations ... in the value file

## Expected behaviour
Be able to add my own labels/annotations/... to any seldon resources
Seldon helm chart running with argocd without issues

## Environment

* Cloud Provider: AWS EKS
* Kubernetes Cluster Version: 1.24
* Deployed Seldon System Images: 2.5.0

**Comment by RafalSkolasinski** [comment]
@FredericJames could you provide example of how you see extending the Helm charts without ArgoCD in the picture?

**Comment by FredericJames** [comment]
We're using argocd and won't be able to do otherwise.
Right now, the missing field protocol is preventing me to use argocd properly.
So I have to fork this helm chart to fix the bug

**Comment by cliveseldon** [comment]
This seems strange as [TCP](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#containerport-v1-core) is the default

**Comment by cliveseldon** [comment]
Maybe related to [this](https://github.com/argoproj/argo-cd/issues/6939#issuecomment-910917402)?

**Comment by peterezetta** [comment]
+1 for tolerations, nodeSelectors, et al. in the Helm chart. We're using Seldon Core V2, and would like to be able to deploy everything to its own node pool without the need for patching the yaml after the Helm deploy.

**Comment by Rajakavitha1** [comment]
closing this issue because the fix is in #5771
