### ISSUE TITLE
Core v2: seldon-v2-components.yaml:563: unclosed action

### ISSUE THREAD

**Issue by JSilent** [SeldonIO/seldon-core#4977]
## Describe the bug

When install core v2 with helm, an error pops up:
$ helm install seldon-core-v2  seldon-charts/seldon-core-v2-setup --namespace seldon-mesh
Error: parse error at (seldon-core-v2-setup/templates/seldon-v2-components.yaml:563): unclosed action

## To reproduce

1. helm repo update seldon-charts
2. helm install seldon-core-v2  seldon-charts/seldon-core-v2-setup --namespace seldon-mesh

## Expected behaviour

Helm install successfully.

## Environment

Kubernetes Cluster Version: v1.23.17
Chart version: 2.5.0
Helm version: v3.5.2

**Comment by cliveseldon** [comment]
@JSilent which version of Helm are you using? We support v3+.

**Comment by JSilent** [comment]
> @JSilent which version of Helm are you using? We support v3+.

v3.5.2

**Comment by cliveseldon** [comment]
Could this be related to [this](https://github.com/helm/helm/issues/7704) issue? Can you try upgrading Helm and trying again?

**Comment by JSilent** [comment]
After upgrading to helm v3.12.1 is completed, the issue has gone. Thank you for the tips!
