### ISSUE TITLE
Enable MLServer OTel tracing for docker and ansible installations

### ISSUE THREAD

**Issue by vtaskow** [SeldonIO/seldon-core#4988]
When tracing is enabled for core v2, we are able to use Jaeger UI and observe traces. However, MLServer as of this moment does not support any kind of tracing. In the incoming versions of MLServer(as of 1.4.0.dev3), it will be supporting this feature as well, allowing us to have an improved view of a trace's journey. 
MLServer tracing will be available as a setting for [Docker](https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/docker-installation/index.html) and [Ansible](https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/kubernetes-installation/ansible.html) installations of Seldon.
It relates to this issue in MLServer: https://github.com/SeldonIO/MLServer/issues/39

This is an example of how it will look like once this issue is closed.
![image](https://github.com/SeldonIO/seldon-core/assets/13816060/d6bf8dba-2741-4c51-87c1-6ed2b415a8c2)

**Comment by adriangonz** [comment]
Fixed by #4989
