### ISSUE TITLE
Support Kafka auth with SASL OAUTHBEARER mechanism and OIDC method

### ISSUE THREAD

**Issue by pthalasta** [SeldonIO/seldon-core#4992]
Seldon core v2 currently does not support SASL with OAUTHBEARER mechanism of authentication. However, it does offer other methods of SASL_SSL protocol. As seldon source code uses confluent-kafka-go libraries internally, there should be an option to add the support for OAUTH authentication with automatic refresh of token as well. 

Sample code from confluent-kafka-go/v2 examples: https://github.com/confluentinc/confluent-kafka-go/blob/v2.1.1/examples/oauthbearer_oidc_example/oauthbearer_oidc_example.go

This requires passing of the following basic configurations:
```
		"sasl.mechanism":                      "OAUTHBEARER",
		"sasl.oauthbearer.method":             "OIDC",
		"sasl.oauthbearer.client.id":          "<oauthbearer_client_id>",
		"sasl.oauthbearer.client.secret":      "<oauthbearer_client_secret>",
		"sasl.oauthbearer.token.endpoint.url": "<token_endpoint_url>",
		"sasl.oauthbearer.scope":              "<scope>",

```
Current version of confluent-kafka-go in seldon source code is `1.9.1`. As OIDC tokens are short lived we'll have to handle token refresh if we want to stick with v1 of confluent-kafka-go. As per the details, v2 of confluent-kafka-go, should be able to handle automatic token refresh as per details in https://docs.confluent.io/cloud/current/access-management/authenticate/oauth/configure-clients-oauth.html#client-login-callback-handler-top-level-configuration-options and https://cwiki.apache.org/confluence/display/KAFKA/KIP-368%3A+Allow+SASL+Connections+to+Periodically+Re-Authenticate

**Comment by RafalSkolasinski** [comment]
Implemented as part of 2.7.0. See https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/kubernetes-installation/security/confluent-oauth.html
