### ISSUE TITLE
hodometer needs to be enabled for seldonConfig to be deployed inside helm chart

### ISSUE THREAD

**Issue by SDJustus** [SeldonIO/seldon-core#5021]
Is there a reason, why hodometer needs to be enabled inside the setup helm chart for the default SeldonConfig to be deployed?
Also, inside the setup helm chart, there is hodometer.enable and in the runtime helmchart, there is hodometer.disable. I think it would be nice to have either enabled or disabled everywhere.

**Comment by cliveseldon** [comment]
This is a typo in the docs [here](https://docs.seldon.io/projects/seldon-core/en/v2/contents/metrics/usage.html).
We will update the docs as now its only on the runtime that you need to disable components if you wish.

**Comment by cliveseldon** [comment]
Fixed
