### ISSUE TITLE
GRPC Tritonclient not working with Release 2.6.0

### ISSUE THREAD

**Issue by SDJustus** [SeldonIO/seldon-core#5024]
## Describe the bug
After upgrading from seldon-core v2 Release 2.4.0 to 2.6.0 the grpc tritonclient for python is not longer working and raises the following Excpetion: `tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] stream terminated by RST_STREAM with error code: INTERNAL_ERROR`

The grpc call doesn't reach my deployed triton server, but it shows in the envoy accesslog and looks like this:
`[2023-07-13T12:39:34.707Z] "POST /inference.GRPCInferenceService/ModelInfer HTTP/2" 200 - 731078 0 3 3 "-" "grpc-python/1.56.0 grpc-c/33.0.0 (linux; chttp2)" "-" "seldon-mesh:80" "10.0.5.60:9501"`

the agent inside the triton server is logging:

```
time="2023-07-13T13:34:34Z" level=debug msg="Extracted model name seldon-internal-model:mymodel_1 seldon-model:mymodel" Source=GRPCProxy                                                                         
time="2023-07-13T13:34:34Z" level=debug msg="Ensure that model mymodel_1 is loaded in memory" Source=StateManager                                                                                                
time="2023-07-13T13:34:34Z" level=debug msg="Model exists in cache mymodel_1" Source=StateManager                                                                                                                                               │
time="2023-07-13T13:34:34Z" level=debug msg="Request ids from incoming meta []" Source=GRPCProxy 
```

Other seldon components doesn't log any error (at least not on the default log level).

A full redeployment of seldon-core didn't help.

Methods like curl, tritonclient.http, seldon cli (grpc) still work.

## To reproduce

I don't think the model is of any interest, since the other methods are working, so here is a minimal failing tritonclient.grpc example:
```
import numpy as np
import tritonclient.grpc as grpcclient
model_name = "test_model"
headers = {"seldon-model": model_name}
grpc_triton_client = grpcclient.InferenceServerClient( url="localhost:8080",  verbose=False)
inputs = [ grpcclient.InferInput("input", [1,4], "UINT8")]
inputs[0].set_data_from_numpy(np.array([[1,2,3,4]], dtype=np.uint8))
result = grpc_triton_client.infer(
        model_name,
        inputs,
        headers=headers,
    )
```

seldon-mesh:80 is port-forwarded via `kubectl port-forward svc/seldon-mesh 8080:80`

## Expected behaviour
I'd expect the tritonclient (grpc) to work for seldon-core v2 as it was in 2.4.0

## Environment

* Cloud Provider: AWS EKS
* Kubernetes Cluster Version 1.24
* Deployed Seldon System Images: Helm Charts for Release 2.6.0 with disabled opentelemetry and one-sided TLS Kafka Connection
* Triton Version: 21.08 (deployed via seldon-core-v2)
* tritonclient.grpc == 2.35.0

**Comment by cliveseldon** [comment]
Could this be a timeout issue. The envoy logs show success at that point and the agent logs look like the call is arriving.

Can you try the [tritonclient notebook](https://docs.seldon.io/projects/seldon-core/en/v2/contents/examples/tritonclient-examples.html) we have as this seems to work fine with 2.6.0

**Comment by SDJustus** [comment]
Ok, so unfortunatly, I am not able to run the tritonclient notebook because i don't have access to gcs for various reasons.
However, I was able to find out, that if I deploy exactly the same (i.e. ONNX-)Model on a Triton with version 23.01 (instead of 21.08 as I was using before), the error seems to not occur.. So maybe somehow the triton Version 21.08 (and below I guess) are not longer supported... I'll check deeper on that, so that I can verify a complete running example on Version 23.01

**Comment by SDJustus** [comment]
works with a newer triton version.

**Comment by cliveseldon** [comment]
@SDJustus  great!
