### ISSUE TITLE
Start triton server via bash -c tritonserver instead of just tritonserver

### ISSUE THREAD

**Issue by SDJustus** [SeldonIO/seldon-core#5029]
## Describe the bug
At the moment, Triton seems to have a sort of [bug](https://github.com/triton-inference-server/server/issues/3877), where it has to be started using `bash -c tritonserver` rather calling the binary directly (as it is done in the default ServerConfig, provided by the Helm Charts). This only occurs when using triton with CUDA and using i.e. Version 22.12. This is not really a seldon-core bug but it would be nice to have this different call in the default ServerConfig to not have to write an own one.
Sorry to open the bug here, since this isn't really seldon core related, but the triton dev team seems to see the start with `bash -c tritonserver` as a fix, as the last comment on the [issue](https://github.com/triton-inference-server/server/issues/3877) states.

## To reproduce
1. Deploy a Triton Server using GPU
2. Deploy a Model (i.e. torchscript or onnx model, dali works) 
3. get the error message from triton: `UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain`

## Expected behaviour
Models to be deployable on GPU

## Environment

* Cloud Provider: AWS EKS
* Kubernetes Cluster Version 1.24
* Deployed Seldon System Images: Helm Charts of Release 2.6.0

## Model Details 
i.e. scripted pytorch model traced within the nvcr.io/nvidia/pytorch:22.12-py3 container from NGC

**Comment by WaterKnight1998** [comment]
I found the same issue, it would be helpfull that they integrate this fix...

**Comment by SDJustus** [comment]
Thanks for merging.
Closing this issue.
