### ISSUE TITLE
Install blocked by PyYaml dependency broken with new Cython 3

### ISSUE THREAD

**Issue by lpfann** [SeldonIO/seldon-core#5033]
There was a new release of Cython v3 yesterday, which breaks all versions of PyYaml<6.0.1.
This makes it impossible to install seldon-core currently.
More information here: https://github.com/yaml/pyyaml/issues/724
https://github.com/SeldonIO/seldon-core/blob/ac914f3c2b2848f32241927a6faea2bdc3c0dbd2/python/setup.py#L43

Is it possible to relax the dependency range to this?
```
 "PyYAML >= 5.4, <= 6.0.1", 
```

**Comment by dictcp** [comment]
upstream refuse to release fix for pyyaml v5.4 (see https://github.com/yaml/pyyaml/pull/726#issuecomment-1640397938)
so a pyyaml version pump in seldon is needed as proper fix.

and it would be great if it can be backport to seldon-core v1.x as well

**Comment by kylebluenote** [comment]
> > and it would be great if the fix (if any) can be backport to seldon-core v1.x as well.
> 
> ➕ there are innocent models dying out here, we're pretty heavily blocked until this is resolved
> 
> > and as workaround, per [yaml/pyyaml#724 (comment)](https://github.com/yaml/pyyaml/issues/724#issuecomment-1641571578) you consider to install pyyaml via `pip install "cython<3.0.0" wheel && pip install pyyaml==5.4.1 --no-build-isolation`, before installing your other dependencies
> 
> In case you have other dependencies getting in the way, it seems the reverse also works. I'm able to install pyyaml==6.0.1 and `pip install --no-build-isolation seldon-core==1.15.0`

Jumping in on this train here, we're blocked on this as well and upgrading doesn't look like it's going to fix things for us
