### ISSUE TITLE
How to wrap models using tool chains other than s2i?

### ISSUE THREAD

**Issue by jlewi** [SeldonIO/seldon-core#507]
A question I (and others seem to have) is how to build seldon model servers using toolchains other than s2i e.g.

* kaniko
* Fairing's append build
* Google Cloud Builder (#123)

Looking at the [docs](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_wrapping.html) if you aren't familiar with s2i its not clear what is actually happening.

However as far as I can tell wrapping your model boils down to the following for Python

* Create a Docker image using whatever tool chain you prefer
* Include seldon-core package
  * possibly by using seldon-core as a base image
* Start seldon by running seldon-core-microservice
  
  ```
  seldon-core-microservice
    - LabelPrediction
    - REST
    - --service-type=MODEL
    - --persistence=0
  ```
Is that accurate? 

/cc @cliveseldon

**Comment by cliveseldon** [comment]
Yes that is correct. 

 We want to show clear docs for using other methods such as Kaniko, Fairing etc so would be great to get priorities so we can work on this for next release in collaboration with Kubeflow.

**Comment by rajivml** [comment]
Can we have an example where Kaniko is being used to package a model as a flask service using s2i may be by taking github-issue-summarisation or some other simple model as an example

**Comment by cliveseldon** [comment]
We could refer to https://github.com/kubeflow/pipelines/blob/master/samples/contrib/seldon/mnist_tf.py#L62 or https://github.com/kubeflow/example-seldon/blob/95e386b344e17158455353ed61135230b5fa8838/workflows/training-r-mnist-workflow.yaml#L58
