### ISSUE TITLE
where is io.seldon.protos.DeploymentProtos package located?

### ISSUE THREAD

**Issue by TaylorHere** [SeldonIO/seldon-core#508]
as titled.

**Comment by cliveseldon** [comment]
You can find the protos at https://github.com/SeldonIO/seldon-core/tree/master/proto

**Comment by cliveseldon** [comment]
You can also find the OpenAPI versions of these at:https://github.com/SeldonIO/seldon-core/tree/master/openapi

**Comment by TaylorHere** [comment]
thx for your comment, that is helpful.
