### ISSUE TITLE
Seldon deleting custom labels in deployment

### ISSUE THREAD

**Issue by aishwaryagirish** [SeldonIO/seldon-core#5083]
## Describe the bug
We are using seldon to deploy machine learning models. we have a gatekeeper running which injecting some custom labels. But seldon is trying to delete the labels in the deployment. 

## Error
We are receiving this error-
![image](https://github.com/SeldonIO/seldon-core/assets/22720356/1b266e15-e599-4850-b941-76506cbd7547)

## Expected behaviour
We would not want seldon to delete them 

## Environment
Azure kubernetes

<!-- You Can fill it manually or paste the output of the command below:

* Cloud Provider: Azure

**Comment by cliveseldon** [comment]
Which version of Seldon does this apply to. In general you will need to add the labels to the custom resource so they can be assigned to dependent resources by the operator.
