### ISSUE TITLE
Will Seldon Core V1 be deprecated by Seldon Core V2?

### ISSUE THREAD

**Issue by spicoflorin** [SeldonIO/seldon-core#5118]
Hello!

 I've read the announcement of releasing the Seldon Core V2: https://www.seldon.io/news/seldon-core-v2-the-next-generation-open-data-centric-mlops

In this context, I have the following questions:
1. Do you have any plan to deprecate the Seldon Core V1?
2. Both of the version will work in parallel and will receives updates?
3. Do you have a roadmap on how to support the Seldon Core V1?
4. If I start fresh or Seldon, what do you recommend Seldon Core V1 or Seldon Core V2?

I look forward for your answers.

Best regards,
  Florin

**Comment by agrski** [comment]
Hi @spicoflorin,

To answer a couple of your questions:
2. Both Core v1 and Core v2 work in parallel and can be installed in the same cluster.  They use different resource definitions and resource names, so do not conflict.  It is already the case that both receive updates and new releases.  For example, 1.17.1 was released two weeks ago and there is 2.7.1-rc1 from a week ago, as seen [here](https://github.com/SeldonIO/seldon-core/releases).
4. For anyone starting fresh, the recommendation is to use Core v2.  This has a number of improvements over Core v1, such as smaller, domain-specific resources such as `Models` and `Pipelines`, multi-model serving, being service mesh-agnostic, and being based around an asynchronous data-flow paradigm.  The benefits and differences are discussed in more depth [here](https://docs.seldon.io/projects/seldon-core/en/v2/contents/about/index.html).

**Comment by spicoflorin** [comment]
Hell, @agrski!
Thank you for your answers. 
From them I can understood that the current plan is to:
- maintain/develop both of the  versions
- no deprecation of Seldon Core V1  so we can safely use it
- for new projects, Seldon V2 is recommended version for the mentioned improvements and features.

I hope that I got the it clear.
Regards,
 Florin
-

**Comment by agrski** [comment]
Hi Flori,

Glad I could provide some clarity!

It is likely that at some point, Seldon Core v1 will be deprecated.  For the time being, it's fine to continue using it and it will continue to be maintained, but Core v2 is the focus for development efforts as it does have a number of benefits over Core v1.

As for any timelines and roadmap for exactly when and what the deprecation of Core v1 will look like, that has yet to be announced.
