### ISSUE TITLE
Document about microservice's input data

### ISSUE THREAD

**Issue by MarvinMiao** [SeldonIO/seldon-core#512]
Is there any document about the format of input data for microservice, in detail? I have to check the source code to see how it works...expect for more elaborative documents.

**Comment by cliveseldon** [comment]
You can look at docs on 
  * [External API](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/external-prediction.html)
  * [Internal API](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/internal-api.html)

The [proto buffer defintions](https://github.com/SeldonIO/seldon-core/blob/master/proto/prediction.proto)  are the core source of truth

There are also [OpenAPI specs](https://github.com/SeldonIO/seldon-core/tree/master/openapi)

**Comment by MarvinMiao** [comment]
> You can look at docs on
> 
> * [External API](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/external-prediction.html)
> * [Internal API](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/internal-api.html)
> 
> The [proto buffer defintions](https://github.com/SeldonIO/seldon-core/blob/master/proto/prediction.proto) are the core source of truth
> 
> There are also [OpenAPI specs](https://github.com/SeldonIO/seldon-core/tree/master/openapi)

Ok, thanks
