### ISSUE TITLE
(helm-charts): replica count for seldon controller manager configurable via helm chart

### ISSUE THREAD

**Issue by SDJustus** [SeldonIO/seldon-core#5149]
Hello folks,

since the documentation indicates, that the v2 seldon controller manager can be scaled, would it make sense for you to make the replica count for the controller configurable via the helm charts?

**Comment by paulb-seldon** [comment]
This this should now be available here: https://github.com/SeldonIO/helm-charts/blob/master/helm-charts/seldon-core-v2-runtime/values.yaml
