### ISSUE TITLE
(envoy): Envoy startup probe is not set

### ISSUE THREAD

**Issue by SDJustus** [SeldonIO/seldon-core#5157]
## Describe the bug
I have deployed seldon core v2 Release 2.6.0 and have scaled the model-gateway, pipeline-gateway, envoy and dataflow pods to 2 via the SeldonRuntime. All of these pods do have a Pod Disruption Budget of minAvailible: 1 as well, which should not matter here. When I restart an Envoy Pod, I get an GRPC Exception (StatusCode.UNAVAILABLE).

I think this is due to the health endpoints of the envoy pod, which return ready/live despite the envoy pod being not ready. The traffic the newly created pod then receives, results in the failure.

The envoy is ready after the followling log line is printed:
`[info][config] [source/extensions/listener_managers/listener_manager/listener_manager_impl.cc:858] all dependencies initialized. starting workers`

## To reproduce

Scale up the envoy pod to >1 and restart one while doing consistent requests against seldon-mesh
## Expected behaviour

readiness and liveness probes to be configured.

## Environment

* Cloud Provider: AWS
* Kubernetes Cluster Version: 1.25
* Deployed Seldon System Images: 2.6.0
## Model Details 
not relevant

**Comment by SDJustus** [comment]
For Envoy, this would be via the ready endpoint of the envoy admin (IP:9003/ready) which returns PRE_INITIALIZING if it is not ready yet and LIVE if it is ready.

**Comment by SDJustus** [comment]
adding the following to the envoy deployment works:
``` yaml
startupProbe:
  failureThreshold: 30
  httpGet:
    path: /ready
    port: envoy-admin
    scheme: HTTP
  periodSeconds: 1
```

Can you point me to the correct position to insert this, so I can create a PR?
(Don't know if it is `scheduler\k8s\envoy\envoy.yaml` or `operator\config\seldonconfigs\default.yaml`)

**Comment by agrski** [comment]
Hi @SDJustus,

Thanks for identifying this and looking into it.  I'm just checking the right place to update for you.

**Comment by agrski** [comment]
Hi again, I think the best place would be `operator/config/seldonconfigs/default.yaml`.  In the equivalent ServerConfigs in a sibling directory there are lifecycle probes defined, so this would be in keeping with that.

Should any templating be needed, e.g. for the start-up duration, that should go in a patch file under `k8s/kustomize/...`.

You'll also need to run the generation scripts to propagate these changes into the Helm chart, etc.  If you could thereafter please confirm this works without issue in a deployment, that'd be grand!  I don't foresee this causing issues with the operator reconciliation logic, but best to check and be sure.

Thanks again for investigating and offering to put in a fix!

**Comment by SDJustus** [comment]
Ok. I'll create the PR tomorrow. I think it would make sense to put in a readiness probe as well, point to the same endpoint. Does this make sense for you as well?

**Comment by SDJustus** [comment]
@agrski I added the PR, which defines a readiness probe. After I looked into the kubernetes docs I saw, that the startup probe is primarily used for slow starting pods. Since the envoy isn't one of them, a readiness probe fits more imo. Let me know, if this is fine for you.

**Comment by agrski** [comment]
Hello, just using a readiness probe seems fine to me - as you say, one wouldn't expect Envoy to have a long start-up period.

I'll take a look at that PR now!

**Comment by agrski** [comment]
That's been merged in now!  Thanks again for the contribution @SDJustus.

One thing to note is that you made changes directly on your `v2` branch, so just be aware that may not exactly track `seldonio/v2` given the merged commit has a slightly different name.
