### ISSUE TITLE
otel-collector-1 container not starting: error decoding 'exporters': unknown type: "jaeger" for id: "jaeger"

### ISSUE THREAD

**Issue by avolts** [SeldonIO/seldon-core#5189]
## Describe the bug
After following the installation guide for Docker Compose for SeldenCoreV2, the otel-collector-1 container cannot start due to the following error:
error decoding 'exporters': unknown type: "jaeger" for id: "jaeger" (valid values: [opensearch prometheus awsxray azuredataexplorer azuremonitor carbon cassandra mezmo sentry file honeycombmarker opencensus sumologic sapm skywalking alertmanager alibabacloud_logservice awscloudwatchlogs dataset googlecloud pulsar datadog f5cloud loadbalancing logicmonitor logzio logging clickhouse loki debug otlp awsemf coralogix instana tencentcloud_logservice dynatrace elasticsearch googlecloudpubsub prometheusremotewrite signalfx otlphttp awskinesis awss3 googlemanagedprometheus influxdb kafka splunk_hec syslog zipkin])

## To reproduce
1. Follow the installation instructions for Docker Compose [https://docs.seldon.io/projects/seldon-core/en/v2/contents/getting-started/docker-installation/index.html](url) and set CUSTOM_IMAGE_TAG=2.6.0
2. Check running containers in Docker Desktop
3.  See that otel-collector-1 cannot start 

## Expected behaviour
I expect that the otel-collector-1 container is starting without issues after local deployment.
Replacing jaeger with otlp at the marked places in the otel-collector-config.yaml solves the issue.
"jaeger" is no longer in the exporters values.
![image](https://github.com/SeldonIO/seldon-core/assets/22810956/329a1a41-1141-413a-90e3-0e6dd1ff1c99)

## Environment

- SeldonCoreV2 Installation on WSL Ubuntu-22.04
- Docker Desktop v4.24.2
- Windows Windows 10 Enterprise, 22H2

**Comment by sakoush** [comment]
A potential fix is described [here](https://github.com/SeldonIO/seldon-core/pull/5170)

a workaround for now is to use an older version of otel/jeager via setting `JAEGER_IMG=jaegertracing/all-in-one:1.49`

**Comment by lc525** [comment]
This is believed to be fixed via #5291
