### ISSUE TITLE
status code in response missing. Seldon v 0.2.3

### ISSUE THREAD

**Issue by klalit** [SeldonIO/seldon-core#519]
In the response below cannot see the status code

curl -X POST -H 'Content-Type: application/json' -d '{"meta":{"puid":"test" }, "data": {"names": ["input_filepath"],"ndarray": ["s3://test.txt"]}}' http://mydomain.com/seldon/test/api/v0.1/predictions

{
  "meta": {
    "puid": "test",
    "tags": {
    },
    "routing": {
    }
  },
  "data": {
    "names": ["t:0", "t:1"],
    "ndarray": []
  }

**Comment by cliveseldon** [comment]
The HTTP status code is not provide in the meta data itself. You can view it in curl with `curl -v`
