### ISSUE TITLE
put crd and controller into single helm chart

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#522]
We could have a single chart for the CRD and controller and have a crd.create option for the user to decide whether to install the CRD. This is what is done in:

https://github.com/helm/charts/blob/c7edb3f3012c4db73624583dafe6963aec3055e0/stable/sealed-secrets/values.yaml#L24

and

https://github.com/helm/charts/blob/7d0450231c4fe88483d5cb15b760a5886f3c1903/stable/prometheus-operator/values.yaml#L448

**Comment by cliveseldon** [comment]
That's the plan for the controller rewrite in Golang. A single helm chart with both and then allow people to add ingress as needed : Ambassador, Seldon OAuth Gateway, Istio-Ingress.

**Comment by ryandawsonuk** [comment]
This will be closed out by https://github.com/SeldonIO/seldon-core/pull/559

**Comment by cliveseldon** [comment]
Fixed
