### ISSUE TITLE
make engine probes configurable

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#525]
Exposing env vars in the cluster manager and making available to the helm chart would do it.

Given that the engine is a sidecar, I personally would like to put its config directly in a configmap populated by the helm chart and have the cluster-manager read the configmap. [Like istio does](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml). Then we could expose its config more flexibly.

**Comment by cliveseldon** [comment]
Closing can reopen if we think engine probes need to be controllable.
