### ISSUE TITLE
Defining the model serving class with full name doesn't currently work

### ISSUE THREAD

**Issue by hmonteiro** [SeldonIO/seldon-core#533]
In line 194 of microservice.py you are trying to load a module from args.interface_name. The problems is that at this point, interface name is the full class name (e.g. package.module.Class) so import_lib.import module fails.

This line has to be changed from `interface_file = importlib.import_module(args.interface_name)` to `interface_file = importlib.import_module(parts[0])`

**Comment by hmonteiro** [comment]
By the way, I'm really happy with this change, since (after this bug is fixed) I can throw away my hack of setting up a dummy serving class that just forwards the requests to the proper one.

**Comment by cliveseldon** [comment]
Thanks. Any chance you can do a PR and check why these tests are not adequate:

https://github.com/SeldonIO/seldon-core/blob/250bf16c0fed89fb0d5cb7486138bb8e01984987/python/tests/test_microservice.py#L94-L109

**Comment by hmonteiro** [comment]
I'll try to have a look. If I find the unit test problem I'll do a PR

**Comment by hmonteiro** [comment]
Found the problem, you are still relaying on the fact that the filename is the same as the class name. In python the filename should be snake case while class names are camel case, so this won't usually be the case. I'll fix the unit test and the code and will provide a PR.

**Comment by cliveseldon** [comment]
Thanks. This is great.

**Comment by hmonteiro** [comment]
The fix is in the PR, let me know if there is anything else you need.

**Comment by cliveseldon** [comment]
Closed as merged.
