### ISSUE TITLE
Not able be build python3.6 base image. 

### ISSUE THREAD

**Issue by chennupushkar** [SeldonIO/seldon-core#542]
> cd seldon-core/wrappers/s2i/python
> make build_local PYTHON_VERSION=3.6

ERROR: jaeger-client 4.0.0 has requirement opentracing<3.0,>=2.1, but you'll have opentracing 1.3.0 which is incompatible.

**Comment by lengwei1977** [comment]
I have the same problem, just modify the seldon-core/python/setup.py   :
  'jaeger-client'  ==> 'jaeger-client==3.13.0'
then it works.

**Comment by cliveseldon** [comment]
This is fixed in master
