### ISSUE TITLE
Investigate Request Logging

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#545]
* Add to engine optional push of request/responses to external request logger
 * What would be best initial backends to support: InfluxDB, ElasticSearch?

**Comment by jklaise** [comment]
For data science usage we also need to think about breaking down batch requests into single instance logging.

**Comment by axsaucedo** [comment]
I guess we could close this @cliveseldon @jklaise ?

**Comment by cliveseldon** [comment]
Fixed.
