### ISSUE TITLE
requirements.txt for Python wrapped models should be a configurable name/path

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#548]
Currently the wrapper will only look for either `requirements.txt` or `setup.py` (https://github.com/SeldonIO/seldon-core/blob/18db0f373979ac2d660600ca4e35ff70aecdbb53/wrappers/s2i/python/s2i/bin/assemble#L53), it would be useful to provide an environment variable to enable wrapping multiple models with distinct requirements from the same directory.

**Comment by cliveseldon** [comment]
We plan to move to other forms of image creation.
