### ISSUE TITLE
Python client - SyntaxError

### ISSUE THREAD

**Issue by Sharathmk99** [SeldonIO/seldon-core#551]
Hi,

I'm using python3
`python3 --version`
Python 3.5.2

I installed seldon-core using 
`pip3 install seldon-core`

When i try using seldon-core-tester, i'm getting SyntaxError. Please find below complete error,
`Traceback (most recent call last):
  File "/home/seldon/.local/bin/seldon-core-tester", line 7, in <module>
    from seldon_core.microservice_tester import main
  File "/home/seldon/.local/lib/python3.5/site-packages/seldon_core/microservice_tester.py", line 60
    raise SeldonTesterException(f"Unknown dtype in reconciliate_cont_type {dtype}")
                                                                                 ^
SyntaxError: invalid syntax
seldon@mlseldon:~/seldon-test$ python3 /home/seldon/.local/lib/python3.5/site-packages/seldon_core/microservice_tester.py
  File "/home/seldon/.local/lib/python3.5/site-packages/seldon_core/microservice_tester.py", line 60
    raise SeldonTesterException(f"Unknown dtype in reconciliate_cont_type {dtype}")
                                                                                 ^
SyntaxError: invalid syntax
`

**Comment by jklaise** [comment]
What is the full command you're calling including all arguments? Also do you have the latest version of the pip package (0.2.7)?

**Comment by Sharathmk99** [comment]
I checked the version of pip its,
pip 19.1.1

**Comment by jklaise** [comment]
Sorry, I meant the `seldon_core` package from pip. Also it would be helpful to have the full command with arguments to see why it failed.

**Comment by Sharathmk99** [comment]
Yes its 0.2.7
seldon-core          0.2.7

**Comment by jklaise** [comment]
What is the full command you used?

**Comment by arun-muthy** [comment]
getting the same error here

**Comment by jklaise** [comment]
@arun-muthy @Sharathmk99 looks like you haven't set the `dtype` in the contract.json, it has to be one of `FLOAT` or `INT`, if you're trying to test string or binary data it won't work: https://github.com/SeldonIO/seldon-core/blob/c62dbfa5cee65ec99147f8074cd960ec3776a431/python/seldon_core/microservice_tester.py#L55-L60

**Comment by arun-muthy** [comment]
still no luck, i'm going through examples provided by seldon, here's the json: https://github.com/SeldonIO/seldon-core/blob/master/examples/models/sklearn_iris/contract.json

**Comment by raul1991** [comment]
Is it seldon_core or seldon-core to install it with pip because the latter gets a read time out error during the installation ?

**Comment by cliveseldon** [comment]
Is this still an issue @arun-muthy Please reopen if it is.
