### ISSUE TITLE
Support microservice testing via curl with JSON content-type

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#552]
Currently [this example](https://docs.seldon.io/projects/seldon-core/en/latest/workflow/api-testing.html#microservice-api-test-via-curl) requires to put the payload as part of the url being called. At least for Python wrappers we could extend these to accept a JSON content-type header.

**Comment by ryandawsonuk** [comment]
I think curl supports this with `-d`. I thought that we [did use this](https://github.com/SeldonIO/seldon-core/blob/e08e13556d0eb481a2db2531c66785dcd496845b/wrappers/s2i/R/s2i/bin/usage#L28) but [don't see it in the docs anywhere, just examples/code](https://github.com/SeldonIO/seldon-core/search?q=%22curl++-d%22&unscoped_q=%22curl++-d%22)

**Comment by jklaise** [comment]
Interesting, I do recall using those examples on Python microservices a few months ago, maybe it worked before the Python wrapper re-write @cliveseldon ?

**Comment by cliveseldon** [comment]
Fixed.
