### ISSUE TITLE
Clearer usage/defaults or warnings about GRPC components in the deployment graph

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#553]
Currently if a microservice is wrapped with a GRPC endpoint, this needs to be specified in the SeldonDeployment manifest explicitly, otherwise the deployment will succeed but be unable to pass messages through the graph which can cause confusion.

**Comment by cliveseldon** [comment]
Solved in executor.

**Comment by cliveseldon** [comment]
In latest have added an explicit protocol and transport filed (rest or grpc) so will be clearer in new executor
