### ISSUE TITLE
Provide a NULL/None type in the CRD

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#554]
In Python it is a valid convention to use `None` as a default value for a parameter, however for Python components if we want to document in the deployment manifest all parameters with a default value of `None`, currently we would have to pass is as a STRING parameter and do post-processing in the Python wrapper (e.g. explicitly checking if the STRING is "None" and if so setting the parameter to `None`), this would introduces another convention to document.

**Comment by jklaise** [comment]
Alternative solutions:
 * Make `value` field optional in the CRD (https://github.com/SeldonIO/seldon-core/blob/3d8b3791b343118953757a1e787e5919cc64e697/proto/seldon_deployment.proto#L141)
 * Make use of the json `null` value

**Comment by cliveseldon** [comment]
Given this seems to be more of a documenting process and I can't see a neat solution to fix this will close. Open if I am mistaken.
