### ISSUE TITLE
Docker image name and version messed up

### ISSUE THREAD

**Issue by sasvaritoni** [SeldonIO/seldon-core#562]
https://github.com/SeldonIO/seldon-core/blob/3d8b3791b343118953757a1e787e5919cc64e697/engine/src/main/java/io/seldon/engine/predictors/PredictiveUnitState.java#L90-L95

This will end up really ugly when the docker registry is running on a non-default port (this is often the case for private docker registries).

E.g.:  "hostname:5000/myimage:v0.0.1"

The split should in fact occur at the last ":", not the first one.

**Comment by cliveseldon** [comment]
Could you create a PR for this?

**Comment by sasvaritoni** [comment]
Added PR #576
