### ISSUE TITLE
node exporter port conflict

### ISSUE THREAD

**Issue by csabika7** [SeldonIO/seldon-core#563]
Helm chart for seldon-core-analytics includes installing a node-exporter daemonset. As it is directly uses the host network reserving the port 9100.
Deployment of this helm chart would then fail if node-exporeter have been deployed already for another application like **ranch**.

Do you know some way to still be able to install seldon-core-analytics which would use the already deployed node-exporter if it is already present?

**Comment by cliveseldon** [comment]
Would a fix me to make that port configurable in the Helm chart values?  Could you submit a PR?

**Comment by csabika7** [comment]
Can you even do that?
In the Dockerfile of the node-exporter the 9100 port is exposed.
In the helm chart the hostNetwork is set to true.

So the container will use the host network namespace so setting any other port in the chart will not have any effect right?

**Comment by gsunner** [comment]
merged changes in PR#617
