### ISSUE TITLE
Decouple tensorflow package from the base python seldon-core image.

### ISSUE THREAD

**Issue by chennupushkar** [SeldonIO/seldon-core#564]
Python Seldon-core base image comes with tensorflow package.
Decouple tensorflow package from the base python seldon-core image.

**Comment by cliveseldon** [comment]
I think you mean the seldon-core python module includes tensorflow. 
I could be a longer term aim to try to remove this dependency but we need it for:

 * gRPC handling of TensorProto payloads

**Comment by chennupushkar** [comment]
Thank you Clive. Yes i meant seldon-core python module. Let me edit the issue.

**Comment by cliveseldon** [comment]
The trouble is our payloads allow TensorProto whose serializaton/deserialization needs a method from Tensorflow python packagfe. Not sure we can easily change this as the Tensorflow package is a monolithic package unfortunately.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
It is possible to install seldon-core package without tensorflow now
