### ISSUE TITLE
HTTPS/HTTP switch for seldon client

### ISSUE THREAD

**Issue by mcminis1** [SeldonIO/seldon-core#572]
As a seldon user, i need to be able to configure the seldon client in python to use https instead of http when connecting over the internet so that the contents of the massages are secure while in flight.

**Comment by cliveseldon** [comment]
This is definitely something missing. You mentioned in slack you would be interested in providing a PR?

**Comment by cliveseldon** [comment]
An example where Ambassador does the https would be a great example once the code is done.

**Comment by cliveseldon** [comment]
@mcminis1 Any update on this?

**Comment by cliveseldon** [comment]
Fixed by latest code in master
