### ISSUE TITLE
kubeflow/example-seldon on local cluster

### ISSUE THREAD

**Issue by sasvaritoni** [SeldonIO/seldon-core#585]
Looking at kubeflow/example-seldon  readme, it states that GKE is required to run the example.

Is there anything specific to GKE in these examples which would prevent it from being run on a local K8s cluster with kubeflow?
Or are there maybe similar examples for end-to-end training flow with Seldon to be performed on a local cluster?

Thanks!

**Comment by cliveseldon** [comment]
It needs a ReadWriteMany (NFS) persistent volume. So in theory I think you could mount a local disk for minikube for example. Have not tried this but would be great to have a PR if possible. Can you open one on that repo? I will close this one.
