### ISSUE TITLE
Government use license?

### ISSUE THREAD

**Issue by csbrown** [SeldonIO/seldon-core#5895]
Hello.  What are the terms of use for government agencies (NASA, NIST, NOAA, USGS, etc)?  I only see non-profit and commercial entities referenced in the license.

**Comment by isobelshawseldon** [comment]
Hi Scott @csbrown 
I'm Isobel, the Community Account Manager at Seldon, here to help with Seldon Core licensing.
For government agencies, our licensing terms are the same as for commercial entities. This means that to use Seldon Core in production for versions released after January 22nd, 2024 (versions 1.18 and 2.7 onwards), you'll need a license subscription.
Our annual subscription for production use is a flat fee of USD $18,000. I'm happy to discuss this further and answer any questions you might have. Feel free to reach out to me directly at [isobel.shaw@seldon.io](mailto:isobel.shaw@seldon.io)
