### ISSUE TITLE
How to set allowPrivilegeEscalation: false for seldon-v2-runtime core components?

### ISSUE THREAD

**Issue by arodindev** [SeldonIO/seldon-core#5979]
The Deployments of the core components, created via

```bash
helm install seldon-v2-runtime seldon-charts/seldon-core-v2-runtime --namespace seldon-mesh --set pipelinegateway.disable=true --set dataflow.disable=true
```

are not able to create the Pods because our gatekeeper requires containers to have `allowPrivilegeEscalation: false`. Otherwise our ReplicaSets throw an error. For example:

```bash
Privilege escalation container is not allowed: hodometer
```

We can patch them manually to make it work but this does not seem like a good solution:

```bash
kubectl patch replicaset -n seldon-mesh hodometer-6b788cfccf -p='{
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "name": "hodometer",
            "securityContext": {
              "allowPrivilegeEscalation": false
            }
          }
        ]
      }
    }
  }
}'
```

We would like to set this via Helm - is it possible?

**Comment by sakoush** [comment]
@arodindev thanks for your comment.

This can be done already via helm by setting the `<component>.securityContext` for the different components of core 2. This has to be done for each component though, check [here](https://github.com/seldonio/seldon-core/blob/v2/k8s/helm-charts/seldon-core-v2-setup/values.yaml).
e.g. of allowPrivilegeEscalation and other security related settings:
```
serverConfig:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
```

This is set at the `seldon-core-v2-components` level.
