### ISSUE TITLE
OpenAPI spec for external and internal prediction APIs

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#6]
The APIs are presently described as gRPC/proto files.

Translating automatically to OpenAPI does not seem possible, see [issue on OpenAPI project](https://github.com/OAI/OpenAPI-Specification/issues/801)
There is an [OpenAPI to proto Converter project](https://github.com/NYTimes/openapi2proto) so one possibility is to see how close a created manual OpenAPI spec of the current gRPC spec when sent through this recreates the existing gRPC spec. If this was identical we could think of just keeping the OpenAPI spec and generating the proto file.

**Comment by elgalu** [comment]
Are you guys planning to be SwaggerAPI compliant?

**Comment by cliveseldon** [comment]
Yes, we definitely want to. The question is how to convert the gRPC proto buffer message definitions which are presently the source of truth.

**Comment by cliveseldon** [comment]
fixed by #271
