### ISSUE TITLE
tensorflow-gpu

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#602]
The seldon-core microservice library has tensorflow (cpu version) [as a dependency](https://github.com/SeldonIO/seldon-core/blob/master/python/setup.py#L22). This leads to either dependency issues if anyone wants to use tensorflow-gpu or being able to build and then getting a 'CPU supports instructions that this TensorFlow binary was not compiled to use' message. This has been[ encountered before](https://github.com/SeldonIO/seldon-core/issues/380) and came up again recently [on slack](https://seldondev.slack.com/archives/C8Y9A8G0Y/p1559139617052000?thread_ts=1559060738.035900&cid=C8Y9A8G0Y).

We should look at ways to make it easier to use tensorflow-gpu with seldon. Some ideas:

- Will it work to install seldon-core, uninstall tensorflow and then install tensorflow-gpu? Slack discussion currently suggests not but if we did get that working would it be adequate to document that?
- Could we just rely on the tensorflow protos (which is what we really need) without bringing in all of tensorflow?
- Could we use another [library to handle detection](https://pypi.org/project/tensorflow-auto-detect/)?
- Provide two versions of seldon-core?

**Comment by cliveseldon** [comment]
The seldon-core python libraries just need to convert a tensorProto to ndarray but so far not found a way to isolate that code easily and maintainably.

**Comment by cliveseldon** [comment]
Still hard to see any easy solution to this without creating separating out the tensorflow part.

**Comment by cliveseldon** [comment]
Fixed - you can specify tensorflow-gpu in python wrapper setup
