### ISSUE TITLE
volume mounting - update examples

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#604]
The java-base seldon operator (0.2.8 and below) requires volumes to be specified like:

```
							"volumes": [
								{
									"name": "persistent-storage",
									"volumeSource": {
										"persistentVolumeClaim": {
											"claimName": "modelpvc"
										}
									}
								}
							]
```
With the new go-based operator we need to remove the volumeSource level like:

```
							"volumes": [
								{
									"name": "persistent-storage",
									"persistentVolumeClaim": {
											"claimName": "modelpvc"
                                    }
								}
```

We need to update examples here and in kubeflow. (Encountered this when [running kf example](https://github.com/kubeflow/example-seldon/blob/647a00160f40635573476b14952709acbcaabffc/k8s_serving/serving_model.json#L42) with new operator.) We also need to update kubeflow's seldon operator version.

**Comment by ryandawsonuk** [comment]
It seems we are seeing this due to upgrading the k8s client library in the operator and the volumeSource form doesn't work with that anymore. I tried running:

```
{
	"apiVersion": "v1",
	"kind": "Pod",
	"metadata": {
		"name": "pvc-access-container"
	},
	"spec": {
		"containers": [
			{
				"name": "pvc-access-container",
				"image": "busybox",
				"command": [
					"/bin/sh",
					"-ec",
					"sleep 1000"
				],
				"volumeMounts": [
					{
						"name": "mypvc",
						"mountPath": "/mnt"
					}
				]
			}
		],
		"volumes": [
			{
				"name": "mypvc",
				"volumeSource": {
					"persistentVolumeClaim": {
						"claimName": "nfs-1"
					}
				}
			}
		]
	}
}
```
And got `error: error validating "pvcvolumesourcetester.json": error validating data: ValidationError(Pod.spec.volumes[0]): unknown field "volumeSource" in io.k8s.api.core.v1.Volume; if you choose to ignore these errors, turn validation off with --validate=false`. So the form that seldon has been using doesn't work even in ordinary pods in this k8s version (client 1.14, server v1.11.9-gke.8). It seems to make sense therefore that the new operator doesn't support the old volumeSource form.

**Comment by cliveseldon** [comment]
https://docs.seldon.io/projects/seldon-core/en/latest/examples/tmpl_model_tracing.html need changing
