### ISSUE TITLE
Update Python SeldonClient to handle JSON payloads

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#607]
As a result of #595 .

**Comment by cliveseldon** [comment]
Fixed in 0.3.0

**Comment by jklaise** [comment]
Reopening as this is still missing.

**Comment by axsaucedo** [comment]
This was now added on 0.3.1, @jklaise good to close?

**Comment by jklaise** [comment]
@axsaucedo if you say so, although I don't see the relevant PR in the changelog.

**Comment by axsaucedo** [comment]
@cliveseldon I caught up with @jklaise to understand better, and what he was referring to is actually the support for the `json_data=` in the seldon client - which is unfortunately not added yet (although it would be a small change)
