### ISSUE TITLE
Extend Python SeldonClient to communicate directly with the SVC endpoint for the engine

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/seldon-core#608]
This is required to communicate from within a Python model with another deployment in the cluster (e.g. for model explainers). Currently it can be done by setting `ambassador_endpoint` to the svc name and set `gateway_prefix` to "", but this should be an explicit option.

**Comment by cliveseldon** [comment]
Closing this as explainers are handled differently now, also Tempo is a possible solution for custom service orchestration
