### ISSUE TITLE
seldon-core-analytics grafana shows metrics of only of first canary model

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#618]
# seldon-core-analytics grafana shows metrics of first canary model

When following the canary deployment tutorial using the MNIST or any other example, the grafana dashboard is able to display metrics for the first seldondeployment, but when deploying a canary deployment, the containers of the canary are not present in the grafana dashboard.

**Comment by cliveseldon** [comment]
The example https://docs.seldon.io/projects/seldon-core/en/latest/examples/ambassador_canary.html seems to work
![canry](https://user-images.githubusercontent.com/10563075/60172323-57b0b380-9804-11e9-95cb-f5fe568b0701.png)

**Comment by axsaucedo** [comment]
Thank you for having a look @cliveseldon. The reason why this example in particular works is because the container names are different. If a pipeline is run with a different deployment name but the same container name, it wouldn't be picked up by grafana. A solution could be to also use the deployment name (and the namespace) as a prefix in the prometheus exporter.

**Comment by cliveseldon** [comment]
That sounds like a grafana dashboard issue?
