### ISSUE TITLE
 Tensorflow GPU Example

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#619]
Several community members and enterprise clients have requested examples using Seldon Core with GPU usecases. We should create an example that shows a step by step example building a tensorflow GPU model, and serving it with Seldon Core.

**Comment by axsauze** [comment]
Once this example is up and running we could try to use #602 if relevant.

**Comment by axsauze** [comment]
This will also address discussions like #590.

**Comment by cliveseldon** [comment]
Done
