### ISSUE TITLE
Changes required for Seldon Core Analytics Grafana to work behind proxy

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#622]
# Changes required for Seldon Core Analytics Grafana to work behind proxy

In order for the Grafana in Seldon Core analytics to work behind an ambassador proxy that has a prefix, such as `/grafana/`, the Grafana application requires an environment variable to know about it for it to work (i..e  load all frontend assets correctly, etc).

This would require changes in the seldon core analytics helm chart to allow for a prefix to be passed as a parameter. More specifically this would be an environment variable in the deployment specification as follows:

```
          - name: GF_SERVER_ROOT_URL
            value: "%(protocol)s://%(domain)s/grafana/"
```

Then the service would just have to have the ambassador definition as follows:

```
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: grafana_mapping
      prefix: /<PREFIX>/
      service: grafana.<NAMESPACE>:3000
```

**Comment by cliveseldon** [comment]
Can you not write an [Ambassador prefix rewrite](https://www.getambassador.io/reference/rewrites/) to do this without changing Grafana?

**Comment by axsauze** [comment]
I did try - unfortunately grafana needs that to be defined on a config level, here are the details https://grafana.com/docs/installation/behind_proxy/. That's why I added the config required above. This config should be extended tho, as currently the config I provided would only work for the /grafana/ prefix, but that could be configured on a helm-chart-level.

**Comment by cliveseldon** [comment]
If we use the official Grafana and Prometheus charts this could maybe be changed to just be a docs update.
#613

**Comment by ryandawsonuk** [comment]
I hit this same issue running behind istio gateway and made the same change. I've started a PR adding support for [it to the seldon-core-analytics helm chart](https://github.com/SeldonIO/seldon-core/pull/650) as well as support for creating an istio VirtualService. Grafana [needs to know the path it is running on](https://github.com/SeldonIO/seldon-core/pull/650/files#diff-5e3fb95c76b2c7485bcac774eaeb3ea5R15), [even when using a rewrite rule](https://github.com/SeldonIO/seldon-core/pull/650/files#diff-859f2cbe13b3792ba9e626e709932af3R18).
