### ISSUE TITLE
Using the cluster-manager underlying API as a library

### ISSUE THREAD

**Issue by orendain** [SeldonIO/seldon-core#626]
It'd be great to use the cluster-manager project as a library (`SeldonDeploymentUtils`, and `SeldonDeploymentOperator.DeploymentResources`, for example, would give us a way of having Kubernetes-API-native Seldon objects to play with and manually deploy/manage in our own k8s systems).

I didn't see a published way of doing this - but it'd be great to have exposed.

**Comment by cliveseldon** [comment]
The cluster-manager has been replaced by the [seldon-operator](https://github.com/SeldonIO/seldon-operator) in release 0.3.0. 

Can you expand on what you are looking for? Are you using Java and want to use some of the functionality in the Java Cluster Manager?

**Comment by orendain** [comment]
We're using Java to manage our Kubernetes cluster by way of an in-house management library we've written.  We use a Kubernetes client API to create and launch deployments.  Ideally, we'd like to build/launch Seldon resources from within our java environment.

At the moment, we're resorting to calling `kubectl apply -f seldon-template.json` under the hood for deployment (and configuring the template via JSON transformations), but it'd be great to do something a bit more like: `kubernetesClient.deploy(new SeldonDeployment(myConfig));`.

Thanks for the info on seldon-operator - I had missed that! 😃

**Comment by cliveseldon** [comment]
We are planning to remove the cluster-manager code. However, there could be a use case for a Java API library based on the core code you mention to all Java users to create SeldonDeployments directly. We would be happy to have a PR for this if you are interested.

**Comment by orendain** [comment]
Thanks a lot - I'll bring this back to the team and see if anything comes from it.  It's likely that our `kubectl` backend workaround will do for the time being, but if our integration with Seldon increases we may have to put something together.
