### ISSUE TITLE
volume mounting kubeflow example

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#637]
Updates were made to examples in this repo for https://github.com/SeldonIO/seldon-core/issues/604

But kubeflow main example still needs updating - https://github.com/kubeflow/example-seldon/search?q=volumeSource&unscoped_q=volumeSource

**Comment by axsaucedo** [comment]
Would the current Kubeflow example in the repo be enough to close this issue or would we want a volume mounting-specific example?

**Comment by cliveseldon** [comment]
probably can close this as there are other Seldon examples now.
