### ISSUE TITLE
Seldon-core-operator install fails

### ISSUE THREAD

**Issue by colebaileygit** [SeldonIO/seldon-core#640]
**Background**
- Fresh kubernetes cluster setup using Docker for Mac k8 cluster.
- helm installed using `brew install helm`
- helm initialized using `helm init --history-max 200`

**Issue**
When following the documentation and installing the seldon-core-operator via `helm install seldon-core-operator --name seldon-core --repo https://storage.googleapis.com/seldon-charts --set usageMetrics.enabled=true` the following error occurs:

`Error: release seldon-core failed: CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[metadata].properties[annotations].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[metadata].properties[labels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[volumes].items.properties[flexVolume].properties[options].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[volumes].items.properties[csi].properties[volumeAttributes].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[affinity].properties[podAffinity].properties[preferredDuringSchedulingIgnoredDuringExecution].items.properties[podAffinityTerm].properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[affinity].properties[podAffinity].properties[requiredDuringSchedulingIgnoredDuringExecution].items.properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[affinity].properties[podAntiAffinity].properties[preferredDuringSchedulingIgnoredDuringExecution].items.properties[podAffinityTerm].properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[affinity].properties[podAntiAffinity].properties[requiredDuringSchedulingIgnoredDuringExecution].items.properties[labelSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[nodeSelector].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[hpaSpec].properties[metrics].items.properties[external].properties[metricSelector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[hpaSpec].properties[metrics].items.properties[object].properties[selector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[hpaSpec].properties[metrics].items.properties[pods].properties[selector].properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false]`

**Additional info**
helm version returns:
`Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}`

kubectl version returns:
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by colebaileygit** [comment]
Note: This issue does not occur when installing via minikube. I presume it is an issue related to the kubernetes server version used by Docker for Mac.

For first-time users it would be great to have more documentation on these kinds of restrictions for installation. (e.g. k8s version 1.14+ required)

**Comment by cliveseldon** [comment]
Hi - I think we require >=1.11 k8s server. I will update the docs. Can you test?

**Comment by cliveseldon** [comment]
Updated : https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html

**Comment by colebaileygit** [comment]
Can only confirm that it was not working for me on 1.10, but did indeed work with 1.14.

For this reason, I can recommend `minikube` instead of `docker-for-mac` built-in k8s since I am unaware how to update the latter.

**Comment by masonlr** [comment]
@colebaileygit, @cliveseldon, it is possible to deploy seldon-core to a k8s cluster using docker-for-desktop edge. You can download the edge releases from here https://docs.docker.com/docker-for-mac/edge-release-notes/

I have tested seldon-core on Docker Community Edition 2.0.5.0 2019-06-12, which runs Kubernetes 1.14.3.

**Comment by cliveseldon** [comment]
Thanks @masonlr

**Comment by cyrilthank** [comment]
![image](https://user-images.githubusercontent.com/4562436/66976689-75aa6880-f0c0-11e9-8d6c-d64cc1df7f83.png)

**Comment by divyadilip91** [comment]
Hi 
Could anyone help me with this error which occured when I tried to install seldon using kustomize.
After running the makefile under the seldon-core/operator directory , I get the below error

The CustomResourceDefinition "seldondeployments.machinelearning.seldon.io" is invalid: status.storedVersions[1]: Invalid value: "v1": must appear in spec.versions
Makefile:63: recipe for target 'deploy-cert' failed
make: *** [deploy-cert] Error 1

**Comment by cliveseldon** [comment]
@divyadilip91 Maybe create a new issue. 
Which Makefile command did you run and for which release?

**Comment by divyadilip91** [comment]
> @divyadilip91 Maybe create a new issue.
> Which Makefile command did you run and for which release?

I ran "make deploy" command-
The below line failed in the makefile and gave the above error
 "kubectl apply -f machinelearning.seldon.io_seldondeployments.yaml
I downloaded v0.5  - seldonio/seldon-core-operator:0.5.1-SNAPSHOT.  I even tried with version v1.0.1-SNAPSHOT (the latest one) but that also posed error in the make file

**Comment by cliveseldon** [comment]
Can you point to the Makefile line you are referring to?

**Comment by divyadilip91** [comment]
<img width="1322" alt="Screenshot 2020-01-13 at 9 12 15 PM" src="https://user-images.githubusercontent.com/57779683/72258684-a65f5700-3649-11ea-9f8d-058bb591acee.png">

**Comment by cliveseldon** [comment]
Is this because you have the CRD on your cluster from an old install?

**Comment by divyadilip91** [comment]
> Is this because you have the CRD on your cluster from an old install?

I am doubtful because as you said, first I had installed Seldon from the GCP marketplace which I unintsalled since it was not working. Then I reinstalled using kustomize.

**Comment by cliveseldon** [comment]
Could you confirm there is no seldon CRD by looking at `kubectl get crd seldondeployments.machinelearning.seldon.io`
Can you test on a fresh cluster - GKE or local Kind?

Also maybe join our Slack community - see link from top level github page.

**Comment by divyadilip91** [comment]
> Could you confirm there is no seldon CRD by looking at `kubectl get crd seldondeployments.machinelearning.seldon.io`
> Can you test on a fresh cluster - GKE or local Kind?
> 
> Also maybe join our Slack community - see link from top level github page.

Yes its working in a new cluster. I think the previous cluster had the crd by which this error was caused. Thankyou so much for your help.

**Comment by divyadilip91** [comment]
Could you please share the slack community link. I couldnt find it

**Comment by cliveseldon** [comment]
https://join.slack.com/t/seldondev/shared_invite/enQtMzA2Mzk1Mzg0NjczLTJlNjQ1NTE5Y2MzMWIwMGUzYjNmZGFjZjUxODU5Y2EyMDY0M2U3ZmRiYTBkOTRjMzZhZjA4NjJkNDkxZTA2YmU

**Comment by 0x717578** [comment]
Hi folks and @cliveseldon , just letting you know that this problem is still occurring.

Kubernetes v1.18 on MicroK8s, Helm 3, seldon-core-operator **v1.1.0**
This is a newly created instance, so there's no legacy CRDs or other objects floating around.

```
$ cat values.yaml 
ambassador:
  enabled: true
  singleNamespace: false                                                                        
single_namespace: false
crd:
  create: true

$ helm repo add seldon https://storage.googleapis.com/seldon-charts
$ helm install "seldon-core" seldon/seldon-core-operator --version=1.1.0 --values=values.yaml  --namespace=seldon-system

Error: CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

**Comment by 0x717578** [comment]
> Hi folks and @cliveseldon , just letting you know that this problem is still occurring.
> 
> Kubernetes v1.18 on MicroK8s, Helm 3, seldon-core-operator **v1.1.0**
> This is a newly created instance, so there's no legacy CRDs or other objects floating around.
> 
> ```
> $ cat values.yaml 
> ambassador:
>   enabled: true
>   singleNamespace: false                                                                        
> single_namespace: false
> crd:
>   create: true
> 
> $ helm repo add seldon https://storage.googleapis.com/seldon-charts
> $ helm install "seldon-core" seldon/seldon-core-operator --version=1.1.0 --values=values.yaml  --namespace=seldon-system
> 
> Error: CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
> ```
Ah. For others looking at this issue, I found this on the `seldondev` Slack channel:
https://github.com/SeldonIO/seldon-core/issues/1675

**Comment by cliveseldon** [comment]
I think the #1675 issue is due to k8s 1.18 incompatability while this is due to not having a 1.14> k8s I think.
