### ISSUE TITLE
Seldon & Istio - broken link

### ISSUE THREAD

**Issue by BakerLJ** [SeldonIO/seldon-core#643]
At the end of Seldon & Istio - https://github.com/SeldonIO/seldon-core/blob/bb9ce7fd7aece435100ceb720bc9a5f421de786a/doc/source/examples/istio.md  page, link is dead :  https://github.com/SeldonIO/seldon-core/blob/bb9ce7fd7aece435100ceb720bc9a5f421de786a/doc/source/examples/istio_canary.html. Potential replacement link is https://docs.seldon.io/projects/seldon-core/en/latest/examples/istio_canary.html

**Comment by cliveseldon** [comment]
This link works if viewed from the actual docs not the raw source

https://docs.seldon.io/projects/seldon-core/en/latest/examples/istio.html
