### ISSUE TITLE
Support Swagger or something like that

### ISSUE THREAD

**Issue by yu-iskw** [SeldonIO/seldon-core#645]
## Motivation
We potentially create a bunch of APIs with seldon. In order to share the specs of APIs among members, something like swagger would be necessary. Just writing docs about the spec by hand is not so productive. If APIs' spec would be easy to share and manage, that would be great!

Besides, if we introduce a standard way to design APIs across machine learning projects, it would be much easier to hand the APIs to other role, such as backend engineers and client engineers. In my opinion, following any of existing ways would be easy to standardize.

- https://swagger.io
- https://awslabs.github.io/smithy/

**Comment by cliveseldon** [comment]
We have OpenAPI specs. See https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/openapi.html
