### ISSUE TITLE
Docs do not mention addition of jsonData outside of the release notes

### ISSUE THREAD

**Issue by colebaileygit** [SeldonIO/seldon-core#652]
I wasn't aware of the `jsonData` support even after going through most of the docs and several examples until someone mentioned it on Slack - actually that was a use-case I was considering building my own work-around for.

I think this section of the docs should be updated to reflect this: https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/prediction.html

Perhaps also an example or snippet showing how the user-defined function signature works with dictionary data could be added.

**Comment by ryandawsonuk** [comment]
@colebaileygit if you're interested in submitting a PR you can modify that docs page at https://github.com/SeldonIO/seldon-core/blob/master/doc/source/reference/apis/prediction.md - you can even use the edit button direct from the github UI

**Comment by gsunner** [comment]
added scikit learn iris model using jsondata example PR #678

**Comment by gsunner** [comment]
Proto doc updated in PR #786
