### ISSUE TITLE
Remove Java Operator

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#654]
* Delete folder
 * Remove inclusion in build

**Comment by ryandawsonuk** [comment]
Would we also remove the 'seldon-core' helm chart in favour of the 'seldon-core-operator' one? Would that impact existing users on the old version or would the published versions of the chart remain out there?

**Comment by cliveseldon** [comment]
We need to check how the helm chart index is created but I think it merges with the new version so hopefully should be ok.
