### ISSUE TITLE
Ambassador Swagger definition does not include namespace

### ISSUE THREAD

**Issue by aarondav** [SeldonIO/seldon-core#660]
The generated Swagger definition linked to from [these docs](https://github.com/SeldonIO/seldon-core/tree/master/openapi) intended for Ambassador integration only allows providing `deployment`:

https://github.com/SeldonIO/seldon-core/blob/2de80865d4a03079c8986e84c823e3c1835d0af2/openapi/engine.oas3.json#L34

However, in practice it seems that both (Kubernetes) namespace and deployment are required. That is, the actual path should look like `/seldon/{namespace}/{deployment}/api/v0.1/predictions`.

Since Swagger HTML-escapes the input parameters, attempting to put a value for deployment like `namespace/deployment` gets escaped to `namespace%2Fdeployment`, so I think we need a second top-level parameter.

Please let me know if this proposal makes sense, or if I'm just missing something.

**Comment by cliveseldon** [comment]
Yes that makes sense. Will you submit a PR?
