### ISSUE TITLE
Feature_names is redundant when using jsonData in predict. Also meta is redundant in response, as meta can be combined in the jsonData.

### ISSUE THREAD

**Issue by chennupushkar** [SeldonIO/seldon-core#665]
When using jsonData, why does the predict signature still require features_names as an argument in the Predict function?
```def predict(self,X,features_names):
        """
        Return a prediction.

        Parameters
        ----------
        X : array-like
        feature_names : array of feature names (optional)
        """
        print("Predict called - will run identity function")
        return X```
. Also the response of the Predict function when using jsonData has meta:{} in it. When jsonData is suppose to be generic json why is predict function returning meta?
```curl -g http://localhost:5000/predict --data-urlencode 'json={"jsonData": {"ndarray": [[4.098, 2.128, 9.715, 2.977]]}}'
{"jsonData":{"my_predictions":[[3.9589564268624405e-18,4.098772877346702e-09,0.9999999959012271]]},"meta":{}}```

**Comment by cliveseldon** [comment]
Meta data is for the whole request and is understood by the engine component that manages the requests. So makes sense to keep it as a core Seldon feature for meta irrespective of data payload.

I agree feature names could be made a keyword argument which defaults to None.

https://github.com/SeldonIO/seldon-core/blob/559f897353fe70b4efa1d7f40d05a3ce1f78957b/python/seldon_core/user_model.py#L26

**Comment by cliveseldon** [comment]
Closing. Please open if issue.
