### ISSUE TITLE
Update NVIDIA-TensorRT Server Example

### ISSUE THREAD

**Issue by damitkwr** [SeldonIO/seldon-core#672]
Hi,

I am working on updating the NVIDIA TensorRT integration example to work since the TensorRT server only supports [Python3](https://ngc.nvidia.com/catalog/containers/nvidia:tensorrtserver/tags) and the commands for starting the container are now different. 

The work that I see that needs to be done is:

1. Change the seldonio/nvidia-inference-server-proxy as I think it is calling the TensorRT IS container
2. Change the helm charts for the nvidia_mnist example
3. Update the notebook to reflect the new changes

Let me know if there is anything else I need to change and i'll start on the changes then will do a PR request. I also might need access to the container repo to push the new image.

Thanks!

**Comment by cliveseldon** [comment]
Sounds great. Look forward to it!

**Comment by cliveseldon** [comment]
Taken out of 1.0 for now. @damitkwr feel free to update if you have done any more work on this.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Closing this. Please retry with latest release with Triton.
