### ISSUE TITLE
Income Classifier Example with Kubeflow

### ISSUE THREAD

**Issue by JoelH96** [SeldonIO/seldon-core#676]
The income classifier example is currently used to demo Alibi/explainers. The income classifier is deployed using seldonctl, the income classifier explainer can then be deployed through the Deploy UI. 

Need to develop the creation/training and deployment of the income classifier model with Kubeflow. This will allow for a full end-to-end demo, showing Kubeflow+Alibi.

**Comment by cliveseldon** [comment]
I think this is outdated as the examples have moved on.
