### ISSUE TITLE
TLS handshake errors in manager logs

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#680]
example:
```
TLS handshake error from 10.1.2.64:47392: tls: first record does not look like a TLS handshake
```

Maybe related to https://github.com/kubernetes/kubernetes/issues/70411

**Comment by cliveseldon** [comment]
Does not seem to impact  controller operation but needs to be researched some more.

**Comment by oshev** [comment]
Confirmed, these errors don’t affect the work of the controller-manager. We managed to run our system on the latest Seldon and pass our tests.

**Comment by cliveseldon** [comment]
Not longer valid we have moved to kubebuilder v2
