### ISSUE TITLE
Deployment with empty oauth key

### ISSUE THREAD

**Issue by Koshmaar** [SeldonIO/seldon-core#683]
Hi, I was using Seldon core 0.2.4 and deploying models was working fine. After bumping version to 0.2.8 I started getting this error in seldon-core-seldon-apiserver on kubernetes:
```
2019-07-09 09:55:47.309  WARN 1 --- [pool-3-thread-1] i.s.apife.deployments.DeploymentStore    : Deployment with empty oauth key - ignoring dep-6028066
2019-07-09 09:55:47.309  WARN 1 --- [pool-3-thread-1] io.seldon.apife.grpc.SeldonGrpcServer    : Empty oauth key ignoring for dep-6028066
```
Deployments don't appear in `kubectl get sdep`. From what I've checked, warning comes from this code in https://github.com/SeldonIO/seldon-core/blob/master/api-frontend/src/main/java/io/seldon/apife/deployments/DeploymentStore.java :

```
 public void deploymentAdded(SeldonDeployment mlDep) {
		 final DeploymentSpec deploymentDef = mlDep.getSpec();
		 final String namespace = k8sUtil.getNamespace(mlDep);
		 
		 if (StringUtils.isEmpty(deploymentDef.getOauthKey())) // XXX
		 {
			 logger.warn("Deployment with empty oauth key - ignoring {}",deploymentDef.getName());
		 }
                 else // add deployment
````
Before 0.2.5 the if at XXX wasn't there, and I guess because of that deployments were created without any special oauth handling. And they were curl-able.

In docs there are examples only on how to configure Sedon Oauth gateway ie. https://docs.seldon.io/projects/seldon-core/en/latest/ingress/seldon.html

But I'm using Ambassador gateway from seldon chart. I don't see there any place for configuring this oath behaviour. How can that be done? Or what did I miss? Ideally I'd like to disable Oauth for Ambassador.

**Comment by cliveseldon** [comment]
If you are using Ambassador then this should not affect you. The Oauth gateway is deprecated.
The fact the deployments are not appearing must be for a different reason.
Can you update to seldon 0.3.1 to test?
For that you should install the Helm chart `seldon-core-operator` and then the ingress of your choice - in your case Ambassador.

**Comment by cliveseldon** [comment]
Please reopen if still an issue.
