### ISSUE TITLE
docs: Ambassador REST endpoint path

### ISSUE THREAD

**Issue by masonlr** [SeldonIO/seldon-core#688]
Should the Ambassador REST endpoint docs mention the namespace in which a model is deployed, or am I missing something here?

To reproduce:

The Ambassador REST docs at https://docs.seldon.io/projects/seldon-core/en/v0.3.1/workflow/serving.html state:

> A REST endpoint will be exposed at : `http://<ambassadorEndpoint>/seldon/<deploymentName>/api/v0.1/predictions`

If, as an example, I deploy a model on minikube following https://github.com/SeldonIO/seldon-core/blob/v0.3.1/examples/models/mlflow_model/mlflow.ipynb and port-forward using

```shell
kubectl port-forward $(kubectl get pods -l app.kubernetes.io/name=ambassador -o jsonpath='{.items[0].metadata.name}')  8003:8080
```

then the namespace seems to be needed in the REST endpoint path: i.e. predictions are accessible via

```shell
curl -v 0.0.0.0:8003/seldon/default/mlflow-example/api/v0.1/predictions -d '{"data": {"ndarray": [[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}}'  -H "Content-Type: application/json"
```

If I deploy the same mlflow-example model into a "seldon" namespace (loosely following https://github.com/SeldonIO/seldon-core/blob/v0.3.1/notebooks/helm_examples.ipynb), then the model predictions are accessible via

```
curl -v 0.0.0.0:8003/seldon/seldon/mlflow-example/api/v0.1/predictions -d '{"data": {"ndarray": [[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}}'  -H "Content-Type: application/json"
```

Both of these have a namespace in the path? If the above is correct/intended, then a change like the following would be clearer for new users:

> A REST endpoint will be exposed at : `http://<ambassadorEndpoint>/seldon/<deploymentNamespace>/<deploymentName>/api/v0.1/predictions`

**Comment by cliveseldon** [comment]
Yes you are correct. We had both before but as the operator is clusterwide by default at present then the namespace is needed to ensure no clashes. We should update the docs.
