### ISSUE TITLE
Deploying modified TensorRT example on GKE does not deploy anything

### ISSUE THREAD

**Issue by damitkwr** [SeldonIO/seldon-core#694]
Hi,

I am modifying the TensorRT example by getting rid of the TRTProxy Image and directly including a TRTServer pod in the deployment and a TYPE: MODEL deployment. Here is the relevant slack thread:

https://seldondev.slack.com/archives/C8Y9A8G0Y/p1563207453433900

**Comment by damitkwr** [comment]
Update: The issue seems to be the liveness probe and readiness probe. Seldon was not recognizing this as seen by this: 

`{
 controller:  "seldondeployment-controller"
 error:  "Deployment.apps "trt-sp-sp-nvidia-72d9821" is invalid: [spec.template.spec.containers[1].livenessProbe: Required value: must specify a handler type, spec.template.spec.containers[1].readinessProbe: Required value: must specify a handler type]"
 level:  "error"
 logger:  "kubebuilder.controller"
 msg:  "Reconciler error"
 request:  "kubeflow/nvidia-sp"
 stacktrace:  "github.com/seldonio/seldon-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error
    /go/src/github.com/seldonio/seldon-operator/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217
github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
    /go/src/github.com/seldonio/seldon-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
    /go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
    /go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until
    /go/src/github.com/seldonio/seldon-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
 ts:  1563215708.732645
}`

**Comment by cliveseldon** [comment]
Can you show the yaml that is creating this error?
