### ISSUE TITLE
docs: Python API reference

### ISSUE THREAD

**Issue by masonlr** [SeldonIO/seldon-core#696]
Trying to help improve the docs here: As a new user, I found it difficult to find the functionality of the python `seldon_core.seldon_client`. Two things that might help:

1. **Suggestion:** Move/copy the "Python API reference"  section of the docs from "WRAPPERS > Python Models > Python API reference" to "REFERENCE > Python API reference".

2. As a new user you land at [Seldon Core Python API Client](https://docs.seldon.io/projects/seldon-core/en/latest/python/python_module.html#seldon-core-python-api-client) then are directed to [Example Seldon Core Deployments using Helm
](https://docs.seldon.io/projects/seldon-core/en/latest/examples/helm_examples.html)  
The code fragments these links don't demonstrate how to pass data payloads to `sc.predict()`. If you are quickly skimming the docs (for example when evaluating whether to use the library) it is easy to misunderstand what functionality is available.  
**Suggestion:** Add a brief example of passing a data payload to `sc.predict()` in the docs/example links above. Examples exist in other places (`canary.ipynb`, `kubeflow_seldon_e2e_pipeline.ipynb`, etc.), but unless you know where these are it's difficult to find a reference example.

**Comment by cliveseldon** [comment]
Thanks. Useful suggestion.
