### ISSUE TITLE
docs: ambassador version

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#697]
[Lots of our notebooks](https://github.com/SeldonIO/seldon-core/search?q=There+are+gRPC+issues+with+the+latest+Ambassador%2C+so+we+rewcommend+0.40.2+until+these+are+fixed.&unscoped_q=There+are+gRPC+issues+with+the+latest+Ambassador%2C+so+we+rewcommend+0.40.2+until+these+are+fixed.) say "There are gRPC issues with the latest Ambassador, so we rewcommend 0.40.2 until these are fixed." Then the notebooks go on to install the latest ambassador. We should remove the comment.

**Comment by cliveseldon** [comment]
Should be fixed by #646
