### ISSUE TITLE
Java Seldon Engine doesn't pass microservice HTTP exceptions upstream

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#705]
When the microservice raises a `SeldonMicroserviceException` in the Python Wrapper, the Java seldon engine currently doesn't send the information upstream (i.e. the message, reason, code, etc). This would be required functionality in order for the errors to provide richer information on the microservice errors. This would require changing the `InternalPredictionService.java`'s `queryREST` function to add the functionality to parse the error from the microservice and return it.

**Comment by cliveseldon** [comment]
Should be fixed now.
