### ISSUE TITLE
Ambassador does not work in v0.3.2

### ISSUE THREAD

**Issue by damitkwr** [SeldonIO/seldon-core#710]
Hi,

Ambassador annotations are not added it v0.3.2. I downgraded to v0.3.1 and works.

**Comment by cliveseldon** [comment]
Can you give some further details. You mean 0.3.2-SNAPSHOT running from master?
Which version of Ambassador>
Can you run the [helm examples notebook](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/helm_examples.ipynb)

I just tested with master with 
quay.io/datawire/ambassador:0.70.1 and this works.

**Comment by cliveseldon** [comment]
I tried with latest stable ambassador 0.73.0 and this also works.

**Comment by damitkwr** [comment]
Upgrading the ambassador version work now. Kubeflow has an older ambassador version installed. Thanks
