### ISSUE TITLE
calling SeldonClient.predict inside a microservice model rasing "TypeError: Couldn't build proto file into descriptor pool!"

### ISSUE THREAD

**Issue by Ridooo** [SeldonIO/seldon-core#711]
Any idea how can I workaround this issue?

Inside a model I am calling another deployment using SeldonClient.predict. When the SeldonClient is imported the below error is raised.
from seldon_core.seldon_client import SeldonClient

r = self.sc.predict(gateway="ambassador",transport="rest",data=X,method="aggregate", payload_type="ndarray")

root@ea4c26c01ce4:/microservice# python -u microservice.py HWRModel REST --service-type MODEL --persistence 0
Traceback (most recent call last):
  File "microservice.py", line 154, in <module>
    interface_file = importlib.import_module(args.interface_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/microservice/HWRModel.py", line 1, in <module>
    from seldon_core.seldon_client import SeldonClient
  File "/usr/local/lib/python3.6/site-packages/seldon_core/seldon_client.py", line 1, in <module>
    from seldon_core.proto import prediction_pb2
  File "/usr/local/lib/python3.6/site-packages/seldon_core/proto/prediction_pb2.py", line 27, in <module>
    dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,])
  File "/usr/local/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 879, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "proto/prediction.proto":
  proto/prediction.proto: A file with this name is already in the pool.

**Comment by cliveseldon** [comment]
This is strange. I attempted to repeat by running {sklearn iris notebook](https://docs.seldon.io/projects/seldon-core/en/latest/examples/iris.html) and adding `from seldon_core.seldon_client import SeldonClient` in the import section but seems to be fine.

This was wrapped using `s2i build . seldonio/seldon-core-s2i-python3:0.10 sklearn-iris:0.1`

Can you create a small test case?

**Comment by Ridooo** [comment]
It works now. I was using this  image  seldonio/seldon-core-s2i-python3.
thank you.

**Comment by cliveseldon** [comment]
Glad it works.

**Comment by panbalag** [comment]
The error still exists. I tried building https://github.com/SeldonIO/seldon-core/tree/master/integrations/tfserving with seldonio/seldon-core-s2i-python3:latest. The build is successful, but when the container is started, I see the following error,

Traceback (most recent call last):
  | File "microservice.py", line 154, in <module>
  | interface_file = importlib.import_module(args.interface_name)
  | File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
  | return _bootstrap._gcd_import(name[level:], package, level)
  | File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  | File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  | File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  | File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  | File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  | File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  | File "/microservice/tfservingproxy.py", line 8, in <module>
  | from seldon_core.utils import get_data_from_proto, array_to_grpc_datadef, json_to_seldon_message, grpc_datadef_to_array
  | File "/usr/local/lib/python3.6/site-packages/seldon_core/utils.py", line 4, in <module>
  | from seldon_core.proto import prediction_pb2
  | File "/usr/local/lib/python3.6/site-packages/seldon_core/proto/prediction_pb2.py", line 27, in <module>
  | dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,])
  | File "/usr/local/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 879, in __new__
  | return _message.default_pool.AddSerializedFile(serialized_pb)
  | TypeError: Couldn't build proto file into descriptor pool!
  | Invalid proto descriptor for file "proto/prediction.proto":
  | proto/prediction.proto: A file with this name is already in the pool.
