### ISSUE TITLE
eliminate cluster wide Secret access RBAC

### ISSUE THREAD

**Issue by phsiao** [SeldonIO/seldon-core#714]
It is not clear to me if that is needed, and I can't find in the code where it is actually being used, but the requirement of that is making adoption of it difficult in a production environment.

**Comment by cliveseldon** [comment]
The secret is just for the certs for the webhook. This should definitely be limited to the namespace that the operator manager is running inside.

**Comment by cliveseldon** [comment]
This seems to be conected to https://github.com/kubernetes-sigs/kubebuilder/issues/748

**Comment by phsiao** [comment]
With the latest 0.3.2 SNAPSHOT now it needs serviceaccounts and configmaps privilege at the cluster-level.  This will make deployment in multi-tenant environment more challenging.

**Comment by cliveseldon** [comment]
Which serviceaccounts and configmaps are you referring to preciscely?

**Comment by phsiao** [comment]
I just updated to latest 0.3.2-SNAPSHOT today, and the operator/webhook now requires access to both kinds of objects at cluster level and if not it would generate these errors in the log

```E0808 16:45:47.222112       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:seldon-core:seldon-core-operator" cannot list resource "configmaps" in API group "" at the cluster scope```

```E0808 19:13:49.634162       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:196: Failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:seldon-core:seldon-core-operator" cannot list resource "serviceaccounts" in API group "" at the cluster scope```

**Comment by cliveseldon** [comment]
I think you solved this @phsiao so closing.
