### ISSUE TITLE
multiple containers in componentSpecs.spec.containers not supported?

### ISSUE THREAD

**Issue by phsiao** [SeldonIO/seldon-core#718]
Don't know if this was the design goal, but I was assuming it would support multiple containers (not all being used for serving, for example, opentracing agent sidecar); however, it does not appear to work, and cursory inspection of the code I think the problem is https://github.com/SeldonIO/seldon-operator/blob/master/pkg/controller/seldondeployment/seldondeployment_controller.go#L635 where there is no matching graph entry and it does not know what to do with it.

**Comment by cliveseldon** [comment]
Its definitely meant to be allowed to have multiple containers including ones outside the graph. This must be a bug introduced on the move to the Go operator.

**Comment by cliveseldon** [comment]
can you retest with 0.3.2-SNAPSHOT release from master? This should be fixed.

**Comment by phsiao** [comment]
Confirmed that I can add additional container without problem in a very simple case.  Thanks!
