### ISSUE TITLE
versions for prepackaged model servers

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#724]
For example I tried the SKLEARN_SERVER with a scikit-learn 0.21.0 model. I found I had to downgrade the model to 0.20.3 to get it to work.

We should declare the versions for prepackaged servers. Ideally we'd provide options for users to choose a version.

**Comment by axsaucedo** [comment]
That's a good point - it currently provides versions of prepackaged model servers through the docker tags, but I agree we should probably have a way to have a SKlearn / xgboost version with the range of compatible versions.

**Comment by cliveseldon** [comment]
At least update docs

**Comment by ryandawsonuk** [comment]
Interesting notes on this - https://github.com/kubeflow/kfserving/blob/10e9b88eda747e716744a14db8b57bf23166bd3e/pkg/apis/serving/v1alpha1/framework_tensorflow.go#L32 and https://github.com/kubeflow/kfserving/blob/cdd0aeac8a4212605db86ad520321a45213eff03/install/v0.1.0/kfserving.yaml#L505

**Comment by gsunner** [comment]
Versions used in the the current prepackaged servers

seldonio/sklearnserver_rest:0.2     sklearn: v0.20.3
seldonio/xgboostserver_rest:0.2     xgboost: v0.82
seldonio/mlflowserver_rest:0.2      pandas: v0.25.0, mlflow: 1.1.0
