### ISSUE TITLE
exception swallowing in seldon-core

### ISSUE THREAD

**Issue by ryandawsonuk** [SeldonIO/seldon-core#725]
e.g. https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/user_model.py#L141

We were hitting this when having a sklearn version mismatch. The end result was that the model returned an empty message and didn't log any error.

**Comment by axsaucedo** [comment]
This may be another place where #700 will have to be changed, as there are AttributeErrors that are being caught as well, which may not be just due to the Model wrapper not implementing a specific function.

**Comment by cliveseldon** [comment]
Duplicate #700
