### ISSUE TITLE
tracing not sharing context from ambassador?

### ISSUE THREAD

**Issue by phsiao** [SeldonIO/seldon-core#731]
I am using ambassador as ingress gateway for sleldon-core.  This may not be a bug but I am hoping there are more insights from the community.

With the default configuration from `template_model_tracing` as well as enabling zipkin tracing using [TracingService](https://www.getambassador.io/reference/services/tracing-service/), I ended up with two separate sets of traces, one for ambassador (isolated) and another for seldon-core (including the model).   I have verified that ambassador sets the headers to include the context.

I assume it does not work because ambassador only sent context using zipkin-style header (b3), while by default the jaeger java client that the engine uses assumes jaeger style header.  I tried setting `JAEGER_PROPAGATION` according to the [java client doc](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/README.md) to 'b3' but it still leads to two sets of traces.

Appreciate help here.

**Comment by phsiao** [comment]
Actually, just tried to use grpc instead of rest, and it works for grpc, just not for rest, that is,

seldon-core-api-tester -p contract.json <gateway endpoint> tracing-example -n 1 --grpc

works, but with --grpc I ended up with two sets of traces.

**Comment by cliveseldon** [comment]
That's interesting. We do use Jaeger in the engine. Not sure why gRPC would only produce 1 trace and REST not. Would need to check the code that starts the traces in both

grpc: https://github.com/SeldonIO/seldon-core/blob/978bbddbb07891fd6c8b6cc44fb7ec20ae82bdcb/engine/src/main/java/io/seldon/engine/grpc/GrpcChannelHandler.java#L31-L34

rest: https://github.com/SeldonIO/seldon-core/blob/978bbddbb07891fd6c8b6cc44fb7ec20ae82bdcb/engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java#L157-L161

Maybe `io.opentracing.contrib.grpc.TracingClientInterceptor` does something more intelligent?

**Comment by cliveseldon** [comment]
Lets test in new executor and reopen if still an issue
