### ISSUE TITLE
Golang CRD api

### ISSUE THREAD

**Issue by Koshmaar** [SeldonIO/seldon-core#734]
Hi, are there any plans to create golang API for deploying models, deleting them etc. using client-gen tools? There are some resources about that:
* https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md
* https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/
* https://itnext.io/how-to-generate-client-codes-for-kubernetes-custom-resource-definitions-crd-b4b9907769ba

I know about https://github.com/SeldonIO/seldon-core/tree/master/examples/wrappers/go
But it is using json which would need to be templated, while using approaches from above would allow to use golang types.

**Comment by cliveseldon** [comment]
You mean more than https://github.com/SeldonIO/seldon-operator/tree/master/pkg/client ?

**Comment by Koshmaar** [comment]
Actually it looks like exactly what I need. Question though, is it compatible with Seldon 2.8? I don't want to upgrade now to 3.0+ (which AFAIK bundled core and core-crd into operator).

**Comment by cliveseldon** [comment]
It should be compatible as the CRD is backwards compatible between these versions. We haven't tried. Please feedback.

**Comment by Koshmaar** [comment]
I am able to deploy model using seldon 0.2.8 with golang seldon operator library :) However, now the deployment is bundled into one ie. 
```
my-namespace   dep-5188857-dep-5188857-d660749-74cc64bc8d-cnsjp          2/2     Running             0          37s
```
which has two containers with classifier and seldon-container-engine. While before deployment consisted of two pods -classifier and -svc-orch , ie. 
```
dep-2511961-dep-2511961-classifier-0-64997cd757-9kmmr
dep-2511961-dep-2511961-svc-orch-58cf4d4bdd-5m7qk
```
Is it something that has been changed in 0.3.0? Or perhaps its caused by deploying model in custom namespace (instead of default)? Also, is there a way to control it (bring back old structure)?

**Comment by cliveseldon** [comment]
Yes the engine svc-orch will be packaged by default in your first podSpec. If you want the old behaviour you can control this with the annotation seldon.io/engine-separate-pod

See https://docs.seldon.io/projects/seldon-core/en/latest/graph/annotations.html#service-orchestrator

**Comment by Koshmaar** [comment]
Thanks :)
