### ISSUE TITLE
Prometheus endpoint sending invalid type for Histograms

### ISSUE THREAD

**Issue by amoldavsky** [SeldonIO/seldon-core#740]
For record of type  `Histogram` the Prometheus endpoint sends `quantiles` which is not a supported type for `Histogram`. It seems as if the Seldon Prometheus server is throwing these records away, but our DataDog implementation is trying to make sense of these records and results in broken reports.

here is a log snippet:
```
# HELP seldon_api_engine_client_requests_seconds Timer of RestTemplate operation
# TYPE seldon_api_engine_client_requests_seconds histogram

seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.5",} 0.005767168

seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.75",} 0.006029312

seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.95",} 0.0065536

seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.98",} 0.00786432

seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.99",} 0.00917504

seldon_api_engine_client_requests_seconds_bucket{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",le="0.001",} 0.0

seldon_api_engine_client_requests_seconds_bucket{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-
```

The first five are Histograms but having a type of quantile.

According to the documentation, `Histogram` only supports three types and `quantiles` is not one of them:
https://prometheus.io/docs/concepts/metric_types/#histogram

**Comment by cliveseldon** [comment]
We are using micromerter with the configuration:

https://github.com/SeldonIO/seldon-core/blob/559f897353fe70b4efa1d7f40d05a3ce1f78957b/engine/src/main/resources/application.properties#L6-L7

What version of Prometheus are you using? We have had no issues with these metrics in our analytics helm chart using Prometheus and Grafana.

Can you post the error from which component you are seeing?

**Comment by cliveseldon** [comment]
This is our setup at present:

https://github.com/SeldonIO/seldon-core/blob/58927fa0462174717d414636b417a72e2d868aee/engine/src/main/resources/application.properties#L4-L8

Happy to discuss how this can be changed.

**Comment by markusgay** [comment]
Your Grafana dashboard file predictions-analytics-dashboard.json uses the function histogram_quantile (e. g.  below) to calculate the quantile from the buckets on the server-side. So the application setting 'management.metrics.distribution.percentiles.all=0.5, 0.75, 0.95, 0.98, 0.99' is not needed, which creates quantiles on the application side. 

<code>
       "expr": "histogram_quantile(0.99, sum(rate(seldon_api_engine_client_requests_seconds_bucket{uri=\"/predict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[20s])) by (predictor_name,predictor_version,model_name,model_image,model_version,le))",
</code>

If you want use Prometheus Histogram and Summary metric types in your dashboards you would have to create two separate timed metrics in your application source code. At the moment, this cannot be achived by using application property settings.

**Comment by cliveseldon** [comment]
Are you saying micrometer does not allow for what you need. Are you able to suggest the correct config for sping/micrometer?

**Comment by markusgay** [comment]
The configuration without the line 'management.metrics.distribution.percentiles.all=0.5, 0.75, 0.95, 0.98, 0.99'  is working for us. I also looked at your Grafan dashboard code, and it is using the function histogram_quantile. So removing the configuratiob setting 'management.metrics.distribution.percentiles.all=0.5, 0.75, 0.95, 0.98, 0.99' should not break your dashboards.

**Comment by cliveseldon** [comment]
We are moving to Go replacement. Will be available in 1.1

**Comment by cliveseldon** [comment]
Please reopen if an issue in Go executor @markusgay

**Comment by zyxue** [comment]
> For record of type `Histogram` the Prometheus endpoint sends `quantiles` which is not a supported type for `Histogram`. It seems as if the Seldon Prometheus server is throwing these records away, but our DataDog implementation is trying to make sense of these records and results in broken reports.
> 
> here is a log snippet:
> 
> ```
> # HELP seldon_api_engine_client_requests_seconds Timer of RestTemplate operation
> # TYPE seldon_api_engine_client_requests_seconds histogram
> 
> seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.5",} 0.005767168
> 
> seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.75",} 0.006029312
> 
> seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.95",} 0.0065536
> 
> seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.98",} 0.00786432
> 
> seldon_api_engine_client_requests_seconds{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",quantile="0.99",} 0.00917504
> 
> seldon_api_engine_client_requests_seconds_bucket{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-predictor",predictor_version="v1",status="200",uri="/predict",le="0.001",} 0.0
> 
> seldon_api_engine_client_requests_seconds_bucket{clientName="localhost",deployment_name="mnist-deployment",method="POST",model_image="seldonio/sk-example-mnist",model_name="sk-mnist-classifier",model_version="0.2",predictor_name="sk-mnist-
> ```
> 
> The first five are Histograms but having a type of quantile.
> 
> According to the documentation, `Histogram` only supports three types and `quantiles` is not one of them:
> https://prometheus.io/docs/concepts/metric_types/#histogram

I also find this a bit confusing. Do I understand correctly that in principle, those quantile lines (with `quantile="something"`) shouldn't appear in the histogram metric type?
