### ISSUE TITLE
Liveness probe kills seldon engine container when model predict function takes a long time to send a result

### ISSUE THREAD

**Issue by pisymbol** [SeldonIO/seldon-core#753]
Seldon-Core 0.3.0
Client Version: 1.15
Server Version: 1.13

What's happening is we have a long pipeline for model segmentation (a color image gets segmented into hundreds of images, some DL is performed, then reassembled and finally returned).

The whole pipeline works until the very end when we are returning the largish image (4032, 3024, 3) over the wire. The network latency is probably around 1-2 minutes through my VPN connection. As a result, the liveness probe kills the container like so:

```
019-08-05 20:18:55.505  WARN 1 --- [pool-2-thread-1] i.s.e.api.rest.SeldonGraphReadyChecker   : Failed to connect to localhost:9000
2019-08-05 20:18:55.505  WARN 1 --- [pool-2-thread-1] i.s.e.api.rest.SeldonGraphReadyChecker   : Failed to connect to localhost:9000
2019-08-05 20:18:55.505  WARN 1 --- [pool-2-thread-1] i.s.e.api.rest.SeldonGraphReadyChecker   : Failed to connect to localhost:9000
2019-08-05 20:18:55.505  WARN 1 --- [pool-2-thread-1] i.s.e.api.rest.SeldonGraphReadyChecker   : Failing localhost:9000
2019-08-05 20:18:55.506  INFO 1 --- [pool-2-thread-1] i.s.e.api.rest.SeldonGraphReadyChecker   : aicv-pmg-graph not ready!
2019-08-05 20:18:55.801  WARN 1 --- [nio-8082-exec-9] i.s.e.api.rest.RestClientController      : Not ready graph checker false, controller true
2019-08-05 20:18:56.801  WARN 1 --- [io-8082-exec-10] i.s.e.api.rest.RestClientController      : Not ready graph checker false, controller true
2019-08-05 20:18:57.801  WARN 1 --- [nio-8082-exec-1] i.s.e.api.rest.RestClientController      : Not ready graph checker false, controller true
2019-08-05 20:18:58.587  WARN 1 --- [nio-8082-exec-2] i.s.e.api.rest.RestClientController      : Not ready graph checker false, controller true
2019-08-05 20:18:58.801  WARN 1 --- [nio-8082-exec-3] i.s.e.api.rest.RestClientController      : Not ready graph checker false, controller true
2019-08-05 20:18:59.801  WARN 1 --- [nio-8082-exec-4] i.s.e.api.rest.RestClientController      : Not ready graph checker false, controller true
```

I can literally watch these message appear as seldon is serializing the image and sending it over to the wire. As a result, the client sees a 502 response in its request.

How can I avoid this from happening? This is very similar to Issue #674 but happens at the end of predict.

**Comment by axsaucedo** [comment]
Interesting. This would actually get fixed once #684 is merged (as a quick fix), as that pr will enable for multiple workers which will be able to respond to the liveness probe whilst the longer request is processing. For the meantime you can configure your own liveness probes to provide a longer time - have you tried extending the liveness probe times?

**Comment by pisymbol** [comment]
Can you please give me an example on what you think works? I have tried several iterations of this with no success.

**Comment by pisymbol** [comment]
```
 "containers": [
                            {
                                "image": "foo:latest",
                                "imagePullPolicy": "IfNotPresent",
                                "name": "aicv-pmg-graph",
                                "resources": {
                                    "requests": {
                                        "memory": "4Gi"
                                    }
                                },
				"livenessProbe": {
				    "timeoutSeconds": 300,
			            "handler": {
					"tcpSocket": {
					    "port" : "http"
					}
				    }
				}
                            }
```

No worky though...

**Comment by pisymbol** [comment]
The other thing strange is that it always happen at the EXACT same time no matter what I set my liveness probe too. What is going on here?

**Comment by ryandawsonuk** [comment]
I think it's the engine liveness probe failing rather than the one on your model, just like in https://github.com/SeldonIO/seldon-core/issues/674#issuecomment-517175318 Could you try again using the latest snapshot version - 0.3.2-SNAPSHOT ?

**Comment by pisymbol** [comment]
I agree @ryandawsonuk but I don't know how to change the liveness/readiness probe (if it is even possible). Let me see if I can get the SNAPSHOT installed. Is there any workaround to this issue though? It is preventing ALL of our models from being deployed under Seldon right now.

**Comment by cliveseldon** [comment]
Have you tried with latest master install of the seldon-operator? As the liveness probe that @ryandawsonuk mentioned should fix your issue.

**Comment by pisymbol** [comment]
Just tried 0.3.2-SNAPSHOT, same thing.

Are you saying I should try master of everything or just seldon-operator?

**Comment by cliveseldon** [comment]
Just the seldon-operator should be good enough. Can you check the yaml of your deployment and see if the liveness probe for the engine point to `/live`.

**Comment by pisymbol** [comment]
@cliveseldon On 0.3.2-SNAPSHOT:

    Liveness:   tcp-socket :http delay=60s timeout=1s period=5s #success=1 #failure=3
    Liveness:   http-get http://:admin/live delay=20s timeout=2s period=5s #success=1 #failure=7

**Comment by pisymbol** [comment]
Another question, is there a way to just shutoff the seldon-container-engine liveness probe completely or fake it as a temporary workaround?

**Comment by cliveseldon** [comment]
Not at present.

So its suggesting the java code is not able to respond to the liveness probe with a timeout of 2 secs when processing the return of the image. Are you sure the java has enough memory and its not garbage collecting or otherwise stalled during this time? Have you set engine resource request to a high value and does your cluster node have enough memory?

**Comment by pisymbol** [comment]
If java was running out of memory, wouldn't we see that in the Spring logs? The pod's node has 64GB of RAM, that's plenty. I've limited my pod to 4GB, I can up to 8GB if you think that will help?

**Comment by cliveseldon** [comment]
its more about adding more resources to the engine.

**Comment by pisymbol** [comment]
Which engine? You mean my pod or the seldon-container-engine. I think you mean the latter.

Both are running on a host with 64GB of RAM. Are you talking about giving java more memory? How do I that?

Here is the command you guys run:

java -Djava.security.egd=file:/dev/./urandom -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.manag
ement.jmxremote.local.only=false -Djava.rmi.server.hostname=127.0.0.1 -jar app.jar

One thing I suggest is run it in '-server' mode or set higher defaults for -Xms and maybe -Xmx.

I was reading Issue #398 but the doc link goes to 404. How can I allocate more resources to the seldon-engine-container sidecar?

**Comment by cliveseldon** [comment]
you can add a `svcOrchSpec` section, e.g.:

```
{
  "apiVersion": "machinelearning.seldon.io/v1alpha2",
  "kind": "SeldonDeployment",
  "metadata": {
    "labels": {
      "app": "seldon"
    },
    "name": "release-name"
  },
  "spec": {
    "annotations": {
      "seldon.io/engine-log-message-type": "seldon.message.pair",
      "seldon.io/engine-log-messages-externally": "false",
      "seldon.io/engine-log-requests": "false",
      "seldon.io/engine-log-responses": "false",
      "seldon.io/headless-svc": "false"
    },
    "name": "release-name",
    "predictors": [
      {
        "componentSpecs": [
          {
            "spec": {
              "containers": [
                {
                  "image": "seldonio/mock_classifier:1.0",
                  "imagePullPolicy": "IfNotPresent",
                  "name": "classifier",
                  "resources": {
                    "requests": {
                      "memory": "1Mi"
                    }
                  },
                  "env": [
                    {
                      "name": "LOG_LEVEL",
                      "value": "INFO"
                    }
                  ]
                }
              ],
              "terminationGracePeriodSeconds": 1
            }
          }
        ],
        "graph": {
          "children": [],
          "name": "classifier",
          "type": "MODEL",
          "endpoint": {
            "type": "REST"
          }
        },
        "svcOrchSpec": {
          "resources": {
            "requests": {
              "cpu": "0.1"
            }
          },
          "env": []
        },
        "name": "release-name",
        "replicas": 1,
        "labels": {
          "fluentd": "true",
          "version": "v1"
        }
      }
    ]
  }
}
```

**Comment by pisymbol** [comment]
Ok, slightly different now. Readiness probe failed not the liveness one. That was with 4Gi.

**Comment by pisymbol** [comment]
Eureka! 8Gi worked!!!!!!! 

Alright, so how can this error be diagnosed a bit better in the future? And is there anything future model deployers should know? I mean this really hit me out of left field without a lot of things to go on.

**Comment by cliveseldon** [comment]
great!

Some metrics from a k8s dashboard that shows the java engine is thrashing/garbage collecting would be ideal. We should be able to add engine memory, cpu metrics or something that shows the pod is under heavy load.

**Comment by pisymbol** [comment]
Thanks again Clive et al.

I would have given you a few bucks for just a warning or alert message from the side car container that memory is low. 

What I do suggest is that in future releases deployers have more control over the seldon-container-engine side car resources etc.

**Comment by ryandawsonuk** [comment]
Have created https://github.com/SeldonIO/seldon-core/issues/761 as a follow-up action
