### ISSUE TITLE
docs: python wrapping docker

### ISSUE THREAD

**Issue by masonlr** [SeldonIO/seldon-core#754]
There's likely a rogue `exec` in the example Dockerfile at https://github.com/SeldonIO/seldon-core/blob/v0.3.1/doc/source/python/python_wrapping_docker.md.

Suggest changing: 

```dockerfile
CMD exec seldon-core-microservice $MODEL_NAME $API_TYPE --service-type $SERVICE_TYPE --persistence $PERSISTENCE
```

to

```dockerfile
CMD seldon-core-microservice $MODEL_NAME $API_TYPE --service-type $SERVICE_TYPE --persistence $PERSISTENCE
```

**Comment by cliveseldon** [comment]
Why do you think the `exec` is rogue?

**Comment by masonlr** [comment]
Apologies, this is a false alarm. 

I can't reproduce, but was getting an error similar to "command not found" for exec, it may have been due to my base docker image. Testing this now with `python:3.7-slim` and `python:3.7-slim-buster` and there is no issue.

I confused docker exec with the bash exec builtin, and assumed that a docker exec command had been pasted in (retaining the exec) in the process of writing the docs.
