### ISSUE TITLE
"puid" when sent in request is not returned in response from python wrapper service. However in case of external api it is returned as is

### ISSUE THREAD

**Issue by klalit** [SeldonIO/seldon-core#765]
``` {"meta": {"puid":"1234"}, "data":{"ndarray":[1,2,3]}}```

in python wrapper response meta is blank

```{"meta":{}}```

in engine response meta contains puid

```{"meta": {"puid":"1234"}}```

**Comment by cliveseldon** [comment]
Do you mean for local internal API calls the puid is not transfered to response. Its true this is done in the engine at present so only happens when running as a full graph.

**Comment by cliveseldon** [comment]
You can add your own meta() method to add response meta data at present.

**Comment by klalit** [comment]
yes it's in internal api. for passing the meta we'll have to implement ```predict_raw```. With ```predict(X,feature)``` i cannot add back the puid. i'm not using graph deplo
