### ISSUE TITLE
seldon container engine sidecar java process should run with '-server' setting

### ISSUE THREAD

**Issue by pisymbol** [SeldonIO/seldon-core#781]
Currently, seldon container engine's JVM runs with somewhat limited memory constraints in client mode. Given that the engine runs in effect as a server process, why not run it with the '-server' option?

From the doc:

"Although the Server and the Client VMs are similar, the Server VM has been specially tuned to maximize peak operating speed. It is intended for executing long-running server applications, which need the fastest possible operating speed more than a fast start-up time or smaller runtime memory footprint."

Source: https://www.oracle.com/technetwork/java/whitepaper-135217.html

**Comment by cliveseldon** [comment]
Fixed by https://github.com/SeldonIO/seldon-operator/pull/55

**Comment by pisymbol** [comment]
Thank you!
