### ISSUE TITLE
javaopts -Xmx throws error

### ISSUE THREAD

**Issue by OrBarda** [SeldonIO/seldon-core#784]
Hi,
javaopts has something wrong, when I'm trying to set seldon.io/engine-java-opts: "-Xmx2G" I get the following:
![image](https://user-images.githubusercontent.com/15226665/62869352-5be75080-bd20-11e9-9aeb-c15cfd858e32.png)
Here's the deployment file:
![image](https://user-images.githubusercontent.com/15226665/62869416-7e796980-bd20-11e9-943c-edace8cdf6bb.png)

**Comment by cliveseldon** [comment]
This is a limitation of annotations it seems in apps.Deployment checks. The current operator allows those to be specified at the top level but we may need to rethink this. See https://docs.seldon.io/projects/seldon-core/en/latest/graph/annotations.html#service-orchestrator

Longer term we will move to a Go executor to replace the Java.
