### ISSUE TITLE
Graph with epsilon greedy router sometimes fails on first request

### ISSUE THREAD

**Issue by Maximophone** [SeldonIO/seldon-core#80]
The graph can be found in [notebooks/resources/epsilon_greedy.json](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/resources/epsilon_greedy.json)

When the graph has just been deployed and a first request is sent, it takes a long time and sometimes fails. The second request onward works fine.

When looking into the microservice logs it appears that the request was sent four times to the router and successive models. The issue can be reproduced by following the epsilon greedy example notebook:
notebooks/epsilon_greedy.ipynb

**Comment by cliveseldon** [comment]
Should be fixed now by MAB updates.
