### ISSUE TITLE
Create wrapper for PyTorch models

### ISSUE THREAD

**Issue by ahousley** [SeldonIO/seldon-core#82]
There are issues to create wrappers for R and Spark, so adding PyTorch here too as it was raised the [community Slack](https://join.slack.com/t/seldondev/shared_invite/enQtMzA2Mzk1Mzg0NjczLWQzMGFkNmRjN2UxZmFmMWJmNWIzMTM5Y2UxNGY1ODE5ZmI2NDdkMmNiMmUxYjZhZGYxOTllMDQwM2NkNDQ1MGI) earlier today. This would be a great first PR for anyone looking to contribute!

- expose PyTorch models with a thin REST server or gRPC server that respects the internal model API
- Build Docker image

**Comment by jlewi** [comment]
For the Kubeflow 0.3.0 release I think we'd like to flush out our PyTorch story which includes finding a good way to serve PyTorch models.

kubeflow/kubeflow#1117

**Comment by cliveseldon** [comment]
We have an [IBM FfDL Example](https://github.com/IBM/FfDL/blob/master/community/FfDL-Seldon/pytorch-model/README.md). We could close this or work with Kubeflow on a focused example.

**Comment by dsdinter** [comment]
FYI - I am working on a Kubeflow Pytorch example leveraging Seldon.
[Link](https://github.com/kubeflow/examples/pull/274) to the PR.

**Comment by cliveseldon** [comment]
@dsdinter  That's great - we'll follow your updates. Feel free to reach out if there are any questions.

**Comment by cliveseldon** [comment]
Kubeflow example exists. So closing.
