### ISSUE TITLE
How to send data in request with meta field

### ISSUE THREAD

**Issue by lennon310** [SeldonIO/seldon-core#822]
I'm trying to send a json request with `meta` field included, something like `{"data": {"names":...., "ndarray":....}, "meta": {"a": "b"}}` and my predict function looks like

```def predict(
        self, model_input: np.ndarray, features_names: list,
            meta: Dict
    ) -> np.ndarray
```

This works properly with `seldon-core-microservice`, but it seemed not parsing the meta field correctly when I deployed to Kubernetes since the meta only shows me

```{'puid': 'foj1is4926k33j71h6vuuli0uu', 'tags': {}, 'routing': {}, 'requestPath': {}, 'metrics': []}
```

I have to create the meta data by putting my stuff inside one of the above 5 fields in order to get them show up in `predict` correctly, i.e., I have to send the data like

```
{"data": {"names":...., "ndarray":....}, "meta": {"tags": {"a": "b"}}}
```

Is it expected? And is it a correct use case to put extra metadata under `tags` field like this instead of creating customized field by myself?

**Comment by cliveseldon** [comment]
Yes this is correct as the meta field is not an open field but spec-ed under our proto-buffers:

https://github.com/SeldonIO/seldon-core/blob/60c9fd2792fb0133d67868be5a106b9062e5918d/proto/prediction.proto#L40-L46
