### ISSUE TITLE
Create a prepackaged model server for PyTorch Models

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#831]
PyTorch is quite a popular library, adding a prepackaged model server would allow for deploying custom PyTorch models, but would also allow for some of the popular models that are trained using PyTorch. 

For background information, it was attempted to build a model for PyTorch Hub models in #642, but given that some models are too big, it could not be done (and the init containers could not be used either).

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
TorchServe is now available: https://github.com/pytorch/serve
