### ISSUE TITLE
How do I override the default port for the flask application that seldon runs ?

### ISSUE THREAD

**Issue by raul1991** [SeldonIO/seldon-core#848]
I see that it always starts on the default_port = 5000. Is there a way to override this by specifying an env in the docker file ?

**Comment by cliveseldon** [comment]
You can add a port named "http" or "grpc" in your containerSpec. This will then be used rather than the automatic port creation.

**Comment by raul1991** [comment]
so something like this in Dockerfile should work ?

FROM .......
ENV http 9000
CMD .......

**Comment by cliveseldon** [comment]
No you would set it in the kubernetes SeldonDeployment resource. We'll try to provide an example.

**Comment by raul1991** [comment]
Oh alright

**Comment by adriangonz** [comment]
Not quite.

When you set it up at the `Dockerfile`/microservice level the engine has no way to know on which port it is running. In that case, what could happen is that the model's microservice starts listening to requests on port `7070`, but the engine is really expecting it to listen on port `5000`. To avoid these sort of mismatches the best solution is to do it through the `ports` field.

Going into a bit more detail, I think that what happens in reality is that the k8s operator starts the model's microservice overriding the `PREDICTIVE_UNIT_SERVICE_PORT` env variable to make sure that it starts listening on the same port that the engine is expecting it to. So even if you changed it in the `Dockerfile`, it would get overridden by the operator.

Do you have any particular scenario in mind where the `Dockerfile` needs to reflect this as well?

**Comment by raul1991** [comment]
In my company we have created a wrapper around the seldon deployment to facilitate model deployment as a service plus some company specific things/dashboards. It expects me to wrap the model using seldon wrapper and create a docker file out of it. I then upload it to an accessible image repo from it pulls and starts the micro service.

As you said earlier I need to define the port in the seldon deployment spec , I might need to ask the maintainer in our company for that option. To avoid doing the aforementioned I wanted to know my options of overriding it through the docker file or through seldon-core command.


Just to reiterate, I need to override it in the seldon spec only. Right ?

**Comment by adriangonz** [comment]
Yes, I think the best place to change it is on the `SeldonDeployment` resource spec. That way all the different components of the `seldon-core` platform will be aware of the port change.

Out of curiosity, why do you need to change this? It will only affect the communication between Seldon's engine and the micro service.

**Comment by raul1991** [comment]
I understand that seldon is only going to expose me an endpoint so the need
for the port won't ever arise.
Since seldon runs a docker file and uses the env (MODEL) to identify the
python wrapper and run it as web service maybe I could pass another param
specifying a port to it.

I was just curious to know if it could work this way :-)

**Comment by cliveseldon** [comment]
Closing as fixed. Please reopen if more info needed.
