### ISSUE TITLE
Seldon GPU Image with seldon-core 0.4.0 support not available

### ISSUE THREAD

**Issue by adeepsri** [SeldonIO/seldon-core#850]
Current available python base image for Seldon GPU donot have support for seldon-core 0.4.0 .

Image at https://hub.docker.com/r/seldonio/seldon-core-s2i-python3-tf-gpu **version 0.1** pass input to TestModel Class as SeldonMessage proto string which is not compatible with earlier versions where TestModel Class gets dictionary.

This issue is been resolved with seldon-core version 0.4.0 but  base image for GPU is not available.

Please help in upgrading python3 TensorFlow GPU image at https://hub.docker.com/r/seldonio/seldon-core-s2i-python3-tf-gpu to support seldon-core 0.4.0.

**Comment by cliveseldon** [comment]
@adeepsri  can you test seldonio/seldon-core-s2i-python3-tf-gpu:0.12-SNAPSHOT

**Comment by adeepsri** [comment]
sure, will test and let you know.thanks
