### ISSUE TITLE
Custom prepackaged model servers

### ISSUE THREAD

**Issue by OrBarda** [SeldonIO/seldon-core#857]
I have is a predict function that can serve different models, and it is not one of the toolkits that you currently have. I need to be able to build my own toolkit and use it the same way.

**Comment by cliveseldon** [comment]
By this do you mean you want to have a yaml resource file that has the same structure as the existing prepacked servers where you just specify SKLEARN or XGBOOST? But in this case you want a  custom name that uses some predefined image?

If so can you say why this is important as opposed to just specifying the image of your model in the normal PodSpec manner?

**Comment by ryandawsonuk** [comment]
You should be able to set a modelUri and also specify an image for the container. By setting a modelUri an initContainer will be added that downloads the model and puts it in local storage. But the way it is currently implemented the type of prepackaged model server would have to be specified to one of the existing values (which we could change). I believe this is what would need to be changed as [the proposal is to have a server that doesn't correspond to any of the toolkits in the list](https://seldondev.slack.com/archives/C8Y9A8G0Y/p1568191465121100).

**Comment by ryandawsonuk** [comment]
This was implemented under https://github.com/SeldonIO/seldon-core/issues/959
