### ISSUE TITLE
Add options to populate meta data in wrappers foreach API request

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#86]
* Update python wrapper

**Comment by cliveseldon** [comment]
At present the python wrapper does not allow people to pass back meta data.
We should add an option method say ```def meta()``` which if it exists is called and a user can pass back a dictionary of tags that will be placed in https://github.com/SeldonIO/seldon-core/blob/01a104c26824f1b355742d5bd4f8e3ba5ac86ab1/proto/prediction.proto#L38

**Comment by cliveseldon** [comment]
Each of the _microservice.py modules will need to be updated to add this functionality in https://github.com/SeldonIO/seldon-core/tree/master/wrappers/python

**Comment by hjarraya** [comment]
`meta` data should be added to the already existing one.

**Comment by cliveseldon** [comment]
Available now.
