### ISSUE TITLE
Default values of metrics missing in /feedback API for Python wrapper

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#861]
As mentioned by @jklaise in #847, 'default values of metrics were missing [for the /feedback API], i.e. if a metric has a value of 0, protobuf conversion interprets it as missing and returns the metric e.g. as {"key":"accuracy", "type": "GAUGE} when it should be {"key":"accuracy", "type": "GAUGE, "value": 0}, this will need to be fixed for the /send-feedback endpoint too for the stateful metrics.'

**Comment by cliveseldon** [comment]
Fixed by PR- reopen if issue.
