### ISSUE TITLE
Integrate GPU Seldon Core Image into Build Scripts

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#868]
The current GPU build is sitting on its own in https://github.com/SeldonIO/seldon-core/tree/master/wrappers/s2i/python-gpu/python-gpu

 * This needs to be integrated in the core https://github.com/SeldonIO/seldon-core/tree/master/wrappers/s2i/python folder
 * Needs to set same version as used in the scripts there and be included in build scripts
 * Needs to ensure it uses same version of Tensorflow as main python build

Initial partial fix started in #867

**Comment by JoelH96** [comment]
#1074
