### ISSUE TITLE
Dynamic Engine version support at Seldon operator

### ISSUE THREAD

**Issue by yufengshan** [SeldonIO/seldon-core#871]
Based on the understanding of the current code (0.4.0), the engine is an environment variable of Seldon operator. Whenever a SeldonDeployment is deployed, the engine defined at the ENV is used for the deployment pod. Every deployment that uses this operator will have the same engine.  Is there a way that the SeldonDeployment can specify an Engine version? I mean different SeldonDeployment can use different Engine version while still share the Operator. For example,  let's say the default environment variable configured engine version is 0.4.0 and the new version I plan to test is 0.4.1. If I could specify an Engine version at my SeldonDeployment, my specific deployment pod uses 0.4.1 and other SeldonDeployments still use the configured 0.4.0. The benefit of using dynamic Engine version can facilitate engine customization testing/development at customer deployment without affecting the operation.

**Comment by cliveseldon** [comment]
Partly solved via #1142

**Comment by cliveseldon** [comment]
With the PR https://github.com/SeldonIO/seldon-core/pull/1142 you can install a seldon operator in a single namespace or one that works on on SeldonDeployments with a given `seldon.io/controller-id` label. This way you could test updates to the engine which always go in lock-step with the Operator releases. I will add a fixes to this PR. Feel free to comment.
