### ISSUE TITLE
Enable Storage.py to be able to download from URL file

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#883]
Currently the Storage.py functionality encompasses s3, Azure bucket, Google bucket and local filestore.

The scope of this issue is to enable the Storage.py interface to be able to handle downloads of files through URL HTTP file downloads.

An example would be a link such as `https://website.com/file.tar.gz`

**Comment by cliveseldon** [comment]
You might want to update to latest storage.py from kfserving if useful as well: https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/storage.py

**Comment by axsaucedo** [comment]
Closing and moving to #1028
