### ISSUE TITLE
Model initializer does not work with S3

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#885]
This was fixed for Kfserving in the main repo with https://github.com/kubeflow/kfserving/issues/213, but it seems the issue still exists when using the pre-packaged model server

**Comment by axsaucedo** [comment]
@cliveseldon woudl this require updating to the latest Storage.py file from KFServing?

**Comment by cliveseldon** [comment]
Yes we should stay aligned with Storage.py in kfserving

**Comment by cliveseldon** [comment]
Needs to be retested

**Comment by cliveseldon** [comment]
Explore other libraries to replace kfserving library.

**Comment by adriangonz** [comment]
[Apache `libcloud`](https://github.com/apache/libcloud) could be a good alternative worth exploring. One of its caveats is that it may support too many things though.

**Comment by axsaucedo** [comment]
moving discussion into #1028. Stil keeping open as this is still an issue

**Comment by axsaucedo** [comment]
Currently a PR has been opened to be able to provide default access to public S3 files https://github.com/kubeflow/kfserving/pull/589

**Comment by axsaucedo** [comment]
As a current fix, it's possible to circumvent this by creating a secret in the same way as the Seldon Docs suggest, adding an S3_ENDPOINT key with the value "s3.amazonaws.com".

**Comment by axsaucedo** [comment]
The change has been landed in the KFServing repo - @cliveseldon @ryandawsonuk  what would be the best way to reflect that change into the initContainer we use? Would there be a way to do it before the next KFrelease? Or when is the next release?

**Comment by cliveseldon** [comment]
> The change has been landed in the KFServing repo - @cliveseldon @ryandawsonuk what would be the best way to reflect that change into the initContainer we use? Would there be a way to do it before the next KFrelease? Or when is the next release?

Only if we create our own image and use that in Operator I think?

**Comment by axsaucedo** [comment]
Got it! Ok, I think we can use the walkaround until the new KFServing image comes out if we don't want to go through creating a new image

**Comment by ryandawsonuk** [comment]
I guess https://github.com/kubeflow/kfserving/pull/589 is the fix (just linking for reference)

**Comment by axsaucedo** [comment]
Correct. Closing this as it's now addressed in the next version of kfserving, and we'll be diving further in #1028.
