### ISSUE TITLE
Helm Upgrade Process

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#890]
Check upgrades between versions have a documented process and has tests.

**Comment by ryandawsonuk** [comment]
I just tried doing a helm upgrade from 0.4.2-SNAPSHOT to 0.5.0-SNAPSHOT

The CRD did momentarily disappear so my watch of `kubectl get sdep -w` was momentarily broken. However, the Pods all kept running and the Deployments stayed up. They all went through a normal rolling update and serve predictions fine.

**Comment by ryandawsonuk** [comment]
I just tried this again. This time I did the install with:
```
helm install seldon-core-operator --name seldon-core --repo https://storage.googleapis.com/seldon-charts --set usageMetrics.enabled=true --namespace seldon-system --version 0.4.1 --set istio.gateway="kubeflow-gateway.kubeflow.svc.cluster.local" --set istio.enabled="true" --set engine.logMessagesExternally="true"
```
I then tried to upgrade to master by running the following from the examples/centralized-logging/ dir:
```
helm upgrade --install seldon-core ../../helm-charts/seldon-core-operator/ --namespace seldon-system --set istio.gateway="kubeflow-gateway.kubeflow.svc.cluster.local" --set istio.enabled="true" --set engine.logMessagesExternally="true"
```
Unfortunately that resulted in the pods going down and `kubectl get sdep` then failed with `Error from server (NotFound): Unable to list "machinelearning.seldon.io/v1alpha3, Resource=seldondeployments": the server could not find the requested resource (get seldondeployments.machinelearning.seldon.io)`. I had to delete the helm release and install again from scratch to get it working.

**Comment by ryandawsonuk** [comment]
The best I've been able to do is the below but it does result in a window of downtime.
```
helm install seldon-core-operator --name seldon-core --repo https://storage.googleapis.com/seldon-charts --set usageMetrics.enabled=true --namespace seldon-system --version 0.4.1 --set istio.gateway="kubeflow-gateway.kubeflow.svc.cluster.local" --set istio.enabled="true" --set engine.logMessagesExternally="true"
<INSTALL SOME SDEPS, WAIT FOR PODS AND WATCH>
kubectl delete crd seldondeployments.machinelearning.seldon.io
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io mutating-webhook-configuration -n seldon-system
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io validating-webhook-configuration -n seldon-system
helm upgrade --install seldon-core ../../helm-charts/seldon-core-operator/ --namespace seldon-system --set istio.gateway="kubeflow-gateway.kubeflow.svc.cluster.local" --set istio.enabled="true" --set engine.logMessagesExternally="true"
<REINSTALL THE SDEPS>
```

**Comment by axsaucedo** [comment]
Here are some notes from our meeting discussing different types of "upgrades" that can be supported, subject to re-scoping as we decide which one would be more feasible to start with, as it may actually be a more iterative approach:

Different types of "handling versions" of Seldon Core across clusters:
* Only able to install one operator globally in the cluster
* Able to install one operator globally in the cluster and restrict with RBAC towards specific namespaces
* Able to install an operator in a single namespace, but all have to be same CRD version
* Able to install multiple operators with multiple different CRDs, but leveraging a central / backwards compatible CRD
* Able to restrict an operator to look after specific Seldon Deployments that have specific labels

*Disjoin to this, it is the ability to do rolling upgrades of each single operator and backwards compatibility for all the deployed models.*

Action points: 
* Test Upgrading from 0.5.0 to 0.5.1
* Scope work as deliverable task
* Explore feasibility of operators that can have access across multiple namespaces 
* Take what we’ve discussed and convert into tasks
* Scope work for integration tests that run rolling updates with models

As a heads up, it was pointed out by @cliveseldon that you cannot have multiple versions of CRDs, but you can have a backwards compatible CRD. He pointed to the kubebuilder book to an example of how this can be achieved with a central CRD that interfaces with different versions of CRDs.

**Comment by adriangonz** [comment]
@ryandawsonuk I just found out that the `v0.4.1` charts specified a version `v1alpha3` of the CRD: https://github.com/SeldonIO/seldon-core/blob/e7585bb8c0220a559a18ae3b32724c6f7916f11e/helm-charts/seldon-core-operator/templates/crd.yaml#L3213-L3218

This version got them removed in `v0.5.0`: https://github.com/SeldonIO/seldon-core/blob/945731316b745825786e9a3b8fce422a1e8523e2/helm-charts/seldon-core-operator/templates/customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml#L3727-L3729

The error during the upgrade to `v0.5.0` (and onwards) seems to point to this missing `v1alpha3`. I'm still not sure on how does Kubernetes treat these versions. Should we try to "phase out" `v1alpha3` by setting `served: false` above?

**Comment by cliveseldon** [comment]
Yes, that was a mistake the v1alpha3 got into a release. I'm not sure if we want to add this back in now that we have removed it in 0.5.x ?

**Comment by adriangonz** [comment]
@cliveseldon it seems to break the upgrade path from `v0.4.1` to `v0.5.0+`. We could add it as a "non-served version" so that Kubernetes doesn't think it has suddenly disappeared?

I'm gonna run a couple tests first to see if that actually solves the issue @ryandawsonuk described above.

**Comment by adriangonz** [comment]
As an update on this, it seems that `v0.4.1` stores the models as `v1alpha3` regardless of having `storage: false` set:

```yaml
apiVersion: machinelearning.seldon.io/v1alpha3
kind: SeldonDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"machinelearning.seldon.io/v1alpha2","kind":"SeldonDeployment","metadata":{"annotations":{},"name":"sklearn","namespace":"seldon"},"spec":{"name":"iris","predictors":[{"graph":{"children":[],"implementation":"SKLEARN_SERVER","modelUri":"gs://seldon-models/sklearn/iris","name":"classifier"},"name":"default","replicas":1,"svcOrchSpec":{"env":[{"name":"SELDON_LOG_LEVEL","value":"DEBUG"}]}}]}}
  creationTimestamp: "2019-11-26T17:34:19Z"
  generation: 1
  name: sklearn
  namespace: seldon
  resourceVersion: "2051"
  selfLink: /apis/machinelearning.seldon.io/v1alpha3/namespaces/seldon/seldondeployments/sklearn
  uid: 571caa4e-8e64-4d98-8559-363038cd1eee
...
```

**Comment by adriangonz** [comment]
It seems that Kubernetes always tries to [operate with the most recent version according to their naming convention](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#version-priority). Therefore, by default, it will try to use `v1alpha3`, even when it's not the `storage` version.

This is at least what I get from `kubectl get sdep`. The only way to get the deployed resources as `v1alpha2` is to fetch them explicitly as `kubectl get sdep.v1alpha2.machinelearning.seldon.io`.

Based on this, I think that the cleanest solution to ensure a safe upgrade path is to keep the `v1alpha3` as it was on `v0.4.1`. This would be just a temporary solution until we release version `v1`. 

What are your thoughts on this @ryandawsonuk @cliveseldon?
