### ISSUE TITLE
OSS-11: Separate engine requires the cluster domain to be ".svc.cluster.local." to work

### ISSUE THREAD

**Issue by phsiao** [SeldonIO/seldon-core#891]
But it is not a good assumption.  The routing would not work if separate engine is configured and the cluster domain suffix is not "svc.cluster.local".

**Comment by cliveseldon** [comment]
Is there a k8s standard way to find cluster domain prefix in use?

**Comment by phsiao** [comment]
I am not aware of any.  Some suggested parsing the pod's resolv.conf file if it is setup to use ClusterFirst dns policy but I don't know how reliable that is.

**Comment by cliveseldon** [comment]
I think i'm going to push this to 1.1 as I'm not clear of the best and required way to fix. Happy to fix if a particular use case comes up and we can understand how the cluster was setup to change the assumption from `svc.cluster.local`.

**Comment by cliveseldon** [comment]
Maybe a configurable annotation in operator

**Comment by cliveseldon** [comment]
please reopen if still an issue with latest release
