### ISSUE TITLE
Seldon Client is not passing binary data field properly with REST

### ISSUE THREAD

**Issue by lennon310** [SeldonIO/seldon-core#897]
I'm using the [OpenAPI](https://github.com/SeldonIO/seldon-core/blob/master/openapi/engine.oas3.json) that Seldon provides to generate the Java client used in sending predict request to the Seldon model.

I'm using s2i to create the image, and pulling it in deployment. Looks like I have to set GRPC in both `API_TYPE` in environment and model endpoint type in the deployment yaml file in order to wrap binary JSON data in SeldonMessage request. If I set REST to both files, the binData field in seldon-core is empty (I printed the `binData` field in `predict_raw` to verify this). 

Is it a bug?

My Java client code in wrapping/sending the request:

```
final ObjectMapper mapper = new ObjectMapper();
final byte[] data = mapper.writeValueAsBytes(pojo);
final SeldonMessage request = SeldonMessage.builder().binData(data).build();
final SeldonMessage response = api.predictWithOptions(request....);
```

**Comment by axsaucedo** [comment]
As you can remember from #739 We had to implement a non-trivial change to support "proxy servers" and increase speed for 0.4.0, which required us to handle some of these points that were previously handled automatically by the proto object serialisation and deserialisation.

The handling of binary data was a point that we discussed in the PR on how to handle, and currently it was modified this way by design (as per some of the tests defining this functionality explicitly https://github.com/SeldonIO/seldon-core/blob/ed63ed736cc6911b90cd2be7bd7b572cf66c33ef/python/seldon_core/utils.py#L520)

This change only came with the release to 0.4.1, and given we're currently on the roadmap towards 1.0 on November, we're keen to get insights on what would be the ideal way to handle this, as beyond 1.0 we will be planning to minimise changes to ensure backwards compatibility with other versions to ensure maturity of the API

**Comment by axsaucedo** [comment]
What is the request you are currently sending? Can you show the steps to reproduce? Thank you @lennon310

**Comment by lennon310** [comment]
@axsaucedo I'm having a POJO class created, converted to byte array, and sent in request.

```
@ToString
@AllArgsConstructor
public class SeldonModelInputDataPOJO
{
    @Getter
    @Setter
    private List<String> featureNames;

    @Getter
    @Setter
    private List<List<Object>> modelInput;
}
```

My model class 

```

class HHMlflowArtifactBinaryModel:
    """
    To convert class to a image, run
    s2i build -E environment_artifact . \
    seldonio/seldon-core-s2i-python3:0.12-SNAPSHOT \
    sem-docker.maven.dev.tripadvisor.com/mlflow_prehac_artifact_model:0.3
    """

    def __init__(self) -> None:
        self.loaded = False

    def load(self) -> None:
        self.pyfunc_model = pyfunc.load_model("model")
        self.loaded = True

    def predict_raw(
        self, msg: prediction_pb2.SeldonMessage
    ) -> prediction_pb2.SeldonMessage:
        if not self.loaded:
            self.load()

        binData = msg.binData
        data = json.loads(binData)
        features_names = data["featureNames"]
        model_input = data["modelInput"]
        if features_names is not None and len(features_names) > 0:
            df = pd.DataFrame(data=model_input, columns=features_names)
        else:
            df = pd.DataFrame(data=model_input)

        ndarray = self.pyfunc_model.predict(df)["score"].to_numpy()
        proto_array = array_to_list_value(ndarray)
        datadef = prediction_pb2.DefaultData(ndarray=proto_array)
        return prediction_pb2.SeldonMessage(data=datadef)
```

I created the model image with s2i and deployed to our Kubernetes, then I ran the Java client code locally.  It works well with GRPC (but the Swagger itself is actually for REST).

**Comment by cliveseldon** [comment]
Just to clarify. Does this work with a curl call? Just want to determine if its the Open API Java is the issue.

**Comment by lennon310** [comment]
@cliveseldon I was seeing this when I tried to curl with binary on REST configuration:

```
E1001 14:51:58.433416 140335298062080 wrapper.py:29] {'status': {'status': 1, 'info': "Invalid request data type: {'me
ta': {'puid': 'mjbp1en27jactl2kvdvhsffj8t', 'tags': {}, 'routing': {}, 'requestPath': {}, 'metrics': []}}", 'code': -1
, 'reason': 'MICROSERVICE_BAD_DATA'}}
I1001 14:51:58.433931 140335298062080 _internal.py:122] 127.0.0.1 - - [01/Oct/2019 14:51:58] "POST /predict HTTP/1.1"
400 -
```

So I guess the swagger should not be the issue.

**Comment by cliveseldon** [comment]
What does the input payload look like? Sounds like its malformed.

**Comment by lennon310** [comment]
I was using
```
final ObjectMapper mapper = new ObjectMapper();
final byte[] data = mapper.writeValueAsBytes(pojo);
``` 

to serialize the pojo file (the class copied above) and used as the payload. I don't think it matters if the payload malformed since at least I should see this payload being passed to `binData` field (as I did in GRPC mode), right?

**Comment by lennon310** [comment]
I was able to pass binData through REST with seldon-core 0.4.1 and seldon-core-s2i-python3:0.12. I guess the old version was having some bugs. 
Closing this ticket.
