### ISSUE TITLE
Support model encryption

### ISSUE THREAD

**Issue by dtaniwaki** [SeldonIO/seldon-core#901]
I have models that include confidential data and want to encrypt them.

There're 2 methods for the encryption: client side and server side. The server side encryption is supported in S3 and Minio, so we can just set [request headers](https://github.com/minio/minio-py/blob/53ad4f3347ecac60dd36c1e4a013488afe0a08e5/examples/put_and_get_encrypted_object.py) on each get request. On the other hand, Minio [doesn't support the client side encryption](https://github.com/minio/minio-hs/issues/60). Maybe, we can have a client encryption support for all the storage types on our side.

I'd like to discuss the necessity of encryption and how we can implement it. I'm happy to implement the feature after the discussion.

**Comment by cliveseldon** [comment]
Can you discuss further the use cases for client-side encryption?
Would this be an addition to the language specific wrappers, such as python?

**Comment by dtaniwaki** [comment]
> Can you discuss further the use cases for client-side encryption?

Do you mean the reason why we need client-side encryption?

> Would this be an addition to the language specific wrappers, such as python?

I was going to add an option of client-side encryption in https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/storage.py, but we can support it in any other languages if necessary.

**Comment by cliveseldon** [comment]
Sounds good. Yes be interested in your use case for client side encryption
for model servers.

**Comment by seldondev** [comment]
Issues go stale after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with `/close`.
/lifecycle stale

**Comment by cliveseldon** [comment]
Please look at [mlserver](https://github.com/SeldonIO/MLServer) and see if this fit your custom needs?
