### ISSUE TITLE
Update python wrapper to pass bytes instead of string

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#909]
We had to implement a non-trivial change to support "proxy servers" in 0.4.0 (https://github.com/SeldonIO/seldon-core/issues/739), which required us to handle some of these points that were previously handled automatically by the proto object serialisation and deserialisation.

The handling of binary data was a point that we discussed in the PR on how to handle, and currently it was modified this way by design (as per some of the tests defining this functionality explicitly https://github.com/SeldonIO/seldon-core/blob/ed63ed736cc6911b90cd2be7bd7b572cf66c33ef/python/seldon_core/utils.py#L520)

Currently the data received can be transformed using:
```
base64.b64decode(X.decode('utf-8')))
```

It was discussed that it would make sense to pass the value to the predict function with this processed with the base64 decode, as it is possible to access the raw in the `predict_raw` function. 

This only needs to be changed in the `seldon_utils.py` file and in the tests.

**Comment by cliveseldon** [comment]
@lennon310 This is the issue for base64 decoding
