### ISSUE TITLE
Seldon Image at "seldonio/seldon-core-s2i-python3-tf-gpu:0.12-SNAPSHOT" not able to find GPU devices

### ISSUE THREAD

**Issue by adeepsri** [SeldonIO/seldon-core#914]
Seldon Image at "seldonio/seldon-core-s2i-python3-tf-gpu:0.12-SNAPSHOT" not able to find GPU devices.

It is happening because image contains both tensorflow as well as tensorflow-gpu library. Image is 
picking tensorflow from seldon-core library.

Fix: I have uninstalled all libraries of tensorflow and re-installed only tensorflow-gpu.

Reference: https://stackoverflow.com/questions/41402409/tensorflow-doesnt-seem-to-see-my-gpu

**Comment by cliveseldon** [comment]
Would we need CPU and GPU versions of the core builder wrappers?

**Comment by JoelH96** [comment]
The "seldonio/seldon-core-s2i-python3-tf-gpu:0.12-SNAPSHOT"  has been updated to only contain tensorflow-gpu.

**Comment by JoelH96** [comment]
Python GPU image and wrapper updated, to ensure only TF-GPU is installed #1011
