### ISSUE TITLE
Model version duplication when rollout times out

### ISSUE THREAD

**Issue by omerdlv** [SeldonIO/seldon-core#916]
Hey,

Following up on the thread we had in Slack; Deploying a new version of a SeldonDeployment and reaching the quota limit for that namespace during the rollout, results in running two versions concurrently, and the rollout process to time out.

We have 2 SeldonDeployments with the same name both configured with 8 replicas.
The rollout process starts and since we hit the quota limit on the 4th pod, 3 new pods and 5 old pods are running at the same time and the K8s rollout process timed out (so no further changes take place).

As we understand this is not the expected behavior of the operator, and so we are raising this issue.

Thanks for your help

**Comment by cliveseldon** [comment]
I think it is working if:

 * The external endpoint is still working and you can send requests that successfully go to the "old" deployment.
 * When you add extra resources to the namespace the Deployment completes and the rolling update completes

Can you verify this @omerdlv and if this is not the case state exactly what is the error. You say the rollout "timed out": can you expand on what this means?

**Comment by OrBarda** [comment]
Hi Clive,

as for the first one we'll try to reproduce the error and see what version the requests are routed to.
As for the second point, after adding resources to the namespace, the rolling update doesn't continue, thus never complete, so we need to use kubectl scale to finish the deployment of the new version and then delete the old deployment.

About the timeout, this is not accurate, what Omer meant was the deployment faces the quota and stops, I'm pretty sure there is no timeout involve in it.

**Comment by cliveseldon** [comment]
@OrBarda Any update on this error from your side?

**Comment by cliveseldon** [comment]
Will close this. Please reopen if you have found the specific use case which you think Kubernetes normal pending/rolling updates is not doing in Seldon.
