### ISSUE TITLE
Models with multiple input types are not supported

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-core#921]
Currently dealing with a model with tabular inputs that contain integers, floats and categorical (string), but given that the SeldonEngine is using Google proto "Values", the arrays seem to be limited to only one data type, even for arrays of arrays. Because of this limitation, it's also not possible to use the json attribute, as it still uses google proto Values, which are also constrained to the same limitation.

**Comment by cliveseldon** [comment]
Strange this works:

```
public class TestJsonUtils {

	@Test
	public void testListValue() throws InvalidProtocolBufferException
	{
		String json = "[1.0,\"hello\"]";
		ListValue.Builder builder = ListValue.newBuilder();
		ProtoBufUtils.updateMessageBuilderFromJson(builder, json );
	}
	
}
```

**Comment by axsaucedo** [comment]
This is due to the conversion into a numpy, so only happens when using `datadef`, if using JSON this is ok (besides the int to float issue) - it also only happens in the Python wrapper, I built a small experiment that shows that predict_raw actually receives the array without conversion https://github.com/axsaucedo/seldon_experiments/tree/master/multiple_inputs.

A solution would be setting the numpy array type as O instead of currently default to string. 

i.e. this:
```
>>> np.array([1,"2",3.0], dtype='O')
array([1, '2', 3.0], dtype=object)
```
Instead of this:
```
>>> np.array([1,"2",3.0])
array(['1', '2', '3.0'], dtype='<U21')
```

Although I would say that this may be something that could be added as a parameter, as I don't think people would always want to have their numpy arrays coerced to 'O', unless they are looking to build it with multiple inputs. It seems this would enable a large number of applications without adding too much complexity.

**Comment by cliveseldon** [comment]
Maybe just add docs to use `predict_raw`
