### ISSUE TITLE
Why seldon chose application/x-www-form-urlencoded as Content-Type instead of application/json when treating predict requests?

### ISSUE THREAD

**Issue by cloga** [SeldonIO/seldon-core#935]
I just find seldon use application/x-www-form-urlencoded instead of application/json, this make me confused, in my opinion , I should use json as data for both input and out datatype.

What pros and cons when treating ml predict requests using application/x-www-form-urlencoded and application/json?

I find some discussion about this：https://stackoverflow.com/questions/11281117/x-www-form-urlencoded-vs-json-http-post

> If the structure of encoded data is guaranteed to be a flat list of name-value pairs, x-www-form-urlencoded seems sufficient. If the structure could be (arbitrarily) complex (e.g. nesting lists or associative arrays), then definitely use JSON.

**Comment by cliveseldon** [comment]
We have both. https://github.com/SeldonIO/seldon-core/blob/174431a404d8a725582a0de6eba1caf6b93512bd/engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java#L140

Please reopen if I misinterpreted you.

**Comment by cloga** [comment]
Thanks @cliveseldon ，How can I post data to predict interface use application/json?
I find the example using application/x-www-form-urlencoded:
`!curl  -d 'json={"data":{"ndarray":[[1,2,3]]}}' http://0.0.0.0:5000/predict`

**Comment by cliveseldon** [comment]
You can use POST as well:
e.g.

```
curl  0.0.0.0:5000/api/v0.1/predict -H "Content-Type: application/json"  -d '{"data":{"ndarray":[[1,2]]}}'
```

**Comment by cliveseldon** [comment]
Which version of Seldon are you using. This has changed.

https://github.com/SeldonIO/seldon-core/blob/52752f0616803a62792d9cb2f83b833fbb600381/python/seldon_core/flask_utils.py#L59

**Comment by axsaucedo** [comment]
@blublinsky I think this is what you had been talking about in regards to the form/json ^

**Comment by cloga** [comment]
![image](https://user-images.githubusercontent.com/1320343/66664842-ea744180-ec7f-11e9-8745-bed5df6f4fcc.png)

I use seldonio/seldon-core-s2i-python3 to build model server image, and find extract_message method in microservice/microservice.py

but now I can't find extract_message method in project:
![image](https://user-images.githubusercontent.com/1320343/66665013-34f5be00-ec80-11e9-94e8-38bc7095b0e4.png)

**Comment by eminemence** [comment]
This is what worked for me:
`curl -v  -s http://localhost:5000/predict -H "Content-Type: application/x-www-form-urlencoded" -d "json={\"data\":{\"ndarray\":[[123,123,123]]}}"`
