### ISSUE TITLE
helm-charts/seldon-core does not have seldon-core

### ISSUE THREAD

**Issue by cyrilthank** [SeldonIO/seldon-core#936]
git clone https://github.com/SeldonIO/seldon-core.git

does not have helm-charts/seldom-core

can you please share which of the below instead is the replacement

seldon-abtest
seldon-core-analytics
seldon-core-controller
seldon-core-crd
seldon-core-kafka
seldon-core-loadtesting
seldon-core-operator
seldon-mab
seldon-od-model
seldon-od-transformer
seldon-openvino
seldon-single-model

**Comment by cliveseldon** [comment]
seldon-core-operator

https://docs.seldon.io/projects/seldon-core/en/latest/workflow/install.html
