### ISSUE TITLE
Custom errors raised in Python microservice don't make it back to the client

### ISSUE THREAD

**Issue by ahutterTA** [SeldonIO/seldon-core#939]
Using a UserCustomException in a Python microservice results in the engine intercepting the exception, changing the status code to a 500 from whatever set by the microservice, and dropping the payload. The engine returns: 
```
{
  "code": 203,
  "info": "org.springframework.web.client.HttpClientErrorException: 400 BAD REQUEST",
  "reason": "Microservice error",
  "status": "FAILURE"
}
```
It should return the payload created by the microservice.

**Comment by axsaucedo** [comment]
@cliveseldon this may be fixed with the executor?
