### ISSUE TITLE
Improve PrePackaged Model Servers

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/seldon-core#959]
* get image from configMap
 * Change prepackaged model name to String to allow any defined server->image mappings in configmap. Fail if no mapping.

**Comment by ryandawsonuk** [comment]
This overlaps with https://github.com/SeldonIO/seldon-core/issues/857

**Comment by ryandawsonuk** [comment]
Everything listed in this issue is now available in master. Could do with adding something to docs.
