### ISSUE TITLE
Enable Storage.py to be able to download from HDFS URL

### ISSUE THREAD

**Issue by tanmaymathur89** [SeldonIO/seldon-core#963]
Currently the Storage.py functionality encompasses s3, Azure bucket, Google bucket and local filestore.

The scope of this issue is to enable the Storage.py interface to be able to handle downloads of files through HDFS URL.

An example would be a link such as http://webhdfs.seldon.com/webhdfs/v1/user/mlflow-tracking-server/1/de848552/artifacts/model

**Comment by axsaucedo** [comment]
This is an interesting request @tanmaymathur89. We have currently several requests to add as extension for the Storage.py (see #883). One thing to bare in mind is that we actually are using the KFServing Storage.py module (https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/storage.py), so any changes to the storage.py should actually be made on that repo, and then we would leverage those changes (to make sure we keep in sync).

IMO it may be interesting to support this if the functionality is not too complex, would you be able to provide a suggestion of the code that would have to be added to support this? @cliveseldon would be able to make the call from there as he's leading the KFServing project

**Comment by axsaucedo** [comment]
Closing and moving to #1028

**Comment by HubSKY** [comment]
does it already support download model file from HDFS

**Comment by cliveseldon** [comment]
We support Rclone now which has [support](https://rclone.org/hdfs/).
