### ISSUE TITLE
Set JSON_SORT_KEYS and JSONIFY_PRETTYPRINT_REGULAR to False by default

### ISSUE THREAD

**Issue by kparaju** [SeldonIO/seldon-core#964]
During our testing we have found out that setting [JSON_SORT_KEYS](https://flask.palletsprojects.com/en/1.1.x/config/#JSON_SORT_KEYS) and [JSONIFY_PRETTYPRINT_REGULAR](https://flask.palletsprojects.com/en/1.1.x/config/#JSONIFY_PRETTYPRINT_REGULAR) to False (in older version of flasks this is True by default) in flask increases performance quite a bit. especially if your payload is huge. 

This is because formatting will create lots of whitespace characters that gets sent through the wire and it takes computational resource. JSON_SORT_KEYS=False will also cause us not to unnecessarily sort keys of the dictionary. 

I can work on this in the next ~week or so.

**Comment by cliveseldon** [comment]
Great. That sounds very useful additions to the python wrapper.
