### ISSUE TITLE
Seldon deployment issue when adding initContainer

### ISSUE THREAD

**Issue by SandhyaaGopchandani** [SeldonIO/seldon-core#968]
I am using initContainer to mount the volume in Seldon deployment file. The deployment is created successfully and the data seems to be mounted properly as well. The container logs do not show any error but the deployment status is not ready yet hence not exposed at the Ambassador endpoint

The deployment status shows: `map[serviceStatus:map[seldon-30431ae882caeb414f589e862388285c:map[httpEndpoint:seldon-30431ae882caeb414f589e862388285c.seldon-models:9000 svcName:seldon-30431ae882caeb414f589e862388285c]] state:Creating]`

**Comment by axsaucedo** [comment]
Thanks for the heads up, can you please provide the steps and config files to reproduce?
