### ISSUE TITLE
/helm-charts/seldon-core not present in seldon-core repository for CICD demo

### ISSUE THREAD

**Issue by vdinesh2461990** [SeldonIO/seldon-core#970]
Hi, I am trying CI/CD demo of seldon-core. while starting the services, I face below issues
1. helm install --kube-context="${KUBE_CONTEXT}" ${SELDON_CORE_DIR}/helm-charts/seldon-core-operator --name seldon-core --set usageMetrics.enabled=true --namespace seldon-system
seldon core operator chart has only seldon-controller-manager. But while checking roll out status it checks for
1. deployment.apps/seldon-core-seldon-apiserver
2. deployment.apps/seldon-core-seldon-cluster-manager
Moreover, in the helm examples "helm install ../helm-charts/seldon-core" - only seldon-core chart has above deploments. However seldon-core chart is missing in seldon-core repository

**Comment by cliveseldon** [comment]
Yes, these lines seem to be outdated:

https://github.com/SeldonIO/seldon-core/blob/174431a404d8a725582a0de6eba1caf6b93512bd/examples/cicd-argocd/watch-rollout-status#L17-L18

**Comment by gsunner** [comment]
Update to the cicd demo now merged in PR #1001
It should fix this and other related issues.

These related repos also updated
https://github.com/SeldonIO/cicd-demo-model-source-files
https://github.com/SeldonIO/cicd-demo-k8s-manifest-files
