### ISSUE TITLE
 Make Helm chart repository available on Helm Hub

### ISSUE THREAD

**Issue by desaintmartin** [SeldonIO/seldon-core#973]
The Helm Hub (https://hub.helm.sh/) provides a way to expose Charts and will be used as the canonical way to search for Charts in Helm 3.

https://github.com/helm/hub/blob/master/Repositories.md

Unfortunately, I can't find the chart in the hub.

It would allow to install Seldon without having to git clone. 

If you would like to do it, I can help setting it up.

**Comment by ryandawsonuk** [comment]
It's at https://hub.helm.sh/charts/seldon/seldon-core-operator

**Comment by ryandawsonuk** [comment]
Totally agree that we should have charts there. If you've any ideas on why it was difficult to find then we'd certainly be interested

**Comment by desaintmartin** [comment]
Oh, I need to improve my search capacity. The UI is misleading, I thought there were only 4 results. Thanks! Closing...
