### ISSUE TITLE
Integration tests for tracing

### ISSUE THREAD

**Issue by adriangonz** [SeldonIO/seldon-core#977]
It would be good to add integration tests to ensure that tracing works properly. From a high-level point of view this means that:

- Traces get pushed to Jaeger both from the engine and from any other component in the inference graph.
- Traces get pushed in the right format, with the engine wrapping all inner requests inside the inference graph. 
- Traces work both with REST and gRPC.

An example of what can be considered a properly working trace on Jaeger's UI can be seen below:

![Working Trace](https://user-images.githubusercontent.com/1577620/67222664-ade5da00-f425-11e9-8dcd-c24e5d04bfee.png)

**Comment by cliveseldon** [comment]
related to #731 ?

**Comment by axsaucedo** [comment]
@adriangonz will have a look at this one to see if it makes sense to move it to 1.2 or keep it in 1.1

**Comment by axsaucedo** [comment]
Reprioritising for 1.1
